### ISSUE TITLE
Move dev tools option

### ISSUE THREAD

**Issue by claytron5000** [TanStack/query#2994]
Sometimes the ergonomics of a button- stuck tool is hard to use. Could there be a button, like in native dev tools to pin the query tool to the sides, or top/ bottom

**Comment by TkDodo** [comment]
Can you be a bit more specific? What is a button-stuck tool please?

i think there are already options to position the devtools differently if that’s what you mean..

**Comment by claytron5000** [comment]
No problem, I probably shouldn't write features requests while walking the dog. 

Currently we can set the position of the flower tool by passing the position parameter:
```
<ReactQueryDevtools position={"top-right"} />
```
That puts the flower trigger in the top right corner. However, the drawer always opens at the bottom.

A user could pass styles and classes in through `panelProps`. And position the r-query devtools where-ever they please.


What I'm thinking is a toggler within the devtools that allows the user to switch the drawer position on the fly. The example I'm thinking of is the layout switcher in Chrome:
![image](https://user-images.githubusercontent.com/5767672/142743719-afaea8bd-6a3d-43d4-9b4e-aa0099bc8a7c.png)

This would allow  a user to reposition the devtool drawer on the fly as they might switch page layouts, or other window sizes.

**Comment by TkDodo** [comment]
❤️ the idea, would you like to add it?

**Comment by claytron5000** [comment]
Yes, I'll work on it.
═════════
Clayton Salem
413-768-8522
═════════

**Comment by salamaashoush** [comment]
@TkDodo  @claytron5000  I could work on this if there is one currently working on it

**Comment by TkDodo** [comment]
@salamaashoush go ahead, I've assigned you to the issue.

**Comment by nirtamir2** [comment]
Hi,
I created https://github.com/nirtamir2/react-query-devtools-extension to solve this problem. It works well in development but I have a little problem with its event when building it for production. You can use it and integrate it back to react query

**Comment by salamaashoush** [comment]
@nirtamir2  this is a pretty cool browser extension, but I am just adding the ability to reposition the current devtools so you don't need to install a browser extension

**Comment by salamaashoush** [comment]
@TkDodo  if you have time could you please have a look at this PR https://github.com/TanStack/query/pull/3678

**Comment by yairEO** [comment]
I would love to be able to hold with the mouse and drag it somewhere else, in case it covers something I want to interact with on the page (or see). It doesn't need to remember the new dragged position after refresh, but simply solve an anecdotal situation
