### ISSUE TITLE
QueryClientConfig is missing type args

### ISSUE THREAD

**Issue by aryzing** [TanStack/query#3352]
### Describe the bug

The type `QueryClientConfig` is missing type args. It is currently defined as

```ts
export interface QueryClientConfig {
    queryCache?: QueryCache;
    mutationCache?: MutationCache;
    defaultOptions?: DefaultOptions;
}
```

and used in the QueryClient [constructor](https://github.com/tannerlinsley/react-query/blob/26b39546cc1f37a3fff1e43515b65e640f532ad6/src/core/queryClient.ts#L65) as

```ts
constructor(config: QueryClientConfig = {}) // ...
```

This makes it impossible to define a typed `config` object with types other than `unknown`.

### Your minimal, reproducible example

Already in bug description

### Steps to reproduce

In bug description

### Expected behavior

Ability to create a typed config with types other than `unknown` used it's porpertyes type args.

```
const defaultOptions: DefaultOptions<ApiError> = {/* ... */};
const queryClient = new QueryClient({ defaultOptions });
```

### How often does this bug happen?

Every time

### Platform

N/A

### react-query version

    "react-query": "3.34.16",

### TypeScript version

    "typescript": "4.6.2",

**Comment by Alcas1** [comment]
Are they worried that we could potentially use a different error type on some queries? My use case is openapi gen client so we internally guarantee an error type of ApiError. I feel like we should be given the option to define this if we need

**Comment by TkDodo** [comment]
can someone please provide a reproduction in https://typescriptlang.org/play ? From the description alone, I don't understand the problem fully.

**Comment by SevenOutman** [comment]
@aryzing Looks like you wish `QueryClientConfig` type to be generic and to take type args because error type is predictable? If I'm understanding you correctly, [this discussion](https://github.com/TanStack/query/discussions/3528#discussioncomment-2592717) has talked about it already.

**Comment by aryzing** [comment]
The discussion proved useful, will close.
