### ISSUE TITLE
useMutation does not fire useEffect when useQuery data is the useEffect dependency

### ISSUE THREAD

**Issue by Jared-Dahlke** [TanStack/query#3596]
### Describe the bug

https://stackoverflow.com/questions/72172769/react-query-usemutation-not-updating-usequery-data

### Your minimal, reproducible example

na

### Steps to reproduce

https://stackoverflow.com/questions/72172769/react-query-usemutation-not-updating-usequery-data

### Expected behavior

https://stackoverflow.com/questions/72172769/react-query-usemutation-not-updating-usequery-data

### Platform

all

### react-query version

3.34.18

**Comment by JaredDahlke** [comment]
@TkDodo  https://codesandbox.io/s/gifted-tu-t3fevm?fontsize=14&hidenavigation=1&theme=dark

**Comment by TkDodo** [comment]
don't mutate input you get from a function?

https://codesandbox.io/s/charming-cloud-gpuluv?file=/src/useTest.js

**Comment by JaredDahlke** [comment]
ah I was just returning the object incorrectly . basic JS error, my bad
