### ISSUE TITLE
Stale refetched queries do not use new authentication headers

### ISSUE THREAD

**Issue by daniboomerang** [TanStack/query#3705]
### Describe the bug

I use `graphql-request` along with `react-query`

I have defined my own hook where I create a new graphql client with the latest JWT token
something like this

```
import { GraphQLClient } from 'graphql-request'
import { getJwtToken } from 'lib/auth/authHelpers'

export const gqlClient = (jwtToken: string): GraphQLClient =>
  new GraphQLClient(String(process.env.NEXT_PUBLIC_GRAPHQL_HTTP_URI), {
    credentials: 'same-origin',
    headers: {
      authorization: `Bearer ${jwtToken}`
    }
  })

export const useGqlQuery = ({ queryHook, variables, options }) => {
  const JWTToken = getJwtToken()
  return queryHook(gqlClient(JWTToken), variables, options)
}

```

I really like the Stale queries refetch defaults, but I have a big issue. 
Whenever the refresh token expires and I update my JWT, my app will mostly fail
With high probability a window focus or a new instance of the query will be mounted, and the query will be called with the cached headers

I have debugged my code. I can see when the query is refetched in the background the correct JWTToken is used to instance `graphql-request` client, however in the devtools/network tab the query contains the previous authentication header, with a wrong JWTToken (old one)

The workaround for this is just disable the refetchOnMount, refetchOnWindowFocus, refetchOnReconnect defaults, but I actually like the background refetch feature. It would be a pity to lose it

Do you have any suggestions? 

Regards

### Your minimal, reproducible example

None

### Steps to reproduce

I can't really provide a production place  to reproduce the issue

### Expected behavior

The stale query refetch should update authentication headers

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Google Chrome Version 102.0.5005.61 (Official Build) (x86_64)

### react-query version

v3.34.8

### TypeScript version

v4.5.4

**Comment by TkDodo** [comment]
I remember discussing this somewhere else. Not sure what the conclusion was, likely everything that should trigger a refetch needs to be part of the query key. Also, nothing I can do without a reproduction.

**Comment by lemonjp** [comment]
I have exact same issue. :(
