### ISSUE TITLE
Change of head branch broke examples at tanstack.com

### ISSUE THREAD

**Issue by mlasevich** [TanStack/query#3734]
### Describe the bug

Example like https://react-query.tanstack.com/examples/simple are unable to load codesandbox because the website expects the branch name to be `master` but it is now `main`

### Your minimal, reproducible example

https://react-query.tanstack.com/examples/simple

### Steps to reproduce

1 Go to https://react-query.tanstack.com/examples/simple
2 Observe Not Found error
3 click on [Open in CodeSandbox](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/simple) link
4 Observe Not Found error
5 Alter URL and replace `master` with `main` 
6 watch it work

### Expected behavior

Expect to point to a working codesandbox by default

### How often does this bug happen?

Every time

### Platform

N/A

### react-query version

N/A

**Comment by TkDodo** [comment]
fixed with 3ebf0d4d77c5c2b88edfa0934ceba71a87c48f69, but not sure why the docs aren't updating.

**Comment by TkDodo** [comment]
Docs are fixed now.
