### ISSUE TITLE
useQuery() does not accept query-options when passed as a variable

### ISSUE THREAD

**Issue by rabengraph** [TanStack/query#3738]
### Describe the bug

Given: Values for `UseQueryOptions` are assigned to a variable. The variable is not explicitly typed.

When passing this variable to `useQuery()` a type error is thrown.

In contrast, when passing the values to `useQuery()` inline, the same values are accepted and `useQuery()` infers the types properly.

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRQK4FMoE8BiqB2AxjMBPgMJkzoAeMANHKgM7pqZZwC+cAZlBBBwA5FHQBDYgFoAjhmzCAsACgVhMs3i90MQgAsAyoJ17g+AOZwAvHHHMsROAAoEKuO7hyOAaXRYAXHAA2ki8EBDcALr0KlyB7Nh4RCRklPjUdAA8bh5BOR4ersoFJR5hEIH4qCAARpj5JVwxxR6RKgB8AJTW7XAACgIgwKwAdGLMEAA2AG7oLnA14lCB5dydKiq0kLB8BMSk+EysABLhANZO3UUNAPQ3cGaTZui2UObV6OnMgQDu0GfMBosNjyLDzLyJfArHT6IwgExmcyMCFYXwBYKhcKBACMUTWGxa7jucDAdmYcGmS2A4hqkxedle73h6UCABMIOhyfgIPA-lAAXAGup8JpPKCAIJvck2JAonBQvgwwzGGCmCzI0FowIhPhYuC4riRbhA1gJMEoyXmZjrVTKLgqIA

### Steps to reproduce

Look at line 20 in the `typescriptlang.org/play` example.

### Expected behavior

Given: Values for UseQueryOptions are assigned to a variable. The variable is not explicitly typed.

When passing this variable to `useQuery()`, 
- useQuery should accept this variable without throwing a type error
- useQuery should infer the types from the values of the variable

### How often does this bug happen?

Every time

### Platform

https://www.typescriptlang.org/play

### react-query version

3.39.1

### TypeScript version

4.7.2

**Comment by TkDodo** [comment]
@artysidorenko could you have a look at that maybe?

**Comment by artysidorenko** [comment]
Hi @rabengraph,

On your line 6 you've specified that your query function must take a query key that's a fixed-length tuple - `[{ foo: number }]`. 

But when you initialise query-options as a variable, TS assumes the query key to be a variable-length array `{ foo: number }[]`, not a tuple (TS always does this, it's why [for example it complains when you try to assign an array literal to an identical typed-tuple](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiAqBXMAbaBeKBtA3lAZgPaEBcUAdogLYBGEATlAL4C6AsAFBrBRULJoycJKgzY8RUlACMzdlwg8+AeWAALBiLRRMuAsTKzWnPlrEr1mgRCA), but [I don't think there's any plans for that to change](https://github.com/microsoft/TypeScript/issues/44309))

I think your best bet to avoid TS complaints but maintain type-safety is to also give your variable a type to give TS a clue that the query key is a tuple not an array. [Like this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRQK4FMoE8BiqB2AxjMBPgMJkzoAeMANHKgM7pqZaPvYDyYJZZnAC+cAGZQIIOAHIo6AIbEAtAEcM2GQFgAULphYw6OABVuWANLoscALxwA2kjEQIALjj5UIAEaYRALr6hsZmGlh8AvhC9uaRpNEAPAQA1vgQAO74jKnpWTn4aZnZpuZWWAB8urqEgvBi6DCEABYAylKNzcD4AOZ2cArMWERwABQIunBTcOoc5R5O4q6B9LrCHuZ4RFGU+NR0iWFz1hUAlHYVcAAKkiDArAB08swQADYAbujjcD4KUB4uCAiU7VHS0SCwcQEYgJJisAASrhSo3OEz0OmmcAA9Fi4N1Xt1jH8et50HtmB4MtAUsxJtMWGxwt9ZtgcPgAY0Wu0QJ1uj1GCzLNYFs5XB4AIyBYGgzE4uBgQZCd5-YAKHyvIlCYmkvaU6lCYBiOBYCCoOA9YCfPHwBRwAxGOlTWrReCCgCCUB6FNK4Xign6SEFbI5TTaHRgXV6AvC80covccElwgCIkdcMZHFG7s9zBB6OEuiAA).

**Comment by chungweileong94** [comment]
Agreed with @rabengraph. 
Or you can create a query key factory that manages the query keys, which also handle type nicely. There's a [good blog article](https://tkdodo.eu/blog/leveraging-the-query-function-context#query-key-factories) from @TkDodo

**Comment by rabengraph** [comment]
Thank you for the input!
The Generic I use in my example is just not correct,
I changing the Generic from
```
QueryFunctionContext<
    [
        {
            foo: number
        },
    ]
>
```
to 
```
QueryFunctionContext<
    ReadonlyArray<
        {
            foo: number
        }
    >
>
```
which fixes the problem.
