### ISSUE TITLE
Next.js example doesn't load

### ISSUE THREAD

**Issue by torinmb** [TanStack/query#3746]
### Describe the bug

If you navigate to the default example for Next.js the code sandbox fails to run correctly: https://react-query.tanstack.com/examples/nextjs

### Your minimal, reproducible example

Code Sandbox

### Steps to reproduce

Go to: https://codesandbox.io/s/github/tannerlinsley/react-query/tree/main/examples/nextjs, or https://react-query.tanstack.com/examples/nextjs

### Expected behavior

expect to see it running. :) 

### How often does this bug happen?

Every time

### Platform

Mac OS 11.3.1, Chrome Version 103.0.5060.53 (Official Build) (x86_64)

### react-query version

current

**Comment by TkDodo** [comment]
I think it has something to do with the checked in `yarn.lock` file. Most other examples don't have that. We've changed the hydrate export so maybe that's that.

I've forked the example and updated the version, then it works fine: https://codesandbox.io/s/nostalgic-swartz-6pdt3l

**Comment by TkDodo** [comment]
This is fixed now
