### ISSUE TITLE
Calling `queryClient.setQueryData` during `onSettled` might cause `onSettled` to be called

### ISSUE THREAD

**Issue by jtomaszewski** [TanStack/query#3780]
### Describe the bug

I have two queries q1 and q2. 

Both of them contain part of data that is the same.

So I defined a `onSettled` callback in both of them. So that when q2 query suceeds, it updates the cache of q1, and vice-versa, when q1 query succeeds, it updates the cache of q2.

Unfortunately I'm meeting an infinite loop. It seems like `onSettled` callbacks get called infinitely:

![image](https://user-images.githubusercontent.com/1862580/177581344-b4e89a4b-22b6-494b-b8d4-5ab24e15c23d.png)

It's not something I'd expect, as the documentation of `onSettled` says it shouldn't be invoked after cache update (in contrast to `onSuccess`).

Is there anything I'm missing?

### Your minimal, reproducible example

not yet, but I might create one soon

### Steps to reproduce

see description

### Expected behavior

see description

### How often does this bug happen?

Every time

Note: It might seem to happen only when using `useInfiniteQuery`, during the last page fetch (when `getNextPageParam` returns undefined).

### Platform

Chrome, OS X
react 17.0.2

### react-query version

3.39.1

**Comment by jtomaszewski** [comment]
It might seem to happen only when using `useInfiniteQuery`, during the last page fetch (when `getNextPageParam` returns undefined).

**Comment by TkDodo** [comment]
In v4, setQueryData does no longer call callbacks, so this is likely fixed. Can you please try with v4?

**Comment by jtomaszewski** [comment]
Yeah, it seems to be fixed in v4. I guess I'll stay with v4 then ;o
