### ISSUE TITLE
Unable to install Tanstack Query

### ISSUE THREAD

**Issue by bootrino** [TanStack/query#3793]
### Describe the bug

Trying to install results in an error.

npm i "@tanstack/react-query"

### Your minimal, reproducible example

?

### Steps to reproduce

npm i "@tanstack/react-query"
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tanstack%2freact-query - Not found
npm ERR! 404
npm ERR! 404  '@tanstack/react-query@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

### Expected behavior

It installs.

### How often does this bug happen?

Every time

### Platform

MacOS, Linux

### react-query version

latest

### TypeScript version

n/a

**Comment by stelmakhivan** [comment]
I was successful with `npm i react-query@v4.0.0-beta.23` ...

**Comment by daniel-anh-nguyen** [comment]
Can reproduce.

**Comment by vslepkan** [comment]
Package not found
https://bundlephobia.com/package/@tanstack/react-query

**Comment by olan-go2** [comment]
Having the same issue... the package is not available via npm

**Comment by TkDodo** [comment]
Duplicate:
- https://github.com/TanStack/query/issues/3790

**Comment by aouaiti** [comment]
In my case it happened because i installed the dev tools before the react query, all i did was deleting the node_modules file, then "npm i", finally i installed it
