### ISSUE TITLE
docs: codesandbox not loading

### ISSUE THREAD

**Issue by theskillwithin** [TanStack/query#3812]
### Describe the bug

codesandbox examples not loading in docs

### Your minimal, reproducible example

https://tanstack.com/query/v4/docs/examples/react/simple

### Steps to reproduce

go to docs

### Expected behavior

that it works

### Platform

macOS,= chrome

### react-query version

idk

### Additional context

https://tanstack.com/query/v4/docs/examples/react/simple

**Comment by TkDodo** [comment]
Thanks, we're aware. Release is coming really soon to fix this.
