### ISSUE TITLE
isDataEqual is not explained in Docs

### ISSUE THREAD

**Issue by airman5573** [TanStack/query#3813]
### Describe the bug

I'm reading useQuery API spec in [docs](https://tanstack.com/query/v4/docs/reference/useQuery).

I found that `isDataEqual` is not explained in that docs.  

### Your minimal, reproducible example

https://tanstack.com/query/v4/docs/reference/useQuery

### Steps to reproduce

1. Go to https://tanstack.com/query/v4/docs/reference/useQuery
2. Command + f
3. type `isDataEqual`

### Expected behavior

As a docs reader, the `isDataEqual` should be defined in docs.

### Screenshots or Videos

No video

### Platform

- OS: MacOS

### react-query version

4

### TypeScript version

v4.7.4

### Additional context

CHeck Please!

**Comment by TkDodo** [comment]
would you like to add an explanation?

**Comment by airman5573** [comment]
> would you like to add an explanation?

OK, I will
