### ISSUE TITLE
Failed to compile; "React Example: Auto Refetching"

### ISSUE THREAD

**Issue by delfincortesb** [TanStack/query#3837]
### Describe the bug

![image](https://user-images.githubusercontent.com/66261899/179381199-321e98b6-8aa5-463f-aa8a-ae692f84d4d6.png)

> ./pages/index.js
Module not found: Can't resolve '@tanstack/react-query' in '/sandbox/pages'

### Your minimal, reproducible example

https://codesandbox.io/s/github/tanstack/query/tree/beta/examples/react/auto-refetching?from-embed

### Steps to reproduce

1. Got to CodeSandbox

### Expected behavior

Failed to compile.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/66261899/179381216-849adb5f-9b30-4cd7-814d-1d2f33c5be61.png)

### Platform

- Browser 

### react-query version

^4.0.0-beta.1

**Comment by scpedicini** [comment]
Probably related, but the homepage react example for codesandbox doesn't seem to work:
![CleanShot 2022-07-17 at 01 23 15](https://user-images.githubusercontent.com/2040540/179386716-678c9ee8-3a32-4196-9b86-d0ab4b1c9fd9.png)

**Comment by TkDodo** [comment]
imports are already changed towards the rebrand, but it hasn't been released yet. see:
- https://github.com/TanStack/query/issues/3790#issuecomment-1185484427
