### ISSUE TITLE
Could not find a declaration file for module `@tanstack/react-query`

### ISSUE THREAD

**Issue by kkirsche** [TanStack/query#3847]
### Describe the bug

react-query 4.0.0 does not seem to correctly expose type information.

```
Could not find a declaration file for module '@tanstack/react-query'. '/Users/path/to/project/ui/node_modules/@tanstack/react-query/build/cjs/packages/react-query/src/index.js' implicitly has an 'any' type
```

### Your minimal, reproducible example

https://codesandbox.io/s/elastic-sound-pe5253

### Steps to reproduce

Look at red squiggly under import

### Expected behavior

Types should be exposed in such a way that they function as part of the upgrade path, or a migration path is provided to correctly handle the updated types.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="1153" alt="CleanShot 2022-07-18 at 16 51 53@2x" src="https://user-images.githubusercontent.com/947110/179615258-16132962-69a4-478b-bf3c-d73a80dd3d72.png">
<img width="501" alt="CleanShot 2022-07-18 at 16 52 30@2x" src="https://user-images.githubusercontent.com/947110/179615316-debb6daa-351e-494e-9e8a-7943a25952de.png">
<img width="594" alt="CleanShot 2022-07-18 at 16 52 58@2x" src="https://user-images.githubusercontent.com/947110/179615372-c72db380-9369-4f03-a15a-dcedc779c19a.png">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 103.0.5060.114 (Official Build) (x86_64)

### react-query version

v4.0.0

### TypeScript version

v4.7.4

**Comment by kkirsche** [comment]
It’s not solved, closed as a dupe of https://github.com/TanStack/query/issues/3846 so I’m waiting for that issue to be addressed.

**Comment by TheYashJain17** [comment]
did anyone find the solution of this issue as this issue is present till date
