### ISSUE TITLE
Cannot find module '../../../node_modules/use-sync-external-store/shim/index.js'

### ISSUE THREAD

**Issue by mvierssen** [TanStack/query#3848]
### Describe the bug

```
Error: Cannot find module '../../../node_modules/use-sync-external-store/shim/index.js'
Require stack:
- /home/node/app/node_modules/react-query/build/cjs/packages/react-query/src/useSyncExternalStore.js
- /home/node/app/node_modules/react-query/build/cjs/packages/react-query/src/useQueries.js
- /home/node/app/node_modules/react-query/build/cjs/packages/react-query/src/index.js
```

### Your minimal, reproducible example

Using a Linux terminal with NodeJS installed

### Steps to reproduce

1. Create and change to new directory
2. Run `npm install react-query`
3. Create file `test.mjs` with the following:
```js
import {QueryCache, QueryClient, QueryClientProvider, Hydrate} from "react-query";
```
4. Run: `node test.mjs`

### Expected behavior

I expect to not get a 'MODULE_NOT_FOUND' error.

### How often does this bug happen?

Every time

### Platform

- Linux
- Node.js v18.5.0

### react-query version

v4.0.0

### Additional context

This also happens when using `@tanstack/react-query` instead of `react-query`

**Comment by bombillazo** [comment]
These packages have been extracted to their own package and no longer under the `react-query` package:

```
    @tanstack/query-core@4.0.2
    @tanstack/query-async-storage-persister@4.0.2
    @tanstack/query-broadcast-client-experimental@4.0.2
    @tanstack/query-sync-storage-persister@4.0.2
    @tanstack/react-query@4.0.2
    @tanstack/react-query-devtools@4.0.2
    @tanstack/react-query-persist-client@4.0.2

```
