### ISSUE TITLE
Module '"@tanstack/react-query"' has no exported member 'QueryClient'

### ISSUE THREAD

**Issue by Paultje52** [TanStack/query#3855]
### Describe the bug

When trying to import `QueryClient`, TypeScript says that `@tanstack/react-query` doesn't export `QueryClient`. The QuickStart guide clearly mentiones that `QueryClient` needs to be imported (https://tanstack.com/query/v4/docs/quick-start).

### Your minimal, reproducible example

It's just one line: `import { QueryClient } from "@tanstack/react-query";`

### Steps to reproduce

1. Install `@tanstack/react-query`
2. Try to import `QueryClient`

### Expected behavior

`QueryClient` should be available

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/31313717/179708472-cf7e624c-439d-4256-8dc6-b6868f62ea2e.png)

```ts
Type error: Module '"@tanstack/react-query"' has no exported member 'QueryClient'.

  3 | import { Fragment, useState } from "react";
  4 | import Head from "next/head";
> 5 | import { QueryClient } from "@tanstack/react-query";
    |          ^
  6 | 
  7 | function MyApp({ Component, pageProps }: AppProps) {
  8 |   // const [ queryClient ] = useState(() => new QueryClient());
```

### Platform

Every platform

### react-query version

4.0.3

### TypeScript version

4.7.4

### Additional context

Why are there so many problems regarding TypeScript? Yesterday I couldn't use react-query either, because the typings weren't exported. How can I be confident that no more issues occur, when two massive oversights regarding TypeScript already happend?

**Comment by Karol-Perec** [comment]
Try to reinstall your node_modules, this issue should not appear since 4.0.3

**Comment by TkDodo** [comment]
We can also see in the official examples that this works now:

https://codesandbox.io/s/github/tanstack/query/tree/main/examples/react/simple

**Comment by Paultje52** [comment]
> We can also see in the official examples that this works now:
> 
> https://codesandbox.io/s/github/tanstack/query/tree/main/examples/react/simple

The official example isn't working either when converted to TypeScript.
![image](https://user-images.githubusercontent.com/31313717/179728892-d483c0cf-4497-49f4-9cfc-7db57ed743a7.png)



> Try to reinstall your node_modules, this issue should not appear since 4.0.3

I deleted the entire node_modules directory and reinstalled it using yarn. I checked the `package.json` in `node_modules/@tanstack/react-query/package.json` and it says version `4.0.3`. So this issue is still present in the current version.

**Comment by TkDodo** [comment]
here is a perfectly fine typescript codesandbox with version 4.0.3:

https://codesandbox.io/s/tanstack-query-example-react-basic-typescript-forked-t3smwg?file=/src/index.tsx

**Comment by goodluckgod** [comment]
![image](https://user-images.githubusercontent.com/42766561/179736815-56051d91-1f33-44f2-b6c4-0110bd06c365.png)

There is nothing exported called "QueryClient", I am using 4.0.3 too..

**Comment by TkDodo** [comment]
@goodluckgod it's re-exported from the query core via: `export * from '@tanstack/query-core'`

please show a reproduction (not a screenshot) that we can take a look at.

**Comment by Paultje52** [comment]
After restarting my pc everything seems to be working fine, strange. Maybe it's some kind of caching issue. Anyways, everything works now. Thanks for your help!

**Comment by Karol-Perec** [comment]
> After restarting my pc everything seems to be working fine, strange. Maybe it's some kind of caching issue. Anyways, everything works now. Thanks for your help!

It happens that Typescript won't refresh when you install/update packages. If it happends, run _Typescript: Restart TS Server_ command in your IDE.

**Comment by Patchrik** [comment]
I'm on WSL 2, VS Code, and I'm having the same issues. Under package.json I have`"@tanstack/react-query": "^4.0.8",`

`import { QueryClient, QueryClientProvider } from '@tanstack/react-query';`
Gives me the error "Module '"@tanstack/react-query"' has no exported member 'QueryClient'.ts(2305)"

So far I have restarted VS Code, TS server, and WSL. Deleted and reinstalled node-modules, restarted the PC. Not sure what to try next, would love any ideas or help.

**Comment by TkDodo** [comment]
Hmm, do you still have a copy of  react-query in your node_modules? What does packages.lock say?

**Comment by maapteh** [comment]
For me 4.0.10 fixed it eventually, i first removed react-query did yarn then yarn add @tanstack/react-query which installed version 4.0.10 and all my typing errors are gone

**Comment by TkDodo** [comment]
glad to hear that

**Comment by Patchrik** [comment]
Alright I finally found the issue. My co worker had also installed react-query that I missed when reading through the project's packages. So I had a new and old version on the project, versions 4.0.0 & 4.0.8. I removed both of them from the lock, packages, and node modules did a fresh install and everything is now working as it should.

Thank you for your help!

**Comment by TkDodo** [comment]
everybody wants to install react-query 😂

**Comment by HabibMollah** [comment]
I was getting this error when trying to import `QueryClient` after installing with `pnpm add @tanstack/react-query` in our Next.js project.
The error disappeared after setting `"preserveSymlinks"` to `false` in `tsconfig.json`:
```json
{
  "compilerOptions": {
    // other options...
    "preserveSymlinks": false
  }
}
```
But it was failing to build with this tsconfig.
The issue was fixed after I installed `@tanstack/query-core` manually by running `pnpm add @tanstack/query-core`.
But isn't `@tanstack/query-core` supposed to be installed automatically when someone installs `@tanstack/react-query`?

**Comment by TkDodo** [comment]
yes, the query core is a dependency of react-query

**Comment by Graveheart** [comment]
We're having the same issue at work as @HabibMollah, I wonder if it's pnpm specific? The pnpm version we're using is 8.11.0.

**Comment by tacticSugar** [comment]
![image](https://github.com/TanStack/query/assets/105880918/e89dabf0-316d-45f0-aa85-4ab94b93de9b)
Nor dehydrate, nor QueryClient. 
**NextJS 13.5.6
@tanstack/react-query 5.18.1**

**Comment by yuriuliam** [comment]
Had a similar issue recently with my react-vite under pnpm package manager w/ Node. Just deleted node_modules and reinstalled from scratch and everything is now working fine!
