### ISSUE TITLE
@tanstack/react-query-devtools v4 does not include `NODE_ENV` check 

### ISSUE THREAD

**Issue by jaworek** [TanStack/query#3860]
### Describe the bug

According to the documention, devtools should only be included in `development` mode:
https://tanstack.com/query/v4/docs/devtools#install-and-import-the-devtools

React Query v3 devtools include check for that:
https://github.com/TanStack/query/blob/v3/devtools/index.js

React Query v4 are missing this check which results in devtools being bundled in production and increasing overall bundle size:
https://github.com/TanStack/query/blob/main/packages/react-query-devtools/src/index.ts

### Your minimal, reproducible example

https://stackblitz.com/edit/nextjs-odbs3c?file=pages/_app.js

React Query v3 does not have this issue:
https://stackblitz.com/edit/nextjs-ssq6g3?file=pages/_app.js

### Steps to reproduce

1. Open `_app.js` file
2. Open terminal and run `npm run build`
3. Comment out `<ReactQueryDevtools initialIsOpen={false} />` and `import { ReactQueryDevtools } from '@tanstack/react-query-devtools';`
4. Run `npm run build`
5. Notice that shared bundle size decreased from `103kB` to `90kB`

### Expected behavior

React Query Devtools should not be bundled in production build by default.

### How often does this bug happen?

Every time

### Screenshots or Videos

Next 12.2 project with devtools enabled:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/22678765/179733092-1e9c087b-e7b4-4417-abb3-56d7aa585eec.png">

Next 12.2 project with devtools disabled:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/22678765/179733218-dc3b64ff-f6b7-41a3-936c-43c870f3ea46.png">

### Platform

- OS: MacOS
- Browser: Chromium
- Version: 4.0.3

### react-query version

4.0.3

### TypeScript version

4.7.4

**Comment by TkDodo** [comment]
I re-created what we had in v3 here: https://github.com/TanStack/query/pull/3861

but it doesn't seem to work well with ESM. Do you have a better idea?

**Comment by MattyBalaam** [comment]
I am guessing this issue also causes these failures in my test too:

<img width="1081" alt="Screenshot 2022-07-20 at 10 08 01" src="https://user-images.githubusercontent.com/1246923/179943774-cc13d878-3c09-464f-9f86-374b47b7e705.png">

**Comment by TkDodo** [comment]
@jaworek can you try it out with this codesandbox preview build?

```
"@tanstack/react-query-devtools": "https://pkg.csb.dev/TanStack/query/commit/df9c197e/@tanstack/react-query-devtools",
```

it doesn't seem to work on my tests with the stackblitz - I get 101kb with the devtools and 87 without them.

However, I also get 101kb if I do:

```
      {process.env.NODE_ENV === 'development' && (
        <ReactQueryDevtools initialIsOpen={false} />
      )}
```

which, idk, should be the same as if the devtools were not there at all, right?

**Comment by Manubi** [comment]
Hi,
   "@tanstack/react-query": "^4.0.5",
    "@tanstack/react-query-devtools": "^4.0.6",
![CleanShot 2022-07-20 at 18 09 56](https://user-images.githubusercontent.com/20935138/180030769-166481b4-96db-49d6-8270-9e4eeeee3ae7.png)

**Comment by TkDodo** [comment]
@Manubi which bundler is this?

**Comment by ug02fast** [comment]
Having the same issue. Devtools not loading.

**Comment by TkDodo** [comment]
Can someone please provide more info?

**Comment by Manubi** [comment]
Hi again,

"react": "18.2.0",
"react-dom": "18.2.0",
"next": "12.2.2", with webpack 5.

Anything else?

**Comment by TkDodo** [comment]
fix is here:
- https://github.com/TanStack/query/pull/3884

**Comment by ThantZin-develope** [comment]
I face the same problem like @Manubi
