### ISSUE TITLE
Unable to upgrade from v3 to v4

### ISSUE THREAD

**Issue by doberkofler** [TanStack/query#3863]
### Describe the bug

I have been trying to upgrade from v3 to v4 and wanted to install the new package as described in the documentation.
Unfortunately the packages do not seem to exist:

```bash
npm i --save @tanstack/react-query
npm ERR! code ENOVERSIONS
npm ERR! No versions available for @tanstack/react-query

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/doberkofler/.npm/_logs/2022-07-19T13_08_25_064Z-debug-0.log
```

### Your minimal, reproducible example

n.a.

### Steps to reproduce

```bash
npm i --save @tanstack/react-query
npm ERR! code ENOVERSIONS
npm ERR! No versions available for @tanstack/react-query

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/doberkofler/.npm/_logs/2022-07-19T13_08_25_064Z-debug-0.log
```

### Expected behavior

n.a.

### How often does this bug happen?

Every time

### Platform

macOS 12.4

### react-query version

18.2.0

### TypeScript version

4.7.4

**Comment by pgs-gmartowski** [comment]
Same here, it was working couple of hours ago, now is not.

**Comment by TkDodo** [comment]
yeah we did "something", not sure what. Tanner and I are looking into it. sorry for that.

**Comment by TkDodo** [comment]
it's back at version `4.0.5`. sorry for the trouble

**Comment by TkDodo** [comment]
at least we can say: `4.0.3` worked fine, then `4.0.4` was not found, and `4.0.5` is back again. oh the irony 😆 . sorry again

**Comment by doberkofler** [comment]
Thank you

**Comment by Zerebokep** [comment]
You should make 4.0.5 also available in the 'react-query' repo, switching to @tanstack breaks graphql codegen: https://github.com/dotansimha/graphql-code-generator/issues/8116

Maybe mirror the repo?
