### ISSUE TITLE
Can't install persistence plugins

### ISSUE THREAD

**Issue by smashercosmo** [TanStack/query#3867]
### Describe the bug

when trying to install persistence plugins by running 'yarn add @tanstack/query-async-storage-persister' getting the following error
```
yarn add @tanstack/query-async-storage-persister
yarn add v1.22.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@tanstack/react-query-core/-/query-core-4.0.5.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/smashercosmo/Documents/projects/fonectacaller/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Your minimal, reproducible example

repro is not needed

### Steps to reproduce

just try to run `yarn add @tanstack/query-async-storage-persister`

### Expected behavior

it should be possible to install persistence plugins

### Platform

- OS: MacOS Monterey

### react-query version

4.0.5

### TypeScript version

4.7.4

**Comment by TkDodo** [comment]
works for me. can you try again?

the offline example that uses persisters is also up and running: https://tanstack.com/query/v4/docs/examples/react/offline

**Comment by smashercosmo** [comment]
Ok, it works with npm, but doesn't work with yarn. installing @tanstack/react-query works both with npm and yarn.

**Comment by TkDodo** [comment]
i tried both yarn and npm locally and it worked

**Comment by smashercosmo** [comment]
ok, I upgraded yarn to 1.22.5. And it started to work after that. Thx.
