### ISSUE TITLE
Previous @tanstack/react-query versions unpublished?

### ISSUE THREAD

**Issue by pakatagoh** [TanStack/query#3875]
### Describe the bug

Unable to install versions before 4.0.5

`npm view @tanstack/react-query versions ` results in only 4.0.5 being listed

### Your minimal, reproducible example

https://www.npmjs.com/package/@tanstack/react-query

### Steps to reproduce

Try installing with a fixed version like 4.0.4

### Expected behavior

Expected to install 4.0.4 successfully

### Screenshots or Videos

npm only shows a single version as well

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/37908805/179887908-c1b37e1e-96c7-4e64-8f07-b848e4749027.png">

_No response_

### Platform

- OS: MacOS

### react-query version

4.0.3

**Comment by huynqjmango360** [comment]
same here!

**Comment by TkDodo** [comment]
They have been unpublished by accident. please start with 4.0.5.
