### ISSUE TITLE
v4.0.5 lots of types are suddenly missing in v4 while in the docs/code

### ISSUE THREAD

**Issue by maapteh** [TanStack/query#3879]
### Describe the bug

I suddenly got TS errors when moving away from the beta4 to the real v4. 
While these errors are not legit since the props are in the code!

`Module '"@tanstack/react-query"' has no exported member 'QueryClient'.ts(2305)`

also things on `useQuery` like "retry", "enabled", "refetchInterval", "cacheTime",  "retry" is suddenly gone in typings, according to the docs: https://tanstack.com/query/v4/docs/guides/query-retries these props are there... but not in its typings. This didnt make the transition from the beta smooth at all.

### Your minimal, reproducible example

none

### Steps to reproduce

import v 4.0.5 and use it in typescript project
see all warnings on props not there

then reference with version 4.0.0-beta.23 which all typings did work...

### Expected behavior

package being typed correctly

### Platform

osx and ci

### react-query version

4.0.5

### TypeScript version

latest

**Comment by TkDodo** [comment]
please show a codesandbox reproduction where this doesn't work. it was reported a lot in the last 2 days and it was always a false positive

**Comment by maapteh** [comment]
I will look into your typings export and show you the proof :)

**Comment by maapteh** [comment]
`node_modules/@tanstack/react-query/build/types/packages/react-query/src/useQuery.d.ts`

```
import { QueryFunction, QueryKey } from '@tanstack/query-core';
import { DefinedUseQueryResult, UseQueryOptions, UseQueryResult } from './types';
export declare function useQuery<TQueryFnData = unknown, TError = unknown, TData = TQueryFnData, TQueryKey extends QueryKey = QueryKey>(options: Omit<UseQueryOptions<TQueryFnData, TError, TData, TQueryKey>, 'initialData'> & {
    initialData?: () => undefined;
}): UseQueryResult<TData, TError>;
export declare function useQuery<TQueryFnData = unknown, TError = unknown, TData = TQueryFnData, TQueryKey extends QueryKey = QueryKey>(options: Omit<UseQueryOptions<TQueryFnData, TError, TData, TQueryKey>, 'initialData'> & {
    initialData: TQueryFnData | (() => TQueryFnData);
}): DefinedUseQueryResult<TData, TError>;
export declare function useQuery<TQueryFnData = unknown, TError = unknown, TData = TQueryFnData, TQueryKey extends QueryKey = QueryKey>(queryKey: TQueryKey, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData, TQueryKey>, 'queryKey' | 'initialData'> & {
    initialData?: () => undefined;
}): UseQueryResult<TData, TError>;
export declare function useQuery<TQueryFnData = unknown, TError = unknown, TData = TQueryFnData, TQueryKey extends QueryKey = QueryKey>(queryKey: TQueryKey, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData, TQueryKey>, 'queryKey' | 'initialData'> & {
    initialData: TQueryFnData | (() => TQueryFnData);
}): DefinedUseQueryResult<TData, TError>;
export declare function useQuery<TQueryFnData = unknown, TError = unknown, TData = TQueryFnData, TQueryKey extends QueryKey = QueryKey>(queryKey: TQueryKey, queryFn: QueryFunction<TQueryFnData, TQueryKey>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData, TQueryKey>, 'queryKey' | 'queryFn' | 'initialData'> & {
    initialData?: () => undefined;
}): UseQueryResult<TData, TError>;
export declare function useQuery<TQueryFnData = unknown, TError = unknown, TData = TQueryFnData, TQueryKey extends QueryKey = QueryKey>(queryKey: TQueryKey, queryFn: QueryFunction<TQueryFnData, TQueryKey>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData, TQueryKey>, 'queryKey' | 'queryFn' | 'initialData'> & {
    initialData: TQueryFnData | (() => TQueryFnData);
}): DefinedUseQueryResult<TData, TError>;
```

**Comment by TkDodo** [comment]
I don't know what you are trying to say 🤷‍♂️

**Comment by maapteh** [comment]
wha

**Comment by maapteh** [comment]
It seems to origin from the fact locally i was using the beta and just added the new package.
When i removed all my local modules and runned yarn again my editor was happy, sorry for again false positive but i guess there where more beta users like me :) thanks for the TS playground @TkDodo appreciated!

**Comment by maapteh** [comment]
https://github.com/TanStack/query/issues/3855#issuecomment-1189127386
