### ISSUE TITLE
Unexpected query call in suspense mode

### ISSUE THREAD

**Issue by ilovedesert001** [TanStack/query#3911]
### Describe the bug

Why is fetchMockApi1 called twice?

```

const fetchMockApi1 = async () => {
  console.log("fetchMockApi1");
  return 1;
};

const fetchMockApi2 = async () => {
  console.log("fetchMockApi2");
  return new Promise((y) => {
    setTimeout(() => {
      console.log("fetchMockApi2 --- end");
      y(1);
    }, 1000 * 3);
  });
};

function Example() {
  const d1 = useQuery(["d1"], fetchMockApi1);
  const d2 = useQuery(["d2"], fetchMockApi2);
  return <div>test</div>;
}

```

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/15065396/180657470-301d902a-8e80-41da-9f30-742b7735a725.png">

### Your minimal, reproducible example

https://codesandbox.io/s/competent-dew-fomvdq?file=/src/index.js

### Steps to reproduce

1. go to https://codesandbox.io/s/competent-dew-fomvdq?file=/src/index.js
2. click on refresh 
3. Observe console outputs

### Expected behavior

fetchMockApi1 should only be called once

### How often does this bug happen?

Every time

### Platform

MacOS
version:4

### react-query version

4.0.10

**Comment by TkDodo** [comment]
Because of suspense: true
suspense unmounts the component and mounts the fallback of the suspense boundary instead. Then, when the request finishes, it will mount the component again. Multiple useQuery calls + suspense create a waterfall, so what happens is:
- component mounts, d1 fetches, component suspends
- d1 finishes, component re-mounts, d2 fetches, component suspends
- d2 finishes, component re-mounts. At this time, data for d1 is considered stale ( i staleTime is set), so you'll see a background refetch because of refetchOnMount

**Comment by dante01yoon** [comment]
@TkDodo  Hi, I wonder any alternative ways prevent waterfalls when using with Suspense.
In some cases, we can't assure there is only single useQuery hook called in single component.

**Comment by TkDodo** [comment]
@dante01yoon I wrote a blogpost about it: https://tkdodo.eu/blog/seeding-the-query-cache

**Comment by dante01yoon** [comment]
@TkDodo Oh, new post, doesn't surprise me how this ecosystem so fast. I'll take a look at it and comeback. Thank you!

**Comment by dante01yoon** [comment]
@TkDodo I saw your blog and thank you for introducing good ways to prevent water falls. 

I wonder why  waterfall is not happen in case  parent component has two different child component call useQuery seperately and wrap parent with Suspense.

```jsx
<Suspense>
   <Parent/> 
</Suspense>


...
const Parent = () => {
  ...
   return (
     <>
       <Child1/>
       <Child2/>
    </>
}
```

why water fall only showed on use mutiple queries in single comonent,  but not when split into two component?

**Comment by TkDodo** [comment]
@dante01yoon can you show what you mean in a codesandbox reproduction?
