### ISSUE TITLE
umd file index.development.js returns null for devtools

### ISSUE THREAD

**Issue by geraldodev** [TanStack/query#3916]
### Describe the bug

The UMD file https://unpkg.com/browse/@tanstack/react-query-devtools@4.0.10/build/umd/index.development.js returns null for devtools.

I'm my case I'm consuming via shadow-cljs , the clojurescript compiler,
According to @tkdodo it also can affect cdn consumers.

### Your minimal, reproducible example

https://unpkg.com/browse/@tanstack/react-query-devtools@4.0.10/build/umd/index.development.js

### Steps to reproduce

1- consume the umd package via cdn
2 - render query tools component
3 - it'll render null

### Expected behavior

Query tools component render

### How often does this bug happen?

Every time

### Platform

Linux

### react-query version

4.0.10

**Comment by TkDodo** [comment]
it's fixed in the beta we just released:

https://unpkg.com/browse/@tanstack/react-query-devtools@4.0.11-beta.0/build/umd/index.development.js

there are some other issues in there though, so it will be available once we generally fix this :)
