### ISSUE TITLE
Custom useQuery hook, passing down options requires Omit<>

### ISSUE THREAD

**Issue by amiiit** [TanStack/query#3920]
### Describe the bug

Hello,

Immense gratitude for creating this powerful library ❤️ 

See the following [TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwK4GcCmBFJaoE8A0cAquljrgPJgzAQB2KAvnAGZQQhwBEAAjAIYMBAYwDWAeihp+wmAFoAjtjxcA3AFgAUFpi4waOAFlcAEX4C4AXkRa4duHQBcDpCABGOLYy3D6KeKhoxmYCAOrAMAAWVDR+VnAAFLb2ENS0DAD8ziSYypRpfgA8web8hACiUOxQhCUCAHxaAJRW9Taa9nBSMEhQdHCBZHjFpqX1SR2d9gDaAOQguHIAJqWzALr4yVOJvnQwaAAeMC2WbQhb2-bdvf0ACuwgwOgAdFIoEAA2AG5oCQhOcAALAAmRhNC6dRibSbbVKxBgXJoabSaRjIrSHSCwOBLNAsfhID4BdB1fjhKIxdIoZFAA)

The hook I'm trying to do, should allow the caller to pass in options:

```typescript
import {useQuery, UseQueryOptions} from "@tanstack/react-query";

type MyData = {
    n: number
}
const useMyDataWithOptions = (
    options?: UseQueryOptions<MyData, Error, MyData>
) => {
    return useQuery<MyData>(
        ['my-data'],
        (context) => {
            return Promise.resolve({n: 42})
        },
        options
    );

};

export default useMyDataWithOptions;

```

So the problem lies in that useQuery has the following signature for the `options` argument:

```typescript
Omit<
    UseQueryOptions<TQueryFnData, TError, TData, TQueryKey>,
    'queryKey' | 'queryFn' | 'initialData'
  > & { initialData?: () => undefined }
```

**This pattern of passing down the options works fine for `useMutation` without any type manipulations**. _Any I missing something?_ Or can we create a type helper perhaps to allow us to easily type this kind of use-case?

Please have a look at the playground, but for completeness here is the error message I get from TypeScript:

```typescript
No overload matches this call.
  Overload 1 of 9, '(queryKey: QueryKey, queryFn: QueryFunction<MyData, QueryKey>, options?: (Omit<UseQueryOptions<MyData, unknown, MyData, QueryKey>, "initialData" | ... 1 more ... | "queryKey"> & { ...; }) | undefined): UseQueryResult<...>', gave the following error.
    Argument of type 'UseQueryOptions<MyData, Error, MyData, QueryKey> | undefined' is not assignable to parameter of type '(Omit<UseQueryOptions<MyData, unknown, MyData, QueryKey>, "initialData" | "queryFn" | "queryKey"> & { initialData?: (() => undefined) | undefined; }) | undefined'.
      Type 'UseQueryOptions<MyData, Error, MyData, QueryKey>' is not assignable to type 'Omit<UseQueryOptions<MyData, unknown, MyData, QueryKey>, "initialData" | "queryFn" | "queryKey"> & { initialData?: (() => undefined) | undefined; }'.
        Type 'UseQueryOptions<MyData, Error, MyData, QueryKey>' is not assignable to type 'Omit<UseQueryOptions<MyData, unknown, MyData, QueryKey>, "initialData" | "queryFn" | "queryKey">'.
          Types of property 'refetchInterval' are incompatible.
            Type 'number | false | ((data: MyData | undefined, query: Query<MyData, Error, MyData, QueryKey>) => number | false) | undefined' is not assignable to type 'number | false | ((data: MyData | undefined, query: Query<MyData, unknown, MyData, QueryKey>) => number | false) | undefined'.
              Type '(data: MyData | undefined, query: Query<MyData, Error, MyData, QueryKey>) => number | false' is not assignable to type 'number | false | ((data: MyData | undefined, query: Query<MyData, unknown, MyData, QueryKey>) => number | false) | undefined'.
                Type '(data: MyData | undefined, query: Query<MyData, Error, MyData, QueryKey>) => number | false' is not assignable to type '(data: MyData | undefined, query: Query<MyData, unknown, MyData, QueryKey>) => number | false'.
                  Types of parameters 'query' and 'query' are incompatible.
                    Type 'Query<MyData, unknown, MyData, QueryKey>' is not assignable to type 'Query<MyData, Error, MyData, QueryKey>'.
                      Types of property 'initialState' are incompatible.
                        Type 'QueryState<MyData, unknown>' is not assignable to type 'QueryState<MyData, Error>'.
                          Type 'unknown' is not assignable to type 'Error'.
  Overload 2 of 9, '(queryKey: QueryKey, queryFn: QueryFunction<MyData, QueryKey>, options?: (Omit<UseQueryOptions<MyData, unknown, MyData, QueryKey>, "initialData" | ... 1 more ... | "queryKey"> & { ...; }) | undefined): DefinedUseQueryResult<...>', gave the following error.
    Argument of type 'UseQueryOptions<MyData, Error, MyData, QueryKey> | undefined' is not assignable to parameter of type '(Omit<UseQueryOptions<MyData, unknown, MyData, QueryKey>, "initialData" | "queryFn" | "queryKey"> & { initialData: MyData | (() => MyData); }) | undefined'.
      Type 'UseQueryOptions<MyData, Error, MyData, QueryKey>' is not assignable to type 'Omit<UseQueryOptions<MyData, unknown, MyData, QueryKey>, "initialData" | "queryFn" | "queryKey"> & { initialData: MyData | (() => MyData); }'.
        Type 'UseQueryOptions<MyData, Error, MyData, QueryKey>' is not assignable to type 'Omit<UseQueryOptions<MyData, unknown, MyData, QueryKey>, "initialData" | "queryFn" | "queryKey">'.
  Overload 3 of 9, '(queryKey: QueryKey, queryFn: QueryFunction<MyData, QueryKey>, options?: Omit<UseQueryOptions<MyData, unknown, MyData, QueryKey>, "queryFn" | "queryKey"> | undefined): UseQueryResult<...>', gave the following error.
    Argument of type 'UseQueryOptions<MyData, Error, MyData, QueryKey> | undefined' is not assignable to parameter of type 'Omit<UseQueryOptions<MyData, unknown, MyData, QueryKey>, "queryFn" | "queryKey"> | undefined'.
      Type 'UseQueryOptions<MyData, Error, MyData, QueryKey>' is not assignable to type 'Omit<UseQueryOptions<MyData, unknown, MyData, QueryKey>, "queryFn" | "queryKey">'.
        Types of property 'refetchInterval' are incompatible.
          Type 'number | false | ((data: MyData | undefined, query: Query<MyData, Error, MyData, QueryKey>) => number | false) | undefined' is not assignable to type 'number | false | ((data: MyData | undefined, query: Query<MyData, unknown, MyData, QueryKey>) => number | false) | undefined'.
            Type '(data: MyData | undefined, query: Query<MyData, Error, MyData, QueryKey>) => number | false' is not assignable to type 'number | false | ((data: MyData | undefined, query: Query<MyData, unknown, MyData, QueryKey>) => number | false) | undefined'.
              Type '(data: MyData | undefined, query: Query<MyData, Error, MyData, QueryKey>) => number | false' is not assignable to type '(data: MyData | undefined, query: Query<MyData, unknown, MyData, QueryKey>) => number | false'.(2769)
```

Thank you!

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwK4GcCmBFJaoE8A0cAquljrgPJgzAQB2KAvnAGZQQhwBEAAjAIYMBAYwDWAeihp+wmAFoAjtjxcA3AFgAUFpi4waOAFlcAEX4C4AXkRa4duHQBcDpCABGOLYy3D6KeKhoxmYCAOrAMAAWVDR+VnAAFLb2ENS0DAD8ziSYypRpfgA8web8hACiUOxQhCUCAHxaAJRW9Taa9nBSMEhQdHCBZHjFpqX1SR2d9gDaAOQguHIAJqWzALr4yVOJvnQwaAAeMC2WbQhb2-bdvf0ACuwgwOgAdFIoEAA2AG5oCQhOcAALAAmRhNC6dRibSbbVKxBgXJoabSaRjIrSHSCwOBLNAsfhID4BdB1fjhKIxdIoZFAA

### Steps to reproduce

1. go to attached TS playground and see the error

### Expected behavior

As a user I would expect to be able to expose the options to the caller, so that the caller can decide i.e. to show notifications on success/error without mixing in concerns, and also without me having to repeat the Options already defined by this library

### How often does this bug happen?

Every time

### Platform

mac os

### react-query version

v4.0.10

### TypeScript version

v4.6.3

**Comment by amiiit** [comment]
Typing my `options` argument as follows stops the error from showing:

```typescript
    options?: Omit<
        UseQueryOptions<OfficeHoursRule[], unknown, OfficeHoursRule[]>,
        'queryKey' | 'queryFn' | 'initialData'
    >

```

I'm hoping for a bit more elegant way to achieve this though

**Comment by TkDodo** [comment]
if you are using the version of useQuery where you pass in queryKey and queryFn separately from each other, then yes, you have to omit. Because `queryKey` and `queryFn` are both part of the `options`,so what would happen if I call your custom hook with a different queryKey? Would we take the one from the options, or the hardcoded one `['my-data']` ?

This is just a very weird api, and I always advocate for _not_ creating low level abstractions like that. It also doesn't make sense that every consumer passes in a different `cacheTime`, but at least that is technically possible. Multiple different keys or functions are not.

So, here is a [working version](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwK4GcCmBFJaoE8A0cAquljrgPJgzAQB2KAvnAGZQQhwBEAAjAIYMBAYwDWAeihp+wmAFoAjtjxcA3AFgAUFpi4waOAFlcAEX4C4AXkRa4duHQBcDpCABGOLYy3D6KeKhoxmYCAOrAMAAWVDR+VnAAFLb2ENS0DAD8zhQgEQA8JJjKlGl+ecHm-IQAolDsUIQVAgB8hADkSuQA0mi4bXAAPnAdxQBidG3NWgCUVs02mvZwUjBIUHRwgWR4SYtL9gDabSC4cgAmlW0AuvjJ+4m+dDBoAB4ws5bzCHf39itrGwACuxcugAHRSFAQAA2ADc0AkEE44AAWABMjGmPyWjFue3uqViDB+0w02k0jDJWlekFgcDOaBY-CQ0IC6Ca-HCURi6RQZKAA) of your custom hook that will allow the consumers to not make mistakes by passing those two things.

if you _really_ want to allow all options, then you have to use the object syntax for useQuery ([playground here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwK4GcCmBFJaoE8A0cAquljrgPJgzAQB2KAvnAGZQQhwBEAAjAIYMBAYwDWAeihp+wmAFoAjtjxcA3AFgAUFpi4waOAFlcAEX4C4AXkRa4duHQBcDpCABGOLYy3D6KeKhoxmYCAOrAMAAWVDR+VnAAFLb2ENS0DAD8ziSYypRpfgA8web8hACiUOxQhCUChACCVfy4hf5QwHQA5gB8PVoAlFY9Npr2cFIwSFB0cIFkeAkIyeN2AHQbqbEM+CurSuQA0mi4zgDaAOQguHIAJqUXALq7Y6t2B3gAYk6JvnQwaAAHjAhpYRstXm9xpNprMAArsEDAdBrKQoCAAGwAbmglj8ACwAJkYAz240YL3JpM0jA02k0QMgsDgtzQLH4SAxAXQdX44SiMXSKDpQA))

```
const useMyDataWithOptions = (
    options?: UseQueryOptions<MyData, Error, MyData, Array<string>>
) => {
    return useQuery({
        ...options,
        queryKey: ['my-data'],
        queryFn: (context) => {
            return Promise.resolve({n: 42})
        },
    })
};
```

but again, this function signature doesn't make much sense. If you spread options first, queryKey and queryFn in options do nothing, and if you spread them last, it can overwrite your hard-coded values, which you very likely don't want.

**Comment by amiiit** [comment]
Thank you @TkDodo, this makes total sense! 

Did you have any thoughts about a utility type for this, so that this kind of pattern can be done more easily, or do you consider this to be an absolute anti-pattern?

What would be a recommended way to simply expose options such as `onError`, `onSuccess`, things that a healthy use-case would want to be able to expose?

If you share some of your idea I'd also be happy to submit a PR with a utility type.

**Comment by TkDodo** [comment]
I'd just do:

```
const useMyDataWithOptions = (
  options: {
    onSuccess?: (data: MyData) => void,
    onError?: (error: unknown) => void
  }
)
```

there usually aren't that many custom things you'd want to pass in to the same hook :)

**Comment by amiiit** [comment]
Thank you!

**Comment by dmahajan980** [comment]
Hello @TkDodo, unfortunately TypeScript starts throwing errors when `placeholderData` is passed and that data is a subset of the data received from query function. I tried playing around with `TQueryFnData` and `TData` generic arguments of the `UseQueryOptions` interface:

```typescript
options: UseQueryOptions<MyData, Error, Partial<MyData>, string[]>
```

This does not throw any error. However, the `data` received from `useQuery` will always reflect the type `Partial<MyData>` which shouldn't be the case after the data is loaded from `queryFn`. Any pointers on where I'm going wrong and how should I set this up correctly?

Thanks in advance!

**Comment by TkDodo** [comment]
there's no way right to have `placeholderData` be a subset of `data` on type level. We would need more generics for this, and then `data` would be `TData | TPlaceholderData` and you would always need to narrow with `isPlaceholderData` or `isSuccess` checks. Doesn't feel too ergonomic to me as well.

I think it's best to have placeholderData be the same type as data and kinda fill it with empty values if possible

**Comment by dmahajan980** [comment]
> data would be TData | TPlaceholderData and you would always need to narrow with isPlaceholderData or isSuccess checks.

Yes, but don't we check that data is `TData` (and not `undefined`) using `isSuccess` in the current API? As we know, the data can be either `TData` or `undefined`. If a new type for `placeholderData` is added, the data becomes `TData | TPlaceholderData` (instead of `TData | undefined`) which'll be checked the same way using `isSuccess`.

> I think it's best to have placeholderData be the same type as data and kinda fill it with empty values if possible

I beg to differ here. `placeholderData` seems very ideal for cases where some portion of data is already available. Although filling the remaining values can be done when they are small in number, it does not scale well when there are too many properties. I know this is not a very strong reasoning. However, it would be quite annoying to fill up 20-25 properties or more with empty values and is also not desirable.

**Comment by TkDodo** [comment]
> Yes, but don't we check that data is TData (and not undefined) using isSuccess in the current API? As we know, the data can be either TData or undefined. If a new type for placeholderData is added, the data becomes TData | TPlaceholderData (instead of TData | undefined) which'll be checked the same way using isSuccess.

You can also check for `if (data)` right now, which some people do a lot. It means "whenever you have data". Note that you can have `data` while you are in `isError` state, e.g. if a background refetch failed. In those scenarios, I'd rather display an error toast notification and not replace my data with a "hard error" state.

This is just preference, but I wouldn't want to make the experience worse when checking for `if (data)`. Also, adding the extra generic is another thing that isn't that easy.

> I beg to differ here. placeholderData seems very ideal for cases where some portion of data is already available. Although filling the remaining values can be done when they are small in number, it does not scale well when there are too many properties. I know this is not a very strong reasoning. However, it would be quite annoying to fill up 20-25 properties or more with empty values and is also not desirable.

yeah sure, but there are other ways around it, like:

```
const { data = { some, partial, data } } = useQuery(...)
```

so you don't really _have to_ use placeholderData to achieve the same effect

**Comment by dmahajan980** [comment]
> yeah sure, but there are other ways around it, like:
> 
> ```
> const { data = { some, partial, data } } = useQuery(...)
> ```
> 
> so you don't really _have to_ use placeholderData to achieve the same effectt

Oh, this would be helpful! Thanks for sharing @TkDodo.

Maybe I was forcing myself too much to solve this from Query API that I didn't think of this. Although this would nullify the benefits of tracked queries when wrapped with a custom hook (I suppose), I can live with that for now.

**Comment by TkDodo** [comment]
> Although this would nullify the benefits of tracked queries when wrapped with a custom hook (I suppose), I can live with that for now.

yeah if you destruct like `{ data, ...rest }` that's true :/
