### ISSUE TITLE
Devtools not working on React Native Web

### ISSUE THREAD

**Issue by Estevete** [TanStack/query#3943]
### Describe the bug

Devtools are not working on React Native Web anymore. In v3, it used to work.

### Your minimal, reproducible example

https://github.com/TanStack/query/tree/main/examples/react/react-native example

### Steps to reproduce

1. Get the https://github.com/TanStack/query/tree/main/examples/react/react-native example
2. In file `App.tsx`, import & add `<ReactQueryDevtools />` inside `QueryClientProvider`
3. Launch project
4. If package expo-font missing, add it. (v10.0.3)

### Expected behavior

Devtools should be displayed, like v3.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 103.0.5060.134

### react-query version

5.0.10

### TypeScript version

4.3.5

**Comment by TkDodo** [comment]
could this be related to #4017 and thus eventually to #3882  ?

If you see `null` being rendered, my guess is that the wrong entry point is being picked up.

**Comment by Fogh** [comment]
I have the same problem in v4. The Dev tool icon is not showing up

**Comment by TkDodo** [comment]
@Estevete @Fogh can you please try it out with `v4.3.0-beta.0` ?

**Comment by YZahringer** [comment]
@TkDodo on my side, the web app crash with the `v4.3.0-beta.0`
![image](https://user-images.githubusercontent.com/4254116/185663119-16b02a99-36f0-4990-8a0d-1da6ff6971ff.png)

Works well in `4.0.10`, but without the DevTools.

**Comment by TkDodo** [comment]
Which bundler are you using? Seems to be the same as:
- https://github.com/TanStack/query/issues/3882#issuecomment-1219413217

**Comment by YZahringer** [comment]
I use webpack 4.46.0 with Expo CLI

**Comment by TkDodo** [comment]
@YZahringer @Fogh @Estevete can you please try out the latest beta version to see if it fixes your issue?

- https://github.com/TanStack/query/releases/tag/v4.3.0-beta.3

**Comment by YZahringer** [comment]
Everything works fine on my side with Expo SDK 46 on Web.
@TkDodo Thanks a lot 👍
