### ISSUE TITLE
error field only contains message

### ISSUE THREAD

**Issue by Zerebokep** [TanStack/query#3948]
### Describe the bug

When accessing the .error field it seems only to contain the error message, no additional data.

`

### Your minimal, reproducible example

-

### Steps to reproduce

For example I get the following response from the graphql server:

`{"errors":[{"extensions":{"path":"$","code":"test-message"},"message":"Test message."}]}`

the output of the error field is:

`Error: New device detected.

### Expected behavior

The error field should contain all error data from the graphql response.

### How often does this bug happen?

Every time

### Platform

Docker

### react-query version

4.0.10

**Comment by TkDodo** [comment]
the error field will contain exactly what the queryFn returns if it returns a failed Promise.

```
useQuery(key, () => {
  return Promise.reject("foo") // error will be the string 'foo'
}
```

```
useQuery(key, () => {
  throw 5 // error will be the number 5
}
```

```
useQuery(key () => {
  throw new Error("oh no") // error will be an error object with message "oh no")
}
```

there is nothing graphql specific about react-query, so this behaviour only depends on how you fetch the data inside the queryFn.

also, if you open an issue, always provide a runnable codesandbox example
