### ISSUE TITLE
v4 of broadcast client, "cannot resolve '../../src/methods/node.js"

### ISSUE THREAD

**Issue by olliejm** [TanStack/query#3965]
### Describe the bug

I am trying to update a Gatsby application to the new v4 packages of React Query. All of this went fine with the exception of the new `@tanstack/query-broadcast-client-experimental` package. We were previously using the experimental broadcast client in v3 without any issues. The error reported, which breaks the build itself, is the following:

```
Module not found: Error: Can't resolve '../../src/methods/node.js' in 'C:\path\to\my\repo\node_modules\@tanstack\query-broadcast-client-experimental\build\esm'
```

I created a minimal reproduction of the issue on CodeSandbox using the gatsby starter. We are also using the `persistQueryClient` but I commented that out to ensure it was not an interaction of the two causing an issue.

I tried to create a reproduction using just the base React template of CodeSandbox, that seems to have a different problem caused simply by wrapping `<App />` in the `QueryClientProvider` (error: `Cannot read properties of undefined (reading 'mount')`). The broadcast client is not used in that sandbox. [Here is the link](https://codesandbox.io/s/holy-grass-99lecp) to that if it's of any additional use.

### Your minimal, reproducible example

https://codesandbox.io/s/wild-framework-qz3fvl?file=/gatsby-browser.js

### Steps to reproduce

1. `import { broadcastQueryClient } from '@tanstack/query-broadcast-client-experimental';`
2. Create a new `QueryClient`, call the imported broadcast function and wrap the application in the provider with the client
3. Try to build the Gatsby application

### Expected behavior

The webpack build breaks with the following error

```
Module not found: Error: Can't resolve '../../src/methods/node.js' in 'C:\path\to\my\repo\node_modules\@tanstack\query-broadcast-client-experimental\build\esm'
```

### How often does this bug happen?

Every time

### Platform

- OS: Windows
- Browser: Chrome
- Version: 103.0.5060.134 (Official Build) (64-bit)

### react-query version

4.0.10

**Comment by olliejm** [comment]
I did further reading and this seems to be related to the `broadcast-channel` package itself not being handled (or maybe not being configured correctly to be handled) by webpack and other bundlers:
https://github.com/FredKSchott/snowpack/discussions/2450

**Comment by alvesvaren** [comment]
This happens to me too

**Comment by olliejm** [comment]
I'm not sure why it didn't happen previously to me with v3 as it seems both query v3 and v4 are using the same version of the broadcast-channel package

It does appear though that the problematic code in question is no longer in the latest version of broadcast-channel (4) so perhaps updating that package could be one solution

If I find some spare time I can try to do that and see if it solves the issue or creates new ones

**Comment by TkDodo** [comment]
it might have something to do with bundling.

> It does appear though that the problematic code in question is no longer in the latest version of broadcast-channel (4) so perhaps updating that package could be one solution
> If I find some spare time I can try to do that and see if it solves the issue or creates new ones

that would be great!

**Comment by neemski** [comment]
I'm also seeing the same issue reported in my Next.js app:

```bash
error - ../.yarn/cache/@tanstack-query-broadcast-client-experimental-npm-4.0.10-e3fab36717-c3c9bcaa0a.zip/node_modules/@tanstack/query-broadcast-client-experimental/build/umd/index.production.js:11:7630
Module not found: Can't resolve '../../src/methods/node.js'

Import trace for requested module:
./pages/_app.tsx
```

by simply doing:
```tsx
import React from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { broadcastQueryClient } from "@tanstack/query-broadcast-client-experimental";

const queryClient = new QueryClient();

broadcastQueryClient({
  queryClient,
  broadcastChannel: "some-test-channel"
});

export default function MyApp({ Component, pageProps }) {
  return (
    <QueryClientProvider client={queryClient}>
      <Component {...pageProps} />
    </QueryClientProvider>
  );
}

```

CodeSandbox repro link: https://codesandbox.io/s/react-query-broadcast-client-bug-5dt9so?file=/pages/_app.js
