### ISSUE TITLE
`useQuery` status on mount is `loading` when `enabled` is false in React Native Project

### ISSUE THREAD

**Issue by Pika-Pool** [TanStack/query#3972]
### Describe the bug

Similar to #1657.

On initial load, `useQuery`'s status is `loading`, even without running the fetch function, when the `enabled` option is set to `false`.

### Your minimal, reproducible example

https://snack.expo.dev/@pikapool/react-query-initial-loading-bug

### Steps to reproduce

Run the expo snack link

### Expected behavior

initial status of `useQuery` should not be `loading`.

### How often does this bug happen?

Every time

### Platform

- Expo (tested on web)

### react-query version

v4.0.10

**Comment by TkDodo** [comment]
This is on purpose and one of the breaking changes in v4. Please see:
- https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4#the-idle-state-has-been-removed
- https://tanstack.com/query/v4/docs/guides/queries#why-two-different-states
- https://tanstack.com/query/v4/docs/guides/disabling-queries

**Comment by TkDodo** [comment]
You can just disable the button while the query is in loading state. The button will then be disabled initially while the query has is disabled, and also while the query is initially fetching...

**Comment by Pika-Pool** [comment]
@TkDodo, thank you, but my use case is a bit complicated.

I want to let the user submit a form using that button with a mutation. So the button should initially go into loading state when the mutation loads, not before that.

The query is enabled once the mutation is successful, as it depends on the returned data.  But the button should show loading state until this query has loaded too, as the data from the query is a part of the form submission process.

**Comment by TkDodo** [comment]
please show a codesandbox reproduction so that I can look at and understand the issue

**Comment by helenaford** [comment]
this seems like a bug, it's not intuitive to the user when enabled is false... 

To get around this in my own project, we ignore the loading prop until enabled is true

**Comment by Pika-Pool** [comment]
@helenaford, I also think this is unintuitive. In my project I'm checking if both isLoading and isFetching are true for this, or returning the current enabled state from a custom hook.

I get that its for offline data persistence, but I hope they find a better way for it.
