### ISSUE TITLE
misleading document after v4 release

### ISSUE THREAD

**Issue by tmokmss** [TanStack/query#4003]
### Describe the bug

Hi I'm very new to React Query and I found a misleading description in README.

https://github.com/TanStack/query/blob/e6df356edd5ce3d9d93eabbc7c15af68cdd2eb30/README.md?plain=1#L31-L34

According to release pages, v4 is not in beta any more and the link to v4 document should be https://tanstack.com/query/v4

### Your minimal, reproducible example

n/a

### Steps to reproduce

n/a

### Expected behavior

n/a

### Platform

n/a

### react-query version

4.0.10

**Comment by leotm** [comment]
was wondering why react-query-beta.tanstack.com -> react-query-v3.tanstack.com

thx for raising and linking tanstack.com/query/v4

**Comment by leotm** [comment]
doesn't look updated in
- https://github.com/TanStack/query/pull/3998
- https://github.com/TanStack/query/pull/3969

would be great to merge those in and follow this up w a PR too

**Comment by TkDodo** [comment]
Please PR it

**Comment by TkDodo** [comment]
closing the issue, please just open a PR that updates the readme file.

**Comment by tmokmss** [comment]
I'm not yet very familiar with React Query to come up with an appropriate description for this change so I'll leave this for someone familiar with it :)
