### ISSUE TITLE
React query v4 is not triggering component refresh properly where as V3 is doing absolutly fine

### ISSUE THREAD

**Issue by ursnj** [TanStack/query#4015]
### Describe the bug

After debugging more than a week i realized v4 is somehow not triggering updates to my components in React Native app, with the same setup v3 is working absolutly fine.

After updating data in cache with setQueryData it should trigger refresh in component but some how its not refreshing component with latest cache data

Not able to create a repro snack as it happening few places, but this is the only issue dragging me to use v3 instead of v4.

Please see if you can able to reproduce and fix this.

Note: Im using v4 with React Native + React Freeze + React Query

### Your minimal, reproducible example

https://tanstack.com/query/v4

### Steps to reproduce

Use react Query v4 with latest React Native version with React Freeze

### Expected behavior

After updating data in cache with setQueryData it should trigger refresh in component but some how its not refreshing component with latest cache data

### How often does this bug happen?

Every time

### Platform

Macos, Android, React Native

### react-query version

4.0.10

### TypeScript version

4.4.4

**Comment by nhducit** [comment]
Can you give us a reproduce repo? If the repro doesn't use any external native dependencies then you can use https://snack.expo.dev/ to quickly create one

**Comment by TkDodo** [comment]
closing as there is no reproduction. feel free to reopen once you have a reproduction.
