### ISSUE TITLE
isLoading is true when the query is not enabled

### ISSUE THREAD

**Issue by mazenkhalil** [TanStack/query#4019]
### Describe the bug

With V3, when the query is disabled, isLoading resolves to **false**. Upon upgrading to V4, isLoading resolves to **true** when the query is disabled.

```
useQuery(
    ['key'],
    () =>
        API.get(`...`).then((res) => res.data)
    {
      enabled: false
    },
  );
```

### Your minimal, reproducible example

NA

### Steps to reproduce

1. Create a query
2. Set enabled = false
3. observe isLoading value

### Expected behavior

isLoading should resolve to false as the query is not enabled yet.

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Version: 4.0.10
- React Version: 17

### react-query version

v4.0.10

### TypeScript version

v4.7.4

**Comment by TkDodo** [comment]
has been reported before, and it's a documented breaking change.

**Comment by anglee** [comment]
For others who landed on this issue, here is the other thread: https://github.com/TanStack/query/issues/3975
