### ISSUE TITLE
Unable to test ReactQuery using React 18

### ISSUE THREAD

**Issue by jxbaker-sep** [TanStack/query#4022]
### Describe the bug

- `react-hooks-testing-library` version: n/a, using React 18 and @testing-library/react 13.3
- `react` version: 18.2
- `react-dom` version (if applicable): 18.2
- `react-test-renderer` version (if applicable): n/a
- `node` version: v16.16.0
- `npm` (or `yarn`) version: 8.11.0

### Relevant code or config:

```js
import { QueryClient, QueryClientProvider, useQuery } from "@tanstack/react-query";
import { renderHook, waitFor } from "@testing-library/react";

test("useIasQuery", async () => {
    function useCustomHook() {
        return useQuery(['customHook'], () => 'Hello');
    }
    const queryClient = new QueryClient();
    const wrapper = ({ children }) => (
        <QueryClientProvider client={queryClient}>
            {children}
        </QueryClientProvider>
    );

    const { result } = renderHook(() => useCustomHook(), { wrapper });

    await waitFor(() => result.current.isSuccess, {interval: 100});
    expect(result.current.data).toEqual("Hello");
});
```

### What you did:

I attempted to implement and run the example test for ReactQuery (https://tanstack.com/query/v4/docs/guides/testing), using React 18. Note that react-hooks-testing-library renderHooks has been rolled into @testing-library/react for React 18. Therefore, you will note one change in the above code from the example test provided: instead of using the `waitFor` method returned by renderHook, I am using the `waitFor` method defined in @testing-library/react.

### What happened:

The test fails because `waitFor` times out.

### Reproduction:

`git clone git@github.com:jxbaker-sep/broken-react-query-test.git`
`npm test`

### Problem description:

We would like to write good tests for our ReactQuery app, but are unable to determine how to correctly write those tests with React 18.

### Suggested solution:

Update ReactQuery docs to demonstrate functional testing with React 18.

### Your minimal, reproducible example

https://github.com/jxbaker-sep/broken-react-query-test

### Steps to reproduce

`git clone git@github.com:jxbaker-sep/broken-react-query-test.git `
`npm test`

### Expected behavior

Expected test copied from documentation to pass; instead it fails.

### How often does this bug happen?

Every time

### Platform

OS: Windows 
Browser: n/a
Browser Version: n/a

### react-query version

4.0.10

**Comment by TkDodo** [comment]
that's because `renderHook` from `react-hooks/testing-library` does _NOT_ work exactly like the one from `react-hooks-testing-library`.

It would be good to update the docs to be explicit about this if you want.

You'd need:

```diff
- await waitFor(() => result.current.isSuccess, {interval: 100});
+ await waitFor(() => expect(result.current.isSuccess).toBe(true))
```

`react-hooks-testing-library` allows you to return a `boolean` from the callback, while `react-hooks/testing-library` wants you to return a Promise.

you can see a working version in the repo I link to from my blog:
- https://github.com/TkDodo/testing-react-query/blob/5e4dc865391038eadb8c62d6abdcdba36280be32/src/tests/hooks.test.tsx#L14

can you try if that works and if possible, PR the docs?

**Comment by jxbaker-sep** [comment]
That worked, thank you. I will PR the docs.

**Comment by jxbaker-sep** [comment]
PR here: https://github.com/TanStack/query/pull/4023
