### ISSUE TITLE
Deadlink in doc

### ISSUE THREAD

**Issue by doliG** [TanStack/query#4054]
### Describe the bug

All the example of the doc are broken. See https://react-query-v3.tanstack.com/examples/simple

I think it's because the structure in github repo changed from `tree/main/examples/simple` to `tree/main/examples/react/simple`

**Comment by TkDodo** [comment]
yeah the examples point to:
`react-query/tree/main/examples/simple`

for v3, they need to point towards the v3 branch. Can you contribute a PR to the v3 branch to fix it please?

**Comment by doliG** [comment]
closed by #4065 . Thanks @nicholasgriffintn
