### ISSUE TITLE
Parallel Queries mess up with useIsFetching

### ISSUE THREAD

**Issue by rcfrias** [TanStack/query#4055]
### Describe the bug

While performing 2 requests in parallel, useIsFetching is being used to present a busy overlay.  isFetching gets stuck with "1" pending query, so overlay will stay because of the concurrency problem.  Changing it to serial/dependent, fixes the issue, but it brings a bad user experience.

### Your minimal, reproducible example

Not needed

### Steps to reproduce

use useQuery for a parallel request.

### Expected behavior

isFetching will change to 0

### Platform

iOS

### react-query version

latest

**Comment by TkDodo** [comment]
Please show a minimal reproduction, preferably with codesandbox and TypeScript.

**Comment by TkDodo** [comment]
feel free to reopen with a reproduction.
