### ISSUE TITLE
Breaking change: isLoading now true for disabled queries

### ISSUE THREAD

**Issue by Shaddix** [TanStack/query#4056]
### Describe the bug

In v3 (`react-query`) if query is disabled (and has no data) `isLoading` was `false`, in v4 it's `true`.

This is partially covered in [the idle state has been removed](https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4#the-idle-state-has-been-removed) migration section, but I still want to double-check that this is an intended change and that I correctly understand how to migrate the following use-case (I assume this use-case is an often one).

### Use-case
We relied on `isLoading` to actually show a loader to the user. So, we have the following code:
```
<Loading isLoading={query1.isLoading || query2.isLoading || query3.isLoading}>
   /* actually render content here. Loader is rendered above the content unless all queries are loaded */
</Loafing>
```
Now if `query3` is disabled, the loading is infinite.
In docs the `enabled` option is described to be used in dependent queries. In our use-cases `query3` is indeed a dependent query, but it might be forever disabled, if we know it has no data (e.g. we load a Patient information and then load Doctor information if `patient.doctorId` is not null. But if  `patient.doctorId` is null, we never load doctor information).

So I guess, according to [Why two different states](https://tanstack.com/query/v4/docs/guides/queries#why-two-different-states) section we need to replace the code with something like:
```
<Loading isLoading={(query1.isLoading && query1.fetchStatus !== 'paused') || (query2.isLoading && query2.fetchStatus !== 'paused') || (query3.isLoading && query3.fetchStatus !== 'paused') }>
   /* actually render content here */
</Loafing>
```
Am I right? The previous version was much shorter and easier for developers to understand :)

My guess is that this use-case is used broadly, so it might deserve a dedicated section (or at least a few words) in the [migration guide](https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4)

### Your minimal, reproducible example

.

### Steps to reproduce

```
const query = useQuery('key', ()=>true, {enabled:false});
```
`query.isLoading` is now `true`

### Expected behavior

`query.isLoading` is `false`

### How often does this bug happen?

Every time

### Platform

Windows/Chrome

### react-query version

v4.2.1

**Comment by TkDodo** [comment]
You haven't seen all the other issues about this that were opened before?
- https://github.com/TanStack/query/issues/4019
- https://github.com/TanStack/query/issues/3975
- https://github.com/TanStack/query/issues/3925
