### ISSUE TITLE
React query doesn't work if the wifi is off

### ISSUE THREAD

**Issue by alimehasin** [TanStack/query#4062]
### Describe the bug

This issue might be a little bit weird, but react-query requires a wifi to be on to function correctly, if the wifi is off `isLoading` flag stays `true`, now this is absolutely OK and not a bug for the most users who uses react-query to send HTTP requests to fetch data from the server, however we want use react-query in desktop application that doesn't require internet connection therefor the wifi might be off.

### Your minimal, reproducible example

https://codesandbox.io/s/elegant-river-med5ru

### Steps to reproduce

1. Copy the code from codesandbox to your machine
2. Install deps
3. Turn off the wifi
4. Run the code

### Expected behavior

As a user, I expect the useQuery to run the async function even if there are no internet, but the async function doesn't get called and `isLoading` flag stays `true`

### How often does this bug happen?

Every time

### Platform

Tested on macOS

### react-query version

v4.2.1

### Additional context

I don't think that there are a lot of people who cares about this, but now react-query is an `Async state management`, so I hope to use react-query offline in desktop applications

**Comment by TkDodo** [comment]
Set `networkMode: 'always'` ?
https://tanstack.com/query/v4/docs/guides/network-mode#network-mode-always

**Comment by alimehasin** [comment]
Ohhh, I haven't seen this, thank for your response
