### ISSUE TITLE
Unable to test ReactQuery using React 17

### ISSUE THREAD

**Issue by WolfyUK** [TanStack/query#4073]
### Describe the bug

Similar to https://github.com/TanStack/query/issues/4022, I am unable to test React Query 4 in React 17 as per the [documented instructions](https://tanstack.com/query/v4/docs/guides/testing). This was originally observed from an in-place upgrade from React Query 3, which worked fine. To reproduce, clone https://github.com/WolfyUK/react-17-react-query-4-testing and execute `npm run test-query`:

```
 FAIL  src/Query.test.js
  ✕ useIasQuery (1042 ms)

  ● useIasQuery

    Timed out in waitFor after 1000ms.

      at waitFor (node_modules/@testing-library/react-hooks/lib/core/asyncUtils.js:64:13)
```

#### Dependencies

```json
{
    "@tanstack/react-query": "^4.2.1",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^12.1.5",
    "@testing-library/react-hooks": "^7.0.2",
    "@testing-library/user-event": "^13.5.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
}
```

### Your minimal, reproducible example

https://github.com/WolfyUK/react-17-react-query-4-testing

### Expected behavior

I expect the tests against React Query 4 `useQuery()` hooks to have the same results as those against React Query 3 on React 17.

### How often does this bug happen?

Every time

### react-query version

V4.2.1

**Comment by TkDodo** [comment]
I change the test execution to `react-scripts` in this reproduction, it works:

```diff
- "test-query": "jest './src/Query.test.js' -t 'useIasQuery'"
+ "test-query": "react-scripts test --testNamePattern=useIasQuery"
```

I put some log statements into the `waitFor` callback and they are never logged when run directly via `jest`. I'm totally not sure what is going on here, but it doesn't seem react-query related ?

**Comment by WolfyUK** [comment]
Thanks, @TkDodo. You helped point me in the right direction for the fix. Ejecting the `create-react-app` and comparing the jest config with what I was expecting identified that it was the `jest` configuration in `package.json` that was being ignored. Setting the `testEnvironment` to `jsdom` in the `test-query` script seems to resolve this issue for me in the updated repro, without needing to eject:

```diff
- "test-query": "jest './src/Query.test.js' -t 'useIasQuery'"
+ "test-query": "jest './src/Query.test.js' -t 'useIasQuery' --env=jsdom"
```

```diff
- },
-   "jest":{
-     "testEnvironment": "jsdom"
```

Rolling this out to my own solution via `jest.config.ts` works perfectly:

```diff
- // testEnvironment: "jest-environment-node",
+ testEnvironment: "jsdom",
```

**Comment by TkDodo** [comment]
glad I could help 🙌
