### ISSUE TITLE
ERROR when trying to install react query 

### ISSUE THREAD

**Issue by omershelef** [TanStack/query#4077]
### Describe the bug

after installing react query and just adding the react query client provide I am having the following error:
```
ERROR in ./node_modules/@tanstack/react-query/src/QueryClientProvider.tsx 6:8
Module parse failed: Unexpected token (6:8)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| import { ContextOptions } from './types'
| 
> declare global {
|   interface Window {
|     ReactQueryClientContext?: React.Context<QueryClient | undefined>

 
```

### Your minimal, reproducible example

test

### Steps to reproduce

1. install react query using npm install

### Expected behavior

should compile fine

### Platform

- OS

### react-query version

4.2.1

### TypeScript version

4.7.4

### Additional context

I created the project using typescript create-react-app template

**Comment by TkDodo** [comment]
> I created the project using typescript create-react-app template

then please create an open source repo and show the error there!

**Comment by TkDodo** [comment]
reopen once you have a reproduction
