### ISSUE TITLE
React is needed during testing

### ISSUE THREAD

**Issue by dgrcode** [TanStack/query#4080]
### Describe the bug

I'm trying to reproduce an issue in a different library (for reference issue: https://github.com/blitz-js/superjson/issues/196, PR: https://github.com/blitz-js/superjson/pull/197). For that I'm using `QueryClient` and `dehydrate`, but I'm getting the following error:
```bash
Cannot find module 'react' from 'node_modules/@tanstack/react-query/build/cjs/react-query/src/useQueries.js'

    Require stack:
      node_modules/@tanstack/react-query/build/cjs/react-query/src/useQueries.js
      node_modules/@tanstack/react-query/build/cjs/react-query/src/index.js
      src/index.test.ts
```

This is the whole test:
```ts
  const queryClient = new QueryClient();
  const input = { props: { dehydratedState: dehydrate(queryClient) } };

  const stringified = SuperJSON.stringify(input);
  const parsed: any = SuperJSON.parse(stringified);

  expect(parsed).toEqual(input);
```

### Your minimal, reproducible example

https://codesandbox.io/s/tanstack-query-react-dependency-bnkx3l?file=/src/index.test.js

### Steps to reproduce

1. Go to the reproduction [codesandbox](https://codesandbox.io/s/tanstack-query-react-dependency-bnkx3l?file=/src/index.test.js)
2. Go to the tests tab
3. The test doesn't pass

### Expected behavior

I think the test should pass, since it's not using any hook, just the `QueryClient` and `dehydrate`.

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Browser: Brave
- Version: 1.39.11

### react-query version

4.2.1

**Comment by TkDodo** [comment]
`QueryClient` and `dehydrate` are both part of the `query-core`. So if you only depend on that, the test works:

https://codesandbox.io/s/tanstack-query-react-dependency-forked-x2e2v9?file=/src/index.test.js

```diff
- import { QueryClient, dehydrate } from "@tanstack/react-query";
+ import { QueryClient, dehydrate } from "@tanstack/query-core";
```

basically: if you depend on `react-query`, you need react. If you don't need react, don't depend on react-query :)

**Comment by dgrcode** [comment]
Nice! Good to know :)

This is a weird place to say this, but I'm not sure there's a good place. Thanks for being so helpful all over the place: issues (this one), discussions (https://github.com/TanStack/query/discussions/4024), PR (https://github.com/TanStack/query/pull/4010), and even a StackOverflow Question I asked about NextJS SSR (https://stackoverflow.com/a/73342248/5452969). And those are just the places where you've helped me directly. I've definitely been helped by answers you left to other people. Thanks! 🙏
