### ISSUE TITLE
After migrate to v4 -> setQueryData not trigger re-render 

### ISSUE THREAD

**Issue by denys-utsekha** [TanStack/query#4106]
### Describe the bug

When I update the cache data using setQueryData, the components where this data is used are not re-rendered. 
In v3 everything worked fine.

v4 - not work - https://codesandbox.io/s/xenodochial-saha-814hxw?file=/src/App.js
v3 - the same code works well - https://codesandbox.io/s/romantic-galileo-zi8t0k?file=/src/App.js

### Your minimal, reproducible example

https://codesandbox.io/s/xenodochial-saha-814hxw?file=/src/App.js

### Steps to reproduce

1. Click any button "Update this title"
2. After click we update the cache
3. But we don't see any changes in page
4. Only if we manual update local state by click "Re-render all page" - we can see update cache

### Expected behavior

After update cache, components where this cache are used must be re-rendered.

### How often does this bug happen?

Every time

### Platform

macOs

### react-query version

4.2.1

### TypeScript version

4.8.2

**Comment by TkDodo** [comment]
you directly mutating an item inside the queryCache. That might or might not have worked in the past, but updates should always be performed immutably.

here's a fixed sandbox: https://codesandbox.io/s/epic-swanson-h73k1b?file=/src/App.js

```
    queryClient.setQueryData(["todos"], (oldData) => {
      return oldData.map((item) => {
        if (item.id === id) {
          return {
            ...item,
            title: "Updated"
          };
        }
        return item;
      });
    });
```

if you don't like immutable updates, try [immer](https://github.com/immerjs/immer)
