### ISSUE TITLE
React Query v3 Examples and links not working

### ISSUE THREAD

**Issue by patsantos** [TanStack/query#4108]
### Describe the bug

The examples section in v3 of the docs isn't loading and the links to GitHub 404. See this page for example: https://react-query-v3.tanstack.com/examples/basic

### Your minimal, reproducible example

https://react-query-v3.tanstack.com/examples/basic

### Steps to reproduce

Open page at https://react-query-v3.tanstack.com/examples/basic and notice the example doesn't load. Click "View Source" link and see page 404s.

### Expected behavior

The examples should load and the links should be active.

### Platform

macOS 12.5.1
Chrome 104.0.5112.101
Safari 15.6.1

### react-query version

NA

**Comment by TkDodo** [comment]
fix is already merged but needs to be deployed. Replace "main" with "v3" in the links in the meantime

**Comment by MitchTalmadge** [comment]
For now find examples here: https://github.com/TanStack/query/tree/main/examples/react

**Comment by TkDodo** [comment]
We fixed it yesterday
