### ISSUE TITLE
Update base 64 image in page

### ISSUE THREAD

**Issue by shiv-raj45** [TanStack/query#4132]
### Describe the bug

I'm working on a table view where images are place besides their name when I update the list the API request is made to update the row of table and when the PUT request is successful .I update table row with  previously passed form data 
 to query cache.Other columns are updated accordingly but image is not updated.Is there any solution to this problem.On the other hand Is there any anything to do with browser cached image?Any response would be helpful

### Your minimal, reproducible example

Sorry this is production code

### Steps to reproduce

try to update query cached image

### Expected behavior

I expect react query to update recent image 

### Platform

chrome

### react-query version

3.39.0

**Comment by TkDodo** [comment]
> Sorry this is production code

It is your duty to provide a minimal example that shows the issue so that we can rule out anything in your specific setup. If it's your production code, then write something new in codesandbox that shows the issue that is not production code 🤷
