### ISSUE TITLE
[Docs] Comparison page is broken

### ISSUE THREAD

**Issue by iicdii** [TanStack/query#4134]
### Describe the bug

The comparison section of the docs shows an error. https://tanstack.com/query/v4/docs/comparison

### Your minimal, reproducible example

https://tanstack.com/query/v4/docs/comparison

### Steps to reproduce

1. Go to https://tanstack.com/query/v4/docs/comparison

### Expected behavior

The comparison page should load.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/4951716/189015407-e4086349-4b38-4bf4-94c2-8491e1c5996f.png)

### Platform

- OS: Window
- Browser: Chrome

### react-query version

v4

**Comment by maddhruv** [comment]
Looks like some issues with mdx plugin not able to read through the comments in comparison.md
![image](https://user-images.githubusercontent.com/18121502/189258637-51b8f494-b8da-4041-b0e1-f6caf6e18231.png)


Raised a PR to fix this - https://github.com/TanStack/query/pull/4137

**Comment by iicdii** [comment]
![image](https://user-images.githubusercontent.com/4951716/189347147-c3154c53-c584-4bca-b2dd-6e1e47860ad0.png)

It seems that markup is broken.
