### ISSUE TITLE
Docs inconsistent in how to handle app refocus in React Native

### ISSUE THREAD

**Issue by tibbe** [TanStack/query#4135]
### Describe the bug

How to deal with app refocus (i.e. App moving from background to active state) is documented twice:
- https://tanstack.com/query/v4/docs/react-native
- https://tanstack.com/query/v4/docs/guides/window-focus-refetching#managing-focus-in-react-native

The suggested code differs in the two docs, making me wonder which is the recommended approach. Could the code examples be unified?

### Your minimal, reproducible example

Documentation issue

### Steps to reproduce

Go to:
- https://tanstack.com/query/v4/docs/react-native
- https://tanstack.com/query/v4/docs/guides/window-focus-refetching#managing-focus-in-react-native

Compare code examples:

```ts
import { focusManager } from '@tanstack/react-query'

function onAppStateChange(status: AppStateStatus) {
  if (Platform.OS !== 'web') {
    focusManager.setFocused(status === 'active')
  }
}

useEffect(() => {
  const subscription = AppState.addEventListener('change', onAppStateChange)

  return () => subscription.remove()
}, [])
```

vs

```ts
import { AppState } from 'react-native'
import { focusManager } from '@tanstack/react-query'

focusManager.setEventListener(handleFocus => {
  const subscription = AppState.addEventListener('change', state => {
    handleFocus(state === 'active')
  })

  return () => {
    subscription.remove()
  }
})
```

### Expected behavior

Consistent advice on how to deal with app focus in React Native.

### How often does this bug happen?

Every time

### Platform

- OS: all
- Browser: React Native

### react-query version

v3.39.1

**Comment by TkDodo** [comment]
@arnaudbzn wrote that documentation I believe. If you know what the right way is, let's please streamline it.

**Comment by varwasabi** [comment]
The instructions posted here: [App State Docs](https://tanstack.com/query/v4/docs/react-native) are correct and work as intended.
