### ISSUE TITLE
Configurations using setQueryDefaults for a query is not working. 

### ISSUE THREAD

**Issue by rishabh2712** [TanStack/query#4143]
### Describe the bug

Setting cachetime and staletime for a query using setQueryDefaults is not working. Looking into the console, the cachetime still show default 300000ms. 

### Your minimal, reproducible example

https://codesandbox.io/s/charming-haze-2y4bzz?file=/src/index.js

### Steps to reproduce

Have added the setQueryDefaults in the given example

### Expected behavior

Ideally setQueryDefaults options should work just the way it does for useQuery 

### Platform

Browser - Chrome 

### react-query version

v3.5

**Comment by TkDodo** [comment]
a query picks up its defaults when it is created. Changes to the defaults after that have no effect on already created queries, as changing default settings also does not re-render existing queries to inform them about that change.

If you move the call to `setQueryDefaults` to before the query is created, it works as expected. Calling `setQueryData` also creates a query.

**Comment by rishabh2712** [comment]
Had to use the setQueryDefaults as suggested by you in one of the discussions, to set the options for a query  like cacheTime or staleTime. As setQueryData doesn't accept such config.
