### ISSUE TITLE
Upgrading to latest version [4.3.4] even we have defined the version 4.2.3 in package.json

### ISSUE THREAD

**Issue by chaithrabhalli** [TanStack/query#4152]
### Describe the bug

When we define a particular version in package.json it's not installing same version , it's straight away installing latest build version please check this issue

### Your minimal, reproducible example

   ` "@tanstack/query-core": {       "version": "4.3.4",       "resolved": "https://registry.npmjs.org/@tanstack/query-core/-/query-core-4.3.4.tgz",       "integrity": "sha512-NLAe3j5Vk1yYEtoPP5fPGPjRzkZPx67KUM3f14L3InziJZJ0wVecCh7uKfgYkbRKJSeq6PlbND7iuCGdTplN6Q=="     },     "@tanstack/react-query": {       "version": "4.3.4",       "resolved": "https://registry.npmjs.org/@tanstack/react-query/-/react-query-4.3.4.tgz",       "integrity": "sha512-IiAo+B8bxphEpO7xwLQaCptd2rY4Ef3pW1q9J3pT66G+J/st4QpGQ+cSm9iESp9ccRy1YNUk3klk/hQtWewl6g==",       "requires": {         "@tanstack/query-core": "4.3.4",         "use-sync-external-store": "^1.2.0"       }     }
`
### Steps to reproduce

define 4.2.3 in package.json
delete node modules
do npm install 
it will install 4.3.4 instead 4.2.3

### Expected behavior

it should install 4.2.3 version

### Platform

MacOS

### react-query version

4.2.3

**Comment by twentyonedot** [comment]
Facing the same issue.

**Comment by TkDodo** [comment]
I just tried this and it installed v4.3.2 for me. We also use strict dependencies to cross-reference versions between our own packages.

We're just publishing packages according to semver to npm. How they are being picked up and installed is not in our control.

What does your package-lock.json file say?

**Comment by chaithrabhalli** [comment]
### ./node_modules/@tanstack/react-query/build/lib/reactBatchedUpdates.mjs
Can't import the named export 'unstable_batchedUpdates' from non EcmaScript module (only default export is available)

in package.json i have defined 4.2.3 , if i install node modules ` "@tanstack/query-core": {
      "version": "4.3.4",
      "resolved": "https://registry.npmjs.org/@tanstack/query-core/-/query-core-4.3.4.tgz",
      "integrity": "sha512-NLAe3j5Vk1yYEtoPP5fPGPjRzkZPx67KUM3f14L3InziJZJ0wVecCh7uKfgYkbRKJSeq6PlbND7iuCGdTplN6Q=="
    },
    "@tanstack/react-query": {
      "version": "4.3.4",
      "resolved": "https://registry.npmjs.org/@tanstack/react-query/-/react-query-4.3.4.tgz",
      "integrity": "sha512-IiAo+B8bxphEpO7xwLQaCptd2rY4Ef3pW1q9J3pT66G+J/st4QpGQ+cSm9iESp9ccRy1YNUk3klk/hQtWewl6g==",
      "requires": {
        "@tanstack/query-core": "4.3.4",
        "use-sync-external-store": "^1.2.0"
      }
    },`
it's 4.3.4

**Comment by TkDodo** [comment]
sorry now you're mixing different things here. I can't tell you much anyways without knowing which bundler in which version you are using. And yes, a reproduction is needed. Feel free to re-open if you can provide one.
