### ISSUE TITLE
Not able to build Vite (SSR) with react-query

### ISSUE THREAD

**Issue by duerdod** [TanStack/query#4215]
### Describe the bug

This small example fails when running `yarn serve` (essentially `yarn build && yarn serve`): https://github.com/duerdod/react-query-vitejs.git. 

The build works fine when removing these lines https://github.com/duerdod/react-query-vitejs/commit/ef110a6d4fb1b93c72448e1d48278a782e9324c4#diff-1ba718c1eb8aa39cd20c2562d92523068c734d75f54655e97d652b992d9b4259R71-R77.

Issue seems to be react-query is loading the development version of react-dom: 
<img width="1298" alt="Screenshot 2022-09-24 at 18 30 53" src="https://user-images.githubusercontent.com/30701650/192108811-3a12269f-14ac-4acf-8c26-0c6b522df7d7.png">

Basically a reproduction of this ol badboy: https://github.com/facebook/react/issues/13276#issuecomment-408232369

### Your minimal, reproducible example

https://github.com/duerdod/react-query-vitejs.git

### Steps to reproduce

1. Clone https://github.com/duerdod/react-query-vitejs.git
2. Run `yarn && yarn serve`
3. Go to http://localhost:7456/

### Expected behavior

React-query to load the production version of react-dom and not fail to build

### How often does this bug happen?

Every time

### Platform

macOS

### react-query version

4.5.0

### TypeScript version

4.8.2

### Additional context

Same issue on previous react-query versions.
`yarn dev:server` works fine (I guess it's because all deps are loaded in development)

**Comment by TkDodo** [comment]
As discussed on Discord, react-query doesn't decide which version (prod or dev) it loads of react-dom - we just import react like everybody else 🤷‍♂️. So it seems more like an issue for the bundler...
react-query has react dom as optional peerDependency because you could also use it with react native - Maybe the bundler doesn't like that

**Comment by TkDodo** [comment]
anything we can do here @duerdod ?

**Comment by TkDodo** [comment]
closed because stale
