### ISSUE TITLE
v2 documentation loading v3 documentation

### ISSUE THREAD

**Issue by twolfson** [TanStack/query#4249]
### Describe the bug

Love the repo and thank you for your work! It looks like the https://react-query-v2.tanstack.com/guides/mutations is loading the content from https://react-query-v3.tanstack.com/guides/mutations

i.e. v2 doesn't have `mutateAsync` yet it's documented (and was a red herring for me)

https://github.com/TanStack/query/blob/v4.8.0/docs/guides/migrating-to-react-query-3.md#mutationmutate-no-longer-return-a-promise

As a workaround, I can navigate to https://web.archive.org/web/20210307044920/https://react-query-v2.tanstack.com/docs/guides/mutations to get the proper content, but that seems non-ideal

I'm not sure what your LTS is for v2 docs, so understandable if this isn't a priority =/

### Your minimal, reproducible example

https://react-query-v2.tanstack.com/guides/mutations

### Steps to reproduce

1. Navigate to https://react-query-v2.tanstack.com/guides/mutations

### Expected behavior

Expect documentation to not mention `mutateAsync` yet it does

Expect documentation to match https://web.archive.org/web/20210307044920/https://react-query-v2.tanstack.com/docs/guides/mutations

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/902488/193367369-63df2082-2544-46e6-b6d6-84394b098d86.png)

### Platform

macOS Firefox 105.0.1

### react-query version

v2.26.4

**Comment by timkindberg** [comment]
Can also view them here as a workaround: https://github.com/TanStack/query/tree/2.x/docs/src/pages/docs

**Comment by TkDodo** [comment]
I think the v2 site is now completely down. The last v2 release happened over 2 years ago. I would consider it dead (we're working on v5 already). Please look at the markdown files in the repo as linked above.
