### ISSUE TITLE
solid-query does not work in NX monorepo

### ISSUE THREAD

**Issue by Stevedohh** [TanStack/query#4250]
### Describe the bug

The QueryClientProvider from solid-query does not work properly in NX monorepo.

When I'm trying to use QueryClientProvider I see the "React is not defined" error

![image](https://user-images.githubusercontent.com/59619468/193376486-451af570-d72f-406e-ac25-3fd3ac992eac.png)

### Your minimal, reproducible example

https://github.com/Stevedohh/nx-with-solid-query

### Steps to reproduce

1. Go to https://github.com/Stevedohh/nx-with-solid-query and clone it
2. Run `npm i` in root directory
3. Run `npm run start-solid-app`
4. Open the runnable app
5. Observe "Uncaught ReferenceError: React is not defined" in console tab

### Expected behavior

As a user, I want not to see any errors in the console. And works with the library in a proper way.

### How often does this bug happen?

Every time

### Platform

Windows 10

### react-query version

@tanstack/solid-query ^4.8.0

### TypeScript version

~4.8.2

### Additional context

The App component with QueryClientProvider located in apps/solid-app/src/App.tsx

**Comment by TkDodo** [comment]
Could this be related to:
- https://github.com/TanStack/query/pull/4211#issuecomment-1256869249

and:
- https://github.com/solidjs/vite-plugin-solid/issues/57

?

**Comment by Stevedohh** [comment]
> Could this be related to:
> 
> * [feat(solid-query): Solid Query Adapter for TanStack Query #4211 (comment)](https://github.com/TanStack/query/pull/4211#issuecomment-1256869249)
> 
> and:
> 
> * [2.3.7 revert breaking solid-query package solidjs/vite-plugin-solid#57](https://github.com/solidjs/vite-plugin-solid/issues/57)
> 
> ?

Unfortunately no. Changing versions of "vite-plugin-solid" and "vite" did not help. Any ideas what it might be?

**Comment by GertValiakhmetov** [comment]
@Stevedohh I think that the main problem is in the pad between the chair and the monitor.

**Comment by Stevedohh** [comment]
Regarding this issue
https://github.com/solidjs/vite-plugin-solid/issues/41
I excluded deps in vite config and it helps

Thanks @TkDodo for mentioning related issues!

**Comment by ardeora** [comment]
Glad that helped! I also have added a PR here https://github.com/TanStack/query/pull/4255 that will make solid-query work by default without using the excluded deps fix
