### ISSUE TITLE
Error in an Example in the React Query Section

### ISSUE THREAD

**Issue by gssakash** [TanStack/query#4256]
### Describe the bug

The React query example part of the docs website does not seem to be functioning and returns a 502 Bad gateway error.

### Your minimal, reproducible example

https://tanstack.com/query/v4/docs/examples/react/react-router

### Steps to reproduce

1. Open the Page here https://tanstack.com/query/v4/docs/examples/react/react-router
2.  Notice the Example displayed through Code Sandbox

### Expected behavior

The example has to show a valid way of using React Router with React Query

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/52027687/193438679-06efcefb-1c2d-4b05-bdc1-dc7b1f3de1c4.png)

### Platform

Windows 10 (64-bit)
Chrome 106.0.5249.91 
Firefox 105.0.1 (64-bit)
Brave 1.44.105

### react-query version

NA

**Comment by TkDodo** [comment]
must be something with codesandbox. It works fine if you just fork the example, which creates a new VM.

**Comment by TkDodo** [comment]
example is working again now.
