### ISSUE TITLE
devtools is not working

### ISSUE THREAD

**Issue by mujaen** [TanStack/query#4278]
### Describe the bug

I used it in version 3 without any problems
Trying to use devtools in version 4...
This kind of problem has occurred

I think it's a Bundler crash...

React CRA is fine.

### Your minimal, reproducible example

https://codesandbox.io/s/reverent-maxwell-wighue?file=/src/index.js:335-477

### Steps to reproduce

1. set up devtools
2. start react server

### Expected behavior

as-is:
detools is not working

to-be:
works for me

### Screenshots or Videos

![스크린샷 2022-10-05 오후 7 13 13](https://user-images.githubusercontent.com/36294103/194276409-84bce26a-db9a-4fe3-b47f-5b52131933b9.png)

### Platform

- Web Browser: Chrome, Firefox, Safari, Edge
- React: v16.13.0

### react-query version

v4.10.1

### TypeScript version

v4.7.4

**Comment by TkDodo** [comment]
are you aware that the devtools work just fine in the sandbox reproduction you provided 🤨?
