### ISSUE TITLE
Devtools appear inverted when page direction is rtl

### ISSUE THREAD

**Issue by Omar-Awawdeh** [TanStack/query#4282]
### Describe the bug

When the direction of the page or a parent element is rtl the devtools are inverted.

### Your minimal, reproducible example

https://codesandbox.io/s/angry-sun-2qbl4j?file=/src/App.tsx

### Steps to reproduce

1. Add `dir="rtl"` on the html body.
2. Open the dev tools.

### Expected behavior

Dev tools should appear the same despite the body's direction as English afaik is the only supported language for the dev tools right now 

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/72731329/194596746-f0aa69a5-e9a3-4ea7-b3da-c418eb3e330a.png)

### Platform

- OS: WSL2 Ubuntu on windows
- Browser: All browsers

### react-query version

v4.10.1

**Comment by aliakbarazizi** [comment]
Before release of the new pull request you can use `panelProps={{ dir: "ltr" }}` as a prop of devtools
