### ISSUE TITLE
docs: testing useInfiniteQuery uses wrong example 

### ISSUE THREAD

**Issue by arnassavickas** [TanStack/query#4319]
### Describe the bug

Docs that describe how to test `useInfiniteQuery` use a failing example.
https://tanstack.com/query/v4/docs/guides/testing#testing-load-more--infinite-scroll

It is stated, that after calling `fetchNextPage()`, it should be enough to await `isFetching`, and then the data can be asserted like so:
```ts
result.current.fetchNextPage();

await waitFor(() => expect(result.current.isFetching).toBe(true)); // test fails: false !== true
await waitFor(() => expect(result.current.isFetching).toBe(false));

expect(result.current.data.pages).toStrictEqual(/* some response */);
```
However, this example fails (only in one local setup resulted in working but flaky tests).

What works is awaiting and asserting on the data itself.
```ts
result.current.fetchNextPage();

await waitFor(() => expect(result.current.data.pages).toStrictEqual(/* some response */));
```

Is there something wrong with my setup, or do the docs lie?

### Your minimal, reproducible example

https://codesandbox.io/s/useinfinitequery-failing-tests-51yel3?file=/src/hooks/queries.test.tsx

### Steps to reproduce

1. Go to `Tests` tab in the codesandbox
2. See how the `fetches more pages failing %s` tests fail

### Expected behavior

Tests should work, or docs should be fixed.

### How often does this bug happen?

Every time

### Platform

- macOS
- Chrome
- Codesandbox

### react-query version

v4.10.3

**Comment by TkDodo** [comment]
I think we discussed this on discord as well. Please feel free to update the docs.

**Comment by arnassavickas** [comment]
@TkDodo I will 👍 
But I was wondering, why asserting for `isFetching` doesn't work?
