### ISSUE TITLE
graphql-request query stuck on loading state

### ISSUE THREAD

**Issue by Miigaarino** [TanStack/query#4320]
### Describe the bug

Hello, im using graphql-request with react-query.
Below is my getProjects query
```
const { data, isLoading, error } = useQuery(
    ["projects"],
    async () => await request<QueryData>(URL, ProjectsQuery)
  );
```

The query isLoading is true, but isFetching is false and stuck on the paused state on react-query-devtools
While investigating the problem found out that official react-query docs graphql-request page was having the same problem as mine.

Press link to see:
https://tanstack.com/query/v4/docs/examples/react/basic-graphql-request

Anyone has faced this kind of problem?

### Your minimal, reproducible example

https://codesandbox.io/s/github/tanstack/query/tree/main/examples/react/basic-graphql-request

### Steps to reproduce

Go to https://codesandbox.io/s/github/tanstack/query/tree/main/examples/react/basic-graphql-request
Open up console - no request getting send
React-query-devtools - query is on paused state

### Expected behavior

Should send request

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="650" alt="image" src="https://user-images.githubusercontent.com/48021917/195776845-f8cbe9e7-e714-4345-9c25-9c1be68f396d.png">

### Platform

only on Chrome
macOS 

### react-query version

v4.2.3

### TypeScript version

4.7.4

**Comment by TkDodo** [comment]
The example works fine for me. The query will be in `paused` state when there is no internet connection? Maybe there were some connection problems?

**Comment by Miigaarino** [comment]
> The example works fine for me. The query will be in `paused` state when there is no internet connection. Maybe there were some connection problems?

Hello, no connection problems occuring, The example is stuck on paused only on Chrome browser, works fine on different browsers, so is my project.

**Comment by TkDodo** [comment]
maybe you have network disabled in the chrome devtools or something. anyways, not an issue.
