### ISSUE TITLE
webpack loaders with nuxt-bridge

### ISSUE THREAD

**Issue by esamani77** [TanStack/query#4329]
### Describe the bug

Hey there, I tried to use vue-query with nuxt framework with nuxt-bridge version.
But I faced with this problem, What should I do?

https://i.postimg.cc/kXCVJKK4/195976499-df780ec8-84e2-4fa1-a789-0a38c8cf8940.png

### Your minimal, reproducible example

https://i.postimg.cc/kXCVJKK4/195976499-df780ec8-84e2-4fa1-a789-0a38c8cf8940.png

### Steps to reproduce

install nuxt 2
migrate to nuxt-brige
install vue-query and try to use it.

### Expected behavior

I expected it works.

### How often does this bug happen?

Every time

### Screenshots or Videos

![Uploading 195976499-df780ec8-84e2-4fa1-a789-0a38c8cf8940.png…]()

### Platform

-OS: mac-os
-browser: everything
-version: latest

### react-query version

latest

### TypeScript version

latest

**Comment by TkDodo** [comment]
A reproduction is a runnable program that shows the issue, _not_ a screenshot. codesandbox is great for that. Please provide a reproduction or we'll close this issue. Thanks.

**Comment by DamianOsipiuk** [comment]
Try adding this to your nuxt config:
```ts
import { defineNuxtConfig } from "@nuxt/bridge";

export default defineNuxtConfig({
  build: {
    transpile: ["vue-query", "vue-demi"],
  }
})
```
