### ISSUE TITLE
queryClient.refetchQueries(queryKey)  refetches disabled queries

### ISSUE THREAD

**Issue by yegao** [TanStack/query#4331]
### Describe the bug

The official documentation describing the enabled option :
```
When enabled is false:
...
The query will ignore query client invalidateQueries and refetchQueries calls that would normally result in the query refetching.
```
But In my project queryClient.refetchQueries(queryKey)  refetches disabled queries。

### Your minimal, reproducible example

none

### Steps to reproduce

1. Create a `query` with `useQuery` and set `enabled` option to `false`.
2. Create a `queryClient` with `useQueryClient`.
3. Invalidate this `query` with `refetchQueries`.

### Expected behavior

The disabled queries (`enabled: false`) would **not** `refetch` when I use `refetchQueries`

### Platform

OS: macOs
Browser: Not related

### react-query version

^3.39.2

### TypeScript version

^4.7.4

**Comment by TkDodo** [comment]
This should be fixed in v4:
- https://github.com/TanStack/query/pull/3223

**Comment by LetItRock** [comment]
hey @TkDodo! 👋 is there a workaround for this bug in v3?

**Comment by TkDodo** [comment]
we haven't back-ported the fix to v3. Is there anything stopping you from upgrading to v4 ?

**Comment by LetItRock** [comment]
@TkDodo I'm not sure how much effort it might be and how many issues after it might bring. I'll go through the migration guide first then. But yeah, we would like to migrate anyway.
