### ISSUE TITLE
bug: Hydration logic error when prefetching on the server for existing query on navigate to subroute

### ISSUE THREAD

**Issue by bennettdams** [TanStack/query#4335]
### Describe the bug

Under specific circumstances, there is some error in the hydration logic.

The setup is the following:
 - Index route that fetches data on the client
 - Navigate to a dynamic subroute that prefetches the same query on the server
 - -> Error!

The result is the generic, well-known error message: "Can't perform a React state update on an unmounted component.":

![image](https://user-images.githubusercontent.com/29319414/196285111-ec3aef87-c5ab-431f-91b8-e167b0710e9e.png)

I know that this is not a huge issue in itself, but maybe this still relevant for other parts of the logic and worth investigating, especially because of some weird quirks I'm describing below.

### Your minimal, reproducible example

https://github.com/bennettdams/bug-react-query-hydration

### Steps to reproduce

1. `npm i`
2. `npm run dev`
3. Go to <http://localhost:3000>
4. Click on "Dynamic Subroute"
5. Error in console:
   ```
   Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
   at Home
   ```
When you've seen the error message once, you need to reload the page on the home route to see it again.

The reproduction is based on "Create Next App" with one API endpoint and the typical React Query integration.

You can follow all steps here if needed:

https://github.com/bennettdams/bug-react-query-hydration/commits/main

![image](https://user-images.githubusercontent.com/29319414/196285450-fb5613df-ae9e-4ff1-af81-0666aac3b009.png)

### Expected behavior

No error log 😅

### How often does this bug happen?

Every time

### Platform

- OS: Linux (Ubuntu) and Windows 10
- Browser: Chrome, Firefox

### react-query version

v4.12.0

### TypeScript version

v4.8.4

### Additional context

This error only occurs with React `v17`.

#### Weird quirks

You can make small changes in the reproduction that will make the error go away (changing only **one** of the following is enough!):

- see `pages/_app.tsx`
  - Adding an additional `<Link />`
    or
  - Wrapping the main component (`<Component {...pageProps} />`) in a `div`

or

- see `pages/user-gssp/[userId].tsx`
  - Disable prefetching (`queryClient.prefetchQuery(...)`)

or

- see `pages/index.tsx`
  - Disable fetching data on the client (`... useQuery(['user', { userId: '1' }], fetchUser, ...`)

#### Call stack

Maybe this helps already: Debugging shows that the last running app code before the error is the hydration logic, which tries to `setState` of the dehydrated query:

https://github.com/TanStack/query/blob/main/packages/query-core/src/hydration.ts#L148

![image](https://user-images.githubusercontent.com/29319414/196286946-410162fc-1ed2-4ec5-b139-5cca5fa14d15.png)

I think the actual error log is related to some shenanigans in a `useMemo` where `hydrate` is called:

https://github.com/TanStack/query/blob/main/packages/react-query/src/Hydrate.tsx#L23

#### Next.js bug?
Maybe this is even a bug in Next.js' hydration logic, but I have no idea how to find that out.

**Comment by TkDodo** [comment]
Not entirely sure why this is happening. According to the react 18 discussion:
- https://github.com/reactwg/react-18/discussions/82

This warning was mostly a false-positive, and the workarounds introduced by tracking things with a ref did more harm than good.

We've removed all `isMountedRef` workarounds with v4 because of that.

Our subscriptions are all handled by `useSyncExternalStore`, where we _do_ unsubscribe properly.

setting state on the query is fine, it doesn't do anything really. it's informing the subscriptions that might trigger re-renders in react consumers. In react 17, this has to happen via `useEffect`. We use the `useSyncExternalStore` shim from react for that, and in there, it seems that [`forceUpdate` is called in an effect](https://github.com/facebook/react/blob/9143864ae1f6d3e8158e5670f5a8623dc6c47dbf/packages/use-sync-external-store/src/useSyncExternalStoreShimClient.js#L108), which I think can lead to that warning in react17 if the component unmounted in between.

I'm unsure if we can do anything here tbh, or if it's even worth doing something because the warning hasn't been "fixed" by react, it has just been removed because it doesn't matter ...

**Comment by bennettdams** [comment]
I think these are valid points. What is so weird in my opinion are the quirks described in the "Additional context" section above:

> see `pages/_app.tsx`
Adding an additional `<Link />`
or
Wrapping the main component (`<Component {...pageProps} />`) in a `div`

Doing one of these makes it so the "error" is not shown anymore - and I personally would really like to know why. Again, maybe this is a Next.js bug at this point?

---

> it seems that [forceUpdate is called in an effect](https://github.com/facebook/react/blob/9143864ae1f6d3e8158e5670f5a8623dc6c47dbf/packages/use-sync-external-store/src/useSyncExternalStoreShimClient.js#L108), which I think can

Not sure if it matters, but the error is not coming from the code in the `useEffect` you have linked above, but the [invocation of the `forceUpdate` inside the `handleStoreChange`](https://github.com/facebook/react/blob/9143864ae1f6d3e8158e5670f5a8623dc6c47dbf/packages/use-sync-external-store/src/useSyncExternalStoreShimClient.js#L120).

![image](https://user-images.githubusercontent.com/29319414/196442148-828224a8-17a1-41c2-851e-f7b816e71c69.png)

**Comment by TkDodo** [comment]
okay but does that mean it's some sort of issue with `useSyncExternalStore` ?

**Comment by bennettdams** [comment]
@TkDodo I don't know. My gut tells me it has something to do with the way the hydration is initialized and **not** how `useSyncExternalStore` itself is implemented, because changing HTML elements in the root `_app.tsx` makes the error go away (see "Weird quirks" in the issue description above).



But I guess only someone with more knowledge about how React Query's hydration, Next.js' hydration and React's hydration plays together needs to look at this. Not sure if it is worth keeping it up as a React Query issue though, as I don't even know if this is specific to React Query.

**Comment by TkDodo** [comment]
We'll drop support for React17 with the next major release:
- https://github.com/TanStack/query/discussions/4252

as a side effect, we'll also get rid of the uSES shim and the warning will not exist anymore in React18. I don't see much reason to track this as a bug here.
