### ISSUE TITLE
Inconsistent `isLoading` when using multiple `mutateAsync` calls

### ISSUE THREAD

**Issue by knyzorg** [TanStack/query#4338]
### Describe the bug

Writing code that calls `mutateAsync` in parallel causes inconsistencies with `isLoading`, where it reports that it is no longer loading when that is not yet the case.

### Your minimal, reproducible example

https://codesandbox.io/s/damp-snow-ueyjg5?file=/src/App.js

### Steps to reproduce

1. Go to codesandbox
2. Press the button

### Expected behavior

I expect "isLoading, false" to be printed after all the other console statements, but that is not what happens:

![image](https://user-images.githubusercontent.com/10255546/196504845-2cfb844b-8bdc-4fd5-a6c0-923a03e56329.png)

### How often does this bug happen?

Often

### Platform

Firefox, Windows, latest

Didn't test other browsers

### react-query version

4.12

**Comment by TkDodo** [comment]
Every invocation of `mutate` or `mutateAsync` creates a new observer, and the `useMutation` instance on the component only tracks the "latest" invoked mutation. If that mutation is finished, you'll see false even if other instances are still running.

This is documented here:

https://tanstack.com/query/v4/docs/guides/mutations#consecutive-mutations

I realised the documentation is for the `onSuccess` callback, where it clearly says:

```
// Will execute only once, for the last mutation (Todo 3),
// regardless which mutation resolves first
```

but awaiting a mutateAsync is pretty much the same as having onSuccess for mutate. Maybe we should make that better in the docs?

---

anyways, potential solutions:

- give each invocation their own `useMutation` instance, thus avoiding to call `mutateAsync` twice on the same component.
- give `useMutation` a `mutationKey` and track the loading state for those mutations via
```
useIsMutating(myKey)
```

here is a fork of your sandbox with the `useIsMutating` fix:

https://codesandbox.io/s/agitated-cherry-3d2c28?file=/src/App.js

you can see that it prints the number of running mutations.

**Comment by knyzorg** [comment]
Interesting. Thanks for the solution!
