### ISSUE TITLE
The order in which object properties are defined -  effects  on query key.

### ISSUE THREAD

**Issue by oneznamov** [TanStack/query#4347]
### Describe the bug

Based on your [documentation](https://tanstack.com/query/v4/docs/guides/query-keys#query-keys-are-hashed-deterministically) -  order of properties in object no matter. But in my case - the order in which object properties are defined -  effects  on query key.

### Your minimal, reproducible example

Full describe in reproduce section

### Steps to reproduce

In both example below - same query with same params called in two separate components, but at the same time.

Some definition which used in our code & below
```javascript
const appsInventoryRetrieveKeys: unknown[] = ['apps', 'inventory', 'retrieve'];
const entityId = '090515e2-a03a-465d-8301-9d663e64360b';

app.fingerprintID.app === 'd99ac760-0ad6-11ea-9b04-c7455c63d59e'
```

## Example when it working correctly:

1) Define entity id 
```javascript
const id = new ItemID();
        id.app = app.fingerprintID.app;
        id.id = entityId;
```

2) Use it like queryKeys
```javascript
appsInventoryRetrieveKeys.concat(id)
```

3) Repeat steps 1 & 3. in other component 

4) Result 
<img width="839" alt="image" src="https://user-images.githubusercontent.com/100121487/196907084-54fb96eb-8701-4bb9-8b31-5b2186d63a35.png">

Query hash from query dev tools 
```javascript
queryHash: "[\"apps\",\"inventory\",\"retrieve\",{\"_app\":\"d99ac760-0ad6-11ea-9b04-c7455c63d59e\",\"_id\":\"090515e2-a03a-465d-8301-9d663e64360b\"}]"
```

## Example when works wrong: 

1) Define entity id 
```javascript
const id = new ItemID();
        id.app = app.fingerprintID.app;
        id.id = entityId;
```

2) Use it like queryKeys
```javascript
appsInventoryRetrieveKeys.concat(id)
```

3) Define entity id  in other component , but properties in other order.
```javascript
const id = new ItemID();
        id.id = entityId;   // just switch it order
        id.app = app.fingerprintID.app;  // just switch it order 
```

4) Use it like queryKeys
```javascript
appsInventoryRetrieveKeys.concat(id)
```

5) Result 
In this case we already have 2 different queries , with different query hash

<img width="841" alt="image" src="https://user-images.githubusercontent.com/100121487/196908399-bdb03525-f0b8-4898-858a-ca179b07627f.png">

```javascript
queryHash: "[\"apps\",\"inventory\",\"retrieve\",{\"_app\":\"d99ac760-0ad6-11ea-9b04-c7455c63d59e\",\"_id\":\"6fef6f95-feee-4653-a4e9-57866c921a12\"}]"
```

<img width="841" alt="image" src="https://user-images.githubusercontent.com/100121487/196908688-cf3182ba-baac-4a69-8e63-277f1236c54a.png">

```javascript
queryHash: "[\"apps\",\"inventory\",\"retrieve\",{\"_id\":\"6fef6f95-feee-4653-a4e9-57866c921a12\",\"_app\":\"d99ac760-0ad6-11ea-9b04-c7455c63d59e\"}]"
```

### Expected behavior

I expect that order of setting object properties - does not change ready query hash (query key)

### How often does this bug happen?

Every time

### Platform

- OS: MacOs 12.5.1
- Chrome: Version 106.0.5249.103 (Official Build) (x86_64)

### react-query version

4.7.2

### TypeScript version

4.8.4

### Additional context

```json
"@tanstack/query-core": "^4.7.2",
"@tanstack/react-query": "^4.7.2",
"@tanstack/react-query-devtools": "^4.7.2",
"typescript": "^4.8.4",
```

**Comment by TkDodo** [comment]
you still need to show a codesandbox reproduction please, because I'm not going to put that code in a runnable environment to debug it. That's your job.

FYI, here is our default hashing function:

https://github.com/TanStack/query/blob/f9ebf9aaae59050331c22f143d835e46fac402cc/packages/query-core/src/utils.ts#L269-L280

it's a json stringify where all _plain objects_ are sorted. My best guess is that your `ItemID` class (?) is not an json serializable object, but again, you're not showing that, so how should I know. Pretty sure this works:

```
const id = {}
id.app = app.fingerprintID.app;
id.id = entityId;
```

🤷 

if you use special stuff like classes as keys, you'd need to provide your own `queryKeyHashFn`.

**Comment by oneznamov** [comment]
Sorry if i was incomprehensible , this my first experience of opening issue.

I missed  `queryKeyHashFn` option in docs.  So i use it in config for cover all call(api & hooks) :
```javascript
const config = {
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: false,
      queryKeyHashFn: (queryKey: QueryKey): string => {
	...

const queryClient = new QueryClient(config);
```

This works as i expecting, thanks
