### ISSUE TITLE
separate shouldLoadOnMount and shouldFetchOnMount

### ISSUE THREAD

**Issue by milahu** [TanStack/query#4368]
### Describe the bug

note:
work in progress. im working on a fix, will PR later
so no repro code here

edit:
this may be a race condition
between my `persister.restoreClient` and `QueryObserver.onSubscribe`.
all queries should wait for restoreClient

use case:
im fetching immutable data: files from github.
these files are content-addressed via commit hash or blob hash,
so building a cache should be trivial

goal:
fetch every file only once

how:
persistence via indexeddb
query options:

```js
    {
      cacheTime: Infinity,
      staleTime: Infinity,
      refetchOnWindowFocus: false,
      refetchOnMount: false,
      refetchOnReconnect: false,

      // any previous data will be kept when fetching new data because the query key changed.
      //keepPreviousData: true, // ?
    }
```

but this is not enough to prevent TanStack/query from refetching

executeFetch is still called in QueryObserver.onSubscribe

`node_modules/@tanstack/query-core/build/lib/queryObserver.esm.js`

```js
class QueryObserver extends Subscribable {
// ...
  onSubscribe() {
    if (this.listeners.length === 1) {
      this.currentQuery.addObserver(this);

      if (shouldFetchOnMount(this.currentQuery, this.options)) {
// FIXME QueryObserver.onSubscribe should not refetch, but use cache
        this.executeFetch();
      }

      this.updateTimers();
    }
  }
```

when i remove the line `this.executeFetch();` it works as expected = dont refetch, use cache

problem: `shouldFetchOnMount` calls `shouldLoadOnMount`
but "fetch" and "load" are different actions

```js
function shouldFetchOnMount(query, options) {
  return shouldLoadOnMount(query, options) || query.state.dataUpdatedAt > 0 && shouldFetchOn(query, options, options.refetchOnMount);
}
```

when i simply remove `shouldLoadOnMount(query, options) ||`
then my interface is broken, the data is not rendered

related https://github.com/TanStack/query/pull/71#issuecomment-1288180640

### Your minimal, reproducible example

http://localhost/

### Steps to reproduce

note:
work in progress. im working on a fix, will PR later
so no repro code here

### Expected behavior

see above

### How often does this bug happen?

Every time

### Platform

```
grep /@tanstack pnpm-lock.yaml 

  /@tanstack/query-core/4.13.0:
  /@tanstack/query-persist-client-core/4.13.0:
  /@tanstack/react-query-persist-client/4.13.0:
  /@tanstack/solid-query/4.13.0_solid-js@1.6.0:
```

### react-query version

4.13.0

**Comment by milahu** [comment]
> edit:
> this may be a race condition
> between my `persister.restoreClient` and `QueryObserver.onSubscribe`.
> all queries should wait for restoreClient

probably yes ... closing

**Comment by TkDodo** [comment]
> all queries should wait for restoreClient

they do if you use the `PersistQueryClientProvider`

**Comment by milahu** [comment]
see my demo app [prosemirror-inplace-editing-demo](https://github.com/milahu/prosemirror-inplace-editing-demo) based on solid.js framework

im wrapping my app in `PersistQueryClientProvider`
which is defined in [tanstack-solid-query-persist-client.jsx](https://github.com/milahu/prosemirror-inplace-editing-demo/blob/main/src/tanstack-solid-query-persist-client.jsx)
using the same logic as similar components, see "based on"

by fetching from the github api
i get an exact number of the actual fetches in the `x-ratelimit-used` header

i need [patches](https://github.com/milahu/prosemirror-inplace-editing-demo/tree/main/patches) to

* pause the queryClient before restoreClient, so that all queries wait until the persistent cache is loaded
* fix `@tanstack+solid-query` error `DOMException: Failed to execute 'put' on 'IDBObjectStore': [object Array] could not be cloned.` because Proxy objects in queryKey cannot be serialized for indexeddb

imho these fix bugs in tanstack, but maybe im doing something wrong...?

**Comment by TkDodo** [comment]
> pause the queryClient before restoreClient, so that all queries wait until the persistent cache is loaded

this is what the Provider is doing via the `isRestoring` value that is passed with the `IsRestoringProvider`:

https://github.com/TanStack/query/blob/7741a2f723f37bdb3ce79cb96ed2394b121b21d3/packages/react-query-persist-client/src/PersistQueryClientProvider.tsx#L50

Observers are not subscribed while the client is still restoring, so no fetches should go out. We have tests for that :)

**Comment by milahu** [comment]
thanks for the hint.
i tried to translate this to `@tanstack/solid-query` but ...

the first fetch works, then result is in cache.
on the next page reload, after `persister.restoreClient`, it fails to load result from cache

i still dont see how QueryObserver is reading data from the cache
i.e. from `queryClient.clientState.queries` ... enough for today

[demo](https://github.com/milahu/prosemirror-inplace-editing-demo)
