### ISSUE TITLE
When I change the data of useQuery directly, the data keeps changing.

### ISSUE THREAD

**Issue by hsk-kr** [TanStack/query#4378]
### Describe the bug

```typescript
import { useEffect, useState } from "react";
import {
  QueryClientProvider,
  QueryClient,
  useQuery,
  useQueryClient,
} from "react-query";
import { ReactQueryDevtools } from "react-query/devtools";

const queryKey = "key";

function Query() {
  const client = useQueryClient();
  const { data } = useQuery(
    queryKey,
    () => [
      {
        name: "alle",
      },
      {
        name: "bob",
      },
    ],
    {
      staleTime: 0,
      select: (res) => res, // Without this select option, it works fine.
    }
  );
  const [, set] = useState(false);

  const rerender = () => set((prev) => !prev);

  useEffect(() => {
    console.log("data changed", JSON.stringify(data));

    if (!data) return;

    // If I changed the cache data the same as the data, it also worked fine.
    // const cache = client.getQueryCache();
    // const target = cache.find(queryKey);
    // if (target) (target.state.data as any)[0].name = "charlie";
    data[0].name = "charlie";
    rerender();
  }, [data]);

  return (
    <ul>
      {data?.map((d, dIdx) => (
        <li key={dIdx}>{d.name}</li>
      ))}
    </ul>
  );
}

function Main() {
  const [visible, setVisible] = useState(false);

  const toggle = () => {
    setVisible((visible) => !visible);
  };

  return (
    <div>
      <button onClick={toggle}>toggle</button>
      {visible && <Query />}
    </div>
  );
}

const queryClient = new QueryClient();

function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <ReactQueryDevtools />
      <Main />
    </QueryClientProvider>
  );
}

export default App;
```

There is inactive data in the cache, and I use select option of useQuery.
When I change the data directly and it rerenders, the data keeps changing, so, the useEffect is called infinitely.
But without select option, it works fine. or if I change the cache data the same as the data, it also works correctly.

We'd often copy the data like this way,

```typescript
const newData = [...data];
```

This code would occur this problem too.

### Your minimal, reproducible example

https://codesandbox.io/s/react-query-bug-un9g1x?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-query-bug-un9g1x?file=/src/App.js
2. Click toggle button
3. Click toggle button again
4. You'll see useEffect is called infinitely

Without select or if you uncomment the cache changing part, it would work fine. 

### Expected behavior

A hash of the data doesn't change. it means, useEffect is not called when it rerenders. 

### How often does this bug happen?

Every time

### Platform

Windows11, Mac M1

### react-query version

v3.39.2

### TypeScript version

v4.8.3

**Comment by TkDodo** [comment]
because when you use `select`, we store the select result on the query observer. This is compared with the new result. By manipulating the data in the cache + re-render, when then compare what is in the cache (new) with what is stored in the observer (old), it's different, so we structurally share the data and give you the new object, effect runs again etc ...
