### ISSUE TITLE
infinite loop when using placeholderdata and enabled false

### ISSUE THREAD

**Issue by CedricCouton** [TanStack/query#4398]
### Describe the bug

Hi,

During our migration from v3 to v4, we observed an infinite loop with a specific usage of placeholderdata and enabled false, if the placeholderdata is defined directly in the usage of useQuery we have it, if we defined in a constant the placeholderdata and use it in the useQuery the issue gone. 

Here the project to reproduce the issue : https://github.com/CedricCouton/react-query-loop

### Your minimal, reproducible example

https://github.com/CedricCouton/react-query-loop

https://codesandbox.io/s/priceless-thunder-3zk8y1?file=/src/index.jsx

### Steps to reproduce

Use this repo : https://github.com/CedricCouton/react-query-loop

And use the useQuery as that : 
``` const response = useQuery(["users"], fetchUsers, { placeholderData: {}, enabled: false});```

### Expected behavior

Not having the infinite loop

### How often does this bug happen?

Every time

### Platform

All

### react-query version

v4

**Comment by TkDodo** [comment]
not sure I understand what this code is supposed to be doing. There is a useEffect that runs after every render (no dependencies) that calls setState, which triggers a re-render. What's the purpose of that?

**Comment by CedricCouton** [comment]
Yes it can seem weird, but React is capable to detect that the state1 is unchanged and stop to render the children of the Parent. Here just adding the row with the useQuery (with placeholderdata and enable false) generate a render of each children because the "response" value have a new reference each render, with the v3 of rq it was not the case.

**Comment by TkDodo** [comment]
I don't think `response` should be a different value each render, because `placeholderData` is structurally shared. Also, response is unused. Renders "coming from" react-query will only happen when data in the cache changes, which does't happen. So the render is top-down, and likely done by react. Maybe it cannot bail out of the `useState` update because of useSyncExternalStore in the query, idk. It's weird.

**Comment by CedricCouton** [comment]
If we use a placeholder data defined outside the component, the issue gone.

**Comment by TkDodo** [comment]
If fixed this by always structurally sharing placeholderData. I'm unsure what causes the infinite loop, but this seems like a good fix regardless:

https://codesandbox.io/s/silent-sun-xwe8c0
