### ISSUE TITLE
Cached initialData (function) values are not reused within staleTime window

### ISSUE THREAD

**Issue by arackaf** [TanStack/query#4415]
### Describe the bug

When initialData is specified with a function, it prevents cached data from being reused (repro below).

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-rayu8t?file=src%2FApp.tsx,src%2FTodos.tsx,package.json

### Steps to reproduce

Refresh the repo. 

Quickly select "High" from the dropdown. 

The results will change. 

Quickly re-select "All."

The cached "All" results will *not* re-show. 

### Expected behavior

The cached data should be re-used within the staleTime window.

### How often does this bug happen?

Every time

### Screenshots or Videos

n/a

### Platform

MacOS / Chrome

### react-query version

4.13.5

### TypeScript version

n/a

### Additional context

n/a

**Comment by TkDodo** [comment]
it seems to be something between the 3 setting:
- initialData
- keepPreviousData
- staleTime

removing any of the 3 makes it pass, all 3 are broken

**Comment by TkDodo** [comment]
@arackaf here is a codesandbox (😆) with your reproduction using the preview build from the linked PR. I cannot reproduce the issue anymore:

https://codesandbox.io/s/tanstack-query-example-react-basic-typescript-forked-x4v80m?file=/src/index.tsx
