### ISSUE TITLE
eslint-plugin: "dependencies are missing in your queryKey" error if the dependency is cast to boolen

### ISSUE THREAD

**Issue by SpadarShut** [TanStack/query#4429]
### Describe the bug

if a dependency is used as `!! myDependency` in the key, missing dependency error is triggered.

### Steps to reproduce

```js
const useFoo = ({myNonSerializableDep}) => {
  return useQuery({
    // ESLint: The following dependencies are missing in your queryKey: myNonSerializableDep(@tanstack/query/exhaustive-deps)
    queryKey: ['foo', !!myNonSerializableDep], // <= get the error on this line
  })
} 
```
### Expected behavior

there should be no error

### How often does this bug happen?

Every time

### Platform

MacOS

### react-query version

4.14.1

### TypeScript version

4.8.3

**Comment by TkDodo** [comment]
@Newbie012 can you have a look maybe?

**Comment by Newbie012** [comment]
Sure, I'm on vacation (not near my computer), so I'll fix it in a few days.
