### ISSUE TITLE
queryFn is called twice on first refetch

### ISSUE THREAD

**Issue by rostero1** [TanStack/query#4445]
### Describe the bug

On load, my queryFn is called once.  When "refetch" is clicked, it's called twice.  When "refetch" is clicked again, it's called once.  Version 4.14.1.

### Your minimal, reproducible example

https://codesandbox.io/s/elated-neumann-lgd2u7?file=/src/App.tsx

### Steps to reproduce

On load, my queryFn is called once.  When "refetch" is clicked, it's called twice.  When "refetch" is clicked again, it's called once.  Version 4.14.1.

### Expected behavior

Refetch is only ever called once per click.  Or is this a useEffect in dev mode issue?  I don't know how refetch is implemented.

### Platform

MacOS & Chrome

### react-query version

4.14.1

### TypeScript version

4.4.2

**Comment by TkDodo** [comment]
it's a refetchOnWindowFocus thing. A classic.

https://tkdodo.eu/blog/practical-react-query#the-defaults-explained
