### ISSUE TITLE
`enabled` property doesn't get updated in Solid Query

### ISSUE THREAD

**Issue by OrJDev** [TanStack/query#4460]
### Describe the bug

While the react docs show that the `enabled` property can be reactive ([here](https://tanstack.com/query/v4/docs/guides/disabling-queries#lazy-queries)), 
the enabled proprty / properties in general  in solid query doesn't get updated after `enabled` is being set to false,

```ts
  const func = async () => {
    await new Promise((resolve) => setTimeout(resolve, 3000));
    return `is it enabled`;
  };
  const res = createQuery(() => ["hello", name()], func, {
    enabled: name() !== "from tRPC",
  });
```

right so here is how i render the above

``` ts
createEffect(
    () =>
      name() !== "from tRPC" &&
      console.log(`name changed to ${name()} but the query work?`)
  );
  return (
    <div class="font-bold text-2xl flex flex-col gap-2 text-gray-500">
      {res.isLoading ? "loading" : res.data}
      <button
        onClick={() => {
          setName("John Doe");
        }}
      >
        Set
      </button>
    </div>
  );
```
![Screenshot_1](https://user-images.githubusercontent.com/91349014/200108664-90b2d798-4aac-43ab-86f0-456ffe6a55bc.png)

And ofc it just stuck at loading (meaning the queryFunction wasn't even called) even tho the enabled property was set to true (because name was changed and no longer equals "from tRPC"),
i was trying to treat the opts as solid accessor assuming i'm the one who is doing something wrong but opts cannot be a callback.

    

### Your minimal, reproducible example

Mentioned above

### Steps to reproduce

Create A Solid Signal - "name"
Create A Solid Query That Is Disabled While Name.length < 3 (condition for example) And The QueryFunction Should Wait 3 Seconds Before Returning Anything - 'Response from query" for example
Now Change The Name Signal To A Name With More Than 3 Characters, And You Will See That The QueryFunction Will Never Be Called Even Tho It Does Seem To Be Reactive In The React Query Docs ([here](https://tanstack.com/query/v4/docs/guides/disabling-queries#lazy-queries))

### Expected behavior

the queryfunction should be called when enabled is set to true even tho it was set to false at the first place

### Platform

Window, Chrome - Version 107.0.5304.88 (Official Build) (64-bit)

### react-query version

4.14.3

**Comment by TkDodo** [comment]
can you please put that code in a runnable reproduction like codesandbox or stackblitz?

I don't know much solid, but looking at our tests, the `enabled` option needs to be wrapped in a getter to become reactive. This is also mentioned [in the docs](https://tanstack.com/query/v4/docs/adapters/solid-query).

> If you want options to be reactive you need to pass them using object getter syntax. This may look strange at first but it leads to more idiomatic solid code.

```
const res = createQuery(() => ["hello", name()], func, {
  get enabled() {
    return name() !== "from tRPC"
  },
});
```

This will get better in v5, have a look at the roadmap and the comment from @ardeora 

- https://github.com/TanStack/query/discussions/4252#discussioncomment-3779788

**Comment by OrJDev** [comment]
> can you please put that code in a runnable reproduction like codesandbox or stackblitz?
> 
> I don't know much solid, but looking at our tests, the `enabled` option needs to be wrapped in a getter to become reactive. This is also mentioned [in the docs](https://tanstack.com/query/v4/docs/adapters/solid-query).
> 
> > If you want options to be reactive you need to pass them using object getter syntax. This may look strange at first but it leads to more idiomatic solid code.
> 
> ```
> const res = createQuery(() => ["hello", name()], func, {
>   get enabled() {
>     return name() !== "from tRPC"
>   },
> });
> ```
> 
> This will get better in v5, have a look at the roadmap and the comment from @ardeora
> 
> * [v5 Roadmap 🗺 #4252 (comment)](https://github.com/TanStack/query/discussions/4252#discussioncomment-3779788)

oh you are right it does work with a getter i don't know how have i missed that, tahnks
