### ISSUE TITLE
eslint-plugin-query: false positive for factory functions that return an object

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#4476]
```
const getQuery = () => ({
  queryKey: ['foo'],
  queryFn: () => Promise.resolve(5)
})

return useQuery(getQuery())
```

⬆️ `ESLint: Objects syntax for useQuery is preferred(@tanstack/query/prefer-query-object-syntax)`

what's more dangerous, it even auto fixes this to:

```
return useQuery({ queryKey: getQuery() })
```

which is wrong.

---

As a workaround, we have to create a new object and spread:

```
useQuery({ ...getQuery() })
```

---

The wrong auto-fix is a big problem I think because it will convert working code to non-working code :/

**Comment by TkDodo** [comment]
@Newbie012 not sure if this easy to fix...

**Comment by Newbie012** [comment]
I'll fix it

**Comment by Newbie012** [comment]
I got it working, and many other complex cases (such as deep multiple returns).The code is currently unreadable, so I'll fix it and push a PR today or tomorrow.
