### ISSUE TITLE
useMutation: child components are not re-rendered when cache is updated

### ISSUE THREAD

**Issue by hallelujahdrive** [TanStack/query#4478]
### Describe the bug

Memorized child components are not re-rendered when values are assigned to object properties before cache updates.

Below is an excerpt of the cache update code from [codesandobox](https://codesandbox.io/s/gracious-napier-01be0z?file=/src/App.tsx):
```ts

const queryClient = useQueryClient();

const { data } = useQuery({ ... });
 
const { mutate: handleChange } = useMutation({
  mutationFn: async (value: { value: string }) => {
    // Change object properties by reassignment before updating cache.
    data.value = value.value;
    // Objects are not re-rendered when references are changed.
    queryClient.setQueriesData(["values"], { ...data });

    // Updating the cache with only one line below is not a problem.
    // queryClient.setQueriesData(["values"], value);
    // or
    // queryClient.setQueriesData(["values"], { ...data, ...value });
  }
});
```

### Your minimal, reproducible example

https://codesandbox.io/s/gracious-napier-01be0z?file=/src/App.tsx

### Steps to reproduce

1. Enter text in input.

### Expected behavior

Reassigning a value to a property requires that it be re-rendered if the object referenced in the cache changes.

### How often does this bug happen?

Every time

### Platform

- OS: Alpine Linux 3.16
- Browser: Chrome 107
- Node: v18.12.0

### react-query version

v4.14.5

### TypeScript version

v.4.8.4

### Additional context

It could be a bug in `React.memo`, since the child component is re-rendered normally when it is not memoized. However, this event does not occur when the state is managed by `React.useState` / `React.useReducer`.

**Comment by TkDodo** [comment]
By mutating data in place via the assignment:

```
data.value = value.value;
```

you write the new value directly to the query cache, and then call `setQueryData` on it. After the `setQueryData` call, react-query sees that the values are deeply equal (via the feature of `structuralSharing`) and then gives you the referentially stable object back, because they are considered equal. That will cause `memo` to bailout.

Do not mutate values in-place, ever. This follows the same rules as react. You have to update state immutably.

**Comment by hallelujahdrive** [comment]
@TkDodo  Thank you, I understand the `setQueryData` process.

I was working with larger, more complex objects and code a process that regenerates them after assignment to avoid typescript type errors: split assignments to union types often result in type errors.

I am puzzled because react does not have such strict rules to suppress rerendering, but I will consider using Immer, etc. to work around this problem.

**Comment by darktasevski** [comment]
A bit late to the party, but I had a similar problem and got around it with the [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone).

@hallelujahdrive  with it you can update the code above to be:

```ts
   const newCachedData = structuredClone(data);
   newCachedData.value = value.value;

   queryClient.setQueriesData(["values"], newCachedData);
```
and it should work. 

The only downside is that the `structuredClone` is pretty [new](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility), but there are polyfills for it.
