### ISSUE TITLE
TypeScript error in /app/node_modules/@tanstack/react-query-devtools/build/lib/utils.d.ts(40,78):

### ISSUE THREAD

**Issue by Elwazer007** [TanStack/query#4487]
### Describe the bug

Integrating the react-query devtools with react-query is broken , I followed the instructions in the docs : 
here's a sample code 
```
const Application = () => {

  const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        refetchOnWindowFocus: false,
        refetchOnMount: false,
      },
    },
  });

  return (
      <QueryClientProvider client={queryClient}>
        {/* My components tree */ }
        <ReactQueryDevtools initialIsOpen={false} />
      </QueryClientProvider>
  );
};

``` 
results : 
Failed to compile the application with the following log error : 
```
    38 |  * Example given `border` and `right` it return `borderRight`
    39 |  */
  > 40 | export declare function getSidedProp<T extends string>(prop: T, side: Side): `${T}Left` | `${T}Right` | `${T}Bottom` | `${T}Top`;
       |                                                                              ^
    41 | export interface SidePanelStyleOptions {
    42 |     /**
    43 |      * Position of the panel
Compiling...
Failed to compile.
```

### Your minimal, reproducible example

asked in stackoverflow https://stackoverflow.com/questions/74362928/react-query-devtools-doesnt-in-a-react-typescript-app

### Steps to reproduce

install react query version 4.0.10 
install react query devtools 4.14.5 
configure react query devtools just as docs description 

### Expected behavior

I think it shloud be working as normal but it is failing to compile

### Screenshots or Videos

<img width="1042" alt="Screenshot 2022-11-08 at 5 24 41 PM" src="https://user-images.githubusercontent.com/28496859/200605454-2967a063-337f-407a-a908-be069d606c64.png">

### Platform

macos m1  
chrome browser 

### react-query version

4.0.10

### TypeScript version

3.7.5

### Additional context

react-query-devtools version is 4.14.5

**Comment by TkDodo** [comment]
Please show a real running reproduction of the issue in either codesandbox or stackblitz.

**Comment by TkDodo** [comment]
I just saw:

> TypeScript version
> 3.7.5

Please note that TanStack/query v4 requires at least TypeScript 4.1:

- https://tanstack.com/query/v4/docs/typescript
- https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4#typescript

template literal types are only supported in TS 4.1 or greater
