### ISSUE TITLE
v3 litters Jest tests with `not wrapped in act()` errors

### ISSUE THREAD

**Issue by ericbiewener** [TanStack/query#4494]
### Describe the bug

Using `@testing-library/react`, a minimal test case that renders a component which calls `useQuery()` results in the error

> Warning: An update to TestCmp inside a test was not wrapped in act(...)

This does not occur with versions 2 nor 4.

### Your minimal, reproducible example

https://github.com/ericbiewener/react-query-act-error

### Steps to reproduce

This error can be seen in the `v3` branch of [this test repo](https://github.com/ericbiewener/react-query-act-error). I have included `v2` and `v4` branches as well to show the absence of the console error. In all cases, just run `npm install; npm test` to see the output.

Here is the test code for the v3 version:

```jsx
import { render } from '@testing-library/react';
import { useQuery, QueryClientProvider, QueryClient } from "react-query"

const queryCache = new QueryClient();

const TestCmp = () => {
  const result = useQuery(["foo"], () => Promise.resolve("foo"));
  return null;
};

test('should have no act() error', () => {
  render(
    <QueryClientProvider client={queryCache}>
      <TestCmp />
    </QueryClientProvider>
  );
});
```

Calling `cleanup()` from `@testing-library/react` [at the end of the test (but still _inside the test_)](https://github.com/ericbiewener/react-query-act-error/blob/v3-inline-cleanup/src/react-query.test.js#L19) does resolve this issue, but not when using it [in an `afterEach()` call](https://github.com/ericbiewener/react-query-act-error/blob/v3-afterEach-cleanup/src/react-query.test.js#L13), which is the standard approach. The same goes for calling `queryCache.clear()` -- inside the test it works, but in an `afterEach` call it does not.

### Expected behavior

No `act()` errors.

### Platform

- macOS
- No browser, just in jest.

### react-query version

3.39.2

**Comment by TkDodo** [comment]
I'm not going to look into this because you're using react-query v3 with react 18 and testing-library v13. This is not meant to work together. Only v4 has proper support for react18.

See also the [release notes of v3.35.0](https://github.com/TanStack/query/releases/tag/v3.35.0)

**Comment by todofixthis** [comment]
Adding some context for anyone who comes across this issue in the future:

`react-query` is the v3 branch of the library; switch to `@tanstack/react-query` to install the v4 branch:

```
npm uninstall react-query
npm install @tanstack/react-query
```
