### ISSUE TITLE
Duplicate request and cache issue when using vue-query along with suspense

### ISSUE THREAD

**Issue by Alexis2004** [TanStack/query#4496]
### Describe the bug

I've prepared a minimal reproduction to demonstrate the problem I'm having on a real project.

The application contains two components:
1) Component `App.vue` that loading another component `Content.vue` wrapped in a `<Suspense>` tag.
2) Component `Content.vue` displaying some data that is “loaded” from the server. I replaced the real loading with emulation through a setTimeout. The content depends on the `pageType` reactive variable, the value of which can be changed by pressing the `Page A` and `Page B` buttons. The component has a setup method with the `async` modifier and `await suspense()` before return clause.

You can run the example with command: `yarn install && yarn run dev`.

Load page and press buttons `Page B`, then `Page A`, then `Page B`.

As a result, we have two problems:
1) When loading data for the `["page-b"]` key, two requests are made to the server instead of one.
2) These queries corrupt the data in the cache for the previously written key `["page-a"]`.

### Your minimal, reproducible example

https://codesandbox.io/p/github/Alexis2004/vue-query-suspense-issue/main or https://github.com/Alexis2004/vue-query-suspense-issue

### Steps to reproduce

1) Open the page http://localhost:5173/
2) See:
– Title: `Page page-a`
– Content: `Content for page: 'page-a'`
– One console entry: `Emulating server request for pageType='page-a'`
3) Press the button `Page B`
4) See:
– Title: `Page page-b`
– Content: `Content for page: 'page-a'` **<<< Value unchanged!**
– Two identical console entries `Emulating server request for pageType='page-b'` **<<< Two requests actually made to the server!**
5) Press the button `Page A`
6) See:
– Title: `Page page-a`
– Content: `Content for page: 'page-a'`
– There are no new entries in the console
7) Press the button `Page B`
8) See:
– Title: `Page page-a`
– Content: `Content for page: 'page-a'` **<<< Value unchanged again!**
– There are no new entries in the console

### Expected behavior

1) Open the page http://localhost:5173/
2) See:
– Title: `Page page-a`
– Content: `Content for page: 'page-a'`
– One console entry: `Emulating server request for pageType='page-a'`
3) Press the button `Page B`
4) See:
– Title: `Page page-b`
– Content: `Content for page: 'page-b'`
– Another console entry: `Emulating server request for pageType='page-b'`
5) Press the button `Page A`
6) See:
– Title: `Page page-a`
– Content: `Content for page: 'page-a'`
– There are no new entries in the console (data taken from the cache)
7) Press the button `Page B`
8) See:
– Title: `Page page-b`
– Content: `Content for page: 'page-b'`
– There are no new entries in the console (data taken from the cache)

### How often does this bug happen?

Every time

### Platform

– macOS
– Chrome 107

### react-query version

"@tanstack/vue-query": "4.14.1"

### TypeScript version

^4.6.4

### Additional context

If we look at the information from the `Vue Query` tab in `Vue Dev Tools`, then immediately after opening we see one query in the cache:

```
Query Details:
	Query key: "["page-a"]"
	Query status: "fresh"
Data explorer:
	Data: Object
		content: "Content for page: 'page-a'"
```

And after pressing the `Page B` button, there are two, where the correct value is in the `["page-b"]` key, and the corrupted value is in the `["page-a"]` key (for some reason it was overwritten by the value from the key `["page-b"]`):

```
Query Details:
	Query key: "["page-b"]"
	Query status: "fresh"
Data explorer:
	Data: Object
		content: "Content for page: 'page-b'"
---
Query Details:
	Query key: "["page-a"]"
	Query status: "inactive"
Data explorer:
	Data: Object
		content: "Content for page: 'page-b'" <<< Corrupted value
```

Could you tell me, what could be causing this behavior? Am I using `vue-query` wrong somehow or is it a bug in the library? If so, is there any workaround? Thanks in advance!

----

I am posting issue here and not to https://github.com/DamianOsipiuk/vue-query because of `This package was migrated to be a part of https://github.com/TanStack/query`. Please correct me if I'm wrong with the posting.

**Comment by DamianOsipiuk** [comment]
@Alexis2004 Could you please check with https://github.com/TanStack/query/releases/tag/v4.17.0
This issue should be fixed in that version.
