### ISSUE TITLE
SSR + suspense + solid-query does not seem to work

### ISSUE THREAD

**Issue by marbemac** [TanStack/query#4510]
### Describe the bug

SSR + suspense does not seem to work with `solid-query` (or I'm doing something wrong on the implementation). I've included a minimum reproducible repo that compares solid-query vs basic `createResource` (which I looks like solid-query is using in some capacity under the hood, so *maybe* this is fixable!).

### Your minimal, reproducible example

https://codesandbox.io/p/github/marbemac/solid-query-ssr-bug

### Steps to reproduce

Turn off javascript and load up the solid-query route in the attached reproducible example. Under the hood it's just using a simple query, with a suspense wrapper (https://github.com/marbemac/solid-query-ssr-bug/blob/main/client/pages/solid-query.tsx), rendering on the server with `renderToStringAsync`.

### Expected behavior

As a user, I'd like to leverage suspense + solid-query in SSR applications.

### How often does this bug happen?

Every time

### Platform

- macOs

### react-query version

4.15.1

### TypeScript version

4.8.4

### Additional context

- https://github.com/marbemac/solid-query-ssr-bug
- https://codesandbox.io/p/github/marbemac/solid-query-ssr-bug

**Comment by TkDodo** [comment]
I think I remember @ardeora mentioning somewhere that there is no complete story for solid-query in SSR yet and that we wanted to wait until solid-start is stable. But I could be wrong / misremember 😅

**Comment by OrJDev** [comment]
https://twitter.com/aryan__deora/status/1592025888761446400?s=46&t=HoDG03U8-68q6IdSB-sZGQ

**Comment by marbemac** [comment]
Resolved by the variety of improvements Aryan and I made to solid-query over the last year.
