### ISSUE TITLE
isLoading is set to true when query is not enabled

### ISSUE THREAD

**Issue by kevineaton603** [TanStack/query#4511]
### Describe the bug

`isLoading` from the `useQuery` is set to true when query is not enabled on the first render.

### Your minimal, reproducible example

https://codesandbox.io/s/hungry-wildflower-qfy9qw?file=/src/index.jsx

### Steps to reproduce

1. Check out Example

### Expected behavior

As a user, I expected `isLoading` to be set to `false` when the query is not enabled on the first render but the actual behavior is that it was set to true.

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Browser: Chrome

### react-query version

4.13.0

**Comment by DamianOsipiuk** [comment]
It works as intended.
You can use `fetchStatus` to check if query is fetching.
https://tanstack.com/query/v4/docs/guides/queries#why-two-different-states

**Comment by kevineaton603** [comment]
Alright thank you for your help!
