### ISSUE TITLE
enabled and query keys reactivity in Vue-query

### ISSUE THREAD

**Issue by chboing** [TanStack/query#4516]
### Describe the bug

I've just encountered some difficulties with the `enabled` functionnality in Vue query.
Solved it when i found this : https://github.com/TanStack/query/issues/4460

The 1st issue i'd like to mention is the vue-query doc is not mentionning the getter thing, that immediately solved the issue
BUT
I now face a similar issue with the key of the query. I'd like to include the id in the key, but the id is not reactive
`useQuery(["detcoll_geom", idColl.value]`
While `idColl.value` is used with a valid value in the request, the key does not update, so I always get `["detcoll_geom", null]` key and I don't know if it's a bug or something i missed. Maybe a way to update the key in the query func ?

![image](https://user-images.githubusercontent.com/2633332/202146903-c2a5ce81-9f6d-4ec0-adba-5c5b74cba3a6.png)

Thank you for the great lib !

### Your minimal, reproducible example

https://codesandbox.io/s/vue-query-reactivity-forked-lmdewg?file=/src/components/Users.vue

### Steps to reproduce

but I did not manage to get a look on the keys ... whereas in my app, i use the devtool and see them

### Expected behavior

not null but a correct key with the id.

### How often does this bug happen?

Every time

### Platform

window / chrome

### react-query version

4.10.1

**Comment by DamianOsipiuk** [comment]
@chboing You should not unwrap `reactive` props when passing them to `vue-query`.
Ex.
```ts
const idColl = ref(123)

useQuery(["detcoll_geom", idColl.value], ...)
// ❌you are passing plain value here, not reactive object, so vue-query would not be able to tell if this value changed

useQuery(["detcoll_geom", idColl], ...)
//✅
```

The same goes for enabled, do not pass `xyz.value` to `useQuery`. Pass `xyz`.

`vue-query` will subscribe and react to changes of those reactive variables.

**Comment by chboing** [comment]
Right, I don't know how I did not ended up trying this ...
This is working as you said @DamianOsipiuk thank you for taking the time.
