### ISSUE TITLE
Dehydration not works in getInitialProps and getServerSideProps

### ISSUE THREAD

**Issue by phatify** [TanStack/query#4539]
### Describe the bug

I am using react-query with NextJS (getInitialProps and getServerSideProps) to fetch data SSR by hydration method but I get undefined returned from getInitialProps althought getServerSideProps still returned data.

My code like this:

__app.js_

```
App.getInitialProps = async (context) => {
    const pageProps = await NextApp.getInitialProps(context);

    try {
        const { req, res } = context.ctx;
        const token = getCookie('auth_token', { req, res });

        const queryClient = new QueryClient();
        await queryClient.fetchQuery(['auth'], () => 'example-result-data-1');

        return {
            ...pageProps,
            pageProps: {
                dehydratedState: dehydrate(queryClient), // not working
            },
        };
    } catch (err) {
        return {};
    }
};
```

_./profile.js_

```
export const getServerSideProps = async (context) => {
    const queryClient = new QueryClient();
    await queryClient.fetchQuery(['profile'], () => 'example-result-data-2');

    return {
        props: {
            dehydratedState: dehydrate(queryClient),
        },
    };
};
```

When trying to get query data of `profile `key, it still working as expected, but undefined returned from `auth `key.
Example: 

```
queryClient.getQueryData({ queryKey: 'auth' }); // it return undefined 👎 
queryClient.getQueryData({ queryKey: 'profile' }); // it return 'example-result-data-2'  💯 
```

I think that is bug and not the feature.

### Your minimal, reproducible example

https://stackoverflow.com/questions/74535515/why-dehydration-not-works-in-react-query

### Steps to reproduce

.

### Expected behavior

.

### How often does this bug happen?

Sometimes

### Platform

Windows 10

### react-query version

lastest version

**Comment by TkDodo** [comment]
linking from the `minimal, reproducible example` to the same question on StackOverflow is not a good way to get us to look into this issue. I'll close this, but feel free to re-open once you can provide a real reproduction.
