### ISSUE TITLE
Failed queries are fetched multiple times

### ISSUE THREAD

**Issue by knyzorg** [TanStack/query#4548]
### Describe the bug

React-Query causes needless refetches when calling a failing query. If a query fails, it will be fetched again by _every subscriber of that query_. This is bad because it exhausts the rate-limit pool on failing calls way more than it needs to.

### Your minimal, reproducible example

https://codesandbox.io/s/react-query-repeated-failures-6s2u33?file=/src/App.tsx

### Steps to reproduce

Write a hook that throws an error and invoke it multiple times. The error is not cached and leads other queries querying the same key query needlessly.

Expected result:

![image](https://user-images.githubusercontent.com/10255546/203644831-9816a65d-7350-4091-a906-5952c1e241c2.png)

Actual result:
![image](https://user-images.githubusercontent.com/10255546/203644854-6b147081-6b3e-4c9c-a631-60d6a9ab0773.png)

### Expected behavior

Expected result:

![image](https://user-images.githubusercontent.com/10255546/203644831-9816a65d-7350-4091-a906-5952c1e241c2.png)

### How often does this bug happen?

Every time

### Platform

Firefox

### react-query version

v4.16.1

**Comment by DamianOsipiuk** [comment]
I think what you are seeing is exponential backoff retries.
You can turn it off by setting `retry: 0` in the query options.

You can read more about defaults here: https://tanstack.com/query/v4/docs/guides/important-defaults

> Queries that fail are silently retried 3 times, with exponential backoff delay before capturing and displaying an error to the UI.

This does not mean that for 10 instances of the same query you will have 30 requests. You still should have 3.

**Comment by knyzorg** [comment]
Ah my bad. I forgot about retry.

**Comment by knyzorg** [comment]
@DamianOsipiuk I didn't adequately re-create the issue I was facing. I added `retry` now, but whenever a child calls the same query, it runs again with no respect towards any configured options.
