### ISSUE TITLE
Calling invalidateQueries re-queries, but not with the latest version of the query function

### ISSUE THREAD

**Issue by robin-xyzt-ai** [TanStack/query#4552]
### Describe the bug

There is an inconsistency with how the `refetch` function (returned by `useQuery`) works and how `invalidateQueries` behaves:

- `refetch` uses the latest version of the query function you passed into the `useQuery` hook
- `invalidateQueries` on the other hand retriggers the query function that has been executed last (which might be older than the latest version of the query function you passed into the `useQuery`  hook

The result is that when you call `invalidateQueries`, you might start doing fetches with outdated information, e.g. an outdated authentication token, despite the fact you passed the up-to-date information to `useQuery`.

### Your minimal, reproducible example

https://codesandbox.io/s/react-query-issue-bbxqeo

### Steps to reproduce

1. Open the code sandbox and open the console
2. Click the "Change token" button. Nothing should happen, except that the token changes
3. Click the Refetch data button. The query should be done with the new token. This works, as shown on the console and on the webpage
4. Click the "Change token" button again. Nothing should happen, except that the token changes
5. Now click the "Invalidate queries" button. Expectation is that the query is done with the latest token (just like the refetch), but it is actually happening with the previous token

### Expected behavior

As a user, I expect that calling `invalidateQueries` will re-query with the latest version of the query function, and not with the previously executed query function.

### How often does this bug happen?

Every time

### Platform

- OS: Linux (Ubuntu)
- Browser: Firefox
- Vesion: 107.0

### react-query version

v3.39.2

### TypeScript version

4.4.2

**Comment by TkDodo** [comment]
I was surprised that calling `refetch` like this works, because you're "violating" a core principle of react query, which is: your dependencies need to be added to the queryKey. A dependency is _everything_ you're using in your queryFn.

The stale closure problem you're seeing is exactly the reason why this is recommended.

The reason why `refetch` from `useQuery` works is because it is bound to the instance (observer) of a query, so we can safely use those latest options, including the queryFn.

If you have multiple useQuery "instances" / observers (e.g. call the same custom hook twice), they will both have a different, bound version of `refetch`.

But `queryClient.invalidateQueries` doesn't know about that. It only knows the "latest" version of a queryFn that was fetched with. And that function might be from any observer, and if that one closures over a value, that might become stale. Adding it to the queryKey solves that issue because it creates a new cache entry with that function.

**Comment by robin-xyzt-ai** [comment]
I was already surprised I would be the very first person to bump into this "bug", so it makes sense the problem was located in how I was using the library.

Putting the token into the query parameters indeed solves the problem, but it has 1 significant drawback. Each time my token gets updated (which happens in the background, transparent to the user) I'm using a new query hence the data disappears.

E.g. in 

```
const {data} = useQuery([queryKey, token], () => {...});
```

the `data` becomes `null` when my token updates.

The only workaround I can currently think of is keeping the token out of the query key, and use a ref to obtain the latest version of the token.

```
const tokenRef = useRef(token);
const {data} = useQuery(queryKey, () => {
  const token = tokenRef.current;
});

tokenRef.current = token;
```

**Comment by TkDodo** [comment]
> Each time my token gets updated (which happens in the background, transparent to the user) I'm using a new query hence the data disappears.

you can use `keepPreviousData: true` to prevent that.

tokens are a bit special though. I agree they shouldn't be in the key, but I think they also shouldn't be in _react_ at all. I would add them on the api layer, e.g. in an axios interceptor if you are using that.
I also like to use cookies so I don't have that problem 😅

**Comment by robin-xyzt-ai** [comment]
> you can use keepPreviousData: true to prevent that.
Thanks. That is way easier than my current solution of 

```
      initialData: () => {
        return queryClient.getQueryData(queryKeyWithOldToken);
      }
```
Just like before, it is mentioned in the docs but I overlooked it. Shame on me.

> tokens are a bit special though. I agree they shouldn't be in the key, but I think they also shouldn't be in react at all.

That ship has sailed for now (together with the cookies :-( ).

**Comment by robin-xyzt-ai** [comment]
Just leaving this comment here in case somebody stumbles upon this issue in the future.

I also considered using the `meta` property to pass the token instead of making it part of the query key.

The V3 docs say:

> If set, stores additional information on the query cache entry that can be used as needed. It will be accessible wherever the query is available, and is also part of the QueryFunctionContext provided to the queryFn

From that doc, it is not 100% clear (to me) if:

- Putting that info in meta and removing it from the query key would mean I'm once again in violation of the core principle, just as I was when I was opening this issue.
- If there is any guarantee I always receive the "latest" `meta` when the query function is called

A quick experiment shows that this approach has the same problem as my original problem: calling `invalidateQueries` retriggers the query function with a context containing the "old" `meta` value, and not the latest. So that is not a solution for this either.

**Comment by TkDodo** [comment]
yep, you'd need to put a `ref` into `meta` as shown here:

https://twitter.com/TkDodo/status/1572281134826016769
