### ISSUE TITLE
Vue reactive call no longer preserves union type of vue-query's useQuery

### ISSUE THREAD

**Issue by henribru** [TanStack/query#4556]
### Describe the bug

In the old, separate vue-query package, using vue's `reactive` on the return of `useQuery` preserved the union return type, but now all the union types seem to get combined into one type. This means you can't narrow types based on e.g. `isSuccess`. 

### Your minimal, reproducible example

I attempted to reproduce this in the Typescript Playground, but for whatever reason it just shows me `any` for the return type of the old `useQuery` ... https://www.typescriptlang.org/play?ts=4.8.4#code/JYWwDg9gTgLgBAbzlApgQwMY2ANxXAXzgDMoIQ4AiHAVxUoG4AoUSWROGgZxQEU6oAT0IkyFAOS0UAWgCOAweOato8JNz4K4aLpx78UQgHIoA7iNLk44gAIw0AOy72MAawD0UuQqVMmxGgcsYAgHEggIAAoASkQmOATkFBgaKDCABTFgHgA6VC4IABs8SMpiCMpopgI-DFDnOHlDYQBeJMxsEo0DIUiAbTKKgF0AGnCIaOjmJqEcgBM0exZiOEiZwRzsgGUaDAwULi5YhHjE9fnFtGra+vh1k3M21A7cFEjuhQf+wYhKUfHJtMFBclsAVmtPmZNlwdnsDkc4olGpDTCCrgQgA

I've made a local reproduction you can clone instead: https://github.com/henribru/vue-query-use-query-reactive/blob/master/src/main.ts

### Steps to reproduce

1. Open up src/main.ts in e.g. VS Code
2. Hover over `query.data` and notice it's been narrowed to string
3. Hover over `queryNew.data` and notice it hasn't been narrowed and is `string | undefined`
4. Hover over `query` and notice it's a union type
5. Hover over `queryNew` and notice it's not a union type

### Expected behavior

I expected `@tanstack/vue-query` to have the same behavior as `vue-query` so that I can discriminate between union types.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/6639509/204086009-10a67754-55c5-404e-a1b9-c9653910dffb.png)
-
![image](https://user-images.githubusercontent.com/6639509/204086018-e4e355a2-c3cd-47ff-8d9a-399849772337.png)
-
![image](https://user-images.githubusercontent.com/6639509/204086450-a31d5d08-a3d4-4df1-bb04-70dd88d2485e.png)
-
![image](https://user-images.githubusercontent.com/6639509/204086454-40572ecc-0de8-4f89-81d6-9768e4a2d488.png)

### Platform

- OS: Linux
- Browser: N/A
- Version: N/A

### react-query version

4.17.1 for @tanstack/vue-query, 1.26.0 for vue-query

### TypeScript version

4.8.4

**Comment by henribru** [comment]
This appears to be related to the use of  `Omit` in the definition of `UseQueryReturnType`, if I just naively remove that the error goes away. 

Probably related to issues like these:
https://github.com/microsoft/TypeScript/issues/28339
https://github.com/microsoft/TypeScript/issues/31501
https://github.com/microsoft/TypeScript/issues/39556
https://github.com/microsoft/TypeScript/issues/46361

I guess it could probably be fixed using a `DistributiveOmit`?
https://stackoverflow.com/questions/57103834/typescript-omit-a-property-from-all-interfaces-in-a-union-but-keep-the-union-s
https://davidgomes.com/pick-omit-over-union-types-in-typescript/

**Comment by TkDodo** [comment]
FYI, we won't need the omit in v5 because we remove the overloads there

**Comment by henribru** [comment]
Sounds good. I think I'll do a PR now so it's fixed in v4 as well, though.
