### ISSUE TITLE
refetchInterval not working

### ISSUE THREAD

**Issue by Willham12** [TanStack/query#4584]
### Describe the bug

refetchInterval not working with 4.19.0, with 4.18.0 everything is fine

### Your minimal, reproducible example

https://github.com/TanStack/query/issues/new

### Steps to reproduce

```js
		useQuery([QueryKeys.job], job, {
			refetchInterval: 2000,
			enabled: paymentLinkResource !== undefined,
			onSuccess: () => { console.log("log")
			}});
```

### Expected behavior

refetch every 200ms

### How often does this bug happen?

Every time

### Platform

iOS

### Tanstack Query version

4.19.0

### TypeScript version

3.8

### Additional context

...

**Comment by TkDodo** [comment]
provide a reproduction please

**Comment by johnanthonyeletto** [comment]
Same issue here in React Native using 4.19.0. This query doesn't work:
```js
const { data } = useQuery(
        ['query-key'],
        () => {
           console.log("runQuery"); 
            return 1;
       },
        {
            refetchInterval: 1000,
        }
   );
```

**Comment by TkDodo** [comment]
what does `typeof document` yield in react-native please? This is the only change we made:

- https://github.com/TanStack/query/commit/34e0ad239ba55b3aeb374c773c19d5b9094507a7

**Comment by TkDodo** [comment]
I tried to create a basic reproduction in expo snack:
- https://snack.expo.dev/@tkdodo/greedy-yogurt

it works fine in the web view, but as soon as I try to create an ios view, I'm getting:


```
App.js (1235:889)
Unable to resolve module 'module://react-dom.js'
(Device)
  Evaluating module://react-dom.js
  Evaluating module://@tanstack/react-query.js
  Evaluating module://App.js.js
  Loading module://App.js
```

I don't know enough about react-native or expo snack to understand this error. Maybe someone else can take it from here?

**Comment by Willham12** [comment]
Thanks for the quick fix ;D
