### ISSUE TITLE
useQuery parameters types doesn't work as expected

### ISSUE THREAD

**Issue by Miigaarino** [TanStack/query#4610]
### Describe the bug

I am creating custom useQuery hook using graphql-request
When doing so original useQuery hook expects first parameter to be queryKey even though the whole parameter can be single object.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/48021917/206372800-4cf83074-0995-4471-8be7-47ef26b96036.png">

Error of image above: 
```Object literal may only specify known properties, and 'queryKey' does not exist in type 'readonly unknown[]'.```

      

### Your minimal, reproducible example

https://codesandbox.io/s/condescending-matsumoto-r99vhv?file=/src/App.tsx

### Steps to reproduce

Copy this code to write 
```
export function useQuery<Data>(
  queryKey: string[],
  query: RequestDocument,
  options: Omit<UseQueryOptions, 'queryKey' | 'queryFn'>,
) {
  return useQueryOrig<Data>({
    queryKey,
    queryFn: async () => await client.request(query),
    ...options,
  });
}
```

### Expected behavior

Accurate type suggestion

### How often does this bug happen?

Every time

### Platform

macOS

### Tanstack Query version

v4.19.1

### TypeScript version

v4.8.3

**Comment by TkDodo** [comment]
`UseQueryOptions` has 4 generics that you need to abide by.

It is often not recommended to create low-level abstractions because a) it's quite hard to type  (as we can see) and b) the abstraction is very low level - would you really want all consumers to pass in a different `cacheTime` for the same `queryKey` for example?

I have a twitter thread on the topic as well:

https://twitter.com/TkDodo/status/1491451513264574501

Anyways, things work just fine if you provide the proper generics. Here's a fork of your sandbox: https://codesandbox.io/s/confident-lehmann-ye5zbi?file=/src/App.tsx

**Comment by c01inQvQ** [comment]
Hi @TkDodo, 

Sorry for replying on this closed issue, which might bother you.
I've encountered another issue when creating my own custom abstraction.
Just like the sandbox you provided above, I wrapped `useQueryOrig` with my custom `useQuery`.

However, even though I've explicitly passed in `initialData`, it will always give me `UseQueryResult` instead of `DefinedUseQueryResult`. In other words, TypeScript couldn't find the correct overloaded signature.

```ts
// The return type should be `DefinedUseQueryResult`, but got `UseQueryResult`
const { data } = useQuery<QueryData>(['random'], Query, {
  initialData: () => ({ posts: { data: [{ id: 123, title: '123' }] } }),
});
```

And it seems like the result of a few design limitations or missing features in TypeScript.
https://github.com/microsoft/TypeScript/issues/13235

Do you have any idea about working around this?

**Comment by TkDodo** [comment]
don't pass the generic:

```diff
- useQuery<QueryData>(['random'], ...)
+ useQuery(['random'], ...)
```

**Comment by c01inQvQ** [comment]
@TkDodo Thanks for your incredibly quick reply.
I've tried removing the generic, but got the same result.

**Comment by TkDodo** [comment]
oh yeah, this applies to `useQuery` from react-query. If you have your own wrapper around it, you'd need overloads like we have them. It's another reason to advise against low-level wrappers:

https://github.com/TanStack/query/blob/772e55d8314a92ab9f4dcb2d0c169453c9119454/packages/react-query/src/useQuery.ts#L52-L70

**Comment by c01inQvQ** [comment]
Oh, I got your point. Indeed, I need overloads on my own wrapper to make TypeScript work.
But actually, what I'm trying to implement is a bit more complicated than the above examples.

1. I have a factory function `createServiceQuery`, which accepts `defaultQueryOptions` and return a custom wrapper `useServiceQuery`
2. When calling the created `useServiceQuery`, we could also pass in `queryOptions`
3. The `defaultQueryOptions` and `queryOptions` are combined together as final query options

Please have a look at the following code snippets.

**Factory function `createServiceQuery`**
```ts
export const createServiceQuery = <
  TServiceMethodArgs extends unknown[],
  TQueryFnData = unknown,
  TError = unknown,
  TData = TQueryFnData,
  TQueryKey extends QueryKey = QueryKey,
>({
  serviceMethod,
  queryKeyCreator,
  defaultQueryOptions, // It's accepted to pass in `defaultQueryOptions` when calling factory function
}: CreateServiceQueryParams<
  TServiceMethodArgs,
  TQueryFnData,
  TError,
  TData,
  TQueryKey
>) => {
  const useServiceQuery = (
    ...args: UseServiceQueryArgs<
      TServiceMethodArgs,
      TQueryFnData,
      TError,
      TData,
      TQueryKey
    >
  ) => {
    const [serviceMethodArgs, queryOptions] = splitArgs(...args); // When calling `useServiceQuery`, we could also pass in `queryOptions`
    const queryKey = queryKeyCreator(...serviceMethodArgs);
    const queryFn = queryFnCreator(serviceMethod, ...serviceMethodArgs);
   
   // This is the original `useQuery`
    return useQuery({
      queryKey,
      queryFn,
      // The `defaultQueryOptions` and `queryOptions` are combined together here
      ...defaultQueryOptions,
      ...queryOptions,
    });
  };

  return useServiceQuery;
};
```

**Usage**
```ts
// We have some predefined `defaultQueryOptions` such as `initialData` or anything else
const useProductsQuery = createServiceQuery({
  serviceMethod: productsService.getProducts,
  queryKeyCreator: keyManager.products.list.key,
  defaultQueryOptions: {
    initialData: fallbackProductsQueryData,
    initialDataUpdatedAt: 0,
  },
});

// We could reuse the created `useProductsQuery` but give them different `queryOptions`
const Component = () => {
  // Without `queryOptions` 
  const { data: onSaleProductsData } = useProductsQuery({
      isOnSale: true,
    },
  );
  
  // With `queryOptions`, which set `cacheTime` as `0`
  const { data: newProductsData } = useProductsQuery(
    {
      tag: ProductTag.NEW,
      isRandom: true,
    },
    { cacheTime: 0 },
  );
};

  return (...);
}
```

Under these premises, implementing my own overloads will become more difficult and complicated.
But as you said, maybe I should avoid creating this kind of low-level abstraction, which is quiet hard to type.

Anyway, really appreciate for you quick reply. It really points out the core issue and helps me a lot.
