### ISSUE TITLE
ensureQueryData missing in queryClient

### ISSUE THREAD

**Issue by mkbctrl** [TanStack/query#4614]
### Describe the bug

Hey, 

I wanted to use: https://tanstack.com/query/v4/docs/reference/QueryClient#queryclientensurequerydata
and while setting up queryClient under my cusstom hook, I don't have an access to this method. I don't see any docs nor issues on that.

I have a nextjs up, so I console.logged the queryClient passed to context at it's source (_app.tsx) but it's missing there as well

If I missed smth, sorry for bothering but I did extensive research before this submission.

Hope it help 🤞 

### Your minimal, reproducible example

https://codesandbox.io/s/nextjs-react-query-forked-roxsky?file=/pages/index.js

### Steps to reproduce

![Screenshot 2022-12-09 at 12 28 41](https://user-images.githubusercontent.com/10107362/206692813-d34588a2-b688-4e99-a125-3c24d3032826.png)

### Expected behavior

I should be able to access this function

### How often does this bug happen?

Every time

### Platform

Mac os, any browser

### Tanstack Query version

v4.14.5

### TypeScript version

v4.8.4

**Comment by TkDodo** [comment]
the sandbox you're linking uses `react-query` `v3.19.6`.

The function is available in `@tanstack/react-query` starting from `v4.18.0`

https://github.com/TanStack/query/releases/tag/v4.18.0
