### ISSUE TITLE
docs: Optimistic updates javascript example sandbox not loading 

### ISSUE THREAD

**Issue by shubham-y** [TanStack/query#4620]
### Describe the bug

I came to [React Example: Optimistic Updates](https://tanstack.com/query/v4/docs/examples/react/optimistic-updates) docs page from [Mastering Mutations in React Query](https://tkdodo.eu/blog/mastering-mutations-in-react-query#example) blog example section and found the sandbox not being loaded

### Your minimal, reproducible example

https://tanstack.com/query/v4/docs/examples/react/optimistic-updates

### Steps to reproduce

1. Go to https://tkdodo.eu/blog/mastering-mutations-in-react-query#example
2. Click on [in JavaScript](https://react-query.tanstack.com/examples/optimistic-updates) anchor link
3. See sandbox not being loaded

### Expected behavior

Expected to see to the sandbox example being loaded

### How often does this bug happen?

Every time

### Platform

- OS: Windows 11
- Browser: Brave

### Tanstack Query version

v4

**Comment by TkDodo** [comment]
That's because the example links have changed, it's now:
- https://tanstack.com/query/v4/docs/examples/react/optimistic-updates-typescript

If you're kind, you'll make a PR to my blog fixing the link :)

**Comment by TkDodo** [comment]
also, we removed the JS example and only the TS on exists
