### ISSUE TITLE
eslint: wrong autofix for multi-line queries

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#4630]
the following query auto-fixes correctly when using `@tanstack/query/prefer-query-object-syntax`:

```
// input
const query = useQuery(['key'], () => Promise.resolve('data'))

// output
const query = useQuery({ queryKey: ['key'], queryFn: () => Promise.resolve('data') })
```

However, if you have the same query in a multi-line setup, the output is wrong:

```
// input
const query = useQuery(
  ['key'], 
  () => Promise.resolve('data'),
)

// output

const query = useQuery(
    ,
{ queryKey: ['key'], queryFn: () => Promise.resolve('data') })
```

Gif of working version:
![screencast 2022-12-13 16-17-33](https://user-images.githubusercontent.com/1021430/207372965-ce89479e-9b27-4537-92d9-bad71cc00e0e.gif)

Gif of non-working version
![screencast 2022-12-13 16-16-17](https://user-images.githubusercontent.com/1021430/207373150-eb456b0b-2076-48d1-a6db-716df66f9f45.gif)

@Newbie012 FYI

**Comment by Newbie012** [comment]
I'll take a look at it
