### ISSUE TITLE
Refetch doesn't update component

### ISSUE THREAD

**Issue by voortexx** [TanStack/query#4645]
### Describe the bug

Hello, 
Thank you for this library which I find fantastic, but I am facing a problem that I do not understand.

I have a feed that works very well with `useInfiniteQuery`. I manage to post a message and update the display.

I also have a comment feed which is a screen using the same component as the previous one. But for this one I can't update the data either with a `refetch` or an `invalidateQuery`. In fact just the first `refetch` with a new data works. The only thing that works is `resetQueries`, but it bothers me a bit to go through an initialization loading again before displaying the new messages.

However, on the network side I can see the new message, but the data returned by `useInfiniteQuery` is not up to date.
But if in my Flatlist I change the data to [] en then the data returned from the hooks it's ok.

It's like the screen or component is not rerendered.

In my Comment screen
````
 const { data, isLoading, isFetching, fetchNextPage, refetch } = useGetComments({
    clientId,
    feedType,
    feedItemId: feedGroupItemId || itemFromRoute?.id,
  });
 // data here stay the same <-----------

  const { pages } = data || {};

  const commentsData = pages ? pages.flatMap((page) => page.data) : [];
````

My hooks
````
export const useGetComments = ({
  clientId,
  feedItemId,
  feedType,
  limit = 8,
  isFeedComment = false,
}) => {
  return useInfiniteQuery(
    ['comments', { clientId, feedItemId, feedType, isFeedComment }],
    async ({ pageParam }) => {
      if (isFeedComment) {
        return { data: undefined, meta: undefined };
      }
      const { data, meta } = await interactionsApi
        .getComments({ clientId, feedItemId, feedType, next: pageParam, limit })
        .then((p) => p.request);
      return { data, meta };
    },
    {
      getNextPageParam: (currentPage) => {
        return currentPage?.meta?.next;
      },
    },
  );
};
````

Hooks to add a comment
````
export const useAddOneComment = ({ clientId, feedItemId, feedType, medias = [] }) => {
  const queryClient = useQueryClient();

  return useMutation(
    async (content) => {
      return interactionsApi
        .createComment({
          clientId,
          content,
          medias,
          feedItemId,
          feedType,
        })
        .then((p) => p.request);
    },

    {
      onSuccess: () => {
        queryClient.invalidateQueries([
          'comments',
          { clientId, feedItemId, feedType, isFeedComment: false },
        ]);
      },
    },
  );
};
````
### Your minimal, reproducible example

/

### Steps to reproduce

/

### Expected behavior

/

### How often does this bug happen?

None

### Platform

react-native
Version: 0.68.2

### Tanstack Query version

4.14.5

**Comment by TraNguyen95** [comment]
Same issue

**Comment by TkDodo** [comment]
Please show a minimal, runnable reproduction or I'll close this issue

**Comment by TkDodo** [comment]
we can reopen this issue once you have a reproduction
