### ISSUE TITLE
Latest major version issues with Cypress clock

### ISSUE THREAD

**Issue by louis-young** [TanStack/query#4655]
### Describe the bug

Firstly, thanks for the plethora of amazing libraries. 

I've used React/TanStack query for years without issue but I've noticed what I think is possibly unintended/undesirable behaviour when testing a component that uses a query with a refetch interval through Cypress when using the clock to advance time. I'm not convinced this is a bug in TanStack query per se but I thought it was worth raising an issue as it exhibits very different behaviour between version 3 and 4 and wondered if it might be classified as a regression of sorts.

### Problem

When testing a component that uses a query with a refetch interval through Cypress when using the clock to advance time, the query hook appears to hang in a loading/fetching state, despite the request having resolved successfully. 
 
 ### Observations
 
1. This occurs on the initial/first request and causes the test to fail.
2. This _does not_ happen when the Cypress clock isn't being used (so essentially when the refetch interval is less than the Cypress timeout and there's no need to use fake timers/advance time).
3. This _does not_ happen with React Query version 3.39.2.
4. This _does_ happen with TanStack Query version 4.20.4.

### Thoughts

I imagine there's possibly been a change in the TanStack Query internals that now depends on one of the timing APIs that Cypress clock fakes but I'm not convinced this is the case. I'd imagine it was using one of these constructs before. Perhaps I've implemented the test incorrectly or there's something I'm missing.

### Your minimal, reproducible example

https://github.com/louis-young/tanstack-query-cypress-clock-issue-v4, https://github.com/louis-young/tanstack-query-cypress-clock-issue-v3

### Steps to reproduce

Sorry, I know the reproduction steps are somewhat onerous but I think this is the only way to demonstrate issues with Cypress tests.

### Version 3

1. Clone https://github.com/louis-young/tanstack-query-cypress-clock-issue-v3
2. Run `npm install`, `npm start`, and then `npm test` in the root directory.
3. Run the test that appears in the Cypress runner.
4. Note how the test passes as expected.

### Version 4

1. Clone https://github.com/louis-young/tanstack-query-cypress-clock-issue-v4
2. Run `npm install`, `npm start`, and then `npm test` in the root directory.
3. Run the test that appears in the Cypress runner.
4. Note how the test fails and the query hook hangs in a loading/fetching state.

### Expected behavior

I'd expect both tests using both versions to exhibit the same behaviour.

### How often does this bug happen?

Every time

### Platform

- OS: Windows and macOS
- Browser: Google Chrome version 108.0.5359.124 (Official Build) (arm64)
- TanStack Query version: 4.20.4
- Cypress version: 12.1.0
- React version: 18.2.0
- React DOM version: 18.2.0

### Tanstack Query version

4.20.4

### Additional context

Thanks again for the fantastic libraries. I'd be surprised if this is an actual bug with TanStack Query but I thought it was worth raising to clarify the change in behaviour.

**Comment by TkDodo** [comment]
no idea what's the issue here. We use `setTimeout` and `setInterval` under the hood, and no changes were made between v3 and v4. I only checked out the v4 example, but it fails at the first assertion. So I don't think it has anything to do with the `refetchInterval`. Commenting out `cy.clock()` makes the first assertion work.

removing all `clock` associated code and changing the `refetchInterval` to one second also makes the test pass, because the interval is fired immediately.

We also use timers for other things like garbage collection. Maybe this is related, idk.

**Comment by louis-young** [comment]
Thanks for getting back to me. I also have no idea what the issue is here or why it’s only present in v4! I’ve proven it’s caused by using fake timers and advancing time but I’ll try and narrow it down further. 

I’ll let you know as and when I get to the bottom of it. Thanks for the garbage collection pointer.

Thanks again. I’ll close this issue as it’s evidently not an issue with TanStack Query itself 🙂

**Comment by louis-young** [comment]
@TkDodo I've found some time to look at this and have resolved it. If you were interested, mocking the implementation of `setTimeout` was the problem, even when advancing time.

I've tested this with Playwright using Sinon fake timers and it exhibits the same behavior (unsurprisingly as Cypress uses Sinon under the hood).

This does the trick (explicitly specifying the APIs to mock):

```diff
- cy.clock();
+ cy.clock(null, ["setInterval", "clearInterval"]);
```

Hopefully this helps someone in the future 🙂

**Comment by TkDodo** [comment]
Thank you 🙏

**Comment by dexterionut** [comment]
Hey there! Can we please reopen this issue as I'm experiencing the same problem using `jest.useFakeTimers()`? It is indeed breaking if I am not explicitly telling to jest no to fake the `setTimeout` as @louis-young suggested.

**Comment by dexterionut** [comment]
I've opened a PR to add a failing test but it seems that it's actually working with faketimers from jest. 

I found that the problem on my side was because we were using older version of the react testing library.
Upgraded to `"@testing-library/react-hooks": "8.0.1"` and `"@testing-library/react": "12.1.5"` and the react-query doesn't break anymore while using fake timers.

**Comment by robdodson** [comment]
@louis-young you are a _saint_! Thank you! I've been banging my head against this all day.

**Comment by louis-young** [comment]
> @louis-young you are a _saint_! Thank you! I've been banging my head against this all day.

You're welcome! I had to deprioritise this for a while, but I'll need to look at it again and solve it properly soon. 

The solution I proposed doesn't work in all scenarios. It won't work when another piece of code under test uses `setTimeout` with a long timeout duration. This is blocking some upgrades to v4, and with v5 just around the corner, this is starting to become a real issue.

**Comment by robdodson** [comment]
Thankfully in my case we just needed to change a `cy.clock(now)` to `cy.clock(now, ['Date'])`. But I was nowhere near figuring out why the test was failing. After spending all day on it, I came here and searched 'Cypress' and was lucky enough to hit on your response. Thank you for saving me countless more hours 😅

**Comment by TkDodo** [comment]
Should we put this as a common gotcha into the testing guide of the docs?

**Comment by louis-young** [comment]
> Should we put this as a common gotcha into the testing guide of the docs?

I think so, it’d be useful until we can identify what changed between v3 and v4 to cause both parties not to play nicely together.

It’s an difficult one because as far as I can see there’s not an actual issue with React Query or Sinon (the fake timer implementation used by Cypress and Playwright), they just don’t seem to play nicely together anymore.

I’m happy to put together the change for the documentation, and, if I get time (that’s a big if unfortunately), step through every change that went into v4 until I can identify the root cause 🙂

**Comment by robdodson** [comment]
I don't know if it's any help, but I can share the react-query code that was getting stuck. I think we use cy.clock in other tests, but this was the only one that was failing.

```tsx
const getSeries = async () => {
  try {
    const res = await network.get<DataSourcesPayload>(
      endpoints.realtimeEnergy.series()
    )
    return res
  } catch (e) {
    throw new Error(e)
  }
}

const getEvents = async ({ startDate }) => {
  try {
    const res = await network.get<EventsDataPayload>(
      endpoints.realtimeEnergy.events({
        start_time: startDate,
      })
    )
    return res
  } catch (e) {
    throw new Error(e)
  }
}

export const useDataSources = (
  startDate: string
): [
  DataSources,
  EventsDataPayload,
  {
    dataSourcesQuery: QueryObserverResult<DataSourcesPayload>
    eventsQuery: QueryObserverResult<EventsDataPayload>
  }
] => {
  const dataSourcesMap = React.useRef<DataSources>(new Map())
  const events = React.useRef<EventsDataPayload>({})
  const dataSourcesQuery = useQuery('rt-dash-series', getSeries, {
    refetchOnWindowFocus: false,
  })

  const eventsQuery = useQuery<EventsDataPayload>({
    queryKey: ['rt-dash-events', startDate],
    queryFn: () => getEvents({ startDate }),
    enabled: !!startDate,
    refetchOnWindowFocus: false,
  })

  events.current = React.useMemo(() => {
    // Keep old data around while the new data is fetching
    if (eventsQuery.isFetching || eventsQuery.isLoading) {
      return events.current
    }
    // Otherwise, we have real data, so replace it
    if (eventsQuery.data) {
      return eventsQuery.data
    }

    // Fallback
    return events.current
  }, [eventsQuery.isFetching, eventsQuery.isLoading, eventsQuery.data])

  // If we have data sources, flatten them out
  dataSourcesMap.current = React.useMemo(() => {
    if (dataSourcesQuery.data) {
      return dataSourceUtils.flattenDataSources(dataSourcesQuery.data)
    }

    return dataSourcesMap.current
  }, [dataSourcesQuery.data])

  // For convenience, pass the data we care about first,
  // but also expose the raw queries in case downstream components needs to look
  // at loading states
  return [
    dataSourcesMap.current,
    events.current,
    {
      dataSourcesQuery,
      eventsQuery,
    },
  ]
}
```

```js
context('Realtime Dashboard Without Events', () => {
  beforeEach(() => {
    cy.auth()
    cy.viewport(1300, 1000)

    cy.visit(`http://localhost:${Cypress.env('APP_PORT')}/dashboard`, {
      onBeforeLoad(win) {
        const mockFetchWithoutEvents = (path) => {
          if (path.includes('/events')) {
            return Promise.resolve({
              json: () => ({}),
              ok: true,
              text: () => '{}',
            })
          }

          return mockFetch(path)
        }
        // Our fixtures have active events, so let's no use the out of the box mock
        cy.stub(win, 'fetch', mockFetchWithoutEvents)
      },
      onLoad(win) {
        win.voltusMeta = makeVoltusMeta()
      },
    })
  })

  it('Empty Realtime dashboard matches screenshot', () => {
    // Test fails here because we never get our mock data back from the react-query hook
    cy.contains('Search for a facility or market').should('be.visible')
    cy.matchImageSnapshot('realtime-energy-initial-load-empty')
  })
})
```

**Comment by justasdev** [comment]
Seems like closing this issue means "we won't fix this" instead of "issue is fixed". People are still struggling with it. Is it really not possible to make it work like v3? What tradeoffs should you introduce for it to work as before?
React query was a really great library because using it was seamless - no boilerplate, no complexity, works great in any case! It is sad to see it has changed in a bad way
