### ISSUE TITLE
React Query v4 Examples and links not working

### ISSUE THREAD

**Issue by DavidYang2149** [TanStack/query#4660]
### Describe the bug

The examples section in v4 of the docs isn't loading and the links to error page. See this page for example link & screenshot

### Link

[https://tanstack.com/query/v4/docs/react/examples/basic](https://tanstack.com/query/v4/docs/react/examples/basic)

### Screenshot

<img width="909" alt="error" src="https://user-images.githubusercontent.com/40143056/208369185-ae60569a-8d7a-4a27-b562-3742a5226e68.png">

### Your minimal, reproducible example

https://tanstack.com/query/v4/docs/react/examples/basic

### Steps to reproduce

1. Direct access
Open page at [https://tanstack.com/query/v4/docs/react/examples/basic](https://tanstack.com/query/v4/docs/react/examples/basic) and notice the example doesn't load.

<img width="789" alt="direct-error" src="https://user-images.githubusercontent.com/40143056/208370257-f31679c6-6486-4831-854b-3cae42b7320b.png">

2. Indirect access
Open page at [https://tanstack.com/query/v4](https://tanstack.com/query/v4) and click "Examples" link and see error page.

<img width="909" alt="indirect-error" src="https://user-images.githubusercontent.com/40143056/208370283-0f834046-63fa-4d23-9fef-34e1e8ec064d.png">

### Expected behavior

The examples should load and the links should be active.

### How often does this bug happen?

Every time

### Screenshots or Videos

1. Direct access
<img width="789" alt="direct-error" src="https://user-images.githubusercontent.com/40143056/208370257-f31679c6-6486-4831-854b-3cae42b7320b.png">

2. Indirect access
<img width="909" alt="indirect-error" src="https://user-images.githubusercontent.com/40143056/208370283-0f834046-63fa-4d23-9fef-34e1e8ec064d.png">

### Platform

macOS 13.0.1
Chrome 108.0.5359.124

### Tanstack Query version

NA

### TypeScript version

No response

### Additional context

No response

**Comment by TkDodo** [comment]
works for me, but links have changed:
- https://tanstack.com/query/v4/docs/react/examples/react/basic

@DamianOsipiuk shouldn't they redirect?

when I'm entering 
- https://tanstack.com/query/v4/docs/react/examples/basic

I only get a page that says `Unexpected Server Error`

**Comment by DamianOsipiuk** [comment]
Old links to examples should be properly redirected. Ex. https://tanstack.com/query/v4/docs/examples/react/basic
There is one link that i have missed, which point to a wrong url:
![image](https://user-images.githubusercontent.com/28151934/208391560-3abc25fc-a0b9-46c6-ac34-72f6a03b15e7.png)

But i will tinker with redirects logic, to fix this corner case as well.

**Comment by AmitGurbani** [comment]
Navigation links at bottom doesn't work as well.

https://tanstack.com/query/v4/docs/react/overview
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/8795134/208392776-df3d1cf0-6c73-4520-8f67-887d5429b112.png">

Clicking on Installation leads to https://tanstack.com/query/v4/docs/react/react/installation
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/8795134/208393248-24a8eb91-be95-4d81-8836-caaa6d693375.png">

**Comment by TkDodo** [comment]
yep, well spotted. They go to:
- https://tanstack.com/query/v4/docs/react/react/installation

so double `react` 😅
