### ISSUE TITLE
'queryClient.invalidateQueries' is not working when Using multiple elements in queryKey array  with Vue

### ISSUE THREAD

**Issue by kimsupin** [TanStack/query#4669]
### Describe the bug

I want to invalidate some queries when component is unmounted. 

so, I write code like this

```js
onUnmounted(() => {
    queryClient.invalidateQueries({ queryKey: ['key1', 'key2'] });
});
``` 

but this code is not worked
(not refetching when the component is re-rendering). 

so I do invalidate query each other.. like this...

```js
onUnmounted(() => {
    queryClient.invalidateQueries({ queryKey: ['key1'] });
    queryClient.invalidateQueries({ queryKey: ['key2'] });
});
```
and it's working! but the documents is written it's possible to invalidate multiple query at once.

https://tanstack.com/query/v4/docs/react/reference/QueryClient#queryclientinvalidatequeries
https://tanstack.com/query/v4/docs/react/guides/query-keys

what should I do for solving this problem? 

### Your minimal, reproducible example

confidential

### Steps to reproduce

```js
<script setup lang="ts">
...

onUnmounted(() => {
    queryClient.invalidateQueries({ queryKey: ['key1', 'key2'] });
});

...
</script>
``` 

### Expected behavior

I expect to fetch data when the component is re-render.

### How often does this bug happen?

Every time

### Platform

- OS: MacOs
- Browser: Chrome 108
- vue: ~2.7.10

### Tanstack Query version

^4.17.0

**Comment by TkDodo** [comment]
This is a misconception of how fuzzy query invalidation works.

`queryClient.invalidateQueries({ queryKey: ['key1', 'key2'] });` will invalidate all keys _starting with_ `['key1', 'key2']`, _not_ those starting with either `key1` _or_ `key2`.

With query keys, it is advised to build a hierarchy, so that you can target various scopes at once. I've written about that here: https://tkdodo.eu/blog/effective-react-query-keys

**Comment by kimsupin** [comment]
@TkDodo yeah I want to invalidate all queries that I set in queryKey array. 
but it doesn't work. (not invalidate when I write all keys in one array)

**Comment by TkDodo** [comment]
if you want to invalidate `key1` and `key2` with one call, they need to have something in common. If they are:

```
['foo', 'key1']
['foo', 'key2']
```

you can target them both with `queryClient.invalidateQueries(['foo'])`.

**Comment by kimsupin** [comment]
ok tanks!

**Comment by dileepainivossl** [comment]
> This is a misconception of how fuzzy query invalidation works.
> 
> `queryClient.invalidateQueries({ queryKey: ['key1', 'key2'] });` will invalidate all keys _starting with_ `['key1', 'key2']`, _not_ those starting with either `key1` _or_ `key2`.
> 
> With query keys, it is advised to build a hierarchy, so that you can target various scopes at once. I've written about that here: https://tkdodo.eu/blog/effective-react-query-keys

import { useQuery, useQueryClient } from '@tanstack/react-query';
import userRequest from '@/utils/AxiosInstance';

export const useGetQuery = <TResponse, TParams>(
  queryKey: (string | number)[],
  url: string,
  params: TParams
) => {
  const client = useQueryClient();
  return useQuery({
    queryKey: queryKey,
    queryFn: async () => {
      const { data } = await userRequest.get(url, {
        params: params,
      });
      return data as TResponse;
    },
    onSuccess: (data: TResponse) => {
      // client.invalidateQueries(queryKey);
      console.log(data);
    },
    onError: (err) => {
      console.error(err);
    },
  });
};

In this function it keeps reloading the api call, is there something wrong

**Comment by TkDodo** [comment]
> In this function it keeps reloading the api call, is there something wrong

invalidate does a refetch, so yeah, your code refetches, and onSuccess, it refetches again, which trigger onSuccess, which fetches again ...

not sure what you're trying to achieve with invalidation in onSuccess, but please note that the callbacks (onSuccess, onError, onSettled) on useQuery are deprecated and will be removed in the next major version.

**Comment by dileepainivossl** [comment]
> > In this function it keeps reloading the api call, is there something wrong
> 
> invalidate does a refetch, so yeah, your code refetches, and onSuccess, it refetches again, which trigger onSuccess, which fetches again ...
> 
> not sure what you're trying to achieve with invalidation in onSuccess, but please note that the callbacks (onSuccess, onError, onSettled) on useQuery are deprecated and will be removed in the next major version.

Im trying to invalidate because, In my issue, Im trying to edit my record in frontend, so to do that first I use GET, then the PATCH, issue occured was after editing that record, and Im trying to edit the same record again it shows me the previous data, not the updated ones

**Comment by TkDodo** [comment]
> Im trying to invalidate because, In my issue, Im trying to edit my record in frontend, so to do that first I use GET, then the PATCH, issue occured was after editing that record, and Im trying to edit the same record again it shows me the previous data, not the updated ones. How can I fix that

the query invalidation needs to happen in the callbacks of `useMutation` (where the PATCH request happens), not in the callbacks of the query (where the GET request happens)

**Comment by dileepainivossl** [comment]
> > Im trying to invalidate because, In my issue, Im trying to edit my record in frontend, so to do that first I use GET, then the PATCH, issue occured was after editing that record, and Im trying to edit the same record again it shows me the previous data, not the updated ones. How can I fix that
> 
> the query invalidation needs to happen in the callbacks of `useMutation` (where the PATCH request happens), not in the callbacks of the query (where the GET request happens)

Is there a way to invalidate the GET queries

**Comment by Demetri0** [comment]
> Is there a way to invalidate the GET queries

GET/PATCH doesn't mater here, you invalidate queries by their `queryKey` and you should trigger invalidation at the moment when you want to invalidate it.

**Comment by Abg4work** [comment]
@kimsupin You can try something like this:
```
await queryClient.invalidateQueries({
                predicate: query =>
                    ['key1', 'key2' ].includes(query.queryKey[0] as queryKeys)
});
```

Refer [this page in doc](https://tanstack.com/query/v4/docs/framework/react/guides/query-invalidation) for more information.
