### ISSUE TITLE
require minimum of TS 4.7

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#4674]
v5 will need TS4.7 or greater to support the object syntax properly.

**Comment by incepter** [comment]
I believe the ts version in the repository of react-query should always use the latest version (or any the maintainers feel okay with!), since it won't affect the developers' land

**Comment by TkDodo** [comment]
If we use the latest version and use features of the latest version (4.9), like `satisfies`, the .d.ts files that we ship as type definitions will not work with versions prior to 4.9. we could do differential transpiling and ship different types for lower TS versions but that effort is not worth it imo.
