### ISSUE TITLE
rename useErrorBoundary

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#4677]
### context

A property that starts with the prefix `use` is unfortunately named, as `use` usually indicates a hook in React. `ErrorBoundary` might also be a quite react specific term.

Renaming the property to e.g. `throwError` would more accurately describe what is happening: the error will be thrown. In React, it will be picked up by the nearest error boundary.

### proposal

- rename `useErrorBoundary` to `throwError`

**Comment by Moshyfawn** [comment]
Should this issue be assigned to be then?
