### ISSUE TITLE
Add 'use client' in the correct places

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#4689]
To be compatible with React Server Components

@Ephem we'd need to decide if this can go into v4 or if we also do this for v5

**Comment by Ephem** [comment]
At least on the surface this is an easy fix with no downsides I can see that helps early adopters play with the new APIs without a bunch of wrapping, so I think we should add it in a v4 minor. I haven't investigated the exact places to add it yet though, but that shouldn't be that tricky.

**Comment by Suman085** [comment]
I would be happy to contribute here if I get more clarity on the work that needs to be done here :)

**Comment by TkDodo** [comment]
@Suman085 we'd need to add `"use client"` at the top of all files that use either state, context or effects in order to have them opt out of being server components in next13.

the devtools would also naturally need `"use client"`.

**Comment by abhijithp05** [comment]
Please close this issue
