### ISSUE TITLE
hydration

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#4691]
Hydration implementation details (major)
Step 1: Should still happen in render for new queries (and queries with no observers?), but be scheduled for a useEffect for queries that someone is actively listening to since this results in re-renders/observable side effects
Step 2 (optional): When hydrating in useEffect also add the new data to a context for that subtree, refactor all reads to patch in data from that context. That subtree safely gets the new data during the same render instead of after, "true" cache and thus anything listening outside of that subtree gets updated via the useEffect (This might be overkill, we should evaluate if step 1 is good enough first)

@Ephem

**Comment by Ephem** [comment]
I wanted to throw together a demo of this issue so it's easily understandable, and as something to verify the changed behaviour against, so threw together a sandbox here: https://codesandbox.io/s/hydrate-in-render-demonstration-uvpe46?file=/src/App.js
