### ISSUE TITLE
Rename `Hydrate` to `HydrationBoundary`

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#4692]
and remove `useHydrate` hook

**Comment by Omar-Awawdeh** [comment]
Should the `useHydrate` hook be replaced with anything or just completely removed?

**Comment by TkDodo** [comment]
> Should the `useHydrate` hook be replaced with anything or just completely removed?

It can be removed

**Comment by prateek3255** [comment]
Hey @TkDodo I would like to contribute to this issue and write the codemod for it

**Comment by TkDodo** [comment]
perfect, it's yours

**Comment by TkDodo** [comment]
@prateek3255 please wait with the code-mod until we have the setup in place, see:
- https://github.com/TanStack/query/issues/4705#issuecomment-1385437601

we'll probably create separate code-mod issues then for each one.

**Comment by sshmaxime** [comment]
Hey, I think you should update the documentation [here](https://tanstack.com/query/v4/docs/react/guides/ssr): `<Hydrate state={dehydratedState}>`

**Comment by TkDodo** [comment]
you're looking at v4 docs, the rename happened in v5

**Comment by sshmaxime** [comment]
My bad, thanks dude 👍
