### ISSUE TITLE
Eslint plugin removes generics from useQuery hooks

### ISSUE THREAD

**Issue by brianlovin** [TanStack/query#4696]
### Describe the bug

Originally [shared on Twitter](https://twitter.com/brian_lovin/status/1606351401101074432).

The `@tanstack/eslint-plugin-query` package is removing generics from `useQuery` hooks when `--fix`ed:

![Screen Shot 2022-12-23 at 11 39 46@2x](https://user-images.githubusercontent.com/1923260/209392982-84c5c6a5-7982-4ab4-8cec-c66a2b5368a7.png)

### Your minimal, reproducible example

N/A

### Steps to reproduce

1. Have a `useQuery` hook with generics passed for `Data` and `Error`
2. Install the eslint plugin with default rules
3. `--fix` the file

### Expected behavior

I would expect my manually-typed generics for `Data` and `Error` to be considered when the eslint plugin switches me to `prefer-object-syntax` rules.

### How often does this bug happen?

Every time

### Screenshots or Videos

![Screen Shot 2022-12-23 at 11 39 46@2x](https://user-images.githubusercontent.com/1923260/209393202-19954465-1645-4aa5-b6e4-5135ca1a8c68.png)

### Platform

- macOS
- VSCode

### Tanstack Query version

4.2.3

### TypeScript version

4.8.2

**Comment by brianlovin** [comment]
Note: after the initial `--fix` removes the generics, if I add them back in, they won't be cleared. They are only being cleared in the codemod that moves to object syntax.

**Comment by TkDodo** [comment]
@Newbie012 fyi

**Comment by Newbie012** [comment]
should be fixed in https://github.com/TanStack/query/pull/4703
