### ISSUE TITLE
codemods for v5

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#4705]
for breaking syntax changes:

- #4694 
- #4677 
- #4678 
- #4692 
- #4688 

@balazsmatepetro let me know if you want to work on this :)

**Comment by moaoa** [comment]
I am interested

**Comment by balazsmatepetro** [comment]
@TkDodo of course! :)

**Comment by TkDodo** [comment]
We can also split the work into multiple codemods - just want to avoid two people doing the same work :)

**Comment by balazsmatepetro** [comment]
> We can also split the work into multiple codemods - just want to avoid two people doing the same work :)

Sounds like a plan. ;)

**Comment by moaoa** [comment]
Hello there

I have some experience with code mods and can help can you guys give some guidance

**Comment by TkDodo** [comment]
@moaoa if you want, please review the PR for the overloads removal codemod:

- #5046

**Comment by moaoa** [comment]
Great
I have exams in the next two weeks
As soon as I finish I will look into that

**Comment by TkDodo** [comment]
I created separate issues for the remaining codemods:

https://github.com/TanStack/query/issues?q=is%3Aissue+is%3Aopen+codemod
