### ISSUE TITLE
eslint-plugin-query suggests wrong dependencies

### ISSUE THREAD

**Issue by DreierF** [TanStack/query#4724]
### Describe the bug

I tried to run the new ESLint plugin on our codebase and found a few cases that did not produce the expected results for the `@tanstack/query/exhaustive-deps` rule.

### Your minimal, reproducible example

https://stackblitz.com/edit/node-cnvnyj?file=src/index.js

### Steps to reproduce

The following example

```js
import { useQuery } from '@tanstack/react-query';

class Foo {}

function useData(arg, ...args) {
  return useQuery({
    queryKey: ['foo', arg, ...args],
    queryFn: async () => {
      if (arg === undefined) {
        return null;
      }
      return new Foo([arg, ...args]);
    },
  });
}
```

results in 

```
  7:5  error  The following dependencies are missing in your queryKey: undefined, Foo, args  @tanstack/query/exhaustive-deps
```

- Arrays that are already part of the query key (`args`) are not considered
- `undefined` is considered to be a variable
- The `Foo` class is considered to be a variable

### Expected behavior

Actually I would expect to not get any error for the code snippet. The last one might be tricky to avoid as it could theoretically be reassigned, but it should be enough to exclude values imported from a JS module as (to my understanding) those are guaranteed to not change after initial module initialization.

### How often does this bug happen?

Every time

### Platform

macOS

### TanStack Query version

4.20.7

### TypeScript version

-

**Comment by TkDodo** [comment]
agree, the example should be fine and the reported errors are false positives. @Newbie012 can you take a look?

**Comment by Newbie012** [comment]
Should be fixed after https://github.com/TanStack/query/pull/4725 is merged
