### ISSUE TITLE
Examples in documentation not working

### ISSUE THREAD

**Issue by SyFlo** [TanStack/query#4737]
### Describe the bug

The examples, links to codesandbox etc. in the documentation are broken. I think that's probably because the links point to e.g. https://github.com/TanStack/query/tree/main/examples/simple but that path does not exist anymore since the examples folder in the code now has subfolders "react", "solid" and "vue".

### Your minimal, reproducible example

https://react-query-v3.tanstack.com/examples/simple

### Steps to reproduce

1. Go to the documentation page https://react-query-v3.tanstack.com/examples/simple
2. Try to read example code

### Expected behavior

As a user I expect to see working documentation including example code, but I see only a black square instead.

### How often does this bug happen?

None

### Platform

- OS: not relevant
- Browser: not relevant

### TanStack Query version

v4.20.8

**Comment by TkDodo** [comment]
https://github.com/TanStack/query/issues/4108
