### ISSUE TITLE
Edit this page on GitHub [Link] gives 404 on the mentioned link for every page

### ISSUE THREAD

**Issue by Assad-Ashraf** [TanStack/query#4754]
### Describe the bug

Edit this Page link on the docs gives 404 for the link ( https://github.com/TanStack/query/edit/master/docs/src/pages/guides/suspense.md )

### Your minimal, reproducible example

https://react-query-v3.tanstack.com/guides/suspense

### Steps to reproduce

1. Go to any page like ( https://react-query-v3.tanstack.com/guides/suspense )
2. Scroll down to the bottom 
3. hit Edit this page on Github Link

### Expected behavior

Should either be removed or the link is to be updated.

### How often does this bug happen?

Every time

### Platform

On every OS it is happening

### TanStack Query version

4.20.9

**Comment by TkDodo** [comment]
yeah because the master branch doesn't exist anymore. it works fine for v4
