### ISSUE TITLE
No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by bquangDinh** [TanStack/query#4784]
### Describe the bug

I'm trying to use React Query DevTools, followed the doc, and put it inside QueryClientProvider. But the error is still there. Removed it, and things worked like normal. So I guessed it must be from ReactQueryDevTools. Here the code. I used NextJS.

```ts
function MyApp({ Component, pageProps }: any): JSX.Element {
	const Layout = Component.Layout ? Component.Layout : React.Fragment;

	const router = useRouter();

	const queryClient = new QueryClient();

	useEffect(() => {
		if (AppConfigs.NODE_ENV === 'production' || AppConfigs.NODE_ENV === 'prod') {
			const analytics = getAnalytics(FirebaseApp);

			const logRouterEvent = (url: string) => {
				logEvent(analytics, 'screen_view', {
					firebase_screen: url,
					firebase_screen_class: 'asdas',
				});
			};

			router.events.on('routeChangeComplete', logRouterEvent);

			logRouterEvent(router.pathname);

			return () => {
				router.events.off('routeChangeComplete', logRouterEvent);
			};
		}
	// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);

	return (
		<Provider store={store}>
			<QueryClientProvider client={queryClient}>
				<ConfigProvider
					locale={viVN}
					theme={{
						algorithm: theme.defaultAlgorithm,
						token: {
							colorPrimary: '#0554F2'
						}
					}}
				>
					<Layout>
						<Component {...pageProps} />
					</Layout>
				</ConfigProvider>
				<ReactQueryDevtools></ReactQueryDevtools>
			</QueryClientProvider>
		</Provider>
	);
}
```

### Your minimal, reproducible example

Described above

### Steps to reproduce

Described above

### Expected behavior

I expected it to work like the doc

### How often does this bug happen?

Every time

### Platform

Mac OS
Chrome

### TanStack Query version

3.39.2

### TypeScript version

4.1.3

**Comment by judicaelandria** [comment]
Hey! the minimum version I can install now is 4.0, so I cannot repro this! but your code looks fine! but perhaps you could try upgrading React Query and the devtools, and let's see if it solves the issue?

**Comment by TkDodo** [comment]
please provide a runnable reproduction. feel free to reopen if you have one.

**Comment by judicaelandria** [comment]
@bquangDinh just checking, are you using ```@tanstack/react-query``` or ```react-query``` ?
if you're using ```react-query``` please use ```@tanstack/react-query```, ```react-query``` is not maintained anymore (latest version is 3.39.2)

**Comment by bquangDinh** [comment]
Thank you. I wasn't aware of that fact. Thought `react-query` and `@tanstack/react-query` are the same thing. I'll check it out.

**Comment by judicaelandria** [comment]
> Thank you. I wasn't aware of that fact. Thought `react-query` and `@tanstack/react-query` are the same thing. I'll check it out.

yeah! but `@tanstack/react-query` is the one maintained right now w/ the latest version so everything should work

**Comment by uttu-316** [comment]
```
import React from 'react';
import {StatusBar} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import AppNavigator from './src/navigators';
import {theme} from './src/utils/theme';
import {navigationRef} from './src/utils/navigation';
import {Provider} from 'react-redux';
import {PersistGate} from 'redux-persist/integration/react';
import {store, persistor} from './src/redux/store';
import SplashScreen from 'react-native-splash-screen';
import {MenuProvider} from 'react-native-popup-menu';
import {PersistQueryClientProvider} from '@tanstack/react-query-persist-client';
import {queryClient, queryPersister} from './src/utils/react-query';

const Envesto = () => {
  SplashScreen.hide();
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <PersistQueryClientProvider
          client={queryClient}
          persistOptions={queryPersister}>
          <MenuProvider>
            <NavigationContainer theme={theme} ref={navigationRef}>
              <StatusBar backgroundColor={'grey'} />
              <AppNavigator />
            </NavigationContainer>
          </MenuProvider>
        </PersistQueryClientProvider>
      </PersistGate>
    </Provider>
  );
};
export default Envesto;

```

**Comment by judicaelandria** [comment]
hey @uttu-316 what `@tanstack/react-query` version are you using? and can you please provide a working example, like on codesandbox or stackblitz?

**Comment by jseminck** [comment]
I am experiencing the same issue, using `PersistQueryClientProvider` but when running the app I get the error "https://github.com/TanStack/tanstack.com/issues/66"

The weird thing is, when I copy/paste the code from https://github.com/TanStack/query/blob/main/packages/react-query-persist-client/src/PersistQueryClientProvider.tsx into our project, and import that, then everything works.

Using version 4.22.4 for all dependencies.

**Comment by palfrey** [comment]
Seeing same bug with 4.29.15

**Comment by palfrey** [comment]
Seems to work fine in 5.7.0
