### ISSUE TITLE
Update NPM ( OLD )Package

### ISSUE THREAD

**Issue by carlosrziegler** [TanStack/query#4787]
### Describe the bug

I see that REACT QUERY package in NPM are in version 3.39.2. If I run `npm i react-query`I get old version instead a V4 of React Query.

Some way to redirect people to install new version ? 

Update some npm descriptions of @tanstack/react-query.

### Your minimal, reproducible example

https://www.npmjs.com/package/react-query

### Steps to reproduce

1: Go to https://www.npmjs.com/package/react-query
2: Install react-query with: npm i react-query

### Expected behavior

As developer I wnat to install last version of package

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="478" alt="image" src="https://user-images.githubusercontent.com/86771140/211479055-4a6950df-431d-4328-a515-d345e200d641.png">

<img width="260" alt="image" src="https://user-images.githubusercontent.com/86771140/211479088-06d61a09-ccf1-40e4-b849-5f9845009c0a.png">

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/86771140/211479131-fb26e043-6bff-403d-8063-6569e93315aa.png">

<img width="1573" alt="image" src="https://user-images.githubusercontent.com/86771140/211479298-9fb9d3a0-f5b4-475e-b002-4d903cdd9ef0.png">

### Platform

- OS: OSx 
- Browser: Chrome

### TanStack Query version

3.39.2

### TypeScript version

4.5.4

### Additional context

I think it is good to update because some people get react-query direct from NPM.

**Comment by daominh** [comment]
Unfortunately, the [react/query](https://www.npmjs.com/package/react-query) can point to v3 only. The only way to use v4 is installing from [@tanstack/react-query](https://www.npmjs.com/package/@tanstack/react-query). For which, if you're already using v3 in your project, you have to go through refactoring to replace _react/query_ with _@tanstack/react-query_

**Comment by TkDodo** [comment]
It's done: https://www.npmjs.com/package/react-query
