### ISSUE TITLE
`@tanstack/react-query` doesn't work on iOS 13

### ISSUE THREAD

**Issue by ynifamily3** [TanStack/query#4796]
### Describe the bug

Tanstack Query v4 doesn't work on iOS 13,

According to the documentation, it is said to be supported starting with the iOS 12 version, but in reality it is not the same at all.
<https://tanstack.com/query/v4/docs/react/installation#requirements>

The example on the official website also doesn't run at all. There is not even an error in the console.
<https://tanstack.com/query/v4/docs/react/examples/react/simple>
<img width="393" alt="image" src="https://user-images.githubusercontent.com/13795765/211777808-2183dc37-144d-49aa-9076-75fd8223dfa3.png">

### Your minimal, reproducible example

https://codesandbox.io/s/github/tanstack/query/tree/main/examples/react/simple?from-embed

### Steps to reproduce

1. on iOS 13 device safari, any feature doesn't work

### Expected behavior

Normal operation

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="393" alt="image" src="https://user-images.githubusercontent.com/13795765/211777808-2183dc37-144d-49aa-9076-75fd8223dfa3.png">

### Platform

OS: iOS 13 
browser: safari 
Version: 13.7

### TanStack Query version

v4.20.4

### TypeScript version

v4.9.4

**Comment by TkDodo** [comment]
I'm on iOS 16 and things work fine.

one thing I could imagine is that `navigator.onLine` somehow returns `false`, making react-query think it's offline. You could check by inspecting the `fetchStatus` variable (fork the sandbox and print it on screen next to the `loading...` text).

if that says `'paused'`, that would explain it.

**Comment by ynifamily3** [comment]
Thanks, It doesn't seem to reproduce the issue anymore, so I'm quitting for now.

**Comment by tiye** [comment]
> one thing I could imagine is that navigator.onLine somehow returns false, making react-query think it's offline. You could check by inspecting the fetchStatus variable (fork the sandbox and print it on screen next to the loading... text).

also encountered 3 cases on Chrome Desktop returns `navigator.onLine` `false` 😅  . One of them:

macOS version:

![image](https://user-images.githubusercontent.com/449224/226541730-e26a07b4-0e04-4343-a3d1-e995c2ee0550.png)

Chrome version:

![image](https://user-images.githubusercontent.com/449224/226541754-b83aacad-1940-4323-a52e-9b49f8762163.png)
