### ISSUE TITLE
PersistQueryClientProvider duplicates persisted mutations on page refresh

### ISSUE THREAD

**Issue by whanso** [TanStack/query#4846]
### Describe the bug

Hi there,

I created an application to test the persistQueryClient plugin's ability to predictably resume mutations and I am running into issues.

The app is Vite React, using workbox to set up a service worker with network-first caching.  When I toggle the browser offline, I can record events and watch them gather in the persister (in this case, LocalStorage).  Upon refreshing the page, however, the mutations double in size.  Every refresh I give it, the dehydrated mutations that were persisted gets doubled.

This is happening likely because my my service worker is able to support rendering the app while the browser is still offline; the PersistQueryClientProvider attempts to resume the mutations, realizes the app is still offline, and dehydrates the mutations again into persisted storage (thereby creating the doubling observation).  This to me is not expected, and I hope my conclusion on the "why" isn't a red herring. 

I tried poking around the APIs in the plugin to see if I can hook into the restore/save functions, but I haven't had any success.

## !!!READ Before running sandbox!!!:
The start script spins up a json-server as a mock backend alongside the Vite React app, and stackblitz points the URL to it instead of the application on startup. **For the preview window**, you will need to change the URL to the port the app is hosted at: **https://vitejsvite3mlpp8-20ms--5173.local-credentialless.webcontainer.io/** (or similar)

Video on how to navigate to site when sandbox runs:

https://user-images.githubusercontent.com/26184716/213866936-6163a9f9-8db7-4912-908e-f5f8db317db1.mov

Sandbox URL: https://stackblitz.com/edit/vitejs-vite-3mlpp8

### Steps to reproduce

1. Navigate to the stackblitz.  
2. With the rendered application open in a new tab (port for the window should be ~5173), toggle the application Offline.
3. Click on either button in the UI to record an event. 
4. Confirm the offline cache in LocalStorage contains an entry for the mutation.
5. Refresh the page.
6. Observe the offline cache in LocalStorage.  The mutations should increase to two.  
7. Each refresh will double the mutations. 2, 4, 8, etc.

### Expected behavior

I don't expect the persisted entries to double on page refresh while the app is supported in offline mode.  The persistQueryClient plugin should be able to safely save/restore when, on page reload, the client attempts to resume paused mutations.

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/26184716/213841241-89e6f998-cc43-444b-8318-82a2caaff657.mov

### Platform

macOS, Chrome 108.0.5359.124

### TanStack Query version

4.22.0

**Comment by TkDodo** [comment]
> the PersistQueryClientProvider attempts to resume the mutations, realizes the app is still offline, and dehydrates the mutations again into persisted storage (thereby creating the doubling observation). 

Hmm, I thought that this might be true, but then again, calling `resumePausedMutations()` shouldn't _create_ a new mutation. We take what is in the mutationCache and resume it. It will stay in paused state though when you are still offline, so the `resumePausedMutations` will never resolve. I think we should attempt to continue if we are still offline, but still, it doesn't explain the behaviour.

I can't execute the sandbox. All I'm seeing is an empty object printed and a 404 request. I tried various browsers.

<img width="1494" alt="Screenshot 2023-01-21 at 08 33 37" src="https://user-images.githubusercontent.com/1021430/213849116-4263667f-7f38-4954-938d-d5aa0b50a288.png">

Would be nice to be able to debug this.

**Comment by whanso** [comment]
@TkDodo 
>  I can't execute the sandbox. All I'm seeing is an empty object printed and a 404 request. I tried various browsers.
> 
> Would be nice to be able to debug this.

Hi there, the start script spins up a json-server to use as a mock backend alongside the Vite React app, and stackblitz points the URL to it instead of the application on startup.  You will need to change the URL in the preview window from https://vitejsvite3mlpp8-20ms--3004.local-credentialless.webcontainer.io to **https://vitejsvite3mlpp8-20ms--5173.local-credentialless.webcontainer.io**, which sets the correct port number the app is hosted at.  This is in the reproduce steps - apologies for the slowdown.

https://user-images.githubusercontent.com/26184716/213866702-6b3e5a54-feca-491b-b777-335424d4e096.mov

> calling resumePausedMutations() shouldn't create a new mutation.
Commenting out resumePausedMutations in the OnSuccess callback does not stop the behavior.

> I think we should attempt to continue if we are still offline, but still, it doesn't explain the behaviour.
I agree.

**Comment by TkDodo** [comment]
okay found it, a classic react18 StrictMode / StrictEffect useEffect gotcha. restore from hydration is called twice because we run it in a `useEffect` 🙄 . That's why duplicate mutations turn up in the cache. mutations can't be deduped like queries (where we only take the one with the latest timestamp no matter how often you call hydrate).

Not sure there is something we can / should do here ?

**Comment by whanso** [comment]
@TkDodo I found that just earlier, thanks so much for the quick response!  I would not recommend a solution based off of that.
