### ISSUE TITLE
Update version 3 documentation example links

### ISSUE THREAD

**Issue by louis-young** [TanStack/query#4860]
The example links in the version 3 documentation are broken. They appear to be missing the React adapter URL segment. 

This issue is derived from https://github.com/TanStack/query/discussions/4857#discussion-4784273

**Comment by TkDodo** [comment]
duplicate:
- https://github.com/TanStack/query/issues/4108

**Comment by TkDodo** [comment]
It's actually fixed in the code, but not deployed. I don't know how to deploy for v3. I'll sync with Tanner.

**Comment by louis-young** [comment]
Sorry 🤦‍♂️ I tried searching for a duplicate but evidently not well enough. Nice one, thanks :rocket:
