### ISSUE TITLE
eslint-plugin-query: add support for queryKeyFactories

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#4862]
@Newbie012 I think this is still not supported, right?

```
const fooQueryKeyFactory = {
    foo: () => ['foo'] as const,
    num: (num: number) => [...fooQueryKeyFactory.foo(), num] as const,
}

const useFoo = (num: number) =>
    useQuery({
        queryKey: fooQueryKeyFactory.foo(),
        queryFn: () => Promise.resolve(num),
    })
```

Here, I would expect an error because we're using `num` in the `queryFn`, but not in the `queryKey`. The fix would be:

```diff
- queryKey: fooQueryKeyFactory.foo(),
+ queryKey: fooQueryKeyFactory.num(num)
```

This doesn't have to auto-fix (because I think it's impossible), but I think it should error when we're not using `num` to produce the queryKey. Do you think that's possible ?

**Comment by Newbie012** [comment]
Correct, it seems like query key factories aren't supported yet, but I can start working on it if you want. It shouldn't be complicated.

https://github.com/TanStack/query/blob/main/packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.rule.ts#L72-L75

Although, I have to ask - what's the added value of separating the `queryKey` from `queryFn`? It might be a bit off-topic, but it reminds me back in the old days when there were no components in AngularJS, so each time we want to define a page or modal, we had to pass both `templateUrl` (html) and `controller` (js), until the Angular team introduced components.

**Comment by TkDodo** [comment]
> Although, I have to ask - what's the added value of separating the queryKey from queryFn?

Yeah, I tend to agree. Query Keys and Query Functions are a pair that should go together. I will try to move away from "query key factories" towards "query factories". However, one advantage is that type inference of the queryFn works better when you inline it, like:

```
const fooQueryKeyFactory = {
    foo: () => ['foo'] as const,
    num: (num: number) => [...fooQueryKeyFactory.foo(), num] as const,
}

const useFoo = (num: number) =>
    useQuery({
        queryKey: fooQueryKeyFactory.foo(num),
        queryFn: ({ queryKey, signal }) => Promise.resolve(queryKey[1]),
//                  ⬆️ inferred                            ⬆️ type safe
    })
```

if you extract `queryKey` and `queryFn` to a factory, you have to type annotate:

```
const fooQueryFactory = {
    foo: () => ['foo'] as const,
    num: (num: number) => ({
        queryKey: [...fooQueryKeyFactory.foo(), num] as const,
        queryFn: ({ signal }: QueryFunctionContext) => ...
//                            ⬆️ needs manual annotation
    })
}
```

and then again, you'd need to pass a generic to `QueryFunctionContext` if you'd want the `queryKey` passed to it to be properly inferred ...

**Comment by Newbie012** [comment]
It's funny that I stumbled across this exact issue, so I wrote this utility function (mostly copied for the source code):

```ts
function createQuery<
  TQueryFnData = unknown,
  TError = unknown,
  TData = TQueryFnData,
  TQueryKey extends QueryKey = QueryKey
>(
  options: Omit<UseQueryOptions<TQueryFnData, TError, TData, TQueryKey>, "initialData"> & {
    initialData?: () => undefined;
  }
) {
  return options;
}
```

This allows me to define inferred + type safe queries as follows:

![image](https://user-images.githubusercontent.com/10504365/214537076-8473e30e-1073-4891-baed-b57f38956d53.png)
 
As a plus, I can write a function `updateOptimisitically` which takes a query factory and update it type safely:

![image](https://user-images.githubusercontent.com/10504365/214538609-31fb8284-db1c-49d8-94dc-7e861b6e991c.png)

In any case, I understand that a lot of the community now is using query key factories, so I hope I'll have enough time today to raise a PR 🙂

**Comment by TkDodo** [comment]
Cool! Maybe we should ship this function out of the box 🤔

**Comment by Newbie012** [comment]
Which one?

Back to the original issue - I raised a [PR](https://github.com/TanStack/query/pull/4879)

**Comment by TkDodo** [comment]
> Which one?

the `createQuery` one :)
