### ISSUE TITLE
Queries are persisted with cacheTime of 0

### ISSUE THREAD

**Issue by ianschmitz** [TanStack/query#4887]
### Describe the bug

`cacheTime` and `queryKey` don't seem to behave how i would expect when using a persister.

### Your minimal, reproducible example

https://codesandbox.io/s/persister-cachetime-55qnu4?file=/src/index.jsx:1108-1561

### Steps to reproduce

1. Open codesandbox link
2. Read `BUG:` comments in `useQuery` hook options
3. Refresh page repeatedly using the refresh button in the browser preview
    - Note that the even though we've specified `cacheTime: 0` that the resolved value is persisted and used in the new page render
    - Note that changing `queryKey` value will persist the previous value indefinitely. This creates cache bloat - it's effectively creating a memory leak as these values will continue to be deserialized on subsequent application loads

### Expected behavior

- `cacheTime: 0` does not serialize the values into persisted storage. 
- Queries that specify `cacheTime: 0` do not use cached values in subsequent unmounts/mounts

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Chrome 109.0.5414.119

### TanStack Query version

4.23.0

**Comment by TkDodo** [comment]
> // BUG: I would not expect this to be stored in persistant cache.

I think you're misunderstanding what `cacheTime` is for, which is one of the reasons why we will rename it in the next major version to `gcTime`. As long as your query is actively used, we will not remove it. with `cacheTime: 0`, the query will be removed from the cache as soon as it gets unused, which, in your example app, doesn't happen at all.

// BUG: Try changing this cache key and watch the old
// cached query persist indefinitely.

Yeah I think this _is_ a bug. I've looked in the code and we only ever trigger a garbage-collection for a query if the last observer has been removed. We need to find a better way to do this for queries that have been put into the cache via hydration 🤔

**Comment by TkDodo** [comment]
I think if we would just call `scheduleGc()` in the constructor of the Query, this would be fixed. In case we have observers, this doesn't do anything, but it would make sure that queries that are created and never fetch will be removed in due time

**Comment by ianschmitz** [comment]
> I think you're misunderstanding what cacheTime is for, which is one of the reasons why we will rename it in the next major version to gcTime

I’ll admit that it definitely has confused me a number of times and I often go back to your blog post to clear it up. However in this case I think where I see it as a bug is as a consumer the persister is effectively a cache in my eyes, so when we say ‘cacheTime: 0’ my expectation is this wouldn’t be persisted in a cache.

**Comment by TkDodo** [comment]
you can exclude queries that have no cacheTime by filtering them out when dehydrating:

```
<PersistQueryClientProvider
  client={queryClient}
  persistOptions={{
    persister,
    dehydrateOptions: {
      shouldDehydrateQuery: (query) => !!query.options.cacheTime,
    },
  }}
>
```

if we fix the second bug, what will happen if you don't do this is:
- the query will be persisted
- when the query is restored and there are no observers, it will be removed instantly. This implies that you somehow have a global cacheTime of `0` set because without that, the defaults of 15 minutes would be taken because query options are not persisted - just data.
```

**Comment by ianschmitz** [comment]
@TkDodo just to follow up: i integrated your fix into my local and it does indeed seem to clear up the stale queries not being gc'ed in the persisted cache. Thanks for this!  🎉 

I also tried your `shouldDehydrateQuery` suggestion and it _mostly_ works, but sometimes i was still seeing it serialized. The reason was `query.options.cacheTime` would be equal to the default cache time specified at the client level instead of `0`. It's incredibly hard to reproduce though so i haven't been able to file a bug. Seems like some sort of race condition.
