### ISSUE TITLE
eslint-plugin-query: options passed as variable removed by autofix

### ISSUE THREAD

**Issue by henribru** [TanStack/query#4889]
### Describe the bug

If you pass option to `useQuery` as a variable instead of a literal, the ESLint plugin removes it

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-wa33s3?file=src%2Fmain.ts&terminal=dev

### Steps to reproduce

1. Press ctrl-c to exit the vite dev server
2. Run `npx eslint src/main.ts --fix`
3. Observe that `useQuery(['foo'], () => undefined, options)` turned into `useQuery({ queryKey: ['foo'], queryFn: () => undefined })`

### Expected behavior

I expected `useQuery({ queryKey: ['foo'], queryFn: () => undefined, ...options })`, or that it didn't autofix at all and left it for the user to fix.

### How often does this bug happen?

Every time

### Platform

- Linux
- Firefox
- 109.0

### TanStack Query version

v4.21.0 of @tanstack/eslint-plugin-query

**Comment by TkDodo** [comment]
hmm not sure why but it doesn't auto fix anything for me in that stackblitz:

```
❯ npx eslint src/main.ts --fix

/home/projects/vitejs-vite-wa33s3/src/main.ts
  12:5  error  Objects syntax for query is preferred  @tanstack/query/prefer-query-object-syntax

✖ 1 problem (1 error, 0 warnings)
```

**Comment by henribru** [comment]
@TkDodo Oh crap, I accidentally overwrote my reproduction. Fixed

**Comment by TkDodo** [comment]
confirmed. @Newbie012 please 🙏

**Comment by Newbie012** [comment]
Sorry... totally missed that issue

Raised a fix here - https://github.com/TanStack/query/pull/4932
