### ISSUE TITLE
`refetch()` does not update component state in Jest tests

### ISSUE THREAD

**Issue by ericbiewener** [TanStack/query#4892]
### Describe the bug

- Calling `useQuery`'s `refetch` function does update the component's state in Jest tests
- In fact, calling it immediately in a `useEffect` hook with an enabled `useQuery` invocation will _prevent_ the query from the `useQuery` invocation from every propagating its state to the component.
- None of this occurs in the browser.

### Your minimal, reproducible example

https://codesandbox.io/s/react-query-refetch-fetchingstatus-bug-react-17-36n01z?file=/src/refetch.tsx

### Steps to reproduce

The provided codesandbox link has both tests and their equivalent browser examples for comparison.

### Expected behavior

I would expect the tests to function the same as in the browser environment.

### How often does this bug happen?

None

### Platform

- OS: Mac OS
- Browser: Chrome 109.0.5414.87

### TanStack Query version

4.16.1

### TypeScript version

4.4.2

### Additional context

**Other package versions:**
- React@17.0.2
- @testing-library/react@12.1.5

**Additional debugging info**
When debugging this locally in the RQ source code, I found that [this line](https://github.com/TanStack/query/blob/9c15b327df35d7676e3fc768e7a4b753d7098af9/packages/react-query/src/useBaseQuery.ts#L75) produced the _previous_ version of the query state, while [this line](https://github.com/TanStack/query/blob/9c15b327df35d7676e3fc768e7a4b753d7098af9/packages/react-query/src/useBaseQuery.ts#L77) (if you saved its return value to a variable) returned the new, expected value. However, `useBaseQuery` returns the former, older value. Sure enough, modifying the source code to return the value from `useSyncExternalStore` fixed the test I was working on. I assume returning the value from `observer.getOptimisticResult()` is intentional, but I was surprised to see that differ from `useMutation`, [which _does_ return the value from `useSyncExternalStore()`](https://github.com/TanStack/query/blob/9c15b327df35d7676e3fc768e7a4b753d7098af9/packages/react-query/src/useMutation.ts#L95).

Not sure if the RQ team considers this a bug since it doesn't impact the browser, but I figured I'd submit it as a bug report since I am using an ecosystem-standard testing setup that is surely used by the vast majority of your user base.

**Comment by TkDodo** [comment]
hmm, I've taken your first failing test and re-written to it the style we usually write our tests, and with that, it works fine 🤔 

```
it('should render correctly with useQuery when refetching', async () => {
    const results: UseQueryResult[] = []

    const Page = () => {
      const result = useQuery({
        queryKey: ['foo'],
        queryFn: () => Promise.resolve('foo'),
      })

      results.push(result)

      const refetch = result.refetch

      React.useEffect(() => {
        console.info(`::`, 'refetching')
        refetch()
      }, [refetch])

      return (
        <div>
          data: {result.data}, status: {result.status}
        </div>
      )
    }

    const rendered = renderWithClient(queryClient, <Page />)

    await waitFor(() => rendered.getByText('data: foo, status: success'))

    await waitFor(() => {
      expect(results.length).toBeGreaterThan(1)
    })
  })
```

I thought this might be an issue with property tracking because we don't use anything from the returned values except for `refetch`, so it never re-renders. But I set `notifyOnChangeProps: undefined` and it still didn't work. It's weird because as soon as I change the return statement to `return null`, the test fails 🤔

**Comment by TkDodo** [comment]
but then again, if you are rendering `null`, thus having an observer that doesn't observe anything - why does it matter how often the query renders?

I'd say this is a non-issue if you write your tests the way you write your app, which is always a good thing to do :)
