### ISSUE TITLE
V2 

### ISSUE THREAD

**Issue by zhang2118** [TanStack/query#4919]
### Describe the bug

The V2 doc link is returning 404 error. 
https://react-query-v2.tanstack.com/. 

### Your minimal, reproducible example

N/A

### Steps to reproduce

1. Go to https://react-query-v2.tanstack.com/. 
2. See 404 error

### Expected behavior

I'd expect to see the V2 doc

### How often does this bug happen?

Every time

### Platform

- OS: Mac OS
- Browser: Chrome

### TanStack Query version

V2

**Comment by TkDodo** [comment]
We've had enough troubles keeping the v3 docs up. Please treat v2 as unmaintained and upgrade.

Source for the docs is here: https://github.com/TanStack/query/tree/2.x/docs/src/pages/docs
