### ISSUE TITLE
[isFetching] not any newwork request happen,but isFetching changed and endpoint is  true

### ISSUE THREAD

**Issue by Valar103769** [TanStack/query#4928]
### Describe the bug

```jsx
  const {
    isFetching,
    data: res,
    isLoading,
    refetch,
  } = useQuery(
    ['/report_data/table', fetchDataOptions],
    () => axios.post('/report_data/table', { ...fetchDataOptions }),
    {
      keepPreviousData: true,
      enabled: gridReady,
    }
  )

const [state,setState] = useState()
console.log('isFetching',isFetching)
 //  false 
// true 

<button onClick={()=> setState()}>setState</button>
```

### Your minimal, reproducible example

https://snack.expo.dev/

### Steps to reproduce

queryKey is not changed, but isFetching state is changed

### Expected behavior

isFetching is changed to true 

### How often does this bug happen?

None

### Screenshots or Videos

isFetching is false 

### Platform

mac os 
chrome

### TanStack Query version

^4.19.1

**Comment by TkDodo** [comment]
> Your minimal, reproducible example

This doesn't link anywhere and I don't understand the description. Please reopen once you have a reproduction
