### ISSUE TITLE
eslint-plugin-query: mutation function is turned into mutation key

### ISSUE THREAD

**Issue by henribru** [TanStack/query#4938]
### Describe the bug

The ESLint plugin is turning the mutation function into the mutation key

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-6buzvj?file=src%2Fmain.ts&terminal=dev

### Steps to reproduce

1. Press ctrl-c to exit the vite dev server
2. Run `npx eslint src/main.ts --fix`
3. Observe that `useMutation(() => Promise.resolve(3));` turned into `useMutation({ mutationKey: () => Promise.resolve(3) });`

### Expected behavior

I expected `useMutation({ mutationFn: () => Promise.resolve(3) });`

### How often does this bug happen?

Every time

### Platform

- Linux
- Firefox
- 109.0

### TanStack Query version

v4.24.5 of @tanstack/eslint-plugin-query

**Comment by TkDodo** [comment]
@Newbie012 can you take a look?

**Comment by Newbie012** [comment]
Raised a PR [here](https://github.com/TanStack/query/pull/4973)

**Comment by henribru** [comment]
@Newbie012 Thanks for the fix. Unfortunately while the case in my reproduction no longer occurs, it still happens if you include an options object, see https://stackblitz.com/edit/vitejs-vite-q9jvoz?file=src%2Fmain.ts&terminal=dev

**Comment by Newbie012** [comment]
@henribru it should be fixed once https://github.com/TanStack/query/pull/4986 will be merged and released.
