### ISSUE TITLE
useQueries queries array

### ISSUE THREAD

**Issue by Enas-Sello** [TanStack/query#4952]
### Describe the bug

when i use the docs as a reference
i got "queries.map is not a function"

i solved it by padding the queries array directly as the useQueries argument like this ⬇️
![image](https://user-images.githubusercontent.com/94912513/217546938-e5dbc83c-7107-4420-896d-76446b08261d.png)

### Your minimal, reproducible example

.

### Steps to reproduce

.

### Expected behavior

.

### How often does this bug happen?

None

### Platform

win

### TanStack Query version

latest

### TypeScript version

latest

**Comment by DamianOsipiuk** [comment]
Please double check in your `package.json` which version you have installed.
For latest version (v4) you should install `@tanstack/react-query`, not `react-query`

**Comment by saver711** [comment]
@DamianOsipiuk 
What are the differences?

**Comment by DamianOsipiuk** [comment]
@saver711 
`react-query` was migrated to `@tanstack/react-query` and only the new package receives updates. Old one might only receive security updates.

`react-query` have older version of the API, so you might want to reference different version of the docs if you cannot migrate: https://tanstack.com/query/v3/docs/react/overview
