### ISSUE TITLE
Memory leak in vue-query SSR

### ISSUE THREAD

**Issue by schneefux** [TanStack/query#4953]
### Describe the bug

In SSR, Vue will never do `app.unmount()`, so the query client never unmounts and cannot be garbage collected

### Your minimal, reproducible example

https://github.com/schneefux/vue-query-memory-leak-reproduction

### Steps to reproduce

```bash
npm install
npm run build
npm run start
while true; do curl -s localhost:3000 -o /dev/null; done
```

Perform a heap dump, for example in Chrome like this:
* Open Chrome's dev tools
* Click the NodeJS icon 
* Click the Memory tab
* Click the trash icon to force garbage collection
* Click "Take Snapshot"

In the heap dump, open the Summary, set the class filter to `QueryClient`, observe that there are hundreds/thousands of query clients.

### Expected behavior

vue-query should use a different method to unmount during SSR or the SSR docs should explicitly state that you have to call `queryClient.unmount()` after a request

### Platform

Reproduced on macOS and Linux with Nuxt and without a framework (as per https://vuejs.org/guide/scaling-up/ssr.html#rendering-an-app)

### TanStack Query version

4.24.4

### Additional Context

Related Vue discussions and issues:
* https://github.com/vuejs/core/discussions/5945
* https://github.com/intlify/vue-i18n-next/issues/920
* https://github.com/vuejs/core/issues/2907#issuecomment-1280010611

**Comment by DamianOsipiuk** [comment]
@schneefux Could you please check if https://github.com/TanStack/query/releases/tag/v4.24.10 fixes your issue?

**Comment by schneefux** [comment]
Thank you, I have been running this in production for a while and have not seen any memory leaks since.
