### ISSUE TITLE
eslint-plugin-query: @tanstack/query/exhaustive-deps is not applied for setQueryData()

### ISSUE THREAD

**Issue by fmacherey** [TanStack/query#4959]
### Describe the bug

We are using react-query to cache the locale for our product (derived from the hostname).

I enabled the eslint plugin with recommended rules as listed in the docs.https://tanstack.com/query/v4/docs/react/eslint/eslint-plugin-query#recommended-config 

I had as mismatched dependency of variables, which are missing in the cacheKey (`host` is missing):
```
export const useCountry = (): CountryType => {
    const queryData = useQuery<CountryType>({
        queryKey: [QUERY_NAME_COUNTRY],
        queryFn: () => getCountryFromHostname(host)
        staleTime: Infinity,
    });
    return queryData.data ?? getCountryFromHostname(host);
};
```

We also setting this information on our _app-Page (we are using nextjs) 
```
queryClient.setQueryDefaults([QUERY_NAME_COUNTRY, host], {
    staleTime: Infinity,
});
queryClient.setQueryData([QUERY_NAME_COUNTRY], () =>
    getCountryFromHostname(host)
);
```

But this use didn't note me the eslint error. I think this should also apply to this methods. Even though its not a useQuery hook, it otherwise prevents from unnecessary refetching.

### Your minimal, reproducible example

not needed i guess

### Steps to reproduce

see above

### Expected behavior

eslint plugin should also apply for `setQueryData`

### How often does this bug happen?

Every time

### Platform

- macOS 13.2
- node v18.12.1

### TanStack Query version

4.24.5

### TypeScript version

4.9.5

**Comment by TkDodo** [comment]
sorry, this is not intended. `setQueryData` just writes data to the cache, and is only invoked once when running. It doesn't matter here what you "use" inside the updater function, as there is no correlation to the key.
