### ISSUE TITLE
Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by mdeoliveira-hw** [TanStack/query#4966]
### Describe the bug

I have a project that consist in multiple packages :

- a library who export some react-query hooks that define `@tanstack/react-query` as `peerDependency`
- a React app, build with `create-react-app` that use the library to fetch data.

Both package, used the same version of `react` and `@tanstack/react-query`.

![Capture d’écran 2023-02-10 à 16 56 26](https://user-images.githubusercontent.com/112888359/218136822-3b9d4b6d-85f0-44a3-b639-5f3c6885efc8.png)

If we try to use the hooks define in the library from the react app, we got the following error :

![Capture d’écran 2023-02-10 à 16 35 47](https://user-images.githubusercontent.com/112888359/218131849-3007df82-ed1c-47ea-ad4a-8e6e9c318d78.png)

### Your minimal, reproducible example

- https://github.com/mdeoliveira-hw/react-query-queryclient-issue
- https://github.com/mdeoliveira-hw/react-query-queryclient-issue-lib (lib that export custom hooks)

### Steps to reproduce

```bash
yarn 
yarn start
```

### Expected behavior

We should be able to use the `queryClient` in both sides (app + lib).

### How often does this bug happen?

Every time

### Platform

- OS : macOS
- Browser : Chrome 110.0.5481.77 (Build officiel) (arm64)

### TanStack Query version

4.24.4

### TypeScript version

4.9.5

**Comment by zhengjitf** [comment]
In my understanding, the lib pkg shouldn't install react-query as devDep, otherwise your two repos actually import different path react-query. You need adjust development mode for lib pkg. Or an another unrecommended solution is that set contextSharing to QueryClientProvider, it might work but marked as deprecated.

**Comment by sergiidiak** [comment]
This is most likely CSJ vs ESM issue. If the hook can't find context, even though you have it in your app, either your library pulls CJS version of react-qeury or your app pulls CJS version of your library, but the library pulls ESM of react-query

**Comment by sergiidiak** [comment]
From your example repro example. Your library is built with commonjs module type, but app is using ESM. Try changing 'module' to 'es2020' in your lib tsconfig.json

**Comment by mdeoliveira-hw** [comment]
Thank you @sergiidiak for your quick response, that solved the problem
