### ISSUE TITLE
windowSize for useInfiniteQuery

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#4975]
as discussed on [twitter](https://twitter.com/ArnBZN/status/1624732689227030531), as a potentially different api to replace `refetchPages`.

@arnaudbzn

**Comment by arnaudbzn** [comment]
### Overview
`useInfiniteQuery` supports a new `windowSize` option.
`windowSize` defines the number of pages to store in the query data.

The objective is to keep only a "window" of pages in memory and fetch pages outside this window when needed (bi-directional).

Example: 
An infinite scroll that can generate +50 pages: Refetching to whole list will sequentially trigger 50 network calls. 
By setting `windowSize` to 5, only 5 pages are refetched and kept in memory. 
Moving outside the window (both directions are supported) will remove a page from the memory to keep the number of pages fixed and the new page is fetched as usual and added to the end or the start of the pages array according to the direction.

### Functional specs
`windowSize` has no effect if its value is `undefined` or equals `0`

When the total number of pages is lower than `windowSize` the behavior is the same as without `windowSize`

When number of pages is equal to `windowSize` a call to:
- `fetchNextPage` will remove the first page and add a new page at the end of the pages array. 
- `fetchPreviousPage` will remove the last page and insert a new page at the start of the pages array.

## Requirements
- the infinite list must be bi-directional: `getPreviousPageParam` must be defined

## Other DX impacts
The developer has to keep in mind that the number data pages is limited to the`windowSize` when using:
- `getQueryData` 
- `setQueryData` (e.g: Optimistic UI)
- `persistQueryClient`

### Implementation specs
In `infiniteQueryBehavior` class:
`buildNewPages` can be updated to use a new `LimitedLengthArray` util class (or a set of functions) to manage `newPageParams` and pages array by applying the window logic if needed.

**Comment by TkDodo** [comment]
sounds lovely ❤️ . Maybe we should discuss the name `windowSize`, I'm not sure it reflects what we're doing. With windowing, I would associate a perf optimization for rendering where we would only return the amount of requested pages to the user, but still cache them all.

But what we're actually doing is throwing away cached results, and I think we should make that clear. Something like `maxCacheSize` or `maxPages` / `maxCachedPages` maybe?

Another thing: Should we also stick to that maxSize when `setQueryData` is called with more than that? I don't think so as we wouldn't know which pages to discard. That means that it's possible to get more pages into the cache via `setQueryData`, but I guess that's fine...

**Comment by arnaudbzn** [comment]
Quick tests done with the suggested implementation look promising with only the following code changes to `buildNewPages`.
I can create a PR for this WIP or I can share it somewhere else so you can experience the prototype.
In the meatime a quick demo [here](https://www.loom.com/share/b51c2c15166c4e9f80b68249f53cd099) 
```ts
        const windowSize = 3
        const newPageParamsWindow = new LimitedLengthArray(windowSize, newPageParams)

        const buildNewPages = (
          pages: unknown[],
          param: unknown,
          page: unknown,
          previous?: boolean,
        ) => {
          const pagesWindow = new LimitedLengthArray(windowSize, pages)
          if(previous) {
            newPageParamsWindow.addItemToStart(param)
            pagesWindow.addItemToStart(page)
          } else {
            newPageParamsWindow.addItemToEnd(param)
            pagesWindow.addItemToEnd(page)
          }
          return pagesWindow.getItems()

          // OLD CODE
          // newPageParams = previous
          //   ? [param, ...newPageParams]
          //   : [...newPageParams, param]
          // return previous ? [page, ...pages] : [...pages, page]
        }
  ```

**Comment by arnaudbzn** [comment]
> But what we're actually doing is throwing away cached results, and I think we should make that clear. Something like maxCacheSize or maxPages / maxCachedPages maybe?

`maxPages` sounds great

> Another thing: Should we also stick to that maxSize when setQueryData is called with more than that? I don't think so as we wouldn't know which pages to discard. That means that it's possible to get more pages into the cache via setQueryData, but I guess that's fine...

Agreed, it should be fine.

**Comment by arnaudbzn** [comment]
Prototype EDIT
To support `refetch`, the following code should be added too in `buildNewPages`

```ts
        // Refetch pages
        else {
          newPageParams = []
          // NEW CODE
          newPageParamsWindow = new LimitedLengthArray(windowSize, newPageParams)
```

**Comment by arnaudbzn** [comment]
@TkDodo Preliminary testing of the prototype looks good. If you agree, I can prepare a PR including tests (I will do the docs later when the solution is validated and stabilized)

**Comment by TkDodo** [comment]
Just to be sure: please use the v5 branch as base

**Comment by ehtodd** [comment]
Is there a workaround for v4, where I could achieve the same thing as maxPages? Thanks a lot for all your work on this lib btw
