### ISSUE TITLE
Unexpected fetch behaviour on webkit when <select/> is used

### ISSUE THREAD

**Issue by palmerusaf** [TanStack/query#4980]
### Describe the bug

This may be more an issue with web-kit than useQuery.

When a <select/> tag is used in the same component as query.data it causes query to re-fetch data.

This happens specifically whenever the selector is clicked. 

It turns out that on web-kit fires a window blur event every time the selector is clicked. This causes useQuery's refetchOnWindowFocus to fire. I found a workaround is to set refetchOnWindowFocus to false.

### Your minimal, reproducible example

https://codesandbox.io/s/webkit-usequery-bug-i62mst?file=/src/App.js

### Steps to reproduce

1. Go to the [sandbox](https://codesandbox.io/s/webkit-usequery-bug-i62mst?file=/src/App.js) in a web-kit based browser
2. Open the console
3. click the drop down selector and you can see fetch being logged each time

### Expected behavior

Like I said earlier this is probably more an issue with web-kit. Re-fetching on window focus is documented and expected for useQuery. What's unexpected is re-fetching/re-rendering every time a <select/> tag is clicked.

### How often does this bug happen?

Every time

### Platform

- OS: Pop!_OS 22.04 LTS x86_64
- Browser: GNOME Web 43 WebKitGTK 2.38.1
- Version: 4.24.4

### TanStack Query version

4.24.4

**Comment by TkDodo** [comment]
We have already changed how the focusManager works for v5. It will only listen to the `visibilitychange` event to avoid thins like this.

For v4, you can set your own custom event handler:

https://tanstack.com/query/v4/docs/react/guides/window-focus-refetching#custom-window-focus-event
