### ISSUE TITLE
useMutation gets stuck loading if called from useEffect

### ISSUE THREAD

**Issue by navigator-dev** [TanStack/query#4983]
### Describe the bug

If I call `mutation.mutate()` within a `useEffect` hook (on mount) the `mutation.isLoading` will always be true even if the mutation has returned a result _or_ has errored.

I'm assuming this has to do with React 18 in strict mode.

Also it seems if I do a timeout within the `useEffect` then the loading state works as expected.

### Your minimal, reproducible example

https://codesandbox.io/s/keen-sanderson-ihh2vs?file=/src/App.js

### Steps to reproduce

Start a mutation from within a useEffect immediately on render.

### Expected behavior

I would expect that the mutation state gets updated according to the status of the mutation -- if the `onError` gets called then surely the mutation has finished and yet the `isLoading` field is always true.

### How often does this bug happen?

Every time

### Platform

OS: MacOS
Browser: Brave | Version 1.49.33 Chromium: 109.0.5414.87 (Official Build) nightly (x86_64)

### TanStack Query version

4.24.6

**Comment by TkDodo** [comment]
it's indeed related to strict effects, because if you remove `<StrictMode>`, it works fine. It also works fine if you remove the `ref` and just let it run twice.

Not really sure where the issue is tbh...

**Comment by navigator-dev** [comment]
> it's indeed related to strict effects, because if you remove `<StrictMode>`, it works fine. It also works fine if you remove the `ref` and just let it run twice.
> 
> Not really sure where the issue is tbh...

If the mutation is something that shouldn't be run twice then this is an issue, no? Is the "timeout" trick the best way to get around this other than turning off strict mode?

**Comment by TkDodo** [comment]
> If the mutation is something that shouldn't be run twice then this is an issue, no? 

only in dev mode for now. But if you don't want mutations to run more than once, don't put them in useEffect. React might run effects more often in future versions (like when parts of the ui goes offscreen and then comes back into the screen), so strict mode tries to prepare you for that.

mutations should usually be triggered in event handlers - they are side-effects of a user interaction, _not_ side effects of "rendering".

**Comment by navigator-dev** [comment]
In this case, running it multiple times _is fine_, I just do not want it to run multiple times _per mount_. If the component is mounted, unmounted, then mounted again due to page routing or something then I would actually _want_ it to run again.

Regardless, I moved the function call to a button so feel free to close the issue as it's not directly applicable to me anymore.

**Comment by Dremora** [comment]
> > If the mutation is something that shouldn't be run twice then this is an issue, no?
> 
> only in dev mode for now. But if you don't want mutations to run more than once, don't put them in useEffect. React might run effects more often in future versions (like when parts of the ui goes offscreen and then comes back into the screen), so strict mode tries to prepare you for that.
> 
> mutations should usually be triggered in event handlers - they are side-effects of a user interaction, _not_ side effects of "rendering".

I disagree with the above reasoning. I only want the query to run once on component mount, so, as per the StrictMode constraints, I've introduced a ref that makes sure that the query only runs once, regardless of how many times the effect was executed. The query now runs only once, as expected. However, something within react-query prevents it from working correctly in strict mode.

Note that I'm using version 3.39.1 and can't upgrade right now. Perhaps this has been fixed in later versions.
