### ISSUE TITLE
loop retry

### ISSUE THREAD

**Issue by vaynevayne** [TanStack/query#4988]
### Describe the bug

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/124666577/219259762-45063ae9-4538-4611-8b0e-83c11dbf7e81.png">

```js
axios.interceptors.response.use(
  function (response) {
    if ('statusText' in response) {
      return response.data
    } else {
      return response
    }
  },
  function (error: AxiosError) {

    if (error.response?.status === 401) {
      localStorage.removeItem('token')
      router.navigate('/login')
    }
    return Promise.reject(error)
  }
)


export const useGamesQuery = () =>
  useQuery(
    currentKey,
    () =>
      axios.get('/games/my').then(({ data }) => {
        return data
      }),
    {
      staleTime: Infinity,
    }
  )
```

<img width="1621" alt="image" src="https://user-images.githubusercontent.com/124666577/219259901-c3df906c-15ea-4472-924a-af5a4e2bdc3b.png">

```js
export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: false,
    },
  },
})

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <QueryClientProvider client={queryClient}>
    <App />
    <ReactQueryDevtools initialIsOpen={false} />
  </QueryClientProvider>
)
```

### Your minimal, reproducible example

i don't know how to reproduce

### Steps to reproduce

open the browser

### Expected behavior

once if 

### How often does this bug happen?

None

### Platform

macos chrome

### TanStack Query version

^4.19.1

**Comment by judicaelandria** [comment]
thanks for the feedback! but can you setup an example that reproduces this please? codesandbox or stackblitz

**Comment by vaynevayne** [comment]
> 

<img width="747" alt="image" src="https://user-images.githubusercontent.com/124666577/219280578-4d294fd4-26cc-4002-ba19-02b619de8324.png">

 don't let me repeat please

**Comment by judicaelandria** [comment]
I don't think this is react-query's doing. I can't tell much from a screenshot with partial code and a video ...
it looks like you're calling the query function directly in render and have an infinite render loop or so
cc @TkDodo

**Comment by TkDodo** [comment]
Don't let me repeat: We're not looking into bugs without a standalone, minimal, runnable reproduction. Feel free to re-open once you have that.
