### ISSUE TITLE
`onError` property doesn't exist on `QueryCache` (but does on `MutationCache`)

### ISSUE THREAD

**Issue by mkosir** [TanStack/query#4991]
### Describe the bug

When trying to access `onError` options property when instantiating new QueryCache, it doesn't exist, but at runtime it exists, from what I assume it's probably a type issue?
```ts
queryCache: new QueryCache({
    onError: (error, query) => {
      // @ts-expect-error Missing (type) property in react-query library.
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      const isCustomErrorDefined = query.options.onError;
      if (isCustomErrorDefined) {
        return;
      }

      errorHandler()(error);
    },
  }),
```
It is accessible when creating new `MutationCache`, from which I assume it should be the same/similar with `QueryCache`.

```ts
  mutationCache: new MutationCache({
    onError: (error, _variables, _context, mutation) => {
      const isCustomErrorDefined = mutation.options.onError;
      if (isCustomErrorDefined) {
        return;
      }

      errorHandler()(error);
    },
  }),
```

### Your minimal, reproducible example

https://codesandbox.io/s/nifty-yonath-mjfpkm?file=/src/index.jsx

### Steps to reproduce

Try to access `onError` property in your code editor, where it's non-existent (type `any`/not provided in intellisense).

### Expected behavior

`onError` should be accessible when creating new QueryCache.

### How often does this bug happen?

Every time

### Platform

OS: macOS
Browser: Chrome

### TanStack Query version

v4.24.6

### TypeScript version

v4.9.5

**Comment by TkDodo** [comment]
That's because a query doesn't have an `onError` or `onSuccess` callback, only an `Observer` does. This is also the reason why those callbacks are called multiple times if you have multiple observers.

**Comment by mkosir** [comment]
@TkDodo thanks for reply, and idea how could I implement the same functionality as in mutationCache, to "detect", if custom error was already defined?

**Comment by TkDodo** [comment]
since it's different use-cases it's not really possible

**Comment by TkDodo** [comment]
You can set `defaultOptions` that would then be overwritten by individual observers though
