### ISSUE TITLE
UseMutation Typescript errors unclear regardless of where you made one: mutationFn' does not exist in type 'readonly unknown[]

### ISSUE THREAD

**Issue by robinclaes** [TanStack/query#5008]
### Describe the bug

When making a typescript error in useMutation, the error is very vague/unclear 

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type .......... is not assignable to parameter of type 'MutationKey'.
      Object literal may only specify known properties, and 'mutationFn' does not exist in type 'readonly unknown[]'
```

In my example, I have made an error in the retry function. (returns a number instead of the expected boolean)
I would expect the TS error to show that an error was made in the return type of this retry function.
Currently, it's hard to know where the error manifests.

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-gk1zbh?file=src/App.tsx

### Steps to reproduce

1. Check the typescript error (I have returned a number from the delay function, this has to be a boolean)
2. Observe that the typescript error is unclear and does not refer to my error in the delay function

### Expected behavior

I expect the typescript error to complain about my `delay` function not having the correct return type.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/11699918/220059268-6f002e04-f992-4a3e-b169-2819f225ca90.png)

### Platform

OS: macOS 
Browser: n/a 
Version: n/a

### TanStack Query version

v4.24.9

### TypeScript version

v4.9.5

**Comment by TkDodo** [comment]
That's one of the drawbacks when using overloads, which we won't be doing anymore in v5. There, the error will be:

```
Type '(count: number, error: Error) => number' is not assignable to type 'RetryValue<Error> | undefined'.
  Type '(count: number, error: Error) => number' is not assignable to type 'ShouldRetryFunction<Error>'.
    Type 'number' is not assignable to type 'boolean'.ts(2322)
index.tsx(27, 12): Did you mean to call this expression?
```

and it shows directly at `retry`:

![Screenshot 2023-02-20 at 11 05 52](https://user-images.githubusercontent.com/1021430/220074967-0b7ed455-eb65-4580-8070-32022e305d1b.png)


Fork of your reproduction with a v5 preview build:

https://codesandbox.io/s/tanstack-query-example-react-basic-typescript-forked-ils78z?file=/src/index.tsx

**Comment by ivan3123708** [comment]
Is there any solution to this problem? It's been almost half a year and v5 isn't released yet, so how do we avoid this error in v4?
