### ISSUE TITLE
useQuery remove seems to cause an endless loop

### ISSUE THREAD

**Issue by MarByteBeep** [TanStack/query#5020]
### Describe the bug

Consider the following simple example in which I fetch data from a URL every two seconds:

```js
    const fetchData = async () => {
        console.info('fetching');
        const result = (await api.get(`/`)).data;
        return result.data;
    };

    useQuery(['mykey'], fetchData, {
        refetchInterval: 2000,
    });
```
This all works as expected. Every two seconds fetching is printed to the console.

However suppose I don't want to continue fetching this anymore. My thought was to use `useQuery.remove()` for that. The documentation on `remove` says the following:

`A function to remove the query from the cache.`

Perfect. So I modified the example above to the following:

```js
    const { remove } = useQuery(['mykey'], fetchData, {
        refetchInterval: 2000,
    });

    // ... do stuff and then remove the periodic fetch:
    remove();
```

However upon calling that `remove()`, suddenly `fetchData()` is called continuously and the console is flooded with the fetching message.

What am I doing wrong here? Or is this a bug?

### Your minimal, reproducible example

https://codesandbox.io/s/green-brook-y1t4uk

### Steps to reproduce

Run the following code

```js
	const fetchData = async () => {
		console.info('fetching ', `/courses/${props.courseId}`);
		const result = (await api.get(`/courses/${props.courseId}`)).data;
		return result.data;
	};

	const { remove } = useQuery('mykey', fetchData, {
		refetchInterval: 2000,
	});

	remove();
```

### Expected behavior

The query should be removed from the catch and refetching should stop, not end up in an infinite loop.

### How often does this bug happen?

Every time

### Platform

Windows 11, nodejs v18.14.0

### TanStack Query version

3.39.3

**Comment by TkDodo** [comment]
don't use remove on an active query. We'll remove the returned function in v5.

if you want to stop an interval, `refetchInterval` can take a function and you can return `false` from there to not refetch anymore.

**Comment by MarByteBeep** [comment]
Thanks! Although, This is a bit counter intuitive to me, I just want to get rid of the entry I added using `useQuery`. Setting enabled to false or changing the `refetchInterval`, feels like a workaround or a hack to me. In my code that query becomes useless, so I don't want it anymore. Isn't there a proper way to just undo the action I caused by calling `useQuery` in the first place?

**Comment by TkDodo** [comment]
what would you expect to happen if you remove a query that is rendered on the screen? It cannot be "useless" if your screen needs to show the data 😅

**Comment by MarByteBeep** [comment]
A little background on what I'm trying to do here. I'm using this mechanism to enable or disable a button. It polls the database for a change. Every two seconds. And calls `onSuccess`, which evaluates the data received from the database. In that function I determine whether or not the button should be disabled. If the button is disabled, it's disabled permanently. Forever. So at that point, there is no reason anymore to poll the database. Yes, I could set the `refetchInterval` to false. But, in this case I think it makes more sense to remove that polling query.

**Comment by TkDodo** [comment]
sounds like you're copying the value from the query somewhere else, maybe local state, in onSuccess? What I would do is something like:

```
const useIsButtonDisabled = () => {
  const { data } = useQuery(...)

  return computeDisabledFromData(data)
}

const disabled = useIsButtonDisabled()

<button disabled={disabled}>

```

then, just give that query a high staleTime and turn off the refetchInterval when you have the value you want. The query is still relevant because it's the source of your information. Anything else just overcomplicates it. Might not be relevant for you right now, but what if you unmount this component and come back to it? What if you use this query in a second component etc. With this, it just works ...

**Comment by MarByteBeep** [comment]
Thanks for this!
