### ISSUE TITLE
ESLint plugin does not work well with TypeScript `satisfies`

### ISSUE THREAD

**Issue by RomainLanz** [TanStack/query#5028]
### Describe the bug

Hey there! 👋🏻 

The ESLint rule `prefer-query-object-syntax` does not handle the case correctly when `satisfies` is used.

```ts
const queryDefinition = {
    queryKey: ['my-key'],
    queryFn: fetchSomething,
} satisfies UseQueryOptions<{ data: any }>;

function useSomething() {
    return useQuery(queryDefinition);
                    // 👆 Not Happy and make it { queryFn: queryDefinition } when fixing
}
```

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/withered-cookies-zogzv2

### Steps to reproduce

I tried to reproduce the issue in a Codesandbox, but it seems to not handle the `satisfies` keyword. Therefore, ESLint cannot have the error.

You can activate the rule and copy-paste the code shared above to give it a try.

### Expected behavior

ESLint should not catch this code as a mistake.

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- IDE: JetBrains PHP Storm

### TanStack Query version

4.24.6

### TypeScript version

4.9.5

**Comment by TkDodo** [comment]
just to be sure, can you check if the latest patch from yesterday fixes this?

**Comment by RomainLanz** [comment]
Hey @TkDodo! 👋🏻 

Thanks for the reply.
Yes, with the latest release (`4.24.11`) the issue still occurs.

**Comment by TkDodo** [comment]
Thanks. @Newbie012 fyi

**Comment by TkDodo** [comment]
I don't think we'll be investing into this, because the rule has been removed altogether in v5.

**Comment by Newbie012** [comment]
I totally forgot about this issue 😅
