### ISSUE TITLE
The queryClient is made reactive (!?) in the options causing severe performance issues in vue

### ISSUE THREAD

**Issue by simonwep** [TanStack/query#5031]
### Describe the bug

Hey! We make extensive use of the query client by, for example, using a query in a table to resolve a value for each cell. We also initialize our own instance of `QueryClient` and pass it as option to each `useXXX`-call like so:

```ts
const queryClient = new QueryClient({ ... });
const query = useQuery(..., ..., {
    queryClient,
});
```

We have to do this since we use the query-client outside of vue component-instances and, as of right now, the query client is by default [injected](https://github.com/TanStack/query/blob/8b51e8b690f68190c06c865a84fb6a22c5c29d34/packages/vue-query/src/useQueryClient.ts#L14) which would throw an error in this instance.

For some reason the queryClient seems to be made reactive as this causes severe performance issues in our case since vue traverses the whole client for reactive changes on _every change_.

### Your minimal, reproducible example

See below

### Steps to reproduce

I unfortunately couldn't manage to reproduce it as this seems to only happen if there is _lots_ of data so please bear with me. I seem to have found out what _might_ cause performance issues with the new option of passing the `queryClient` to, for example, `useQuery`:

All arguments passed to `useQuery` (and other utility functions) are [wrapped in a computed](https://github.com/TanStack/query/blob/8b51e8b690f68190c06c865a84fb6a22c5c29d34/packages/vue-query/src/useBaseQuery.ts#L57), [cloned](https://github.com/TanStack/query/blob/8b51e8b690f68190c06c865a84fb6a22c5c29d34/packages/vue-query/src/useBaseQuery.ts#L172) and [refs unwrapped](https://github.com/TanStack/query/blob/8b51e8b690f68190c06c865a84fb6a22c5c29d34/packages/vue-query/src/utils.ts#L59). This **includes** the `queryClient` we pass as option as well. Now, the query client is rather large and, I'm not sure, may contain many reactive values / data-structures which are cloned _every time_ they change (because of the [computed](https://github.com/TanStack/query/blob/8b51e8b690f68190c06c865a84fb6a22c5c29d34/packages/vue-query/src/useBaseQuery.ts#L57)).

When we mark the `queryClient` as [raw](https://vuejs.org/api/reactivity-advanced.html#markraw) all problems are gone, the same if we do _not_ pass the `queryClient` directly as option to one of the query functions.

This issue is difficult to reproduce, as on our end we work with very large amount of dynamic queries (e.g. queries where the query key changes), that is around 200-10.000, and for anything below that JavaScript is fast enough to process the whole queryClient as you do.

### Expected behavior

The `queryClient` should not be cloned or made reactive (at least not as it's done right now). Instead, you could extract the `queryClient` from the options ([here?!](https://github.com/TanStack/query/blob/8b51e8b690f68190c06c865a84fb6a22c5c29d34/packages/vue-query/src/useBaseQuery.ts#L57)) and handle it separately which would solve the issue.

### How often does this bug happen?

Every time

### Screenshots or Videos

Performance tests conducted on our system (closed source) with only one change: marking the `queryClient` as raw **or** not passing it as option:

passing the  `queryClient` as-is to `useQuery`:  
![image](https://user-images.githubusercontent.com/30767528/221113206-4aa26c8a-6d48-4ded-a52c-2c32e9d2858a.png)

marking the `queryClient` as `raw` **or** not providing it as option in `useQuery`:  
![image](https://user-images.githubusercontent.com/30767528/221113384-6c5b6353-f2e8-403d-ab50-33b8c830b25d.png)

I know that this doesn't really help as I can't share my code with you for this, but just to demonstrate the difference it makes for us with this little change)-

### Platform

- OS: Ubuntu 22.04.1 LTS
- Browser: Chrome v109
- Version: @tanstack/vue-query v4.24.6

Also happens on comparable windows / mac-os setups.

### TanStack Query version

v4.24.6

### TypeScript version

v4.9.5

### Additional context

I'm sorry that I couldn't come up with a reproduction, if there are any more details I can add to help fix this please go ahead. I tried to provide as many details as possible, but the project I'm working on is rather large and closed-source making it difficult to create an appropriate reproduction.

**Comment by DamianOsipiuk** [comment]
Hi
This problem will be solved in v5 as `queryClient` will be passed as a separate option https://github.com/TanStack/query/blob/v5/packages/vue-query/src/useBaseQuery.ts#L50

As for v4, maybe extracting client in `parseQueryArgs` to prevent deep cloning, would be enough?

**Comment by DamianOsipiuk** [comment]
Should be fixed in https://github.com/TanStack/query/releases/tag/v4.32.2
