### ISSUE TITLE
isFetching is updated after queryFn has been called

### ISSUE THREAD

**Issue by jasongerbes** [TanStack/query#5032]
### Describe the bug

When refetching stale data, the `isFetching`/`fetchStatus` properties are only updated _after_ the `queryFn` has been called.

This causes an issue when the `queryFn` modifies external state, as there's no way to handle the refetch (i.e. `isFetching` status) before the `queryFn` has been called.

### Your minimal, reproducible example

https://codesandbox.io/s/competent-darwin-p9314m

### Steps to reproduce

1. Go to https://codesandbox.io/s/competent-darwin-p9314m
2. Open and console tab and clear it
3. Trigger an automatic refetch by focusing the browser window
4. Observe the logs

You'll notice that the `queryFn` has been called before `isFetching` is set to `true`.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/13686180/221131715-4c0c68bc-e797-4469-96b7-6b0bd44c6aa5.png">

### Expected behavior

The `isFetching`/`fetchStatus` state should be updated _before_ the `queryFn` is called.

### How often does this bug happen?

Every time

### Platform

- macOS
- Safari/Chrome

### TanStack Query version

latest

**Comment by TkDodo** [comment]
the status does update before, it's just that react hasn't re-rendered the component yet. You can see this by adding a log statement to the queryFn:

```
console.log(queryClient.getQueryState(["repoData"]));
```

https://codesandbox.io/s/romantic-panna-vdyewd?file=/src/index.jsx

Basically, this is just how react works. Pseudo code:

```
const [fetching, setFetching] = useState(false)

useEffect(() => {
  setFetching(true)
  queryFn()
})

console.log(fetching)
```

here, it would also print logs in the `queryFn` first and then, once the component has actually re-rendered, you would see the fetching state reflected in the component.

> This causes an issue when the queryFn modifies external state

This sounds worrying. What are you doing in your queryFn?

**Comment by jasongerbes** [comment]
Thanks for the explanation. Your pseudocode example makes it easier to understand this behaviour.

> This sounds worrying. What are you doing in your queryFn?

I'm incrementally migrating an app from MobX observable state and a custom data fetching hook to Tanstack Query.

In the initial implementation, the `queryFn` is calling an existing 'load action' that clears some global MobX state before fetching the new data. However, due to the complexity of the existing MobX state, the `data` from `useQuery` isn't being utilised.

The long-term plan is to remove the MobX state and use `data` from `useQuery` instead, which will prevent this issue via the built-in 'stale while refetch' behaviour of `useQuery`.

In the meantime, as a workaround, I plan to disable automatic data refetching.
