### ISSUE TITLE
TanStack Query causes components it's used in to render twice

### ISSUE THREAD

**Issue by thianphat** [TanStack/query#5035]
### Describe the bug

Hi,

First off, thank you for this. Game changer. I love it.

I'm running into this issue where any usage of my custom ReactQuery hook will cause a component to render twice. The first render is with undefined data, then the second render with the correct data. Even with it cached.

Is anyone else running into this issue? Please see CodeSandbox

### Your minimal, reproducible example

https://codesandbox.io/embed/upbeat-minsky-6xf1im?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce

1. Add react query to a component.
2. Watch it render once undefined.
3. Then watch it render again with the data.

### Expected behavior

I expect it to render once with data.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="826" alt="Screenshot 2023-02-24 at 6 25 03 PM" src="https://user-images.githubusercontent.com/23284914/221331826-6ea4e6ac-d5ad-4ef6-8572-c456b7e2afaf.png">
<img width="821" alt="Screenshot 2023-02-24 at 6 24 42 PM" src="https://user-images.githubusercontent.com/23284914/221331828-d0c80c6d-1c9f-4e9a-a777-fce5c77eece2.png">
<img width="820" alt="Screenshot 2023-02-24 at 6 32 24 PM" src="https://user-images.githubusercontent.com/23284914/221331830-df5f22ad-61cc-4c99-a0a6-f425d53f7dda.png">
<img width="811" alt="Screenshot 2023-02-24 at 6 24 48 PM" src="https://user-images.githubusercontent.com/23284914/221331831-f7335366-4c7b-4a3a-9c20-035f5be73fbd.png">
<img width="808" alt="Screenshot 2023-02-24 at 6 25 11 PM" src="https://user-images.githubusercontent.com/23284914/221331832-6dbceafa-d725-4b3a-b6ba-1021ad383af2.png">
<img width="1978" alt="Screenshot 2023-02-24 at 6 30 26 PM" src="https://user-images.githubusercontent.com/23284914/221331835-bf998c81-626c-4bf8-9f72-680cccc9e08d.png">

### Platform

macOS

### TanStack Query version

4.24.10

### Additional context

CodeSandbox is what I have on my machine. I just changed the API URL.

**Comment by TkDodo** [comment]
So I'm guessing this about the persistence plugin and you'd expect only one render after you have data persisted and reload the page? You're not mentioning that in the steps to reproduce, so this is just a guess.

The persistence plugin restores asynchronously, but we'll still render the component while the restore is happening. This is crucial for server-side-rendering to work. The query renders in `loading` state, but with `fetchStatus: idle`. If you want to stop your app from rendering, you can check with `useIsRestoring` if that is in progress and render `null` or something instead of your App:

```
const isRestoring = useIsRestoring()

return isRestoring ? null : <App />
```

then, your App will only render once.

**Comment by thianphat** [comment]
Thank you, I removed it from the CodeSandbox and it only renders once. However, I removed it from my application and it still renders twice.
![Screenshot 2023-02-25 at 10 40 34 AM](https://user-images.githubusercontent.com/23284914/221374230-d036d88d-886d-4d9b-9a11-11fce512f20a.png)
![Screenshot 2023-02-25 at 10 39 58 AM](https://user-images.githubusercontent.com/23284914/221374233-a4159c67-a090-43fd-8fa3-7e80af659552.png)
![Screenshot 2023-02-25 at 10 39 28 AM](https://user-images.githubusercontent.com/23284914/221374234-32c967eb-1ea1-4c79-a0cf-4f8c0f40bd56.png)
![Screenshot 2023-02-25 at 10 35 24 AM](https://user-images.githubusercontent.com/23284914/221374235-22f450cc-fcbc-4f1c-b4a3-d03f903bec1f.png)
<img width="1347" alt="Screenshot 2023-02-25 at 10 35 15 AM" src="https://user-images.githubusercontent.com/23284914/221374236-501cce99-072a-4868-ad45-1c14e4c1a913.png">

**Comment by TkDodo** [comment]
Idk, that component has a bunch of other side effects that could cause renders. If it works in a sandbox, we're good.
