### ISSUE TITLE
Possible problem with infinite query + optimistic mutation in Vue

### ISSUE THREAD

**Issue by marina-mosti** [TanStack/query#5047]
### Describe the bug

When mutating an infinite query pages, the reactivity from the `data` returned by the `useInfiniteQuery` is not triggered. This causes computed properties attached to the `data` ref to not recalculate.

### Your minimal, reproducible example

https://codesandbox.io/s/possible-vuequery-infinite-computed-issue-3v14c8

### Steps to reproduce

1. Go to the codesandbox
2. Open the console log and click mutate

You will notice:

```
mutating -> Start of mutation
setting new pages  -> setQueryData
new data  
mutation resolved -> mutationFn resolved
settled, invalidating -> onSettled and invalidation

// vue query refetches 

!! computed fired !!
```

The computed property does not fire until _after_ the mutation is completely resolved and settled. The problem here is that the `data` property seemingly is not being updated with the result of `setQueryData`, thus rendering the whole optimistic update pointless.

### Expected behavior

I would expect `data` to be updated internally by the query client whenever I `setQueryData` so that I can rely on Vue reactivity to display it to the user.

### How often does this bug happen?

Every time

### Platform

macOs
Firefox 110

### TanStack Query version

4.10.1 > 4.24.10

**Comment by DamianOsipiuk** [comment]
By changing this piece of code it will trigger computed recalculation.

```ts
//lastPage.push(5);
newPages[newPages.length - 1] = [...lastPage, 5]
```

**Comment by marina-mosti** [comment]
Thanks for looking into it @DamianOsipiuk
