### ISSUE TITLE
[vue]: type narrowing not working on `data` field

### ISSUE THREAD

**Issue by WickyNilliams** [TanStack/query#5065]
### Describe the bug

type narrowing of the `data` field does not work correctly with vue. even after checking `isSuccess` or `state === "succcess"` the type of data is `TData | undefined`

consider [this example from the docs](https://tanstack.com/query/v4/docs/vue/typescript#type-narrowing):

```ts
const { data, isSuccess } = useQuery({
  queryKey: ['test'],
  queryFn: () => Promise.resolve(5),
})

if (isSuccess) {
  data
  //  ^? const data: number
}
```

OK, the first issue is that the example does not access the `.value` prop on the data ref. but ignoring that, if you paste the above into the typescript playground, you will see that the type is actually `number | undefined`

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ5wC+cAZlBCHAOQACMAhgHaoMDGA1gPQBuOAtAEcc+KgFgAUBNYRm8JABN6DADRxgqAMrJWrdKlRE4AXhQZsuPAAoA2lRh6YVALqrLASmMA+OAAVyIdXQAOig9CAAbbnRLAFY3NwkJYBI4S3UtHT1UDwQJOHy4RQYg7npwnDyCzk4C-IA9AH4JQgkgA

### Steps to reproduce

1. go to above link
2. notice the type shown is `number | undefined` but it should be narrowed to `number` only

### Expected behavior

i expect type narrowing to work in vue, as shown in the docs

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="542" alt="image" src="https://user-images.githubusercontent.com/1091390/222493847-601cee14-cc24-4697-b32a-e1f755ebd325.png">

### Platform

- OS: macOS
- browser: n/a

### TanStack Query version

4.24.10

### TypeScript version

v4.9.5

**Comment by DamianOsipiuk** [comment]
This is a limitation of current typechecking in Vue

You can work around it by wrapping `useQuery` with `reactive` and avoiding destructuring.

![image](https://user-images.githubusercontent.com/28151934/223516465-0d2df366-413d-4e08-bb17-2c1d938ebe05.png)

**Comment by DamianOsipiuk** [comment]
Sure, go for it 👍

**Comment by sschwandter** [comment]
Hi!

I just got started with vue query 5 and stumbled upon this issue. This is still an issue in v5 AFAICT, isn't it? If yes I could provide a PR for the documentation (I didn't find an existing one).

**Comment by viniciusteixeiradias** [comment]
I ran into a type-narrowing issue in a Vue template. TypeScript was narrowing `data` in a way that forced me to use `data.value`, but doing that made the UI render nothing. The template only worked when accessing `data` directly, which meant ignoring the TS errors. This was happening with:
```json
"typescript": "~5.9.0",
"@tanstack/vue-query": "^5.92.1"
```
Downgrading TypeScript resolved the problem:
```json
"typescript": "~5.8.0",
"@tanstack/vue-query": "^5.92.1"
```
