### ISSUE TITLE
eslint plugin exhaustive deps objects false positive

### ISSUE THREAD

**Issue by DianomiJH** [TanStack/query#5069]
### Describe the bug

I recently installed the plugin and started using the recommended rules but it flagged a bunch of false positives. 

When using an object of data within useQuery, we sometimes pass the whole object to the queryKey, but the eslint plugin says some items are missing from the queryKey.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/vibrant-voice-fktju6?welcome=true&file=%2FREADME.md

### Steps to reproduce

open the terminal and run `npm run lint` and see errors in the terminal. 

### Expected behavior

I'd expect this to work the same as a useEffect dependency array, allowing passing the object to the array and removing warnings, But I'm seeing it asking for additional items in the array.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/84312830/222692268-9f9fdc6b-df2a-4803-80a4-c2f68433091f.png)

### Platform

macOS
in vscode (and codesandbox)

### TanStack Query version

v4.22.0

### TypeScript version

^4.9.4

edit:
I also notice, if I do add state.id to the query key, the warning goes away, but I'm still using 2 other items from state in the query function and am not getting any errors anymore! (maybe this is more problematic than the original issue??)

**Comment by TkDodo** [comment]
yeah I think it's two bugs actually:

1) if you use `state.id` and `state.name` in the queryFn, but you only have `state.id` in the queryKey, it doesn't error even though it should.

2) if you use `state.id` and `state.name` in the queryFn, and you have the complete `state` in the queryKey, it errors even though it shouldn't.

@Newbie012 FYI. I can try to write the failing test cases later today when I have some more time.

**Comment by DianomiJH** [comment]
I think there might be another issue here too, if you use optional chaining in the queryKey but don't use it in the queryFn it complains at you (or maybe it was the other way around, I'm on mobile right now and can't check)

**Comment by TkDodo** [comment]
here is a failing test case for situation 1 I described (should error, but doesn't):

```
{
  name: 'should fail if queryFn is using multiple object props when only one of them is in the queryKey',
  code: normalizeIndent`
    const state = { foo: 'foo', bar: 'bar' }

    useQuery({
        queryKey: ['state', state.foo],
        queryFn: () => Promise.resolve({ foo: state.foo, bar: state.bar })
    })
  `,
  errors: [
    {
      messageId: 'missingDeps',
      data: { deps: 'state.bar' },
    },
  ],
},
```

and here is one for situation 2 (should work, but errors), even though this situation can be worked around at the moment by just using all props explicitly. We could even argue that this case is an OK error because what if `state` contains more fields? Then you have something in the queryKey which is not used in the queryFn, which will lead to unnecessary duplicated cache entries. So I'm not sure if we should really "fix" this one:

```
{
  name: 'should not fail if queryKey is having the whole object while queryFn uses some props of it',
  code: normalizeIndent`
    const state = { foo: 'foo', bar: 'bar' }

    useQuery({
        queryKey: ['state', state],
        queryFn: () => Promise.resolve({ foo: state.foo, bar: state.bar })
    })
  `,
},
```

**Comment by Newbie012** [comment]
Thanks :) I'll take a look at it

**Comment by Newbie012** [comment]
Should be fixed once https://github.com/TanStack/query/pull/5079 will be merged.

**Comment by DianomiJH** [comment]
🥳
