### ISSUE TITLE
jest -> vitest

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#5074]

**Comment by crutchcorn** [comment]
Per our conversation here:

https://twitter.com/TkDodo/status/1631952196974592000?t=nqJfxD8QT7aOnDw8MZzCYQ&s=19

(Mostly linking to preserve for my memory's sake) 

I'd like to see what progress I can make on this issue

**Comment by snnyvrz** [comment]
I'm just a comment away? I want to know if I can help

**Comment by ydubinskyi** [comment]
Would like to contribute to this
