### ISSUE TITLE
@tanstack/svelte-query never catches the request error. 

### ISSUE THREAD

**Issue by danielfsmith91** [TanStack/query#5086]
### Describe the bug

svelte-query never catches the error.

### Your minimal, reproducible example

https://codesandbox.io/s/stupefied-monad-1ptn88?file=/src/lib/Simple.svelte

### Steps to reproduce

in this example, just change the fetch url to throw an error
https://tanstack.com/query/latest/docs/svelte/examples/svelte/simple

### Expected behavior

an error message should be displayed

### How often does this bug happen?

Every time

### Screenshots or Videos

query
```
const query = createQuery({\n
   queryKey: ['todos'],
   queryFn: () => fetch('https://jsonplaceholder.typicode.com/todos-')
});
```

status
![Screenshot at 2023-03-06 16-28-03](https://user-images.githubusercontent.com/53831261/223251516-c5d3fb92-a3f4-4225-a049-bcb46aaa7379.png)

request
![Screenshot at 2023-03-06 16-27-40](https://user-images.githubusercontent.com/53831261/223251678-93c3706d-fc56-470a-8ae4-d83ba52d1460.png)

### Platform

- OS: Linux
- Browser: Chrome
- Version: 110.0.5481.177 (Official Build) (64-bit)

### TanStack Query version

@tanstack/svelte-query: 4.26.1

### TypeScript version

typescript: 4.9.5

**Comment by TkDodo** [comment]
fetch doesn't reject the Promise on 4xx and 5xx status codes

https://tanstack.com/query/v4/docs/react/guides/query-functions#usage-with-fetch-and-other-clients-that-do-not-throw-by-default
