### ISSUE TITLE
Docs: useMutation incorrectly has mutationKey as an optional param

### ISSUE THREAD

**Issue by givensuman** [TanStack/query#5114]
### Describe the bug

The [documentation](https://react-query-v3.tanstack.com/reference/useMutation#_top) for `useMutation` appears to be incorrect.

It says:
```
 const {
   ...
} = useMutation(mutationFn, {
   mutationKey,
   ...
})

```
when the actual structure of the hook is
```
const {
   ...
} = useMutation(mutationKey, mutationFn?, {
   ...
})
```
The question mark there is because the type definition specifies the mutationFn as optional, and it's also documented that way in the [useQuery](https://react-query-v3.tanstack.com/reference/useQuery#_top) page.

The options below the codeblock also appear to be wrong, stating that the key is optional and the callback is required, when these are reversed.

I imagine this is an artifact of an older version of the API?
Let me know if I'm wrong about this, I'm hardly an expert on this library (it rules btw). If it is confirmed I'd be happy to handle a PR to update the useMutation docs page.

### Your minimal, reproducible example

https://react-query-v3.tanstack.com/reference/useMutation#_top

### Steps to reproduce

N/A

### Expected behavior

N/A

### How often does this bug happen?

None

### Platform

N/A

### Tanstack Query adapter

None

### TanStack Query version

N/A

**Comment by TkDodo** [comment]
the docs are correct. the function is required for mutations, the key is not. there are overloads, so multiple versions to call the function are possible. This will change with v5, where it's always an object:

https://tanstack.com/query/v5/docs/react/reference/useMutation
