### ISSUE TITLE
refetchonwindowfocus is not working on android browser

### ISSUE THREAD

**Issue by anhnt160190** [TanStack/query#5121]
### Describe the bug

our api configuration is `refetchOnWindowFocus: 'always'`
it works in web browser, ios safari but does not work in the android browser

### Your minimal, reproducible example

https://5x4il2.csb.app/

### Steps to reproduce

1. my codesandbox: https://codesandbox.io/s/eloquent-leakey-5x4il2?file=/src/App.js
2. access URL https://5x4il2.csb.app/ via android browser
3. wait for some minutes
4. touch into the screen
5. not change in the screen

### Expected behavior

new date will be updated in the screen

### How often does this bug happen?

None

### Platform

OS: Android

### Tanstack Query adapter

react-query

### TanStack Query version

3.39.3

**Comment by TkDodo** [comment]
> touch into the screen

what does that mean please? We listen to the standard [visibilitychange event](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) to trigger refetches of stale queries. If that doesn't work in your situation, you can supply your own event listener:

https://tanstack.com/query/v4/docs/react/reference/focusManager#focusmanagerseteventlistener

**Comment by anhnt160190** [comment]
@TkDodo mean that it doesn't trigger refetches the queries in the android browser

**Comment by anhnt160190** [comment]
@TkDodo I keep the screen for about 5mins without any actions
then I try to touch in the screen
I expect the API should be refetched

**Comment by TkDodo** [comment]
You'd have to setup a custom event listener as described above.
