### ISSUE TITLE
Recurring error with vite-plugin-solid: 2.6.1 and solid-query: 4.26.1

### ISSUE THREAD

**Issue by LazyYuuki** [TanStack/query#5141]
I was just about to merge this when I took another look at the codesandbox preview build, and it sadly doesn't render anymore:

https://codesandbox.io/s/tanstack-query-example-solid-basic-typescript-17fbsy

The error is:

```
Uncaught ReferenceError: React is not defined
    at QueryClientProvider (QueryClientProvider.jsx:37:5)
    at dev.js:519:12
    at untrack (dev.js:425:12)
    at Object.fn (dev.js:515:37)
    at runComputation (dev.js:695:22)
    at updateComputation (dev.js:680:3)
    at devComponent (dev.js:526:3)
    at createComponent (dev.js:1228:10)
    at App (index.tsx:142:3)
    at dev.js:519:12
```

I was working yesterday for sure :/

_Originally posted by @TkDodo in https://github.com/TanStack/query/issues/4211#issuecomment-1256869249_

Hi, sorry I am not very familiar with opening up issue yet, so please excuse me if my format is wrong.

As reference above, I am seeing the exact error again when I am trying to use solid-query package. I am currently on `vite-plugin-solid: 2.6.1` and `tanstack/solid-query: 4.26.1`. Any help in resolving issue will be much appreciated.

**Comment by TkDodo** [comment]
the provided sandbox link works fine for me now
