### ISSUE TITLE
Docs: Broken link for Custom hooks example

### ISSUE THREAD

**Issue by cseas** [TanStack/query#5172]
### Describe the bug

Google search for React Query custom hooks leads to a broken link in the docs. This example is not listed under the "Examples" section in the sidebar navigation. Looks like it used to exist at some point but got removed. Can this be added back?

I can see an example on the same link if I switch to v3 docs. It's missing in v4.

<img width="609" alt="Screenshot 2023-03-21 at 6 09 57 PM" src="https://user-images.githubusercontent.com/29686866/226608783-b7121d60-47a0-43bd-ac33-bd288c686737.png">

### Your minimal, reproducible example

https://tanstack.com/query/v4/docs/react/examples/react/custom-hooks

### Steps to reproduce

Visit https://tanstack.com/query/v4/docs/react/examples/react/custom-hooks

### Expected behavior

The custom hooks example link should work.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="1295" alt="Screenshot 2023-03-21 at 6 13 14 PM" src="https://user-images.githubusercontent.com/29686866/226609440-8a35bbb5-4d6e-4ec2-a833-596898769f18.png">

### Platform

- OS: macOS
- Browser: Edge

### Tanstack Query adapter

None

### TanStack Query version

4

**Comment by TkDodo** [comment]
The example has been removed, so it doesn't exist anymore.
