### ISSUE TITLE
docs incomplete on invalidate example

### ISSUE THREAD

**Issue by rkristelijn** [TanStack/query#5176]
### Describe the bug

https://github.com/TanStack/query/blob/main/docs/react/quick-start.md

the code imports things from an external file when I'm interested in what is in these functions:

`import { getTodos, postTodo } from '../my-api'` 

Why not just put the two functions inline so you have one overview?

### Your minimal, reproducible example

https://github.com/TanStack/query/tree/main/docs/react/guides

### Steps to reproduce

1. Go to https://github.com/TanStack/query/blob/main/docs/react/quick-start.md
2. See the functions getTodos and postTodo are not there

### Expected behavior

As a developer I would like to understand the full picture:

1. Go to https://github.com/TanStack/query/blob/main/docs/react/quick-start.md
2. See the functions getTodos and postTodo

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/21142148/226871680-4ded216b-fdaf-463b-85d1-b757b9076abd.png)

### Platform

any platform, but using chrome browser ¯\(°_o)/¯ 

### Tanstack Query adapter

None

### TanStack Query version

DamianOsipiuk docs(vue-query): migrate vue-query docs (#4710) … Latest commit 46fae94 on Dec 29, 2022  History

### TypeScript version

DamianOsipiuk docs(vue-query): migrate vue-query docs (#4710) … Latest commit 46fae94 on Dec 29, 2022  History

**Comment by TkDodo** [comment]
> Why not just put the two functions inline so you have one overview?

Because we would have to implement the API in some way, either fetch or axios or Promise.resolve or something else ... It would just lead users to believe that this is the only way to implement query functions, which is not true. React Query doesn't care how the query function is implemented.

also, if you want a runnable example, they are on the examples page.

**Comment by rkristelijn** [comment]
What about linking in a code example in the documentation? Would help learning about tanstack-react-query https://github.com/dotansimha/graphql-code-generator/tree/master/examples/react/tanstack-react-query

**Comment by TkDodo** [comment]
we are already doing that at the top of that page:

> If you're looking for a fully functioning example, please have a look at our [simple codesandbox example](https://github.com/TanStack/query/blob/main/docs/examples/react/simple)

**Comment by rkristelijn** [comment]
Thanks for taking the time to still try and answer my question. The link provided is exactly what I'm *not* looking for. I'm looking for a working example for useMutation and graphql, which is not provided in the examples.

**Comment by TkDodo** [comment]
why would the quickstart link to a useMutation and graphql example? That's a quite specific thing ...
