### ISSUE TITLE
Query retries pause window is in the background (electron) even though refetchIntervalInBackground is true.

### ISSUE THREAD

**Issue by nnguyen01** [TanStack/query#5197]
### Describe the bug

Here's my code:
  ```const { data } = useQuery({
    queryKey: ['myQuery'],
    queryFn: myQuery,
    retry: handleRetry,
    refetchInterval: 2000,
    refetchIntervalInBackground: true,
    networkMode: 'always',
  });
```

  
I've tried setting networkMode to always but it's also not working. My electron window has `backgroundThrottling: false,` as well.

After logging the fetch status, it is in a `paused` state no matter what if the query fails and the window is in the background.

### Your minimal, reproducible example

N/A

### Steps to reproduce

1. Create a window with background throttling set to false in electron.
2. Run a query with retries.
3. Minimize the window.
4. Force the query to fail.

### Expected behavior

As a user, I expect the query to retry after a failure and the fetch status to not be paused if the app / window (electron) is in the background.

### How often does this bug happen?

Every time

### Platform

Windows

### Tanstack Query adapter

react-query

### TanStack Query version

v4.28.0

**Comment by nnguyen01** [comment]
Ah looks like I had to manually set the focus to enable retries even with the network mode

https://github.com/TanStack/query/blob/main/packages/query-core/src/retryer.ts#L97
https://tanstack.com/query/v4/docs/react/reference/focusManager

**Comment by TkDodo** [comment]
yes, queries are paused if they are not in focus. You can override the focusManager event listener if you want to change that.
