### ISSUE TITLE
v4 - no exported member QueryClient 

### ISSUE THREAD

**Issue by aestheticsdata** [TanStack/query#5203]
### Describe the bug

The QueryClient was available in v3. Switching to v4 I have the error : TS2724: '"@tanstack/react-query"' has no exported member named 'QueryClient'. Did you mean 'useQueryClient'?
But it's still there in the doc : https://tanstack.com/query/v4/docs/react/reference/QueryClient#queryclient

Trying to switch to useQueryClient 
`const queryClient = useQueryClient();`
or `const queryClient = useQueryClient({});`
I have the error TypeError: Cannot read properties of null (reading 'useContext')
But reading the doc : https://tanstack.com/query/v4/docs/react/reference/useQueryClient , "Otherwise, defaultContext will be used."

### Your minimal, reproducible example

no playground

### Steps to reproduce

install Tanstack query for react v4.28.0
install NextJS v13.1.2
build the NextJS project

### Expected behavior

according to the doc, using QueryClient do not throw an error
according to the doc, using useQueryClient without context should work and use the defaultContext

### How often does this bug happen?

Every time

### Platform

MacOS 11.6
Mac M1
NextJS v13.1.2

### Tanstack Query adapter

None

### TanStack Query version

v4.28.0

### TypeScript version

v4.5.5

**Comment by TkDodo** [comment]
Sorry to see that you have this error, but `QueryClient` is definitely exported. All our codesandbox examples show that this is working.

So you have to provide a reproduction please. Feel free to reopen if you can isolate the issue.

**Comment by aestheticsdata** [comment]
in my monorepo with pnpm, the way to make it working is to set `preserveSymlinks` to false in tsconfig.json of each of the app which use TanStack Query.
