### ISSUE TITLE
Module level directives cause errors when bundled, "use client"

### ISSUE THREAD

**Issue by duypham90** [TanStack/query#5216]
### Describe the bug

When use vite v4.2.1 building for production I got many warning as below:
`
Module level directives cause errors when bundled, "use client" in "node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs" was ignored.
`

<img width="1634" alt="Screen Shot 2023-04-01 at 19 27 07" src="https://user-images.githubusercontent.com/24804332/229288725-78f7fd36-c324-444d-9f61-3f4e9de985af.png">

### Your minimal, reproducible example

N/A

### Steps to reproduce

1. Init source 
```ts
yarn create vite my-app --template react-ts
```
2. install TanStack query and config same with TanStack document.
3. Add sample fetch data by `useQuery`
3. Build for production mode

### Expected behavior

Don't show errors
> Module level directives cause errors when bundled, "use client"

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/24804332/229289016-5268f0d0-5231-4b7c-9ba5-1b5354b56872.mov

### Platform

- OS: Mac OS Monterey. Version 12.5

### Tanstack Query adapter

react-query

### TanStack Query version

v4.28.0

### TypeScript version

v5.0.2

**Comment by TkDodo** [comment]
duplicate:
- https://github.com/TanStack/query/issues/5175
