### ISSUE TITLE
Module level directives cause errors when bundled

### ISSUE THREAD

**Issue by vadymstebakov** [TanStack/query#5220]
### Describe the bug

I got a lot of error warnings while building with React v18.2.0 + Vite v4.1.4.

### Your minimal, reproducible example

-

### Steps to reproduce

1. `npm run build`;
2. see error;

### Expected behavior

I expected the build process to go without any error warnings. It has already been said in [this](https://github.com/TanStack/query/pull/5161#issuecomment-1491988610) pull request.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/37370019/229346030-ce39a357-01ee-4c50-a07e-c11bd79f5188.png">

### Platform

- macOS;
- Chrome;
- version 111;

### Tanstack Query adapter

react-query

### TanStack Query version

v4.28.0

### TypeScript version

v4.9.5

**Comment by TkDodo** [comment]
I literally just closed the same issue an hour ago as a duplicate. Opening more duplicates won't make it any better. Please use the search before filing issues.

- https://github.com/TanStack/query/issues/5216
- https://github.com/TanStack/query/issues/5175

**Comment by vadymstebakov** [comment]
My bad. Thanks.
