### ISSUE TITLE
Testing a customHook that has a failing response does not update the error property

### ISSUE THREAD

**Issue by holgergp** [TanStack/query#5226]
### Describe the bug

Hi all!

I wanted to test a custom hook that may have to work with an erroneous response. For this I throw an Error if a reponse code > 299 is present.
Something like:
```
queryFn: () => {
  throw new Error("My response fails!");
},
```
In the test I use `renderHook` and await the error like so:

```
await waitFor(() => {
  return expect(result.current.isError).toBe(true);
});
```

But this does not seem to yield the expected result, same goes for returning a rejected promise.

Do I do something wrong here? Did I miss something or is my expectation towards the error state false?

I am happy about any pointers!

The github repo containing the minimal example can be found here: https://github.com/holgergp/react-query-error

Cheers from Düsseldorf and thanks for your great work!

Holger

### Your minimal, reproducible example

https://codesandbox.io/p/github/holgergp/react-query-error

### Steps to reproduce

- Run the tests
- See `myCustomHook should work with an error` fail.

### Expected behavior

As a user testing a custom hook I would like to see errors happening in the queryFunction be reflected in the `result.current.isError` property.

### How often does this bug happen?

Every time

### Platform

OS: MacOS/GithubActions/Codesandbox

### Tanstack Query adapter

react-query

### TanStack Query version

4.28.0

### TypeScript version

4.9.5

**Comment by TkDodo** [comment]
It works if I set `retry: false,` directly on the `useQuery`, so something is up with your `beforeEach`

looking closer, `queryClient.defaultQueryOptions` doesn't set anything, it combines options. You're likely looking for `queryClient.setDefaultOptions`.

On the other hand, I don't know why you'd share a queryClient between production and testing. Just create a separate one for each test, as described here:

https://tanstack.com/query/v4/docs/react/guides/testing

and here:

https://tkdodo.eu/blog/testing-react-query
