### ISSUE TITLE
UseQuery does not fetch when using enabled, initialData, staleTime and a variable querKey

### ISSUE THREAD

**Issue by ArthurNRL** [TanStack/query#5250]
### Describe the bug

When using staleTime > 0, the enabled flag attached to some state, a variable query key related to some state, and a initialData value, the query does not fetch when the cache key changes. removing the initialData option or the stateTime setting makes it work but not in the way we want it to (since I need staleTime and initialData). Worked around by not setting initialData and then checking for the current data value.

### Your minimal, reproducible example

https://codesandbox.io/s/fragrant-bash-83ql2o?file=/src/App.js

### Steps to reproduce

1. Click enable
2. Click any of the other boxes to change the queryKey
3. Check console, state is changing but the refetch is not happening

### Expected behavior

I expect that when the queryKey changes, if we already have non stale data for the new key the non stale data is shown, if the data is stale the query runs again.

### How often does this bug happen?

Every time

### Platform

Windows 11
Newest Chrome and firefox

### Tanstack Query adapter

react-query

### TanStack Query version

4.29.1

### TypeScript version

4.9.5

### Additional context

I've added redux to my example because I thought it was the culprit, but it seems it's actually the initialData/staleTime combo

**Comment by Talent30** [comment]
Please provide an example without redux to help the community maintainers troubleshoot this issue better

**Comment by Talent30** [comment]
I have noticed that your staleTime is 360000, if you set the staleTime to 60 then your statement "the query does not fetch when the cache key changes" would be false because it does fetch but there is a delay.

**Comment by Talent30** [comment]
https://stackoverflow.com/questions/75346877/react-query-staletime-and-cached-value

**Comment by ArthurNRL** [comment]
Changed the example to remove redux. I don't see how staleTime should matter when the query key is changing. And like I said, removing the initialData option enables it to run for some reason(?).

**Comment by Talent30** [comment]
Yes, for every query key change it is supposed to trigger the queryFn. However, since you have such a high staleTime plus initial data, to react-query this query is actually fresh therefore it would not call the queryFn. 

So my conclusion is that this is not a bug.

Please read [https://tanstack.com/query/v4/docs/react/guides/initial-query-data#staletime-and-initialdataupdatedat](url)

**Comment by ArthurNRL** [comment]
I'm sorry but if it's supposed to refetch with the new query arguments, then why staleTime even matters?
My data hardly changes(only through user interaction, which changes the queryKey) thats why I have a high staleTime, so I don't hit the user with loading side effects when they navigate away and back.
My reasoning is: I need initial data to avoid dealing with undefined(value and type), I need staleTime to avoid loading screens when they are not needed, if the queryKey changes(changing filtering params/user interaction changes the data in the backend) then the query should be able to like you said trigger the fn.
In my undertanding initialData is there if the query hasn't finished fetching yet/failed, staleTime starts ticking as soon as the fetch is done. 
I see that the docs you've sent does say that initialData actually sets the staleTime for itself, is there a way to workaround this? I would rather not have `if(data!==undefined)` and `data?....` everywhere in my code

**Comment by Talent30** [comment]
"I'm sorry but if it's supposed to refetch with the new query arguments, then why staleTime even matters?"

It matters because as soon as the new query is created it is 'fresh' due to the initial data, therefore it wouldn't even call queryFn. Therefore it is not a bug suggest we move this to discussions.

I highly recommend you install devtool to help you visualise what is going on.

**Comment by Talent30** [comment]
"so I don't hit the user with loading side effects when they navigate away and back."

https://tanstack.com/query/v4/docs/react/guides/window-focus-refetching

**Comment by TkDodo** [comment]
initialData is persisted to the cache. It's treated as if that data were fetched from the network. So if you provide `initialData` and a `staleTime`, you will not get a refetch even when the key changes. I think you are just looking for `placeholderData`.

Please read: https://tkdodo.eu/blog/placeholder-and-initial-data-in-react-query

**Comment by ArthurNRL** [comment]
Thanks for the help!

**Comment by dwjohnston** [comment]
@TkDodo  Thanks for clarifying here, but I thought I'd mention there's a reason I might not want to use placeholder data. 

For example, say you've got a list of items, and you're going to be polling it every 10 seconds for updates. We don't want it be showing a flash of an empty list every 10 seconds as it polls. 

It's worth mentioning too, that you can use `initialData` and have it be immediately stale if you set the `initialDataUpdatedAt` to 0.

**Comment by TkDodo** [comment]
> We don't want it be showing a flash of an empty list every 10 seconds as it polls.

that's not what placeholderData would do. If you use a `refetchInterval`, it will only show the placeholder instead of the first empty state. After that, it will keep the stale data always.

> It's worth mentioning too, that you can use initialData and have it be immediately stale if you set the initialDataUpdatedAt to 0.

yes that also works.
