### ISSUE TITLE
Doesn't work with Next 13.3

### ISSUE THREAD

**Issue by hornta** [TanStack/query#5257]
### Describe the bug

I test that it works with Next 13.2.

With 13.3 it gives me this error:
![image](https://user-images.githubusercontent.com/4553604/231399282-30e0102f-8683-4121-a032-0eaa504e3302.png)

### Your minimal, reproducible example

-

### Steps to reproduce

-

### Expected behavior

-

### How often does this bug happen?

Every time

### Platform

-

### Tanstack Query adapter

None

### TanStack Query version

4.29.1

**Comment by Talent30** [comment]
There is nothing to do with react-query, if you are a Windows user please checkout https://github.com/vercel/next.js/issues/47704

**Comment by hornta** [comment]
Alright yes that might be it. I'm closing this then, thanks.
