### ISSUE TITLE
NextJS 13 Beta App Directory + React Query error: attempting to export "metadata" from a component marked with "use client", which is disallowed.

### ISSUE THREAD

**Issue by prodbygoss** [TanStack/query#5261]
### Describe the bug

I am using NextJS 13 beta app directory with React Query. I followed the setup instructions [here](https://tanstack.com/query/latest/docs/react/guides/ssr#using-experimental-app-directory-in-nextjs-13)

Now, I am getting the following compile error:

```
You are attempting to export "metadata" from a component marked with "use client", which is disallowed. Either remove the export, or the "use client" directive. Read more: https://beta.nextjs.org/docs/api-reference/metadata
```

This is unexpected because the file where the metadata export happens does not have "use client" written in it. In other words, it should be a server component.

In order to prevent a compile error, I can do the following:
- Remove the `metadata` export line (not ideal because I want meta tags for the page)
or
- Remove the `useQuery` call inside the child client component

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/nextjs-reactquery-v8sgy9?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A4%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A4%2C%22startLineNumber%22%3A14%7D%5D

### Steps to reproduce

1. Load the CodeSandbox
2. Observe the error shown 
3. Comment out the metadata line to have it successfully compile
```
export const metadata: Metadata = {
  title: "My Site",
};
```

### Expected behavior

I expect to be able to use the `metadata` export feature without a compile error.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="720" alt="CleanShot 2023-04-12 at 18 19 47@2x" src="https://user-images.githubusercontent.com/82852973/231620861-524c7fee-49f0-4399-ac30-0d766e75836d.png">

### Platform

- OS [Mac OS]
- Browser [Arc]

### Tanstack Query adapter

react-query

### TanStack Query version

v4.29.1

### TypeScript version

v4.9.4

### Additional context

Maybe I set something up wrong? Or maybe this is a known issue? Thanks for the help.

**Comment by prodbygoss** [comment]
I have figured out the issue causing this (and it was unrelated to react-query).

For others wondering or experiencing the same issue, the issue arises because I am importing a part of the server component into a client component.

In the case of the sandbox, I'm importing the `getBeers` function from the `app/page.tsx` file (a server component) into `app/Beers.tsx` (a client component), which is not allowed.

**Comment by kriptonian1** [comment]
@prodbygoss then what's the fix, if I want to use title to a server side page
