### ISSUE TITLE
 Module level directives cause errors when bundled, "use client" in "node_modules/.pnpm/@tanstack+react-query@4.28.0_biqbaboplfbrettd7655fr4n2y/node_modules/@tanstack/react-query/build/lib/useBaseQuery.mjs" was ignored.

### ISSUE THREAD

**Issue by vaynevayne** [TanStack/query#5263]
### Describe the bug

in vite4 

<img width="943" alt="image" src="https://user-images.githubusercontent.com/124666577/231712223-86708023-af1c-43df-a7f9-a0c20c31ebef.png">

### Your minimal, reproducible example

build error

### Steps to reproduce

pnpm run build 

### Expected behavior

wu

### How often does this bug happen?

None

### Platform

node build 

### Tanstack Query adapter

None

### TanStack Query version

4.28

**Comment by tortilaman** [comment]
Why was this closed? I am also seeing this error:

```
vite v4.2.1 building for e2e...
transforming (38) node_modules/@tanstack/react-query/build/lib/index.mjsModule level directives cause errors when bundled, "use client" in "node_modules/@tanstack/react-query-devtools/build/lib/index.mjs" was ignored.
transforming (68) node_modules/@tanstack/react-query/build/lib/setBatchUpdatesFn.mjsModule level directives cause errors when bundled, "use client" in "node_modules/@tanstack/react-query/build/lib/useQueries.mjs" was ignored.
Module level directives cause errors when bundled, "use client" in "node_modules/@tanstack/react-query/build/lib/useQuery.mjs" was ignored.
[...]
```

Both Vite and Tanstack query are up to date.
