### ISSUE TITLE
TS mistyping: QueryOptions missing staleTime

### ISSUE THREAD

**Issue by scarlac** [TanStack/query#5269]
### Describe the bug

`staleTime` is missing from `QueryOptions`, but new `Query`ies are [always created with the default query options](https://github.com/TanStack/query/blob/main/packages/query-core/src/queryCache.ts#L103).

Since the default options are of the type `QueryObserverOptions` (via `DefaultedQueryObserverOptions`), and the `Query.options` property is of type `QueryOptions`, the property `staleTime` is lost from the types.
This has the effect that `onFetch(context: FetchContext)`, and other places where `query.options` are used, do not have typed access to the `staleTime` property that might exist. This means that consumers have to cast QueryOptions to `QueryObserverOptions`.
I checked the source of v3 for any instances of `new Query(...)` and only found that one location (assuming main hasn't changed too much since then), so it should be safe to simply update `QueryOptions` as such:
```ts
export interface QueryOptions<...> {
  // ..
  cacheTime?: number // exists already
  staleTime?: number // add this
}
```

By doing this, we could also get rid of `staleTime?: number` on: `QueryObserverOptions` and complete removal of `FetchQueryOptions`.

I was originally hesitant to cast to observer options, because I thought there was a conceptual difference, but it's not clear that there is. Practically speaking, all queries may be assigned a `staleTime`, yet `QueryOptions` does not reflect this fact.

### Your minimal, reproducible example

https://snack.expo.dev/9z36ZxLX9

(snack sites shows all types as 'any' so you may not be able to see the issue)

### Steps to reproduce

```
queryClient.setDefaultOptions({
  queries: {
    staleTime: 42,
    behavior: {
      onFetch: (context) => {
        // This will generate a type error, but still works (ie. it logs out 'context staleTime 42' when a fetch is initiated)
        console.log('context staleTime', context.options.staleTime)
      }
    },
  },
});
```

### Expected behavior

`QueryOptions` should have `staleTime?: number` on it

### How often does this bug happen?

Every time

### Screenshots or Videos

![Screenshot 2023-04-13 at 10 15 55](https://user-images.githubusercontent.com/895369/231835354-df95c2ca-2e73-475e-82ce-3c4b0e8a66d9.jpg)

![Screenshot 2023-04-13 at 10 27 14](https://user-images.githubusercontent.com/895369/231837825-457d7be6-1e91-4d72-abec-7cb46b5d5b0f.jpg)

### Platform

- OS: all
- Browser: all
- Version: 3.39.1 (and also in `main` branch)

### Tanstack Query adapter

react-query

### TanStack Query version

v3.39.1

### TypeScript version

v4.3.5

**Comment by TkDodo** [comment]
`staleTime` is an observer level property and not a `query` level one (as opposed to `cacheTime`). You can have multiple observers with different `staleTime`.
