### ISSUE TITLE
Memory leak in vue-query + Nuxt 2 SSR

### ISSUE THREAD

**Issue by gridmaniac** [TanStack/query#5296]
### Describe the bug

Using Nuxt v2.15.8 I did simple setup by adding `QueryClient` initialization with `vue-query.js` plugin.

```js
import { VueQueryPlugin, QueryClient } from '@tanstack/vue-query'
import Vue from 'vue'

export default () => {
  // Modify your Vue Query global settings here
  const queryClient = new QueryClient()
  const options = { queryClient }

  Vue.use(VueQueryPlugin, options)
}
```

In component I call useQuery (it is called on SSR and client) inside setup function:
```js
const { data: pokemons } = useQuery(['pokemons'], async () => {
  const res = await fetch('https://pokeapi.co/api/v2/pokemon')
  return res.json()
})
```

Then I run nuxt in production mode and debug it with DevTools using
`while true; do curl -s localhost:3000 -o /dev/null; done`

Heap size starts growing infinitely and number never goes down.

`QueryClient` and `QueryCache` number is only 2 but `QueryObserver` number is growing and every QueryObserver contains all states with data which seems to be what taking that much memory.

I tried workaround clearing it with `queryClient.clear()` that helps with releasing `QueryObservers` but I also tried same setup in Nuxt 3 and there is no memory leak there.

### Your minimal, reproducible example

https://github.com/gridmaniac/nuxt2-vue-query

### Steps to reproduce

1.` yarn build`
2. `yarn dev-debug`
3. chrome://inspect/#devices -> `inspect`
4. `while true; do curl -s localhost:3000 -o /dev/null; done`

Memory goes crazy, `QueryObserver` never gets released.

### Expected behavior

After I stop `while true; do curl -s localhost:3000 -o /dev/null; done` used memory should go down, but even after many hours it still same like 30 -> 500 mb and it should go back to 30 or ideally not go beyond 100 at all with playground setup.

### How often does this bug happen?

Every time

## DevTools

<img width="779" alt="image" src="https://user-images.githubusercontent.com/25141263/233288079-b36ad963-d1b0-4a98-976c-ad22970158a8.png">

## Production log

![image](https://user-images.githubusercontent.com/25141263/233290559-93b0673d-4206-427e-b874-8e8534c0238d.png)

In production hydration is used but it doesn't seem to related.

### Platform

AWS

### Tanstack Query adapter

vue-query

### TanStack Query version

v4.29.1

### TypeScript version

v4.1.5

**Comment by DamianOsipiuk** [comment]
@gridmaniac Yeah, it seems that `Nuxt 2` does not call `onScopeDispose` in the components. Therefore we are not `unsubscribing` from the observers. This is behavior difference since as you noticed it does not leak in `Nuxt 3`.

I think the same fix/check as we did here, should be added in all places where we `subscribe` to Observers - https://github.com/TanStack/query/pull/5015/files

Since we have to `await suspense()` on the server anyway, it should not have any negative effect.

**Comment by gridmaniac** [comment]
@DamianOsipiuk thank you for explaining the details of the problem!
To be honest when I saw `client.mount()` before with `isServer` check, I don't understand how this line helps releasing `vue-query` resources. And why shouldn't we call it on server in first place?

**Comment by DamianOsipiuk** [comment]
@gridmaniac Should be fixed in https://github.com/TanStack/query/releases/tag/v4.29.13

**Comment by escaton** [comment]
@DamianOsipiuk any chance you remember, why did you have to revert these changes later? I'm hitting the same issue, although I'm not using nuxt, my onscopedispose is not called either (seems default vue 3 SSR behavior). Any advice?

**Comment by DamianOsipiuk** [comment]
@escaton This fix caused a regression in nuxt 3 https://github.com/TanStack/query/issues/5592

**Comment by escaton** [comment]
@DamianOsipiuk I see, but then, what to do with the hanging query observers in vanilla, non-nuxt app?

**Comment by DamianOsipiuk** [comment]
Use [effectScope](https://vuejs.org/api/reactivity-advanced.html#effectscope)  or direct methods on QueryClient.

Potentially would be easier with an example of leaking code.

**Comment by escaton** [comment]
Let me create a new issue for that
