### ISSUE TITLE
when first  exec invalidateQueries is not work with  post method 

### ISSUE THREAD

**Issue by vaynevayne** [TanStack/query#5298]
### Describe the bug

// refresh page , gameId  is '' , send request 
// changed gameId, nothing happend ❌

```jsx
useDidUpdate(() => {
console.log(gameId)// // here is correct  ✅
    queryClient.invalidateQueries({
      predicate: (query) => {
    
        return ['/report_data'].some((str) =>
          query.queryKey[0]?.startsWith?.(str)
        )
      },
    })
  }, [gameId, timezone, attribution]) 

const {

  } = useQuery({
    queryKey: ['/report_data/table', fetchDataOptions],
    queryFn: () => axios.post('/report_data/table', { ...fetchDataOptions }),
    keepPreviousData: true,
    enabled: gridReady && !isEmpty(fetchDataOptions.data_table_options.columns),
  })
```

### Your minimal, reproducible example

https://codesandbox.io/s/new

### Steps to reproduce

for invalidateQueries , The post request will not be re-executed

### Expected behavior

exec report_data/table request, even if it ie post method 

### How often does this bug happen?

None

### Platform

macos chrome

### Tanstack Query adapter

None

### TanStack Query version

4.29.3

**Comment by TkDodo** [comment]
I don't understand the question / problem. Please provide a reproduction. I hope the link to https://codesandbox.io/s/new is just a mistake :)

**Comment by vaynevayne** [comment]
replace  `queryFn: () => axios.post()` to  `queryFn: () => axios.get()`
 
 I write a demo to reproduce and I tell you the steps to reproduce. The difference is only in who writes demo. You must have a lot of templates over there, which can be used as soon as possible. It's much easier than me.
Besides, the cost I paid was to find this bug and make it come back. Isn't that enough?

**Comment by vaynevayne** [comment]
this simple to reproduce it   if you  try and actually  not reproduce  i can  provide  demo .do you  agree?

**Comment by TkDodo** [comment]
the deal is always that if you want a maintainer to look into an issue that you have, you write the demo, because you know what the bug is.

if you want to start from a template, look at: https://tanstack.com/query/v4/docs/react/examples/react/simple

**Comment by TkDodo** [comment]
feel free to re-open with a reproduction
