### ISSUE TITLE
invalidate infinite queries is too fast with use mutation hook

### ISSUE THREAD

**Issue by ccreusat** [TanStack/query#5324]
### Describe the bug

Hello,

Dependencies : 
`"react": "18.2.0"`
`"vite": "4.1.1"`
`"@tanstack/react-query": "4.26.1"`

Let me explain what I'm trying to do : 
- Fetching data with the use `useinfinitequery` hook 🆗 
- I need to delete a resource and I use `useMutation` hook 🆗 
- I call `invalidateQueries` to refetch the data `onSuccess` but it doesn't update...

hacks:
- I have to invalidate again through `ReactQuery` devtools
- I have to refresh my page...
- I have to CTRL+S in my IDE (VSCode), Hot Reload (ViteJS) will do the trick...

When I use the mutation, my request to delete the resource is sent and the invalidateQueries too.. I'm thinking it's happening too fast because if I call `invalidateQueries` inside a setTimeout of 1000ms it's working.

Is it possible to wait the server ?
Is it normal ?
Do I have to perform optimistic update and not waiting for the server ?
Is `invalidateQueries` needs to be await ? (async / await)

🙏🏼  Thank you for your help !

### Your minimal, reproducible example

.

### Steps to reproduce

```
const { data, isLoading, fetchNextPage, isFetching } = useInfiniteQuery({
    queryKey: [
      "context",
    ],
    queryFn: async () => await fetchData,
    getNextPageParam: (lastPage) =>
      lastPage.pagination.startIdx + lastPage.pagination.pageSize ?? undefined,
  });
```

useMutation hook : 
```
const deleteFolder = useMutation({
  mutationFn: async () => await deleteFolder(params),
  onSuccess: () => queryClient.invalidateQueries(["context"]),
});
```

Using `deleteFolder`:

`<button onClick={() => deleteFolder.mutate()}>Delete Folder</button>`

> params comes from local state and gives one or many IDs to delete resource(s)

If I add the setTimeout, it's working but I don't like this hack..

```
const deleteFolder = useMutation({
  mutationFn: async () =>
    await deleteFolder(params),
  onSuccess: () => {
    setTimeout(async () => {
      return await queryClient.invalidateQueries(["context"]);
    }, 1000);
  },
});
```

### Expected behavior

When `invalidateQueries` is called after the mutation, I fetch the correct updated data..

### How often does this bug happen?

Every time

### Platform

OS: MacOS Ventura 13.1
Chrome: 112

### Tanstack Query adapter

react-query

### TanStack Query version

4.26.1

### TypeScript version

4.9.5

### Additional context

ViteJS : 4.1.1
React : 18.2.0

**Comment by clementcreusat** [comment]
Update : 
With optimistic update on `onSuccess`, I will not use `invalidateQueries` because it refetch the previous data.. I think there is something wrong or some pending time between mutation request on server and refetch...

So just doing optimistic update without invalidate works. It updates my data and if I come back or refresh my page, data is up to date..

Would be nice to know if I'm doing something wrong or not with `invalidateQueries`... here is the latest example : 

```
const [params, setParams] = useState({...});

const queryKey = ["context"];
const createFolder = useMutation({
    mutationFn: async () =>
      await createFolder(params),
    onSuccess: async (data) => {
      await queryClient.cancelQueries({ queryKey });
      const previousData = queryClient.getQueryData<ISearchResults>(queryKey);

      if (previousData) {
        return queryClient.setQueryData<
          InfiniteData<ISearchResults> | undefined
        >(queryKey, (prev) => {
          if (prev) {
            return {
              ...prev,
              pages: prev?.pages.map((page) => {
                return {
                  ...page,
                  folders: [...page.folders, data],
                };
              }),
            };
          }
          return undefined;
        });
      }
    },
    onSettled: () => {
      console.log("settled, invalidating");
      // queryClient.invalidateQueries({ queryKey });
    },
  });
```

**Comment by TkDodo** [comment]
I think we discussed this somewhere else and the problem was something with the backend. This can happen if the mutation succeeds, but the backend hasn't finished updating yet. It's not an issue with react-query. If I'm wrong, please provide a runnable reproduction that shows the issue.

**Comment by ccreusat** [comment]
Hello!

Yeah you're right. I was thinking the same it is because of backend and I wasn't saying something was wrong with react query.

But I was looking for help, or any advice about a better implementation. 

For the moment, I did optimistic UI using `setQueryData` but what do you think @TkDodo about a setTimeOut in the `onSettle` or any other practice?

Thank you

**Comment by TkDodo** [comment]
I would say: fix the backend 😅

**Comment by clementcreusat** [comment]
Right answer ! I will see with a backend developer but I think we have this delay because ingest time of elasticsearch... Thank you for your time
