### ISSUE TITLE
`InfiniteQueryObserver` overrides `behavior` passed through `options`

### ISSUE THREAD

**Issue by DanielGiljam** [TanStack/query#5331]
### Describe the bug

When passing a `behavior` passed through `options` to `InfiniteQueryObserver` like this:

```js
new InfiniteQueryObserver(client, {behavior: customBehavior});
```

…it's overridden in `InfiniteQueryObserver`'s `setOptions` method:

https://github.com/TanStack/query/blob/b369b6c9fd289b66646c53b793785c9c0899497d/packages/query-core/src/infiniteQueryObserver.ts#L70-L87

### Your minimal, reproducible example

https://codesandbox.io/s/old-cdn-u1sims?file=/src/App.js

### Steps to reproduce

1. Open the [reproducible example](https://codesandbox.io/s/old-cdn-u1sims?file=/src/App.js) in CodeSandbox.
2. Open the dev console.
3. Witness that the `customBehavior` is not applied.
    - It doesn't say "Hello from my custom behavior!" in the dev console.

### Expected behavior

As a developer, I expect my custom behavior to be applied, instead I'm seeing that my custom behavior is not applied.

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Chrome
- Version: 112.0

### Tanstack Query adapter

None

### TanStack Query version

v4.28.0

**Comment by TkDodo** [comment]
I don't think the `behavior` option is a public api - it's something that we pass around internally to distinguish an infinite query from a normal query. For example, `getOptimisticResult` won't work either:

https://github.com/TanStack/query/blob/cb76da3b0cf7b659401b4a91e3bebfce1b026ab8/packages/query-core/src/infiniteQueryObserver.ts#L103-L107

I'm not sure it's intended that _you_, as a user, create a custom behavior. What are you trying to achieve with that?

**Comment by DanielGiljam** [comment]
I'm trying to extend `InfiniteQueryObserver` for some special use cases, similar to how `InfiniteQueryObserver` extends `QueryObserver` for the pagination use case. It's very much in the experimentation phase, and I currently resorted to achieving the desired functionality in a different way, but here's a link to what I'm experimenting with if you're curious to see what it's about: https://github.com/DanielGiljam/tanstack-query-with-orbitjs/blob/987cfbc2bf3d43f744621a67c889f16ab12d6b7e/libs/tanstack-query-with-orbitjs/src/LiveQueryObserver.ts

Also, there's a quirk with `infiniteQueryBehavior` which could be addressed by applying another `behavior` on top of it. The quirk is that if you update query cache for an infinite query while the infinite query is in-flight (currently fetching), then, when the infinite query resolves, the updates you made while the query was in-flight might be undone.

This is due to `infiniteQueryBehavior` "snapshotting" the pages when it starts fetching the next page and then the "snapshotted" pages + the next page gets put into cache when fetching the next page has resolved. So if existing pages in cache have been changed while the next page was being fetched, those changes will get overwritten.

Of course, you could cancel and refetch next page always when encountering that the next page is being fetched but you want to update existing pages in cache (you can see me doing it [here](https://github.com/DanielGiljam/tanstack-query-with-orbitjs/blob/987cfbc2bf3d43f744621a67c889f16ab12d6b7e/apps/example-chat-app-with-tanstack-query/src/query/cache-updaters/onNewChatMessage.ts#L25-L36)), but if it's a rapidly changing dataset and fetching is slow, then the next page will never "get a chance" to finish fetching if it's constantly being interrupted.

Ideally, if there was a way to "merge" the items in the next page with whatever exists in the query cache for that query at the time when fetching the next page resolves. I was trying to achieve this by passing a custom `behavior` to `InfiniteQueryObserver`. I assumed it was a "semi-public" API since it was exposed in the `QueryObserverOptions` interface, which users interact with all the time.

(My temporary solution for the `infiniteQueryBehavior` quirk is [this patch](https://github.com/DanielGiljam/tanstack-query-with-orbitjs/blob/987cfbc2bf3d43f744621a67c889f16ab12d6b7e/patches/%40tanstack__query-core%404.26.1.patch).)

**Comment by TkDodo** [comment]
> The quirk is that if you update query cache for an infinite query while the infinite query is in-flight (currently fetching), then, when the infinite query resolves, the updates you made while the query was in-flight might be undone.

yes, that's because you can only have one thing: data that was fetched from the server _or_ data that you write to the cache manually. Usually, data from the server is "correct", because the state is owned by the server. The two ways I would solve this are:

- cancelling the query _before_ you write to it. We do this in our optimistic update examples.
- don't refetch the query (set a high staleTime) if you plan to write to the queryCache manually frequently. This seems like what you'd want when building a chat application. If a websocket sends data down and you want to treat that data as source of truth and write it to the cache - why would you want to refetch?

**Comment by DanielGiljam** [comment]
I tried cancelling the query before I write to it (like in the optimistic update examples), but somehow I still experienced that the `pages` occasionally were "corrupted" (contained duplicates, last item in page 1 same item in page 2). Could it be my usage of `cancelQueries`? I'm a bit unsure about how it's supposed to be used and why it returns a `Promise`. Can I rely on the cancellation being in effect immediately after the calling the function or must I wait until the `Promise` has resolved before I can be sure that cancellation is in effect? (Should I `await` it or `void` it?)

I wouldn't necessarily want to refetch, but I would like to fetch more pages. Socket informs about new messages, but when the user scrolls to the end of the messages list, an additional page of old messages are fetched from REST API endpoints.

But sometimes I would like to refetch too. For example, I don't want to keep the socket connection alive continuously if the tab is in the background. So I usually close the connection after `x` amount of time of tab being in background and then, upon tab coming to foreground again, I want to refetch since now there's been a gap in time when the app wasn't connected to socket and didn't get to know about new messages.

**Comment by TkDodo** [comment]
> Could it be my usage of cancelQueries? I'm a bit unsure about how it's supposed to be used and why it returns a Promise

it returns a Promise so that you can await it. Internally, we reject the Promise with a `CancelledError`, catch it and revert the Query to its previous state.

I'm sorry that you're having some troubles with infinite queries, but trying to make your own QueryBehaviour, which is an undocumented and somewhat private api, is not the way to go.

I can take a look at your issue if you can show a standalone codesandbox reproduction please.
