### ISSUE TITLE
When passing a custom behavior in `options.behavior` to the `InfiniteQueryObserver` constructor, an invalid `"observerOptionsUpdated"` event is fired

### ISSUE THREAD

**Issue by DanielGiljam** [TanStack/query#5336]
### Describe the bug

When passing a custom behavior in `options.behavior` to the `InfiniteQueryObserver` constructor, an invalid `"observerOptionsUpdated"` event is fired.

This issue is related to https://github.com/TanStack/query/issues/5331.

The cause for this issue is that now the following block in `QueryObserver#setOptions` will run (`!shallowEqualObjects(...)` will evaluate to `true`)…

https://github.com/TanStack/query/blob/1614c31f84744c62b5bee8f2ff97fc15a1652e86/packages/query-core/src/queryObserver.ts#L169-L175

…since `prevOptions.behavior` now refers to a different object than `this.options.behavior` and `shallowEqualObjects` returns false if any of the first argument's properties differ from the second argument's corresponding properties (it ignores additional properties on the second argument which don't exist on the first argument).

`this.currentQuery` has not been assigned yet when `setOptions` is called for the first time from the constructor, so `event.query` ends up being `undefined`, which is unexpected since the `QueryCacheNotifyEvent` interface defines `query` as  always being defined.

### Your minimal, reproducible example

https://codesandbox.io/s/dank-resonance-7jsurp?file=/src/index.ts

### Steps to reproduce

1. Open the [reproducible example](https://codesandbox.io/s/dank-resonance-7jsurp?file=/src/index.ts) in CodeSandbox.
4. Witness error "Cannot read properties of undefined (reading 'queryHash')".

### Expected behavior

As a developer, I expect `query` to always be defined as the `QueryCacheNotifyEvent` interface suggests, but I am seeing that in this particular case, it will be `undefined`.

### How often does this bug happen?

Every time

### Platform

- OS: N/A
- Browser: N/A
- Version: N/A

### Tanstack Query adapter

None

### TanStack Query version

v4.27.0

**Comment by TkDodo** [comment]
instead of opening new issues about `behavior`, can you please answer the question what you are trying to do with it first?

- https://github.com/TanStack/query/issues/5331#issuecomment-1527234478
