### ISSUE TITLE
react query useQueries doesn’t accept an abort signal

### ISSUE THREAD

**Issue by jasikpark** [TanStack/query#5342]
### Describe the bug

The types for useQueries in the react query alpha doesn’t accept an abort signal handler to be passed to the query function. 

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1WO1OAXzgDMoIQ4ByAARgEMA7VRgYwGsB6KdBtmAFoAjjigBPagFgAULLhsILeL1TIANvAC8KDNlz5UACgTy450QYIAuOAG0z586ZlO3cSxIDS6cbbvUpBAQ1AC6ADSO7p7iAGJMtiZwqMAA5kwM6sQAlHBaAHxwAAoUIMAYAHSqEOoAbuhGgcHU2ZGu7kRtbhFmRNkA3EA

### Steps to reproduce

Run the ts playground

### Expected behavior

I expected useQueries to accept query configs that are the same as a useQuery config. 

I would really like for #5153 to support creating a query config that can be passed to useQuery *or* useQueries

### How often does this bug happen?

Every time

### Platform

macOS, Arc

### Tanstack Query adapter

react-query

### TanStack Query version

v5.0.0-alpha.21

### TypeScript version

v5.0.4

**Comment by TkDodo** [comment]
FYI, this issue exists in v4 as well, it's not v5 related.

@artysidorenko if you find some time, please take a look

**Comment by artysidorenko** [comment]
Hi - this one is also related to the current TS limitations when trying to infer callback parameters nested in a tuple type.

It was mentioned in the discussion forum, with a workaround: https://github.com/TanStack/query/discussions/4785#discussioncomment-4695929
