### ISSUE TITLE
useQueries doesn't correctly infer the type of onSuccess (but useQuery does)

### ISSUE THREAD

**Issue by merisbahti** [TanStack/query#5359]
### Describe the bug

the first parameter in `onSuccess` for a query in `useQueries` is not correctly inferred.
```typescript
useQueries({
    queries: [
      {
        queryKey: ["a"],
        queryFn: () => Promise.resolve({ a: 1 }),
        onSuccess: (a) => { // `a` implicitly has any type
         }
      }
    ]
  });
```

### Your minimal, reproducible example

https://codesandbox.io/s/competent-sea-36hiky?file=/src/App.tsx

### Steps to reproduce

1. Open the CSB
2. Hover the `a` parameter in the `useQueries` call

### Expected behavior

I expect it to behave the same way it works in `useQuery`, like this:

```typescript
  const working = useQuery({
    queryKey: ["a"],
    queryFn: () => Promise.resolve({ a: 1 }),
    onSuccess: (a) => {
      a; // correct type!!!
    }
  });
```

### How often does this bug happen?

Every time

### Platform

Independent (it's a typescript type thing)

### Tanstack Query adapter

None

### TanStack Query version

4.28

### TypeScript version

4.7.4

**Comment by TkDodo** [comment]
it's a known limitation. Also, callbacks on queries will be removed in v5:

- https://github.com/TanStack/query/discussions/5279
