### ISSUE TITLE
Can't install @tanstack/vue-query, conflict peer dependencies

### ISSUE THREAD

**Issue by dexter-fabrikapp** [TanStack/query#5368]
### Describe the bug

Conflicting peer dependencies
![image](https://user-images.githubusercontent.com/129273463/236162313-44d6e1cc-f79e-4a1f-9719-9a7f48493ab3.png)

### Your minimal, reproducible example

n/a

### Steps to reproduce

npm install @tanstack/vue-query

### Expected behavior

It should install @tanstack/vue-query

### How often does this bug happen?

None

### Platform

OS: Windows
"nuxt": "^3.3.0",
"@nuxtjs/i18n": "next",

### Tanstack Query adapter

vue-query

### TanStack Query version

v4.26.1

**Comment by KieranSunshine** [comment]
If it's any help, I ran into this same error whilst upgrading to v4.29.7.

I resolved it by upgrading Vue to v3.3.2, as well as updating the dependencies listed in their [blog post](https://blog.vuejs.org/posts/vue-3-3).

**Comment by DamianOsipiuk** [comment]
There is nothing we can do about this at this point besides dropping support for Vue2, which is not a solution to be honest.  
We properly mark `peerDependecies` as optional and package manager heuristics is out of our control.

**Comment by coaben2** [comment]
"@tanstack/vue-table": "^8.12.0",
"vue": "^3.3.11",
not working

**Comment by andre-brdoch** [comment]
Are you using yarn? We are experiencing the same. It could be an issue with yarn not handling `peerDependenciesMeta` properly (that package.json field you use to add optional peer dependencies).

**Comment by chaitanyapotti** [comment]
@DamianOsipiuk vue 2 is now fully deprecated.
```
Vue 2 has reached End of Life on December 31st, 2023. It no longer receives new features, updates, or fixes. However, it is still available on all existing distribution channels (CDNs, package managers, Github, etc).
```
Can we now drop support for vue 2 and remove this peer dep?

**Comment by TkDodo** [comment]
> Can we now drop support for vue 2 and remove this peer dep?

Not without a new major version

**Comment by DamianOsipiuk** [comment]
@chaitanyapotti As mentioned we need new `major` release to do that. 

Besides a problem with peer deps, there are no other major issues that would push us to drop vue 2 right now.
