### ISSUE TITLE
QueryClient not found in '@tanstack/react-query'

### ISSUE THREAD

**Issue by kenbankspeng** [TanStack/query#5377]
### Describe the bug

I installed TanStack Query and imported QueryClient as per QuickStart. 

import {
  QueryClient,
  QueryClientProvider,
  useQuery,
} from '@tanstack/react-query'

But builds with error: QueryClient not found in '@tanstack/react-query'

Inside /node_modules/@tanstack/react-query under src and build/lib I see QueryClientProvider, useQuery, etc. but not QueryClient.

### Your minimal, reproducible example

n/a

### Steps to reproduce

1. pnpm add @tanstack/react-query
2. import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

### Expected behavior

No error.

### How often does this bug happen?

Every time

### Platform

macOS Chrome 113.0.5672.63

### Tanstack Query adapter

react-query

### TanStack Query version

v4.29.5

### Additional context

Installed using pnpm

**Comment by kenbankspeng** [comment]
work around: 
1. add `public-hoist-pattern[]=!@tanstack` into .npmrc file
2. remove node_modules
3. pnpm install
4. import { QueryClientProvider, useQuery } from '@tanstack/react-query'
5. import { QueryClient } from '@tanstack/query-core'

**Comment by TkDodo** [comment]
> Inside /node_modules/@tanstack/react-query under src and build/lib I see QueryClientProvider, useQuery, etc. but not QueryClient.

I do see it on my project:

![Screenshot 2023-05-08 at 11 37 27](https://user-images.githubusercontent.com/1021430/236790735-a0d32cf8-7717-468d-a5f4-599346b94f01.png)

So, without a reproduction, there isn't much we can do.

**Comment by kenbankspeng** [comment]
The reproduce scenraio is to install with pnpm option referenced in tanstack docs. Was your installation performed using pnpm?  The reproduce scenario provided is very direct.

**Comment by kenbankspeng** [comment]
Another option is just to change the install docs to indicate that tanstack query does not support pnpm or that it requires the prpovided workaround.

**Comment by kenbankspeng** [comment]
Looking at the snapshot of your install, I also do not see QueryClient there either. I see that /build/lib/index.js is processing queryCore dynamically which seems to go beyond the static linting capability of eslint (import/named).

// eslint-disable-next-line import/named
import { QueryClientProvider, QueryClient } from '@tanstack/react-query';
