### ISSUE TITLE
Unable to Find All External Library Modules in VSCode + Yarn Berry + Yarn Workspace + @tanstack/react-query 4.x

### ISSUE THREAD

**Issue by baekkyoungjung** [TanStack/query#5379]
### Describe the bug

Hey there,

I hope this message finds you well. I've come across an issue that I'd like to share with you.

In a nutshell, we're facing a problem where external library modules cannot be found in the VSCode + Yarn Berry + Yarn Workspace + @tanstack/react-query 4.x combination.

As a frontend developer, I'm currently using @tanstack/react-query in our project. Our setup involves Yarn Berry with Yarn Plug 'n' Play (PnP), and we have multiple monorepos within our repository. Here are some key details about our environment:

Yarn version: 3.4.1
Next.js version: 13.0.6
React version: 18.2
TypeScript version: 4.9.5
VSCode version: 1.78.0
@tanstack/react-query version: 4.29.5
@tanstack/react-query-devtools version: 4.29.6

We recently migrated from react-query 3.x to @tanstack/react-query 4.x and successfully deployed the new version. Our users are happily using it as intended without any issues.

However, there's a significant problem we encounter during development. Since most of our team members prefer using VSCode, allow me to explain the situation using a example:

Imagine we have two repositories, "A" and "B." Now, let's say we open the following files in VSCode:

/apps/a/index.ts from repository A
/apps/b/index.ts from repository B
In this scenario, if we start indexing the "a.ts" file, the import paths within repository A work perfectly fine. However, all external libraries located in repository B suddenly become elusive, resulting in a frustrating "cannot find module" error.

Conversely, if we restart VSCode and index the "b" repository's file first, all TypeScript files within repository A fail to locate the paths for external libraries.

We've made sure to upgrade TypeScript 5.x, Yarn 3.5.x, Yarn's SDKs (via yarn dlx @yarnpkg/sdks), and even VSCode to their latest versions, but the problem persists. Interestingly, when we downgrade to react-query 3.x, all the issues disappear. However, we are determined to stick with @tanstack/react-query 4.x and continue using the latest version.

While it could be considered a potential issue with VSCode, it's evident that the problem arises only with @tanstack/react-query 4.x. It's worth noting that we don't face any issues when using WebStorm. With that said, if you have any similar experiences or insights regarding this issue, we would be extremely grateful for your assistance. The current situation has caused significant mental stress for our team of nine.

Thank you for taking the time to read this message, and we genuinely hope you can help us out.

Best regards, Tanstack

### Your minimal, reproducible example

Issues in the development environment

### Steps to reproduce

In other monorepos excluding the repository where indexing initially starts, installed modules cannot be found (imported), and type inference is not possible.

### Expected behavior

Regardless of any monorepo, module imports and type inference should work in all repositories.

### How often does this bug happen?

Every time

### Screenshots or Videos

![repo_a](https://user-images.githubusercontent.com/13829336/236794485-7ab97cde-3bd3-445f-870d-fbf7702cc46c.jpg)
After running vscode, the first repository that is indexed works fine.

![repo_b](https://user-images.githubusercontent.com/13829336/236794522-e8e3bc89-60fb-4639-8d73-2514adc1a9b8.jpg)
However, in all other repositories opened after that, the import paths cannot be found correctly.

It is not just a problem specific to repositories like A, B, C, but only the repository that vscode reads first works, and the rest of the repositories do not work.

### Platform

- OS: macOS
- Yarn version: 3.4.1
- Next.js version: 13.0.6
- React version: 18.2
- TypeScript version: 4.9.5
- VSCode version: 1.78.0
- @tanstack/react-query version: 4.29.5
- @tanstack/react-query-devtools version: 4.29.6

### Tanstack Query adapter

react-query

### TanStack Query version

4.29.5

### TypeScript version

4.9.5

**Comment by Gyejoon** [comment]
I hope this issue gets resolved.

**Comment by TkDodo** [comment]
> external library modules cannot be found in the VSCode + Yarn Berry + Yarn Workspace + @tanstack/react-query 4.x combination.

We cannot analyze this without a proper, standalone, minimal reproduction. Please provide an open source repo with this setup that clearly shows the errors you're facing. I will re-open the issue once that is provided.
