### ISSUE TITLE
useMutation mutate function does not call onSucces on first slow item when fired twice

### ISSUE THREAD

**Issue by Jimmy89** [TanStack/query#5383]
### Describe the bug

I have a useMutation function that calls the server in one of two ways, depending on the type of resource provided.
One call is slow, one call is fast. Both calls starts almost at the same time.
If I call useMutation with the `mutate` function, containing a `onSuccess` function. The `onSucces` function is not called for the first slow call, only for the fast second call.

### Your minimal, reproducible example

https://codesandbox.io/s/eloquent-cloud-dv8uwl?file=%2Fsrc%2FApp.js

### Steps to reproduce

In the codesandbox link you find an object with a `onSuccess` method. The function should be called twice (for the fast and slow call), but is only called once for the fast call (like the description within the code says).

### Expected behavior

If a onSuccess method is send with the mutate function, the onSuccess method should always be called.

### How often does this bug happen?

Every time

### Platform

OS: Windows 11. Firefox 112.0.2

### Tanstack Query adapter

react-query

### TanStack Query version

4.28.0

**Comment by TkDodo** [comment]
The callbacks on `mutate` are only called for the last invocation. That is on purpose. The callbacks on `useMutation` are called every time.

This is documented here: https://tanstack.com/query/v4/docs/react/guides/mutations#consecutive-mutations
