### ISSUE TITLE
fusing getQueriesClient with useQueries()

### ISSUE THREAD

**Issue by aggarwal-muskaan** [TanStack/query#5388]
### Describe the bug

We are getting undefined when fetching the cached data via the getQueriesClient() hook with the same queryKey used inside useQueries({queries:....})

### Your minimal, reproducible example

export const useGetStudentCourses = ({     courses = [],     payload = {},     options = {}, }) => {     const results = useQueries(         {             queries: courses.map((el) => {                 let payloadObj = {                     psid: payload.psid,                     courseCode: el.id,                 }                 return {                     queryKey: [`studentCourseData`],                     queryFn: () => getCourseData(payloadObj),                 }             }),

### Steps to reproduce

1. make API calls using useQueries hook
2. try to access the data with the same queryKey given inside useQueries() hook in queryClient.getQueriesData()
3. I'm getting undefined for the above step whereas it should fetch the data returned by useQueries() hook

### Expected behavior

We are getting the object populated with the data returned from the custom hook where the useQueries() call is made whereas the same data is not getting fetched when we use queryClient.getQueriesData().

### How often does this bug happen?

None

### Platform

OS : Windows
Browser : Brave

### Tanstack Query adapter

None

### TanStack Query version

v4.28.0

**Comment by TkDodo** [comment]
please show a minimal, run-able reproduction.
