### ISSUE TITLE
different type in onSuccess

### ISSUE THREAD

**Issue by behnamshojaei99** [TanStack/query#5392]
### Describe the bug

my query function returns an Axios promise and i expect the result in the onSuccess callback is an Axios response, but it returns the type of data in Axios response.

my fetcher type for queryFn: 
![image](https://github.com/TanStack/query/assets/44582167/e6f6adae-fa5f-4800-bc7b-821955cee0a2)

return type in result onSuccess: 
![image](https://github.com/TanStack/query/assets/44582167/44bc4d27-65f2-4fca-9073-c3134038c8c7)

in type declaration TData is equal to queryFn but it's not

### Your minimal, reproducible example

.

### Steps to reproduce

1. pass an axios promise to queryFn
2. check type of onSuccess callback

### Expected behavior

i expect returns Axios Response. 

### How often does this bug happen?

Every time

### Platform

- OS: windows
- Browser: chrome

### Tanstack Query adapter

vue-query

### TanStack Query version

4.29.5

### TypeScript version

4.9.4

**Comment by TkDodo** [comment]
1) This works, see [this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAQwB7AgZzgMyhEcDkyqa+AsAFCiSxwDecArmgKYCKDzUAnnAL5Y48+AAIwEAOzRiAxgGsA9FGYJpMALQBHDtzLkKMLmGZwAYhAhwAvHTjAAJgC44UqMHEBzADRxxCEMycXN3c+CgppCEl4TGYYaQALMwtrAAoASicABUFgFgAeJIA+K2LaCjgKuCUYBihxRBR0ADp3WJT8eUxzfDSmmHjmcRSlNEhJY0tikbGWJrsEMUQMJLSKXjDyJjZtLhSy8kq4LU4uAGlmLicAbXwuiHwAXU9yyuPuE3EnGLjE82eDyqRADKDGk0mYaDQThS8zEaRKdBehwqEUkEAANswmuiIO4YQsEKsAci4PJ5CTDgA9AD8SNC5F4aSAA)
2) It's actually _your_ responsibility to provide the playground. Please keep that in mind next time
3) `onSuccess` is deprecated, see the RFC:
- https://github.com/TanStack/query/discussions/5279
