### ISSUE TITLE
Error running in production - @tanstack/react-query-devtools module not found

### ISSUE THREAD

**Issue by brett-james-rocketlab** [TanStack/query#5398]
### Describe the bug

When I run a nextJS install, I get an error in production where the d

According to the docs, this should not be a problem:
https://tanstack.com/query/v4/docs/react/devtools#:~:text=so%20you%20don%27t%20need%20to%20worry%20about%20excluding%20them%20during%20a%20production%20build.

However when I run it in production mode (node_env = production), it crashes.

`Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@tanstack/react-query-devtools' imported from /var/app/current/.next/server/pages/_app.js`

The reason this comes up is because   "devDependencies": {
    "@tanstack/react-query-devtools": "^4.29.6",
}
And it doesn't exist in the dependencies by default

### Your minimal, reproducible example

Production only, hard to show in dev sandboxes

### Steps to reproduce

Create a barebones nextjs app, add in react query devtools as such:

```
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import type { AppProps } from 'next/app'

export const queryClient = new QueryClient()

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <QueryClientProvider client={queryClient}>
       <ReactQueryDevtools initialIsOpen={false} />
      <Component {...pageProps} />
    </QueryClientProvider>
  )
}
```
Now build, and start that application (as in npm run start )

### Expected behavior

I would expect it to work on production  with no need to change or remove that code.

### How often does this bug happen?

Every time

### Platform

OS: Mac/Linux
Node v18.12.1

### Tanstack Query adapter

react-query

### TanStack Query version

4.29.1

### TypeScript version

v4.9.4

### Additional context

I wasn't able to make a sandbox that ran in production mode. You won't see this when you run as npm run dev, nor if you do it locally (npm install, npm run build, npm run start), because the run start will still have the modules from devDependancies there to use (and skip). It breaks on new installs.

**Comment by TkDodo** [comment]
add them as a dependency and not a devDependency.

**Comment by brett-james-rocketlab** [comment]
Thanks, this was the solution.

**Comment by brett-james-rocketlab** [comment]
closing.
