### ISSUE TITLE
Type narrowing not working in vue 3 template

### ISSUE THREAD

**Issue by dili021** [TanStack/query#5418]
### Describe the bug

The type narrowing is not working as described in the docs. I am wrapping some content in the template with a `v-if="isSuccess"` returned from useQuery, but I still have to optionally chain properties inside that if block.

### Your minimal, reproducible example

https://codesandbox.io/s/brave-star-guyu40?file=/src/App.vue

### Steps to reproduce

1. visit example link
2. hover over `data` inside the if statement

### Expected behavior

expected: type of returned data is narrowed by the success status, as is shown in the docs
![image](https://github.com/TanStack/query/assets/55356496/f298ea7f-0b53-441b-8a2e-96360897e69e)

actual: type is not narrowed

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/55356496/8c2b30eb-28ae-4ded-9fa6-49a254d9c0a9)

![image](https://github.com/TanStack/query/assets/55356496/8a126b4f-211a-4214-b568-e661f73a534e)

### Platform

Windows, Brave browser

### Tanstack Query adapter

vue-query

### TanStack Query version

4.29.5

### TypeScript version

4.5.4

**Comment by DamianOsipiuk** [comment]
Unfortunately this is a limitation with current Vue type-checking.

You can wrap result of `useQuery` with `reactive` and avoid destructuring to get the proper type inference.
