### ISSUE TITLE
The useQuery setting of staceTime does not work, and requests will be reissued within the expiration time

### ISSUE THREAD

**Issue by 51wangping** [TanStack/query#5434]
### Describe the bug

When using useQuery, set the StaleTime expiration time to 5 * 60 * 1000. If the data is considered fresh within 5 minutes, the request should not be reissued during refresh.
If it takes 5 minutes for a refresh to be initiated, within 5 minutes, the cached data will be used directly without initiating the request. This is the correct way.

### Your minimal, reproducible example

https://codesandbox.io/embed/antd-datepicker-bug-forked-8h4qyz?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce

https://codesandbox.io/embed/antd-datepicker-bug-forked-8h4qyz?fontsize=14&hidenavigation=1&theme=dark

### Expected behavior

If it takes 5 minutes for a refresh to be initiated, within 5 minutes, the cached data will be used directly without initiating the request. This is the correct way.

### How often does this bug happen?

Every time

### Platform

Google Chrome 113.0.5672.92 (x86_64)

### Tanstack Query adapter

None

### TanStack Query version

v3.39.3

**Comment by TkDodo** [comment]
in your sandbox, you are using `refetch`. If you programmatically call the `refetch` method, data will be refetched. `staleTime` limits the amount of **automatic** requests that are happening when reading from the cache via `useQuery`.

**Comment by 51wangping** [comment]
> in your sandbox, you are using `refetch`. If you programmatically call the `refetch` method, data will be refetched. `staleTime` limits the amount of **automatic** requests that are happening when reading from the cache via `useQuery`.

I think whether it's manually calling the `refresh` of useQuery or automatically calling `useQuery.` If `staleTime` is set and the request should not be reissued during the freshness period, but rather directly read the data in the cache. It is correct to only reissue the request after the cache has passed.

for example：Using `staleTime` in `useRequest` in books , ou can set the data retention time through options.staleTime. During this time, we consider the data to be fresh and will not re-initiate the request.
 https://ahooks.js.org/hooks/use-request/cache

**Comment by TkDodo** [comment]
you can use `queryClient.fetchQuery` if you want that behaviour. `refetch` is always unconditional.
