### ISSUE TITLE
Potential race condition exists between an observer subscribing to a query and when that query's response comes back

### ISSUE THREAD

**Issue by ericbiewener** [TanStack/query#5443]
### Describe the bug

I am seeing a bug in my application when using mocked network requests (i.e. query fetch requests resolve immediately), resulting from a race condition between these network requests resolving and a component's observer subscribing to the query's changes. Unfortunately, I can not reproduce it outside of our proprietary codebase, so simply demonstrating the theoretical possibility will need to suffice.

Consider two components, `A` and `B`, both of which call `useQuery` with the same `queryKey` (thus sharing the same underlying `Query` instance).

1. `A` calls `useQuery`. This creates a new `Query` instance and the query begins fetching. A receives `isLoading: true` from the hook.
2. `B` calls `useQuery`, sharing the same `Query` instance as `A`, and therefore not executing a new fetch. `B` receives `isLoading: true` from the hook.
3. The `useEffect` hooks for `A` execute, resulting in the query observer for `A` calling `addObserver` on its query (via `useSyncExternalStore`), thus subscribing to query state notifications.
4. The network request resolves, updating the `Query` state and notifying `A` of changes.
5. The `useEffect` hooks for `B` execute, so now `B` is subscribed to query state notifications, _but it does not get notified of the query state updates from the previous step_. **This is the race condition.**
6. `A` re-renders with the updated query state, `B` does not.

This race condition exists because React Query does not control how the JS event loop will schedule the `useEffect` calls vs. the resolution of the network request, since both are happening asynchronously. Of course, the moment any real network latency is added to the network call, the execution of the `useEffect` hooks first is effectively guaranteed. Furthermore, while I can reproduce this dependably in Chrome, I am not able to do so in Firefox, which hints at the role that the JS engine is playing in regards to how the work is being scheduled on the event loop.

Our codebase currently has nearly 1700 testcafe tests, and this edge case bug appeared on only a few, all of which were in the same test suite, thus indicating just how much of an edge case it is.

FWIW, component `B` in our case is a child of component `A`, and is rendered as a Next.js `dynamic` component. I don't see any reason to believe that is relevant beyond it having some random effect on the scheduling of work on the event loop, but in theory so could anything else.

**Solution**
I'd be happy to open a PR to patch this if desired. The solution is fairly simple: the observer needs to subscribe to query notifications _immediately_, rather than waiting until the `useEffect` hooks get executed. Since the `handleStoreChange` function is not available from `useSyncExternalStore` until the `useEffect` hooks are called, however, this initial subscription would just set a flag to indicate that `handleStoreChange` needs to be called once it is available. Such a flag could be implemented as an instance property on the observer or as a ref inside `useBaseQuery`, but regardless it would look something like this:

```ts
const [observer] = React.useState(
  () => {
    const observer = new Observer<TQueryFnData, TError, TData, TQueryData, TQueryKey>(
      queryClient,
      defaultedOptions,
    )
    observer.subscribe(() => {
      observer.needsToFlushStoreChange = true
    })
    return observer
  }
)

useSyncExternalStore(
  React.useCallback(
    (onStoreChange) => {
      if (isRestoring) return () => undefined;
      if (observer.needsToFlushStoreChange) {
        observer.needsToFlushStoreChange = false;
        onStoreChange();
      }

      observer.listeners = []; // Remove `needsToFlushStoreChange` subscription
      return observer.subscribe(notifyManager.batchCalls(onStoreChange));
    },
    [observer, isRestoring]
  ),
  () => observer.getCurrentResult(),
  () => observer.getCurrentResult()
);
```

### Your minimal, reproducible example

N/A

### Steps to reproduce

As described above, I am not able to create a standalone reproduction.

### Expected behavior

I expect all components that call `useQuery` to be subscribed to that query in time to immediately receive state updates.

### How often does this bug happen?

Almost always

### Platform

- OS: OSX 13.3.1, and whatever version of Alpine Linux our CI uses
- Chrome 113.0.5672.126

### Tanstack Query adapter

react-query

### TanStack Query version

4.29.7

### TypeScript version

4.3.2

**Comment by TkDodo** [comment]
> As described above, I am not able to create a standalone reproduction.

Could you try to add a failing test case in our codebase to show the problem?

```
observer.listeners = []; // Remove `needsToFlushStoreChange` subscription
```

this seems wrong because it doesn't clean up the observer correctly. Also, in your solution, you're calling `observer.subscribe` inside `React.useState` initializer, which I think violates the rules of react: we shouldn't have side-effects in there ...

**Comment by ericbiewener** [comment]
Unfortunately I can't add a failing test case because I can't find a way to dependably reproduce the issue.

> it doesn't clean up the observer correctly

Fair enough, I didn't dig too far into what the exactly correct implementation details would be. Hopefully the general approach is still clear enough.

> in your solution, you're calling observer.subscribe inside React.useState initializer, which I think violates the rules of react: we shouldn't have side-effects in there

The instantiation of the `QueryObserver` in `useState` leads to the instantiation of a `Query` object and potentially kicks off a `fetch` request. So side effects are already occurring in `useState`. But... just typing this out made me realize that maybe _this_ is the way the race condition bug should be fixed: don't execute the network request as a side effect in `useState`! Instead, it should start in a `useEffect` hook.

**Comment by TkDodo** [comment]
> The instantiation of the QueryObserver in useState leads to the instantiation of a Query object and potentially kicks off a fetch request. So side effects are already occurring in useState

no, it doesn't kick off a fetch request. I guess it looks like that from the code, because the constructor calls `setOptions`, which can trigger a fetch, but it doesn't in this case, because it only triggers a fetch if it has listeners, which it never has in this situation:

https://github.com/TanStack/query/blob/049e0c6e56c6314f4042e9c4849244a19e311161/packages/query-core/src/queryObserver.ts#L177

the fetches really happen when the `useSyncExternalStore` subscription is triggered, which happens, similar to `useEffect`, _after_ the component has rendered.

**Comment by ericbiewener** [comment]
Got it. Still, I question whether subscribing to the query immediately violates some inviolable rule of React. Does instantiating the query in the first place not constitute some kind of side effect?

**Comment by TkDodo** [comment]
> Does instantiating the query in the first place not constitute some kind of side effect?

No, this is just instantiating a resource, like:

```
const [now] = useState(() => new Date())
```

`new Date()` or `new QueryObserver()` makes no difference

**Comment by ericbiewener** [comment]
Ok, certainly happy for an alternative solution that you deem more appropriate. The main goal of this post was to call out the potential race condition.

**Comment by artem-malko** [comment]
By the way, looks like I had the described problem in my project( I had the same query in three places. Sometimes random query is not notified about changes. I pretty sure about that race condition, cause if I change an inner state of a component with such query, that query will receive the lates state from cache.

**Comment by artem-malko** [comment]
By the way, @TkDodo why do you use useState for observer? Looks like ref here is a better choice.

**Comment by TkDodo** [comment]
Why would ref be a better choice? It has no lazy initializer function so you need more code...

**Comment by artem-malko** [comment]
@TkDodo Looks like observer has a stable link, so it is quite useless to add it to deps arrays) But yeah, it doesn't matter. useState is ok. The real problem is a race condition.

So, right now, to fix my problem I have to do:

```ts
const useSomethingQuery = (...args) => {
  const [,rerender] = useState(0);
  
  // This useEffect is used to refresh query state
  useEffect(() => {
    rerender(Math.random());
  }, [])

  return useQuery(args);
}
```

And it's not bullet proof too, cause the race still can be there( So, what do you think about PR with @ericbiewener fix?

**Comment by TkDodo** [comment]
You can't setup a subscription during rendering (in the useState initializer), I'm pretty sure about that. What might work is `useLayoutEffect`. See this slightly related discussion: https://twitter.com/acemarke/status/1661129572908138496

**Comment by artem-malko** [comment]
So, useLayoutEffect can be ok. So, what do you think? I can do a PR. Or @ericbiewener )

**Comment by TkDodo** [comment]
yeah let's try that with a PR 👍

**Comment by artem-malko** [comment]
@TkDodo is there any docs, how to publish a temp release from a branch just to test it in our project?

**Comment by ericbiewener** [comment]
While `useLayoutEffect` will likely reduce the possibility of a race condition, are we sure that it will fully eliminate the possibility? The docs say that it blocks the browser from repainting, but do we know that it will block the `Query` from notifying its observers?

I understand that not performing side effects outside of `useEffect` or `useLayoutEffect` is a "rule" of React. However, I'm not convinced that it can't be violated under any condition. Furthermore, I'd still argue that side effects are already occurring in the `useState` hook. Why isn't the instantiation of a class instances a side effect? And what about the fact that the Query gets added to the `QueryCache` at that time as well? Ultimately, having a `QueryObserver` that is instantiated in an unsubscribed state seems like the fundamental problem.

**Comment by artem-malko** [comment]
Ok, @ericbiewener @TkDodo https://github.com/TanStack/query/pull/5464 check it out)

**Comment by TkDodo** [comment]
So interestingly, we had this in v3 inside the `useEffect` that sets up the subscription:

https://github.com/TanStack/query/blob/baf722f4943ff1fd9fce970e13eef1817c26e562/src/react/useBaseQuery.ts#L100-L102

But I'm not sure what the `useSyncExternalStore` equivalent of that is. I was thinking that it shouldn't be needed, but it seems the `subscribe` function of uSES also runs potentially too late ... so, maybe this?

```diff
  React.useSyncExternalStore(
    React.useCallback(
      (onStoreChange) => {
        const result = isRestoring
          ? () => undefined
          : observer.subscribe(notifyManager.batchCalls(onStoreChange))

+        observer.updateResult()

        return result
      },

      [observer, isRestoring],
    ),
    () => observer.getCurrentResult(),
    () => observer.getCurrentResult(),
  )
```

?

**Comment by TkDodo** [comment]
I have a failing test and a fix; brace yourselves

**Comment by TkDodo** [comment]
> @TkDodo are there any docs, how to publish a temp release from a branch just to test it in our project?

@artem-malko generally, codesandbox does preview builds. It's just that the bot doesn't seem to be working quite well right now.

what should work is just depending on:

```
"@tanstack/react-query": "https://pkg.csb.dev/TanStack/query/commit/33dacbe/@tanstack/react-query",
```

`33dacbe` is the latest commit from my PR.

**Comment by artem-malko** [comment]
@TkDodo 

> what should work is just depending on:

No, it doesn't work. I have webpack, which says, that `workspace: *` is something unknown for it)

**Comment by TkDodo** [comment]
workspace:* dependencies should've been replaced during build 🤔
