### ISSUE TITLE
eslint exhaustive-deps labelling constant values in external functions as dependency

### ISSUE THREAD

**Issue by luizeboli** [TanStack/query#5446]
### Describe the bug

Related to https://github.com/TanStack/query/issues/5196

Incorrect exhaustive-deps error for constant values when using them in an external function to define the query

![image](https://github.com/TanStack/query/assets/13091635/04535902-8cb4-4374-ab86-71bf5e802f70)
(ApiRoutes is an external enum)

### Steps to reproduce

Use constants values in an external function outside `useQuery`

```js
const Ab = 1

// This throws the error
function groupsQuery() {
  return {
    queryKey: ['get-groups'],
    queryFn: () => Ab,
  }
}

// This works
function useGroups() {
  return useQuery({
    queryKey: ['get-groups'],
    queryFn: () => Ab,
  })
}
```

### Expected behavior

Constants used in external functions should not count as a dependency

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- VSCode

### Tanstack Query adapter

react-query

### TanStack Query version

v4.29.5

### Additional context

Using `@tanstack/eslint-plugin-query` in v4.29.8

**Comment by TkDodo** [comment]
@Newbie012 FYI

**Comment by ujjwal313** [comment]
@TkDodo Still facing the same issue

 "@tanstack/react-query": "^5.59.9"

![Image](https://github.com/user-attachments/assets/d9631fa1-bc8e-4f3d-9d48-471ad2475ea7)

**Comment by TkDodo** [comment]
token is correctly missing because you close over it from within your component.
