### ISSUE TITLE
`useErrorBoundary: true` doesn't work with Vue 3 / Nuxt 3

### ISSUE THREAD

**Issue by arnoson** [TanStack/query#5462]
### Describe the bug

Errors thrown in a query/mutation function aren't caught by Vue 3, either using a custom error boundary with Vue's `onErrorCaptured` or using Nuxt's `<NuxtErrorBoundary />`.

### Your minimal, reproducible example

https://codesandbox.io/p/github/arnoson/tanstack-vue-error-boundary

### Steps to reproduce

1. Click `throw normal error` 🠒  the error is caught by the error boundary
2. Refresh
3. Click `throw mutation error` 🠒  the error isn't caught by the error boundary

### Expected behavior

I expect both errors to be handled by the error boundary

### How often does this bug happen?

Always

### Platform

- OS: Windows
- Browser: Firefox/Chrome

### Tanstack Query adapter

vue-query

### TanStack Query version

4.29.7

**Comment by DamianOsipiuk** [comment]
Hmm, i believe this is a gap, that was left from initial implementation.

For now, as a workaround, `mutateAsync` should properly throw errors.

**Comment by hakastein** [comment]
Do you have workaround for useQuery?

**Comment by DamianOsipiuk** [comment]
Should be fixed in https://github.com/TanStack/query/releases/tag/v4.32.4
