### ISSUE TITLE
@tanstack/query/exhaustive-deps does not work when using positional aruments

### ISSUE THREAD

**Issue by everdimension** [TanStack/query#5516]
### Describe the bug

When I used object syntax, plugin reports error correctly:
```
useQuery({
  queryKey: ['deps-missing'], // missing dependencies reported correctly
  queryFn,
})
```

But if I use `useQuery` with positional arguments:
```
useQuery(
  ['deps-missing'], // PROBLEM: missing deps are not reported
  queryFn,
)
```
The issue is not reported by the eslint plugin

As I can guess from the source code of the plugin, this case is not handles at all: https://github.com/TanStack/query/blob/878d85e44c984822e2e868af94003ec260ddf80f/packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.rule.ts#L36

I believe it should be handled.

---

Would you be interested in adding support for this?

### Your minimal, reproducible example

-

### Steps to reproduce

Use `useQuery` with positional arguments:

```
useQuery(
  ['deps-missing'], // PROBLEM: missing deps are not reported
  queryFn,
)
```

### Expected behavior

Missing dependencies must be reported

### How often does this bug happen?

None

### Platform

any

### Tanstack Query adapter

None

### TanStack Query version

v4.29.12

### TypeScript version

v5.0.4

### Additional context

"@tanstack/eslint-plugin-query": "^4.29.9"

**Comment by TkDodo** [comment]
We have only implemented it for the object syntax because in v5 (currently in alpha), this is the only valid syntax. There's also a second eslint rule (`prefer-query-object-syntax`) that will enforce that syntax, so we haven't implemented it for the multiple arguments version, and there's also no plan to add it, sorry.

**Comment by TkDodo** [comment]
> If this object syntax is encouraged, are there particular reasons why there isn't a codemod to switch to it? I've been exclusively using the original syntax in my app and it's going to be quite a lot of work to rewrite.


There is a codemod when migrating to v5
the eslint rule we provide is auto-fixable, so running `eslint --fix` will also migrate for you.

> Next, while this isn't the best place for this discussion, why is the new syntax going to be the only one?

We have always used the object syntax exclusively internally - we've just had overloads that made it possible for users to pass in multiple arguments, and we've converted that to an object internally. There is no runtime change, if anything, there is now _less_ work to do. See also:
- https://github.com/TanStack/query/discussions/4252

**Comment by Vestride** [comment]
I think it would be worth mentioning in `eslint-plugin-query.md` that the `exhaustive-deps` rule only works with the object syntax.
