### ISSUE TITLE
Object.fromEntries - browser compatible

### ISSUE THREAD

**Issue by lzsheng** [TanStack/query#5531]
### Describe the bug

[document](https://tanstack.com/query/latest/docs/react/installation#requirements) writing the browser support iOS >= 12.0

 but the code use `Object.fromEntries` support iOS >= 12.2

https://caniuse.com/?search=fromEntries

### Your minimal, reproducible example

/

### Steps to reproduce

/

### Expected behavior

/

### How often does this bug happen?

None

### Platform

/

### Tanstack Query adapter

react-query

### TanStack Query version

v4.29.5

**Comment by TkDodo** [comment]
And where exactly do we use `Object.fromEntries` in our code-base please?

**Comment by lzsheng** [comment]
@TkDodo 
https://github.com/TanStack/query/blob/878d85e44c984822e2e868af94003ec260ddf80f/packages/query-core/src/queriesObserver.ts#L76

**Comment by whysetiawan** [comment]
my workaround is adding this code in your entry point project

```
Object.fromEntries =
  Object.fromEntries ||
  function (arr: any[]) {
    return arr.reduce(function (acc: { [x: string]: any }, curr: any[]) {
      acc[curr[0]] = curr[1];
      return acc;
    }, {});
  };
```

**Comment by TkDodo** [comment]
I think this is more an error in the docs. I've updated the docs to reflect reality.
