### ISSUE TITLE
Svelte Query's reactivity differs from React Query

### ISSUE THREAD

**Issue by Coretteket** [TanStack/query#5536]
### Describe the bug

It appears that by default Svelte Query is not reactive to state changes in the query keys. This is best illustrated in the Playground example of the docs that exists for both Svelte and React Query. 

### Your minimal, reproducible example

https://tanstack.com/query/v5/docs/svelte/examples/svelte/playground

### Steps to reproduce

Edit the "fruit" filter value in both the [Svelte Query](https://tanstack.com/query/v5/docs/svelte/examples/svelte/playground) and [React Query](https://tanstack.com/query/v5/docs/react/examples/react/playground) examples. In React, this refetches and updates for the new filter value. In Svelte, nothing happens. 

If I change the example to how I understand Svelte to work, replacing `const query = ...` with `$: query = ...`, this is partially solved. However, this seems to break in yet another way, if I add `placeholderData: (p) => p` to both examples, this only works for React, as the (updated) Svelte example seems to recreate the whole query for every state change.

### Expected behavior

For Svelte Query to refetch when the filter value changes.

### How often does this bug happen?

Every time

### Platform

CodeSandbox

### Tanstack Query adapter

svelte-query

### TanStack Query version

^5.0.0-alpha.38

**Comment by lachlancollins** [comment]
@Coretteket you're right, there are some things that don't work super well in this example - someone else found another reactivity bug. I wrote example as a replica of the react example, and because of that I probably didn't write it svelte-y enough. Feel free to submit some changes in a PR, otherwise I'll get onto it when I have time.

**Comment by niemyjski** [comment]
I can't even get this sample to work or compile with the latest version of svelte query to test: https://github.com/TanStack/query/blob/beta/docs/svelte/reactivity.md
