### ISSUE TITLE
ESLint prefer-query-object-syntax rule dose not fix and raise error useInfiniteQuery

### ISSUE THREAD

**Issue by say8425** [TanStack/query#5562]
### Describe the bug

[@tanstack/query/prefer-query-object-syntax](https://tanstack.com/query/latest/docs/react/eslint/prefer-query-object-syntax) rule dose not look `useInfiniteQuery` to a error.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/old-microservice-g6mfwh?file=%2Fpages%2Findex.js%3A36%2C1-37%2C1

### Steps to reproduce

1. install @tanstack/eslint-plugin-query
2. configure `@tanstack/query/prefer-query-object-syntax` rule
3. run eslint fix

### Expected behavior

`useInfiniteQuery` should be error and can be fixed.

### How often does this bug happen?

Every time

### Platform

- macOS 13.4
- Chrome 114

### Tanstack Query adapter

None

### TanStack Query version

v4.0.10

### TypeScript version

v5.0.4

### Additional context

I think adding `useInfiniteQuery`, `useIsFetching`, `useIsMutating` into [QUERY_CALLS](https://github.com/TanStack/query/blob/main/packages/eslint-plugin-query/src/rules/prefer-query-object-syntax/prefer-query-object-syntax.ts#LL7C1-L13C1) will fix this issue. Is that true, then I will fix it.

**Comment by Newbie012** [comment]
@TkDodo should I update the rule to catch `useInfiniteQuery` as well?

**Comment by TkDodo** [comment]
@Newbie012 yes please

**Comment by Newbie012** [comment]
@TkDodo since we removed `prefer-query-object-syntax` rule anymore, should we close this issue?
