### ISSUE TITLE
[v5 alpha] About immutable updates.

### ISSUE THREAD

**Issue by yegao** [TanStack/query#5585]
### Describe the bug
Here is a demo: https://codesandbox.io/s/hopeful-hertz-ocvp6e
Here's what really confused me:
```
// 1. not working, do NOT trigger re-render
dataset.k = "B";
dataset = { ...dataset };
queryClient.refetchQueries({ queryKey: ["dataset"] });
// 2. working,trigger re-render
dataset = { ...dataset, k: "B" };
queryClient.refetchQueries({ queryKey: ["dataset"] });
```
so what difference between
```
dataset.k = "B";
dataset = { ...dataset };
```
and
```
dataset = { ...dataset, k: "B" };
```
I don't know that they are any different, they all produce different object references than before。
But it does produce different results. Does react-query do anything special？

I created a discussion about the problem。https://github.com/TanStack/query/discussions/5496

### Your minimal, reproducible example

https://codesandbox.io/s/hopeful-hertz-ocvp6e

### Steps to reproduce

demo: https://codesandbox.io/s/hopeful-hertz-ocvp6e

### Expected behavior

Both trigger re-render

### How often does this bug happen?

Every time

### Platform

macOS

### Tanstack Query adapter

None

### TanStack Query version

^5.0.0-alpha.38

**Comment by TkDodo** [comment]
we've discussed this before. By writing to `dataset` directly, you manipulate the entries in the queryCache directly. Then, when our structural sharing functionality kicks in after the fetch, it sees that both objects (data in the cache and data returned from the queryFn) are the same and it thus opts out of re-rendering.
