### ISSUE TITLE
`suspense` and `onServerPrefetch` don't seem to work as intended (Nuxt 3)

### ISSUE THREAD

**Issue by genu** [TanStack/query#5592]
### Describe the bug

When working with nuxt, its not clear how suspense is supposed to work.

In the codesandbox, we can see that prefetch calls suspense, and then we call suspense again. However, on the server data is always null.

This causes Nuxt application to break in unexpected ways due to hydration problems.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/github/tanstack/query/tree/main/examples/vue/nuxt3?embed=1&file=%2Fapp.vue%3A10%2C21

### Steps to reproduce

1. Setup a bare minimum Nuxt 3

### Expected behavior

I'm expecting that SSR and client would be in sync whenever a query runs on the server or client.

### How often does this bug happen?

Every time

### Platform

- macoS
- Railway

### Tanstack Query adapter

vue-query

### TanStack Query version

4.29.13

### TypeScript version

5.1.3

**Comment by madskronborg** [comment]
+1 - the issue occurs after upgrading to version 4.29.13. It works as expected in 4.29.11 :)

**Comment by DamianOsipiuk** [comment]
Seems to be connected to a recent change trying to fix nuxt2 memory leak. I guess we need to revert that.

**Comment by kovai** [comment]
I have the same problem after updating to 4.29.14.
Rolling back to 4.29.7, which I used before, solved the problem.

**Comment by DamianOsipiuk** [comment]
Please try with https://github.com/TanStack/query/releases/tag/v4.29.18

**Comment by madskronborg** [comment]
It works - tested with version 4.29.19 - thank you for the quick fix! :+1:
