### ISSUE TITLE
Typescript issue with union typed TError in query.ts

### ISSUE THREAD

**Issue by jotoh98** [TanStack/query#5594]
### Describe the bug

I stumbled across a rather odd issue using react-query in a custom react-native environment. The only thing complaining is `tsc`, telling me that the dispatch method in [query.ts:488:55](https://github.com/TanStack/query/blob/5188ae3f953a9b1100d87a10dbfd5b95a7200553/packages/query-core/src/query.ts#L488) expects a plain `TError`, but receives a potentially unrelated `TError | { silent?: boolean; }`. I've tried my best to supply an adequate example in the ts Playground:

The `onError`-Method seems to expect this unrelated type, although it's implementation does not need this additional field, checking for the CancelledError type at runtime ([query.ts:427](https://github.com/TanStack/query/blob/accecddd167545fd8b8e78af5ed1ec677c3cbb27/packages/query-core/src/query.ts#L427)). A I understand it, the generic is inferred via the `createRetryer` and passed to the `onFail`-Method ([query.ts:487](https://github.com/TanStack/query/blob/accecddd167545fd8b8e78af5ed1ec677c3cbb27/packages/query-core/src/query.ts#L487)) clashing into the `dispatch`-Function expecting a `TError`.

Is there a need for the union type in the `onError` function if the scopes expecting a `CancelledError` already receive it via runtime checks?

### Your minimal, reproducible example

https://tsplay.dev/WGdD2w

### Steps to reproduce

See playground, I'm not sure what makes it work in the project itself

### Expected behavior

No typescript errors

### How often does this bug happen?

Every time

### Platform

- React Native

### Tanstack Query adapter

react-query

### TanStack Query version

v4.29.14

### TypeScript version

v5.1.3

**Comment by TkDodo** [comment]
Hm, 2 questions:

- why do you type-check the sources of react-query?
- why doesn't this show up as error in _our own_ TS pipeline 🤔 ?

**Comment by jotoh98** [comment]
@TkDodo thanks for your quick response.
The first may be a misconfiguration issue somewhere. But I was curious to see if the issue would persist when throwing away all other influences. The playground does not seem to be happy either. But maybe I'm missing something obvious ^^
I was also checking if there is a huge difference between the setups. In the project itself there's no issue - picking the important parts and recreating the situation in playground yields an error.

**Comment by TkDodo** [comment]
> The only thing complaining is tsc, telling me that the dispatch method in [query.ts:488:55](https://github.com/TanStack/query/blob/5188ae3f953a9b1100d87a10dbfd5b95a7200553/packages/query-core/src/query.ts#L488) expects a plain TError, but receives a potentially unrelated TError | { silent?: boolean; }

When I'm checking the code in question in our codebase, I can see that `onFail` gets an error of type `unknown`:

![Screenshot 2023-06-17 at 11 36 15](https://github.com/TanStack/query/assets/1021430/5b34d967-1bd6-41ae-bb5b-2c17c245cfb1)

even if I update to the latest TS 5.1.3

**Comment by jotoh98** [comment]
Unfortunately, I was not able to fix or to find the source of this issue on our side. For now, I'm closing this issue

**Comment by iNetJoJo** [comment]
@TkDodo @ag-import 
i figured out what was going on.

i some places in my project i had stuff imported from '@tanstack/query-core' while it was propagate to parts that were mostly used from '@tankstack/react-query', just replace import froms since they still have same exports. I dont know why this is but seems to be some type colision

**Comment by sc0ttdav3y** [comment]
I see this ticket is old and closed, and React Query has moved on and is now at v5, but I experienced this today.

It blocked my ability to build my Next.JS project even with `skipLibCheck` on and `node_modules` excluded in `tsconfig.json`.  I workaround around it and I thought I'd add my experience here in case it helps others.

Typescript thinks `error` is a `TError | {silent?: boolean}`, but the option key is defined as `TError`. I can't statically work out where Typescript gets its advanced intuition on this.

Versions:

* `@tanstack/react-query` 4.36.1 (not a problem back in 4.2.3 where I was)
* `typescript` 5.4.2

My workaround was to use [patch-package](https://github.com/ds300/patch-package#readme) to add a `// @tsignore` above line query.ts:490. 

Patch:

```
diff --git a/node_modules/@tanstack/query-core/src/query.ts b/node_modules/@tanstack/query-core/src/query.ts
index d334a0f..c8f0644 100644
--- a/node_modules/@tanstack/query-core/src/query.ts
+++ b/node_modules/@tanstack/query-core/src/query.ts
@@ -487,6 +487,7 @@ export class Query<
       },
       onError,
       onFail: (failureCount, error) => {
+        // @ts-ignore
         this.dispatch({ type: 'failed', failureCount, error })
       },
       onPause: () => {
```
