### ISSUE TITLE
QueryCacheNotifyEvent types not exported

### ISSUE THREAD

**Issue by stevekuznetsov** [TanStack/query#5599]
### Describe the bug

When subscribing to the query cache, like:

```ts
const queryCache: QueryCache = new QueryCache();
queryCache.subscribe(event => void work(event));
```

There's no way to type the function signature of `work` since the `QueryCacheNotifyEvent` types are not exported.

### Your minimal, reproducible example

see above

### Steps to reproduce

see above

### Expected behavior

Would love to define a function like

```ts
const work = (event: QueryCacheNotifyEvent) => { ... }
```

### How often does this bug happen?

Every time

### Platform

not important

### Tanstack Query adapter

react-query

### TanStack Query version

@tanstack/react-query@4.24.9

### TypeScript version

Version 4.9.5

### Additional context

Might be cool to get a linter installed that ensures that any public-facing types (used in other exported functions) are also exported.

**Comment by TkDodo** [comment]
you can always extract the types from functions of the QueryCache:

```
import { QueryCache } from '@tanstack/react-query'

type Subscribe = QueryCache['subscribe']
type Listener = Parameters<Subscribe>[0]

const work: Listener = (e) => {
  console.log(e)
}

const queryCache: QueryCache = new QueryCache();
queryCache.subscribe(event => void work(event));
```

See this [typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRQK4FMoE8DCBDAYwAt04BfOAMyghDgHIABGPAOwGcWCBrAeinSEYAWgCOGbPQBQUmFjCkAyqgBG7AlGArSAXhQTchEgG167Ves3b6AXVnzSAGWCd0rTHD0AFPFDwh0GEx2AB5lNQ0tdAA+YwAGOykCCA54AHdobgAuOGdXdyhPOAAKdABKT2jEKTg4ZI4IABt0ADpGiABzUrKpMhl6zjhxTENidBy0Efwxovc0-SmjdGKygG4pYexpkhbzCKtl9AA3N3gdKqOIYAATOAyoblKT1hgytaA)

Usually, those functions will be inlined, but I'd accept a PR that exports those as well.

**Comment by indrajitbnikam** [comment]
Hi, Can I work on it?

**Comment by TkDodo** [comment]
Sure

**Comment by bartvanandel** [comment]
Interested to see this happen as well. I'm building a small (debugging) component to quickly enable query event logging, but would like to implement a filter option. For correct filter function types, this should be able to use the types. Having direct access to the actual types is much preferred over extracting them from the listener type.

**Comment by indrajitbnikam** [comment]
Hi @TkDodo , I've created a PR addressing the exports. Can you review it once?

Also, let me know if I should export other such public-facing types.

**Comment by stevekuznetsov** [comment]
@indrajitbnikam thank you <3
