### ISSUE TITLE
There is a delay in persisting storage using '@tanstack/query-sync-storage-persister' plug-ins. 

### ISSUE THREAD

**Issue by Kerryta** [TanStack/query#5606]
### Describe the bug

Steps:
1. Invoke the login interface and use 'queryClient.setQueryData' to store the token.
2. Jump to the home page and invoke a new interface.
3. The local storage cannot be retrieved in axios' request interception.
Test:
I try not to use plugins and manually store them locally, when the login succeeds, the token is stored, and the new interface is invoked on the jump home page, the locally stored token can be obtained in axios request interception.

### Your minimal, reproducible example

https://stackblitz.com/edit/stackblitz-starters-weqk5r?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx,src%2Flogin.tsx&title=React%20Starter

### Steps to reproduce

1. Invoke the login interface and use 'queryClient.setQueryData' to store the token.
2. Jump to the home page and invoke a new interface.
3. The local storage cannot be retrieved in axios' request interception.

### Expected behavior

fix it pls

### How often does this bug happen?

None

### Platform

react 18 ,chrome

### Tanstack Query adapter

None

### TanStack Query version

"@tanstack/query-sync-storage-persister": "^4.29.11", 		"@tanstack/react-query": "^4.29.12", 		"@tanstack/react-query-persist-client": "^4.29.12",

### TypeScript version

4.9.3

### Additional context

--

**Comment by TkDodo** [comment]
as documented, `throttleTime` defaults to 1s:

https://tanstack.com/query/v4/docs/react/plugins/createSyncStoragePersister#options

also, your reproduction is not working.
