### ISSUE TITLE
Failed to resolve entry for package "@tanstack/solid-query" when upgrading to solid-query 5.0.0

### ISSUE THREAD

**Issue by MattJustMatt** [TanStack/query#5612]
### Describe the bug

I’m trying to migrate a small project I wrote with solid-query from v4 to v5. I’ve tried wiping node_modules and starting fresh but Vite can’t bundle solid-query for some reason with the error in the title. 

### Your minimal, reproducible example

//

### Steps to reproduce

Install solid-query latest alpha,
Try to include it in a Vite bundled project

### Expected behavior

Normal behavior with the new API

### How often does this bug happen?

Every time

### Platform

Windows,
SolidJS project using the solid vite template

### Tanstack Query adapter

solid-query

### TanStack Query version

Alpha 68

### TypeScript version

4.9.5

**Comment by MattJustMatt** [comment]
It looks like there's a typo in the path for the solid entry js file:

https://github.com/TanStack/query/blame/7c61693d6f76adb3d015ed97ce0045fe47df174f/packages/solid-query/package.json#L20

I believe this should be .js. Modifying gets me building again

**Comment by ardeora** [comment]
Thanks for working on this! Should be fixed in [v5.0.0-alpha.69](https://github.com/TanStack/query/commit/b1ea78f3389fa9a699fc1d4285a301fb3d2fd0ba)

Could you please check and confirm 😄

**Comment by MattJustMatt** [comment]
Thanks for merging! Tested locally and good to go! Fresh npm install with no errors
