### ISSUE TITLE
React native 0.72.0 + metro.config.js + unstable_enablePackageExports - true makes app warning raise

### ISSUE THREAD

**Issue by aliza-khu** [TanStack/query#5641]
### Describe the bug

I am getting a warning "TypeError: Cannot read property '__awaiter' of undefined" with the latest react native version 0.72.0 and under metro.config.js file unstable_enablePackageExports = true.

### Your minimal, reproducible example

https://codesandbox.io/s/happy-goldstine-qymrrm?file=/src/App.js:166-174

### Steps to reproduce

1. Switch to react native 0.72.0
2. Under metro.config.js file:
const config = {
  resolver: {
    unstable_enableSymlinks: true,
    unstable_enablePackageExports: true,
  }
};

### Expected behavior

Facing above mentioned warning.

### How often does this bug happen?

Every time

### Platform

- OS: Macos

### Tanstack Query adapter

react-query

### TanStack Query version

3.39.3

### TypeScript version

4.9.5

**Comment by TkDodo** [comment]
> Switch to react native 0.72.0
Under metro.config.js file:
const config = {
resolver: {
unstable_enableSymlinks: true,
unstable_enablePackageExports: true,
}
};

sorry, this is no reproduction. Your sandbox doesn't even have a `metro.config.js` file, I don't even know what that is. Also: You're using v3, which is over a year old. And I'm not sure what you'd expect react-query to do if you use a feature that's prefixed with `unstable_`...
