### ISSUE TITLE
Queries stop working completely in Chrome?

### ISSUE THREAD

**Issue by Jinmo-K** [TanStack/query#5644]
### Describe the bug

Once in a while queries seem to just completely stop working ie. they don't send out a network request (in Chrome + on refresh). Has anyone else experienced this?

Reinstalling Chrome resolves the issue (and I think maybe restarting Chrome worked once)

NOTE: I've noticed the chatGPT website will not load either when this happens + in the most recent report the user was able to use Safari, which tells me it's probably not directly related to our app code but more of a browser issue

### Your minimal, reproducible example

N/A

### Steps to reproduce

No repro

### Expected behavior

Expecting normal behaviour

### How often does this bug happen?

Sometimes

### Platform

- OS: varies
- Browser: Chrome
- version: varies

### Tanstack Query adapter

react-query

### TanStack Query version

v4.24.4

**Comment by TkDodo** [comment]
probably related to: https://bugs.chromium.org/p/chromium/issues/list?q=navigator.online

**Comment by Jinmo-K** [comment]
> probably related to: https://bugs.chromium.org/p/chromium/issues/list?q=navigator.online

interesting, thanks!
