### ISSUE TITLE
Infinite scroll when using async component in react 

### ISSUE THREAD

**Issue by veritem** [TanStack/query#5645]
### Describe the bug

I'm using next 13's app directory but using useQuery in an async component causes an infinite loop that hangs the browser. Ideally, I feel like react query should check for this behavior and avoid it but I don't know how react query works to get a reason for this. You'll let me know me know why this happens 

### Your minimal, reproducible example

https://github.com/veritem/next-13-react-query-repro

### Steps to reproduce

1. pnpm install
2. pnpm dev

open the browser tab, it'll hang. 

### Expected behavior

I should shouldn't hang. 

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/query/assets/53856673/b53b285c-7ee7-4e75-ad30-44ec0ef2cabc

### Platform

- OS: MacOs
- Browser: Chrome 

### Tanstack Query adapter

None

### TanStack Query version

4.29.19

### TypeScript version

5.1.5

**Comment by TkDodo** [comment]
>  using useQuery in an async component

you are using an async client component - that's not a thing. server components can be async, client components cannot.

see: https://twitter.com/AdamRackis/status/1672779428617674753
