### ISSUE TITLE
`mutationFn` drops subsequent arguments

### ISSUE THREAD

**Issue by githorse** [TanStack/query#5650]
### Describe the bug

[The docs](https://tanstack.com/query/latest/docs/react/guides/mutations) show examples where the `mutationFn` has an arity of one:

```
const mutation = useMutation({
  mutationFn: (newTodo) => {
    return axios.post('/todos', newTodo)
  },
})
```

I assumed I could write a `mutationFn` with more arguments if I wanted: 

```
const mutation = useMutation({
  mutationFn: (newTodo, pimpIt) => {
    return axios.post(`/todos?pimpIt=${pimpIt}`, newTodo)
  },
})

...
<button
  onClick={() => {
    mutation.mutate({ id: new Date(), title: 'Do Laundry' }, true)
  }}
>
```

But this doesn't work -- only the first argument (`newTodo`) makes it to the `axios.post()` here. The second argument is `undefined`. Here's a [CodeSandbox example](https://codesandbox.io/p/sandbox/broken-morning-5c772g?embed=1&file=%2Fsrc%2Findex.jsx%3A29%2C10).

Obviously I can rewrite my function to accept an array or an object as the first argument to get around this. But is this by design, or a bug? If by design, could we cover it in the docs? I spent a while tracking down this bug in my code, and others may benefit from calling it out. 

### Your minimal, reproducible example

[CodeSandbox example](https://codesandbox.io/p/sandbox/broken-morning-5c772g?embed=1&file=%2Fsrc%2Findex.jsx%3A29%2C10)

### Steps to reproduce

1. Click the button
2. View `console.log()` output, which shows that the second argument is `undefined`.

### Expected behavior

I expected to pass whatever arguments I wanted to `mutationFn`. 

### How often does this bug happen?

Every time

### Platform

Linux Mint 21.1 Cinnamon
Chromium Version 114.0.5735.133

### Tanstack Query adapter

react-query

### TanStack Query version

4.29.12

### TypeScript version

4.6.4

**Comment by ghostd** [comment]
Hi @githorse 

The current design allows only one parameter. This is not straight in the official documentation, but this is clear is this [TkDodo's article](https://tkdodo.eu/blog/mastering-mutations-in-react-query#mutations-only-take-one-argument-for-variables).

**Comment by githorse** [comment]
Thanks @ghostd -- see [relevant discussion](https://github.com/TanStack/query/discussions/1226). Personally I'd love to see multiple arguments supported; shoehorning the natural function signature of the mutation into an object or array or whatever feels like a hack. (I'll probably writing a wrapper around it to do this for me.) Either way, the current limitation should be noted in the official docs.

**Comment by TkDodo** [comment]
the reason why we only have one argument is that the second argument contains callbacks to `mutate`:

```
mutate(vars, { onSuccess, onError, onSettled })
```

it is documented here: https://tanstack.com/query/v4/docs/react/guides/mutations

> In the example above, you also saw that you can pass variables to your mutations function by calling the mutate function with a **single variable or object**.
