### ISSUE TITLE
queryclient.invalidateQueries is not working in nextjs 13 with revalidatePath

### ISSUE THREAD

**Issue by SeungYn** [TanStack/query#5673]
### Describe the bug

i'm trying NextJS server mutate after running "queryClient.i'm trying NextJS server mutate after "queryClient.invalidateQueries({queryKey:['key']})"
but Network request for above key is ignored

again
If you try to use server mute but use revalidatePath, the invalidQueries request of the react-query ignores the following requests after the first request

<img width="694" alt="image" src="https://github.com/vercel/next.js/assets/66045666/4ce3bb15-2c3b-43f2-9c30-219a4e2f8c14">

<img width="695" alt="image" src="https://github.com/vercel/next.js/assets/66045666/7b7a5240-3b75-4e0c-a8ae-4bc2977877e4">

next config
<img width="420" alt="image" src="https://github.com/vercel/next.js/assets/66045666/82970f4a-1f1b-406b-85c7-b2d378144184">

result
<img width="788" alt="image" src="https://github.com/vercel/next.js/assets/66045666/56883f3d-73dd-48f6-ac89-c31283bd3bb7">

### Your minimal, reproducible example

.

### Steps to reproduce

1. to use a react-query's mutateAsync to mutate for network requests
2. If the mutation is completed, re-request the data related to the key to the parameter using queryClient.invalidateQueries.
3. Nextjs's server-actions and revalidatePath use in order to server mutate

but queryClient.invalidateQueries makes only one network request and does not do it afterwards.

### Expected behavior

1. to use a react-query's mutateAsync to mutate for network requests
2. If the mutation is completed, re-request the data related to the key to the parameter using queryClient.invalidateQueries.
3. Nextjs's server-actions and revalidatePath use in order to server mutate

but queryClient.invalidateQueries makes only one network request and does not do it afterwards.

### How often does this bug happen?

Every time

### Platform

MacOs

### Tanstack Query adapter

react-query

### TanStack Query version

v5.0.0-alpha.71

### TypeScript version

v5.1.3

**Comment by TkDodo** [comment]
Please show a runnable reproduction, not screenshots. I'm not entirely sure, but I think you should either `revalidatePath` from next or `invalidateQueries` from react-query. Why are you doing both?

**Comment by TkDodo** [comment]
feel free to reopen with a reproduction
