### ISSUE TITLE
If you use router refresh of NextJS, query keys and data are lost

### ISSUE THREAD

**Issue by SeungYn** [TanStack/query#5675]
### Describe the bug

I had a problem applying server mute and wrote a small test code.
but
The problem is that when you use the router.refresh, both the query key and the data disappear
Should I ask nextjs about this?

The question may seem stupid, but I'm doing it relying on a translator Please understand

code 
```
'use client';
import { useQuery } from '@tanstack/react-query';
import { useRouter } from 'next/navigation';

async function fetchTest() {
  return fetch('/api/t', { method: 'get' }).then((res) => res.json());
}

export default function Test() {
  const router = useRouter();
  const { data } = useQuery(['test'], () => fetchTest());

  const onClick = async () => {
    router.refresh();
  };

  console.log('data', data, 123);
  return (
    <div>
      <button className='text-neutral-200 text-xl' onClick={onClick}>
        button
      </button>
      <p className='text-neutral-100 text-xl'>{JSON.stringify(data)}</p>
    </div>
  );
}
```

result
![ezgif com-video-to-gif (8)](https://github.com/TanStack/query/assets/66045666/800817c0-f679-4b4e-aa1e-7e3ab4d35511)

### Your minimal, reproducible example

.

### Steps to reproduce

1. fetch data with useQuery
2. button click 
3. but if Nextjs's router.refresh use , both the query key and the data disappear

### Expected behavior

1. fetch data with useQuery
2. button click 
3. but if Nextjs's router.refresh use , both the query key and the data disappear

### How often does this bug happen?

None

### Screenshots or Videos

![ezgif com-video-to-gif (8)](https://github.com/TanStack/query/assets/66045666/800817c0-f679-4b4e-aa1e-7e3ab4d35511)

### Platform

MacOS
Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

v4.29.19

### TypeScript version

v5.1.6

**Comment by kpqrx** [comment]
What version of Next are you running and how did you manage to run Devtools? It seems to be broken in latest Next 13

**Comment by sahibjotsaggu** [comment]
Also having the same issue but with `router.push()` using Next version `13.4.7` and react-query version `4.29.19`

**Comment by sinau123** [comment]
I have same issue, it's like after page navigation the cache was gone.

I'm using pages route.

`"@tanstack/react-query": "^4.29.19",`
`"next": "13.4.7",`

**Comment by sinau123** [comment]
okay for me it caused by next-i18next library when i call `serverSideTranslations` in `getServerSideProps`.

https://github.com/i18next/next-i18next/issues/2187

**Comment by TkDodo** [comment]
I can't help here without a minimal reproduction in codesandbox.

Make sure that the QueryClient is **stable**; for next, that means created in `useState`, as the docs shw.

**Comment by SeungYn** [comment]
@kpqrx react-query in version 4.23.19 and react-query-devtools in 4.29.19 do well in nextjs in version "13.4.8"

**Comment by SeungYn** [comment]
@TkDodo thankyou I was late because I wrote codesandbox. sorry 
i wonder difference to wrap QueryClient with useState
if queryClient is wrapped with useState, is well working but i'm not understand.
If the page is refreshed, it means that I'm requesting a new page, how does the state stay?

Below is a sample of a well-functioning sample

https://codesandbox.io/p/github/SeungYn/react-query-test/main?file=/src/context/ReactQueryContext.tsx:1,1&workspaceId=820da5ea-9550-4af7-97c2-97c230e411ba

Below is a non-functional version of the sample
https://codesandbox.io/p/github/SeungYn/react-query-test/not-working-querycache?file=/src/context/ReactQueryContext.tsx:1,1&workspaceId=820da5ea-9550-4af7-97c2-97c230e411ba

**Comment by TkDodo** [comment]
> if queryClient is wrapped with useState, is well working but i'm not understand.

see: https://tkdodo.eu/blog/react-query-fa-qs#2-the-queryclient-is-not-stable

> If the page is refreshed, it means that I'm requesting a new page, how does the state stay?

`router.refresh` doesn't refresh the page - it just re-renders your components with data newly fetched from the server. If you reload the page with F5 or CMD/CTRL+R, data will be gone.

from https://nextjs.org/docs/app/api-reference/functions/use-router:

> router.refresh(): Refresh the current route. Making a new request to the server, re-fetching data requests, and re-rendering Server Components. The client will merge the updated React Server Component payload without losing unaffected client-side React (e.g. useState) or browser state (e.g. scroll position).

**Comment by SeungYn** [comment]
@TkDodo  thank you!!
i wonder you
What should I do to be a great programmer like you
I wonder what you did when you were 26
