### ISSUE TITLE
AlertDialog documentation needs small update

### ISSUE THREAD

**Issue by usaszerelem** [TanStack/query#5676]
### Describe the bug

The call `const cancelRef = React.useRef()` in the sample AlertDialog documentation (https://chakra-ui.com/docs/components/alert-dialog) needs to be updated to
`const cancelRef = useRef<HTMLButtonElement>(null);` to avoid TypeScript errors

### Your minimal, reproducible example

https://chakra-ui.com/docs/components/alert-dialog

### Steps to reproduce

1. Copy paste the code from the example into your code
2. Run the typescript compiler
3. Error:
`Type 'MutableRefObject<undefined>' is not assignable to type 'RefObject<FocusableElement>'.
  Types of property 'current' are incompatible.
    Type 'undefined' is not assignable to type 'FocusableElement | null'.ts(2322)
alert-dialog.d.ts(18, 5): The expected type comes from property 'leastDestructiveRef' which is declared here on type 'IntrinsicAttributes & AlertDialogProps'`

### Expected behavior

Make the minor update to the documentation and many users will be cheering.

### How often does this bug happen?

Every time

### Screenshots or Videos

![Screenshot 2023-07-04 at 7 45 12 PM](https://github.com/TanStack/query/assets/31490906/f5b092d9-1d7b-467f-b161-59d8a85eb1b2)

### Platform

OS: MacOS
Chrome Version 114.0.5735.198 (Official Build) (arm64)

### Tanstack Query adapter

react-query

### TanStack Query version

"@tanstack/react-query": "^4.29.12",

### TypeScript version

"typescript": "^5.0.2",

**Comment by TkDodo** [comment]
okay?

**Comment by usaszerelem** [comment]
Hello @TkDodo. Your response is brief and not sure what you are asking for. I trust this request simple and would help users.

**Comment by TkDodo** [comment]
Ahm, why exactly did you open an issue about chakra-ui in TanStack/query ?

**Comment by usaszerelem** [comment]
Now I understand. Please accept my apologies for creating this bug report in the wrong category. Please consider this closed and I will create the bug in the correct place. Have a great day.
