### ISSUE TITLE
Devtools not being excluded in production (v5/alpha)

### ISSUE THREAD

**Issue by kaumac** [TanStack/query#5680]
### Describe the bug

I'm using the alpha (v5) version of tanstack query on a side project and I have added the devtools. The dependency (`"@tanstack/react-query-devtools": "^5.0.0-alpha.72",`) is installed as a dev dependency (also tried as normal dependency). I'm using it on a NextJS v13 app generated with created-next-app.
The app is being deployed to Vercel.

The same setup but using react-query v4 was working and deploying to production without a problem.

### Your minimal, reproducible example

https://github.com/kaumac/rank-tt

### Steps to reproduce

Running `npm run build` should trigger the error

### Expected behavior

As a user, I expect to not have the devtools as part of the production bundle, but its happening and breaking production builds.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="2560" alt="Captura de Tela 2023-07-06 às 03 04 30" src="https://github.com/TanStack/query/assets/1170740/e6c81037-51ef-428c-8163-7cd2770a93c6">

### Platform

Mac OS 12.6

### Tanstack Query adapter

react-query

### TanStack Query version

5.0.0-alpha.72

### TypeScript version

5.1.5

**Comment by TkDodo** [comment]
seems to be the same error as in this issue:
- https://github.com/TanStack/query/issues/5671

so let's track it there
