### ISSUE TITLE
Module level directives cause errors when bundled, "use client" in "node_modules/.pnpm/@tanstack+react-query@4.29.3_react-dom@18.2.0_react@18.2.0/node_modules/@tanstack/react-query/build/lib/useSyncExternalStore.mjs" was ignored.

### ISSUE THREAD

**Issue by vaynevayne** [TanStack/query#5681]
### Describe the bug

<img width="931" alt="image" src="https://github.com/TanStack/query/assets/124666577/3d5c2b5d-0a00-4689-b82a-a05e7b303a74">

### Your minimal, reproducible example

https://snack.expo.dev/

### Steps to reproduce

see png

### Expected behavior

see png

### How often does this bug happen?

None

### Platform

see png

### Tanstack Query adapter

None

### TanStack Query version

see png

**Comment by suppayami** [comment]
I just upgrade to latest version and got this warning on Vite build too. In my opinion, TanQuery is fw agnostic so it shouldn't be supporting a single (maybe) popular fw while letting problems (or noises) on the others.

**Comment by TkDodo** [comment]
cmon, this has been reported a bunch of times before:

https://github.com/TanStack/query/issues?q=is%3Aissue+Module+level+directives+cause+errors+when+bundled+is%3Aclosed
