### ISSUE TITLE
UseQueryOptions are not assignable to useQuery in V5

### ISSUE THREAD

**Issue by rajzik** [TanStack/query#5696]
### Describe the bug

After update to react query 5 I've found issue with types.

When I try to create object with RQ UseQueryOptions it is not possible to assign this options to useQuery.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/gracious-meninsky-6mj52n?file=%2Fsrc%2FApp.tsx%3A9%2C8

### Steps to reproduce

1. Create options with type `UseQueryOptions`
2. Pass options to the `useQuery` function
3. Typescript error TS

<details>
 <summary><code>typescript(2769)</code></summary>
<code>
No overload matches this call.
  Overload 1 of 2, '(options: UndefinedInitialDataOptions<GetAllDataContainerResponse, GetAllDataContainerError, TData, string[]>, queryClient?: QueryClient | undefined): UseQueryResult<...>', gave the following error.
    Argument of type '{ enabled?: boolean | undefined; staleTime?: number | undefined; refetchInterval?: number | false | ((data: TData | undefined, query: Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, QueryKey>) => number | ... 1 more ... | undefined) | undefined; ... 24 more ...; queryKey: st...' is not assignable to parameter of type 'UndefinedInitialDataOptions<GetAllDataContainerResponse, GetAllDataContainerError, TData, string[]>'.
      Type '{ enabled?: boolean | undefined; staleTime?: number | undefined; refetchInterval?: number | false | ((data: TData | undefined, query: Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, QueryKey>) => number | ... 1 more ... | undefined) | undefined; ... 24 more ...; queryKey: st...' is not assignable to type 'UseQueryOptions<GetAllDataContainerResponse, GetAllDataContainerError, TData, string[]>'.
        Types of property 'refetchInterval' are incompatible.
          Type 'number | false | ((data: TData | undefined, query: Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, QueryKey>) => number | ... 1 more ... | undefined) | undefined' is not assignable to type 'number | false | ((data: TData | undefined, query: Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, string[]>) => number | ... 1 more ... | undefined) | undefined'.
            Type '(data: TData | undefined, query: Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, QueryKey>) => number | ... 1 more ... | undefined' is not assignable to type 'number | false | ((data: TData | undefined, query: Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, string[]>) => number | ... 1 more ... | undefined) | undefined'.
              Type '(data: TData | undefined, query: Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, QueryKey>) => number | ... 1 more ... | undefined' is not assignable to type '(data: TData | undefined, query: Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, string[]>) => number | ... 1 more ... | undefined'.
                Types of parameters 'query' and 'query' are incompatible.
                  Type 'Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, string[]>' is not assignable to type 'Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, QueryKey>'.
                    The types of 'options.queryFn' are incompatible between these types.
                      Type 'QueryFunction<GetAllDataContainerResponse, string[], never> | undefined' is not assignable to type 'QueryFunction<GetAllDataContainerResponse, QueryKey, never> | undefined'.
                        Type 'QueryFunction<GetAllDataContainerResponse, string[], never>' is not assignable to type 'QueryFunction<GetAllDataContainerResponse, QueryKey, never>'.
                          The type 'QueryKey' is 'readonly' and cannot be assigned to the mutable type 'string[]'.
  Overload 2 of 2, '(options: DefinedInitialDataOptions<GetAllDataContainerResponse, GetAllDataContainerError, TData, string[]>, queryClient?: QueryClient | undefined): DefinedUseQueryResult<...>', gave the following error.
    Argument of type '{ enabled?: boolean | undefined; staleTime?: number | undefined; refetchInterval?: number | false | ((data: TData | undefined, query: Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, QueryKey>) => number | ... 1 more ... | undefined) | undefined; ... 24 more ...; queryKey: st...' is not assignable to parameter of type 'DefinedInitialDataOptions<GetAllDataContainerResponse, GetAllDataContainerError, TData, string[]>'.
      Type '{ enabled?: boolean | undefined; staleTime?: number | undefined; refetchInterval?: number | false | ((data: TData | undefined, query: Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, QueryKey>) => number | ... 1 more ... | undefined) | undefined; ... 24 more ...; queryKey: st...' is not assignable to type 'UseQueryOptions<GetAllDataContainerResponse, GetAllDataContainerError, TData, string[]>'.
        Types of property 'refetchInterval' are incompatible.
          Type 'number | false | ((data: TData | undefined, query: Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, QueryKey>) => number | ... 1 more ... | undefined) | undefined' is not assignable to type 'number | false | ((data: TData | undefined, query: Query<GetAllDataContainerResponse, GetAllDataContainerError, GetAllDataContainerResponse, string[]>) => number | ... 1 more ... | undefined) | undefined'.typescript(2769)
</code>
</details>

### Expected behavior

As a user I expect that `UseQueryOptions` can be assigned to the useQuery hook.

### How often does this bug happen?

Every time

### Platform

- OS: Mac OS
- Browser: Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

5.0.0-alpha.71

### TypeScript version

v5.0.2

**Comment by TkDodo** [comment]
you need to omit `initialData` as well, or provide it as always defined, or provide overloads.

[working playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ4A0cAqhtrngPJgzAQB2qcAvnAGZQQhwDkAAjACGjIQGMA1gHoo6QaJgBaAI458POJMlwYeMOlQAuOIIA2YABaCAUKEiw4AKmNNR0dO07d+QkXKkqKBVcZdU1tXX0jUwtrK3QADzt4HT04AHF0GABBExMAEUEhAGEGIWB6XAAlfUhGdwBeOFQYKHKAcwBtAF0AbjjE6GSI9Myc-MLBEvoyiqgAUShOKDhGhGY+-qS4VxEUDABZPAKhADFM0XMVuAAeABVjwSuM7NyHqZmqmoYMAgA+AAorHA4BAaHRGAB+IyUEDAGDXIHAkhkVRUMHfBFIpHPMZvUqCcqfVC1H6IrE414Td4E2YLJYEMlI+4TBlY4HNVr0TpdRm-VlIgBEAXwAGl0HgBXAAD5wIWok70SUygXlOHAUwPAWI35WACUK1+iERMhgyCg9D2WFR-wQjOFeDFeCMHQFqC46AFRAF4nFAq6-OBADpg6DaN9+cxdX11kA)

I've said it many times before: You do not want to create low level abstractions over useQuery. It's complicated on type level, and it has little gains.
