### ISSUE TITLE
Svelte 4 Support

### ISSUE THREAD

**Issue by canastro** [TanStack/query#5699]
### Describe the bug

Currently svelte-query has a peerDependency on ` "svelte": "^3.54.0"`,  now that Svelte 4 has been release it would be nice to update this peer dep version range.

### Your minimal, reproducible example

N/A

### Steps to reproduce

1. Go to any example
2. Update your svelte version to 4
3. Install
4. You'll get a unmet peer dependency

### Expected behavior

As I user I expect to be able to upgrade my app to svelte 4.

### How often does this bug happen?

Every time

### Platform

- OS: any

### Tanstack Query adapter

None

### TanStack Query version

4.29.19

### TypeScript version

5.0.4

**Comment by inzanez** [comment]
Also looking for this.

**Comment by TkDodo** [comment]
@lachlancollins FYI

**Comment by lachlancollins** [comment]
@canastro I've properly bumped this in the v5 alpha, but didn't bump it in the v4 branch. I'll do that now!
