### ISSUE TITLE
useInfiniteQuery is not executed as expected

### ISSUE THREAD

**Issue by supuwoerc** [TanStack/query#5705]
### Describe the bug

My program uses useInfiniteQuery and react-infinite-scroll-component to implement a long list that can scroll indefinitely, and this list supports keywords filtering. I use keywords as part of queryKey. When the keywords change it does request new data as expected, but the second time I set the keyword to an empty string, useInfiniteQuery requests three pages of data instead. After debugging, I found that it was not react-infinite-scroll-component that called the next method several times incorrectly, but useInfiniteQuery would remember the page number of the last request and re-request the page number of the last request. I found that this could not be configured through option. How to solve this problem?

### Your minimal, reproducible example

https://codesandbox.io/s/awesome-fire-58q6ts?file=/src/App.js

### Steps to reproduce

1.Scrolling requests paging data, such as requesting three pages of data
2.At this time, the request for three pages of data, enter any character in the input box, triggering refetch
3.Delete the content entered in the input box, and the request is triggered multiple times, depending on the page number reached in the first step

### Expected behavior

Reset the query when the queryKey changes

### How often does this bug happen?

Every time

### Platform

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

### Tanstack Query adapter

None

### TanStack Query version

4.29.12

**Comment by supuwoerc** [comment]
![16893163883516](https://github.com/TanStack/query/assets/36561218/382590bc-c56a-4d51-ae03-c1fb654ed062)
I found the relevant explanation in the document, this is the feature, I want to this point can add option to choose to close?

**Comment by TkDodo** [comment]
you can set `cacheTime:0` to completely remove unused queries, in which case you'll get a fresh fetch when you come back to the previous keyword.

or, you remove all pages except the first one with `setQueryData` in a useEffect whenever the `keyword` changes.

https://tanstack.com/query/v4/docs/react/guides/infinite-queries#what-if-i-want-to-manually-update-the-infinite-query

**Comment by supuwoerc** [comment]
> you can set `cacheTime:0` to completely remove unused queries, in which case you'll get a fresh fetch when you come back to the previous keyword.
> 
> or, you remove all pages except the first one with `setQueryData` in a useEffect whenever the `keyword` changes.
> 
> https://tanstack.com/query/v4/docs/react/guides/infinite-queries#what-if-i-want-to-manually-update-the-infinite-query

Thanks for answering my question. In fact, I used moveQueries to clear the data cache of the target query. Of course, the easiest way is to set the cacheTime to 0 as you said, and the problem is solved, but I still feel that this design will cause a large number of Request, if the total number of pages is 100, 100 requests will be reissued in order after the query is resumed. I think most developers will think this is a bug just like me...😂

**Comment by TkDodo** [comment]
> if the total number of pages is 100, 100 requests will be reissued

why would you have 100 pages? Do your users scroll down 99 times ? In v5, you can limit the number of pages with `maxPages` to remove old pages. I doubt that you really want 100 pages on screen or in the cache.

re-issuing the query for all pages is necessary for consistency. I've been giving examples 100 times before, but here once more, for posterity:

assume you have 3 pages in the cache with the following values:

```
{
  pages: ['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i'],
  pageParams: [0, 1, 2],
}
```

Now, you do a refetch and only refetch the first page. In the meantime, entry `c` has been deleted. This will lead to the following data being displayed:

```
{
  pages: ['a', 'b', 'd'], ['d', 'e', 'f'], ['g', 'h', 'i'],
  pageParams: [0, 1, 2],
}
```

Note how `d` is now displayed twice, because it moved from page 2 to page 1. By refetching all pages, we assure consistency, because the cache is then:

```
{
  pages: ['a', 'b', 'd'], ['e', 'f', 'g'], ['h', 'i', 'j'],
  pageParams: [0, 1, 2],
}
```

The same goes for inserting elements btw.

**Comment by supuwoerc** [comment]
> > if the total number of pages is 100, 100 requests will be reissued
> 
> why would you have 100 pages? Do your users scroll down 99 times ? In v5, you can limit the number of pages with `maxPages` to remove old pages. I doubt that you really want 100 pages on screen or in the cache.

It may be that my description is inaccurate. I know that before the cache is cleared, react-query will re-issue the request to update the data to ensure the consistency of the data. It should be that there is a deviation in my understanding. The reason why I think this is a bug is Because in the case of scrolling loading, reloading the list generally only needs to re-acquire the first page of data, and subsequent updates are triggered by scrolling events. I understand, thank you for explaining to me and posterity~👍
