### ISSUE TITLE
`vue-query` does not refetch on `queryKey` change

### ISSUE THREAD

**Issue by Dananz** [TanStack/query#5707]
### Describe the bug

Im using nuxt 3 and trying to refetch data for every key change,
As much as I know `useQuery` from my react usage, It should detect key changes and automatically refetch the data.
Unfortunately in `vue-query` it does not refetch the data unless I call `refetch()` inside a watcher like this:

```typescript
const { data, refetch } = useQuery({
  queryKey: ['test', postId.value],
  queryFn: fetcher,
});

watch(
  () => postId.value,
  () => refetch()
);
```

But this breaks caching and force `useQuery` to do a refetch every time.

### Your minimal, reproducible example

https://stackblitz.com/edit/nuxt-starter-ry7tnj?file=app.vue

### Steps to reproduce

1. Open network tab
2. Click on the 1,2,3 buttons
3. You can see that nothing being fetched in the background

### Expected behavior

`useQuery` should refetch for every `queryKey` change.

I've also created a reproduction example using react just to make sure that Im not mistaken and thats how `useQuery` should behave.
https://codesandbox.io/p/sandbox/mystifying-ardinghelli-xcsg7l?embed=1&file=%2Fsrc%2Findex.jsx%3A18%2C27

### How often does this bug happen?

Every time

### Platform

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`

### Tanstack Query adapter

None

### TanStack Query version

4.29.20

### TypeScript version

5.0.2

**Comment by TkDodo** [comment]
I don't know much vue, but one thing I'm seeing is that you are not actually passing the `postId.value` to the `queryFn`:

```
const { data, suspense, refetch } = useQuery({
  queryKey: ['test', postId.value],
  queryFn: () => fetcher(postId.value),
  staleTime: Infinity,
});
```

this is also how it's done in the example:

https://github.com/TanStack/query/blob/f76783ca715c7c757d33c0592a45cf554de14bd4/examples/vue/basic/src/Post.vue#L22-L25

**Comment by TkDodo** [comment]
@DamianOsipiuk fyi

**Comment by DamianOsipiuk** [comment]
```diff
- queryKey: ['test', postId.value],
+ queryKey: ['test', postId],
```

Vue runs `setup` function only once, and you are passing non-reactive value to `vue-query` by using `.value`. Just pass the `ref` itself, `vue-query` will handle the rest.
