### ISSUE TITLE
Next 13 app dir clear() not working

### ISSUE THREAD

**Issue by ShaulBenDavid** [TanStack/query#5726]
### Describe the bug

Try to use clear to clear the query cache and its not working

### Your minimal, reproducible example

https://github.com/ShaulBenDavid/shaul-sanity-blog

### Steps to reproduce

Next 13.4 app
Create a query client 
Fetch data
Try to clear query client

### Expected behavior

Query client need to be reset

### How often does this bug happen?

Every time

### Screenshots or Videos

![IMG_0632](https://github.com/TanStack/query/assets/79593694/4281877a-0ef5-4631-878a-5409e2b1a15f)
![IMG_0631](https://github.com/TanStack/query/assets/79593694/a84b5405-5b3f-4e2b-be00-044719d70c5c)
![IMG_0630](https://github.com/TanStack/query/assets/79593694/b2e6df33-4b1f-4e2f-b0fb-7a727d1c0dac)
![C182E5DA-BB90-4C6E-BBEE-E5ABDFF8E5E5](https://github.com/TanStack/query/assets/79593694/347b5811-a014-4d3a-add6-67ee011e331a)

### Platform

All

### Tanstack Query adapter

react-query

### TanStack Query version

3.39.3

### TypeScript version

5.0.3

**Comment by TkDodo** [comment]
> Expected behavior
Query client need to be reset

what does this mean? What would you expect to happen when `clear` is called? Note: it will remove entries from the QueryCache (you should see empty devtools afterwards), but it will not re-render your component.

Also, please show a _minimal_ reproduction.

**Comment by TkDodo** [comment]
> But like you see in the last picture the queries not reset

this could be for various reasons. Most likely, you are rendering a component that has a `useQuery` hook call for this hook. I can see two disabled observers in that screenshot, which means you _are_ calling `useQuery` somewhere. I can assure you: `queryClient.clear` removes all data from the cache. If that's not the case for you, please show a minimal codesandbox reproduction.
