### ISSUE TITLE
Stuck in Loading

### ISSUE THREAD

**Issue by soranoo** [TanStack/query#5728]
### Describe the bug

The query will be stuck in loading and no request has been sent when I open the site with Chrome and Edge.
It is fine in Firefox.
![image](https://github.com/TanStack/query/assets/46896789/df9241b6-cac9-415e-959e-34fe9c4f20b6)

### Your minimal, reproducible example

https://tanstack.com/query/v4/docs/react/examples/react/simple

### Steps to reproduce

1. Open https://tanstack.com/query/v4/docs/react/examples/react/simple in different browsers.

### Expected behavior

Load the query page successfully
![image](https://github.com/TanStack/query/assets/46896789/f1f865e4-694a-4416-b4a4-8053fe42eeda)

### How often does this bug happen?

Every time

### Platform

- OS: Windows 11 Pro 22H2
- Browser: Google Chrome Version 114.0.5735.199, Microsoft Edge Version 114.0.1823.82, Firefox Version 114.0.1823.82

### Tanstack Query adapter

react-query

### TanStack Query version

\

**Comment by TkDodo** [comment]
https://github.com/TanStack/query/issues/5679
