### ISSUE TITLE
Prevent cache data in data explorer to be changed

### ISSUE THREAD

**Issue by mrniamster** [TanStack/query#5730]
### Describe the bug

Whenever i change anything in my state.data which is a reactive object the data inside the data explorer are also changing,
I would like to get the previousdata , but due to this i cannot ,

```
const fetchAccount = useQuery({
  queryFn: async () => await axios.get(appConfig.api.user.account.get),
  queryKey: ['fetchAccount'],
  onSuccess(response) {
    console.log('smoke', response.data);
    if (!response.data.response_code) {
      confirm({ message: 'Something went wrong, retry later' })
      return;
    }
    state.data = response.data.data

  }
})

```

### Your minimal, reproducible example

https://codesandbox.io/s/new

### Steps to reproduce

```
<template>
 <input v-model="state.data.soc.displayname" />

</template>

<script>
const fetchAccount = useQuery({
  queryFn: async () => await axios.get(appConfig.api.user.account.get),
  queryKey: ['fetchAccount'],
  onSuccess(response) {
    console.log('smoke', response.data);
    if (!response.data.response_code) {
      confirm({ message: 'Something went wrong, retry later' })
      return;
    }
    state.data = response.data.data

  }
})
const state=reactive({
data:{soc:{display:name}}
})
</script>

```

### Expected behavior

The cahce value shouldn't be changed

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/52563039/0a7f3c0a-bd1b-460b-b790-89be801b66ea)

### Platform

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.11.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  npm@9.6.5
- Builder:          vite
- User Config:      experimental, ssr, turnstile, build, hooks, vue, nitro, css, vite, postcss, app, modules, content, googleSignIn, runtimeConfig, devtools
- Runtime Modules:  nuxt-vue3-google-signin@0.0.8, @pinia/nuxt@0.4.11, @nuxt/content@2.7.0, @pinia/nuxt@0.4.11, @vuestic/nuxt@1.0.14, @nuxtjs/turnstile@0.5.0
- Build Modules:    -
------------------------------

### Tanstack Query adapter

vue-query

### TanStack Query version

^4.29.19

**Comment by DamianOsipiuk** [comment]
Codesandbox link does not work.

From the code snippet I can see that you are assigning reference to an object from cache and then mutating it with `v-model`. This will change cached values and will lead to bugs in your app.
You should either clone the part of the object before assigning to local variable or use a library like `immer`.

There is nothing we can do about this from library side, it's an issue with your code.

**Comment by mrniamster** [comment]
Hello @DamianOsipiuk  I am not assigning to object from cache its a local vue setup state if you see, 

The problem is even if i do getQueryData(queryKey) i get the reactive object!

**Comment by mrniamster** [comment]
@DamianOsipiuk  Thank you so much for this ,

Instead of immer, vanilla structuredClone did the job 

One thing i would still like to ask , 

The response which i'm getting in the  ```onSuccess``` , is it coming from the cache you mean  which got initially stored on  fetch ?

**Comment by DamianOsipiuk** [comment]
Yes, `onSuccess` gives you returned value from `queryFn`. But to be honest you should not use `onSuccess` as it will be removed in V5.
Depending on what you want to achieve there are better ways.

**Comment by mrniamster** [comment]
Yes, what will be the callback for onSuccess ? i saw its decerped, have to update both vue and react applications .

**Comment by DamianOsipiuk** [comment]
Callbacks will still be there for `useMutation`.
For `useQuery` you should derive the state ex via `computed`.

**Comment by mrniamster** [comment]
@DamianOsipiuk  
And for React ?
