### ISSUE TITLE
query-devtools package error in 5.0.0-alpha.87

### ISSUE THREAD

**Issue by Jungzl** [TanStack/query#5749]
### Describe the bug

latest version(5.0.0-alpha.87) `@tanstack/react-query-devtools` not display and throw errors

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/dazzling-cookies-kn8n82?file=%2Fsrc%2Fmain.tsx%3A2%2C41

### Steps to reproduce

1. run dev
2. open browser devtools

### Expected behavior

no errors, display correctly

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/35426360/cf3cfdc0-1322-4df1-bc98-418cb36a7c8e)

### Platform

- OS: windows 10
- Browser: FF && Chrome latest

### Tanstack Query adapter

react-query

### TanStack Query version

5.0.0-alpha.87

### TypeScript version

5.1.6

**Comment by Jungzl** [comment]
BTW, v5.0.0-alpha.86 is working

**Comment by TkDodo** [comment]
Must be related to the bundling changes. @lachlancollins FYI

**Comment by lachlancollins** [comment]
Also tagging @ardeora since this seems like it's the query-devtools package! I'll have a chance to look at it shortly.

**Comment by lachlancollins** [comment]
@ardeora this also doesn't work in svelte-query devtools. It seems like the `index.cjs` file bundles everything internally including `_tmpl$23`, while the `index.js` and `index.jsx` files split their imports. I can undo this by adding `splitting: false`, but I think splitting is needed for the lazy loading?

**Comment by ardeora** [comment]
@lachlancollins  Yeah that wont work and we need the code splitting anyway. I took a look at this and looks like the esbuild plugin is failing on packaging the solid-js dependencies correctly. The `template` function specifically is not correctly configured. I'm taking a look at how to get this fixed

**Comment by lachlancollins** [comment]
@ardeora I merged [this PR](https://github.com/solidjs-community/tsup-preset-solid/pull/4) to update tsup (7.1.0) and esbuild-plugin-solid (0.5.0), I'll see if updating this works.

**Comment by ardeora** [comment]
This issue has now been fixed in alpha.89 Please take a look at the updated sandbox [here](https://codesandbox.io/p/sandbox/interesting-tess-ykknc3?file=%2Fpackage.json%3A13%2C45)
