### ISSUE TITLE
Incorrect query invalidation for bidirectional infinite queries

### ISSUE THREAD

**Issue by lithdew** [TanStack/query#5767]
### Describe the bug

I have a bidirectional cursor paginated API (which takes "before" / "after" query parameters) which is queried as an infinite query with getPreviousPageParam() and getNextPageParam() defined.

```js
useInfiniteQuery({
  queryKey: ["projects"],
  queryFn: ({ pageParam }) => {
    if (pageParam.before !== undefined) {
      return axios
        .get(`/api/projects?before=${pageParam.before}`)
        .then((res) => res.data);
    }
    if (pageParam.after !== undefined) {
      return axios
        .get(`/api/projects?after=${pageParam.after}`)
        .then((res) => res.data);
    }
    return axios.get(`/api/projects`).then((res) => res.data);
  },
  defaultPageParam: {},
  getPreviousPageParam: (firstPage) => {
    if (firstPage.length === 0) return;
    return { before: firstPage[0].id };
  },
  getNextPageParam: (lastPage) => {
    if (lastPage.length === 0) return;
    return { after: lastPage[lastPage.length - 1].id };
  },
});
```

Invalidating the infinite query erroneously causes the next refetch to call the API with `/api/projects?before=0`. The infinite query I believe should instead have the next refetch call the API with `/api/projects` (the `defaultPageParam` should be used).

In the demo I provide, this behavior causes the entire infinite query to wipe away all of its cached data as the data returned from `/api/projects?before=0` is an empty array.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/dawn-wave-dxw3tf?embed=1&file=%2Fsrc%2Fpages%2Findex.js%3A34%2C34

### Steps to reproduce

1. Load previous data by clicking on `"Load Older"`.
2. Click on the `["projects"]` query in the devtools.
3. Click `"Invalidate"`.
4. Erroneously, all the query data is erased.
5. (optionally) add a `console.log` into `queryFn` and notice that the `pageParam` after invalidation is set to `{ before: 0 }` and the `direction` is `forward`. 

### Expected behavior

As a user, I expected that the invalidation of the bidirectional infinite query would have the next refetch call the API with `defaultPageParam`, but I am seeing that the next refetch calls the API with a direction of `forward` with the last known `previousPageParam`. 

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 114.0.5735.133 (Official Build) (arm64)

### Tanstack Query adapter

react-query

### TanStack Query version

v5.0.0-alpha.81

### Additional context

There is a possibility that it might be the case that cursor-paginated API's were not intended to be used with infinite queries. Or, it might be that this behavior is intentional and I am missing something in hindsight to support paginating through a cursor-based API with regards to how getPreviousPageParam() and getNextPageParam() should be defined.

Given that the outputs of getPreviousPageParam() and getNextPageParam() are cached as `pageParams` in the infinite query's data, and query invalidation starts from the first entry in `pageParams`, the only way I assume that it is possible for the library to support bidirectionally traversing through cursor-paginated API's is if the cursor-paginated API returns the first full non-truncated page of data even if the last available `getPreviousPageParam()` precedes the very first cursor available from the API.

**Comment by TkDodo** [comment]
when an infinite query is invalidated, it starts at the first page it sees, and traverses all pages forward from there on by invoking `getNextPageParam`. This might not be the first page you initially fetched if you have traversed in the "previous" direction before. That's also why `getNextPageParam` is required (and `getPreviousPageParam` isn't).

The problem in your example seems to be that we are getting an empty page into the first slot. Ideally, we wouldn't be able to press `load older` in the first place, because there is nothing to load before id `0`.

If the cursors where computed on the backend, and send as part of the result, the first page would probably yield something like:

```
{
  items: [{...}, {...}, {...}, {...}],
  next: 'after=3'
  before: null 
}
```

or something along those lines, so it wouldn't even allow us to `load older`.

---

Alternatively, we also provide the `fetchDirection` as a `direction` param into the `queryFn`. It can be `'backward' | 'forward'`, and it indicates in which direction the infinite query is currently fetching. For a refetch, this will always be `forward`. So we can change the implemention of your `queryFn` to only fetch with `before=` if we have a backward direction:

```diff
+ queryFn: ({ pageParam, direction }) => {
+  if (direction === 'backward' && pageParam.before !== undefined) {
    return axios
      .get(`/api/projects?before=${pageParam.before}`)
      .then((res) => res.data);
  }
  if (pageParam.after !== undefined) {
    return axios
      .get(`/api/projects?after=${pageParam.after}`)
      .then((res) => res.data);
  }
  return axios.get(`/api/projects`).then((res) => res.data);
},
```

with that, refetches should work as expected:

https://codesandbox.io/p/sandbox/zealous-pike-j3qnj9?embed=1&file=%2Fsrc%2Fpages%2Findex.js%3A40%2C33

**Comment by lithdew** [comment]
> If the cursors where computed on the backend, and send as part of the result, the first page would probably yield something like:
> 
> ```
> {
>   items: [{...}, {...}, {...}, {...}],
>   next: 'after=3'
>   before: null 
> }
> ```
> 
> or something along those lines, so it wouldn't even allow us to `load older`.

What about cases where it isn't possible for the infinite query and the backend to know if there are anymore previous pages until new data is pushed to the backend?

A common use case for example would be Twitter or any other social media site which has a cursor-paginated API for fetching the latest posts. A `/feed` API endpoint would return all posts sorted chronologically in descending order by each posts' `createdAt` field.

Consider the scenario:
1. I load the homepage containing all posts from `/feed`.
2. Concurrently, I publish a new post on the homepage, and other users also publish a new post as well.
3. After publishing a new post, I invalidate the infinite query for `/feed`.
4. New previous pages for the infinite query for `/feed` should contain the new post I published alongside all the other posts that other users have published at the same time.

**Comment by TkDodo** [comment]
would this example not be fixed with the `direction` check inside the queryFn, like my forked codesandbox shows?

**Comment by lithdew** [comment]
Yes, clicking on Load Older multiple times causes the previous page to appear twice in the infinite query cached data.

**Comment by TkDodo** [comment]
> Yes, clicking on Load Older multiple times causes the previous page to appear twice in the infinite query cached data.

hmm, if you click `load older` once and you get an empty array back, you should definitely disable the `load older` button ...

**Comment by lithdew** [comment]
> hmm, if you click `load older` once and you get an empty array back, you should definitely disable the `load older` button ...

What about the case where previous pages may become available like in the Twitter/social media example I gave? In that case, the `Load Older` button shouldn't be disabled.

**Comment by TkDodo** [comment]
I think you would get that with a `refetch`. If you refetch, e.g. on window focus or in an interval, you would refetch the first, empty page, and if it has results, you would enable the `load older` button again automatically.
