### ISSUE TITLE
'structuralSharing' has incorrect type when combined with 'select'

### ISSUE THREAD

**Issue by levidrain** [TanStack/query#5806]
### Describe the bug

When using both select and structuralSharing, structuralSharing is incorrectly typed to the query result instead of the result of the select parameter.

### Your minimal, reproducible example

https://www.typescriptlang.org/play?ts=4.9.5#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ4A0c2ueA0uoXAKoYn4DyYMwEAdqnAL5wBmUEEHADkAARgBDDpIDGAawD0UdBJkwAtAEcc+YQG4AsAChjvZGzWs2cAGIQIACgCUiY3Hco6OvA4RuPAdqkFHgAXHAA2gBEcpRRALoE-gHuQfg2bOESqHgWcM5wALwAfHASAO4SwPBRABLoADYNEHAA6tANACZRSUYpHhgN6GrhqDBQRaVjUAB0Q2wA5jAAFr397tPIashQEg0AyssSUMCL4Q4SRABGLiWufesBCgpwbBAsMuhwKxLwK1+oYALNi-HZfCC8b7LYCcGHfPBgdCdb4taanBbXZDwarCTiqGDIPYNPBwMDZDDI-6vZAgK64PgCISDYYwZKPODKAlQaxRKKGB79LhsrhOflcIA

### Steps to reproduce

Create a query with both a select and structualSharing.  The select should return a different type from the queryFn. 

### Expected behavior

The structuralSharing function is typed to accept the queryFn return, but is actually passed the select return.

### How often does this bug happen?

Every time

### Platform

- Typescript 4.9.5
- VS Code

### Tanstack Query adapter

react-query

### TanStack Query version

4.29.3

### TypeScript version

4.9.5

**Comment by TkDodo** [comment]
yeah, `structuralSharing` is applied to both the result of the `queryFn` _as well as_ the result of `select`.

I think it would be best to widen the types of `structuralSharing` to `a: unknown, b: unknown`. Imo, if a custom `structuralSharing` is implemented, it's something that you'd usually do on a global level for all queries / some queries that have a specific key anyways.

would that work for you? would you want to contribute it ?

**Comment by TkDodo** [comment]
> I added console logs to the structuralSharing callback and it appears to only call this function with the post select data.

show a codesandbox reproduction please. I'm pretty sure we first have to call `structuralSharing` for the `data` that is returned from the `queryFn`, so that we get a stable input to `select`. Then, the result of `select` is also structurally shared as an optimization.

**Comment by roalonso** [comment]
Why was `unknown` used instead of `TQueryFnData | TData`?

**Comment by TkDodo** [comment]
because `structualSharing` runs on query level, and `TData` is only known on observer level.
