### ISSUE TITLE
Cursor jumps at the end when using data returned from query as value for input

### ISSUE THREAD

**Issue by tarasowski** [TanStack/query#5823]
### Describe the bug

Basically, when I retrieve data from a query, I display it as the value of an input field. However, when changing the value, the cursor jumps to the end of the input field. This behavior only occurs when using the returned data from a query; using useState doesn't exhibit this issue. What is the best way to resolve this problem? I have found a workaround by changing the value via reference in onSuccess, but this seems to be a very hacky solution to me.

### Your minimal, reproducible example

localhost

### Steps to reproduce

1. Use a textarea or input component
2. Add returned data from a query as value
3. Create an onChange handler where you use queryClient.setQueryData to change the value

### Expected behavior

The cursor should stay where it is and don't jump to the end of the input / textarea field

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/query/assets/33748291/21a37e1a-e3af-4bc5-936f-c81734faa22a

### Platform

MacOs
Chrome

### Tanstack Query adapter

None

### TanStack Query version

@tanstack/react-query": "^4.29.25",

### Additional context

Nothing

**Comment by TkDodo** [comment]
You're not showing a reproduction I can try out. Please add a minimal codesandbox next time.

> Create an onChange handler where you use queryClient.setQueryData to change the value

You can't and shouldn't use react-query to manage synchronous client state. The single source of truth for your `query` should be your `queryFn`. The only reason when it's ever correct to write to the query Cache manually is after a mutation or for optimistic updates. If you write to the cache when the user types, a refetch could overwrite that with the current server state.

So, you need separation between server state and client state. I have a blogpost on that topic: https://tkdodo.eu/blog/react-query-and-forms
