### ISSUE TITLE
Re-ordering cached array does not trigger re-render

### ISSUE THREAD

**Issue by nemmtor** [TanStack/query#5829]
### Describe the bug

When updating query cache by re-ordering the values, react does not re-render even if I create new reference of array.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/crazy-ramanujan-t63rmc

### Steps to reproduce

1. Open sandbox
2. Click `re-order` button
3. Array gets reordered, return value is spread so there shouldn't be reference problem
4. Query cache is updated
5. Component does not re-render
6. Click `force re-render`
7. Component does re-render, re-ordered array is visible in UI

### Expected behavior

Component re-renders after setting query data with re-ordered array.

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/query/assets/50832972/384848e4-8169-4de7-be81-cd26165a812d

### Platform

- OS: MacOS
- Browser: Chrome
- Version: Version 115.0.5790.114 (Official Build) (arm64)

### Tanstack Query adapter

react-query

### TanStack Query version

^4.2.3

### TypeScript version

^4.5.4

**Comment by gmaxlev** [comment]
I guess your problem is related to structural sharing, try to disable it using `structuralSharing: false` in the options.

**Comment by nemmtor** [comment]
@gmaxlev works great, thanks

**Comment by TkDodo** [comment]
your problem is actually that `cache.sort` mutates cache in-place.

the fix is:

```diff
queryClient.setQueryData(["foo"], (cache) => {
-  const sortedCache = cache.sort((a, b) => b - a);
+  const sortedCache = [...cache].sort((a, b) => b - a);
-  return [...sortedCache];
+  return sortedCache;
});
