### ISSUE TITLE
usemutation overload: Object literal may only specify known properties, and 'mutationFn' does not exist in type 'readonly unknown[]'.

### ISSUE THREAD

**Issue by spiritoftime** [TanStack/query#5835]
### Describe the bug

In sum, I basically have a useMutation function 
```
  const { mutate: transformCloudinaryMutation } = useMutation({
    mutationFn: ({
      fileName,
      prompt
    }: {
      fileName: string;
      prompt: string;
    }) => {
      console.log("hi");
    },
    onSuccess: (cloudinaryData: string) => {
      console.log("succeeded");
    }
  });
```
and i am getting 
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ mutationFn: ({ fileName, prompt }: { fileName: string; prompt: string; }) => void; onSuccess: (cloudinaryData: string) => void; }' is not assignable to parameter of type 'MutationKey'.
      Object literal may only specify known properties, and 'mutationFn' does not exist in type 'readonly unknown[]'.ts(2769)
useMutation.d.ts(6, 25): The last overload is declared here.
```
According to https://stackoverflow.com/questions/31816061/why-am-i-getting-an-error-object-literal-may-only-specify-known-properties, it seems that I may want to click into .ts(2769) and edit the source code for usemutation. However, I think it is more likely that I am doing something wrong instead.

### Your minimal, reproducible example

https://codesandbox.io/s/react-typescript-forked-hlnf95?file=/src/App.tsx

### Steps to reproduce

hover over the mutationFn at App.tsx

### Expected behavior

no typescript error

### How often does this bug happen?

None

### Platform

Windows 10

### Tanstack Query adapter

None

### TanStack Query version

4.28.0

**Comment by weebao** [comment]
I am experiencing the same problem. How did you solve it?
