### ISSUE TITLE
`suspense()` won't resolve when initial `enabled` is set to `false`

### ISSUE THREAD

**Issue by Mini-ghost** [TanStack/query#5845]
### Describe the bug

When `enabled` is initially set to `false`, the `suspense()` function will never resolve. One scenario where this is relevant is when you want `useQuery` to execute only on the client site.

```ts
const { data,  } = useQuery({
  queryKey: ['TEST'],
  queryFn: async () => { 
    // .... 
  },

  //  Disabled when on the server site or due to other factors
  enabled: process.client,
});

if (process.client) {
  await suspense();
} else {
  onServerPrefetch(suspense);
}
```

If you execute this code, you'll notice that the web request never completes because `suspense()` never gets resolved.

### Your minimal, reproducible example

https://stackblitz.com/edit/nuxt-starter-et73sx?file=app.vue,plugins%2Fvue-query.ts

### Steps to reproduce

1. Open reproduction
2. Click Open in New Tab ()
3. **page request never ends `suspense()` is never resolved.**

### Expected behavior

If the query is disabled, `suspense()` should resolve immediate

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Chrome
- Version: 4.32.6

### Tanstack Query adapter

vue-query

### TanStack Query version

v4.32.6

**Comment by DamianOsipiuk** [comment]
Related issue https://github.com/TanStack/query/issues/4924
It was done on purpose to support two use-cases.
There are easy ways to prevent suspending on the server when query is disabled, so I do not think we need to change it.

**Comment by Mini-ghost** [comment]
Oh! I didn't even notice this issue! That does seem very reasonable. Thank you.
