### ISSUE TITLE
Initial static render for `useInfiniteQuery` with `initialData` returns the data directly

### ISSUE THREAD

**Issue by scottrepreneur** [TanStack/query#5849]
### Describe the bug

Been having this bug mess with me a couple of times.

It seems on the initial static render via Next when `useInfiniteQuery` is provided `initialData` it will return the data directly instead of adapting it to the expected return data type (`{ pages: [], pageParams: [] }`) for `useInfiniteQuery`. If you pass an array to `initialData`, that array is provided back as `data` from the hook. After a subsequent render (invalidate query), it will properly return as the expected data type.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/charming-forest-5s5fqw

### Steps to reproduce

1. add `useInfiniteQuery` to a next SSR route
2. pass data from props to `initialData` (an array of data)
3. compare `initialData` to data returned from initial render of useInfiniteQuery
4. the data returned initially is the exact array of data passed to `initialData`

- after initial paint, invalidate the query and it will pass the (fresh?) data correctly

### Expected behavior

As a user, I'd expect the initial render with `initialData` to be parsed the same as would be in subsequent calls to fetching new pages.

### How often does this bug happen?

Sometimes

### Screenshots or Videos

From the sandbox above, we're logging `initialData` (9) being passed into the hook and `data` (13) being returned from the hook.

<img width="716" alt="Screenshot 2023-08-07 at 21 48 13" src="https://github.com/TanStack/query/assets/1778380/38a74373-5699-4603-90d5-a8261d1135f6">

With the first render line 13 outputs the `initialData` array directly. This will throw off dependent functions that are expecting the key for `pages`.

### Platform

- OS: Mac OS
- Browser: Arc
- Version: 1.2.1 (Chromium 115)

### Tanstack Query adapter

react-query

### TanStack Query version

v4.28.0

### TypeScript version

--

### Additional context

I'm not sure if this is actually a bug but it popped up with minimal changes to my code and I haven't found a better way to reproduce it. Hoping someone has maybe seen this before. The problem is especially when the query doesn't run "again" initially and my dependent functions are expecting a `pages` array, etc. I wasn't able to reproduce that part specifically, where I can see the data loaded directly, invalidate that query and the data populates as expected.

Not passing `initialData` alleviates the issue, since it does a fresh fetch on load.

On my project, also tried using rq v4.32.6 & ts v5.1.3 with similar results.

**Comment by scottrepreneur** [comment]
Ah, you can further consistently reproduce by passing a default `staleTime` to the query client. The only thing returned from the hook then is the original data structure. Is this expected?

**Comment by TkDodo** [comment]
`initialData` needs to have the same type / structure as real data. For infinite queries, that means it needs to be `{ pages: [], pageParams: [] }`. You can't put "just an array" as initialData into an infinite query.

> Ah, you can further consistently reproduce by passing a default staleTime to the query client. The only thing returned from the hook then is the original data structure. Is this expected?

When you have `staleTime` set, your `initialData` is seen as fresh data and thus, there will be no additional background refetch. see: https://tkdodo.eu/blog/placeholder-and-initial-data-in-react-query

**Comment by scottrepreneur** [comment]
Ok thanks! I couldn't find an example with both infinite query and initial data, but that makes sense 🙏
