### ISSUE TITLE
Wallaby.js test runner giving errors when attempting to run Vitest unit tests

### ISSUE THREAD

**Issue by arnoud-dv** [TanStack/query#5852]
### Describe the bug

[Wallaby.js](https://wallabyjs.com/docs/index.html) is a plugin that runs unit tests while typing in various IDE's. It supports Vitest but on the beta branch I get errors while attempting to run the tests through Wallaby.js

While not free I like using it as it gives a fast feedback cycle while developing and writing unit tests. Note there is a [free license](https://wallabyjs.com/oss/) available for OSS projects.

### Your minimal, reproducible example

https://github.com/TanStack/query/tree/beta

## Visual Studio Code
- Install the Wallaby.js extension
- CTRL/CMD + Shift + P
  - choose *Wallaby.js: select configuration*
  - choose *Automatic Configuration <custom directory>*
  - select a package, for example query-core
  - Wallaby.js will attempt to run unit tests but gives the following error:
  
![image](https://github.com/TanStack/query/assets/6420061/1a8d440f-1577-47ec-bc84-ea78f024d034)

## Webstorm
- Install the Wallaby.js extension
- Add a run configuration as in the screenshot:
![image](https://github.com/TanStack/query/assets/6420061/ae9efd96-e294-4e2d-a57c-1f51b15d617d)
- Wallaby.js will attempt to run unit tests but gives the following error:
![image](https://github.com/TanStack/query/assets/6420061/dcf9029a-f697-4b92-9ed7-a2f33fcf3b69)

### Expected behavior

I expected Wallaby.js to be able to run the Tanstack Query unit tests.

### How often does this bug happen?

Every time

### Platform

- OS: Linux Fedora but probably all operating systems

### Tanstack Query adapter

None

### TanStack Query version

v5.0.0-beta.15

### TypeScript version

5.0.4

### Additional context

I was able to fix this and will submit a PR

**Comment by webprofijt** [comment]
Noticed jsdom is a root dependency which didn't seem right to me, just having it as a sub dependency would be preferable I think. Removing it helped fix this issue.

Also added @vitest/runner as dependency as mentioned here:

              @lucastraba - it sounds like you must be using `pnpm`, if so, it's expected that you will need to install `@vitest/runner`. If you're not using `pnpm`, could you please let us know what package manager you are using? By default, you don't need to install `@vitest/runner`.

_Originally posted by @smcenlly in https://github.com/wallabyjs/public/issues/3146#issuecomment-1577583039_

**Comment by TkDodo** [comment]
we couldn't get wallaby to run at all with our repo, so I'm currently labelling this as wontfix, sorry.

**Comment by smcenlly** [comment]
I'm from the Wallaby team. I understand you've closed the issue and marked as `wontfix` but we are happy to help you get this working if you change your mind.

The first step, as mentioned [here](https://github.com/TanStack/query/pull/5853#issuecomment-1678584435) would be to get `vitest` running from the mono repo root with `pnpm exec vitest`. I expect you'd need to set up a [vitest workspace configuration](https://vitest.dev/guide/workspace.html) for this. If you get `vitest` working from the root of your mono repo, I expect Wallaby will work for you.
