### ISSUE TITLE
Continuous writings using custom IndexedDB persister

### ISSUE THREAD

**Issue by frederikhors** [TanStack/query#5854]
### Describe the bug

Hi people!

I'm using Svelte, `idb-keyval` and a custom persister [as documented here](https://tanstack.com/query/v4/docs/react/plugins/persistQueryClient#building-a-persister) and [suggested here](https://github.com/TanStack/query/discussions/5378#discussioncomment-6240652):

```ts
import { persistQueryClient, type Persister, type PersistedClient } from '@tanstack/query-persist-client-core';
import { QueryClient, setQueryClientContext } from '@tanstack/svelte-query';
import { get, set, del, createStore, type UseStore } from 'idb-keyval';

const queryClient = new QueryClient();

export function initQueryClient() {
	setQueryClientContext(queryClient);
}

function createIDBPersister(store: UseStore): Persister {
	return {
		async persistClient(client: PersistedClient) {
			set("custom-db", client, store);
		},
		async restoreClient() {
			return await get<PersistedClient>("custom-db", store);
		},
		async removeClient() {
			await del("custom-db", store);
		}
	};
}

export function restoreQuery(): () => void {
	const store = createStore("custom-db", "custom-db");

	const persister = createIDBPersister(store);

	const [unsubscribe, promise] = persistQueryClient({
		queryClient,
		persister,
	});

	promise.then(() => {
		queryClient.mount();
	});

	return () => {
		unsubscribe();
		queryClient.unmount();
	};
}
```

I'm trying this for a list of 100 elements (I know, it's a lot and I'll try to optimize in the future).

Debugging performances I saw these ~7 seconds of IDB's `put()` calls:

![image](https://github.com/TanStack/query/assets/41120635/d54a81af-81f3-416a-a9bd-429543fee3e0)

![image](https://github.com/TanStack/query/assets/41120635/026f722e-21fe-44bb-8051-a1fac0cf4948)

`put` comes from  `idb-keybal`'s `index.js`:

![image](https://github.com/TanStack/query/assets/41120635/795078e8-462c-4555-9748-4eb68a94b01a)

### Your minimal, reproducible example

I'll post in a few moments.

### Steps to reproduce

I'll post in a few moments.

### Expected behavior

Coming from `urql` (they also use `IndexedDB` there) I thought `@tanstack/query` worked by storing the data in memory first storing them only later in the persistor (maybe when CPU is idle).

Here instead I see continuous writings. Where am I doing wrong?

### How often does this bug happen?

Every time

### Platform

Windows 10 x64.

### Tanstack Query adapter

svelte-query

### TanStack Query version

4.32.6

### TypeScript version

5.1.6

**Comment by frederikhors** [comment]
I managed to use the below code to mitigate writes to IndexedDB, what do you think?

```ts
import { debounce } from 'lodash-es';

function createIDBPersister(store: UseStore): Persister {
  return {
    persistClient: debounce(async function (client: PersistedClient) {
      set("custom-db", client, store);
    }, 1000),
    async restoreClient() {
      return await get<PersistedClient>("custom-db", store);
    },
    async removeClient() {
      await del("custom-db", store);
    },
  };
}
```

1. Can there be any problems using this?

1. @sharmapukar217 [mentioned here](https://github.com/TanStack/query/discussions/5378#discussioncomment-6674939) that I can provide a filter for cache writes; can you show me an example?

1. Why can't I use an `async` custom persister? Can I use IndexedDB with `createAsyncStoragePersister`?

**Comment by TkDodo** [comment]
> I thought @tanstack/query worked by storing the data in memory first storing them only later in the persistor (maybe when CPU is idle).

yes, in react, we only write in an effect and in a throttled way, so it shouldn't block.

https://github.com/TanStack/query/blob/1d3ee672d2a1536e3463243813c91902aa97d973/packages/query-async-storage-persister/src/index.ts#L66

I think the idea would be to use our `createAsyncStoragePersister`, but use IndexDB as a `storage`?

all you'd need to satisfy is this interface:

https://github.com/TanStack/query/blob/1d3ee672d2a1536e3463243813c91902aa97d973/packages/query-async-storage-persister/src/index.ts#L8-L12

**Comment by frederikhors** [comment]
In that interface `getItem` and the others refer to what? Cache object entirely?

**Comment by TkDodo** [comment]
`getItem` gets an item from your external persistent cache. an `item` is usually the complete persisted client, so, a big string with json in it (but it shouldn't really matter what it is).

**Comment by DamianOsipiuk** [comment]
@frederikhors You could try the new v5 feature https://tanstack.com/query/v5/docs/react/plugins/createPersister to get more granular storage which should help with performance.

**Comment by TkDodo** [comment]
I think the problem here is merely that there is no throttling on the writes in the custom persister. Also, this never came:

> Your minimal, reproducible example
I'll post in a few moments.

> Steps to reproduce
I'll post in a few moments.

So closing.

**Comment by frederikhors** [comment]
Sorry for the late response. I'm using v5 and `createPersister` now: https://github.com/TanStack/query/discussions/6213.
