### ISSUE TITLE
Svelte query - query does not react to changing default options by queryClient.setDefaultOptions in runtime

### ISSUE THREAD

**Issue by Pawel-Zygmunt** [TanStack/query#5855]
### Describe the bug

I have initialized QueryClient in main +layout.svelte:
```
const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        enabled: browser,
        refetchInterval: $dataRefetchIntervalS * 1000
      }
    }
  });

  $: {
    queryClient.setDefaultOptions({
      queries: {
        ...queryClient.getDefaultOptions().queries,
        refetchInterval: $dataRefetchIntervalS * 1000
      }
    });
  }
```

then, somewhere in my app on route /example i have:
```
const streamsQuery = createQuery({
    queryKey: ['streams'],
    queryFn: async () => {
      const res = await fetch(`${PUBLIC_API_KEY}/streams`);
      const data = await res.json();
      return data.map(streamMapper);
    }
  });
  $: ({ data, status } = $streamsQuery);
```
`$dataRefetchIntervalS` as reactive store can be changed and should cause that streamsQuery would react to a new value, but its not. StreamsQuery updates it's options only when unmounted and mounted again - while for e.g changing routes withing app. 

### Your minimal, reproducible example

https://stackblitz.com/edit/stackblitz-starters-megwxq?description=React%20%20%20TypeScript%20starter%20project&file=src%2Findex.tsx,src%2FApp.tsx&title=React%20Starter

### Steps to reproduce

Reproducted the same behaviour in react and works fine.

### Expected behavior

Queries should react to defaultOptions changed by queryClient.

### How often does this bug happen?

Every time

### Platform

- OS: any
- Browser: any

### Tanstack Query adapter

svelte-query

### TanStack Query version

5.0.0-beta.15 but also in stable version

### TypeScript version

5.0.0

**Comment by Pawel-Zygmunt** [comment]
@lachlancollins any progress on this ?

**Comment by softgripper** [comment]
Is this the at the bottom of the overview docs?

Where you need a derived store?

https://tanstack.com/query/v5/docs/svelte/overview

**Comment by TkDodo** [comment]
this is a general design decision in the query core. Calling `queryClient.setQueryDefaults` is not an operation that has any effect on already existing queries - the defaults are only taken into account when the query is created.

**Comment by mihnea-tirca** [comment]
Hi @TkDodo. I'm trying to do basically the same thing: dynamically modify staleTime (with a call to the backend that gets as response a fetching configuration that includes a staleTime value). How would I make this work? I have tried doing queryClient.removeQueries() after setting calling queryClient.setDefaultOptions() and it still doesn't work.

**Comment by TkDodo** [comment]
> I have tried doing queryClient.removeQueries() after setting calling queryClient.setDefaultOptions()

should work I think, show a reproduction?

**Comment by mihnea-tirca** [comment]
I figured out the problem... :D I didn't take the documentation's advice to heart (regarding[stable query client](https://tanstack.com/query/latest/docs/eslint/stable-query-client)) and I was invalidating queries on the wrong QueryClient instance.  I didn't know it was creating multiple instances, so I fixed it and made it a singleton and everything works perfectly fine.
