### ISSUE TITLE
Local caheTime is been overriden by global default cache time when using PersistQueryClientProvider

### ISSUE THREAD

**Issue by subbiah28062** [TanStack/query#5868]
### Describe the bug

I am using @tanstack/react-query-persist-client and @tanstack/query-sync-storage-persister for persisting queries, but on using these, I am facing below issue

```
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      cacheTime: Infinity,
      retry: false,
      refetchOnWindowFocus: false,
      refetchOnMount: false,
      refetchOnReconnect: false,
      staleTime: Infinity,
    },
  },
});
```

```
useQuery(
    ["saudi"],
    () => {
      return fetch("https://restcountries.com/v3.1/name/Saudi%20Arabia").then(
        (response) => {
          return response.json();
        }
      );
    },
    {
      cacheTime: 3000,
    }
  );
```

Everything works well at first, but after refreshing Saudi query is not getting removed at 3000ms. Because after refresh somehow local cacheTimes are getting overridden by default cacheTime.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/use-query-persister-issue-7ytxn4?file=/src/App.tsx:40,7

### Steps to reproduce

1. open inspect element
2. open link
4. App will fetch `https://restcountries.com/v3.1/all`
6. click the switch button
8. App will fetch `https://restcountries.com/v3.1/name/Saudi%20Arabia`
9. refresh
10. App won't fetch `https://restcountries.com/v3.1/all` as the default cache time is Infinity and there is no local cache time
11. Click the switch button
12. App should fetch `https://restcountries.com/v3.1/name/Saudi%20Arabia` as the local cache time is 3000 seconds, but the app won't fetch instead will show data from the cache

### Expected behavior

After refreshing, and the switch button click, The app should fetch `https://restcountries.com/v3.1/name/Saudi%20Arabia` as the local cache time is 3000 seconds, but the app won't fetch instead will show data from the cache

### How often does this bug happen?

Every time

### Screenshots or Videos

https://drive.google.com/file/d/1FscVWMlntlS3akJ3l5FGJj1Kf2eC-Tex/view?usp=sharing

### Platform

Browser

### Tanstack Query adapter

react-query

### TanStack Query version

4.29.12

### TypeScript version

5.0.2

**Comment by TkDodo** [comment]
not sure I fully understand the issue. I think you have `staleTime` and `cacheTime` mixed up. If you want to see a refresh when a component mounts, `staleTime` is the one you want to set. `cacheTime` will be renamed to `gcTime` in v5, because it's a more accurate name for what it does: it's about garbage collecting a Query when it is unused. Your Query isn't unused, so cacheTime does nothing ...

**Comment by subbiah28062** [comment]
@TkDodo Thanks, that solves my issue.

By the name cacheTime i assumed it will be the amount of time data will be cached and refreshed after that, my bad, thanks for the explanation.
