### ISSUE TITLE
Error in github action npm ci when installing react-query devtools

### ISSUE THREAD

**Issue by jsvelte** [TanStack/query#5872]
### Describe the bug

This is in my github actions
![image](https://github.com/TanStack/query/assets/108642414/539d38d3-a0d4-4eda-a1bd-74423cba696d)

This is in my code added
![image](https://github.com/TanStack/query/assets/108642414/aee8f7a0-3c7f-4d3c-bac8-eda57cd9c475)

This is in my package.json
![image](https://github.com/TanStack/query/assets/108642414/1707d3a5-7929-4107-a683-c1b3a1f07d58)

It fails here
![image](https://github.com/TanStack/query/assets/108642414/fb49306a-9b0b-4249-9bf8-eed4eb5473fc)

everything works fine not unless if I setup it in my local and pushed it in github it's not compatible. So what I usually do if I want to merged my task I need to uninstall the devtools first to make it success result

### Your minimal, reproducible example

No sandbox here

### Steps to reproduce

The steps is on the top

### Expected behavior

the step behavior is on the top

### How often does this bug happen?

Every time

### Platform

- Browser Brave

### Tanstack Query adapter

react-query

### TanStack Query version

^4.22.0

### Additional context

The tanstack version is ^4.22.0

**Comment by TkDodo** [comment]
if you use `4.32.6` of the devtools, you also need to use `4.32.6` of react-query itself.

**Comment by jsvelte** [comment]
Thank you for your answer still not working

**Comment by TkDodo** [comment]
then please create an open source repo that shows the issue.

> everything works fine not unless if I setup it in my local and pushed it in github it's not compatible.

have you tried cleaning `node_modules` and running `npm ci` locally? Should show the same result as in CI. It really looks like you haven't updated the lockfile 😅
