### ISSUE TITLE
bug(vue): clientPersisterOnSuccess does not exist

### ISSUE THREAD

**Issue by bazuka5801** [TanStack/query#5876]
### Describe the bug

```ts
interface CommonOptions {
    queryClientKey?: string;
    contextSharing?: boolean;
    clientPersister?: ClientPersister;
}
```

Based on the doc https://tanstack.com/query/v4/docs/vue/guides/mutations#persisting-offline-mutations
we can use `clientPersisterOnSuccess`, but types is missing.

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRQK4FMoE8DCAbYdAO3gF84AzKCEOAcgDoB6ARw230JLoG4AoUJFhwYWMOkQp2uAsRg4IRCsADmcclRr0AAjACGRAM76AxgGtW0gLQno6XgPDR4o8ZICyerACN0AJXQKABF0dDB1SmpaRiZXdEMHABN0Ezw9KAkVPAhvPTxEPjgiuGASTAo9EwkAdVLEiAB3AuKWuAB9NoA1AFUAUTbkPr8ATTacAHkAOQAVXoANaY6AfgAuKUwZLhh+FtI+PeTU9Ik4uE45AAVMQ2BjTDgAXjgAClSttbQN85IASkeAPjgAG1nn8HoCAG4QYCJAA0cAuUVu6AAPFCYf8ALr8UowcqVCQKEAgRTjMAwYCKQzNYpsL6yEgAaXQWFWcGMUFKKh2xVsZQAHjAAMoAC3SXLZ3ggEDw6AMPKKb0u11ueKgbO+MCuUBudyg-D2uPxVTOimUKjJFKpcHQguIiWpRJJREtlKMNKKdI4DPkZtUbM8Pn8gRCYRRn29WwUSlU-wNAjKUAqJs1ruttrxRAdpuJpPJbupCEKtOkmrZEc2cnjhzSGREYgknQwFYueFQKlKafdT2j5q71IAPmcff3+Hxx3zjHAIc3pP21k30C22x2XfnrU8i4qfdrdWrxkQhagTFVDIY1s8vZXfgCPXAr5qGBlDKgQOgLnpUIZ0Il3Kh9FaRigsWpCwvsQA

### Steps to reproduce

1. try to use `clientPersisterOnSuccess` on vue.

### Expected behavior

`clientPersisterOnSuccess` is available

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/11452353/12903cca-5e12-4740-97c0-1a2d5102aacc)

### Platform

- OS: Mac

### Tanstack Query adapter

vue-query

### TanStack Query version

4.32.6

### TypeScript version

5.1.6

**Comment by bazuka5801** [comment]
May be the solution (App.vue)
```ts
const queryClient = useQueryClient()

watch(queryClient.isRestoring, (isRestoring) => {
  if (!isRestoring) {
    queryClient.resumePausedMutations()
  }
})
```

**Comment by TkDodo** [comment]
@DamianOsipiuk FYI
