### ISSUE TITLE
v5: infiniteQuery incorrectly infers unknown as data when used with select

### ISSUE THREAD

**Issue by cs-clarence** [TanStack/query#5881]
### Describe the bug

`createInfiniteQuery` infers unknown for QueryFnData 

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/nostalgic-matan-nrdklh

### Steps to reproduce

1. use `createInfiniteQuery`
2. Provide the required fields for the query options
3. The inferred query data for the pages is `unknown[]`

### Expected behavior

createInfiniteQuery to infer querFn return type as the query data type

### How often does this bug happen?

Always

### Platform

-OS: Linux

### Tanstack Query adapter

solid-query

### TanStack Query version

v5

### TypeScript version

v5.1.6

**Comment by dotsource-tpo** [comment]
Possibly related issue: infiniteQueryOptions in react-query also seems to incorrectly infer the data type without the InfiniteData wrapper, which provides the individual pages.

**Comment by TkDodo** [comment]
you are right, it seems to be a general issue with `select` on infinite queries. Here is a [typescript playground](https://www.typescriptlang.org/play?target=9#code/JYWwDg9gTgLgBAbzgVQM4FMCKBXdUCeASuqtgDYwA0c2GOe+1t6AkgHYBmwbwMWuBaty48+9AgHkwMYBDao4AXzgcoEEHABEAARgBDefoDGAawD0UdHqMwAtAEcB+TXDNm4MfGBIAuOACN0fQBYAChQSFg4ACo4PQUjaHQVNQ0Acl0DVGNzRwZbRMs013dPb1Q-QJDQsMTDODw1KFQAdV4ACwBldDJ0GzgAXhoMdhFefgYACgQwuDgAE3QOPXIYAAU9AHN0Dag9ED8ABkpZuDyCAGl0fD8AbU02bBBA5s0AXRPQue2YADl0AAe6y2Oz0ewOcEmAH1qFCYXAyPFgdtdvsAJSDAB8CKRGxRYP2cAA1HAAIyfOYYXo2PyTeZ6fQYgbYmZfOYIoJwMAghRDen6AB03O2qAA3Kc5nVUBBegKyBBNpNhSQ0eKamy5pYYNgoGwuTyBRxETBJqrTooKXFUPg2EYzk4AGJsJUEkCoNF+NapYAYAA8j2eeFubxZEo58BAq2AYDIwDwg314NQQpBqI0JNJarDvXgAd5cGDVrgAZewazGpU0EhObgwATmdrcF9Q1Jh1FxKJwAxtzzQto7UmXbe5fZcC1Or1vZAejAk0HTOxddikYo0djeDNbItYUUaLCYUa0FaHW61JgAv5ejCblHt7vAD0APz79VS+AAd2gJmPMHaEGwMCnn08BDMwozcOM4j4NMpyLMsqx4qC4JHJa5z4FcNwFg8TwvKg7yWj8-xAohaa0vCcLUIi2Qka6C44tRqausSZKWvENp2mhToukmHpwF66g+ug-o4UGIaINmnIrjIMZxlACbckmKb4uCzGZi+o41nmCaFvExYiVAZbqeyHBVpMNZ1i27Z1s2ZJth2XYFr2YD9vOw5GZqQQTnpboCtOs7zlijbLlGMkbmqczbqEu4vp+UDfm0v7-oBPTAReDJ6EpJDXu4d65XlcBPkAA) showing the same issue for react.

@ecyrbe could you maybe take a look at this?

**Comment by ecyrbe** [comment]
@TkDodo on it, did something change since we added the feature ? i remember we added type checking tests for this. Any regression should have been caught.

**Comment by TkDodo** [comment]
@ecyrbe I'm not sure, but we certainly haven't deleted any tests. So I think we probably don't have a test for this case.

**Comment by cs-clarence** [comment]
I also noticed that the first parameter of `select` function on `createQuery` does not infer the `queryFn`'s return type.

I added it on the codesandbox [here](https://codesandbox.io/p/sandbox/nostalgic-matan-nrdklh). It's on line 19.

**Comment by ecyrbe** [comment]
@TkDodo on my side, all type tests are broken. i don't know how they are passing in CI/CD. Something broke the whole thing. i'm not sure where this regression came from. still on it.

**Comment by ecyrbe** [comment]
@TkDodo the issue seems to be that someone reverted my PR i made here before :
https://github.com/TanStack/query/pull/5040/files

i can get it back to like i did before, but since someone reverted it, i don't know why. feel free to revert it back again if it was a mistake.

**Comment by ecyrbe** [comment]
@TkDodo ok i found the origin of the issue, it was a change made 3 weeks ago to remove suspense from the resulting infinitte query options, just ordering the Omit properly like this fixes the issue :
![image](https://github.com/TanStack/query/assets/633115/72a090b3-819b-4eaa-aadb-c82b8c0698d4)

**Comment by ecyrbe** [comment]
There is still an issue with the type tests as they are ignored by ci/cd. i guess it's because typeschecking is disabled in tests. i strongly suggest to get it back. else these kind of regressions will get incognito into someones production.

**Comment by TkDodo** [comment]
@lachlancollins can you take a look why the tests are excluded from type checks in ci/cd? My guess is because we only use `tsc` now to produce `d.ts` output, and tests are not included? However, we should really have a check where all typescript files are checked for correctness.

**Comment by TkDodo** [comment]
> There is still an issue with the type tests as they are ignored by ci/cd

@ecyrbe I've investigated this a bit more. If I revert your change, all type tests pass. If I change something inside one of the type tests, it is correctly reported as failure. Could it be that we just didn't have a test for this case? I think there's nothing wrong with our CI setup ...

**Comment by alwyntan** [comment]
Hi, I'm still having this issue in react-query 5.28.4 in react. Should this PR fix this problem in react too?

Here's a typescript playground https://www.typescriptlang.org/play?#code/Q
