### ISSUE TITLE
"setQueryData" doesn't do anything when "next dev" mode causes "Refreshing page data due to server-side change"

### ISSUE THREAD

**Issue by ConnorLanglois** [TanStack/query#5883]
### Describe the bug

Context:
When running in Next.js dev mode through the cli command "next dev", Next.js will occasionally do a client-side refresh (not a full refresh with browser loading indicator, some funky js refresh it does internally I'm guessing) with the message "Refreshing page data due to server-side change", which to me so far seems to occur when a hook file is changed and saved. Next.js doesn't seem to output this message when editing a normal component file. Not too sure on specifics here, my guess is that it's because the hook is imported?

Anyway, besides that point since that is just Next.js behavior, I am noticing that whenever Next.js causes this kind of refresh, TanStack Query seems to break, with setQueryData not causing re-renders and therefore "data" being kept the same. Even if I force the hook to re-render with a setState counter, data is still the same every time. I have to do a full-page refresh each time to get it working again. By the way, the hook is the file that is calling the setQueryData function.

I should also note that doing a subsequent getQueryData returns the correct updated data, but for some reason the "data" returned from useQuery is stuck.

### Your minimal, reproducible example

Too tired right now, it's late, so skipping this for now. Let me know if needed

### Steps to reproduce

1. Get TanStack query setup with Next.js
2. Create hook in other file and setup a useQuery
3. Add function Foo in hook to call setQueryData
4. Import/use that hook in a component
5. Add button which calls the function Foo in hook and display query data
6. Run `next dev`
7. Observe behavior is working, query data is up to date
8. Add/change random line in hook file, save file, causing Next to do client refresh
9. Observe behavior not working, query data stuck and not updating

### Expected behavior

I expect everything to continue working even after Next.js refreshes the page.

### How often does this bug happen?

Every time

### Platform

Windows
Chrome
115.0.5790.171

### Tanstack Query adapter

react-query

### TanStack Query version

@tanstack/react-query@4.32.6, @tanstack/query-core@4.32.6

### TypeScript version

typescript@5.0.4

### Additional context

Not sure if this is issue with this library or with Next.js itself.

**Comment by TkDodo** [comment]
> Too tired right now, it's late, so skipping this for now. Let me know if needed

definitely needed :)

**Comment by TkDodo** [comment]
feel free to reopen with a reproduction
