### ISSUE TITLE
[v5] useQueries documentation

### ISSUE THREAD

**Issue by peter-mouland** [TanStack/query#5897]
### Describe the bug

** Documentation error (not production bug**

useQueries code example has `[` `]` instead of `(` `)`

replace
```js
const ids = [1,2,3]
const results = useQueries({
  queries: ids.map(id => [
    { queryKey: ['post', id], queryFn: () => fetchPost(id), staleTime: Infinity },
  ]),
})
```
with
```js
const ids = [1,2,3]
const results = useQueries({
  queries: ids.map(id => (
    { queryKey: ['post', id], queryFn: () => fetchPost(id), staleTime: Infinity },
  )),
})
```

### Your minimal, reproducible example

online

### Steps to reproduce

1. goto https://tanstack.com/query/v5/docs/react/reference/useQueries

### Expected behavior

`()`

### How often does this bug happen?

Every time

### Screenshots or Videos

n/a

### Platform

web

### Tanstack Query adapter

react-query

### TanStack Query version

v5

### TypeScript version

v4

### Additional context

I'm happy to submit a PR if one hasn't been submitted already

**Comment by TkDodo** [comment]
> I'm happy to submit a PR if one hasn't been submitted already

yes please do
