### ISSUE TITLE
Should not select prop on a useQuery be memoized? 

### ISSUE THREAD

**Issue by danieloprado** [TanStack/query#5900]
### Describe the bug

I was using the select function to populate a form, but every render the form was reseted with original value of the request. 

Like example:
```tsx
const query = useQuery({
    queryKey: ["test"],
    queryFn: () => 0,
    select: () => new Date().toISOString(), // not memoized, every render will be recalculated.
  });
```

If someone use a "heavy" logic on select this will decrement performance,  should select function be called only after a "Success" request like deprecated "onSuccess"? This is the expected behavior? 

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/polished-surf-9l8c9d?file=/src/Test.tsx:9,6

### Steps to reproduce

1. Click on count button
2. See that query data will change to the current data time.

### Expected behavior

As a developer, I expect that "select" only be called when the request return not every render, or maybe be informed on docs about this behavior.

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/query/assets/7683575/c7405c1c-58e3-426d-bccb-bfe4cb818825

### Platform

- OS: macOS
- Browser: Brave
- Version: 1.57.47

### Tanstack Query adapter

react-query

### TanStack Query version

4.32.6

### TypeScript version

5.1.6

**Comment by TkDodo** [comment]
select recomputes because it's an inline function. To optimize computations, wrap them in `useCallback`:

```
select: useCallback(() => new Date().toISOString(), [])
```

https://tkdodo.eu/blog/react-query-data-transformations#3-using-the-select-option

**Comment by jcready** [comment]
Unfortunately the issue with `useCallback` is that it is unable to infer the arguments for the function whereas it is inferred correctly when the function is not wrapped in `useCallback`. It ends up being easier to just `useMemo()` to convert the `data` outside the `useQuery` hook. e.g.

```ts
const query = useQuery({
    queryKey: ["test"],
    queryFn: () => 0,
});
const queryData = useMemo(() => new Date().toISOString(), [query.data]);
```

**Comment by jcready** [comment]
Imagine a more [realistic example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMDCBDANrgI2wGMBrAGhQwFl0QI4BfOAMyghDgHIp0SYuAKFCRYiKugCKydFACeTVu05cAAjGwA7VBrIB6XvwC0ARxnyhg4hG3wzshQF4J0hwAoEguN7j35AaXQ5AC44AG0AIhh0HQiAXXIvHz85ADFNULcASjhHAD44amwYAAsAOigtABMObMTGLIBuKxsdX3M5ABFi7FyJWno3bNyClLKqnrgAfnaHccmCgAYygFY4UORNKvQWYE10KsowsYmNOKbBPT0fOAA9KcEW21n5ACY+tCkOjyTvFMCQuEojEYPFEjcUulMjl8oViuVKltallwT4MLh0MQYBsMDh8EQyENTtgYQViXAlqsjudfnArjcGYybvdBA1moIUq95hpLtdmVMgA):
```ts
const query2 = useQuery({
    queryKey: ["test"],
    queryFn: () => Math.random(),
    select: useCallback((data) => data > 0.5, [])
    //                   ^? (parameter) data: any
});
```

**Comment by TkDodo** [comment]
I see. but isn't that a weakness of `useCallback` in general? Wouldn't you have the same issue in a react event handler?

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA0ECuAdvsBE3AMImRNZMwAFAEo4AbxpwpcSjAZQOAHgBGDGDHZx2nADbBcAawC8Y7HhgA6BqiydkOncrwHBgrKKMA+cXFztUEDpYFjoQAOZuFjDIUGFYlgBu9gzuAL4ANHAA2gC6wqmeuHqGigD0qursnpLStXX1DY31paV1AHoA-DSpQA

**Comment by jcready** [comment]
Absolutely. I don't think there's anything this library or react could really do to make that devex better. My only point being that `useMemo` provides the same functionality in this situation (correct me if I'm wrong), but without the user needing to provide the return type of the queryFn (or deal with `any`). The only downside is having to handle the `undefined`.

**Comment by TkDodo** [comment]
> My only point being that useMemo provides the same functionality in this situation (correct me if I'm wrong)

to clarify, it's not exactly the same: with select, you subscribe to the derived result of whatever select returns, meaning that your component will only re-render if the result of select changes. With the memo approach, your component will always re-render when the result of the queryFn changes, even if the memoized result is then the same / not re-computed.

**Comment by jcready** [comment]
Does structural sharing work in conjunction with `select`? i.e. does the result of `select` go through the same structural sharing stuff as the result of the `queryFn`?

I'm starting to believe that `select` could/should start to behave like a whole new query where users can pass their own key for the select, a hash function, if it should have structural sharing, etc. The only difference being that it operates synchronously.

**Comment by TkDodo** [comment]
> does the result of select go through the same structural sharing stuff as the result of the queryFn?

yes it does.

**Comment by zeorin** [comment]
```typescript
import { useCallback } from 'react';

export const useQuerySelect = useCallback as <TQueryFnData, TData>(
  select: (data: TQueryFnData) => TData,
  deps: React.DependencyList
) => (data: TQueryFnData) => TData;
```

**Comment by jcready** [comment]
@zeorin that's great!

@TkDodo this would be an excellent thing to export from the react-query package and/or include in the docs/guide for `select`.

**Comment by zeorin** [comment]
Oh yeah I add this hook to `eslint-plugin-react-hooks`'s `additionalHooks` so its dependencies are checked.
