### ISSUE TITLE
@typescript-eslint/eslint-plugin: Missing peerDependencies.

### ISSUE THREAD

**Issue by justsaul** [TanStack/query#5909]
### Describe the bug

While running linter I've encountered:

```
Error: Failed to load plugin '@tanstack/query' declared in '--config » eslint-config': @tanstack/eslint-plugin-query tried to access eslint, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

This issue should only concern users of package managers that don't rely on node_module resolution algo (yarn with nodeLinker strategy PnP in strict mode). This way, eslint plugin doesn't gain access to eslint, because its not declared as peerDependency. 

General solution is to define peerDependency within @typescript-eslint/eslint-plugin package.json such as:

```JSON
{
  "peerDependencies":  {
    "eslint": "^6 || ^7 || ^8"  // range of eslint matches '@typescript-eslint' package
  }
}
```

### Your minimal, reproducible example

-

### Steps to reproduce

- Define plugin
- run linter

### Expected behavior

Linter should exectute.

### How often does this bug happen?

Every time

### Platform

macOS

### Tanstack Query adapter

None

### TanStack Query version

v4.32.0

### TypeScript version

v4.8.3

### Additional context

Let me know if you agree with this, can create PR.

**Comment by TkDodo** [comment]
Sounds good 👍
