### ISSUE TITLE
Queries can show incorrect data

### ISSUE THREAD

**Issue by shepherdjerred** [TanStack/query#5924]
### Describe the bug

In some cases, TanStack query can return incorrect data when multiple related keys are used

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-a9azfw?file=src%2FApp.vue

### Steps to reproduce

1. Go to this [StackBlitz example](https://stackblitz.com/edit/vitejs-vite-a9azfw?file=src%2FApp.vue).
1. Read through the synopsis and expected behavior
1. Click "swap" twice
1. Notice that the invariants have been violated, and that incorrect data is being shown

### Expected behavior

Reactivity updates should happen all at once so that invalid states cannot be observed

### How often does this bug happen?

Every time

### Platform

macOS Chrome 116.0.5845.110

### Tanstack Query adapter

vue-query

### TanStack Query version

4.34.0

### TypeScript version

5.0.2

**Comment by TkDodo** [comment]
@DamianOsipiuk fyi

**Comment by Mini-ghost** [comment]
This issue should be the same as #5910

**Comment by TkDodo** [comment]
thanks, closing as duplicate then.
