### ISSUE TITLE
[svelte-query@4.3.3]: `isLoading` is true even if `createQuery`s `enabled` prop is false all the time

### ISSUE THREAD

**Issue by frederikhors** [TanStack/query#5945]
### Describe the bug

As you can see on the below REPL I'm using Svelte (NO SSR) and the `createQuery` `enabled` prop:

```svelte
<script>
  import { createQuery, QueryClient, setQueryClientContext } from '@tanstack/svelte-query';

  const client = new QueryClient();

  setQueryClientContext(client);

  async function someFetch() {
    // Fake wait
    await new Promise(r => setTimeout(r, 2000));

    console.log("after the fake wait");

    return ["john", "bob"];
  }

  let search = "";
  
  $: playersStore = createQuery({
    queryKey: ['players'],
    queryFn: someFetch,
    enabled: !!search
  });
</script>

$playersStore.data: {$playersStore.data}

<br><br>

{#if $playersStore.isLoading}
  $playersStore.isLoading = {$playersStore.isLoading}
  <br>
  Is loading... <b>but why?</b>
{:else}
  Ok
{/if}
```

But as you can notice on the REPL the `Is loading...` part is visible even if the query is not started. Even if `enabled` is false.

I think this is a bug and a bad one.

### Your minimal, reproducible example

https://stackblitz.com/edit/sveltejs-kit-template-default-m2gtar?&file=src%2Froutes%2F%2Bpage.svelte

### Steps to reproduce

1. Go to REPL

1. Wait for it to start

1. See the `Is loading...` wrong message

1. see the code in `src/routes/+page.svelte` code

### Expected behavior

The message should be `Ok`.

Since the query is not enabled and has never started the `isLoading` must be `false`.

### How often does this bug happen?

Every time

### Tanstack Query adapter

svelte-query

### TanStack Query version

4.33.0

**Comment by TkDodo** [comment]
> Since the query is not enabled and has never started the isLoading must be false.

disabled queries start in status: 'loading', but fetchStatus: 'idle'. isInitialLoading is also false. 

It's documented here: https://tanstack.com/query/v4/docs/react/guides/disabling-queries
