### ISSUE TITLE
Chrome beta 117 unload api deprecated issue

### ISSUE THREAD

**Issue by Woo-Dong93** [TanStack/query#5952]
### Describe the bug

Chrome has updated to beta 117 and announced that it will deprecated the unload API.
However, it has been confirmed that the broadcast-channel library you are using uses the unload API. 
I wonder if there are any plans to respond!

### Your minimal, reproducible example

none

### Steps to reproduce

- none

### Expected behavior

- none

### How often does this bug happen?

None

### Platform

- Browser: Chrome 177v

### Tanstack Query adapter

None

### TanStack Query version

v3.38.0

**Comment by TkDodo** [comment]
we are not using the `unload` api in our codebase. We are using the `'broadcast-channel'` package, so maybe they do?

**Comment by TkDodo** [comment]
yes, `broadcast-channel` uses the `unload` package:
- https://github.com/pubkey/unload

please file the issue there, then `broadcast-channel` can update its dependency and we can update ours.
