### ISSUE TITLE
TypeScript Type Incompatibility Error in queryObserver.ts 

### ISSUE THREAD

**Issue by hsnmrd** [TanStack/query#5982]
### Issue Summary
I am encountering a TypeScript type incompatibility error in the queryObserver.ts file of the @tanstack/query-core package while using it in my Next.js project.

### Error Message
```
./node_modules/@tanstack/query-core/src/queryObserver.ts:566:46
Type error: Argument of type '(TQueryData & ({} | null)) | (TData & ({} | null))' is not assignable to parameter of type 'TData'.
  'TData' could be instantiated with an arbitrary type which could be unrelated to '(TQueryData & ({} | null)) | (TData & ({} | null))'.
```

### Your minimal, reproducible example

I apologize, but I don't have an online repository or link to share for this issue. However, I can provide a code snippet and detailed instructions to help you reproduce the problem in your own environment.

### Steps to reproduce

1. Create a Next.js project with the following dependencies:

-         Next.js
-         ESLint (8.47.0)
-         @tanstack/query-core (4.32.6)

2. Set up a component or code that uses the @tanstack/query-core package.
3. Enable ESLint in your project configuration.
4. Attempt to build the project using the appropriate build command.

### Expected behavior

I expect that the @tanstack/query-core package should work without TypeScript type errors in my Next.js project. The error message provided seems to indicate a type inference issue.

### How often does this bug happen?

None

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/18046560/a2bfd121-5a51-4d97-8733-3f34b8d9456b)

### Platform

- Node.js Version: [18.16.1]
- TypeScript Version: [5.1.6]
- ESLint Version: [8.47.0]
- @tanstack/query-core Version: [4.32.6]

### Tanstack Query adapter

react-query

### TanStack Query version

v4.32.6

### TypeScript version

v5.1.6

### Additional context

Please let me know if you need any additional information or code snippets to diagnose and resolve this issue.

**Comment by TkDodo** [comment]
you can use codesandbox or stackblitz to show a runnable reproduction. If it's not related to nextJs, a TypeScript playground would also suffice.

**Comment by TkDodo** [comment]
feel free to reopen with a reproduction

**Comment by paneidos** [comment]
Ran into this issue today. It happened when I tried to type my query function.

This line triggered the error:
```
import { QueryFunctionContext } from '@tanstack/query-core/src/types'
```

For me it was resolved by importing the type from `'@tanstack/react-query'` instead.
The other import was made automatically by PyCharm.

**Comment by rzec-allma** [comment]
I can confirm when importing from `query-core` (which some auto import adders seem to do) results in this error.
