### ISSUE TITLE
[nuxt] Data from useQuery is ignored in useHead on server-side

### ISSUE THREAD

**Issue by VladStepanov** [TanStack/query#5995]
### Describe the bug

No way to set Head with data from useQuery in server-side. Data applies only client-side

### Your minimal, reproducible example

https://stackblitz.com/edit/nuxt-starter-ret8gk?file=app.vue

### Steps to reproduce

1. Open repro
2. Right click on preview frame
3. Click on "View frame source"
4. <title> should be "Query data", but we get "Default data

### Expected behavior

As a user, i expected that i can set Seo things with data from useQuery in server-side

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Chrome
- Platform: node@18.16.0

### Tanstack Query adapter

None

### TanStack Query version

4.35.2

**Comment by Mini-ghost** [comment]
Perhaps this folling can solve your problem:

https://stackblitz.com/edit/nuxt-starter-ygn1cm?file=app.vue

```ts
const title = computed(() => data.value ?? 'Default value');

await suspense();
onServerPrefetch(() => suspense());

useServerSeoMeta({
  title,
});
```

**Comment by VladStepanov** [comment]
@Mini-ghost Thanks, that really works! But it seems like a workaround. Is it expected behaviour?

**Comment by Mini-ghost** [comment]
@VladStepanov I think this is expected behavior.

Because even if we use nuxt's built-in composable API `useAsyncDate`, it needs to wait for it to be resolved, like this:

```ts
const { data: asyncData } = await useAsyncData('description', () => {
  return new Promise((resolve) => {
    setTimeout(() => resolve('Query data'), 2000);
  });
});
```

Refer to [useAsyncData · Nuxt Composables](https://nuxt.com/docs/api/composables/use-async-data#example)
