### ISSUE TITLE
[Svelte] SetQueryData does not rerender

### ISSUE THREAD

**Issue by zhihengGet** [TanStack/query#6000]
### Describe the bug

 SetQueryData does not update UI, cache was updated :( 

```
setInterval(() => {
    
    queryClient.setQueryData(
			"repoData"
,
        old=>{return 5})
  }, 3000);  
```

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/infallible-fermi-v4knts?file=/src/lib/Simple.svelte:30,14

### Steps to reproduce

see codesandbox, basically, after setimeout, state should update

### Expected behavior

ui says 5

### How often does this bug happen?

None

### Platform

window, edge

### Tanstack Query adapter

svelte-query

### TanStack Query version

5 .beta.0

### TypeScript version

5

**Comment by TkDodo** [comment]
the devtools clearly show that you create a second, invalid cache entry, because QueryKeys need to be arrays:

![Screenshot 2023-09-13 at 11 47 42](https://github.com/TanStack/query/assets/1021430/baff7d1e-b70a-4898-bf6c-4fce591c29b5)

```diff
- queryClient.setQueryData("repoData"
+ queryClient.setQueryData(["repoData"]

**Comment by zhihengGet** [comment]
sorry that was a bad repor, heres a better one, basically https://codesandbox.io/p/sandbox/infallible-fermi-v4knts?file=/src/lib/Simple.svelte:17,30
