### ISSUE TITLE
Svelte SetQueryData not working with array

### ISSUE THREAD

**Issue by zhihengGet** [TanStack/query#6007]
### Describe the bug
related : https://github.com/TanStack/query/issues/6000 ,  here is  a better reproduction

when using setQueryData to update cache (an array or object),  ui isnt changed

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/infallible-fermi-v4knts?file=/src/lib/Simple.svelte:24,18

### Steps to reproduce

see repro, click on setQuery 

### Expected behavior

ui update

### How often does this bug happen?

Every time

### Platform

microsoft edge

### Tanstack Query adapter

svelte-query

### TanStack Query version

5  beta.23

### TypeScript version

5.0.4

**Comment by TkDodo** [comment]
That's due to our structuralSharing feature. Updates have to happen immutably. setting `OLD[0]="new old"` is not an immutable update.

set `strucuralSharing: false` on your Query, or perform updates in a deeply immutable way.
