### ISSUE TITLE
tanstack query in layout component in nextjs app directory stops responding after a `router.refresh()`

### ISSUE THREAD

**Issue by PaulWild** [TanStack/query#6021]
### Describe the bug

We are using react query as part of a nextjs application using the app router. When there is a component in a layout file that is showing data based off a query, it will stop updating is a 'router.refresh()' has been called from `useRouter` in `next\navigation`.

Apologies if this is a next bug rather than a tanstack query bug. 

### Your minimal, reproducible example

https://github.com/PaulWild/next-app-dir-react-query-bug/

### Steps to reproduce

The app is set up with a react query that returns an int. The current value is shown in a client component that is part of the layout file.

Pressing the invalidate query button will retrigger the query and return the a new number. This is reflected on the page
Clicking reload page will trigger a router.refresh()
Clicking invalidate query now no longer updated the value in the layout component

### Expected behavior

The component showing the latest value should always be updated

### How often does this bug happen?

Every time

### Platform

reproduced on windows and mac, chrome, edge

### Tanstack Query adapter

react-query

### TanStack Query version

4

**Comment by TkDodo** [comment]
The issue is merely an unstable query client. As the docs say, you need to put it in state:

```
const [queryClient] = React.useState(() => new QueryClient());
```

https://codesandbox.io/p/sandbox/muddy-butterfly-qs5rr4

**Comment by PaulWild** [comment]
Well I feel more than a little embarrassed about it being a not reading the docs properly error. Thanks for the quick reply and solution, it is much appreciated!
