### ISSUE TITLE
I'm trying to use both `initialData` prop and `prefetchQuery` but `initialData` is not considered. 

### ISSUE THREAD

**Issue by frederikhors** [TanStack/query#6039]
### Describe the bug

I'm trying to use both `initialData` prop and `prefetchQuery`.

Since my website can have very slow responses I thought that at least in the detail pages I can use `initialData` (with the data I already have in list and which are the same for details) and use the _on hover_ for `prefetchQuery`.

But with big and bad surprise I saw that as soon as the prefetch starts (which lasts a few seconds of slow HTTP call) and the detail page opens, `initialData` is not even considered! And I have spinners all over the page!

Why?

Isn't it possible to use both **together**?

### Your minimal, reproducible example

I'll post in a few moments.

### Steps to reproduce

1. I open the list page and wait for the data

1. With my mouse I hover over one of the items in the list

1. the `prefetchQuery` starts but the server will take more than 5 seconds for a response

1. I click the item in list

1. the detail page opens but `initialData` function is not called

1. hence I see spinners instead of data

### Expected behavior

I expect to see data from `initialData` **DURING** the `prefetchQuery` or better yet I could also cancel the prefetch call and wait for the response that comes from `useQuery` on the detail page.

Am I totally wrong?

### How often does this bug happen?

Every time

### Platform

Win 10. Chrome 117.

### Tanstack Query adapter

svelte-query

### TanStack Query version

4.35.3

### TypeScript version

5

**Comment by TkDodo** [comment]
> But with big and bad surprise I saw that as soon as the prefetch starts (which lasts a few seconds of slow HTTP call) and the detail page opens, initialData is not even considered! And I have spinners all over the page!

`initialData` only does "something" if you have no cache entry. What it does is:

- when the cache entry is created, what you pass is taken as initialState for the data field

When you use prefetching, the call to `prefetchQuery` is creating the cache entry. You can pass `initialData` to `prefetchQuery` as well, but I think you'd rather want to use `placeholderData` instead:

https://tkdodo.eu/blog/placeholder-and-initial-data-in-react-query
