### ISSUE TITLE
QueryClientProvider context lost when call from other Lerna package in a monorepo setup

### ISSUE THREAD

**Issue by kevinvugts** [TanStack/query#6044]
### Describe the bug

In my monorepo built with Lerna, I have two packages: app and components

### General information
The app package is a clean install of a Remix Run app. The components package is a simple component library containing just a Button component I am using @tanstack/react-query to parse data, cache queries etc.

**Public repo:** [https://github.com/kevinvugts/lerna-react-query-context/tree/main](https://github.com/kevinvugts/lerna-react-query-context/tree/main)

**Remix Lerna Package** 
In the root.tsx of the app package, it's wrapped with the QueryClientProvider as stated in the [docs](https://tanstack.com/query/latest/docs/react/quick-start).

When using hooks like useQuery, useQueryClient, or any other you prefer, it works without issues. However, this is only the case when invoked from within the Remix Lerna package.

## **Button**
Regarding the Button, it's rendered in app -> routes -> _index.tsx. The crucial detail here is that the implementation of [Button](https://github.com/kevinvugts/lerna-react-query-context/blob/main/packages/components/src/components/Button/Button.tsx) utilizes the useQueryClient hook from @tanstack/react-query. This is only feasible when it's called within the hierarchy of the QueryClientProvider, which I've done [here](https://github.com/kevinvugts/lerna-react-query-context/blob/main/packages/app/app/root.tsx#L29).

## The problem
When you uncomment line 18 from app -> routes -> _index.tsx the app throws the following error: Error: No QueryClient set, use QueryClientProvider to set one

This indicates to me that the QueryClientProvider's somehow lost its context while rendering the Button.

## Addition of a separate context package
To determine if the issue is related to @tanstack/react-query, I created a separate context package. This package establishes a new context, a corresponding provider, and makes them available externally.

Subsequently, I wrapped the component in a manner similar to @tanstack/react-query, using the . From the Button component, I then invoked a function on the context to retrieve its value, checking if it matched the one from the Remix app. It did!

## So what now?
To be entirely certain, I want to ensure that I haven't made any oversight that might invalidate my assumption about @tanstack/react-query being the culprit.

For clarity, I've verified that react, @tanstack/react-query, and related packages don't have duplicated instances. I've appropriately used peer/dev dependencies and ensured this in the rollup.config.js.

Regardless, any assistance would be greatly appreciated!"

### Your minimal, reproducible example

https://github.com/kevinvugts/lerna-react-query-context/tree/main

### Installation
run yarn install from the root folder and lerna will do the rest for you.

run yarn build and lerna will build all packages

run yarn lerna run dev --scope=app and it will start the Remix development server on http://localhost:3000/ for you

### The problem
When uncommenting line 18 in the file app -> routes -> _index.tsx the app stops working. The reason for this is that @tanstack/react-query somehow doesn't propagate or looses it context value when it's rendering the Button component. At least, that's as far as I can guess it.

In root.tsx the whole app and it's children is wrapped with the required QueryClientProvider as stated per [docs](https://tanstack.com/query/latest/docs/react/quick-start)

### Why is this happening?
Well, as you can guess already, I have no clue. When creating a separate package called "context" that contains the exact same setup in terms of (creating a context, a provider and make these available for consumers) the provider/context is working and getting shared. So to me that clearly looks like a @tanstack/react-query issue.

### Things I tried so far?
Making sure there is only 1 instance of @tanstack/react-query, react and so forth. Making use of the peerdependencies and local linking packages with "*" in package.json.

### What is the goal?
The Lerna package "components" should be able to access the context that is defined in the Lerna package "app" when it's being rendered within the hierachy of the

### Expected behavior
Nested children imported in the main Remix app which are imported from a separate Lerna package in a monorepo setup should be able to enjoy the full @tanstack/react-query library if used correctly within the hierarchy of the QueryClientProvider. 

So context, should not get lost when rendering components from other packages. Right now, the queryClient is getting lost somehow when trying to call any of the @tanstack/react-query functions from the Lerna package "components" while it is being rendered within a QueryClientProvider in the main remix app Lerna package. 

There is a single instance of React, @tanstack/react-query etc. So that shouldn't be the problem imho.

### How often does this bug happen?

Every time

### Screenshots or Videos

![error](https://github.com/TanStack/query/assets/17518874/21411acf-661c-46ff-9477-8144c9ccf415)

### Platform

- OS: macOS Ventura 13.5.2 
- Browser: Chrome 116.0.5845.187,

### Tanstack Query adapter

react-query

### TanStack Query version

v4.35.3

### TypeScript version

v5.1.6

### Additional context

Please find the attached github repository.
```[tasklist]
### Tasks
```

**Comment by TkDodo** [comment]
we are not doing anything special at all with react context. The code is literally just:

https://github.com/TanStack/query/blob/1d3ee672d2a1536e3463243813c91902aa97d973/packages/react-query/src/QueryClientProvider.tsx#L6-L22

So yes, when you get the `No QueryClient set, ...` error, it means that if you inspect the component tree at that time, there is no Provider above this component that was created with the same instance / version of React / React Query.

I've checked your lockfile and there is only one version of the lib, but maybe there's a mixup with ESM and CJS?

When I look at the compiled output of `build/index.js` in `packages/app`, I can see (line 129):

```
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
```

but for `packages/components`, there is a `dist` directory where we have cjs code:

```
"use strict";var e=require("react"),t=require("@tanstack/react-query")
```

we have different bundles for esm and cjs, so that could explain it.

Anyways, I'm sorry that I won't be looking more into this because in my experience, those issues are _always_ setup related. What you can do to side-step the issue is (given you are on v5) that you can export the QueryClient and just pass it directly to `useQueryClient`, in which case there won't be a context lookup (or, more precicely, the missing value will be ignored).

**Comment by kevinvugts** [comment]
> we are not doing anything special at all with react context. The code is literally just:
> 
> https://github.com/TanStack/query/blob/1d3ee672d2a1536e3463243813c91902aa97d973/packages/react-query/src/QueryClientProvider.tsx#L6-L22
> 
> So yes, when you get the `No QueryClient set, ...` error, it means that if you inspect the component tree at that time, there is no Provider above this component that was created with the same instance / version of React / React Query.
> 
> I've checked your lockfile and there is only one version of the lib, but maybe there's a mixup with ESM and CJS?
> 
> When I look at the compiled output of `build/index.js` in `packages/app`, I can see (line 129):
> 
> ```
> import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
> ```
> 
> but for `packages/components`, there is a `dist` directory where we have cjs code:
> 
> ```
> "use strict";var e=require("react"),t=require("@tanstack/react-query")
> ```
> 
> we have different bundles for esm and cjs, so that could explain it.
> 
> Anyways, I'm sorry that I won't be looking more into this because in my experience, those issues are _always_ setup related. What you can do to side-step the issue is (given you are on v5) that you can export the QueryClient and just pass it directly to `useQueryClient`, in which case there won't be a context lookup (or, more precicely, the missing value will be ignored).

Hi,

This issue can be closed since this was indeed related to my setup in Lerna.
The issue was regarding differnent versions between different lerna packages. 

It was a very minor issue but it was due the fact that some packages used a "^" version and other ones used a specific version such as 
"5.0.0".

Thanks anyways for your response!
