### ISSUE TITLE
peerDependency problem with @tanstack/react-query-next-experimental

### ISSUE THREAD

**Issue by arackaf** [TanStack/query#6052]
### Describe the bug

I've installed the follow two versions of these libraries

```json
    "@tanstack/react-query": "^5.0.0-alpha.91",
    "@tanstack/react-query-next-experimental": "^5.0.0-alpha.80",
```

they installed when run separately. But when I subsequently run `npm i` or try to install them both at the same time, ab initio, I get the following error 

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR! 
> npm ERR! While resolving: @tanstack/react-query-next-experimental@5.0.0-alpha.80
> npm ERR! Found: @tanstack/react-query@5.0.0-alpha.91
> npm ERR! node_modules/@tanstack/react-query
> npm ERR!   @tanstack/react-query@"^5.0.0-alpha.91" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer @tanstack/react-query@"5.0.0-alpha.71" from @tanstack/react-query-next-experimental@5.0.0-alpha.80
> npm ERR! node_modules/@tanstack/react-query-next-experimental
> npm ERR!   @tanstack/react-query-next-experimental@"^5.0.0-alpha.80" from the root project
> npm ERR! 
> npm ERR! Conflicting peer dependency: @tanstack/react-query@5.0.0-alpha.71
> npm ERR! node_modules/@tanstack/react-query
> npm ERR!   peer @tanstack/react-query@"5.0.0-alpha.71" from @tanstack/react-query-next-experimental@5.0.0-alpha.80
> npm ERR!   node_modules/@tanstack/react-query-next-experimental
> npm ERR!     @tanstack/react-query-next-experimental@"^5.0.0-alpha.80" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! 
> npm ERR! For a full report see:
> npm ERR! /Users/adamrackis/.npm/_logs/2023-09-24T00_13_02_355Z-eresolve-report.txt
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/adamrackis/.npm/_logs/2023-09-24T00_13_02_355Z-debug-0.log

### Your minimal, reproducible example

n/a

### Steps to reproduce

Run 

`npm i @tanstack/react-query-next-experimental @tanstack/react-query@5   `

on a fresh repo 

### Expected behavior

Should work 

### How often does this bug happen?

None

### Screenshots or Videos

n/a

### Platform

npm 9.5.1

### Tanstack Query adapter

react-query

### TanStack Query version

see above

### TypeScript version

n/a

### Additional context

n/a

**Comment by TkDodo** [comment]
> I've installed the follow two versions of these libraries

This was indeed an issue in the peerDependency of the `alpha` package, as it strictly depended on a matching version of `react-query`. However, we've since fixed this in beta.

Please upgrade to:

```
"@tanstack/react-query-next-experimental": "5.0.0-beta.35"
"@tanstack/react-query": "5.0.0-beta.35"
```

**Comment by TkDodo** [comment]
> npm i @tanstack/react-query-next-experimental @tanstack/react-query@5 

I'm not sure why the `latest` tag on npm of the `react-query-next-experimental` package points to `alpha`:

https://www.npmjs.com/package/@tanstack/react-query-next-experimental?activeTab=versions

I hope this will sort itself out when we make a real release. Until then, I'd use:

```
> npm i @tanstack/react-query-next-experimental@beta @tanstack/react-query@beta
```
