### ISSUE TITLE
Hydrate (capital H) not exported from @tanstack/react-query 5.0.0-alpha.91

### ISSUE THREAD

**Issue by arackaf** [TanStack/query#6053]
### Describe the bug

The title says it all. I'm running the 5.0.0-alpha.91 of @tanstack/react-query, and there's no Hydrate exported. It's not just the typings, too - I checked and it really is undefined at runtime. 

I'm assuming / hoping we can still use useQuery in conjunction with <Hydrate going forward.

Or is useSuspenseQuery intended to replace <Hydrate altogether? I'm seeing extremely weird behavior when that hook is used *not* within a <Suspense tag, so I assumed useSuspenseQuery was only intended to be used with streaming / `<Suspense />` (but I can write up a separate ticket if that's not the case) 

### Your minimal, reproducible example

n/a

### Steps to reproduce

Import Hydrate from @tanstack/react-query v 5.0.0-alpha.91 and see that it's not there 

### Expected behavior

Should be there 

### How often does this bug happen?

Every time

### Screenshots or Videos

n/a

### Platform

n/a

### Tanstack Query adapter

react-query

### TanStack Query version

5.0.0-alpha.91

### TypeScript version

n/a

### Additional context

n/a

**Comment by TkDodo** [comment]
It has been renamed to `HydrationBoundary`: https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5#hydrate-has-been-renamed-to-hydrationboundary-and-the-usehydrate-hook-has-been-removed

**Comment by kmgdevelopment** [comment]
@TkDodo FYI this needs to be updated [in the docs](https://tanstack.com/query/v4/docs/react/reference/hydration). I'd do it myself but I don't know enough about the specifics of how hydrate works or the latest changes to it.

**Comment by TkDodo** [comment]
You are linking to the v4 docs. The v5 docs have been changed:

https://tanstack.com/query/v5/docs/react/reference/hydration
