### ISSUE TITLE
Callbacks passed to `mutate` are not called when the component unmounts

### ISSUE THREAD

**Issue by AntoineThibi** [TanStack/query#6060]
### Describe the bug

Hello,

I have encountered an issue where callbacks passed to the mutate function are not being executed.

Here's a simplified example to illustrate the problem. The full code can be found [here](https://snack.expo.dev/@antoinethib/react-query-mutation-success):

```jsx
const Login = () => {
  // Global state for the example.
  const {setIsLogged, setBgColor} = useContext(Context);

  const {mutate} = useMutation({
      mutationFn: async () => await sleep(),
      onSuccess: () => {
        setIsLogged(true); // This causes the Login component to unmount
      }
    });
  
  const onPress = () => {
    mutate({onSuccess: () => setBgColor("#0FF")}); // This onSuccess callback is never called
  }

  return <Button title={"Login"} onPress={onPress} />
}
```

In this example, when the Login button is pressed, a mutation is triggered. The `onSuccess` callback in `useMutation` sets isLogged to true, which causes the Login component to unmount. However, there is another `onSuccess` callback defined inside the `mutate` function call in the onPress handler, which is supposed to change the bgColor. This callback is never called.

It seems like the callback inside `mutate` is not being executed because it is scheduled to run after the component has unmounted due to the state change triggered by the `onSuccess` callback in `useMutation`. However, it is a strange comportment : the callback should be in the closure of the mutate function, therefore, be executed (on success) no matter what.

### Your minimal, reproducible example

https://snack.expo.dev/@antoinethib/react-query-mutation-success

### Steps to reproduce

1. Click on the Login button
2. Wait for 1 second
3. A logout button is display. However, the backgroundColor should also change.

### Expected behavior

1. Click on the Login button
2. Wait for 1 second
3. A logout button is display and the backgroundColor is changing.

### How often does this bug happen?

Every time

### Platform

- IOS, Android
- "@tanstack/react-query": "^4.28.0"
- "react": "18.2.0"
- "react-native": "0.71.2"

### Tanstack Query adapter

react-query

### TanStack Query version

4.28.0

### TypeScript version

4.5.2

**Comment by TkDodo** [comment]
This behaviour is on purpose, and its [documented here](https://tanstack.com/query/v4/docs/react/guides/mutations):

> You might find that you want to trigger additional callbacks beyond the ones defined on useMutation when calling mutate. This can be used to trigger component-specific side effects. To do that, you can provide any of the same callback options to the mutate function after your mutation variable. Supported options include: onSuccess, onError and onSettled. Please keep in mind that those additional callbacks won't run if your component unmounts before the mutation finishes.

As the docs say, the callbacks on `mutate` are component specific, which means they won't run if the component has been unmounted in the meantime. The ones on `useMutation` always run. I'm also showing some examples where this split can be helpful in my blog:

https://tkdodo.eu/blog/mastering-mutations-in-react-query#some-callbacks-might-not-fire

In your example, if `bgColor` would be local state, this would be ideal because you wouldn't want to set `bgColor` of a component that doesn't exist anymore. Since your `bgColor` is global state, you'd need to put it into the callback of `useMutation` itself:

```
  const {mutate} = useMutation({
      mutationFn: async () => await sleep(),
      onSuccess: () => {
        setIsLogged(true)
        setBgColor("#0FF")
      }
    });
```

**Comment by KutnerUri** [comment]
this is super confusing!
