### ISSUE TITLE
useMutation.data is undefined during fetch, but must be the last success data

### ISSUE THREAD

**Issue by olegcherr** [TanStack/query#6067]
### Describe the bug

`useMutation` [docs](https://tanstack.com/query/v4/docs/react/reference/useMutation) say that `data` should contain `The last successfully resolved data`. BUT `data` becomes `undefined` during every fetch.

### Your minimal, reproducible example

https://codesandbox.io/s/2fz89y

### Steps to reproduce

1. Open Sanbox
2. Click MUTATE

### Expected behavior

`data` shouldn't become `undefined` ever after first successful fetching.

### How often does this bug happen?

Every time

### Screenshots or Videos

![out](https://github.com/TanStack/query/assets/3730074/04f74821-bd24-4e98-bace-b08165a0a5a7)

### Platform

Win 10, Chrome 117

### Tanstack Query adapter

react-query

### TanStack Query version

3.39.3

**Comment by TkDodo** [comment]
docs are probably wrong because it says: `The last successfully resolved data for the query.` But we're talking mutations here, not queries.

what you are getting is the data for a mutation instance. Every time you call mutate, you get a new mutation instance. `useMutation` watches the latest invocation only, so when you click mutate, the new mutation is always in `status: 'loading'` with `data: undefined`. That's how mutations are designed to work, seems like we just need to adapt the docs a bit ?

**Comment by olegcherr** [comment]
@TkDodo Thanks for your reply!
What would you suggest in my case - I need to access the previous mutation `data`. Should I simply store it somewhere independently of react-query, or there is a some way to achieve this using react-query?

**Comment by TkDodo** [comment]
> I need to access the previous mutation data

what's the use-case you're trying to solve?

**Comment by olegcherr** [comment]
> what's the use-case you're trying to solve?

In certain cases I need to request data from the backend. Then sometimes I need to refetch it. But during the refetch I still need to display the previous data.

**Comment by TkDodo** [comment]
resquesting data from the backend and refetching it sounds like a query, not a mutation ?

**Comment by olegcherr** [comment]
Yeah, I know :))
But the problem is that I don't need to make the request right after my UI component is mounted. I need to request only when the user asks for it.

I didn't find a convenient solution to achieve this using `useQuery`. I guess I need to set `enabled: false` flag when mounted, and then set it to `true` when the user asks for the data, and then again set it to `false` till the next time...

Is that correct?

**Comment by TkDodo** [comment]
well mutations are definitely not the right tool for that. You want a lazy query:

https://tanstack.com/query/v4/docs/react/guides/disabling-queries#lazy-queries

> Yeah, I know :))

You know but I didn't. You've asked things about mutations when in fact, you don't even want a mutation...

**Comment by olegcherr** [comment]
Okay, I see what you're talking about. But my issue is still valid, since the docs about `useMutation.data` are wrong.

And the second thing is that the docs about Lazy Queries don't cover my case. They simply suggest to use conditional `enabled` flag. It's not convenient in my case.

Anyway, I found the solution in https://github.com/TanStack/query/issues/1965 where you said that `refetch is often used with disabled queries for imperative fetching`.
This is exactly what I was looking for! I just need to set `enabled: false` and use `refetch` when needed. `refetch` will ignore `enabled` flag. Great!

Thanks for your help!
