### ISSUE TITLE
[vue-query] Query type breaks when using generics as a parameter of useQuery

### ISSUE THREAD

**Issue by joaopslins** [TanStack/query#6091]
### Describe the bug

When using a generic type in `useQuery`, the return value of `data` is not correctly inferred.

I got this after updating from 4.35.3 to 4.35.6. After changelog inspection, I believe it's related to this change:

PR: https://github.com/TanStack/query/pull/6043

Type change in `useBaseQuery`: https://github.com/TanStack/query/pull/6043/files#diff-996721944b77ab3155cb5f86364575311132aeaaff8f7f715755bfcc9fc09108R34-R38

I tried to reproduce in a Code Sandbox but couldn't get the environment right, so I did a Github Repro instead, apologies for the inconvenience.

For convenience, I'm pasting the reproduction code here:

```typescript
import { useQuery } from '@tanstack/vue-query'

let f: <T>() => T

interface MyType {
  a: number
}

const useTestRepro = <K extends MyType>() => {
  const myFetch = async (): Promise<K> => {
    return Promise.resolve(f<K>())
  }

  const query = useQuery([], myFetch)

  console.log(query.data.value.a)

  return query
}

export default useTestRepro
```

I'm not an expert in Typescript generics, so I think I need to inform Typescript that my generic does not have properties that are functions, but after trying for a while, I couldn't get it right. So it's either that or the new typing is wrong.

### Your minimal, reproducible example

https://github.com/joaopslins/vue-query-repro

### Steps to reproduce

1. Checkout https://github.com/joaopslins/vue-query-repro locally, install dependencies with `npm install`

2. Open https://github.com/joaopslins/vue-query-repro/blob/master/src/composables/useTestRepro.ts in your IDE

3. Assert that `.value` property access throws an error

### Expected behavior

`.value` property access shouldn't throw an error

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/15643533/63742ad7-2e58-429e-b83c-4d2cbe66c4e3)

### Platform

- OS: Mac
- IDE: RubyMine (Jetbrains)

### Tanstack Query adapter

vue-query

### TanStack Query version

v4.35.6

### TypeScript version

v5.2.2

**Comment by TkDodo** [comment]
issue is reproducible in typescript playground:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ5wC+cAZlBCHAOQACMAhgHaoMDGA1gPQBuOAtAEcc+KgFgAUBIA26eCQBccADwAVAHwAKAJRwAvGrgqJE4Ixi4S9VujgBZPCrxgbCCXDj1FjZCABGuCUJjcVYIZng0dBV0FgAldDByPWUAaTh0AA9zRgATVDsHJ3RNHX1ENzhQ8LgQPAAxWVYAC2T6VDxGVjhtRQAFchBgDCUUgzLXcXd3KFlkKEY4fooh9AA6GdQIKW50DRIRkq0KoMlJyrCWOCFcAl0UDGwbjQBtKnZ0PCoAXQAaGvrGk0jqd3FVNjJVlIIABzDTXfCrHL0Birbj0KQ4Vb0YEVGYwOYLeF4QLBTKQWBwHLoSzIKQRDDROIJchAA

@DamianOsipiuk fyi
