### ISSUE TITLE
[v5] firstPageParam from getPreviousPageParam is always same

### ISSUE THREAD

**Issue by danilo-89** [TanStack/query#6094]
### Describe the bug

`firstPageParam` is always returning same value.

```
const {
    isPending,
    error,
    data,
    fetchNextPage,
    hasNextPage,
    hasPreviousPage,
} = useInfiniteQuery({
    queryKey: ['notifications'],
    queryFn: ({ pageParam }) => getNotifications(pageParam),
    initialPageParam: 1,
    staleTime: Infinity,
    getNextPageParam: (lastPage, allPages, lastPageParam) => {
        console.log(lastPageParam)                                          // logs: // 1 // 2 // 3 // 4
        return Number(lastPage?.meta?.next?._page) || undefined
    },
    getPreviousPageParam: (firstPage, allPages, firstPageParam) => {
        console.log(firstPageParam)                                          // logs: // 1 // 1 // 1 // 1
        return Number(firstPage?.meta?.first?._page) || undefined
    },
})
```

based on this example from the docs I think it should return current page number
(if this is the case, I would also suggest changing both `lastPageParam` and `lastPageParam` to `currentPageParam` in the docs):
https://tanstack.com/query/v5/docs/react/guides/infinite-queries#what-if-my-api-doesnt-return-a-cursor

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/empty-sea-w2fnqx?embed=1&file=%2Fsrc%2Fpages%2Findex.js%3A41%2C7-42%2C12

### Steps to reproduce

1. create basic example with useInfiniteQuery
2. log `firstPageParam` from `getPreviousPageParam: (firstPage, allPages, firstPageParam)`

### Expected behavior

`firstPageParam` from `getPreviousPageParam` should return current `pageParam` instead of `initialPageParam`

### How often does this bug happen?

Every time

### Platform

- OS: MacOS (m1)
- Browser: Chrome 117.0.5938.92

### Tanstack Query adapter

react-query

### TanStack Query version

5.0.0-rc.4

**Comment by TkDodo** [comment]
> I would also suggest changing both lastPageParam and lastPageParam to currentPageParam in the docs

- `lastPageParam` is the page param of the last page in the cache
- `firstPageParam` is the page param of the first page in the cache

> Your minimal, reproducible example

The sandbox you're showing is made with v4. I've forked it and upgraded the syntax to v5, and it works as expected for me:

https://codesandbox.io/p/sandbox/sad-boyd-2cvk59

initially I have `{firstPageParam: 0}`. Then, if I click `load older`, I see `{firstPageParam: -5}`. Clicking once more, I see {firstPageParam: -10}

**Comment by danilo-89** [comment]
@TkDodo Thank you and sorry for the wrong version in the example.

I added the 'Load Newer' button to your example: 
https://codesandbox.io/p/sandbox/crazy-danny-fx4gq3?file=%2Fsrc%2Fpages%2Findex.js%3A88%2C8

Now, when "Load Older" is clicked two times in a row, and there is nothing to load more ("Load Older" button is disabled) and when 'Load Newer' is clicked,  "Load Older" remains disabled.
Same problem happens vice versa for 'Load Newer' button in the opposite direction.

video: [screen-capture.webm](https://github.com/TanStack/query/assets/58806247/9d204a71-fa9c-4ca4-b89f-4f269535f4fd)

**Comment by TkDodo** [comment]
why is this a problem? Why would you expect the buttons to be enabled again?

Our backend ("database") has the following project ids:

```
-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
```

those are junked into pages. we start with loading the first page, which is:

`[0,1,2,3,4]`

now we can go two times into the "previous" direction to get:

`[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4]`

and then, we can go into the forward direction to get projects with id 5 and upwards. But getting "newer projects" doesn't give us more projects to load in the previous direction - we've literally loaded everything that is in the database already ...

unless of course you use the `maxPages` option, which you don't....
