### ISSUE TITLE
[bug] Calling createQuery does not actually fire the query

### ISSUE THREAD

**Issue by aryzing** [TanStack/query#6097]
### Describe the bug

In Svelte, calling `createQuery()` doesn't fire the query. Nothing at all happens. Even when setting `refetchOnMount: "always",`.

```svelte
<script>
  createQuery(/*...*/); // nothing happens when this code runs. No network request made.
</script>
```

Seems that the query is only called if it is assigned to a variable *and* the variable is used somewhere in the markup,

```svelte
<script>
  const q = createQuery(/*...*/);
</script>

<div>{$q.data}</div>
```

In Selte, how can a query be set up for side effects, or to use it's `onSuccess` callback?

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/young-bird-qyvm9m?embed=1&file=%2Fsrc%2Flib%2FSimple.svelte%3A15%2C5

### Steps to reproduce

Just create any query with `createQuery` without actually assigning it to a variable.

### Expected behavior

`createQuery()` should execute the query regardless of whether it's assigned to a variable or not, assuming the options it is set up with allow for it to execute

### How often does this bug happen?

Every time

### Platform

All

### Tanstack Query adapter

None

### TanStack Query version

"@tanstack/svelte-query": "^4.20.0"

### TypeScript version

^4.7.4

**Comment by TkDodo** [comment]
@lachlancollins FYI

**Comment by softgripper** [comment]
The pattern is standard [svelte store pub/sub](https://svelte.dev/docs/svelte-store).

The beauty of this is, the queries only execute if they are used, not just defined.  This has a number of benefits, especially when dealing with nested routes, or conditionally displayed fields.

Think of `createQuery()` as `createQueryDefinition()` and subscribing to it will cause it to activate the query.  It'd be really strange for this to fire the query.

The easiest thing for you to do would be use onMount to actually mount the query, and cause a subscription.

```ts
 import { onMount } from 'svelte'

 const query = createQuery<Repo, Error>({
    refetchOnMount: "always",
    queryKey: ['repoData'],
    queryFn: async () =>
      await fetch('https://api.github.com/repos/SvelteStack/svelte-query').then(
        (r) => r.json(),
      ),
    onSettled() {
      console.log("Settled") // This never logs because the query is never fired.
    }  
  })

 onMount(query.subscribe)
```
or even `$: $query;` or [`get(query)`](https://svelte.dev/docs/svelte-store#get)

Imo, this is not a bug, just an implementation misunderstanding of how pub/sub works, especially with regard to component lifecycles.

**Comment by aryzing** [comment]
@softgripper excellent explanation, thank you. 

The example in the original post doesn't have any assignments because the idea was to use the creation of the query for side effects with `onSuccess`. Good to know the same can be done by explicitly calling `.subscribe`.

I'm leaning towards closing this issue then if it's working as intended. Not having explicit reactive primitives available makes it hard to know whether things are working as intended, and it can be even harder to debug when different libraries are interacting with each other.

**Comment by softgripper** [comment]
Glad to help.

I rely on this behavior for my current project.

It's important to understand the subscribe methods behavior.  Subscribe returns another function that is used to unsubscribe.

Svelte handles this unsubscribe automatically from usages of the store inside svelte components if you're using `$store` notation.

Also, when using [onMount](https://svelte.dev/docs/svelte#onmount), it's signature is the following.

```typescript
function onMount<T>(
	fn: () => // <-- this could be the zero args subscribe
		| NotFunction<T>
		| Promise<NotFunction<T>>
		| (() => any) // <-- this becomes the unsubscribe
): void;
```


so it might look weird doing 

```typescript
onMount(query.subscribe)
```

but its essentially 
```typescript
onMount(() => { 
  query.subscribe()
})
```
without the extra arrow function that does nothing.

Unsubscribing is important, as it will stop things being active (eg, why refetch a bunch of queries if they're no longer in use by any current part of your app).

I think I got that all right.

Good luck :)
