### ISSUE TITLE
[solid-query] v4.35.7 package is missing build/solid files

### ISSUE THREAD

**Issue by beanow-at-crabnebula** [TanStack/query#6098]
### Describe the bug

Importing the updated package I get this error:
> Failed to resolve entry for package "@tanstack/solid-query". The package may have incorrect main/module/exports specified in its package.json.

Inspecting the `package.json` it seems we're expecting a `build/solid` path.
https://github.com/TanStack/query/blob/85b76b8789621e1ba3f0b3f9e755f8fac48c8edf/packages/solid-query/package.json#L23

But in the actual npm package this directory does not exist.
https://www.npmjs.com/package/@tanstack/solid-query/v/4.35.7?activeTab=code
![image](https://github.com/TanStack/query/assets/118052430/ebaf10ec-89f7-45b0-a090-8f28dcdaa8d6)

Downgrading to the previous release `v4.35.3` fixes the issue.

### Your minimal, reproducible example

https://www.npmjs.com/package/@tanstack/solid-query/v/4.35.7?activeTab=code

### Steps to reproduce

1. Install / update to `@tanstack/solid-query` `v4.35.7`
2. Using any bundler (in my case Vite, through commonjs resolver) it should fail to resolve when building.

### Expected behavior

1. Install / update to `@tanstack/solid-query` `v4.35.7`
2. The bundler resolves and `solid-query` correctly.

### How often does this bug happen?

Every time

### Platform

Linux, during build.

### Tanstack Query adapter

solid-query

### TanStack Query version

v4.35.7

**Comment by timothyallan** [comment]
Yeah, we are getting this too and had to downgrade:

`An unhandled error occured: Error: Failed to resolve entry for package "@tanstack/solid-query". The package may have incorrect main/module/exports specified in its package.json.`

In related bugs, whoever wrote that error message is missing the second R in occurred :)

**Comment by TkDodo** [comment]
not sure what happened here, but I triggered a re-release and it seems to be fine now. Please see: https://www.npmjs.com/package/@tanstack/solid-query/v/4.36.1?activeTab=code
