### ISSUE TITLE
[solid-query v5] Solid Start dependent query from context throws error (missing `defaultQueryOptions`)

### ISSUE THREAD

**Issue by m4rvr** [TanStack/query#6102]
### Describe the bug

Hey! I'm using Solid Start with the Cloudflare Pages adapter, `ssr: false` and solid-query v5-rc.4.

I've noticed that when I provide a query via context within a layout to my routes and use that result for a different query that depends on the result somewhere inside the nested route, I get the following error when navigating from somewhere else to that route:
![CleanShot 2023-10-03 at 20 25 03](https://github.com/TanStack/query/assets/6840287/025af428-a118-4a33-b0c2-7f042e9e1db2)

Reloading that route or directly navigating to it works fine though. It only happens when the route wasn't loaded before.

### Your minimal, reproducible example

https://stackblitz.com/edit/github-czovmr

### Steps to reproduce

1. Go to the home route
2. Click on the "Nested" menu item
3. Error appears

### Expected behavior

There shouldn't be an error

### How often does this bug happen?

Every time

### Screenshots or Videos

![CleanShot 2023-10-03 at 20 29 51](https://github.com/TanStack/query/assets/6840287/ed1bbb28-fb75-4e60-908c-48ae8b16c0ba)

### Platform

- macOS Ventura 13.6
- Chrome v117.0.5938.92

### Tanstack Query adapter

solid-query

### TanStack Query version

rc-4

### TypeScript version

v5.2.2

**Comment by TkDodo** [comment]
@ardeora FYI

**Comment by ardeora** [comment]
Should be fixed in #6125  

Reproduction here https://stackblitz.com/edit/github-czovmr-z3ccfm?file=src%2Froutes%2Fnested%2F[id]%2Findex.tsx

**Comment by ardeora** [comment]
Should be fixed in the new versions and up! `v5.0.0-rc.8`
If you could please update your dependency and check if it works as expected, that would be awesome :D 

Here is the reproduction with the new version
https://stackblitz.com/edit/github-czovmr-yqt3yz

**Comment by m4rvr** [comment]
> Should be fixed in the new versions and up! `v5.0.0-rc.8` If you could please update your dependency and check if it works as expected, that would be awesome :D
> 
> Here is the reproduction with the new version https://stackblitz.com/edit/github-czovmr-yqt3yz

It works now. 😊
Thank you very much, Aryan – you're the king! 👏
