### ISSUE TITLE
[vue-query] Dependent queries's observer gets disconnected during SSR

### ISSUE THREAD

**Issue by Colonel-Sandvich** [TanStack/query#6133]
### Describe the bug

During Vue's SSR all reactivity is disabled which means if you have a dependent query, that query's `QueryObserver` isn't updated with the new resulting query key. (Poorly worded I know sorry).

```ts
const {
  data: id,
} = useQuery();

const enabled = computed(() => !!id.value);

const {
  data: second,
} = useQuery({
  queryKey: ['second', { id }],
  enabled,
});
```

Here we have a query depending on the result of another. At this point in script setup before `onServerPrefetch` the second query creates an observer tracking the query: `['second']` since `id` is undefined. Then in `onServerPrefetch` `id` is resolved and updates which would normally cause [this watcher](https://github.com/TanStack/query/blob/rc/packages/vue-query/src/useBaseQuery.ts#L128) to run and then the observer correctly tracks the query: `['second', { id: $someValue }]` but since watchers are disabled during SSR this never happens and the result of the second query is not updated in time for render. This causes a hydration mismatch too as the cache is actually populated with the correct values.

I hope you understood that, I'm not that great at explaining but the repro should show the issue too.

### Your minimal, reproducible example

https://stackblitz.com/edit/nuxt-starter-jguhre?file=app.vue

### Steps to reproduce

See the console output.

### Expected behavior

`second.value` is undefined but should be defined.

### How often does this bug happen?

Every time

### Platform

Node v20.7.0

### Tanstack Query adapter

vue-query

### TanStack Query version

v5.0.0-rc.6

### Additional context

Repro uses v4.32.6 but I can reproduce this on v5.0.0-rc.6.

**Comment by Mini-ghost** [comment]
You can try the following example, perhaps it will solve your problem.

Stackblitz: https://stackblitz.com/edit/nuxt-starter-3s4bmt?file=app.vue

```vue
<script setup lang="ts">
import { onServerPrefetch } from 'vue';
import { useQuery } from '@tanstack/vue-query';

const queryFn = (res) => () =>
  new Promise((resolve) => setTimeout(() => resolve({ text: res }), 50));

const {
  data: first,
  isLoading: firstLoading,
  suspense: firstSuspense,
} = useQuery({
  queryKey: ['first'],
  queryFn: queryFn('first'),
});

onServerPrefetch(async () => firstSuspense());
await firstSuspense();

const firstText = computed(() => first.value?.text);
const enabled = computed(() => !!firstText.value);

const {
  data: second,
  isLoading: secondLoading,
  suspense: secondSuspense,
} = useQuery({
  queryKey: ['second', { firstText }],
  queryFn: queryFn('second'),
  enabled,
});

onServerPrefetch(async () => secondSuspense());
</script>

<template>
  <div>
    {{ first.text }}
    <div v-if="!secondLoading">
      {{ second.text }}
    </div>
  </div>
</template>

```

**Comment by 4350pChris** [comment]
> You can try the following example, perhaps it will solve your problem.
> 
> Stackblitz: https://stackblitz.com/edit/nuxt-starter-3s4bmt?file=app.vue
> 
> ```
> <script setup lang="ts">
> import { onServerPrefetch } from 'vue';
> import { useQuery } from '@tanstack/vue-query';
> 
> const queryFn = (res) => () =>
>   new Promise((resolve) => setTimeout(() => resolve({ text: res }), 50));
> 
> const {
>   data: first,
>   isLoading: firstLoading,
>   suspense: firstSuspense,
> } = useQuery({
>   queryKey: ['first'],
>   queryFn: queryFn('first'),
> });
> 
> onServerPrefetch(async () => firstSuspense());
> await firstSuspense();
> 
> const firstText = computed(() => first.value?.text);
> const enabled = computed(() => !!firstText.value);
> 
> const {
>   data: second,
>   isLoading: secondLoading,
>   suspense: secondSuspense,
> } = useQuery({
>   queryKey: ['second', { firstText }],
>   queryFn: queryFn('second'),
>   enabled,
> });
> 
> onServerPrefetch(async () => secondSuspense());
> </script>
> 
> <template>
>   <div>
>     {{ first.text }}
>     <div v-if="!secondLoading">
>       {{ second.text }}
>     </div>
>   </div>
> </template>
> ```

Thanks! However, using `await` at top level turns the component into [an async component](https://vuejs.org/api/sfc-script-setup.html#top-level-await) which requires me to change code that uses that component to wrap it in `Suspense` which I'd rather avoid as multiple components would need to change and suspense is still experimental.

**Comment by Mini-ghost** [comment]
Ummm... I remember that Nuxt has `<Suspense>` enabled by default internally, but I'm not sure if it can be turned off manually?

**Comment by 4350pChris** [comment]
I'm not using nuxt, I just used it for the example. For other SSR libraries you need to use vue's experimental API.

**Comment by Mini-ghost** [comment]
@4350pChris You're right, and I apologize for not considering possibilities outside of Nuxt.
