### ISSUE TITLE
useInfiniteQuery refetches all pages up to the lastPage "pageNumber" value that is not updated 

### ISSUE THREAD

**Issue by efkan** [TanStack/query#6137]
### Describe the bug

I have React-Query implementation on React-Native.

If I open the screen that has `useInfiniteQuery` and start to scroll down to the end of the page.
Let's assume I reached down to _page 6_ and returned from that screen to its parent screen. 

If I reopen that screen `useInfiniteQuery` performs _6 API calls_ to reach the page where I left off.
This behavior makes users wait for a couple of seconds.

👍 Adding a callback to remove that query prevents this issue.

Other tries:
• Even if I return `1` for `getNextPageParam` it tries to make even the current page number with the `lastPage.PageNumber` value.
• When I block some of those requests it returns duplicate items. 

### Some screenshots related to this issue
<br />

When the screen opens the first time, it performs only 1 API call:

<img width="625" alt="image" src="https://github.com/TanStack/query/assets/6974198/11b4b99d-db21-41a9-85e3-5f34adebef96">

<br /><br />
When the screen re-opens after scrolling down 6 pages distance, _it performs 6 API calls automatically_:

![image](https://github.com/TanStack/query/assets/6974198/90b06164-61ab-4b00-8136-41ceb324d085)

<br /><br />
A related piece of code:

<img width="789" alt="image" src="https://github.com/TanStack/query/assets/6974198/90263883-367f-4074-9e27-536d77bffca1">

### Your minimal, reproducible example

https://snack.expo.dev/

### Steps to reproduce

No reproducible example

### Expected behavior

The `lastPage.PageNumber` value should be reset once the component is unmounted.

### How often does this bug happen?

Every time

### Platform

-OS: macOS
-Browser: React Native
-Version: 0.71.11 (React Native version)

### Tanstack Query adapter

None

### TanStack Query version

v4.29.13

### TypeScript version

v4.9.4

**Comment by TkDodo** [comment]
set a staleTime on your query to avoid revalidations you don't like
