### ISSUE TITLE
refetchOnWindowFocus is set to false but it is not overriding global configuration which is by default true

### ISSUE THREAD

**Issue by SakarDev** [TanStack/query#6149]
### Describe the bug

When using `useQuery` with a specific configuration for `refetchOnWindowFocus` set to `false`, it seems not to override the global default, which is set to `true`. Despite specifying the query-level configuration, the query still refetches on window focus.

### Your minimal, reproducible example

`  const { data, error } = useQuery({ queryKey: ["data"], queryFn: fetchData }, { refetchOnWindowFocus: false});`

### Expected behavior

Expected behavior is DO NOT fetch on window focus but it does!

### How often does this bug happen?

Every time

### Platform

- Next.js  v13.5.4
- react-query v4.36.1

### Tanstack Query adapter

react-query

### TanStack Query version

v4.36.1

### Additional context

But if i set it to false `globally `which is **not what i want**, it works:
` const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        refetchOnWindowFocus: false,
      },
    },
  });`

**Comment by TkDodo** [comment]
>   const { data, error } = useQuery({ queryKey: ["data"], queryFn: fetchData }, { refetchOnWindowFocus: false});

this is not valid syntax. You want one object passed to useQuery:

```
const { data, error } = useQuery({
  queryKey: ["data"],
  queryFn: fetchData,
  refetchOnWindowFocus: false,
})
```

**Comment by SakarDev** [comment]
You are right! Sorry about the confusion!
