### ISSUE TITLE
useQuery isError not correctly updating

### ISSUE THREAD

**Issue by Keithagy** [TanStack/query#6165]
### Describe the bug

Per [the useQuery docs for the latest version of TanStackQuery](https://tanstack.com/query/latest/docs/react/reference/useQuery), `queryFn` should:
`Must return a promise that will either resolve data or throw an error`

However, I've been unable, per my understanding of that description, to trigger the the `isError`-dependent rendering. I don't see any issues outstanding for this relatively basic piece of functionality, so I'm fairly certain that I'm misunderstanding something, but may I please have some help understanding what's going on in the stackblitz attached?

### Your minimal, reproducible example

https://stackblitz.com/edit/stackblitz-starters-zdeaa2?file=src%2FPart.tsx

### Steps to reproduce

in `Part.tsx`:
1. Running the code as-is results in a thrown runtime error
2. Commenting out the block marked `UNEXPECTED BEHAVIOR 1`, comment in the block marked `UNEXPECTED BEHAVIOR 2`
3. Observe that the page never re-renders
4. Comment out `UNEXPECTED BEHAVIOR 2` comment in `EXPECTED BEHAVIOR` to see that the promise-resolved case works fine

### Expected behavior

I expected that the error-thrown case (`UNEXPECTED BEHAVIOR 1`) would have been caught by an error boundary internal to the `useQuery` hook to trigger the throw-driven `isError` rendering, since the docs indicated that thrown errors and rejected promises trigger the `isError` status. However, I had observed `isError` based rendering on neither of the two cases outlined in the documentation (as I have understood it, at least) 

### How often does this bug happen?

Every time

### Platform

MacOS but reproduction on the codepen gives the same behavior too.

### Tanstack Query adapter

react-query

### TanStack Query version

^5.0.0

### TypeScript version

NA (observed on both JS and TS)

**Comment by TkDodo** [comment]
ad UNEXPECTED BEHAVIOR 1:

you're throwing an error _inside_ a promise. if you want to throw promises, do:

```
queryFn: async () => {
  throw new Error('ok?');
},
```

ad UNEXPECTED BEHAVIOR 2:

this works correctly, there are 3 retries per default with exponential backoff; you can see the `failed` text after about 30s. this is customizable.

ad
