### ISSUE TITLE
Can't createQuery outside of a svelte component, even when providing your own queryClient

### ISSUE THREAD

**Issue by softgripper** [TanStack/query#6188]
### Describe the bug

When providing my own queryClient in a `+page.ts` load function, calling `createQuery(opts, queryClient)` throws an error before the query is created.

Svelte's `getContext` throws if it's not inside a component, and this happens to be called during the createQuery call.

```log
+page.ts:18 Error: Function called outside component initialization
    at get_current_component (chunk-XXZCQZAU.js?v=e97699bd:1202:11)
    at getContext (chunk-XXZCQZAU.js?v=e97699bd:1241:10)
    at getIsRestoringContext (@tanstack_svelte-que…?v=e97699bd:2603:23)
    at useIsRestoring (@tanstack_svelte-que…?v=e97699bd:2614:10)
    at createBaseQuery (@tanstack_svelte-que…?v=e97699bd:2632:23)
    at createQuery (@tanstack_svelte-que…?v=e97699bd:2657:10)
    at load (+page.ts:10:18)
    at async load_node (client.js?v=e97699bd:530:14)
```

Specifically it's from here

 `@tanstack/svelte-query/context.ts`
```typescript
export const getIsRestoringContext = (): Readable<boolean> => {
  const isRestoring = getContext(_isRestoringContextKey) // <-- this line
  if (!isRestoring) return readable(false)
  return isRestoring as Readable<boolean>
}
```

### Your minimal, reproducible example

https://stackblitz.com/edit/stackblitz-starters-6h9bak?file=src%2Froutes%2F%2Bpage.ts

### Steps to reproduce

1. open the stackblitz link
2. wait for it to run
3. observe error in the browser tools

### Expected behavior

I expect to be able to create the query if I provide the queryClient outside of a svelte component.

### How often does this bug happen?

Every time

### Platform

- node: 18.18.1
- svelte: "^4.2.1"
- @sveltejs/kit: "^1.25.1"

### Tanstack Query adapter

svelte-query

### TanStack Query version

v5.0.0

### TypeScript version

v5.2.2

### Additional context

I've got a patch to workaround this - and my application works as expected.
[@tanstack+svelte-query+5.0.0.patch](https://github.com/TanStack/query/files/13038629/%40tanstack%2Bsvelte-query%2B5.0.0.patch)

```patch
diff --git a/node_modules/@tanstack/svelte-query/src/context.ts b/node_modules/@tanstack/svelte-query/src/context.ts
index 98ca5d6..860efcb 100644
--- a/node_modules/@tanstack/svelte-query/src/context.ts
+++ b/node_modules/@tanstack/svelte-query/src/context.ts
@@ -26,9 +26,13 @@ const _isRestoringContextKey = '$$_isRestoring'
 
 /** Retrieves a `isRestoring` from Svelte's context */
 export const getIsRestoringContext = (): Readable<boolean> => {
-  const isRestoring = getContext(_isRestoringContextKey)
-  if (!isRestoring) return readable(false)
-  return isRestoring as Readable<boolean>
+  try {
+    const isRestoring = getContext(_isRestoringContextKey)
+    if (!isRestoring) return readable(false)
+    return isRestoring as Readable<boolean> 
+  } catch (error) {
+    return readable(false);
+  }
 }
 
 /** Sets a `isRestoring` on Svelte's context */
```

I'm unsure of any downstream impacts, but it's a simple change that allows the application to work, and means there isn't a bunch of repeated boilerplate "createQuery" calls inside each component.

**Comment by softgripper** [comment]
Fwiw, I'm no longer using this pattern, although I still find it strange the error can occur when providing your own queryClient.

**Comment by frederikhors** [comment]
@softgripper what pattern are you using now?

**Comment by softgripper** [comment]
> @softgripper what pattern are you using now?

I'm just using createQuery at the top of my pages.svelte files.

I have my mutations and queries defined in `$lib/api/query` and `$lib/api/mutate` and a keys file `$lib/api/keys`

So I just do like

const myQuery = createQuery(keys.account(accountId))

I'm writing an admin app, and this is working well.

It's a little bit of a pain in the ass with callbacks, but I haven't the time to delve into it too deeply.

TkDodo's blog is a worthy read btw.

**Comment by frederikhors** [comment]
> I'm writing an admin app, and this is working well.

It would be amazing to read more code about this. Can you post a reduced project? @softgripper

**Comment by multiplehats** [comment]
Bit late, but here's how I'm doing it right now:

```ts
import type { CreateMutationOptions, QueryClient } from '@tanstack/svelte-query';
import { __ } from '@wordpress/i18n';
import { triggerAddedToCartEvent, triggerFragmentRefresh } from '$frontend/lib/utils/legacyEvents';
import { QueryKeys } from '$frontend/lib/utils/query-keys';
import { CartApiService } from '$frontend/modules/cart/cart.service';
import type { AddCartItemBatchParams } from '$frontend/modules/cart/cart.service';
import toast from '$frontend/modules/notifications';
import type { Cart } from '@cartpops/types';

const service = new CartApiService();

type AddCartItemMutationConfig = CreateMutationOptions<Cart, unknown, AddCartItemBatchParams, unknown>;

export function addCartItemMutationConfig(
	queryClient: QueryClient,
	opts: Partial<Omit<AddCartItemMutationConfig, 'mutationFn' | 'onSuccess'>> = {}
): AddCartItemMutationConfig {
	return {
		mutationFn: (params) => service.addCartItem(params),
		onSuccess: (newCart) => {
			queryClient.setQueryData<Cart>([QueryKeys.cart], newCart);
			triggerAddedToCartEvent({ preserveCartData: true });
			triggerFragmentRefresh();
			toast.success(__('Product has been added to your cart.', 'cartpops'));
		},
		...opts
	};
}

```

My component:

```html
<script lang="ts">
	import { useQueryClient, createMutation } from '@tanstack/svelte-query';
	import { addCartItemMutationConfig } from '$frontend/modules/cart/cart.mutations';

	const client = useQueryClient();
	const addCartItemMutation = createMutation(addCartItemMutationConfig(client));
</script>

<!-- Omitted for brevity -->
````
