### ISSUE TITLE
Svelte: passing a store to `createQuery` breaks typescript

### ISSUE THREAD

**Issue by ottomated** [TanStack/query#6197]
### Describe the bug

In v5, it's encouraged to pass stores to `createQuery` rather than re-creating the query with a reactive expression. However, doing so with a derived query completely breaks type-safety for the options object. An example as simple as this does not work:

```ts
const search = writable('');

const searchQuery = createQuery(
  derived(search, ($search) => ({
    queryKey: ['search', $search] as const,
    queryFn: ({ queryKey }) => {
      // queryKey is of type `any` instead of `readonly ['search', string]`
    },
  }))
);
```

Unfortunately, this makes `@tanstack/svelte-query` nearly unusable.

### Your minimal, reproducible example

[Typescript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQRQK5pQCecAvnAGZQQhwDkAAjBgHYDOzyA1gPRsBuaADbYAtAEcCxOgG4AUKEixEcAO5RgzAEZC0AGjgATQsEGGylarToDh2PjGhpZcuTx5wAQgCUA8gGkAUQA5AC5XZAh2eDZMKGQACzgAXjUNbV0ACjo6AEp5OUjouFiMeIT8QhJU1ExsSuJMuTgWoxMzTNLyg0yAEi7E3JSAPjhMhGbWqbQWDB00Q1C4frjEgDpdFgBzGCTRgAY9SamWgElggDUAQQAZU4ARAH0ggE0lmCgCI5PW9yMINBsOAsCDwdBKeCsOCEahQOAAPVcPxakiq-jQRCWAG0bKsEnQDCsyokALpwDBAoocb7I1HEABiLCW4zgdKI6JIpCGyVGE2RJz+J3hAH5jidSDSfugPpixo8DDDoNzRh8vmKpoLkSKxVzcnJ8q43B4AOq+bz+c4AcXChSiHBKeIATCl6C5bcUBhUpERnTV0FhcN7xmKZnNdIsHcSEo6NjMdns4Icxedrncnq93p99GK-mBqGBCEISODoDAgVDFXDEWK2RzsbiowTI+VHWSKSg7TBJazvYzmUhaxiyMrEOrfh4haKphKxdLiMz5dCoLCR6rsxqJ1rRVyZEA)

### Steps to reproduce

1. Create a derived store
2. Pass said store to `createQuery`
3. Observe the broken types

### Expected behavior

I expect type-safety to work regardless of if the query options are wrapped inside a store.

### How often does this bug happen?

Every time

### Tanstack Query adapter

svelte-query

### TanStack Query version

v5.0.1

### TypeScript version

v5.2.2

**Comment by TkDodo** [comment]
from what I can see, `satisfies CreateQueryOptions` would work:

[TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQRQK5pQCeANHAMLpa4HEDyYMwEAdgM5wC+cAZlBCDgByAAIwM7ccgDWAejYA3NABtsAWgCOtIkIDcAKFCRYiOAHcowcQCNlaMgBNCwJQ669+goYpXZ5MaDQ9fX1ZWTgAIQAlOgBpAFEAOQAuEORWNng2TChkAAs4AF5zSxs7AAohIQBKA310yThsjFy8-EIiIpQqbHbicv04IbgnS1dy5taycoASSfzqooA+OHKEQeHNtBYMWzQHZLg5nPyAOjsWAHMYApWABhINzaGASUSANQBBABkXgBEAPoJACahxgUAIj2ewzCIwgaA4LAg8HQxngEjghH4UDgAD0QtChloOrE0ERDgBtbwnPJCMjHFr5AC6cAwHAamShhOJxAAYixDms4DyiKTOpxFoUVutCc9Yc9cQB+J7PThc6HocHk1YAshY6CSlbgyEqzbywlKlXcNhYYBsHjABEUHo0DoMJgZarVfS1EKhcIAdToUVibwA4ql6hksjSAExdKp1DkxxltbTx4qoTC9bRrFXbXZ2A5NOPnbbXW5wB4qt5fX6AkFgiH2FWwsD8MCEZSdVHQGAcDH6nH4lUisWU6mpukl1OxllslDR9XC7T8wVIMdkriGxCmmHhBXKzZqlWa4iC3WYqDYnfGltmg8W5US3RAA)

other than that, we have to look into making the `queryOptions` API that we released in the react adapter of v5 available to other adapters as well. It would likely solve this.

@lachlancollins FYI

**Comment by TkDodo** [comment]
yes, I noted that. `queryOptions` would do this. Do you want to contribute it to the svelte adapter? The react adapter should have most of the infos:

https://github.com/TanStack/query/blob/1dc5758518594c82f5399deeb30e393b27d0a91a/packages/react-query/src/queryOptions.ts

**Comment by ottomated** [comment]
Made a PR #6211

**Comment by o-az** [comment]
still broken
