### ISSUE TITLE
codemod: uncovered cases by v5 upgrade with remove-overloads

### ISSUE THREAD

**Issue by gillkyle** [TanStack/query#6204]
### Describe the bug

I spent about 30 min (not bad!) updating my codebase at work to newly released v5. I attempted to use the codemod and it handled many of my cases, mostly with functions like `invalidateQueries` and `refetchQueries` without problem. 

However, it didn't catch a couple cases that I had to go handle with some crafty find/replace'ing. On [Twitter](https://twitter.com/balazsmatepetro/status/1715251748418338999) it was recommended I could pass along some snippets that didn't work with the codemod.

They are in the following cases:
1. the `useMutation` hook as a custom React hook:
```
// these custom mutation hooks required me to add mutationFn
export function useDeleteSomething(): any {
  return useMutation(({ groupId }: { groupId: string }) => {
    return fetch(`/api/groups/${groupId}`, {
      method: "DELETE",
    });
  });
}
```

2. a custom `useQuery` hook as my own React hook:
```
// these custom query hooks required me to change some variable names and use the single object syntax
export function useDetails({ groupId }: { groupId?: string }): any {
  const cacheKey = ["details", groupId];
  const query = () => fetch(`/group/${groupId}`);
  const queryObject = useQuery(cacheKey, query, {
    enabled: !!groupId,
  });
  return queryObject;
}
```

### Your minimal, reproducible example

https://stackblitz.com/github/gillkyle/query-v5-codemod?file=src%2Fhooks.ts

### Steps to reproduce

1. Run `npm install` or `bun install` (in my [repro](https://stackblitz.com/github/gillkyle/query-v5-codemod?file=src%2Fhooks.ts), see [GitHub repo here](https://github.com/gillkyle/query-v5-codemod))
2. Run the codemod via the version in `node_modules`:
```
npx jscodeshift ./src/ \
  --extensions=ts,tsx \
  --parser=tsx \
  --transform=./node_modules/@tanstack/react-query/build/codemods/src/v5/remove-overloads/remove-overloads.js
```

### Expected behavior

I thought maybe the codemod would be able to catch when I provided variables to my query hooks, and that mutations might be able to get wrapped as single objects appropriately.

### How often does this bug happen?

None

### Platform

Output: 
```
Processing 1 files...
Spawning 1 workers...
Sending 1 files to free worker...
All done.
Results:
0 errors
1 unmodified
0 skipped
0 ok
```

### Tanstack Query adapter

react-query

### TanStack Query version

v5.0.0

### TypeScript version

v5.0.0

**Comment by gillkyle** [comment]
Thanks for making a codemod, it did save me a bunch of time!

**Comment by TkDodo** [comment]
@balazsmatepetro FYI

**Comment by slax57** [comment]
According to my tests, with `@tanstack/react-query@5.13.4`, the custom `useQuery` case is now correctly handled.

However the `useMutation` hook is still ignored, requiring to add `mutationFn` manually.

**Comment by TkDodo** [comment]
@slax57 yeah this issue is fixed, I just forgot to close it. If there's something else that isn't working, please open another issue with a reproduction, thank you.

**Comment by slax57** [comment]
@TkDodo Thanks for the update.

Actually in my post, I explain that the first issue is solved **but the second is not** (about `mutationFn`)

Would you like me to open a new issue for this second problem?

**Comment by TkDodo** [comment]
> Would you like me to open a new issue for this second problem?

yes please

**Comment by slax57** [comment]
Done: https://github.com/TanStack/query/issues/6548

Thanks for your time! :pray:
