### ISSUE TITLE
Can not use react-query v5 with canary react

### ISSUE THREAD

**Issue by artem-malko** [TanStack/query#6219]
### Describe the bug

I've tried to use react-query v5 with canary react `18.3.0-canary-d803f519e-20231020`

There is a log from npm install (npm is 9.6.7):

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @artem-package/frontend@1.0.0
npm ERR! Found: react@18.3.0-canary-d803f519e-20231020
npm ERR! node_modules/react
npm ERR!   react@"18.3.0-canary-d803f519e-20231020" from @artem-package/frontend@1.0.0
npm ERR!   packages/frontend
npm ERR!     @artem-package/frontend@1.0.0
npm ERR!     node_modules/@artem-packagefrontend
npm ERR!       workspace packages/frontend from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.0.0" from @tanstack/react-query@5.0.0
npm ERR! node_modules/@tanstack/react-query
npm ERR!   @tanstack/react-query@"5.0.0" from @artem-package/frontend@1.0.0
npm ERR!   packages/frontend
npm ERR!     @artem-package/frontend@1.0.0
npm ERR!     node_modules/@artem-package/frontend
npm ERR!       workspace packages/frontend from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Your minimal, reproducible example

It's npm problem, you need to copy package.json from steps to reproduce

### Steps to reproduce

1. npm init
2. Add react-query, react and react-dom

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@tanstack/react-query": "5.0.0",
    "react": "18.3.0-canary-d803f519e-20231020",
    "react-dom": "18.3.0-canary-d803f519e-20231020"
  },
  "author": "",
  "license": "ISC"
}
```
3. npm install

### Expected behavior

As a user, I expected, that npm i will work.

### How often does this bug happen?

Every time

### Platform

OS — Sonoma
Node — v20.3.1
npm — 9.6.7 with workspaces

### Tanstack Query adapter

None

### TanStack Query version

v5.0.0

**Comment by TkDodo** [comment]
I think you need to use `--force` then? Not 100% sure how peer dependencies work with canaries, but this is what we have set up:

https://github.com/TanStack/query/blob/main/packages/react-query/package.json#L64-L68

It seems that `18.3.0-canary-d803f519e-20231020` does not fit into the `^18.0.0` range. Or do you know of a way to make the range be inclusive of canaries ?

**Comment by artem-malko** [comment]
Thx @TkDodo 

Yeap, `--force` fixes that error, but there will be more other problems (with react-redux or other libs). So, it is not. a solution(

So, I have to switch to yarn or pnpm( Should we close this issue?

**Comment by TkDodo** [comment]
I'm really not sure. does this work with other libraries that have peerDependencies set up to be `^18.0.0` ?

**Comment by artem-malko** [comment]
Yeap, the same problem with react-redux.

**Comment by artem-malko** [comment]
But you're right, it is a problem with npm itself and its semver resolve policy

**Comment by TkDodo** [comment]
Yeah, not a lot we can do I'm afraid.
