### ISSUE TITLE
The devtools logo does not display the default value of the `buttonPosition` prop correctly.

### ISSUE THREAD

**Issue by phatpcdev** [TanStack/query#6242]
### Describe the bug

The bug occurs when I show devtools with default options. Specifically, the default value of `buttonPosition` is `bottom-left` (docs: https://tanstack.com/query/v5/docs/react/devtools), but actually I see the logo at bottom-right corner on my screen.

Maybe this problem is from line 91 in file https://github.com/TanStack/query/blob/main/packages/query-devtools/src/Devtools.tsx

I hope my report will help the TanStack team fix the bug faster. Thanks.

### Your minimal, reproducible example

https://codesandbox.io/s/green-field-l6q7pw

### Steps to reproduce

https://codesandbox.io/s/green-field-l6q7pw

### Expected behavior

Expected: The logo will display as the documentation describes

### How often does this bug happen?

None

### Platform

- Version: Query devtools v5.1.0

### Tanstack Query adapter

None

### TanStack Query version

v5.0.5

**Comment by ardeora** [comment]
Thanks for creating this issue! Yeah the docs are erroneous. The default position of the new devtools button should be on the `bottom-right`. I'll fix the documentation for all the adapters. You can still change the button position by by passing the `buttonPosition` prop to the devtools component if you'd like.

**Comment by phatpcdev** [comment]
Thank you!
