### ISSUE TITLE
Solid query 5: `enabled` option is not being tracked in SSR

### ISSUE THREAD

**Issue by shiro** [TanStack/query#6256]
### Describe the bug

The `enabled` flag is not working with solid query and Solid Start's SSR.

See my repro for actual example: [github repro](https://github.com/shiro/repro-SS-solid-query-enabled-flag)

### Your minimal, reproducible example

https://github.com/shiro/repro-SS-solid-query-enabled-flag

### Steps to reproduce

- use solid start with SSR and latest solid query
- use solid start's stream or async SSR modes
- add a simple query, connect the `enabled` option to a signal that's initially set to `false`
- toggle the signal on the client side
- query does not run

### Expected behavior

Query should run once `enabled` is set to true.

### How often does this bug happen?

Every time

### Platform

- OS: linux
- browser: chromium, FF

### Tanstack Query adapter

solid-query

### TanStack Query version

5.2.1

### TypeScript version

4.9.5

**Comment by ardeora** [comment]
Thank you for creating this issue. Sadly this seems like a solid-start bug. I have already filed an issue on the solid-start repo to start the conversation there

Please see:
https://github.com/solidjs/solid-start/issues/1099

**Comment by ardeora** [comment]
@shiro https://stackblitz.com/github/ardeora/solid-start-query-working-old Here is an older version of Solid Start that should work as expected for you. Seems like the issue is in newer versions of solid-start

**Comment by shiro** [comment]
Thank you so much, that was quick!

Will close this for now since its not a query issue.

**Comment by ardeora** [comment]
@shiro Ryan was very kind to fix this issue in solid-js. If you use `v1.8.5` then it works great!

Here's your repro with the latest versions
https://stackblitz.com/edit/github-pejqcl?file=package.json
