### ISSUE TITLE
Toggle Enabled option always refetch query

### ISSUE THREAD

**Issue by artem-malko** [TanStack/query#6277]
### Describe the bug

I tried to find the same problem in the issues, but it wasn't successful( 

Let's say, I have a QueryClient with the next defaults:
```ts
defaultOptions: {
  gcTime: 1000 * 60 * 60,
  staleTime: 1000 * 60 * 60
}
```

And we have two components, which share the same query (the same queryKey), but one of useQuery has enabled flag. So, if enabled is `false`, there are no any additional requests (obviously). But if we `enabled` became true — we have one more request, even we have big stale and gcTime, even there is another query mounted with the same queryKey.

### Your minimal, reproducible example

https://codesandbox.io/s/enabled-react-query-possible-bug-4csk32

### Steps to reproduce

1. Go to codesandbox demo
2. Wait till `<ChildWithUsualQuery />` will render the data from request
3. Enable the query from `<ChildWithDisabledEnabledQuery />` via a button click.

### Expected behavior

As a user, I expected, that there won't be any additional requests, cause we have data in cache, we have active (mounted) query, we have big staleTime.

### How often does this bug happen?

Every time

### Platform

Any OS, Browser

### Tanstack Query adapter

react-query

### TanStack Query version

v5.4.3

**Comment by TkDodo** [comment]
Your default options aren't applied because the way you pass them to `QueryClient` is wrong. You want:

```
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      gcTime: 1000 * 60 * 60,
      staleTime: 1000 * 60 * 60
    }
  }
});
```

`staleTime` is respected when you enable a query. The check is here:

https://github.com/TanStack/query/blob/403699afd10c8e952b213ec1776e8e729e916e15/packages/query-core/src/queryObserver.ts#L734-L739

working reproduction: https://codesandbox.io/s/enabled-react-query-possible-bug-forked-vhk8p8

**Comment by artem-malko** [comment]
Oh! I'm useless without typescript)

So, there is a question: why do we have an additional request, even we have mounted active query? Why do we have the next code:

```ts
isStale(query, options) 
```

**Comment by TkDodo** [comment]
If a disabled observer becomes enabled, we treat it similar to a "mount" event, meaning stale data will be refetched in the background.

**Comment by artem-malko** [comment]
Ok, but what is the point?) What problems does this flow resolve?

**Comment by TkDodo** [comment]
I don't get that question, sorry. What's the point of refetching stale data at a strategic point in time where the lib determines that now is a good time to trigger a refetch, like when an observer mounts or when an observer switches from disabled to enabled? That's what react-query does 😅

**Comment by artem-malko** [comment]
Ok, I've update my example. Now, I use `refetchOnMount: false`.

So, One query is mounted and all data is fetched. Let's mount one more component with a query with the same key and queryFn. There won't be any additional request, even staleTime is 0.

```tsx
{enabled && <ChildWithDisabledEnabledQuery enabled={enabled} />}
```
And `enabled in query is true all the time`.


But, if we just toggle enabled flag (like in my demo), an additional request appears. Looks like these situations are the same for react-query. But the behaviour is different.

**Comment by TkDodo** [comment]
Going from enabled true -> false is a trigger to refetch stale queries that can't be customized.

**Comment by artem-malko** [comment]
Yeap, I understood that fact) But what is the point? 

If we have the query mounted, and we're going to mount the same — there is no additional request. What is the idea behind "Going from enabled true -> false is a trigger to refetch stale queries"? Or what kind of case is resolved with such behaviour.

**Comment by artem-malko** [comment]
@TkDodo 

> There should be if data is considered stale ...

https://codesandbox.io/s/react-query-with-many-similar-quireies-fnj939?file=/src/App.js

As you can see, there are no any additional requests, but data is stale)

Your example is perfect, really. But check mine, pls) Looks like your logic is broken. Or I've done something wrong with a configuration(

**Comment by TkDodo** [comment]
that's because you have set `refetchOnMount: false`, which opts out of those background refetches when a new observer mounts ...

There is no flag to customize the behaviour for the disabled -> enabled transition, but it always respects staleTime. My suggestion is to leave the flags alone and only customize staleTime.

**Comment by artem-malko** [comment]
Yeap, your suggestion is ok, thx. But it's not perfect) 

I don't know, may it is a good idea to add some something like recipes to the documentation? I mean the recipes, that can describe the result of react-query option combinations?
