### ISSUE TITLE
Unexpected behavior of the combine function

### ISSUE THREAD

**Issue by nabokovYaroslav** [TanStack/query#6281]
### Describe the bug

Hello. The combine function doesn't seem to work correctly. When I change the states of the pages, the results passed to the combine function have changed, but seems like the state of the pages remains from the previous rendering.
Maybe I'm doing something wrong, let me know.
If this is how it should be, perhaps you can tell me how to get the page from the results in the combine function?

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/long-fog-z6kf46

### Steps to reproduce

1. Click on the button "Remove first page".
2. In the console, you can see that the state of the pages does not match the results in the first render.

### Expected behavior

The page state must be synchronous with the combine function

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/query/assets/82458819/6e9e71d1-4839-4871-b0b9-0d78c21da393

Watch at 0.25 speed. You may notice that the data is tinted red when the data does not match the page

### Platform

Windows 10 Pro 22H2 x64
Google Chrome 118.0.5993.118

### Tanstack Query adapter

react-query

### TanStack Query version

5.0.5

**Comment by TkDodo** [comment]
if you add a log statement to `combine`, you can see that it will only be called with 9 pages after you've removed the first page. That seems correct to me.

**Comment by nabokovYaroslav** [comment]
I updated the code, I still see that the number of pages does not match the number of elements in the results

https://github.com/TanStack/query/assets/82458819/771ac2b1-18db-4956-b38b-a2d70c41fe0d

**Comment by TkDodo** [comment]
you're closing over the `pages` prop in the `combine` function, so it "sees" the pages from when it was created.

if you log `pages` in the render function and `results` inside `combine`, you'll see they are in sync:

https://codesandbox.io/p/sandbox/unexpected-results-of-combine-function-forked-76yqvp?file=%2Fsrc%2Fapi%2FusePosts.ts%3A23%2C31

I really don't know what you're trying to achieve with this. `combine` is supposed to be a pure function that combines the results. Why does any of this matter here?
