### ISSUE TITLE
Unexpected error boundary reset behaviour

### ISSUE THREAD

**Issue by MarkSFrancis** [TanStack/query#6282]
### Describe the bug

Error boundary reset appears to reset _successful_ queries, rather than failing ones. According to [the docs](https://tanstack.com/query/v4/docs/react/guides/suspense#resetting-error-boundaries), the reset should reset only queries that failed, but it seems to reset only queries that succeeded.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/dry-brook-jxn48p

### Steps to reproduce

1. The sandbox keeps track of the number of times a `queryFn` is called
2. When the sandbox loads, it will render a component that runs a "successful" query and increment the `fetchSuccessCount`
3. When you click the "Trigger error boundary", it will render a component that runs an "error" query and increment the `fetchErrorCount`
4. When you reset the error boundary, it will re-render the component that runs a "successful" query
5. You can run through this process repeatedly to see how the counts increment as the error boundary is reset, in order to see how the queries are running

### Expected behavior

Each time the error boundary is reset, it should re-run only the failed query. 
- My understanding from [the docs](https://tanstack.com/query/v4/docs/react/guides/suspense#resetting-error-boundaries) is that it should **only** reset query errors, which wouldn't include the successful query. So I'd expect the count for the successful query to remain at 1.
- Similarly, I'd expect the error query to be re-ran every time I click the "Trigger error boundary" button, as I would've expected that it was reset and would therefore try to run its `queryFn` again.

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Google Chrome
- Version: 118.0.5993.117 (Official Build) (arm64) 

### Tanstack Query adapter

None

### TanStack Query version

v5.0.0

### Additional context

I am new to error boundaries and suspense, so please be patient with me if I've missed some key way of using boundaries! For example, I'm a little confused in the docs about whether the reset is meant to reset _all_ query state, or only the queries that error. So I apologise in advance if I struggle to understand some things about how error boundaries are supposed to work

**Comment by TkDodo** [comment]
you haven't set a `staleTime` on your query, so you see a normal background refetch because a new observer mounts. The error boundary unmounts your component tree, and when you click try again, it re-mounts. I see nothing out of the ordinary here. If you want fewer fetches, set a higher staleTime.
