### ISSUE TITLE
`TimeoutOverflowWarning` in `Query.scheduleGc`

### ISSUE THREAD

**Issue by luixo** [TanStack/query#6287]
### Describe the bug

Hello,
In my frontend tests I found a bunch of SSR warnings that looked like this: `(node:102) TimeoutOverflowWarning: 2635200000 does not fit into a 32-bit signed integer.`.
After adding `--trace-warnings` to a process, I found that [this](https://github.com/TanStack/query/blob/main/packages/query-core/src/removable.ts#L15-L17) function runs an overflowing timer.
I have no clue why that number got so high, unfortunately, but [validating function](https://github.com/TanStack/query/blob/main/packages/query-core/src/utils.ts#L80-L82) should probably limit `gcTime` to a maximum of [2_147_483_647](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#maximum_delay_value).

### Your minimal, reproducible example

-

### Steps to reproduce

Can't give a minimal example, but hop error stack might help:
```ts
(node:102) TimeoutOverflowWarning: 2635200000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
    at new Timeout (node:internal/timers:173:17)
    at setTimeout (node:timers:165:19)
    at Query.scheduleGc (file:///work/node_modules/@tanstack/query-core/build/lib/removable.mjs:12:24)
    at new Query (file:///work/node_modules/@tanstack/query-core/build/lib/query.mjs:21:10)
    at QueryCache.build (file:///work/node_modules/@tanstack/query-core/build/lib/queryCache.mjs:23:15)
    at QueryObserver.updateQuery (file:///work/node_modules/@tanstack/query-core/build/lib/queryObserver.mjs:453:47)
    at QueryObserver.setOptions (file:///work/node_modules/@tanstack/query-core/build/lib/queryObserver.mjs:82:10)
    at new QueryObserver (file:///work/node_modules/@tanstack/query-core/build/lib/queryObserver.mjs:15:10)
    at file:///work/node_modules/@tanstack/react-query/build/lib/useBaseQuery.mjs:36:43
    at useReducer (/work/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:259:36)
```

### Expected behavior

Warning not being emitted.

### How often does this bug happen?

Every time

### Platform

- OS: macOS 14.0
- Environment: node v20.2.0
- Version: v4.32.0

### Tanstack Query adapter

react-query

### TanStack Query version

v4.32.0

**Comment by TkDodo** [comment]
the `gcTime` we set is either 5 minutes in the browser, or `Infinity` on the server:

https://github.com/TanStack/query/blob/1d3ee672d2a1536e3463243813c91902aa97d973/packages/query-core/src/removable.ts#L22-L25

If it's set to `Infinity`, the timer isn't started because `Infinity` isn't a valid timeout:

https://github.com/TanStack/query/blob/1d3ee672d2a1536e3463243813c91902aa97d973/packages/query-core/src/removable.ts#L14

https://github.com/TanStack/query/blob/1dc5758518594c82f5399deeb30e393b27d0a91a/packages/query-core/src/utils.ts#L81

so it seems like you're setting that high number yourself?

potentially related:
- https://github.com/TanStack/query/issues/1646

**Comment by luixo** [comment]
I looked up the number - and found that I pass it as `cacheTime` to a query I expected to be very stable - exactly as in an [issue you mentioned](https://github.com/TanStack/query/issues/1646).

Thanks for finding that!

Is there a recommended way to keep stable query results intact for long (longer than 2**31 - 1ms) periods of time?

**Comment by TkDodo** [comment]
You can persist them to an external storage. Not sure what the goal is of having unused data be stored in memory for more than 20 something days

**Comment by luixo** [comment]
> Not sure what the goal is of having unused data be stored in memory for more than 20 something days

That's used query, I want it to not get invalidated and reloaded every now and then.
Say, it's a heavy record (say, a record of currencies of timezones with associated data) that one usually load once. If I find that I lack some a key - it's time to refetch data from the server as probably a new key was added.

It seems like there's no way to let library know I don't want data to be refetched for more than 2**31 - 1ms.

**Comment by TkDodo** [comment]
you want to set `staleTime`

**Comment by lazylace37** [comment]
I would recommend we document this somewhere.
I came here after hours of debugging trying to implement the `persistQueryClient` :)
Having a `gcTime` of 30 days is not that crazy for a mobile app for example.

**Comment by TkDodo** [comment]
sure, please PR to the docs
