### ISSUE TITLE
Value of `meta` is `undefined` in queries returned by `useQueries`

### ISSUE THREAD

**Issue by Josh865** [TanStack/query#6289]
### Describe the bug

When a value is assigned to the `meta` field on the queries passed to the `useQueries` hook, that value is `undefined` when iterating over the queries.

```jsx
const pokemonList = ['ditto', 'pikachu', 'charizard'];

const queries = useQueries({
  queries: pokemonList.map((pokemon) => ({
    queryKey: ['pokemon', pokemon],
    queryFn: () => axios(`https://pokeapi.co/api/v2/pokemon/${pokemon}`),
    meta: { pokemon },
    staleTime: Infinity,
  })),
});

return (
  <ul>
    {queries.map((query) => {
      // meta is undefined here
      console.log(query.meta);

      return <li>{query.data.data.name}</li>;
    })}
  </ul>
);
```

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-2hz1pw?file=src%2FApp.jsx

### Steps to reproduce

1. Open the example at https://stackblitz.com/edit/vitejs-vite-2hz1pw?file=src%2FApp.jsx.
2. Open the browser console from within the preview.
3. Note that the logged value of `query.meta` is `undefined`.

### Expected behavior

I expected the value of the `meta` field to be defined and accessible inside my component on each query returned by the `useQueries` hook.

### How often does this bug happen?

Every time

### Platform

- OS: macOS (v14.1)
- Browsers: Edge (v118), Safari (v17.1)

### Tanstack Query adapter

react-query

### TanStack Query version

4.36.1

**Comment by TkDodo** [comment]
`meta` is not part of the returned object from useQuery, just like other fields that you pass to the query are not returned. Like, if you were to access `result.queryKey`, it would also be undefined. Have a look at the [API docs](https://tanstack.com/query/v5/docs/react/reference/useQuery) to see what gets returned, and please consider using TypeScript.
