### ISSUE TITLE
[vue-query]: queryOptions unassignable type

### ISSUE THREAD

**Issue by NoeReverse** [TanStack/query#6299]
### Describe the bug

I tried using `queryOptions` as the [documentation](https://tanstack.com/query/latest/docs/vue/typescript#typing-query-options) says, to use the same parameters in the `useQuery` and the `queryClient.fetchQuery`. When I use the `queryOptions` in the `useQuery`, everything looks fine, but when I try to use it in the `fetchQuery`, an error "_Argument of type <...> is not assignable to parameter of type <...>_" occurs.

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ4A0KG2ueAwgDbDoB2MRAjjvgPJgzAS2pwC+cAGZQIIOAHIAAjACGPWQGMA1gHoAbjgC0zMuICwAKEODktBZ25wQeUvgBitABQBKRIbhwo6GMii04AAoiIMAYAHReqBCUauiO4oIQEOLOhnyGxqbmXP4A5iLIYOwWPC5uBh5ePn5wOmwcOaiOCO4etSx4ANLoeABccADa4jDoqDDiALoErR51eA791rbztK18qQbpRgZoWB2O+RCFxY0uG4YK3GPtZFQ09HAAvMR7t9R0MC6GMgDuMsDwOZ3D5hQTeBQAC2WBwKRQaVzOQA

### Steps to reproduce

1. Go to reproducible example link
2. See the error in the last line

### Expected behavior

I was expecting to be able to use shareable parameters in both the useQuery composable and the fetchQuery function, but I can't because of a TypeScript error

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/30126262/c60a8f26-ea39-4fe1-abc1-1cdfdcd15bb0)

### Platform

Windows 11, Node v21.1.0, Nuxt 3

### Tanstack Query adapter

vue-query

### TanStack Query version

v5.4.3

### TypeScript version

v5.2.2

**Comment by TkDodo** [comment]
same code works in the react adapter so I'd say it's a vue-query bug:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ4A0KG2ueAwgDbDoB2MRAjjvgPJgzAS2pwC+cAGZQIIOAHIAAjACGPWQGMA1gHoo6GQpgBaZmXEBYAFDHByWlq604IPKXwAxWgAoAlImNw46mMijWABREQYAwAOnVUCEoAN3RncUEICHFXYz5jU3NLbjgAcxFkMHZOblQ3DyMvHz9rPTYOK3KETy84erwAaXQ8AC44AG1xGHRUGHEAXQJWrw6nftt7PCdWvjSjDJMjNCwWPGcCiCKSprd14wUy+A6qGno4AF5iXbJbuhg3YxkAdxlga72b3oYUE6BgCgAFksDoVio0ymcgA

**Comment by DamianOsipiuk** [comment]
Fixed in https://github.com/TanStack/query/releases/tag/v5.7.3
