### ISSUE TITLE
`suspense` still available in `defaultOptions`

### ISSUE THREAD

**Issue by lucasvienna** [TanStack/query#6300]
### Describe the bug

I can currently set `suspense` in the client defaults:
```ts
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      suspense: true,
    },
  },
});
```

This breaks the regular `useQuery` hooks when enabling/disabling them.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/laughing-scott-h2q8kd

### Steps to reproduce

1. Click on "Enable"
2. Watch the entire thing crash because no `Suspense` exists.

### Expected behavior

I shouldn't be able to set `suspense: true` in the defaults, since that property cannot be set any more in regular queries (except for the `useBaseQuery`, but that's implementation details of internals).

### How often does this bug happen?

Every time

### Platform

Any

### Tanstack Query adapter

react-query

### TanStack Query version

v5.4.3

### TypeScript version

v5.2.2

### Additional context

We used `suspense` by default, and when queries that shouldn't suspend in v5 kept suspending, it threw us in for a loop because TS didn't warn about this default being there. Lack of proper attention on our part, but still.

**Comment by TkDodo** [comment]
we can remove it from type level, but I don't think we can remove it from implementation as we'er still using that flag internally. If you pass `suspense: true` to `useQuery`, it (unfortunately) still works. But TS is the source of truth so we should remove it from there at least.

**Comment by lucasvienna** [comment]
Just the types would prevent others from making the same mistake we did, thank you!
