### ISSUE TITLE
Docs - Searching the docs on v5 brings you to v4 docs

### ISSUE THREAD

**Issue by olivierbeaulieu** [TanStack/query#6325]
### Describe the bug

Hi! I wanted to report an issue with the docs website - not the library itself. Using the Algolia search while you are browsing the v5 docs will bring you to the v4 docs.

It's not instantly obvious that you're looking at the wrong thing either since the only clear thing that is different is the logo version in the top left. Seems like the docsearch indexes need to be updated?

### Your minimal, reproducible example

See steps to reproduce below

### Steps to reproduce

1. Go to https://tanstack.com/query/latest/docs/react/overview
2. Hit cmd+k, type "useQuery" and select the first result
3. You are brought to https://tanstack.com/query/v4/docs/react/reference/useQuery (v4)

### Expected behavior

You are brought to the v5 useQuery docs (or of whatever version you are currently looking at, ideally? Browsing v3 seems to also bring you to v4)

### How often does this bug happen?

Every time

### Platform

All!

### Tanstack Query adapter

None

### TanStack Query version

v5

**Comment by TkDodo** [comment]
we're aware and working on it. It's an upstream issue with Algolia DocSearch

**Comment by TkDodo** [comment]
it's fixed 🎉
