### ISSUE TITLE
Errors raised inside onError cause infinite loading

### ISSUE THREAD

**Issue by andresespinosapc** [TanStack/query#6332]
### Describe the bug

If there's an error raised inside the onError function, the state of the query will be stuck on `isLoading`.

I think it should be considered as any other query error so the user doesn't see an infinite loading screen.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/admiring-fog-9q7y43

### Steps to reproduce

1. Add an onError function to any query
2. Throw an error inside the error function
3. Print the `isLoading` and `isError` variables

### Expected behavior

I expect `isLoading` to be false and `isError` to be true, but instead `isLoading` is true and `isError` is false

### How often does this bug happen?

Every time

### Platform

- OS: macOS 14.0
- Browser: Arc 1.15.1

### Tanstack Query adapter

react-query

### TanStack Query version

v4.7.1

**Comment by TkDodo** [comment]
the callbacks on `useQuery` are deprecated and have been removed in v5, so we're not going to look into this, sorry.

- https://github.com/TanStack/query/discussions/5279
