### ISSUE TITLE
Data can be undefined even if placeholderData is used

### ISSUE THREAD

**Issue by mehdiSlam** [TanStack/query#6342]
### Describe the bug

When i'm using `placeholderData` in a `useQuery`, the type of `data` returned by the hook still can be `undefined`. But when i log `data` value , the value is never `undefined`.

When i'm using the props `initialData` the data type returned by the hook is not `undefined`. 

Shouldn't we have the same behavior with the `placeholderData` ?

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ5wC+cAZlBCHAEQACMAhgHaoMDGA1gPRTr2swBaAI458VANwBYAFAyYeMOjgARegwAqCpQF44LKMEYBzANoBdGTNYRm8MABs+6ABYR7AE1wAuVRq1xdcylZaWtbRDh3NXoiAJQMbFw8AAoEGTgMuBEkgGl0PC84EypfeiozABp0zOz8ADFGQuSASgCAPjgABXIQYAwAOh5UNwA3dGTikfp7AEYqCuop+wAmcuaq6Uy4BydXD1xSwp3WFzdPKGrCZuCrG2H7dH77CCNkqIZmoA

### Steps to reproduce

- use the hook useQuery with the props `placeholderData`
- in typescript the value data returned by the useQuery can be `MyType | undefined`

### Expected behavior

The hook useQuery should not return a type data `undefined` if the props `placeholderData` is used  

### How often does this bug happen?

None

### Screenshots or Videos

<img width="406" alt="Capture d’écran 2023-11-09 à 12 05 12" src="https://github.com/TanStack/query/assets/61145145/cddce49e-b234-444d-a9b8-ab27abe01f6e">

### Platform

- macos
- google chrome

### Tanstack Query adapter

None

### TanStack Query version

5.0.5

### TypeScript version

4.9.5

**Comment by TkDodo** [comment]
> Shouldn't we have the same behavior with the placeholderData ?

no, because `data` will go back to `undefined` if the query errors.
