### ISSUE TITLE
`refetchOnWindowFocus` is not working (v5)

### ISSUE THREAD

**Issue by frederikhors** [TanStack/query#6351]
### Describe the bug

I just found out that `refetchOnWindowFocus` is not working.

I have this setup:

```ts
export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      gcTime: 1000 * 30, // 30 seconds
      persister: //...
    },
  },
});
```

and even if the below works:

```svelte
<svelte:window on:visibilitychange={() => console.log('visibilitychange changed!')} />
```

tanstack/query does not reload queries when `visibilitychange`s.

Can you confirm?

### Your minimal, reproducible example

https://stackblitz.com/edit/sveltejs-kit-template-default-6ntbzr?file=src%2Froutes%2F%2Bpage.svelte,src%2Fapp.html

### How often does this bug happen?

Every time

### Platform

Win 10, Chrome 119.0.6045.124.

### Tanstack Query adapter

svelte-query

### TanStack Query version

5.4.3

### TypeScript version

5

### Additional context

```json
"@tanstack/query-persist-client-core": "5.4.3",
"@tanstack/svelte-query": "5.4.3",
````

**Comment by frederikhors** [comment]
I'm creating a reproduction...

**Comment by frederikhors** [comment]
I created a reproduction.

**Comment by TkDodo** [comment]
I'm not really sure how svelte works, but somewhere, we need to call `queryClient.mount()` to subscribe to the window events. In React and solid, that's what the `QueryClientProvider` does:

https://github.com/TanStack/query/blob/1d3ee672d2a1536e3463243813c91902aa97d973/packages/react-query/src/QueryClientProvider.tsx#L33-L38

What's the equivalent for svelte here? @lachlancollins might know this :)

**Comment by lachlancollins** [comment]
@TkDodo the equivalent mount/unmount logic should be this:

https://github.com/TanStack/query/blob/73e339624b1f5aa797dffe0138806fb400ae1765/packages/svelte-query/src/QueryClientProvider.svelte#L8-L16

**Comment by lachlancollins** [comment]
@frederikhors Dominik was correct, you need to add the QueryClientProvider component somewhere in your app. The most common place to put this is `src/routes/+layout.svelte`:

```
<script lang="ts">
  import { QueryClient, QueryClientProvider } from '@tanstack/svelte-query'

  const queryClient = new QueryClient()
</script>

<QueryClientProvider client={queryClient}>
  <slot />
</QueryClientProvider>
```

Then you would remove this from `+page.svelte`:

```
const client = new QueryClient();

setQueryClientContext(client);
```

If you needed the client from context you could call `const client = useQueryClient()`

You can see the docs here: https://tanstack.com/query/latest/docs/svelte/overview

**Comment by frederikhors** [comment]
It works! Thanks!
