### ISSUE TITLE
Incorrect types for focusManager.setEventListener

### ISSUE THREAD

**Issue by BreakBB** [TanStack/query#6382]
### Describe the bug

The method `focusManager.setEventListener` accepts a [SetupFn](https://github.com/TanStack/query/blob/dc8f6395f8737cf2a5c9e75e4e5830fcb3ac8951/packages/query-core/src/focusManager.ts#L4) as parameter. And a `setupFn` is a function with a parameter `setFocused: (focused?: boolean) => void`.

[The docs](https://tanstack.com/query/v5/docs/react/guides/window-focus-refetching#custom-window-focus-event) provide the following example:

```
focusManager.setEventListener((handleFocus) => {
  // Listen to visibilitychange
  if (typeof window !== 'undefined' && window.addEventListener) {
    window.addEventListener('visibilitychange', handleFocus, false)
    return () => {
      // Be sure to unsubscribe if a new handler is set
      window.removeEventListener('visibilitychange', handleFocus)
    }
  }
})
```

While this code works (!), it is not valid in TypeScript, because `handleFocus` is actually `setFocused: (focused?: boolean) => void` which is not valid as [event listener callback function](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener?retiredLocale=de#the_event_listener_callback).

Note: This is also an issue, when not explicitly typing `handleFocus` (as in the docs example).

### Your minimal, reproducible example

[here](https://codesandbox.io/p/sandbox/crazy-robinson-rjpxkc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clozvp2bf000a2e6ampbz2lt9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clozvp2bf00032e6awe8up4bg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clozvp2bf00072e6afhmhdweh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clozvp2bf00092e6av4ovlerw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60.857614437985816%252C39.142385562014184%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clozvp2bf00032e6awe8up4bg%2522%253A%257B%2522id%2522%253A%2522clozvp2bf00032e6awe8up4bg%2522%252C%2522activeTabId%2522%253A%2522clozvpgbf007a2e6al1vqx759%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clozvp2bf00022e6apdnpnxva%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522id%2522%253A%2522clozvpgbf007a2e6al1vqx759%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clozvpyes00c32e6a8sj0but2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.tsx%2522%252C%2522id%2522%253A%2522clozvq5b400hx2e6ar129lvbz%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clozvp2bf00092e6av4ovlerw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clozvp2bf00082e6ax921yl1x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clozvp2bf00092e6av4ovlerw%2522%252C%2522activeTabId%2522%253A%2522clozvp2bf00082e6ax921yl1x%2522%257D%252C%2522clozvp2bf00072e6afhmhdweh%2522%253A%257B%2522id%2522%253A%2522clozvp2bf00072e6afhmhdweh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clozvp2bf00042e6a3cocjqqy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clozvp2bf00052e6apai9d84y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clozvp2bf00062e6aunnh8o7l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522preview%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clozvp2bf00042e6a3cocjqqy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Check the call of `window.addEventListener("visibilitychange", setFocused, false);` towards TypeScript errors.

### Expected behavior

The given example should be valid TypeScript.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="709" alt="Screenshot 2023-11-15 at 16 07 28" src="https://github.com/TanStack/query/assets/33514570/9608aa2d-90cd-4132-8c27-7df51db68066">

### Platform

- OS: macOS
- Browser: Firefox, Chrome

### Tanstack Query adapter

None

### TanStack Query version

5.8.4

### TypeScript version

6.9.1

**Comment by TkDodo** [comment]
seems just like a docs issue? The actual code we use is:

https://github.com/TanStack/query/blob/1d3ee672d2a1536e3463243813c91902aa97d973/packages/query-core/src/focusManager.ts#L16-L30

so this indirection is all that's missing:

```
const listener = () => setFocused()
```

want to PR a docs change?

**Comment by BreakBB** [comment]
> want to PR a docs change?

Sure!
