### ISSUE TITLE
useQueries `queries` property does not allow for setting network mode

### ISSUE THREAD

**Issue by jgutman** [TanStack/query#6384]
### Describe the bug

In React Query 5.8.0, using the following:

```
useQueries({
queries: ids.map(id => ({
      queryKey: ...,
      queryFn: ....,
      networkMode: 'always'
})
})
```

fails. I get a typescript error that `Type 'string' is not assignable to type 'NetworkMode | undefined'.` 

I am able to set the network mode option this way in `useQuery` and `useInfiniteQuery`.

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwK4GcCmBFJaoE8A0cqm2UwaKAvnAGZQQhwDkAAjAIYB2KHAxgNYB6KGna8YAWgCOpXEwDcAKEW8I3eMSgo4AXjgBtBMAAmALjgBGSoSNm4AJmuIT5gMyUAukpVqetNDC8ABYAquhQAEK4AJLGunAAFC5wnEggAEY4AJS6AHxE4SgAdDTAnMYJmnkFOEUmujp6Jlnequo1UFg45Np6xF1kFAkIinBjcDLdFOaaxSDsYAmV4Tk6+SPj4yIwSFCciKOb45N4ANJouOb6TJpMhJp1xh74h0cTsgBinOYJq-k0AWCYRwUViy1qzRebzGnACAHdoPwALIQYxocxMdgAGzh7FwKCYr3GlCJlCyLzJ8iAA

### Steps to reproduce

See description and typescript sandbox.

### Expected behavior

I expect that I can set the networkMode option in `useQueries` in the `queries` property, to any of the following strings: `'online' | 'always' | 'offlineFirst'`.

### How often does this bug happen?

None

### Platform

OS 13.6

### Tanstack Query adapter

react-query

### TanStack Query version

v5.8.0

**Comment by TkDodo** [comment]
I think this is because typescript doesn't infer literals in objects inside arrays. You'd need `networkMode: 'always' as const`

**Comment by TkDodo** [comment]
the best way to get type safety is to wrap the option itself in `queryOptions`:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwI4FcCmUCeB5MNgQB2AzgDRwrFoCK6UwaxAvnAGZQQhwDkAAjAEMSggMYBrAPRQ0AkTAC0qDJm4AoVSKLF4lDMTgBeOAG0EwACYAuOAEYm5M1bgAme4gvWAzEwC6AbnVNYTY0GBEACwBVKigAIUwASXNDOAAKDzhCFBAAIwwASkMAPgoY4gA6VmBCc1TdKGLSjHKLQwMjC3yAjS0dGNoMBn0jXQH6RlSEVTgZuCVx4mt6ipABMFS6mMKDEqnZ2ekYFChCObocPAISSen92fnMAGk0TGtjbnrucnqW8x9SW53M7KABihGsqW2JVYoQi0Qw8SSm2anQBQJmhFCAHdoGIALIQcxoazcAQAGyxAkwxDUQKY+UBcHpAPpfiAA
