### ISSUE TITLE
[useInfiniteQuery] succeeds in fetching the data, but does not update the data.

### ISSUE THREAD

**Issue by galaxykhh** [TanStack/query#6387]
### model
```typescript
class Post {
    public readonly id: number;
    public readonly images: string[];
    public readonly content: string;

    constructor(data) {
        ...
    }
}
```

### api
```typescript
class PostRepository {
    public async getListByPage(page: number): Promise<PageResponse<Post>> {
        try {
            const response = await this.client.get(`/v1/posts?page=${page}`);
    
            return PageRespons.parse<Post>(response.data); // it returns posts with page data likes hasNextPage, etc.
        } catch(e) {
            throw new Error();
        }
    }
}
```

### view
```typescript
const MyPostListScreen = () => {
    const { data, status } = useInfiniteQuery(
        queryKey: ['post', 'list'],
        queryFn: async ({ pageParam }) => {
            const data = await PostRepository.getListByPage(pageParam.page);

            console.log('FIRST CONTENT:', data.items[0].content); // log content of first post

            return data;
        },
        initialPageParam: {
            page: 1,
        },
        getNextPageParam: calculateNextPageParam, // this function will returns next page param
    );

    useEffect(() => {
        console.log('DATA UPDATED!!'); // log data updated
    }, [data]);

    if (status === 'pending') return <Loading />;
    if (status === 'error') return <Error />;

    return (
        <FlatList ... />
    );
};
```

### console

```
DATA UPDATED!!
FIRST CONTENT: I am first content
DATA UPDATED!!

// Modify the content to "I'm modified" on another route, then enter the MyPostListScreen again.

DATA UPDATE!! // previous posts rendered
FIRST CONTENT: I'm modified // we can check a new content, but no update data
```

Why isn't the data updated even though got the data well through the server API call?
When use the useQuery in the same way, the data is updated well.

### Your minimal, reproducible example

see in description

### Steps to reproduce

see in description

### Expected behavior

```
DATA UPDATED!!
FIRST CONTENT: I am first content
DATA UPDATED!!

// Modify the content to "I'm modified" on another route, then enter the MyPostListScreen again.

DATA UPDATED!!
FIRST CONTENT: I'm modified
DATA UPDATED!!
```

### How often does this bug happen?

None

### Platform

OS: iOS, Android
Browser: React Native

### Tanstack Query adapter

react-query

### TanStack Query version

5.8.4

**Comment by galaxykhh** [comment]
Sorry, I tried to runnable reproduction but failed to resolve module from Expo Snack..😓

I realized that's the case in certain situations.

### my hook
```typescript
export const useGetPostsByPage = (params: {
    postRepository: PostRepository;
    filter?: string; // optional filter
}) => {
    const { postRepository, filter } = params;

    return useInfiniteQuery<
        PagingResponse<Post>,
        ServerException,
        InfiniteData<Post, PaginateQuery>,
        QueryKey,
        GetPostListByPageParams
    >({
        queryKey: ['post', 'list', typeof filter === 'string' ? filter : 'all'],
        queryFn: ({ pageParam }) => postRepository.getListByPage(pageParam),
        initialPageParam: {
            size: 20,
            page: 1,
            filter,
        },
        getNextPageParam: calculateNextPageParam,
    });
};
```

When calling this hook from the view component, it will always be updated without filter.
but If allocate the filter, it was not updated properly.
Is there a problem with the code above?

**Comment by galaxykhh** [comment]
@TkDodo 

I implemented it  in expo, but worked properly.
So I was confused about why my project was having problems, but I knew why.
I was using fetchNextPage as a callback for FlatList's onEndReached, The initial data call and fetchNextPage were being called together because the list had few scrolling areas.

```typescript
<FlatList
    ...
    onEndReched={hasNextPage ? fetchNextPage : null}
/>
```

It was completely my mistake. I'll close this issue. Thanks!

**Comment by ersefuril** [comment]
> @TkDodo
> 
> I implemented it in expo, but worked properly. So I was confused about why my project was having problems, but I knew why. I was using fetchNextPage as a callback for FlatList's onEndReached, The initial data call and fetchNextPage were being called together because the list had few scrolling areas.
> 
> ```ts
> <FlatList
>     ...
>     onEndReched={hasNextPage ? fetchNextPage : null}
> />
> ```
> 
> The problem was solved by using the code as above. It was completely my mistake. I'll close this issue. Thanks!

We had the exact same issue : my guess is if your code is calling `fetchNextPage` on initialRender, it'll conflict with initial fetch performed by react-query and will results with stale data.

The documentation indicates clearly to not call `fetchNextPage` if there is no next page : 
> Keep in mind that imperative fetch calls, such as fetchNextPage, **may interfere with the default refetch behaviour, resulting in outdated data**. Make sure to call these functions only in response to user actions, or add conditions like hasNextPage && !isFetching.
https://tanstack.com/query/latest/docs/framework/react/reference/useInfiniteQuery
