### ISSUE TITLE
[solved] Uncaught TypeError: node.addEventListener is not a function

### ISSUE THREAD

**Issue by rntgspr** [TanStack/query#6391]
### Describe the bug

I am trying to use react-query@5.8.4 and react-query-devtools@5.8.4 in a chorme extension boilerplate. But for some reason styles are gone and also all actions from react-query-devtools.

I still working on it to have a more clear approach, but this is what I could understand for now:

React Query was doing well, just after adding react-query-devtools I got the following error in my page-script:
![image](https://github.com/TanStack/query/assets/457829/7f911114-70e5-4393-af36-09fd5ce1c670)

Digging a little on React part of react-query-devtools, figured that might not be react-query-devtools React embeded components itself. Still unsure, but debuging it starts breaking after this line:

```javascript
devtools.setButtonPosition(buttonPosition)
````

Rolling back a few versions, I could make at least styles back it using `react-query-devtools@5.1.0` and `react-query@5.0.5` as advised, open/close mechanism stills broken. Same behaviour downgrading all the way to 5.0.0 for both query and devtools.

I will try to keep this post updated in case that I can figure out something new, but it stills unclear for me for now on 5.8.4.

### Your minimal, reproducible example

https://github.com/rntgspr/chrome-extension-boilerplate
(this repo is a WIP, instabilities might happen)

### Steps to reproduce
use env vars like:
```
NODE_ENV=development
EXTENSION_NAME="Chrome Extension Boilerplate"
```

1. install project;
2. run: `npm install && npm run build`;
3. load unpacked extension from `./dist` directory (should work on any page, like github for example);
4. error happens when we open devtools;

### Expected behavior

opening devtools correctly with expected layout/design/functionalities.

### How often does this bug happen?

Every time

### Screenshots or Videos

additional screenshots:
error stack 1:
![image](https://github.com/TanStack/query/assets/457829/fdff9ba6-b851-480d-9998-2eb6508a565b)

error stack 2:
![image](https://github.com/TanStack/query/assets/457829/51b05cdf-6550-483f-a505-c080e8b39f55)
![image](https://github.com/TanStack/query/assets/457829/635a5fa0-8ead-48fc-b759-80de7c3a64b5)

error stack 3:
![image](https://github.com/TanStack/query/assets/457829/00a9ea0d-cdd6-422a-8898-f0911297614c)

from 5.0.0 to 5.1.0 (button and panel running at same time sounds broken?):
![Screenshot 2023-11-16 at 7 14 03 PM](https://github.com/TanStack/query/assets/457829/cd101951-ad4d-49e2-811d-d3cfd7b04b85)

from 5.4.2 and up (mostly of styles and all actions are totally broken at this point):
![image](https://github.com/TanStack/query/assets/457829/a72151e9-c0e1-4f0d-a54d-b28332a084cb)

### Platform

- Chrome Extensions, manifest 3.0;
- using chrome: Version 117.0.5938.149 (Official Build) (arm64);
- MacOSX Sonoma 14;

### Tanstack Query adapter

react-query

### TanStack Query version

versions used from 4.36.1 to 5.8.4

### TypeScript version

5.2.2

### Additional context

From my side, to build extension scripts, I am using ESBuild, nothing that fancy. (could make it work using 4.36.1, the old one).

**Comment by charlotte-bone** [comment]
It looks like if you remove `format: "esm"` from your esbuild context then it works as expected.

**Comment by rntgspr** [comment]
awesome! it worked perfectly now! ty so much! I would never consider to move back to iife without someone shining that light.

Btw, that's sad that a building format interacts so deep in the process that affects how a few modules works or not.
I would also love to keep it as `esm` to keep consistency among other projects. But I can live it as `iife` for now :) a better scenario than before.

**Comment by TkDodo** [comment]
can we consider this issue as closed then?

**Comment by charlotte-bone** [comment]
@TkDodo It seems quite specific to this build configuration and possibly the fact it's a chrome extension too. It's very difficult to debug too, so I think it's sensible to close this and see if it comes up again in a different environment.
