### ISSUE TITLE
UseInfiniteQuery not returning data when used within hooks

### ISSUE THREAD

**Issue by Bikash9609** [TanStack/query#6398]
### Describe the bug

```tsx

 const {
    data,
    isInitialLoading,
    isSuccess,
    isError,
    fetchNextPage,
    isFetchingNextPage,
    remove,
    hasNextPage,
  } = useInfiniteQuery(queryKey, (data) => fetchData(data), {
    keepPreviousData: true,
    ...infiniteQueryOptions,
    enabled: !!(queryKey && (infiniteQueryOptions.enabled ?? true)),
    getNextPageParam: (lastPage) => {
      if (lastPage?.length <= 0) return null;
      return page + 1;
    },
    refetchOnMount: true,
    retry: 2,
  });

```

I am using useInfiniteQuery inside custom hooks which can be imported an used inside any component, but when I use it inline along with other useQuery hooks, the function inside it gets called but still data is empty no results and isInitialLoading is true always.

For example usage in component 'n' 

```tsx

const {
  data,
  isLoading,
  success,
  error,
  isFetchingNextPage,
  loadMore,
  refetch,
  hasNextPage,
} = useInfiniteQueryWithPagination(
  [genericKeys.query1, +params.id],
  ({ pageParam = 1 }) => fetchData1(+params.id, pageParam),
  1);

const data2 = useQuery(
  [genericKeys.query2, params.id, user?.id],
  () => fetchData2(+params.id, user?.id),
  { enabled: !!params.id && success }
);

const data3 = useQuery(
  [genericKeys.query3, +params.id],
  () => fetchData3(+params.id),
  { enabled: !!+params.id && success1 && !isLoading1 }
);

```

Issue Description:

When using useInfiniteQueryWithPagination, I observed that the log appears in the network tab, but data2 and subsequently data3 are not being called. Additionally, it seems that data is successfully fetched only after a successful call to data2. Until then, the queryKey genericKeys.query1 doesn't appear in the React Query DevTools.

### Your minimal, reproducible example

https://codesandbox.io/s/competent-montalcini-5zj2d3?file=/src/App.tsx:414-444

### Steps to reproduce

1. Call useInfiniteQueryWithPagination.
2. Observe the network tab for successful log entries.
3. Check if data2 and data3 are being called.

### Expected behavior

I expect that useInfiniteQueryWithPagination should return non-null data if successfully fetched. Currently, it returns null or undefined even after a successful fetch. Additionally, I am encountering issues where data2 and data3 are not being called. The queryKey genericKeys.query1 is not logged in the React Query DevTools until a successful call to data2.

### How often does this bug happen?

Every time

### Platform

- OS: macOS Sonoma 14.0
- Browser: Chrome - Version 119.0.6045.123 (Official Build) (arm64)

### Tanstack Query adapter

None

### TanStack Query version

^4.29.5

### Additional context

    "@tanstack/react-query-devtools": "^5.8.4",

**Comment by charlotte-bone** [comment]
@Bikash9609 I've tried looking into this but the example doesn't seem to work. I tried switching to query version ^4.29.5 as in the description (it was using 5 in the sandbox) but it's still pretty broken.

**Comment by TkDodo** [comment]
agree, this reproduction is not good enough. It has the wrong version of RQ. After downgrading, it has no Provider. After adding a provider, it dies with `user is not defined`.

Please reopen once you have a proper reproduction
