### ISSUE TITLE
HydrationBoundary not working as expected

### ISSUE THREAD

**Issue by evonicgu** [TanStack/query#6399]
### Describe the bug

I created a test sample app, which just renders a random number from a rng api.

I want it to be server rendered, so, I've followed the "Advanced SSR guide", but the data which appears on the page is stale. It is not stale only after application startup, but every other time it shows the data that was fetched for the first time (the number changes only in layout, not in `HeaderComponent`).

How can this behaviour be fixed, so that newly fetched data shows during the SSR phase every time?

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/laughing-dawn-2pszlx?file=%2Fapp%2Fstyles%2Findex.scss%3A3%2C21

### Steps to reproduce

1. Just refresh the page a few times, the lower number is number from layout, while the upper is from the component.

### Expected behavior

The same number is expected both in `HeaderComponent` and in the layout.

### How often does this bug happen?

Every time

### Platform

Os: windows
Browser: vivaldi
Version: 6.4.3160.44

### Tanstack Query adapter

None

### TanStack Query version

5.8.4

### TypeScript version

5.2.2

**Comment by TkDodo** [comment]
no idea what's going on here, sorry. I'm getting random errors from next:

```
react-dom.development.js:24556 Uncaught Error: Unknown root exit status.
    at finishConcurrentRender (react-dom.development.js:24556:15)
    at performConcurrentWorkOnRoot (react-dom.development.js:24434:9)
    at workLoop (scheduler.development.js:261:34)
    at flushWork (scheduler.development.js:230:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:534:21)
```

My best guess is that you need a higher staleTime to avoid getting a refetch on the client, which would give you a different value.

**Comment by TkDodo** [comment]
also getting this:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:406:5)
    at ServerResponse.setHeader (node:_http_outgoing:652:11)
    at handleRequest (/workspaces/sandbox/node_modules/next/dist/server/lib/router-server.js:341:17)
    at async requestHandlerImpl (/workspaces/sandbox/node_modules/next/dist/server/lib/router-server.js:360:13)
    at async Server.requestListener (/workspaces/sandbox/node_modules/next/dist/server/lib/start-server.js:136:13) {
  code: 'ERR_HTTP_HEADERS_SENT'
```

tbh, it seems more like an upstream issue. I'm pretty sure the `HydrationBoundary` works as expected. Gonna loop in @Ephem here because maybe it has to do how we rehydrate when a query doesn't exist yet, and maybe our caches are somehow kept when the page reloads? But honestly, not sure in which direction to investigate this further as long as there are these errors coming from next ...

**Comment by TkDodo** [comment]
when I re-opened [my forked sandbox](https://codesandbox.io/p/devbox/polished-framework-st96gn), I got the correct logs everywhere:

```
layout data is [ 586 ]
prefetched data is [ 586 ]
data from client is [ 586 ]
data from useQuery is [ 586 ]
```

and the screen was this:
![Screenshot 2023-11-28 at 11 24 39](https://github.com/TanStack/query/assets/1021430/f9bfe590-51f2-4857-98fb-f3c971cf4b4a)

then, with a page reload, it turns into:

```
layout data is [ 139 ]
prefetched data is [ 139 ]
data from client is [ 586 ]
data from useQuery is [ 586 ]
```

so it seems like our client side cache persists over page refreshes, which is impossible 😅

**Comment by evonicgu** [comment]
> also getting this:
> 
> ```
> Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
>     at new NodeError (node:internal/errors:406:5)
>     at ServerResponse.setHeader (node:_http_outgoing:652:11)
>     at handleRequest (/workspaces/sandbox/node_modules/next/dist/server/lib/router-server.js:341:17)
>     at async requestHandlerImpl (/workspaces/sandbox/node_modules/next/dist/server/lib/router-server.js:360:13)
>     at async Server.requestListener (/workspaces/sandbox/node_modules/next/dist/server/lib/start-server.js:136:13) {
>   code: 'ERR_HTTP_HEADERS_SENT'
> ```
> 
> tbh, it seems more like an upstream issue. I'm pretty sure the `HydrationBoundary` works as expected. Gonna loop in @Ephem here because maybe it has to do how we rehydrate when a query doesn't exist yet, and maybe our caches are somehow kept when the page reloads? But honestly, not sure in which direction to investigate this further as long as there are these errors coming from next ...

For me there were no next errors (except for hydration issues), no headers error.

**Comment by TkDodo** [comment]
we did change Hydrate in v5, but not to the extent that it "shouldn't work" :)

**Comment by Ephem** [comment]
Let's take a look at `Providers` here:

```tsx
'use client';

import { QueryClientProvider } from "@tanstack/react-query";
import { createQueryClient } from "@/app/client";

const queryClient = createQueryClient();

export function Providers({children}: { children: React.ReactNode }) {
    return (
        <QueryClientProvider client={queryClient}>
            {children}
        </QueryClientProvider>
    )
}
```

Remember this does not only run client-side, it also runs during SSR. That means having this:

```tsx
const queryClient = createQueryClient();
```

in the root scope only creates _one_ `queryClient` for _all_ SSR requests, not one per request. If you move this inside as per the docs:

```tsx
"use client";

import {useState} from "react"
import { QueryClientProvider } from "@tanstack/react-query";
import { createQueryClient } from "@/app/client";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

export function Providers({ children }: { children: React.ReactNode }) {
  const [queryClient] = useState(() => createQueryClient())

  return (
    <QueryClientProvider client={queryClient}>
      {children}
      <ReactQueryDevtools />
    </QueryClientProvider>
  );
}
```

Everything works! 🎉 

Forked sandbox to prove it: https://codesandbox.io/p/devbox/vigorous-waterfall-zdrzk6?file=%2Fapp%2Fproviders.tsx%3A18%2C1

**Comment by evonicgu** [comment]
Oh, ok, I understand now. I was doing it similar to single client example in the docs. I think, I forgot to use `cache` in order for request data not to leak between different renders.

**Comment by Ephem** [comment]
No worries, this is all pretty confusing! 😄

Note that `cache` doesn't work in client components (yet, but I think that's on the long term React roadmap), so you have to put the `queryClient` in a state (or on a ref) for now.

Glad this got resolved!

**Comment by TkDodo** [comment]
Thanks @Ephem for taking a look here, I totally missed the queryClient problem
