### ISSUE TITLE
throwing error is not working

### ISSUE THREAD

**Issue by segun-flexible** [TanStack/query#6426]
### Describe the bug

when i intentional throw error, am unable to get it using productsQuery.error, and it just return null
am using Development build expo

const productsQuery = useQuery({
    queryKey: ['product', requeryMonitor],
    queryFn: async ()=>{
      throw new Error('Oh no!')
},
  });
  
  

### Your minimal, reproducible example

none

### Steps to reproduce

1. Just throw an Error in useQuery

### Expected behavior

when i throw error, am unable to get the error using productsQuery.error

### How often does this bug happen?

Every time

### Platform

Android & Ios
Expo Development Build

### Tanstack Query adapter

react-query

### TanStack Query version

^5.0.5

**Comment by TkDodo** [comment]
please provide a reproduction, and feel free to re-open the issue if you have one.

note that queries do 3 retries per default, so it can take some time until the query actually goes into error state.

**Comment by segun-flexible** [comment]
`const storeQuery = useQuery({
    queryKey: [queryKey, store.s_id],
    queryFn: async () => {

      try {

          const result = await fetcher({ url: `${ baseUrl } /api/stores / ${ store.s_slug } `, method: "GET" }, { showModal: false });
          
          if (result.status) {
  
            //Do Something

          } else throw Error(result.message || "Something Went Wrong")

      } catch (error) {
        console.log(error)
      }
      

      return {}
    
  })`
  
  
  it was working before on Expo, but when i change to Development build, is not working again, am unable to see error if i console storeQuery.error

**Comment by TkDodo** [comment]
please read: https://tkdodo.eu/blog/react-query-fa-qs#why-do-i-not-get-errors-

your problem is point 2, logging.
