### ISSUE TITLE
Errors after upgrade to Vite 5 / Rollup 4

### ISSUE THREAD

**Issue by Kamahl19** [TanStack/query#6433]
### Describe the bug

After upgrading to Vite 5 which uses Rollup 4, I am getting 2 errors when building.

```
node_modules/@tanstack/react-query-devtools/build/modern/index.js (1:0) Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/@tanstack/react-query/build/modern/useBaseQuery.js (1:0) Error when using sourcemap for reporting an error: Can't resolve original location of error.
```

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/tanstack-query-example-react-simple-cn8h2r?embed=1

### Steps to reproduce

1. upgrade to vite v5
2. run vite build

### Expected behavior

No error should be shown

### How often does this bug happen?

Every time

### Platform

any

### Tanstack Query adapter

react-query

### TanStack Query version

5.8.6

### TypeScript version

5.2.2

**Comment by TkDodo** [comment]
I added a quick integration test for vite5, which works fine. So I think your issue must be somewhere else

- https://github.com/TanStack/query/pull/6443

**Comment by DovMa** [comment]
In my case, I had an import like this ...from  '@tanstack/react-query/build/modern'

**Comment by Stanzilla** [comment]
Getting the same now only after adding Sentry to the project

**Comment by PymZoR** [comment]
> Getting the same now only after adding Sentry to the project and enabling SourceMaps

Same here

**Comment by emrerdem1** [comment]
I get the same error while getting a Docker build
