### ISSUE TITLE
Invalidate Queries don't work with notification context

### ISSUE THREAD

**Issue by verbeckii** [TanStack/query#6434]
### Describe the bug

I've created a notification provider with one ui lib and I'm trying to show notifications when my queries are successful or errors
and I found an interesting case where Invalidate Queries were not working

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/invalidatequeries-and-notification-context-rkzdtg?file=%2Fsrc%2Fwith-react-query.js%3A15%2C22

### Steps to reproduce

1. find my testing codesandbox app with fetched users and 2 buttons, one trigger update user(useMutation) and another one trigger update posts(useMutation), all buttons also triggers invalidation getUsersApi
2. Please open react dev tools and open "Preview Console" to open Chrome dev tools and go to Network tab to see and detect which network request we will send
3. click on Update user button and confirm we have '1' and 'users' it is working as well
![image](https://github.com/TanStack/query/assets/60220767/ab84d39c-8cbe-4462-ac4c-e7d6a6757b6d)
4. from now something happens and we can click on Update user or on Update Post buttons as many as we won't and it will send only one network request, it will not also trigger getUsersApi as we usually want
![image](https://github.com/TanStack/query/assets/60220767/71c27fa2-241b-446f-886b-e91058eba531)
 

### Expected behavior

I expected this behavior:
1. go to the app
2. click on Update user or Update post as many as we want and each time it should trigger getUsersApi as well as in the screenshot(here I comment `const { addErrorNotification } = useNotifications()` )
![image](https://github.com/TanStack/query/assets/60220767/48ec99bb-d9b0-4ae9-be9c-06d62a284ea8)

### How often does this bug happen?

Every time

### Platform

Windows 10
Chrome Version 119.0.6045.160 (Official Build) (64-bit)

### Tanstack Query adapter

react-query

### TanStack Query version

5.8.1

### TypeScript version

5.1.6

**Comment by charlotte-bone** [comment]
It is create creating a new query client every time WithReactQuery is re-rendered (which it does every time you click on either button, as addErrorNotification isn't memoized). If you add in a useMemo where you declare the queryClient and some useCallback hooks into NotificationProvider, then only one query client should be created.

https://codesandbox.io/p/sandbox/invalidatequeries-and-notification-context-forked-rywdsh

**Comment by verbeckii** [comment]
> This isn't a bug. It is creating a new query client every time WithReactQuery is re-rendered (which it does every time you click on either button, as addErrorNotification isn't memoized). If you add in a useMemo where you declare the queryClient and some useCallback hooks into NotificationProvider, then only one query client should be created.
> 
> https://codesandbox.io/p/sandbox/invalidatequeries-and-notification-context-forked-rywdsh

Thank you very much, you help me a lot with this
