### ISSUE TITLE
`queryOptions()` helper using `select` doesn't type-check when used with `useQueries`

### ISSUE THREAD

**Issue by larrifax** [TanStack/query#6442]
### Describe the bug

I'm trying to use a `QueryOptions` object created with the new `queryOptions()` helper in a `useQueries()` call.  
This doesn't typecheck as long as the options object contains a `select`-fn where the return type doesn't equal the return type of the `queryFn`.

It works fine when the same options object is used in a `useQuery()`. Same story with `useSuspenseQueries()` and `useSuspenseQuery()`

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRwK4FMoE8DyYbAQB2AzgDRyonoCKG2FVt9w6JcAvnAGZQQhwARAAEYAQ1LiAxgGsA9FHRipMALRpMWQQChtU4iXgbsAaXRY4AXjgAKAJRWAfHADagmecEBdPQaP0sADEiK1sHS2cABT4QYGoAOkUSCAAbADd0GwBGO19JFACAZXQU9BVoUJsAEzFxAC44IlQQACNMcOca8ThnLN19fIh8QlJQ41xhgxsEbTgCzTMsBvHF+zJZ+exg5YDg9bnqUpUdzWKjmGh1jjsAbn6-Taws0KY6TRshggNb+-zxgCYXtQ3lBWCRppswQ0XJ8RiQvJwfkA

### Steps to reproduce

1. Hover over the error reported in the `useQueries` call in `query2`
2. Observe that it is expecting `select` to return the same type as `queryFn` 

### Expected behavior

I would expect that the `useQueries` call would type-check the same way as the `useQuery` call

### How often does this bug happen?

None

### Platform

Any platform

### Tanstack Query adapter

react-query

### TanStack Query version

5.8.7

### TypeScript version

5.3.2

**Comment by charlotte-bone** [comment]
@TkDodo I think that I have a fix for this. It looks as though it's because select should be optional. I think it affects a few other places too. Could you please assign to me and I'll get the PR ready.

**Comment by charlotte-bone** [comment]
@TkDodo I've managed to get this working - although I couldn't find type tests for most of the methods changed. Let me know if I've done anything wrong as it's my first time opening a PR here.

**Comment by TkDodo** [comment]
@charlotte-bone thank you for this ❤️ 

> although I couldn't find type tests for most of the methods changed

yeah with `useQueries`, we still have an older method of type tests where we include them in the normal test file. At some point, I'd like to refactor this to be similar to `[useQuery.types.test.tsx](https://github.com/TanStack/query/blob/c014ea7a29db5bdd0770733e3c531c9050d7e4e9/packages/react-query/src/__tests__/useQuery.types.test.tsx)`

If that sounds interesting to you, please go ahead :)

Also: We have the useQueries types copied in multiple adapter packages. I think `vue-query` etc would have the same bug. Not sure how much we could abstract here, but we have about 5 usages of very similar types. If you want to take a stab at this too, it would be much appreciated.

**Comment by larrifax** [comment]
Thank you @charlotte-bone! I tried fixing this myself, but my Typescript-fu didn't suffice in this instance. 😄 
And thank you @TkDodo for merging & releasing this so quickly. 👍
