### ISSUE TITLE
[vue-query]: type issue with `queryOptions` inside `ensureQueryData`

### ISSUE THREAD

**Issue by MellKam** [TanStack/query#6477]
### Describe the bug

```ts
import { QueryClient, queryOptions } from "@tanstack/vue-query";

const queryClient = new QueryClient();

queryClient.ensureQueryData(
  queryOptions({
    queryKey: ["hello"],
    queryFn: () => Promise.resolve("hello"),
  }),
);
```

Error:

```
Argument of type 'UndefinedInitialQueryOptions<string, Error, string, string[]> & { queryKey: DataTag<string[], string>; }' is not assignable to parameter of type 'FetchQueryOptions<string, Error, string, string[], never>'.
  Type '{ enabled?: MaybeRefOrGetter<boolean | undefined>; staleTime?: MaybeRefDeep<number | undefined>; refetchInterval?: MaybeRefDeep<number | false | ((query: Query<...>) => number | ... 1 more ... | undefined) | undefined>; ... 26 more ...; maxPages?: MaybeRefDeep<...>; } & { ...; } & { ...; }' is not assignable to type 'FetchQueryOptions<string, Error, string, string[], never>'.
    Types of property 'staleTime' are incompatible.
      Type 'MaybeRefDeep<number | undefined>' is not assignable to type 'number | undefined'.
        Type 'Ref<number | undefined>' is not assignable to type 'number'.
```

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/typescript-playground-export-forked-6fng5h?file=%2Findex.ts

### Steps to reproduce

Just inistall dependencies and run typesciprt server

### Expected behavior

I expect it to work without type error

### How often does this bug happen?

Every time

### Platform

- Windows
- Chrome
- vue - `3.3.9`

### Tanstack Query adapter

vue-query

### TanStack Query version

5.12.2

### TypeScript version

5.3.2

**Comment by TkDodo** [comment]
this works fine in react-query, so it's a vue specific issue:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRQK4FMoE8DCAbYdAOxgBo4BHDbAeTBmAiIGc4BfOAMyghDgCIAAjACGLUQGMA1gHoo6ERJgBaKpiz8A3AChtEps3hrs+QiTgBeOEXQB3FNVwFiMABQBKHduNOzMAHTEzKjyaOoAIiKirtpwlI50DAauCLFx8eoA0uhYAFxwANr8ABboeHgQ-AC6pGlxPgBiRPkelgB8cAAKPCDAzOj+8swQeABu6K4lZRX87rVxbHPankA

@DamianOsipiuk FYI
