### ISSUE TITLE
IsLoading is not returned from useMutation

### ISSUE THREAD

**Issue by ergi98** [TanStack/query#6478]
### Describe the bug

There is no `isLoading` variable returned from useMutation. Also the status of the query does not return loading.

### Your minimal, reproducible example

.

### Steps to reproduce

1. Install
2. Use useMutation

### Expected behavior

isLoading and status of 'loading' to be returned

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="706" alt="image" src="https://github.com/TanStack/query/assets/70513280/44b46d0e-73fe-4e0d-bcd2-a117231ccdec">

<img width="706" alt="image" src="https://github.com/TanStack/query/assets/70513280/a51c81cf-df28-43e0-a3ca-7bc3e6752b07">

### Platform

- OS: Mac OS Ventura 13.6

### Tanstack Query adapter

react-query

### TanStack Query version

v5.12.2

### TypeScript version

v4.8.4

**Comment by maliuta-oleksandr** [comment]
isPending doesn't work as expected for me while API call is in progress

**Comment by ipsips** [comment]
From the migration guide:

> status: loading has been changed to status: pending and isLoading has been changed to isPending and isInitialLoading has now been renamed to isLoading

That seems to be the case with queries only. useMutation result however does not include `isLoading`.
Using v5.81.5

If i look at [useMutation docs](https://tanstack.com/query/latest/docs/framework/react/reference/useMutation), then yes, "pending" is the new "loading"

> status: pending – if the mutation is currently executing.
