### ISSUE TITLE
Performance issue in @tanstack/query-async-storage-persister (and possibly #updateStaleTimeout)

### ISSUE THREAD

**Issue by Jack-Works** [TanStack/query#6489]
### Describe the bug

It looks like [delayFunc](https://github.com/TanStack/query/blob/f4822a739a1e93550b45169ab47058f1d669a265/packages/query-async-storage-persister/src/asyncThrottle.ts#L37) in the `packages/query-async-storage-persister/src/asyncThrottle.ts` has some performance problem.

```js
  const delayFunc = async () => {
    clearTimeout(timeout)
    timeout = setTimeout(() => {
      if (running) {
        delayFunc() // Will come here when 'func' execution time is greater than the interval.
      } else {
        execFunc()
      }
    }, interval)
  }
```

<img width="1374" alt="img" src="https://github.com/TanStack/query/assets/5390719/385d65a8-381e-4926-a25e-8245a2c13b51">

this is the 4x slow-down profile, each `refetch` call causes `persistQueryClientSave` to be called, and then `delayFunc` is the slowest function in the tree. All small yellow bars are `setTimeout` or `clearTimeout` calls.

My throttle timeout is the default (1e3), therefore it cannot be caused by `execFunc` (all those `delayFunc` calls happen within 1 second).

I try to patch my node_modules and replace the `asyncThrottle` with this:

```js
function asyncThrottle2(func, { interval = 1e3, onError = noop } = {}) {
    if (typeof func !== 'function') throw new Error('argument is not function.')
    let currentArgs = null
    setInterval(() => {
        if (!currentArgs) return
        Promise.resolve(func(...currentArgs)).catch(onError)
        currentArgs = null
    }, interval)
    return (...args) => {
        currentArgs = args
    }
}
export { asyncThrottle2 as asyncThrottle }
```

This implementation is incorrect but fast.

<img width="1400" alt="img" src="https://github.com/TanStack/query/assets/5390719/01d4c5f0-e413-4656-a89b-c012793d2cd5">

After the patch, `persistQueryClientSave` now only costs 1 ms instead of 57 ms.

I think it looks like calling `setTimeout` or `clearTimeout` is costly. I think a better async throttle implementation can avoid calling them so often.

btw I also observed that `#updateStaleTimeout` method has a similar behavior.

<img width="1177" alt="img" src="https://github.com/TanStack/query/assets/5390719/3728b88e-5e20-4cd5-88ec-7f7c00714652">

also, this method behaves like `delayFunc`, simple but costs a lot of time (cancel & create timer).

<img width="526" alt="img" src="https://github.com/TanStack/query/assets/5390719/c5dd7021-b74d-4655-b9ba-f1ae4cf5db11">

### Your minimal, reproducible example

n/a

### Steps to reproduce

Sorry I didn't provide one, but my patch works so I think my analysis of the performance problem is correct.

I'm happy to try any new asyncThrottle implementation (by patch node_modules, so maintainers don't have to release a new version for this) in our project to see if that fixes the performance problem. Thanks!

### Expected behavior

No performance problem

### How often does this bug happen?

Every time

### Platform

Chrome 119

@tanstack/query-async-storage-persister 5.8.7

### Tanstack Query adapter

None

### TanStack Query version

5.8.7

**Comment by TkDodo** [comment]
> I'm happy to try any new asyncThrottle implementation 

if you have a better implementation that is also correct, please do contribute 🙏. The `asyncThrottle` function does have a decent test coverage.

Maybe we can also get inspired by other, already existing implementations?

- https://github.com/sindresorhus/p-throttle

**Comment by TkDodo** [comment]
@Jack-Works would you consider contributing your patch back to the persister plugin?

- https://github.com/DimensionDev/Maskbook/pull/11227/files

**Comment by Jack-Works** [comment]
> @Jack-Works would you consider contributing your patch back to the persister plugin?
> 
>     * [DimensionDev/Maskbook#11227 (files)](https://github.com/DimensionDev/Maskbook/pull/11227/files)

Hi! I think our patch is obviously imperfect (it is over simplified and maybe even incorrect). I hope your team can find another throttle implementation and I'd like to try it.

**Comment by jhnns** [comment]
> Maybe we can also get inspired by other, already existing implementations?
> 
>     [sindresorhus/p-throttle](https://github.com/sindresorhus/p-throttle)

@TkDodo Genuine question: why don't you use p-throttle? :) I'm just trying to understand what makes `asyncThrottle` special.

**Comment by webNeat** [comment]
Hello @jhnns,

I was also wondering why not just use `p-throttle`, so I looked into the two implementations and they don't actually behave the same.

Take the following example:

```js
const start = performance.now();
const fn = (a, b) => {
  const time = Math.floor(performance.now() - start);
  const result = a + b;
  console.log({ time, result });
};

const throttledFn = asyncThrottle(fn, { interval: 500 });

throttledFn(1, 2); // prints: { time: 0, result: 3 }
throttledFn(1, 3); // ignored
throttledFn(1, 4); // ignored
throttledFn(1, 5); // ignored
throttledFn(1, 6); // prints: { time: 500, result: 7 }
```

So to my understanding, `asyncThrottle` only keeps the last call waiting and ignores all the other calls.

While `p-throttle` keeps all the calls waiting and executes them in order:
```js
import pThrottle from "p-throttle";

const start = performance.now();
const fn = (a, b) => {
  const time = Math.floor(performance.now() - start);
  const result = a + b;
  console.log({ time, result });
};
const throttle = pThrottle({
  limit: 1,
  interval: 500,
});
const throttledFn = throttle(fn, { interval: 500 });

throttledFn(1, 2); // prints: { time: 0, result: 3 }
throttledFn(1, 3); // prints: { time: 500, result: 4 }
throttledFn(1, 4); // prints: { time: 1000, result: 5 }
throttledFn(1, 5); // prints: { time: 1500, result: 6 }
throttledFn(1, 6); // prints: { time: 2000, result: 7 }
```

I didn't find a way to tell `p-throttle` to only keep the last call, so I don't think it can be used as a drop-in replacement for `asyncThrottle`.

**Comment by webNeat** [comment]
@Jack-Works I made the PR https://github.com/TanStack/query/pull/7224 that suggests a new implementation. Can you please try it on your project and let us know if it fixes the issue?

**Comment by TkDodo** [comment]
fixed by:
- #7224
