### ISSUE TITLE
Queries' cache works strange when dynamic `queryKey` is used

### ISSUE THREAD

**Issue by PowerSlime** [TanStack/query#6495]
### Describe the bug

When `queryKey` is static then on re-renders of the component it doesn't get refetched, but when it's dynamic then no matter what it keeps calling `queryFn` function even if it was called with the same `queryKey` before.

I created simple switch which changes queryKey from 1 to 0 and from 0 to 1.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/unruffled-david-m8mmdl?file=%2Fsrc%2FComponent.tsx%3A19%2C25

### Steps to reproduce

1. Go to provided sandbox link
2. Open it's console to see when `console.log` gets called
3. Start clicking on the button

### Expected behavior

As a developer I expect that my `queryFn` response will be cached and won't be called if previously used `queryKey` will be passed.

So I expect to see only 2 executions of `console.log("called")` in the console, but instead I see them on every click.

### How often does this bug happen?

Every time

### Platform

- Browser: Chrome
- Version: v119.0.6045.200

### Tanstack Query adapter

react-query

### TanStack Query version

v5.12.2

### TypeScript version

v4.4.2

### Additional context

It's a little confusing because when you use some key that are "constant" then request is cached and queryFn doesn't get called once again, but in case when query key is dynamic (for example, in our specific case user may enable of disable some filter, which makes query be dependant that boolean flag) caching is still working but `queryFn` is called on every change, even if it was already called with previous `queryKey`.

**Comment by PowerSlime** [comment]
Ok. So it's an expected behavior as I understand.
In case when query key doesn't get changed over the time the requests doesn't get sent because it's not marked as stale.
But when queryKey changes previous result of the function execution then it gets marked as state and even if cache already exists - function will be re-runned.

If I understand everything correctly, then, I guess issue could be closed.

**Comment by TkDodo** [comment]
the query key points to a query in the cache. When you switch from one query to the next by changing the key, it's one of the indicators that react-query uses to potentially refetch stale queries.

when the key doesn't change, nothing happens, because otherwise, there would be a fetch on every re-render
