### ISSUE TITLE
`useSuspenseQueries` and `startTransition` will trigger infinite query requesting

### ISSUE THREAD

**Issue by angeloaltamiranom** [TanStack/query#6498]
### Describe the bug

If you use `startTransition` to change any value used in a query of `useSuspenseQueries` you will get infinite query requesting.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/tanstack-query-bug-forked-sz564y?file=%2Fsrc%2FApp.js

Edit: Query cancellation was important for this bug to manifest: https://codesandbox.io/p/sandbox/infinite-query-retrying-example-9k2456?file=%2Fsrc%2FApp.js

### Steps to reproduce

1. Open the code sandbox
2. Open the console
3. Click on the `set seed` button
4. Watch the infinite query requesting

### Expected behavior

I expect not to get into the infinite requesting state.

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/query/assets/71276198/eaa7ccdf-a863-4a28-8bb0-7a680ae78cf8

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 119.0.6045.199

### Tanstack Query adapter

react-query

### TanStack Query version

5.12.2

### Additional context

Might be related to the following issues: 
- https://github.com/TanStack/query/issues/6486 
- https://github.com/TanStack/query/issues/6491

**Comment by maciej-baruch** [comment]
@angeloaltamiranom So I wrote a couple of tests and ... I could not fail them, they all passed, there is nothing wrong with the lib.

Make sure your queryClient is static, do not recreate it every time your App re-renders.

Instead of this:
```
export default function App() {

...

  return (
    <QueryClientProvider client={new QueryClient()}>
```

Do this:
```
const client = new QueryClient()

export default function App() {

...

  return (
    <QueryClientProvider client={client}>
```

**Comment by angeloaltamiranom** [comment]
@maciej-baruch Good note. Sadly, your fix only addressed my minimal reproducible example, which maybe was too 'minimal' to show the real issue my team was encountering in our project. 

In this codesandbox I have added query cancellation, and used your fix as well, and the issue is still visible: https://codesandbox.io/p/sandbox/infinite-query-retrying-example-9k2456?file=%2Fsrc%2FApp.js

**Comment by GabbeV** [comment]
I seem to have this issue as well.
Here is a reproduction that resemble my code:
https://codesandbox.io/p/sandbox/quirky-knuth-8ns8dz?file=%2Fsrc%2FApp.tsx%3A8%2C41

After 5.8.6 the old query seem to be garbage collected before the new query is done causing the old query to get fetched again. While fetching the old query again the new query gets garbage collected causing it too loop forever unless the fetch happens to be faster than the gcTime.

Looking at the devtools i can see that before 5.8.6 the old query had an observer until the new query was done while after 5.8.6 the observer immediately disappears and the new query get an observer instead.

Attaching and detaching observers during render seems like a bad idea as react expect render to be a pure operation that it can rerun. Failing to rerun the old rerender here not only lead to the infinite loop but also cause the suspense fallback to get shown even though it shouldn't when the update is using a deferred value or is in a transition.

**Comment by TkDodo** [comment]
I have a new fix that reverts the 5.8.6 changes and fixes that issue in a different way. Can you check if the codesandbox preview from this PR works for you?

- https://github.com/TanStack/query/pull/6611

basically, depend on:

```
"@tanstack/react-query": "https://pkg.csb.dev/TanStack/query/commit/0b33cd80/@tanstack/react-query",
```

and see if that fixes your issues, thanks

**Comment by GabbeV** [comment]
Can't speak for the issue 5.8.6 solved but my codesandbox work as I expect if I change it to depend on 0b33cd80.

**Comment by TkDodo** [comment]
Thx. The 5.8.6 issue is covered with tests so I'm quite sure it's also fixed in that version.

**Comment by TkDodo** [comment]
@GabbeV thanks, I can see in your reproduction that your problem is actually the same as #6486 except that your old query gets gc'd in between
