### ISSUE TITLE
DevTools don't scroll

### ISSUE THREAD

**Issue by luixo** [TanStack/query#6508]
### Describe the bug

Hello,
I updated `react-query` from v4 to v5 and `DevTools` (while looking different in general) stopped to scroll.
The solution is pretty easy: `.tsqd-queries-container { overflow-y: scroll; }`

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/jovial-currying-5rfkly

### Steps to reproduce

1. Add DevTools to your page
2. Add more queries / make DevTools window smaller

### Expected behavior

DevTools is scrollable

### How often does this bug happen?

None

### Platform

-

### Tanstack Query adapter

react-query

### TanStack Query version

5.12.2 (DevTools: 5.13.3)

**Comment by TkDodo** [comment]
@ardeora FYI

**Comment by TkDodo** [comment]
interestingly, it becomes scrollable as soon as you select one entry:

selected (with scrollbars)

![Screenshot 2023-12-09 at 19 39 54](https://github.com/TanStack/query/assets/1021430/08c98e55-45d8-489a-b008-cc216bbf747d)

unselected (without scrollbars)
![Screenshot 2023-12-09 at 19 40 01](https://github.com/TanStack/query/assets/1021430/5640876b-1c31-4af2-bdc9-5210e5d4a745)
