### ISSUE TITLE
`gcTime` has a 32 bit limit

### ISSUE THREAD

**Issue by nahtnam** [TanStack/query#6513]
### Describe the bug

I was trying to set the gcTime to 30 days and was noticing all sorts of bugs. Seems like it has a 32 bit integer limit

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/vigorous-lehmann-9gf2wv

### Steps to reproduce

At 30 days, youll notice once you go to another page, the previous page's cache will be ejected. If you change it to 24 days (just under 32 bit limit), it works fine!

### Expected behavior

Should accept any number, at least 64 bit

### How often does this bug happen?

Every time

### Platform

Chrome

### Tanstack Query adapter

None

### TanStack Query version

5.13.4

**Comment by TkDodo** [comment]
see https://github.com/TanStack/query/issues/1646
