### ISSUE TITLE
useInfiniteQuery not doing anything

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [TanStack/query#6533]
### Describe the bug

Calling `fetchNextData` doesn't return anything

```js
  const { data, fetchNextPage } = useInfiniteQuery({
    queryKey,
    queryFn: ({ pageParam }) => {
      const { skip, limit } = (pageParam as {
        skip: number;
        limit: number;
      }) || { skip: 0, limit: 1 };
      console.log("wee", skip, limit);
      return queryFn({
        skip: skip.toString(),
        limit: limit.toString(),
      });
    },
    getNextPageParam: (lastPage, pages) => {
      lastPage.next ? lastPage.next : undefined;
    },
  });

```

Where queryFn returns a `Page` type

```js
export interface Cursor {
  skip: number;
  limit: number;
}

export interface Page<T> {
  prev: Cursor | null;
  next: Cursor | null;
  items: T[];
  count: number;
}
```

A `queryFN` looks like

```js
export const getPipelines = async ({
  skip = "0",
  limit = LIMIT_PER_REQUEST,
}: {
  skip: string;
  limit?: string;
}): Promise<Page<Pipeline>> => {
  const response = await fetch(
    `${API_URL}/pipelines?` +
      new URLSearchParams({
        skip,
        limit,
      }),
    {
      method: "GET",
      cache: "no-cache",
    }
  );
  if (!response.ok) {
    throw new Error("Network response was not ok: " + response.statusText);
  }
  const data = await response.json();
  return data;
};
```

Then I have a `button`

```js
 <Button variant={"ghost"} size={"xs"} onClick={() => fetchNextPage()}>
          Load more
        </Button>
```
If I click it, it doesn't anything

One solution is to just use refetch, I handle my own state and call it a day but I really like to use this one :)

Thanks a lot

### Your minimal, reproducible example

I need a running api as I have them, not sure how

### Steps to reproduce

I have no idea how to do it since it needs a running server - I apology

### Expected behavior

Should fetch the next page or at least show the console log

### How often does this bug happen?

Every time

### Platform

MacOS X, Chrome

### Tanstack Query adapter

None

### TanStack Query version

how do I know it?

**Comment by FrancescoSaverioZuppichini** [comment]
When I click the button I can see that `getNextPageParam` get called and as you can see `.next` exists

![Screenshot 2023-12-13 at 14 22 49](https://github.com/TanStack/query/assets/15908060/696a1cb0-f781-47e4-bac8-199e1bad0ec5)

**Comment by FrancescoSaverioZuppichini** [comment]
turn out I forgot a `return` 😓 

but now `data` is always `undefined`


```ts
  useEffect(() => {
    console.log("data", data);
  }, [data]);
```
and for some reason the queryFn and getNextPageParam are called an enourmous amount of time, that is the result of ONE click of `load more`

What is going on here?

![Screenshot 2023-12-13 at 14 30 35](https://github.com/TanStack/query/assets/15908060/26569efe-8a23-4365-8312-24af58c91efd)

**Comment by TkDodo** [comment]
this is a question at best, and you're violating a bunch of rules when creating an issue here, so closing.

> Your minimal, reproducible example
I need a running api as I have them, not sure how

That's a lame excuse, out issue template even answers this question, saying:

> To stub out real api requests - Promise.resolve and Promise.reject are good options for easy reproduction

**Comment by FrancescoSaverioZuppichini** [comment]
> this is a question at best, and you're violating a bunch of rules when creating an issue here, so closing.
> 
> > Your minimal, reproducible example
> > I need a running api as I have them, not sure how
> 
> That's a lame excuse, out issue template even answers this question, saying:
> 
> > To stub out real api requests - Promise.resolve and Promise.reject are good options for easy reproduction

thank you for your response, I was hoping for a more friendly interaction, I am not a super expert here - maybe I was doing something obviously wrong to someone with more experience like yourself but it doesn't seem like - will debug on my own and if not succeed try to provide an example

Cheers,

Fra
