### ISSUE TITLE
when parent dom and son dom all request one same query, and inside son dom there's a inside dom which request query func, will cause infinite requests

### ISSUE THREAD

**Issue by LuluLiu66** [TanStack/query#6539]
### Describe the bug

when parent dom and son dom all request one same query, 
and inside son dom there's a inside dom which request query func, 
will cause infinite requests
<img width="836" alt="image" src="https://github.com/TanStack/query/assets/25550986/7484a03f-395f-49b6-b199-018a0308cab1">
<img width="680" alt="image" src="https://github.com/TanStack/query/assets/25550986/aab117e7-e8ca-41f4-b9c2-c13b3c2e704e">
<img width="828" alt="image" src="https://github.com/TanStack/query/assets/25550986/a9279bcd-f042-4661-afde-c0b932bd0164">
result:
<img width="1171" alt="image" src="https://github.com/TanStack/query/assets/25550986/2a4362dc-a935-4b9c-8fb3-9daa864d4ada">

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/react-query-pg262c?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq4wezxd00c03b6n4xukrh93%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq4wezxd00bx3b6ndtfkj8g6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq4wezxd00bz3b6n94phqoma%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq4wezxd00by3b6nvxxp9qaz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq4wezxd00bx3b6ndtfkj8g6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A25%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A25%257D%255D%252C%2522id%2522%253A%2522clq4w5c3y00gt3b6nr8ep08rn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clq4xzj7n00023b6or3ripzgs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A3%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A3%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fquery.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clq4y52wi00023b6nkzckr487%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FChild.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clq4wezxd00bx3b6ndtfkj8g6%2522%252C%2522activeTabId%2522%253A%2522clq4y52wi00023b6nkzckr487%2522%257D%252C%2522clq4wezxd00by3b6nvxxp9qaz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq4w3oiz00063b6nna3ag8qm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq4wezxd00by3b6nvxxp9qaz%2522%252C%2522activeTabId%2522%253A%2522clq4w3oiz00063b6nna3ag8qm%2522%257D%252C%2522clq4wezxd00bz3b6n94phqoma%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clq4wef1600633b6nansksq2k%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clq4wadmv014k3b6nbrm167f7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clq4wd8r60054ehhf4b4u2bdk%2522%257D%255D%252C%2522id%2522%253A%2522clq4wezxd00bz3b6n94phqoma%2522%252C%2522activeTabId%2522%253A%2522clq4wef1600633b6nansksq2k%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

1. setup parent dom which request a useQuery function
2. setup a children dom, and add a function inside it which request a useQuery function as well.
3. write a useQuery function

### Expected behavior

only call api one time

### How often does this bug happen?

Every time

### Platform

chrome browser

### Tanstack Query adapter

None

### TanStack Query version

3.39.3

**Comment by TarekArar99** [comment]
Actualy what you are facing here is not related to react-query, it's React behaviour, you are creating a component inside the render function (another component) which will cause the component to get recreacted on every rerender of the parent and the default behaviour of react-query is to refetch when component is rerendered,

move your second child component outside of the render function and your issue should be solved.

takeaway: never create components inside other components because it will return a new object at every rerender and will be treated as different component by React.
