### ISSUE TITLE
[vue-query] Type inference issue with `useQuery` data transformer when `queryFn` uses arguments

### ISSUE THREAD

**Issue by romansp** [TanStack/query#6543]
### Describe the bug

```ts
import { useQuery } from "@tanstack/vue-query";

const query = useQuery({
  queryKey: ["hello"] as const,
  queryFn: (params) => {
    return Promise.resolve("hello");
  },
  select: (data) => {
           //^? `unknown` but should be `string`
    return data;
  },
});
```

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ5wC+cAZlBCHAEQACMAhgHaoMDGA1gPQBuOAtAEcc+KgG4AUKwjN4Q3AQC8KDNnkAKBOLhw5+ANLo8ALjgBtKgAt0AG2sQqAXTj1UcKTIA0WncLwAxRhM1AEo4BQA+RG9tKHQYZChGOAAFchBgDAA6WNQIa250NUsbOypgiW1CL20Ma3RWGCCAE3oGUIiogEhtHt7OTgA9AH5ouFj4xLgWhgqiL0Jy8UlpFh95ACYw5SxfDW9dPANjM2LbeycXNxWYarX8AKCkVGAAc0Z6ayJ2yM1e8YSkqkKBl0Nl0Ll8oVTqVFpVbrV6o04GppvRvl1epj+sNRv9JqjZlVxAsJMsZHc8ABmLZoHbqX4Uo4mcxWM6OZyudwsW4HB7IsD0KD0ECodEMmJxAEpNIgsEQgpFVkwwnwmyI5qtNFhH7ibqYnrYkZ-SX4zUq4mLMmrA4AFhpKl2DIOTJOSvOHKunn2vgCagFQpFoXFYxNgJlWRyeQV0PssLm3gRDQ1bW1GP12kNuNDUzN3iJJKWXNkvgArPa6fg9tpnYZmTH2ZcizyfYw-YLhaKosaJmHgRHwVGoW6yuaamqGijNUHdfrM92pQS8-NykA

### Steps to reproduce

1. [Open minimal repro](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ5wC+cAZlBCHAEQACMAhgHaoMDGA1gPQBuOAtAEcc+KgG4AUKwjN4Q3AQC8KDNnkAKBOLhw5+ANLo8ALjgBtKgAt0AG2sQqAXTj1UcKTIA0WncLwAxRhM1AEo4BQA+RG9tKHQYZChGOAAFchBgDAA6WNQIa250NUsbOypgiW1CL20Ma3RWGCCAE3oGUIiogEhtHt7OTgA9AH5ouFj4xLgWhgqiL0Jy8UlpFh95ACYw5SxfDW9dPANjM2LbeycXNxWYarX8AKCkVGAAc0Z6ayJ2yM1e8YSkqkKBl0Nl0Ll8oVTqVFpVbrV6o04GppvRvl1epj+sNRv9JqjZlVxAsJMsZHc8ABmLZoHbqX4Uo4mcxWM6OZyudwsW4HB7IsD0KD0ECodEMmJxAEpNIgsEQgpFVkwwnwmyI5qtNFhH7ibqYnrYkZ-SX4zUq4mLMmrA4AFhpKl2DIOTJOSvOHKunn2vgCagFQpFoXFYxNgJlWRyeQV0PssLm3gRDQ1bW1GP12kNuNDUzN3iJJKWXNkvgArPa6fg9tpnYZmTH2ZcizyfYw-YLhaKosaJmHgRHwVGoW6yuaamqGijNUHdfrM92pQS8-NykA)
2. Inspect type of `data` parameter.
3. Compare type of `data` with and without arguments in `queryFn`.
4. `data` should be of type `string` but infers to `unknown`.

### Expected behavior

I'm expecting `data` in `select` transformer to have its type inferred from `queryFn` return.

### How often does this bug happen?

Every time

### Platform

- `vue` v3.3.11

### Tanstack Query adapter

vue-query

### TanStack Query version

v5.14.0

### TypeScript version

v5.3.3

### Additional context

Seems not to be an issue in `@tanstack/react-query`. [Same repro](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ5wC+cAZlBCHAEQACMAhgHaoMDGA1gPRTr2swBaAI458VANwAoVhGbwRuAgF4UGbIoAUCSXDgL8AaXR4AXHADaVABboANrYhUAunHqo4MuQBode0XgAxRjMNAEo4JQA+RF9dHhhkKEY4AAVyEGAMADoeVAhbADd0DWs7BypQqV1CH10MW3R+EIATegZwqJiASF1evs5OAD0Afli4eMTk1oYqoh9CSslpWRY-RQAmCNUsfy1ffTwjUwtS+0cXNw8VmFq1-CCQpFRgAHNGelsiDujtPomk1LpTLoHLoPKFYqncqLaq3eqNGAtNr0b7dProgYjMb-KbI2Y1SQLKTLOR3PAAZi2aB2ml+ZKOZksNjOzlc7k8LFuBwecA0YHoUHoIFQqLpcXQCQBaQowNB4KKJWZ0PxcLsCKR7QiP0kPXRvUxoz+EsmcGm9BVhMWJNWBwALFS1Ls6QcGSclec2VdvPt-EE+QKhSKYkbJclpRlsrl8gqoY4YXNfPCmryzaKdXr9UNDb0caa8b4CUSlhz5P4AKwOmn4Pa6F3GRmx1mXEtc32Mf2C4XhMXjY1SoGRsHRyHuioWupq-gaVNojFZ7F93EzAvzSpAA)

**Comment by TkDodo** [comment]
@DamianOsipiuk FYI

**Comment by Mini-ghost** [comment]
@DamianOsipiuk 

I tried making `select` as a pure function or `MaybeRef<T>` instead of `MaybeDeefRef<T>` and that fixed the error, but could this be a breaking change?
