### ISSUE TITLE
codemod: `remove-overloads` does not handle `useMutation`

### ISSUE THREAD

**Issue by slax57** [TanStack/query#6548]
### Describe the bug

According to the [update guide](https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5), the following replacement needs to be performed on `useMutation`:

```diff
- useMutation(fn, options)
+ useMutation({ mutationFn, ...options })
```

Unfortunately it turns out the `remove-overloads` codemod does not perform this replacement.

### Your minimal, reproducible example

https://stackblitz.com/github/gillkyle/query-v5-codemod?file=src%2Fhooks.ts

### Steps to reproduce

1. Open the sandbox, and wait for `npm install` to finish
2. Run the codemod via the version in `node_modules`:

```bash
npx jscodeshift ./src/ \
  --extensions=ts,tsx \
  --parser=tsx \
  --transform=./node_modules/@tanstack/react-query/build/codemods/src/v5/remove-overloads/remove-overloads.js
```

### Expected behavior

I would have expected the following lines

```tsx
  return useMutation(({ groupId }: { groupId: string }) => {
    return fetch(`/api/groups/${groupId}`, {
      method: "DELETE",
    });
  });
```

to become

```tsx
  return useMutation({
    mutationFn: ({ groupId }: { groupId: string }) => {
      return fetch(`/api/groups/${groupId}`, {
        method: 'DELETE',
      });
    },
  });
```

But the lines remain untouched.

### How often does this bug happen?

Every time

### Platform

- OS: linux
- Browser: Chrome
- Version: 5.14.0

### Tanstack Query adapter

None

### TanStack Query version

5.14.0

### Additional context

Follow up to issue https://github.com/TanStack/query/issues/6204

**Comment by TkDodo** [comment]
@balazsmatepetro can you have a look here please?

**Comment by balazsmatepetro** [comment]
> @balazsmatepetro can you have a look here please?

Sure!

**Comment by nayan-c247** [comment]
Any update on this @balazsmatepetro @TkDodo? facing issue while migrating to v5.

**Comment by TkDodo** [comment]
@balazsmatepetro are you working on this ?

**Comment by nayan-c247** [comment]
@balazsmatepetro @TkDodo

**Comment by TkDodo** [comment]
@nayan-c247 if this is important to you, please consider contributing rather than tagging people. Thanks.

**Comment by balazsmatepetro** [comment]
Hi @nayan-c247! Sorry for the late response, recently I didn't have time to work on codemods. I will check it this week and will get back to you! Thank you for your understanding. 🙏

**Comment by balazsmatepetro** [comment]
Hi @nayan-c247! It seems I found the root cause of the issue, but unfortunately, I need some more time to implement it. 😬 I will get back to you later this week!

**Comment by slax57** [comment]
I opened https://github.com/TanStack/query/pull/7187 to propose a fix. @balazsmatepetro any comments are welcome, happy to change anything if needed :slightly_smiling_face:

**Comment by balazsmatepetro** [comment]
Great job @slax57! I approved your PR. 🎉
