### ISSUE TITLE
Devtool button doesn't work with Headlessui Dialog component and backdrop

### ISSUE THREAD

**Issue by Nargonath** [TanStack/query#6551]
### Describe the bug

HeadlessUI Dialog component uses a portal to render their modal component as a child of `document.body`: https://headlessui.com/react/dialog#rendering-to-a-portal. This is to make sure it always displays over everything else. They also mark the React root node as `inert`. No matter where you place your `ReactQueryDevtool` component in your application it can't receive click event anymore once the modal is opened. The problem is that if you make queries inside your modal then you cannot access the debugging tools.

The best way to fix this would be for the Devtools to render through a portal as well so we can make sure it's rendered on top of everything as well IMO. Also the CSS stacking context will be the same as the modal so the Devtools should take over and be on top.

### Your minimal, reproducible example

https://github.com/Nargonath/react-query-devtools-zindex-bug

### Steps to reproduce

* Clone GitHub repo.
* Run npm run dev.
* Go to http://localhost:5173/.
* Click "Open dialog".
* Try clicking the devtool button and notice that the dialog backdrop gets the click event instead.

### Expected behavior

When clicking the Devtool button, it should open without impacting the Dialog component.

### How often does this bug happen?

Every time

### Platform

* Windows 11 WSL 2
* Brave v1.61.104

### Tanstack Query adapter

react-query

### TanStack Query version

5.14.1

### TypeScript version

5.3.3

### Additional context

@tanstack/react-query-devtools@5.14.1

**Comment by hichemfantar** [comment]
This happens because headless UI dialogs mark the inert property on the react app wrapper div.
The solution is to render the RQ dev tools outside.
```jsx
			{createPortal(
				<ReactQueryDevtools
					initialIsOpen={false}
					panelProps={{
						style: {
							// zIndex: 9999999999999999,
						},
					}}
				/>,
				document.body
			)}

```

**Comment by Nargonath** [comment]
Yes that's what I thought but as I mentioned in the description, shouldn't we make it part of the RQ devtool package?

**Comment by hichemfantar** [comment]
I don't see it as a bug, it's expected behavior due to the inert property.
And the workaround is pretty simple using a portal.

**Comment by Nargonath** [comment]
Yeah but as a matter of comparison, headlessUI doesn't require you to render their Dialog component with a portal to make sure it works properly. They do it themselves. Why not do the same for the RQ Devtool? I'd expect that most application will want the devtool button to be on top of everything anyway, plus it's stated in the docs that it should be put as high as possible without your component tree. Using `createPortal` within this package would ensure this and one less thing to do in userland.

**Comment by TkDodo** [comment]
I think you can render the devtools wherever you want to - we just export the component. There is no dependency on `react-dom` from within the devtools - only on `react`. I wouldn't want to add that.

The portal solution is a good one for user-land. I've seen similar problems with our dialog component - any click in the devtools will close the dialog - so I'll try that out myself :)

**Comment by Nargonath** [comment]
Alright, thanks for the answer. I'll implement the fix on my side then.

**Comment by seb-lean** [comment]
what is the workaround? Using Radix dialog and it adds pointer events: none to body :( 
https://www.radix-ui.com/primitives/docs/components/dialog

**Comment by cbix** [comment]
> what is the workaround? Using Radix dialog and it adds pointer events: none to body :( https://www.radix-ui.com/primitives/docs/components/dialog

Same here. A possible workaround is to pass an `onInteractOutside` event handler to `Dialog.Content` that conditionally prevents default if the target is contained by the dev tools. Something like
```tsx
<Dialog.Content onInteractOutside={(ev) => {
  if (devtoolsRef.current?.contains(ev.target as Node)) {
    ev.preventDefault();
  }
}}>...</Dialog.Content>
```
and wrap devtools like this (pointerEvents auto is required unless you render your `Dialog.Root` with `modal={false}`)
```tsx
<div ref={devtoolsRef} style={{ pointerEvents: 'auto' }}>
  <ReactQueryDevtools />
</div>
```
but I admit it's a bit hacky and a better solution might involve the radix dialog to either provide an option to ignore certain refs or actually consider the portal as a boundary instead of `document.body`.
