### ISSUE TITLE
Following the "Advanced Server Rendering" guide throws: Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".

### ISSUE THREAD

**Issue by ceefour** [TanStack/query#6554]
### Describe the bug

Trying to follow the guide: https://tanstack.com/query/latest/docs/react/guides/advanced-ssr
until before the section [Nesting Server Components](https://tanstack.com/query/latest/docs/react/guides/advanced-ssr#nesting-server-components)

e.g.:

```tsx
export default async function ArticlesServerComponent() {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery({
    queryKey: useListArticlesQuery.getKey(),
    queryFn: async () =>
      axiosFetcher<ListArticlesQuery, ListArticlesQueryVariables>(useListArticlesQuery.document),
  });
  return (
    <HydrationBoundary state={dehydrate(queryClient)}>
      <Articles />
    </HydrationBoundary>
  );
}
```

throws the following error:

```
Unhandled Runtime Error
Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".
  {data: function, dataUpdateCount: 1, dataUpdatedAt: ..., error: ..., errorUpdateCount: ..., errorUpdatedAt: ..., fetchFailureCount: ..., fetchFailureReason: ..., fetchMeta: ..., isInvalidated: ..., status: ..., fetchStatus: ...}
         ^^^^^^^^
```

### Your minimal, reproducible example

-

### Steps to reproduce

1. Follow the guide (using Nextjs 14.0.3)
2. Get error

### Expected behavior

I expected the dehydration to be working, but error.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="560" alt="image" src="https://github.com/TanStack/query/assets/24123/bd231587-0e96-47e5-80c5-8525597c7448">

### Platform

Nextjs 14.0.3

### Tanstack Query adapter

react-query

### TanStack Query version

5.14.1

### TypeScript version

5.3.3

**Comment by TkDodo** [comment]
axiosFetcher is likely a function that you meant to invoke, but didn't.

**Comment by ceefour** [comment]
Thank you @TkDodo , you are right!

For those having a similar issue, the fixed code is as follows:

```tsx
// ArticlesServerComponent.tsx
import { dehydrate, QueryClient, HydrationBoundary } from '@tanstack/react-query';

import { axiosFetcher } from 'src/utils/axiosFetcher';

import {
  ListArticlesQuery,
  useListArticlesQuery,
  ListArticlesQueryVariables,
} from 'src/gql/graphql';

import Articles from './Articles';

type Props = { params: { locale: string } };

export default async function ArticlesServerComponent({ locale }: { locale: string }) {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery({
    queryKey: useListArticlesQuery.getKey(),
    queryFn: async () => {
      // bug was here, adding "()" solved the problem
      const data = await axiosFetcher<ListArticlesQuery, ListArticlesQueryVariables>(
        useListArticlesQuery.document
      )();
      console.debug({ data });
    },
  });
  return (
    <HydrationBoundary state={dehydrate(queryClient)}>
      <Articles lang={locale} />
    </HydrationBoundary>
  );
```

**Comment by Ak1r0** [comment]
> Thank you @TkDodo , you are right!
> 
> `axiosFetcher` is a function that returns a function, which means it needs to be called "twice".
> 
> For those having a similar issue, the fixed code is as follows:
> 
> ```tsx
> // ArticlesServerComponent.tsx
> import { dehydrate, QueryClient, HydrationBoundary } from '@tanstack/react-query';
> 
> import { axiosFetcher } from 'src/utils/axiosFetcher';
> 
> import {
>   ListArticlesQuery,
>   useListArticlesQuery,
>   ListArticlesQueryVariables,
> } from 'src/gql/graphql';
> 
> import Articles from './Articles';
> 
> type Props = { params: { locale: string } };
> 
> export default async function ArticlesServerComponent({ locale }: { locale: string }) {
>   const queryClient = new QueryClient();
>   await queryClient.prefetchQuery({
>     queryKey: useListArticlesQuery.getKey(),
>     queryFn: async () => {
>       // bug was here, adding "()" solved the problem
>       const data = await axiosFetcher<ListArticlesQuery, ListArticlesQueryVariables>(
>         useListArticlesQuery.document
>       )();
>       console.debug({ data });
>     },
>   });
>   return (
>     <HydrationBoundary state={dehydrate(queryClient)}>
>       <Articles lang={locale} />
>     </HydrationBoundary>
>   );
> ```

Hello !

I had the same issue in fixed it (thanks to you) but in an other way. I was doing it wrong too.

Wrong code :

```ts
await queryClient.prefetchQuery({
    queryKey: [getWebhooksPath()],
    queryFn: () => getWebhooks(),
  });
```

Good code :

```ts
await queryClient.prefetchQuery({
    queryKey: [getWebhooksPath()],
    queryFn: () => getWebhooks, // I had to remove the "()" here and that's somehow logical ^^
  });
```
