### ISSUE TITLE
Production Build Error with @tanstack/react-query in a Next.js/MUI Project

### ISSUE THREAD

**Issue by Olow304** [TanStack/query#6560]
### Describe the bug

In my Next.js project with Material-UI (MUI) integration, I'm encountering a production-only error when using @tanstack/react-query. The error message is "Uncaught SyntaxError: Private field '#t' must be declared in an enclosing class". This issue does not occur in the development build.

**Packages:**

```json
"next": "13.2.4"
"react": "18.2.0"
"@tanstack/react-query": "^5.12.2",
"@mui/icons-material": "^5.14.18",
"@mui/lab": "5.0.0-alpha.123",
"@mui/material": "5.11.13",
"@mui/system": "5.11.13"
"@emotion/cache": "11.10.5",
"@emotion/react": "11.10.6",
"@emotion/server": "11.10.0",
"@emotion/styled": "11.10.6"
```

**Expected Behavior:**
The application should run without errors in production, as it does in the development environment.

**Actual Behavior:**
The application throws a syntax error related to the @tanstack/react-query package in the production build.

```JSX
// App.tsx snippet
const App = (props: ExtendedAppProps) => {
  // ... [other initializations]

  const queryClient = new QueryClient({
        defaultOptions: {
          queries: {
            networkMode: 'always',
            refetchOnReconnect: 'always',
            refetchOnWindowFocus: 'always',
            staleTime: 0,
          },
        mutations: {
          networkMode: 'always',
          retry: 0,
          retryDelay: 0,
          gcTime: 0,
        }
    },
  });

  return (
    <QueryClientProvider client={queryClient}>
      {/* ... rest of the component */}
    </QueryClientProvider>
  );
};

```

next.config.js:
```js
const path = require('path')

/** @type {import('next').NextConfig} */

module.exports = {
  trailingSlash: true,
  reactStrictMode: false,
  productionBrowserSourceMaps: true,
  webpack: (config, { isServer, dev }) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      apexcharts: path.resolve(__dirname, './node_modules/apexcharts-clevision')
    }

    if (dev || isServer) {
      config.devtool = 'source-map';
    }


    return config
  }
}
```

I removed the QueryClientProvider and everything works fine. It only happens on production build while using QueryClientProvider.

<img width="1030" alt="Screenshot 2023-12-19 at 10 18 34 AM" src="https://github.com/TanStack/query/assets/7048571/42216cf2-b6c1-4c1c-8e38-de69198379b6">

### Your minimal, reproducible example

None

### Steps to reproduce

1. Implement QueryClientProvider from @tanstack/react-query in a Next.js application with MUI components.
2. Build the Next.js application for production using yarn build.
3. Start the application with yarn start.
4. Visit the application, and observe the error in the console.

### Expected behavior

The application should run without errors in production, as it does in the development environment.

### How often does this bug happen?

None

### Platform

Browser: Chrome

### Tanstack Query adapter

None

### TanStack Query version

5.12.2

### TypeScript version

4.9.5

**Comment by TkDodo** [comment]
please provide a minimal reproduction. We have integration tests for various bundlers, including nextJs, and we also have working examples.

https://github.com/TanStack/query/tree/21502ad8e58a05474ced5fd91977edf701400ff5/integrations/react-next

In those integration tests, we run a production build to make sure that query is buildable with popular bundlers.

So whatever it is, it has to have something to do with your setup. Maybe it's the custom webpack config, idk. Also not sure why you mention MUI components explicitly. Are you sure it works without MUI?

All these questions can be better answered if you show a reproduction, so feel free to reopen if you have one.

**Comment by Olow304** [comment]
Using latest `@tanstack/react-query` version causes issue with MUI. I downgraded `"@tanstack/react-query": "^4.32.6"`, and everything works fine. 

Thanks for your help @TkDodo

**Comment by m-aykurt** [comment]
we have a same problem nextjs project `    "@tanstack/react-query": "5.8.4",
    "antd": "^5.8.3",` 
but i dont want to downgrade to v4. how can i fix it ? @TkDodo @Olow304

**Comment by TkDodo** [comment]
Are you saying everything works if you _remove_ antd and starts to fail again if you add it back? I have troubles believing that - it looks more like a bundling issue but I can't say without a reproduction

**Comment by m-aykurt** [comment]
No, actually, I mentioned Ant Design just as an example. I also have tanstack/react-query v5 installed in my project, and I'm encountering the same error. However, I don't want to downgrade to v4 because I've developed many features based on v5. Is there another solution for this?

![Ekran Resmi 2023-12-22 14 04 06](https://github.com/TanStack/query/assets/79319296/f5cb60a1-2e55-4734-8116-60b98604c7b7)
![Ekran Resmi 2023-12-22 14 06 19](https://github.com/TanStack/query/assets/79319296/5a2f867e-f3d0-48c9-87bb-970bec254422)

**Comment by TkDodo** [comment]
then create a standalone reproduction with as few dependencies as possible to reproduce the issue please. Yes, in v5 we started to use private class fields, but as I said, we are testing against various bundlers, so it must be something specific to how things are built on your end. That's why I can't say more without a reproduction.

**Comment by Wassap124** [comment]
im getting something similar:
```
TypeError: Cannot write to private field
```
digging into it a bit deeper, it fails on this line
```ts
    this.#client = client
```

in `queryObserver`

**Comment by nakamuraos** [comment]
I have faced this error with log `SyntaxError: Invalid character: '#'` on Safari on IOS 14, because safari 14 doesn't support private methods.

My solution is add this line in next.config.js:

```ts
/** @type {import('next').NextConfig} */
module.exports = {
  transpilePackages: ["@tanstack/query-core"],
}
```
and that's all.

**Comment by sommybrown** [comment]
> I have faced this error with log `SyntaxError: Invalid character: '#'` on Safari on IOS 14, because safari 14 doesn't support private methods.我在 IOS 14 上的 Safari 上使用日志 `SyntaxError: Invalid character: '#'` 时遇到了此错误，因为 safari 14 不支持私有方法。
> 
> My solution is add this line in next.config.js:我的解决方案是在 next.config.js 中添加这一行：
> 
> ```ts
> /** @type {import('next').NextConfig} */
> module.exports = {
>   transpilePackages: ["@tanstack/query-core"],
> }
> ```
> 
> and that's all. 就这样。
