### ISSUE TITLE
[vue-query] `getQueryData/setQueryData` fail to infer query data type from `queryOptions.queryFn`

### ISSUE THREAD

**Issue by romansp** [TanStack/query#6566]
### Describe the bug

When using `queryOptions` both `queryClient.getQueryData` and `queryClient.setQueryData` fail to infer query data type and fallback to `unknown`.

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ4DCANsOgHYwA0cAjjvgPJgzARmpwC+cAZlBCDgAiAAIwAhuwkBjANYB6AG44AtHVx4hAbgBQO6W1TwIzVuzgBeOAAoAlJYB8teniYtD1hDrjONAaXQ8AC44AG0hAAt0IiIIIQBdOHEOAylKb198ADEyELtHRAyfKHQYZCgyOAAFfhBgDAA6EtQIIkV0awByKJiITttdH050zgG9VKNMwhJyeCs0LBdiUgo7XQn4ABNxCUsp5dmGgHNS7A0AER3xaxN3djsG9XwAvDGfd7h5eQA9AH49J7TFYwBoYGBnfCXCQ3UweWyPFwvajWMAlRSsND2CxOLzFUrlSqo9DoiBoQYfClfP46UZaIA

### Steps to reproduce

1. Go to TS playground repro.
2. Inspect return types of `getQueryData` and updater callback in `setQueryData`

### Expected behavior

Query data type should be inferred properly from `queryOptions.queryFn`.

### How often does this bug happen?

Every time

### Platform

- `vue` v3.3.11

### Tanstack Query adapter

vue-query

### TanStack Query version

v5.14.4

### TypeScript version

v5.3.3

### Additional context

Types are inferred properly in `@tanstack/react-query`: [TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ4DCANsOgHYwA0cAjjvgPJgzARmpwC+cAZlBCDgAiAAIwAhuwkBjANYB6KOnHSYAWjq48QgNwAoPdLap4EZq3ZwAvHAAUASmsA+WvTxMWx2wj1xXWgGl0PAAuOABtIQALdCIiCCEAXThxDiMpSl9-fAAxMjCHZ0QsvyUYZCgyOAAFfhBgDAA6JVQIIgA3dFsAchi4iG77fT9OTM4hg3STbMIScngbNCw3YlIKB30p+AATcQlrGdX5xoBzdBhsLQARPfFbM092B0bNfCC8Cb8vuHl5AD0APwGV6zNYwRoYC5uG4Se7mLz2F5ud7UWxgJTtVhoRxWFw+UrnCpVdHoTEQNDDb5U36AvTjHRAA).

I thought it's quite bizzare it doesn't work properly in vue-query knowing that it's covered by tests here. https://github.com/TanStack/query/blob/4c9fde9f6960f38badf2ad9a6ed4d82a3b3b98da/packages/vue-query/src/__tests__/queryOptions.types.test.ts#L88-L101

But these tests are using `QueryClient` from `@tanstack/query-core`. After changing it to vue-specific `QueryClient` type tests start to fail. I'm not sure if that's an oversight or done on purpose.

**Comment by DamianOsipiuk** [comment]
@roblabat Could you take a look at this?

**Comment by roblabat** [comment]
@DamianOsipiuk I'm looking at it, it comes from queryOptions that fail to infer queryKey type correctly. I'll make a PR as soon as I'll find a solution on this.

**Comment by TkDodo** [comment]
FYI we have a related PR open:

-  https://github.com/TanStack/query/pull/6699

**Comment by roblabat** [comment]
I pushed a fix @TkDodo there shouldn't be conflict with #6699

**Comment by romansp** [comment]
Just upgraded to `5.17.15` and types are correctly inferred now. Thanks!
