### ISSUE TITLE
Tanstack/react-query doesn't work in my vercel app

### ISSUE THREAD

**Issue by kab1012** [TanStack/query#6571]
### Describe the bug

Vercel app crashes when I follow the tanstack/react-query-devtools blog and download the bundle with `window.toggleDevTools()`, first it gives "undefined" in the console and then application crashes

### Your minimal, reproducible example

NA

### Steps to reproduce

have shared the code structure here
https://stackoverflow.com/questions/77695875/tanstack-react-query-doesnt-work-in-my-vercel-app

### Expected behavior

devtools run on manual instantiation
### How often does this bug happen?

whenever vercel app component mounts

### Platform

OS: macOS 14.3
Browser: Safari and Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

5.14.2

### TypeScript version

0

### Additional context

Steps to reproduce would be 
1. initialise react next app with default settings (no typescript)
2. create a wrapper from the @tanstack/react-query imports
3. follow the blog https://tanstack.com/query/latest/docs/react/devtools

**Comment by TkDodo** [comment]
`toggleDevtools` is not something that _we_ ship. Devtools are meant for dev mode only. If you want to have devtools in production, you have to code it for yourself.

https://tanstack.com/query/v5/docs/react/devtools#devtools-in-production
