### ISSUE TITLE
[react-query] useSuspenseQuery missing docs on `throwOnError`

### ISSUE THREAD

**Issue by happycollision** [TanStack/query#6577]
### Describe the bug

The current docs only mention what properties are not available as options for the Suspense versions of all the Query hooks. However, they fail to mention that `throwOnError` is not available _[because they always throw](https://github.com/TanStack/query/issues/5920#issuecomment-1695821107)_. This is useful information.

### Your minimal, reproducible example

https://tanstack.com/query/v5/docs/react/reference/useSuspenseQuery

### Steps to reproduce

(read the docs)

### Expected behavior

I'd expect to know that if a property is unavailable _and its default value is different from the non-suspense version_ that the docs would mention it.

### How often does this bug happen?

Every time

### Platform

- n/a

### Tanstack Query adapter

react-query

### TanStack Query version

n/a

**Comment by TkDodo** [comment]
> However, they fail to mention that throwOnError is not available https://github.com/TanStack/query/issues/5920#issuecomment-1695821107. This is useful information.

How so? It's documented here:
https://tanstack.com/query/v5/docs/react/reference/useSuspenseQuery

> Options

> The same as for [useQuery](https://tanstack.com/query/v5/docs/react/reference/useQuery), except for:
> - `suspense`
> - `throwOnError`
> - `enabled`
> - `placeholderData`

**Comment by happycollision** [comment]
I’ve learned now that GH formats emails in a way that is very unfortunate. If you read the issue in the browser, you’ll see I didn’t say the fact that it is not available is undocumented, but rather the fact that it is unavailable and also is turned on (the opposite of useQuery) is not documented at that location.~DonOn Dec 23, 2023, at 5:07 AM, Dominik Dorfmeister ***@***.***> wrote:﻿
Closed #6577 as not planned.

**Comment by TkDodo** [comment]
How throwOnError behaves is documented in the guides: https://tanstack.com/query/v5/docs/react/guides/suspense#throwonerror-default

if you feel something is missing, please just open a PR to the docs
