### ISSUE TITLE
useQuery doesn't change data after query invalidation

### ISSUE THREAD

**Issue by rajzik** [TanStack/query#6583]
### Describe the bug

After query invalidation the data isn't changed. 

```tsx
const { status, data, error, isFetching, dataUpdatedAt } = usePosts();

  React.useEffect(() => {
    console.log("data updated", data);
   // this is only called twice once data is undefined and then when data is set
   // invalidate does nothing
  }, [data]);
  React.useEffect(() => {
    console.log({ dataUpdatedAt });
  }, [dataUpdatedAt]);
```

Is this correct behavior? I would expect when I invalidate query that data after refetch will be changed no matter what. 

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/green-monad-5mf7jh?file=%2Fsrc%2Findex.jsx%3A61%2C23

### Steps to reproduce

1. create query
2. Fetch data
3. Invalidate query
4. Data stays the same

### Expected behavior

As a user I expected that data will be changed after query invalidation

### How often does this bug happen?

Every time

### Platform

Mac os
Chrome
React 18

### Tanstack Query adapter

react-query

### TanStack Query version

5.14.6

### TypeScript version

5.3.2

**Comment by 0x2509** [comment]
This is an intended behavior.  

> Query results by default are structurally shared to detect if data has actually changed and if not, the data reference remains unchanged...

You can find the complete explanation here: [Important Defaults](https://tanstack.com/query/v5/docs/react/guides/important-defaults)  
Or here: [Structural sharing](https://tkdodo.eu/blog/react-query-render-optimizations#structural-sharing)

**Comment by TkDodo** [comment]
indeed, you can see in the devtools that the `dataUpdatedAt` and `dataUpdateCount` always increase. However, if data doesn't really "change", you'll get back the referentially same data, so your effects won't trigger unnecessarily. That is the `structuralSharing` feature, which you can turn off with `structuralSharing: false`.

**Comment by rajzik** [comment]
@TkDodo in our project when we invalidate query the data is changed on backend and refetched, this doesn't trigger useefect with data, is this intended?

**Comment by TkDodo** [comment]
If nothing changed in `data` then yes

**Comment by rajzik** [comment]
The data is changing and effect isn't triggered in my case. What algorithm is used to detect changes? @TkDodo

**Comment by TkDodo** [comment]
> The data is changing and effect isn't triggered in my case. What is used to detect changes? @TkDodo

then please show an example where data is changing because in your example, it's not.

links to structuralSharing explanations were shared here: https://github.com/TanStack/query/issues/6583#issuecomment-1870085059

**Comment by n-spl1nter** [comment]
I faced with the same problem. @rajzik did you solve it?

**Comment by woohyun-park** [comment]
same here. api gives new data but query data is not changed yet its fresh
