### ISSUE TITLE
Spreading an any type into UseQuery makes the data unknown

### ISSUE THREAD

**Issue by Jontii** [TanStack/query#6601]
### Describe the bug

Spreading an any type into UseQuery makes the data unknown, any other type and it keeps the type inheritance from the queryFn. I'm not sure if this is by design or a bug. Just wanted to make sure.

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ4A0c2ueAwgDbDoB28AvnAGZQQhwDkAAjAIY2o+AYwDWAeijpeQmAFoAjjnwcAsACh1QiAPiLSlanTgBeODXQB3YkvJVaMABQBKdeorp4EMDGDbUALn48E0R6VzUtHTg9fBC0LBsHBHU4aJsAaXQ8fzgAbQAiIV5YAH1Ffh8YPHyAXQIUtNIAMRoc3lQ8GiE4ZxMAPkQG1MkYZCgaOHyQPAA1XgocfIb6erVUgDpNrx8-dXoXDTUYvHWAE14+dTExVNSAPQB+cMjBOHO+AFUaERoICwnTMcDPZ1gBzDwkfAAEQuvAcuQ4RVK5TowCqHBqB2utzgj2efng714AEFUKhgKDzKcQkC7HQwRCbDC+AAeQRQYA0UF9eGI4owMrICpovAYrE3W6PIA

### Steps to reproduce

1. Spread a variable after the queryFn typed as any.
2. This will make it unknown.
3. Change the type to string [] or something that can be spread
4. It now shows the correct type again

### Expected behavior

As a user, I want to make sure that having a any type doesn't break the queryFn type. Perhaps adding a rule about it in the eslint if this is a common misstake.

### How often does this bug happen?

Every time

### Platform

- Mac OS m2, Latest firefox

### Tanstack Query adapter

react-query

### TanStack Query version

Latest

### TypeScript version

Latest

**Comment by TkDodo** [comment]
> As a user, I want to make sure that having a any type doesn't break the queryFn type. Perhaps adding a rule about it in the eslint if this is a common misstake.

spreading `any` onto an object will always make the whole object be of type any -  I have a blogpost on this topic: https://tkdodo.eu/blog/beware-the-leaking-any

There are already lint rules that can prevent any from leaking - have a look at the `no-unsafe-` group of rules in ts-eslint:

- https://typescript-eslint.io/rules/no-unsafe-argument
- https://typescript-eslint.io/rules/no-unsafe-assignment
- https://typescript-eslint.io/rules/no-unsafe-call
- https://typescript-eslint.io/rules/no-unsafe-member-access
- https://typescript-eslint.io/rules/no-unsafe-return

**Comment by Jontii** [comment]
Thank you so much for the answer ! :) Happy new year!
