### ISSUE TITLE
Doc site is down

### ISSUE THREAD

**Issue by CagriUysal** [TanStack/query#6603]
### Describe the bug

I am not able to access tanstack.com/query. Is there a problem with the site?

### Your minimal, reproducible example

tanstack.com/query

### Steps to reproduce

go to tanstack.com/query
it's not opening

### Expected behavior

site should be open

### How often does this bug happen?

None

### Platform

macOS, chore. it doesn't matter really

### Tanstack Query adapter

None

### TanStack Query version

v*

**Comment by TkDodo** [comment]
Works for me
