### ISSUE TITLE
No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by Manuelandro** [TanStack/query#6604]
### Describe the bug

Premise: i got this error only on production (next.js) and not always, just sometimes,

I already found this [issue](https://github.com/TanStack/query/issues/6432) and it seems that having two version (or the same twice) of react-query in the package-lock can cause this issue. The problem is that i have the version 5.0.0 that i use, and another version which is the dependency of the package wagmi that i need for my project
<img width="538" alt="Screenshot 2023-12-28 alle 14 14 56" src="https://github.com/TanStack/query/assets/3776546/e6b2fb91-2592-46ad-9870-7f11ba1568fe">

How can i solve the problem without removing wagmi which is required for my project?
I've tried to set it as peerDependency but with no luck
<img width="354" alt="Screenshot 2023-12-28 alle 14 21 15" src="https://github.com/TanStack/query/assets/3776546/2caf021b-2f4e-43a8-a3ae-217637f62561">

I also tried to downgrade react-query to the same version of the one inside wagmi but again, no results

### Your minimal, reproducible example

i have no repo cause happens only in production

### Steps to reproduce

This happens only in production

### Expected behavior

No error

### How often does this bug happen?

Often

### Platform

Sentry notifies errors from many users with multiple platforms

### Tanstack Query adapter

react-query

### TanStack Query version

5.0.0

### TypeScript version

5.0.4

**Comment by TkDodo** [comment]
if you use wagmi and it only supports v4, you have to use v4 as well.

wagmi v2 is currently in RC and it supports v5

https://www.npmjs.com/package/wagmi/v/2.0.0-rc.2

**Comment by Manuelandro** [comment]
@TkDodo thanks for the reply. So theoretically if i install wagmi rc it should automatically stop giving me this error?

**Comment by Manuelandro** [comment]
I downgraded to @tanstack/react-query v4 but the problem persists

**Comment by kaushikriya** [comment]
wagmi now support tanstack/query v5 as seen here [https://www.npmjs.com/package/wagmi?activeTab=code](url)
I only have one version installed on my machine `@tanstack/react-query@5.22.2`. I'm still facing this exact error @TkDodo

**Comment by sarthakkundra** [comment]
@kaushikriya were you able to fix the issue?

**Comment by Manuelandro** [comment]
> @kaushikriya were you able to fix the issue?

@sarthakkundra check if you have two versions of react query in your package-lock. Also try to remove ReacQueryDevTools if you use it

**Comment by emzet93** [comment]
@sarthakkundra @kaushikriya did you figure out was the issue in your cases? I'm facing the same problem after upgrading wagmi and react-query and run out of ideas already. I double checked and I have only single version `@tanstack/react-query@5.51.1` in my lock file 🤔
