### ISSUE TITLE
useInfiniteQuery not being refetch on param change

### ISSUE THREAD

**Issue by agilehorse** [TanStack/query#6613]
### Describe the bug

I have a react component which includes this code snippet

```
const {
        data, status: apiStatus, isFetchingNextPage,
        error, fetchNextPage
    } = useInfiniteQuery({
        queryKey: ['myKey', ownerId],
        queryFn: fetchData,
        initialPageParam: 0,
        getNextPageParam: (lastPage) => lastPage.page.number + 1
    })
    const queryClient = new QueryClient()
    async function fetchData({pageParam}: any) {
        return MyApi_getAll({
            isTestData: queryParams.get("isTestData") === "true",
            localStorageKey: userEmail,
            state: {size: 12, page: pageParam, filter: filter}
        });
    }
```

This component is reused on two different pages. Page A and B. When I route from page A to page B, the `ownerId` attribute changes, however the query is not refetched and I see the old data.

When I use console logs I see that the attribute has indeed changed, the debug tools for tanstack also seem to know about it:

Tanstack debug log from page B - active - ['myKey', 12]
Tanstack debug log from page A - stale - ['myKey', 38]

### Your minimal, reproducible example

in the msg above

### Steps to reproduce

in the msg above

### Expected behavior

the query will be refreshed when the attribute ownerId changes

### How often does this bug happen?

Every time

### Platform

macOs

### Tanstack Query adapter

None

### TanStack Query version

5.14.1

### TypeScript version

5.1.6

**Comment by TkDodo** [comment]
please show a minimal reproduction in a codesandbox or stackblitz

**Comment by agilehorse** [comment]
can be reproduced here https://github.com/agilehorse/infinite-query-bug

**Comment by TkDodo** [comment]
please trim down the example to make it as minimal as possible - it should only contain what is necessary to show the issue.

**Comment by agilehorse** [comment]
Okay I may have found out what was the issue. I think the component DataTab is being cached, maybe by react, it seems to depend also on the useState. The fix is adding useEffect that detects the change of personId in my tanstack store

```
useEffect(() => {
      if (formState.personId !== personId) {
          setFormState({...formState, personId: personId})
      }
}, [personId]);
```

**Comment by agilehorse** [comment]
@TkDodo You as a probably more experienced "reacter" might know if this theory is true. I would like to know your opinion. I have pushed even reduced version to the repo.
