### ISSUE TITLE
Cannot read property 'prototype' of undefined when declaring `new QueryClient()` on React Native

### ISSUE THREAD

**Issue by iyansr** [TanStack/query#6627]
### Describe the bug

The app throw error when just declaring `const queryClient = new QueryClient();` in the `App.tsx` file

### Your minimal, reproducible example

-

### Steps to reproduce

Only just Create variable 
`const queryClient = new QueryClient();`

### Expected behavior

I expect no error, but seeing that error

### How often does this bug happen?

None

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/42711013/3c6ac0f8-9103-49a4-875c-2eae2cc3bdd0)

### Platform

- OS: Mac OS Ventura M1
- Platform: React Native `v0.71.14`
- Expo: `~48.0.21`
- @tanstack/react-query : `^5.17.0`

### Tanstack Query adapter

None

### TanStack Query version

v5.17.0

**Comment by Estevete** [comment]
We are facing the same issue. It seems to be a regression from v5. Works perfectly with v4 & Expo SDK49

**Comment by iyansr** [comment]
> We are facing the same issue. It seems to be a regression from v5. Works perfectly with v4 & Expo SDK49

@Estevete have you try using v5 with Expo SDK49?

**Comment by Estevete** [comment]
Yep. Same issue you've mentioned.

**Comment by TkDodo** [comment]
Please show a reproduction. One thing we've changed in v5 is that we use more modern language features without transpiling them, like private class fields.

https://tanstack.com/query/v5/docs/react/installation#requirements

could this impact react-native ?

**Comment by iyansr** [comment]
@TkDodo the iOS simulator I use is 16.

I will try to create reproducible repository for this

**Comment by Estevete** [comment]
@iyansr Are you using custom metro config? Our problem was that we are using custom metro config for firebase and instead of pushing into `sourceExts ` we were doing it into `assetsExts`.

```
const { getDefaultConfig } = require('@expo/metro-config');

const defaultConfig = getDefaultConfig(__dirname);
defaultConfig.resolver.sourceExts.push('cjs');

module.exports = defaultConfig;
```


It seems that it has changed from Expo.

**Comment by iyansr** [comment]
Here's the metro config @Estevete 

```

// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('@expo/metro-config');

const defaultConfig = getDefaultConfig(__dirname);
defaultConfig.resolver.assetExts.push('cjs');

module.exports = defaultConfig;

```

**Comment by Estevete** [comment]
Then, there you have it. To solve it, replace `assetExts `by `sourceExts`.

**Comment by iyansr** [comment]
@Estevete Thanks, it's working!

@TkDodo thanks I will close this Issue
