### ISSUE TITLE
Angular Query: type narrowing not working on query and mutation result

### ISSUE THREAD

**Issue by arnoud-dv** [TanStack/query#6635]
### Describe the bug

From the [React Query documentation](https://tanstack.com/query/latest/docs/react/typescript#type-narrowing):

```ts
const { data, isSuccess } = useQuery({
  queryKey: ['test'],
  queryFn: () => Promise.resolve(5),
})

if (isSuccess) {
  data
  //  ^? const data: number
}
```

When the query is confirmed to be in success state, it is known that data cannot be undefined.

The QueryObserverResult discriminated union provides more such opportunities for type narrowing. This does not work with the Angular adapter. When the query / mutation result is converted into signals type information is lost. Types are retained only at field level, not allowing type narrowing.

Unit tests in #6634 demonstrate the issue.

### Your minimal, reproducible example

https://github.com/TanStack/query/pull/6634

### Steps to reproduce

- Checkout the branch for #6634
- In package angular-query-experimental run the unit tests with `pnpm test:lib` the type test for the discriminate union will fail.

### Expected behavior

Ideally, Angular Query should offer the same type narrowing on query and mutation results as React Query. As Angular Query uses signals (functions) on the result object this will be harder and may not be completely possible.

### How often does this bug happen?

Every time

### Platform

- All

### Tanstack Query adapter

angular-query

### TanStack Query version

v5.17.1

### TypeScript version

v5.2.2

**Comment by rgolea** [comment]
@arnoud-dv I opened a PR. Hope it helps!

**Comment by arnoud-dv** [comment]
Fixed! Thanks @rgolea
