### ISSUE TITLE
Calling useQueries with an empty array leads to unlimited rerenders with the latest version of query

### ISSUE THREAD

**Issue by veithlukas** [TanStack/query#6645]
### Describe the bug

When passing an empty array to `useQueries` it leads to a rerender loop -> see reproduction example 

I think the same bug got also mentioned also in an unrelated other issue: https://github.com/TanStack/query/issues/6631#issuecomment-1875736135

### Your minimal, reproducible example

https://stackblitz.com/edit/vite-react-ts-effjcj?file=src%2FApp.tsx

### Steps to reproduce

See console for re-render loop :)

### Expected behavior

Re-render loop isn't expected... 

### How often does this bug happen?

Every time

### Platform

macOS Chrome 

### Tanstack Query adapter

react-query

### TanStack Query version

5.17.1

**Comment by richardkmiller** [comment]
If it's helpful, I'm also experiencing an infinite re-render loop when passing an empty array to useQueries() in 5.15.5. Works fine in 5.15.4.

**Comment by richardkmiller** [comment]
Thank you, @TkDodo!
