### ISSUE TITLE
NPM: eslint-plugin-query v4.38 tagged as latest

### ISSUE THREAD

**Issue by JamesBream** [TanStack/query#6655]
### Describe the bug

The most recent build of @tanstack/eslint-plugin-query **v4.38.0** has been tagged as latest on NPM despite being a patch release for the old v4 branch. This means that this version is being suggested as an upgrade from the 5.x versions in package managers (at least for me with yarn).

Guessing it's just the v4 publish pipeline that hasn't been updated since v5 shipped.

### Your minimal, reproducible example

N/A

### Steps to reproduce

1. Install @tanstack/eslint-plugin-query@latest
2. Check installed version is 4.38.0

### Expected behavior

I expected 5.17.1 to be the version installed with the latest tag.

### How often does this bug happen?

Every time

### Platform

- OS: macOS 14.2.1 - Node: 18.18.2 - Yarn: 4.0.2

### Tanstack Query adapter

None

### TanStack Query version

5.17.1

**Comment by TkDodo** [comment]
I think this needs to be fixed in the config package. @crutchcorn @lachlancollins FYI. Publishing an older major shouldn't tag as latest. I think right now every release tags as latest. 

as a workaround for now, I'll trigger a new v5 patch release so that it becomes latest again.

**Comment by lachlancollins** [comment]
Fixed here: https://github.com/TanStack/config/pull/24

The bug already existed in the query repo before we replaced the config!
