### ISSUE TITLE
[vue-query] Nuxt2 SSR demo not working as expected

### ISSUE THREAD

**Issue by worldzhao** [TanStack/query#6668]
### Describe the bug

I followed the documentation at https://tanstack.com/query/v4/docs/vue/guides/ssr#nuxt-2 to integrate vue-query into my nuxt@2 project. However, I encountered an error in the onServerPrefetch function stating that it must be run within the setup function. How can I fix this issue?

```javascript
onServerPrefetch(async () => {
  const queryClient = useQueryClient();
  const { ssrContext } = useNuxtApp();
  await suspense();
  ssrContext.nuxt.vueQueryState = dehydrate(queryClient);
});
```

<img width="258" alt="image" src="https://github.com/TanStack/query/assets/25662450/55637e18-518b-4bf7-a059-ddb0e15d204a">

- nuxt: 2.17.2
- vue: 2.7.16
- @tanstack/vue-query: 4.37.1

### Your minimal, reproducible example

https://stackblitz.com/edit/nuxt-starter-avjdeh?file=pages%2Findex.vue

or this repo: https://github.com/worldzhao/nuxt2-vue-query4-issue-20240110

### Steps to reproduce

1. Go to [stackblitz](https://stackblitz.com/edit/nuxt-starter-avjdeh?file=pages%2Findex.vue)
2. Run `npm i`
3. **Run `npx vue-demi-fix`(limitation of stackblitz)**
4. Run `npm run dev`
5. You can see the error.

### Expected behavior

Nuxt2 SSR demo working as expected

### How often does this bug happen?

None

### Screenshots or Videos

<img width="1475" alt="image" src="https://github.com/TanStack/query/assets/25662450/fc70bca3-b60c-4157-88f0-eef21d57db10">

### Platform

- OS: MacOS
- Browser: Chrome

### Tanstack Query adapter

vue-query

### TanStack Query version

v4.37.1

**Comment by worldzhao** [comment]
Should I move useQueryClient and useNuxtApp outside of the onServerPrefetch callback, and could there be any unforeseen consequences of doing so?

<img width="570" alt="image" src="https://github.com/TanStack/query/assets/25662450/53a07788-b6d6-4b72-9f62-6bdc1de56d74">

Additionally, `~/plugins/vue-query.js` should use `context.nuxtState.vueQueryState` (to stay consistent with `ssrContext.nuxt.vueQueryState`) instead of `context.nuxtState['vue-query']`.

<img width="872" alt="image" src="https://github.com/TanStack/query/assets/25662450/a19778b7-3c70-45cd-923c-da23d89989d2">

<img width="801" alt="image" src="https://github.com/TanStack/query/assets/25662450/68b8103f-ffb0-48e3-a1aa-56088a512bce">

**Comment by DamianOsipiuk** [comment]
As you have noticed docs have an error as state `key` should be the same.

As for the error, moving `useQueryClient` outside of `onServerPrefetch` should fix the issue.

If that works for you, you might want to open a PR fix this issue in the docs.

**Comment by worldzhao** [comment]
> As you have noticed docs have an error as state `key` should be the same.
> 
> As for the error, moving `useQueryClient` outside of `onServerPrefetch` should fix the issue.
> 
> If that works for you, you might want to open a PR fix this issue in the docs.

done. https://github.com/TanStack/query/pull/6702
