### ISSUE TITLE
What about Svelte 5?

### ISSUE THREAD

**Issue by frederikhors** [TanStack/query#6674]
After opening https://github.com/TanStack/query/discussions/6673 I thought it was time to consider the imminent arrival of [Svelte 5](https://svelte.dev/blog/runes).

All news are beautiful explained here: https://svelte-5-preview.vercel.app/docs/introduction.

How do we plan to do it?

I think we can finally close bug like:

- https://github.com/TanStack/query/issues/5913
- https://github.com/TanStack/query/issues/5855

**Comment by lachlancollins** [comment]
Everything in Query v5 should continue to work, since Svelte 5 is fully backwards compatible. A future Query version (v6?) will migrate from stores to runes.

**Comment by niemyjski** [comment]
@lachlancollins is there an issue tracking the runes migration. It's been a huge pain working with derived queries with runes. Like a massive pain.

**Comment by lachlancollins** [comment]
> @lachlancollins is there an issue tracking the runes migration. It's been a huge pain working with derived queries with runes. Like a massive pain. It would be great to start a discussion on this. I feel like this issue works for that.

Hi @niemyjski, see this PR: https://github.com/TanStack/query/pull/6981

**Comment by niemyjski** [comment]
@lachlancollins I replied here wondering if it's the correct approach and what was left. https://github.com/TanStack/query/pull/6981#issuecomment-2121243912

**Comment by lachlancollins** [comment]
Hi @frederikhors , I've merged #6981 into https://github.com/TanStack/query/tree/svelte-5-adapter

It's still not ready for release, but I would appreciate more people giving it a try and contributing!

**Comment by lachlancollins** [comment]
We should probably continue discussion here: https://github.com/TanStack/query/discussions/7413
