### ISSUE TITLE
isFetchingNextPage is not always true in the next render cycle after fetchNextPage is called

### ISSUE THREAD

**Issue by yarokon** [TanStack/query#6689]
### Describe the bug

`isFetchingNextPage` should be set to `true` after `fetchNextPage` is called to prevent fetching the same page in the next render cycle.  As a result, sometimes we are fetching the same page twice or event three times.

### Your minimal, reproducible example

[CodeSandbox](https://codesandbox.io/p/sandbox/use-infinite-query-issue-5ng3pq)

### Steps to reproduce

1. Open [CodeSandbox](https://codesandbox.io/p/sandbox/use-infinite-query-issue-5ng3pq)
2. Open "Preview console"
3. Refresh the page
4. Scroll down (fast)
5. You should see `2 fetched 100 - 200`. That means that page with items from 100 to 200 was fetched twice

Note: this issue is less reproducible if define `useInfiniteQuery` and `useVirtualizer` in the same component (example: [VirtualListWithBranches](https://codesandbox.io/p/sandbox/use-infinite-query-issue-5ng3pq?file=%2Fsrc%2Fcomponents%2FVirtualListWithBranches.tsx%3A1%2C2)) 

### Expected behavior

`isFetchingNextPage` should block `fetchNextPage` method in the next render cycle if the next page is currently fetching

```
if (!isFetchingNextPage) {
  fetchNextPage();
}
```

### How often does this bug happen?

Sometimes

### Screenshots or Videos

https://github.com/TanStack/query/assets/4423716/dffc4263-b272-4671-a6c7-19137bd7a044

### Platform

- OS: macOS
- Browser: Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

v5.17.9

### TypeScript version

v5.2.2

### Additional context

This issue is easier reproducible with a complex UI (more components, `useInfiniteQuery` props are passing through several components). In this case, you can easily fetch even three identical pages with slow scrolling.

**Comment by TkDodo** [comment]
I can't reproduce this in the sandbox and your video doesn't play for me ...

**Comment by yarokon** [comment]
@TkDodo, try opening the video in a different browser. The example is reproducible, but it may require several attempts to see the issue.

**Comment by TkDodo** [comment]
interesting. so I added another log that just imperatively reads `queryClient.isFetching()` right before calling `fetchNextPage`, and we can really see that it's already at `1` (which means there is a fetch going on) while the `fetchNextPage` variable is still at `false`:

```
 invoking fetchNextPage(), isFetching is 0
  fetchBranches()
 isFetchingNextPage: ❌
 invoking fetchNextPage(), isFetching is 1
  fetchBranches()
4 isFetchingNextPage: ✅
2 fetched 200 - 300
```

This could be because we batch updates to observers together to avoid frequent renders, but in this case, where every minimal scroll seems to trigger a re-render, this could interfer.

We allow overriding how we batch things in the latest v5 version with [notifyManager.setScheduler](https://tanstack.com/query/v5/docs/react/reference/notifyManager#notifymanagersetscheduler)

I tried setting it to not batch at all with:

```
notifyManager.setScheduler((cb) => cb());
```

and I haven't been able to reproduce the issue since.

You can also try `requestAnimationFrame` or `queueMicrotask` to see if that yields better results for you over our default settings.

**Comment by yarokon** [comment]
Thanks, @TkDodo. Batching with `setTimeout(callback, 0)` as a default setting was the main reason why `isFetchingNextPage` wasn't updated in the next render cycle. `cb = cb()` works in 100% of cases 🎉, and `requestAnimationFrame` and `queueMicrotask` also work almost perfectly (I only saw one parallel request among 200 pages).

Would it be possible to apply this setting to just one query, not the entire project? If yes, how can it be done? If no, is it safe to use the `requestAnimationFrame` or `queueMicrotask` option for the entire project?

P.S. Also, it would be good to mention it here: [TanStack Infinite Scroll](https://tanstack.com/virtual/v3/docs/examples/react/infinite-scroll)

**Comment by TkDodo** [comment]
> Would it be possible to apply this setting to just one query

not possible, because it's about batching updates together, and that doesn't happen on a per-query level.

> is it safe to use the requestAnimationFrame or queueMicrotask option for the entire project?

absolutely - any batching mechanism is okay. Some might result in more re-renders than others. We might switch default in a future major, but that's not decided.
