### ISSUE TITLE
`clear()` function does not clear the cache

### ISSUE THREAD

**Issue by enheit** [TanStack/query#6700]
### Describe the bug

The `clear()` function from the [useQueryClient](https://tanstack.com/query/latest/docs/react/reference/useQueryClient) does not clear the cache

```ts
// NOT working example
function Foo() {
  const { clear } = useQueryClient()

  function clearCache() {
    clear()
  }
}

```

But. The `queryClient.clear()` function from `export const queryClient = new QueryClient()` clears it.

```ts
// Working example
import { queryClient } from "./query-client"

function Foo() {
  function clearCache() {
    queryClient.clear() // Works fine
  }
}

```

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/vigilant-archimedes-slfkl3?file=%2Fsrc%2FMain.tsx%3A12%2C24

### Steps to reproduce

1. Open the CodeSandbox
2. Click the "Logout" button
3. Open the LocalStorage and see that `clientState.queries` inside `REACT_QUERY_OFFLINE_CACHE` is not empty (even after 1 second delay)
4. Open the DevTool and click the clear cache button.
5. Now the `clientState.queries` inside `REACT_QUERY_OFFLINE_CACHE` is empty

### Expected behavior

The cache must be cleared regardless of where the `clear()` function was used

### How often does this bug happen?

Every time

### Platform

- OS: Linux
- Browser: FireFox (121.0.1 (64-bit))

### Tanstack Query adapter

react-query

### TanStack Query version

v5.17.10

### TypeScript version

v5.2.2

### Additional context

Please note that the provided link to the CodeSandbox throws an error (after clicking the "Logout" button) for some reason, but it should be sufficient to understand the context of the problem

**Comment by TkDodo** [comment]
> const { clear } = useQueryClient()

you can't destruct the queryClient because it's a class. It's the same as:

``
const { getDay } = new Date()
getDay() // 💥
```

that's just not how classes work in JavaScript, and you can see that the `queryClient` is a class because you have to create it with `new QueryClient()`
