### ISSUE TITLE
ReactQueryDevtoolsPanel is not exported from "@tanstack/react-query-devtools"  or the docs are wrong 

### ISSUE THREAD

**Issue by itshallrun** [TanStack/query#6711]
### Describe the bug

I am trying to use the ReactQueryDevTools in the embedded mode as explained in the docs:
[@tanstack/react-query-devtools" has no exported member named ReactQueryDevtoolsPanel
](https://tanstack.com/query/v4/docs/react/devtools#embedded-mode)

But I get the error: 
@tanstack/react-query-devtools" has no exported member named ReactQueryDevtoolsPanel

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/react-query-devtoolspanel-reproduction-sthyww

### Steps to reproduce

Try to  import { ReactQueryDevtoolsPanel } from '@tanstack/react-query-devtools'

### Expected behavior

ReactQueryDevtoolsPanel is exported from '@tanstack/react-query-devtools'

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/21173275/9ecbe11d-455b-44f0-8538-ebcb38aed445)

### Platform

    "@tanstack/eslint-plugin-query": "^5.17.7",
    "@tanstack/react-query": "^5.17.12",
    "@tanstack/react-query-devtools": "^5.17.12",

### Tanstack Query adapter

react-query

### TanStack Query version

5.17.12

### TypeScript version

5.2.2

### Additional context

no other context needed

**Comment by itshallrun** [comment]
Looks like the latest version does not support the ReactQueryDevtoolsPanel, is that on purpose?

**Comment by TkDodo** [comment]
we already have a discussion for this:

- https://github.com/TanStack/query/discussions/6564
