### ISSUE TITLE
<useSuspenseQuery> queryClient?: QueryClient cause infinite loop

### ISSUE THREAD

**Issue by agongi** [TanStack/query#6727]
### Describe the bug

when queryClient is provided in useSuspenseQuery or useSuspenseQueries manually, this causes infinite rendering.
queryClient that is obtained via useQueryClient() is working 

```tsx
// external packages so useQueryClient() hooks could not be used
const queryClient = new QueryClient()

const {data} = useSuspenseQuery({
    queryKey: [`KEYS`],
    queryFn: () => axios.get(`URL`)
        .then(response => response.data)
}, queryClient) // ==> this cause infinite loop
```

In mycase, queryClient is not reusable using <QueryClientProvider ...> --- useQueryClient() due to logic defined outside of main project

### Your minimal, reproducible example

NONE

### Steps to reproduce

described above

### Expected behavior

described above

### How often does this bug happen?

Every time

### Platform

macOS: 14.2.1

### Tanstack Query adapter

react-query

### TanStack Query version

v5.17.15

### TypeScript version

v5.2.2

**Comment by TkDodo** [comment]
please show a reproduction. Is the `queryClient` stable ?

**Comment by agongi** [comment]
My bad. your view is correct.
I did like this:

```tsx
// external
export const cachedQueryClient = () => new QueryClient({
    defaultOptions: {
        queries: {
            staleTime: MINUTES * 15,
            throwOnError: true
        },
    },
})

// App
const {data} = useSuspenseQuery({
    queryKey: [`KEYS`],
    queryFn: () => axios.get(`URL`)
        .then(response => response.data)
}, cachedQueryClient()) // ==> this cause infinite loop
```

every rendering new queryClient is provided that causes infinite
