### ISSUE TITLE
unexpected caching when `queryKey` is undefined

### ISSUE THREAD

**Issue by KutnerUri** [TanStack/query#6728]
### Describe the bug

When running useQuery with no `queryKey` (ie `queryKey = undefined`), cached result is shared with all queries having `queryKey = undefined`! This is especially confusing because it happens even when useQuery is `enabled: false`.

I understand it is technically the same queryKey, but I would expect caching to be disabled when queryKey is undefined.
Shouldn't `undefined` be an invalid?
(type is currently `(string | number)[] | undefined`)

### Your minimal, reproducible example

👉 [CodeSandbox](https://codesandbox.io/p/sandbox/usequery-undefined-bug-reproduction-3dsk5q?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrj479b800063b6gihtpg44i%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrj479b800023b6gzpc3kd36%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrj479b800033b6g5qjt6x4i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrj479b800053b6g6rzz5ur3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrj479b800023b6gzpc3kd36%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrj479b800013b6gr8g6h8k8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clrj479b800023b6gzpc3kd36%2522%252C%2522activeTabId%2522%253A%2522clrj479b800013b6gr8g6h8k8%2522%257D%252C%2522clrj479b800053b6g6rzz5ur3%2522%253A%257B%2522id%2522%253A%2522clrj479b800053b6g6rzz5ur3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrj479b800043b6gl2shgr8l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522ASSISTANT_CHAT%2522%252C%2522chatId%2522%253A%2522clrj4cqto00i23b6gou252iju%2522%252C%2522id%2522%253A%2522clrj4cqtr00i43b6gjh9mdamq%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrj479b800043b6gl2shgr8l%2522%257D%252C%2522clrj479b800033b6g5qjt6x4i%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrj479b800033b6g5qjt6x4i%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. make two queries without queryKey
2. execute the first, disable the second
3. see both have the same value

### Expected behavior

Skip caching when no queryKey is supplied

-or-

prevent `queryKey: undefined`. (like we are required to use `queryKey: [1]` and not `queryKey: 1`)
(Might already be blocked in v5? not sure)

### How often does this bug happen?

Every time

### Platform

- MacOs 14.2.1
- Chrome 120

### Tanstack Query adapter

react-query

### TanStack Query version

4.28.0 (also happens in codesandbox using v5.17

### TypeScript version

4.9.5

### Additional context

-

**Comment by TkDodo** [comment]
queryKey is most definitely required on useQuery:

https://github.com/TanStack/query/blob/96cdb28d311772774323c05a75372ed05eedfde8/packages/react-query/src/types.ts#L24

We don't guard against any input that isn't valid typescript

**Comment by KutnerUri** [comment]
@TkDodo - I think it might be a problem with `^4.x.x`, I only get a typescript error in `v5`.
Maybe patch v4 to prevent undefined queryKey?

**Comment by TkDodo** [comment]
can you show a typescript playground please ?

**Comment by TkDodo** [comment]
you are right, this doesn't error:

```
useQuery({
    queryKey: undefined
})
```

but this does:

```
useQuery(undefined)
```

https://www.typescriptlang.org/play?ssl=7&ssc=20&pln=7&pc=1#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ5wC+cAZlBCHAOQACMAhgHaoMDGA1gPRTr2swBaAI458VOJ05wYeMOlQAuOADcALACh1aLKLwAKBOrjG4I3HgDS6PEuSMAJuhLBG6e+sIBKTduzm9do7OrvbeQA

**Comment by KutnerUri** [comment]
I love not being wrong. :p
it should be as simple as making `queryKey` non-optional, no?
