### ISSUE TITLE
useQueries returns error if provided array is empty

### ISSUE THREAD

**Issue by mrbuslov** [TanStack/query#6729]
### Describe the bug

If you run simple code below (in "how to reproduce" section)
  You'll receive error:
`  Cannot read properties of undefined (reading 'map')`

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/strange-meninsky-42rk2c?file=%2Fsrc%2Findex.js

### Steps to reproduce

Run this code
```
  const fetchPlanets = async (page) => {
    const res = await fetch(`https://swapi.dev/api/planets/?page=${page}`);
    return res.json();
  };
  const userQueries = useQueries(
    []?.map(val => {
      return {
        queryKey: ['val', val],
        queryFn: () => fetchPlanets(val),
      }
    }) ?? []
  )
```

### Expected behavior

If array is empty, should not execute anything.
Or better set enabled parameter, as in useQuery.

### How often does this bug happen?

None

### Platform

- OS: Linux Mint

### Tanstack Query adapter

None

### TanStack Query version

5.17.12

**Comment by mrbuslov** [comment]
The docs provide the solution for avoiding this error
https://tanstack.com/query/v4/docs/react/guides/dependent-queries#usequeries-dependent-query
But why not to make the check inside of useQueries?

**Comment by TkDodo** [comment]
useQueries takes an object with a `queries` property, not a top-level array as input
