### ISSUE TITLE
Don't work with Next.js 14.1.0

### ISSUE THREAD

**Issue by Kiborgik** [TanStack/query#6732]
### Describe the bug

 ⨯ ./node_modules/@tanstack/react-query-devtools/build/modern/devtools.js
Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').

Import trace for requested module:
./node_modules/@tanstack/react-query-devtools/build/modern/devtools.js
./node_modules/@tanstack/react-query-devtools/build/modern/index.js
./components/Utils/Providers.tsx
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ⨯ ./node_modules/@tanstack/react-query-devtools/build/modern/devtools.js
Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').

Import trace for requested module:
./node_modules/@tanstack/react-query-devtools/build/modern/devtools.js
./node_modules/@tanstack/react-query-devtools/build/modern/index.js
./components/Utils/Providers.tsx
 ⨯ ./node_modules/@tanstack/react-query/build/modern/HydrationBoundary.js
Attempted import error: 'useState' is not exported from 'react' (imported as 'React').

Import trace for requested module:
./node_modules/@tanstack/react-query/build/modern/HydrationBoundary.js
./node_modules/@tanstack/react-query/build/modern/index.js
./components/Utils/Providers.tsx
 ⨯ ./node_modules/@tanstack/react-query-devtools/build/modern/devtools.js
Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').

Import trace for requested module:
./node_modules/@tanstack/react-query-devtools/build/modern/devtools.js
./node_modules/@tanstack/react-query-devtools/build/modern/index.js
./components/Utils/Providers.tsx

### Your minimal, reproducible example

no

### Steps to reproduce

my Provider.tsx
```
'use client'

import { SessionProvider } from 'next-auth/react'
import { ReactQueryStreamedHydration } from '@tanstack/react-query-next-experimental'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { QueryClientProvider, QueryClient } from '@tanstack/react-query'
import { ReactNode, useState } from 'react'

export interface AuthContextProps {
	children: ReactNode
}

export default function Providers({ children }: AuthContextProps) {
	const [queryClient] = useState(
		() =>
			new QueryClient({
				defaultOptions: {
					queries: {
						//refetchOnWindowFocus: true,
						//refetchOnReconnect: true,
						staleTime: 1000 * 60
						//cacheTime: 1000 * 60 * 60 * 24 * 7,
					}
				}
			})
	)
	return (
		<QueryClientProvider client={queryClient}>
			<ReactQueryStreamedHydration>
				<SessionProvider>{children}</SessionProvider>
			</ReactQueryStreamedHydration>
			{<ReactQueryDevtools initialIsOpen={false} />}
		</QueryClientProvider>
	)
}
```

### Expected behavior

works

### How often does this bug happen?

None

### Platform

win

### Tanstack Query adapter

None

### TanStack Query version

5.17.15

### Additional context

"@tanstack/react-query": "^5.17.15",
"@tanstack/react-query-devtools": "^5.17.18",
"@tanstack/react-query-next-experimental": "^5.17.15",

**Comment by Kiborgik** [comment]
build and production: working
dev: not working

**Comment by tsnery** [comment]
In my case, the request remains in the "fetching" status infinitely

**Comment by TkDodo** [comment]
> Your minimal, reproducible example
no

YES. I'll re-open this once there is a reproduction

**Comment by Kiborgik** [comment]
@TkDodo why you are so toxic? Why need reproduction for obvious bug based on major update to framework. Anyway you will fix it near feature. Be proud, you closed this issue like a man, because someone doesn't have a reproduction for you

**Comment by TkDodo** [comment]
Imo the toxicity comes from people demanding time from open source maintainers without putting in the minimal required effort for themselves. Now you want me to create a nextJs14.1 project myself, and setup react query in the same way as you have to check if there is in even an issue on our end? Do you not think it's more likely that this is a nextJs issue rather than a React Query issue since nextJs just released a new version and it just so happens that you get errors like:

```
'useRef' is not exported from 'react' (imported as 'React').
```

as if I'm personally bundling react and leaving out `useRef` !? Just because the stack trace you're getting has `react-query` in there?

**Comment by Kiborgik** [comment]
@TkDodo I not demand anything. I showed error and problem. Please compare your first answer where you closed a issue depends on something what you don't like and the last answer. I am sorry if my issue triggered you. The problem maybe in next.js, but everything works without react query and as I mentioned in second comment everything works in build and production, but not in development.

Also I checked other open issues (like #6734) and only what I did wrong - put Provider.tsx at other place of issue, why you closed only my issue?

**Comment by TkDodo** [comment]
I closed the issue because it has no reproduction, and I also said I'll reopen it once there is a reproduction. We've had reports in the past where `useEffect` was missing in `React`, I spend time looking into it and it turned out that next had a different version of React for edge deployments and it was just a huge waste of my time.

If the issue is important to you, as it clearly is, create a codesandbox with next14 that shows the error.

**Comment by Kiborgik** [comment]
Yes it was a framework issue, to fix:
1. remove browserslist[] from package.json
2. delete .next folder
source(https://github.com/vercel/next.js/issues/60890#issuecomment-1900804381)

Have a nice day

**Comment by TkDodo** [comment]
I really hope you've learned your lesson and won't waste maintainers' time without a reproduction in the future. Consider sponsoring the TanStack to fund our work 🙏

**Comment by belgattitude** [comment]
Just landed here from the nextjs issue. Just want to share that personally this kind of comment I saw makes me feel sad. For what it’s worth, with experience and time, I learned that respect and empathy are incredibly important in life. 

Not sure if whatever I can say would help, but @TkDodo even if we don’t know each other, I really appreciate the work you’re doing and understand fully your point. Not to create debate, we’re all doing mistakes, and it’s ok. But let’s keep a vibrant, helpful, enthusiastic community around this project. It’s fun, it’s great and a lot to learn from. So thank you

**Comment by mateeyow** [comment]
FWIW to solve this issue you can install @tanstack/query-core as a dev dependency since pnpm does not resolve it properly especially if `preserveSymlinks` is set to true

**Comment by mvn-vietnguyen-dn** [comment]
@TkDodo 
Can you help me check this error? Thank you
<img width="334" alt="image" src="https://github.com/TanStack/query/assets/32171085/6c425ca9-07ff-452d-aa7c-2e95086bbc65">

**Comment by devdfan** [comment]
> @TkDodo Can you help me check this error? Thank you 🙇‍♂️ I'm using NextJS 14.0.4 and @tanstack/react-query ^5.18.0 <img alt="image" width="334" src="https://private-user-images.githubusercontent.com/32171085/307279338-6c425ca9-07ff-452d-aa7c-2e95086bbc65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTg3MTYsIm5iZiI6MTcxMDUxODQxNiwicGF0aCI6Ii8zMjE3MTA4NS8zMDcyNzkzMzgtNmM0MjVjYTktMDdmZi00NTJkLWFhN2MtMmU5NTA4NmJiYzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE2MDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNjBkNjVmMzk1Y2U4Yjc2MzJjODFjMWJlNDFmMjg0MzM3YWM2OTU0Yjk0N2JlMTI3ZGQwZDFkNDU2M2NhZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zRN_w3R5q2JyrPHI4V27UEPd2EWlRkxxpJvw0j9GiC4">

This solution helped me!

https://github.com/TanStack/query/issues/6560#issuecomment-1975771676
