### ISSUE TITLE
useQuery not reflecting updated queryFn while refetching after queryKey Invalidation

### ISSUE THREAD

**Issue by domenbukovac** [TanStack/query#6734]
### Describe the bug

I discovered a problem with the useQuery. When the `queryFn` that is passed to `useQuery()` is updated, the update is not reflected with the useQuery.

However this only happens when useQuery automatically refetches the data (eg. after queryKey is invalidated). Calling `refetch` provided by useQuery() would always refetch using the latest `queryFn`.

The reason for `queryFn` updating while the useQuery() is mounted is that fresh jwtToken that is used in the fetch expires after 20 minutes.

### Your minimal, reproducible example

no-example

### Steps to reproduce

App setup:
1. Create useGetUsersBooks hook

```
export function useGetUsersBooks({
  queryParams,
} {
  const { graphQlQuery } = useGraphQLClient(); // graphQlQuery wraps query for 

  const queryFn = async () => {
    return await graphQlQuery(getUsersBooksQuery, queryParams);
  };

  useEffect(() => {
    console.log("QueryFn fn changed");
  }, [queryFn]);

  return useQuery({
    queryKey: ["getUsersBook", queryParams.userId],
    queryFn,
  });
}
```

2. Create a screen BooksScreen
```
const BooksScreen = () => {
  const { data, refetch } = useGetUsersBooks({ queryParams: { userId: 1 } })
  const queryClient = useQueryClient();
  
  const onPressInvalidateQueryKey = () => {
    queryClient.invalidateQueries({  queryKey: ["getUsersBook", 1] })
  }  
  
  return (
    <View>
      <Text>{data.length}</Text>
      
      <Pressable onPress={onPressInvalidateQueryKey}>
        <Text>Invalidate query key</Text>
      </Pressable>
    
      <Pressable onPress={refetch}>
        <Text>Refetch manually</Text>
      </Pressable>
    </View>
  )
}
```

Steps:
1. Navigate to BooksScreen
2. Keep screen open (mounted) until the jwt token expires
3. Before jwt expires, your auth session handler should refetch new token and in effect `queryFn` will be updated as well — `useEffect(() => ...,[queryFn])` triggers and log "QueryFn fn changed".
4. Press on Invalidate query key (In the real app the would be implemented after a mutation)
5. useQuery would automatically (because query key was invalidated) refetch data using `queryFn`. However `queryFn` would use stale jwtToken and server would reject the request.
6. Press on "Refetch manually"
7. Calling `refetch()` from useQuery() would refetch using recent `queryFn` and refetch would succeed.

### Expected behavior

When manually calling `refetch()` from `useQuery()` the `queryFn` used to refetch the data is the one that was last updated ✅
However when the useQuery detects invalidated queryKey and automatically refetched the data, it does so using the `queryFn` that was provided to `useQuery()` when it was first mounted. ❌

### How often does this bug happen?

Every time

### Platform

- react-native 0.72.6
- react 18.2.0
- Android 14

### Tanstack Query adapter

react-query

### TanStack Query version

5.8.4

### TypeScript version

5.1.3

**Comment by TkDodo** [comment]
You're running into a stale closure issue because you're using something inside the queryFn that isn't part of the key. The fn only updates when the key changes.

if you want to read a jwt token, do it imperatively rather than with a hook. I never understood why tokens need to be part of the react component lifecycle - it really doesn't belong there but more in an interceptor.

**Comment by domenbukovac** [comment]
@TkDodo
Thank you for the explanation. I've taken your advice and implemented an interceptor using graphql-request middleware to handle the jwt token and auth headers. This change has successfully resolved the issue. 

**For anyone experiencing the similar issues**
The reason our token was part of the react component lifecycle is that we were using external library for managing auth session (`expo-keycloak-auth`). The problem is that its hook only provides jwtToken that lives in the context's state.  

Before, I had implemented graphQLClient Context  like so

```typescript
export const GraphQLClientProvider = ({
  graphQlUrl,
  children,
  token,
}) => {

  const client = useMemo(() => {
    return new GraphQLClient(graphQlUrl, {
      headers: {
        authorization: `Bearer ${token}`,
      },
    });
  }, [graphQlUrl, token]);

  const graphQlQuery = useCallback(
    async <TResult, TVariables>(query: string, variables?: TVariables): Promise<TResult> => {
      return graphQlClientQuery<TResult, TVariables>(client,  query, variables);
    },
    [client, setOffline]
  );


  const contextValue: GraphQLClientContextValue = useMemo(() => {
    return {
      graphQlQuery,
    };
  }, [graphQlQuery]);

  return (
    <GraphQLClientContext.Provider value={contextValue}>{children}</GraphQLClientContext.Provider>
  );
};
```

And I would wrap the app with the `graphQlClientProvider` while passing the `token` to it

```typescript
const { token } = useKeycloak();
 
return (
    <GraphQLClientProvider
      graphQlUrl={GRAPHQL}
      token={token}
    >
      <RootNavigator />
   </GraphQLClientProvider>
);
```

```typescript
const { graphQlQuery } = useGraphQLClient();
```

Implementation worked as expected - I would consume the graphQlQuery in a component and if token got updated while a component was mounted, `graphQlQuery` would be updated as well.


However, as it turns out, the `useQuery` only updates the `queryFn` when the `queryKey` prop changes as well. Adding token to `queryKey` wouldn't make sense as it would lead to losing cached data on token refresh.

To overcome this, I first had to modify expo-keycloak-auth to provide a getToken function, ensuring the token lives inside a ref to avoid closure issues:

```typescript
const tokenRef = React.useRef(currentToken);

useEffect(() => {
  tokenRef.current = currentToken;
}, [currentToken]);

const getToken = async (): Promise<string | null> => {
  return tokenRef?.current?.accessToken || null;
};

return (
    <KeycloakContext.Provider
      value={{
        // ...
        getToken,
      }}
    >
      {children}
    </KeycloakContext.Provider>
  );

```

Then I updated the GraphQLClientProvider to use `getToken` instead of a direct token. The key change was adding a request middleware to the GraphQLClient, which intercepts each query request and updates the headers with the fresh token:

```typescript

export const GraphQLClientProvider: React.FC<GraphQLClientProviderProps> = ({
  graphQlUrl,
  children,,
  getToken,
}) => {
  const requestMiddleware: RequestMiddleware = async (request) => {
    const token = await getToken();
    return {
      ...request,
      headers: { ...request.headers, authorization: `Bearer ${token}` },
    };
  };

  const client = useMemo(() => {
    return new GraphQLClient(graphQlUrl, {
      requestMiddleware,
    });
  }, [graphQlUrl]);

```

`getToken` is then passed to `GraphQLClientProvider`

```typescript
const { getToken } = useKeycloak();
 
return (
    <GraphQLClientProvider
      graphQlUrl={GRAPHQL}
      getToken ={getToken}
    >
      <RootNavigator />
   </GraphQLClientProvider>
);
```

This approach ensures the jwt token is always current, effectively resolving the closure problem we were facing.
