### ISSUE TITLE
ReactQueryStreamedHydration hydrated does not properly escape </script>

### ISSUE THREAD

**Issue by ammubhave** [TanStack/query#6735]
### Describe the bug

If the data that is being hydrated has a `</script>` anywhere in the text, then it breaks the web page.
Specifically, the rendered HTML does not escape the `</script>` causing the browser to prematurely end the tag.

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/young-cloud-pq72kc

### Steps to reproduce

Checked the linked codesandbox

1. Add ReactQueryStreamedHydration to your NextJS app.
2. Create an API endpoint that returns back text/json and has `</script>` in the response somewhere.
3. Use `useSuspenseQuery` to query that that endpoint.
4. Observe in the rendered HTML that the following is present
```
<script>
window["__RQ:R6kq:"] = window["__RQ:R6kq:"] || [];window["__RQ:R6kq:"].push({"mutations":[],"queries":[{...
...</script>...
}]})
</script>
```

The above is invalid HTML, notice that there is an unescaped `</script>` because it was present in the originally fetched data.

### Expected behavior

The rendered data should escape `</script>`, perhaps by searching for all instances of `</script>` and replacing with `<\/script>`

### How often does this bug happen?

Every time

### Platform

- Linux
- Browser: Chrome
- NextJS 14.0.4

### Tanstack Query adapter

None

### TanStack Query version

v5.17.10

### TypeScript version

v5.3.3

**Comment by TkDodo** [comment]
fixed by:

- https://github.com/TanStack/query/commit/f2ddaf2536e8b71d2da88a9310ac9a48c13512a1
