### ISSUE TITLE
[v4] Disallow undefined queryFn return in types

### ISSUE THREAD

**Issue by nathanforce** [TanStack/query#6757]
### Describe the bug

I'm in the midst of migrating a large codebase to v4 and misunderstood this line in the migration guide regarding queryFn returning `undefined`:

> This is now disallowed on type level; at runtime, undefined will be transformed to a failed Promise, which means you will get an error, which will also be logged to the console in development mode.

https://tanstack.com/query/v4/docs/react/guides/migrating-to-react-query-4#undefined-is-an-illegal-cache-value-for-successful-queries

Per my understanding of the types, returning `undefined` does not result in a type error. Is this a bug? or am I misunderstanding what "disallowed on type level" means? Is there a reason _not_ to adjust the typescript types such that returning undefined will result in a type error?

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/angry-rubin-279ggv?file=%2Fsrc%2FApp.tsx%3A26%2C1

### Steps to reproduce

```
const query = useQuery(
    ['my-query-key', param],
    () => {
         return;
    }
)
```

### Expected behavior

I'd expect Typescript to error on any queryFn that returns undefined

### How often does this bug happen?

Every time

### Platform

n/a

### Tanstack Query adapter

None

### TanStack Query version

4.36.1

### TypeScript version

4.5.4

**Comment by TkDodo** [comment]
I think we tried this but couldn't really pull it off. You'll get a warning in dev-mode at runtime.

**Comment by nathanforce** [comment]
I'd suggest maybe updating the migration guide to provide some clarity? In our case we have many hundreds of useQuery calls and manually reviewing them all is much more work than we previously thought.

**Comment by TkDodo** [comment]
sure, please PR to the docs if you want
