### ISSUE TITLE
React Query - SetQueryCache must follow with a refetch?

### ISSUE THREAD

**Issue by TomerLankri** [TanStack/query#6767]
### Describe the bug

I am using react query with nextJS. I set the stale time to 10 minutes so while I'm using the app I don't refetch without reason.

Now when i update data in my react query I set the data value in the query cache (SetQueryCache) - that does not invalidate the query (Say I have a list of tasks and i set one of them to done).

Now after i updated the data (Set a task to done) i refresh the page but i see the old data, only when i invalidate the query manually it fetches the correct date.

I am having the same issue with Delete but not with create.(Create gets updated and holds in refresh)

I thought using setQueryCache with the updated data let's react query know that it was changed but the data is not updated, how can i solve this?

I don't want to fetch data on the client side every time i update the queryCache. I would appriciate any help :)

SetQuery Cache -> updates the query cache does not need refetch. Actually does need

### Your minimal, reproducible example

i dont have one

### Steps to reproduce

(Set stale time to be high)
1. create query for tasks table from backend
2. update one task to be done
3. set in the query cache
4. refresh screen - see old data

### Expected behavior

to see new updated data (Task done) 

### How often does this bug happen?

Every time

### Platform

Macos 

### Tanstack Query adapter

react-query

### TanStack Query version

v3.30.1

### TypeScript version

v4.5.4

**Comment by TkDodo** [comment]
this "issue" needs a lot more info. There is no "setQueryCache" function. the in-memory cache is also not persisted per default, so unless you use a persister plugin, so when you refresh the page, everything is gone.

Please come back with a codesandbox reproduction.
