### ISSUE TITLE
Vue docs broken

### ISSUE THREAD

**Issue by Lovor01** [TanStack/query#6770]
### Describe the bug

Vue docs redirect to React

### Your minimal, reproducible example

...

### Steps to reproduce

1. go to docs
2. switch to vue
3. react version is shown (and URL)

### Expected behavior

Vue docs

### How often does this bug happen?

None

### Platform

irrelevant

### Tanstack Query adapter

None

### TanStack Query version

docs

**Comment by gabriel-enrique** [comment]
Issue #6772 might be related to this.

**Comment by Lovor01** [comment]
It might, it seems that solid and svelte have different docs, so these links are not broken, but for vue and angular are.

**Comment by lachlancollins** [comment]
This should be fixed by #6774 , but let me know if anything is still broken.

**Comment by Lovor01** [comment]
I am reopening this, since search for vue still does not work good. Try selecting vue framework, then using search and enter e.g. "useMutate". After selecting the first item in drop menu, redirect to start page of React happens.

**Comment by lachlancollins** [comment]
Sorry, there were issues with the Algolia search too.

This has been fixed in https://github.com/TanStack/tanstack.com/pull/162 and https://github.com/TanStack/tanstack.com/pull/163

Let me know if you are still having issues!
