### ISSUE TITLE
Broken links and urls

### ISSUE THREAD

**Issue by gabriel-enrique** [TanStack/query#6772]
### Describe the bug

Clicking the links in the `Helpers` table from https://trpc.io/docs/client/react/useUtils#helpers will redirect to https://tanstack.com/query/v5/docs/framework/react/overview instead of the actual intended urls.

Was browsing the docs about 5-6 hours ago, then now, all the links are broken. So the commit 0cdbd5a might be the cause of the problem.

### Steps to reproduce

1. Go to https://trpc.io/docs/client/react/useUtils#helpers
2. Try clicking the links under the `Helpers` table

### Expected behavior

Should go to the the actual link, instead of https://tanstack.com/query/v5/docs/framework/react/overview

### How often does this bug happen?

Every time

### Platform

- Browser: chrome

### Tanstack Query adapter

None

**Comment by lachlancollins** [comment]
Thanks for reporting @gabriel-enrique ! It is definitely related to that, I've submitted a PR to fix the links on the tRPC side, and I'll see if we can come up with a temporary workaround in https://github.com/TanStack/tanstack.com.

**Comment by TkDodo** [comment]
@lachlancollins this url:

https://tanstack.com/query/v5/docs/reference/QueryClient#queryclientfetchquery

now redirects to:

https://tanstack.com/query/v5/docs/framework/react/overview#queryclientfetchquery

which still isn't quite right

**Comment by lachlancollins** [comment]
Good point, I'll update these 👍

**Comment by lachlancollins** [comment]
Fixed in https://github.com/trpc/trpc/pull/5397
