### ISSUE TITLE
Queries with same key should not share the same effect

### ISSUE THREAD

**Issue by cuzfrog** [TanStack/query#6806]
### Describe the bug

#6801, there are related issues, but I don't think the current behavior is correct.

When 2 queries with the same key, a query's retry propagates/mirrors the effect to another query in a parent component, which will fall in an infinite loop of re-render/mount, apparently violating the flow direction.

### Your minimal, reproducible example

https://github.com/cuzfrog/retryOnMount-error-demo

### Steps to reproduce

see `README.md`

### Expected behavior

The effect seen by the components should be independent per hook.

### How often does this bug happen?

Every time

### Platform

- OS [22.04.1-Ubuntu]
- Browser [Chrome 120]

### Tanstack Query adapter

None

### TanStack Query version

5.18.0

### TypeScript version

5.2.2

**Comment by cuzfrog** [comment]
Given that you agree to change current behavior, I'm happy to create a PR.

**Comment by TkDodo** [comment]
when `Page` mounts, it sets the query, which is in error state by then, back to `loading` state, after which the parent unmounts the `Page` and then it goes back into error state, mounting the `Page`, triggering another refetch.

This is the "expected" behaviour if you mount children like that without error handling, and the default `retryOnMount: true` setting.

**Comment by TkDodo** [comment]
> the refetch triggered in the Page should only affect the loading in the Page not in the parent.

if you use the same `queryKey`, there is only one cache entry, and that entry goes into loading state, and all components that are interested in that state will be informed about it.

**Comment by cuzfrog** [comment]
loading should not be part of the shared cache. only data should be. loading is just a status from the initiator's perspective.

**Comment by TkDodo** [comment]
That might be what you want but it's not how it works because that's not how this lib was designed to work.
