### ISSUE TITLE
Docs: optimistic updates incorrect statement about invalidateQueries

### ISSUE THREAD

**Issue by swingthrough** [TanStack/query#6823]
### Describe the bug

In the docs for [optimistic updates](https://tanstack.com/query/latest/docs/framework/react/guides/optimistic-updates#via-the-ui)

There is this part with example code:

```
const { isPending, submittedAt, variables, mutate, isError } = useMutation({
  mutationFn: (newTodo: string) => axios.post('/api/data', { text: newTodo }),
  // make sure to _return_ the Promise from the query invalidation
  // so that the mutation stays in `pending` state until the refetch is finished
  onSettled: async () => {
    return await queryClient.invalidateQueries({ queryKey: ['todos'] })
  },
})
```

The statement:

> make sure to **_return_ the Promise from the query invalidation** so that the mutation stays in `pending` state until the refetch is finished

is incorrect, isn't it?

It should state:

> make sure to **_await_ the Promise inside the query invalidation** so that the mutation stays in `pending` state until the refetch is finished

Even if I don't return the expression, it stays in `pending` state. Would returning the awaited promise have any effect?
The only change would be that it returns the awaited value, [which in case of `invalidateQueries` is `void`](https://github.com/TanStack/query/blob/bfdd31fef0327820e5b83579342184ca24e3428d/packages/query-core/src/queryClient.ts#L253), so that would make no difference, would it?

### Your minimal, reproducible example

--

### Steps to reproduce

--

### Expected behavior

--

### How often does this bug happen?

None

### Platform

--

### Tanstack Query adapter

None

### TanStack Query version

v5

**Comment by TkDodo** [comment]
you need to return a promise from the callback that can be awaited internally. If you write an async function that calls `await`, it will implicitly return a Promise because that's how async functions work.
