### ISSUE TITLE
Embedded examples broken in documentation

### ISSUE THREAD

**Issue by jagregory** [TanStack/query#6828]
### Describe the bug

See:
- https://tanstack.com/query/v3/docs/framework/react/examples/simple
- https://tanstack.com/query/v3/docs/framework/react/examples/basic-graphql-request

<img width="744" alt="Screen Shot 2024-02-04 at 12 23 33 pm" src="https://github.com/TanStack/query/assets/10828/2fd24d29-f639-4c50-a607-494b28c87ce9">

### Your minimal, reproducible example

.

### Steps to reproduce

.

### Expected behavior

.

### How often does this bug happen?

None

### Platform

.

### Tanstack Query adapter

None

### TanStack Query version

.

**Comment by lachlancollins** [comment]
Fixed in #6912, thanks for reporting!
