### ISSUE TITLE
Docs: pagination example not working

### ISSUE THREAD

**Issue by sungh0lim** [TanStack/query#6832]
### Describe the bug

React Example: React/pagination page is not visible when connected.

https://tanstack.com/query/latest/docs/framework/react/examples/react/pagination

### Your minimal, reproducible example

https://tanstack.com/query/latest/docs/framework/react/examples/react/pagination

### Steps to reproduce

1. Open `https://tanstack.com/query/latest/docs/framework/react/examples/react/pagination` in browser.

### Expected behavior

1. Go to the tanstack query documentation page.
2. Search "React Example: React/pagination"

### How often does this bug happen?

None

### Screenshots or Videos

![스크린샷 2024-02-04 오후 4 21 09](https://github.com/TanStack/query/assets/70130721/a1714236-6c2c-44bd-ab24-a0f768886854)

### Platform

- Chrome Browser.

### Tanstack Query adapter

None

### TanStack Query version

v4, v5

**Comment by andrewbusch7** [comment]
Where did you get that URL from? If you click the Pagination link in the lefthand nav, it takes you to https://tanstack.com/query/latest/docs/framework/react/examples/pagination, which loads correctly:

![image](https://github.com/TanStack/query/assets/6486627/978f8cc4-a29c-4202-a8d3-5249b3789e0f)

Unrecognised paths do return an error, albeit a reasonable one:

![image](https://github.com/TanStack/query/assets/6486627/ec42b026-98a2-461a-8671-2f87d142a3fa)

**Comment by colbyfayock** [comment]
FYI - still seeing this, only mentioning because it looks like a fix was intended to be merged/deployed from what im gathering from the linked PR

<img width="1719" alt="image" src="https://github.com/TanStack/query/assets/1045274/72b10087-f3b4-4fcd-845a-7b945daf1da5">

**Comment by TkDodo** [comment]
@colbyfayock how did you get to this link? The correct link is:

https://tanstack.com/query/latest/docs/framework/react/examples/pagination

You should get there by navigating via the sidebar

**Comment by colbyfayock** [comment]
Google 😢 

<img width="871" alt="image" src="https://github.com/TanStack/query/assets/1045274/d8e129f4-4da9-4e9f-9e8b-590f715142a3">

```
https://tanstack.com/query/v4/docs/framework/react/examples/react/pagination
```

**Comment by colbyfayock** [comment]
just a note that the URL in the original issue was the same URL that if ound

BUT

I just found something interesting, if you use the site search, it does take you to this page. maybe the site search index needs refreshed as well (but dont know those details)

Video:
https://github.com/TanStack/query/assets/1045274/bcf969ab-4068-43f8-ad41-4926e7904a09
