### ISSUE TITLE
Mutation is not triggered when there is an optimistic update

### ISSUE THREAD

**Issue by DaliborHomola** [TanStack/query#6835]
### Describe the bug

When it's defined `onMutate`, `onError` and `onSettled` in `useMutation`, the `mutate` function doesn't trigger. 
This is exactly what's written in documentation under section optimistic updates/via the cache, but the mutation is not working.

### Your minimal, reproducible example

Code Sandbox

### Steps to reproduce

1. Go to [codesandbox](https://codesandbox.io/p/devbox/react-query-optimistic-cache-update-j525wl?file=%2Fsrc%2FApp.tsx%3A18%2C29&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls7pv78l0007356hi16hjogg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls7pv78k0002356hzb9fmovk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls7pv78k0004356hdbwsp0dv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls7pv78k0006356h7gg97qp5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls7pv78k0002356hzb9fmovk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls7pv78j0001356hgf6m1abp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cls7q0vlt0002356h4pbhyt3v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A18%252C%2522startColumn%2522%253A29%252C%2522endLineNumber%2522%253A18%252C%2522endColumn%2522%253A29%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls7pv78k0002356hzb9fmovk%2522%252C%2522activeTabId%2522%253A%2522cls7q0vlt0002356h4pbhyt3v%2522%257D%252C%2522cls7pv78k0006356h7gg97qp5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls7pv78k0005356hl3u9fz2m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls7pv78k0006356h7gg97qp5%2522%252C%2522activeTabId%2522%253A%2522cls7pv78k0005356hl3u9fz2m%2522%257D%252C%2522cls7pv78k0004356hdbwsp0dv%2522%253A%257B%2522id%2522%253A%2522cls7pv78k0004356hdbwsp0dv%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls7pv78k0003356hmt7h348n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cls7pv78k0003356hmt7h348n%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
2. Preview console and watch network.
3. Try to click button, which has mutate onClick (nothing happens).
4. Try delete `onMutate`, `onError` and `onSettled` in `useMutation`.
5. Refresh the page and click button (it mutates now!).

### Expected behavior

I'm expecting the mutation to be triggered.

### How often does this bug happen?

Every time

### Platform

Windows, Chrome

### Tanstack Query adapter

None

### TanStack Query version

5.18.1

### TypeScript version

4.9.5

**Comment by ardeora** [comment]
In your example, In App.tsx you are creating a new QueryClient with

`const queryClient = new QueryClient();`

Instead you should be using the queryClient available to the app. You can do that by using `useQueryClient` hook

Here is the example you posted fixed: 

https://codesandbox.io/p/devbox/react-query-optimistic-cache-update-forked-528xn4
