### ISSUE TITLE
Mutation cache, old mutations gets updated key and meta on state updates

### ISSUE THREAD

**Issue by gautemo** [TanStack/query#6839]
### Describe the bug

The `meta` and `mutationKey` on previous mutations get updated when state in a component is updated.
This only happens the first time the state updates and only on the last mutation in the cache.

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-pchfwb?file=src%2FApp.tsx

### Steps to reproduce

1. Click the button "Run mutation"
2. See the website list the mutation: "0 = 0 = 0 is true" ([value] = [key] = [meta] is [equal])
3. Click the button "Bump state"
4. See the website list the mutation: "0 = 1 = 1 is false"

### Expected behavior

I expect that all existing mutations should not be altered when some state updates.
Meaning step 4. should stay "0 = 0 = 0 is true".
Meaning that the mutation key and meta object should still hold the value `0` that was the value when the mutation happened.

### How often does this bug happen?

Every time

### Platform

- OS: Windows
- Browser: Edge
- Version: 119.0.2151.58

### Tanstack Query adapter

react-query

### TanStack Query version

5.18.1

### Additional context

You can also see the values being updated in the ReactQueryDevtools.

**Comment by gautemo** [comment]
I see it is fixed when the key is updated. But I would also assume `meta` should not be updated on old mutations. This is actually happening when a key is missing or the same.

## Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-jpzeoh?file=src%2FApp.tsx

## Steps to reproduce

1. Click the button "Run mutation"
2. See the website list the mutation: "0 = 0 is true" ([value] = [meta] is [equal])
3. Click the button "Bump state"
4. Click the button "Bump state"
5. See the website list the mutation: "0 = 2 is false"

## Expected behavior

I expect that all existing mutations should not be altered when some state updates.
Meaning step 5. should stay "0 = 0 is true".
Meaning that the meta object should still hold the value 0 that was the value when the mutation happened.

Does my reasoning and what I expect sound okay, @TkDodo? Also not that meta is only updated every second time, bug is not triggered on odd number of "Bump state" clicks.

**Comment by TkDodo** [comment]
the currently observed mutation will get updates, I think that's expected. Otherwise, we would run into stale closure issues, like the one we fixed here:
- https://github.com/TanStack/query/issues/5056

we _could_ maybe not update the mutation if it is already completed ? If you want to contribute this, I think another check here would be needed:

https://github.com/TanStack/query/blob/61f4d747883ce67cf4edcc65f9a7693fa2bc7b6a/packages/query-core/src/mutationObserver.ts#L77
