### ISSUE TITLE
Unable to type the `useMutationState` hook

### ISSUE THREAD

**Issue by koen-dev** [TanStack/query#6843]
### Describe the bug

When using the `useMutationState` hook and filtering on a specific `mutationKey` I want to be able to type the result accordingly as I know what data to expect. However when using the provided ways to type the hook I end up with a TS error.

```tsx
// Another place we could define the result type however this would also result in a TS error.
// const result = useMutationState<TestResult | undefined>({
const result = useMutationState({
  filters: {
    mutationKey: testMutationKey,
  },
  // Because we filter by mutationKey, we know what data to expect. However this results in a TS error.
  // A current workaround is casting the result to TestResult | undefined
  select: (data: Mutation<TestResult>) => data.state.data,
});
```
```
Type '(data: Mutation<TestResult>) => TestResult | undefined' is not assignable to type '(mutation: Mutation<unknown, Error, unknown, unknown>) => TestResult | undefined'.
  Types of parameters 'data' and 'mutation' are incompatible.
    Type 'Mutation<unknown, Error, unknown, unknown>' is not assignable to type 'Mutation<TestResult, Error, void, unknown>'.
      Types of property 'state' are incompatible.
        Type 'MutationState<unknown, Error, unknown, unknown>' is not assignable to type 'MutationState<TestResult, Error, void, unknown>'.
          Type 'unknown' is not assignable to type 'TestResult'.
```

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/tanstack-query-use-mutation-state-2955yh

### Steps to reproduce

1. Setup `useMutation` with a `mutationKey` and a correct type definition
2. Setup `useMutationState` that uses the above created `mutationKey` and type definition (multiple options available see CodeSandbox)

### Expected behavior

As a developer, I expected the ability to correctly type the select function of `useMutationState` and the ensure the result type matches my expectation.

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 121.0.6167.139

### Tanstack Query adapter

react-query

### TanStack Query version

5.18.1

### TypeScript version

5.3.3

### Additional context

I've had a short interaction with @TkDodo on [X](https://twitter.com/koen_dev/status/1752354629755498886), however I only just now found the time to create an issue and reproducible example. I wanna make sure that this might still be an user error on my side 🙈

**Comment by TkDodo** [comment]
contrary to what I said on twitter, this can't work. There's no type narrowing happening between `filter` and `select`. You might know that data is of a specific type, but TS can't.

The type assertion is fine because it explicitly states that you know better than the compiler :)

https://www.typescriptlang.org/play?#code/ATCWFsAcHsCcBdgG9gFcDOBTAsq+BDeUaAOwGUD5MAaYXS4k4AX2ADNZpxgByAAQIl0BAMYBrAPSxM+EfAC0AR1SZYATx4AoTSHhrImYABVMwgEqnUAG0QBeZDvbRoALmDDYoEgHMA3I4AjfFg3ElRwANV-Zn8QRxFSYWBpdGs7NCx6QkYKQkwACiRHEDZQG1V0NyKQGuBwPGzSAGlMNTcAbR4qYSyiZtaeAF1qYpYR2qwrTDk3fIATQnwASmBbAD5gBYIAOmE87a38YHx0Y1N4C1SbYAAfNBI5zFKSTDnxliXfIA
