### ISSUE TITLE
[svelte-query] derived `$page.params` store will becomes undefined during client side navigation

### ISSUE THREAD

**Issue by ivenuss** [TanStack/query#6845]
### Describe the bug

When using params from SvelteKit $page store, they suddenly become undefined during navigation. (navigating out of page, where they're used along with createQuery).

### Error
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toUpperCase')
```

Stores should be derived according to docs: https://tanstack.com/query/latest/docs/framework/svelte/reactivity

### FYI
When derived function isn't wrapped with createQuery function, then $page.params.name no longer becomes on navigation.

### Simple reproduction

`src/routes/test/[name]/+page.svelte`
```svelte
<script lang="ts">
  import { createQuery } from '@tanstack/svelte-query';
  import { derived } from 'svelte/store';
  import { page } from '$app/stores';

  const noop: (..._args: unknown[]) => any = () => {};

  const test = createQuery(
    derived([page], ([$page]) => ({
      queryFn: noop,
      enabled: !!$page.params.name.toUpperCase(),
    })),
  );
</script>
```

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-query-br7kae?file=src%2Froutes%2Ftest%2F%5Bname%5D%2F%2Bpage.svelte

### Steps to reproduce

1. Visting testing page, for example `/test/anything`
2. Navigate from testing page using the `"Go to home page"` button
3. During the client navigation to the home page, $page.params will become undefined and this will throw an error in console

### Expected behavior

`$page.params` shouldn't become undefined during the navigation

### Platform

MacOS, Google Chrome

Svelte: `4.2.7`
SvelteKit: `2.0.0`
Vite: `5.0.3`

### Tanstack Query adapter

Svelte -> SvelteKit

### TanStack Query version

5.18.1

### TypeScript version

5.0.0

**Comment by TkDodo** [comment]
@lachlancollins fyi

**Comment by lachlancollins** [comment]
Hi @ivenuss , I don't believe this is a Query problem, since `$page` is a SvelteKit feature. You could fix this with optional chaining, e.g. `!!$page.params.name?.toUpperCase()`. Also, since you're just converting to a boolean, you could just simplify it as `!!$page.params.name`.

**Comment by lachlancollins** [comment]
Hi @ivenuss , I'm still a bit unsure about what the issue is from this repro but I think that's a me problem. Either way, the ergonomics of using this adapter will hopefully be significantly improved once #6981 is released.
