### ISSUE TITLE
Homepage is erroring

### ISSUE THREAD

**Issue by MichaelDimmitt** [TanStack/query#6852]
### Describe the bug

The following url's are failing with internal server errors
https://tanstack.com/query/latest
https://tanstack.com/

see images attached.

![homepage1](https://github.com/TanStack/query/assets/11463275/5b9101a3-38ec-474d-a934-bdf1476bed03)

![homepage2](https://github.com/TanStack/query/assets/11463275/10448686-5f2c-4447-814d-701af29659a8)

### Your minimal, reproducible example

N/A

### Steps to reproduce

navigate to:
https://tanstack.com/

### Expected behavior

Homepage should load.

### How often does this bug happen?

Every time

### Platform

- OS Windows

### Tanstack Query adapter

None

### TanStack Query version

v5.18.1

### Additional context

Time - 5:08PM Eastern Time, USA

**Comment by MichaelDimmitt** [comment]
Also confirmed on Mac environment

**Comment by andrewbusch7** [comment]
Seems to be fixed now

**Comment by MichaelDimmitt** [comment]
confirmed working
