### ISSUE TITLE
Vue.js example in the docs doesn't work

### ISSUE THREAD

**Issue by mlodyoskar** [TanStack/query#6854]
### Describe the bug

When you enter [tanstack.com/query/latest](https://tanstack.com/query/latest) and scroll down to the examples section and choose Vue.js, there's an error. It points to the non-existing repository in the examples/vue/simple directory.

### Your minimal, reproducible example

https://tanstack.com/query/latest#:~:text=Less%20code%2C%20fewer%20edge%20cases.

### Steps to reproduce

1. Go to https://tanstack.com/query/latest
2. Scroll down to examples section
3. Choose Vue examples

### Expected behavior

As a user I can see Vue.js examples of tanstack-query on https://tanstack.com/query/latest

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/45982530/f0ae24a2-367b-4160-bd0b-dd20ecc5fe14)

### Platform

Chrome 121, macOS 14.3 but I guess it's not related

### Tanstack Query adapter

vue-query

### TanStack Query version

not related

**Comment by mlodyoskar** [comment]
I've realised now that I should've opened this issue in the tanstack.com repository. If so then close this issue and I will create a new one in correct repo and fix it later

**Comment by Mini-ghost** [comment]
@TkDodo @DamianOsipiuk 
I'd like to solve this issue, would you mind assigning this issue to me?
