### ISSUE TITLE
The object passed to the `queryFn` should be typed as `QueryFunctionContext` when using `useQueries`

### ISSUE THREAD

**Issue by troywoy** [TanStack/query#6880]
### Describe the bug

The `context` isn't typed as `QueryFunctionContext` in a `useQueries` `queryFn`.

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1WO1OAXzgDMoIQ4ByAARgEMA7VRgYwGsB6KdBtmAFoAjjigBPagCgppZEwHAITOAEEwYABQBKRFLhw2y1mXQw2AC1UATa71SEAvHE2pgAcyYMANgC41AEbQMADKHl7e2v6seEzucI4AfHoGBrwwyFAq1AAyzOhwAIzUANz6xGXlRizwaOiqsMCsTi66SSmp6Zkqddi4+KiaCOWpcKL9BL4jo3AA2tMzHYuj4xIA0uji-rPUDLb2qNQAugA0C8ur4gBiTP6aAgAebcmkZpY2dgSDjwB0bp4+bRnZapIjnAxHaZEbTlMFgoA

### Steps to reproduce

1. Open typescript playground
2. Notice `ctx` has type `any`

### Expected behavior

As a user, I expect `context` to be of type `QueryFunctionContext`.

### How often does this bug happen?

Every time

### Platform

- OS: Windows
- Browser: Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

v5.17.1

### TypeScript version

v5.3.3

**Comment by TkDodo** [comment]
@artysidorenko can you take a look here maybe?

**Comment by romanslonov** [comment]
Run into same issue with passed object in `refetchInterval` in `useQueries`.

Temporary solution:

```ts
useQueries({
  queries: [...tasks.value].map((task) => ({
    queryKey: backupQueries.checkTask(task.id),
    queryFn: () => getBackup(task.id),
    refetchInterval: (query: Query<{ backup: Backup }>) => {
      if (query.state.data?.backup && query.state.data.backup.task === null) {
        queryClient.setQueryData<{ backups: Backup[]; meta: ResponseMeta }>(
          stackletQueries.backups(params.value),
          (previousData) => {
            if (previousData) {
              const updatedBackups = previousData.backups.map((backup) =>
                backup.id === task.id && query.state.data?.backup
                  ? query.state.data.backup
                  : backup,
              );

              return { backups: updatedBackups, meta: previousData.meta };
            }
            return previousData;
          },
        );

        return false;
      }
      return 5000;
    },
  })),
});
```

**Comment by artysidorenko** [comment]
Hey folks - I'm afraid this is the same class of issues to do with current Typescript limitations in typing callback params when part of a variadic tuple.

There's some open Typescript PRs I'm keeping an eye on that might make this possible in the future.. but romanslonov's workaround is your best bet for the time being i.e. something like [this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1WO1AGjm1wE8AxZAOwGMZgJqBhJmdAD3gF84AzKBBBwA5AAEYAQ2qoptANYB6KOkn0AtAEccUMiIBQ+vjXqNqcAIJgwACgCUifXDi0ms-uhi0AFhYAmfiqoqHAAvHA2qMAA5tSSADYAXJYARtAwAMoxcfF2ybJ41NFhAHyOzs4qMMhQ5iIAMtLocACMIgDcTnDcnV2uMvBo6BawwLIh4fal5RVVNeZDpHgENghdFXDauPioiesbcADa+wczpxtbugDS6GTJhyKSAUGoIgC6hCfnl5TUyTb0DjJJaUEwMJisajsLgOUJlPieHz+QIEVAAmAcAB0UViCTsn3OFW4X2cb323DsXWJxKAA).

closely related: #5342 (also impacting the `queryFn` callback) and #3994 (`onSuccess` + `select` callbacks)

related Typescript issue: https://github.com/microsoft/TypeScript/issues/52047
