### ISSUE TITLE
Prefetched queries in SvelteKit that uses TRPC are refetched on the client regardless of staleness

### ISSUE THREAD

**Issue by boyeborg** [TanStack/query#6927]
### Describe the bug

When using `queryClient.prefetchQuery` from `@tanstack/svelte-query` with TRPC, the query is refetched on the client even though it's not stale (`staleTime` is set to `Infinity`). In addition, the `.isFetching` is false while the client site request is pending.

I'm suspecting this is a hydration issue, but not quite sure where to go from here. I see that there is a script tag with the data attribute `data-sveltekit-fetched` which I assume is used for hydration as a cache for data that was loaded on the server. When using TRPC these tags gets a `data-hash="..."` attribute, which I haven't seen on data loaded through regular fetch. Perhaps this hash causes some problems? Here's an example from the reproduction where the first one is created by the TRPC query and the second is created by a regular fetch query:

```
<script type="application/json" data-sveltekit-fetched data-url="/trpc/hello" data-hash="u87jg8">{"status":200,"statusText":"","headers":{},"body":"{\"result\":{\"data\":1}}"}</script>
<script type="application/json" data-sveltekit-fetched data-url="/api/hello">{"status":200,"statusText":"","headers":{},"body":"1"}</script>
```

### Your minimal, reproducible example

https://codesandbox.io/p/github/boyeborg/tanstack-trpc-prefetch/main?import=true

### Steps to reproduce

1. Open the reproduction URL (or clone it locally: https://github.com/boyeborg/tanstack-trpc-prefetch)
2. Install dependencies and start the dev server: `npm i && npm run dev`
3. Open a browser and navigate to the dev server url (usually, but check your terminal http://localhost:5173)
4. See the count difference from the API and TRPC queries.
5. You can also open the network console in your browser, hard refresh and see that the TRPC request gets called in the browser, while the API query does not.
6. To see the SSR generated HTML output, right click on the page and select "View page source". Or just curl the dev server.

### Expected behavior

I would expect the TRPC query to behave the same way the API query does, and not refetch on the client unless the data is stale.

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Arc
- Version 1.30.0 (46409)
- Chromium Engine Version 121.0.6167.184

### Tanstack Query adapter

svelte-query

### TanStack Query version

v5.21.7

### TypeScript version

v5.3.3

**Comment by TkDodo** [comment]
@lachlancollins can you have a look here please ?

**Comment by lachlancollins** [comment]
Hi @boyeborg , my best guess is that this is an issue with the tRPC setup rather than an issue with the svelte-query adapter. I've tried manually dehydrating and hydrating the query (using `dehydrate` and `HydrationBoundary`) without any luck either. The fact that it works with a normal fetch function on server and client suggests that the core hydration/dehydration logic works.

Have you considered using [trpc-sveltekit](https://github.com/icflorescu/trpc-sveltekit)? I obviously can't guarantee it'll fix your issues but might be worth looking into.

**Comment by lachlancollins** [comment]
@boyeborg I've fixed the problem - for whatever reason, the `browserClient` needed fetch specified as well.

Replace:
```
		browserClient ??= createTRPCClient<AppRouter>({
			links: [loggerLink({ enabled: () => dev }), httpLink({ url: "/trpc" })],
		});
```

With:
```
		browserClient ??= createTRPCClient<AppRouter>({
			links: [loggerLink({ enabled: () => dev }), httpLink({ url: "/trpc", fetch: fetcher })],
		});
```

**Comment by boyeborg** [comment]
Thank you @lachlancollins! I it was a bit of a facepalm when I realized. I'm pretty sure that the way sveltekit's `+page.ts` works is that the framework specific `fetch` has to be used on the client to get access to the "cache" populated by SSR. So basically the server does all the fetching, and passes the URLs fetched and their associated results to the client (through script tags with `data-sveltekit-fetched` properties). And then you'll have to use the sveltekit fetch function to get access to these prefetched results. Which makes totally sense, but wasn't obvious to me when setting up TRPC. Thanks for spotting the issue!
