### ISSUE TITLE
different behavior without/with developer console

### ISSUE THREAD

**Issue by hellhorse123** [TanStack/query#6934]
### Describe the bug

In my code, when the developer console is open, adequate behavior occurs: the status after start immediately becomes processing and the request will be sent once every 5 seconds until the status is done. However, when the console is closed, my status always remains created, although in fact it is processing (checked via Postman). I tried disabling caching but it didn't work. I attach the videos:

### Your minimal, reproducible example

    const {       data: stageData,       isLoading: stageLoading,       error: stageError,     } = useQuery<IStageData, Error>(       ["get-stage", stageId],       () =>         StagesService.getStage(           projectId || "",           experimentId || "",           stageId || ""         ),       {         onSuccess: (data) => {         setStageStatus(data.status);         },         enabled: !!stageId,         retry: retryLogic,          staleTime: 0,       cacheTime: 0,       }     );

### Steps to reproduce

If need, I may create sandbox with code

### Expected behavior

status correctly change status from response

### How often does this bug happen?

Every time

### Screenshots or Videos

this is behavior with console:
https://github.com/TanStack/query/assets/48678379/1d3c6178-387a-4cd0-a239-5af97d7af2ce

this is behavior without console:
https://github.com/TanStack/query/assets/48678379/8e271188-8179-47ff-a24e-caa257acd038

### Platform

macOS , Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

3.39.3

### TypeScript version

5.2.2

**Comment by TkDodo** [comment]
your chrome console shows `Disable Cache` is checked. So I suspect some caching that behaves differently? Anyways, not a react-query issue because we don't control network caching

**Comment by hellhorse123** [comment]
But don't these functions control the cache?
staleTime: 0, cacheTime: 0,

**Comment by TkDodo** [comment]
they control our own _in memory_ cache, not the _browser_ cache
