### ISSUE TITLE
react query 3.39.3 devtools error 

### ISSUE THREAD

**Issue by SeongHyuenYun** [TanStack/query#6949]
### Describe the bug

If you open React Query devtools and use React Query's enabled option set to false on a page that is dynamically import using React Lazy, the problem of React Lazy's suspense fallback loading infinitely.

### Your minimal, reproducible example

...

### Steps to reproduce

1. Dynamically import the page using react lazy.
2. Page rendering is performed using react lazy’s suspense.
3. Control automatic query execution by setting the enabled option value of React Query to false on the page.
4. Check the behavior when the react query devtools panel is opened and closed

### Expected behavior

Queries should not be auto-executed after the page is rendered.

### How often does this bug happen?

Every time

### Platform

macOS

### Tanstack Query adapter

react-query

### TanStack Query version

3.39.3

**Comment by TkDodo** [comment]
will not look into this without a reproduction, and likely won't fix it for a deprecated, two year old version (v3).

if you can reproduce it with v5, we'll re-open.
