### ISSUE TITLE
docs: Wrong URL for Nextjs example 

### ISSUE THREAD

**Issue by TDanks2000** [TanStack/query#6965]
### Describe the bug

at https://tanstack.com/query/latest/docs/framework/react/examples/react/nextjs the github url is wrong (examples/react/react/nextjs) should be examples/react/nextjs

### Your minimal, reproducible example

https://tanstack.com/query/latest/docs/framework/react/examples/react/nextjs

### Steps to reproduce

1: goto https://tanstack.com/query/latest/docs/framework/react/examples/react/nextjs
2: look at the example
3: it shows error

### Expected behavior

show the nextjs example

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/40835340/53ae1384-2433-4574-b8fd-d0501f110df4)

### Platform

.

### Tanstack Query adapter

None

### TanStack Query version

.

**Comment by TkDodo** [comment]
@lachlancollins can you have a look please?

**Comment by lachlancollins** [comment]
@TDanks2000 how did you get to https://tanstack.com/query/latest/docs/framework/react/examples/react/nextjs in the first place?

https://tanstack.com/query/latest/docs/framework/react/examples/nextjs works in the sidebar

**Comment by TDanks2000** [comment]
> @TDanks2000 how did you get to https://tanstack.com/query/latest/docs/framework/react/examples/react/nextjs in the first place?
> 
> https://tanstack.com/query/latest/docs/framework/react/examples/nextjs works in the sidebar

I dont fully remember, but im pretty sure i search "nextjs"

**Comment by TDanks2000** [comment]
here are the urls of the none working routes

https://tanstack.com/query/latest/docs/framework/react/examples/react/nextjs
https://tanstack.com/query/latest/docs/framework/react/examples/react/nextjs-suspense-streaming
https://tanstack.com/query/latest/docs/framework/react/examples/react/star-wars
https://tanstack.com/query/latest/docs/framework/react/examples/react/simple
https://tanstack.com/query/latest/docs/framework/react/examples/react/rick-morty

**Comment by lachlancollins** [comment]
> got to these by searching "example" and "nextjs"

Ahhh yep, the search is still broken :( for now please use the sidebar.

**Comment by Hanna922** [comment]
Is there a planned resolution for this issue?

**Comment by TkDodo** [comment]
we switched from aloglia to orama and search works better now.
