### ISSUE TITLE
Example of Nextjs suspence streaming doesn't work on the site

### ISSUE THREAD

**Issue by atellmer** [TanStack/query#6972]
### Describe the bug

Example of Nextjs suspence streaming doesn't work on the site.

### Your minimal, reproducible example

https://tanstack.com/query/latest/docs/framework/react/examples/nextjs-suspense-streaming

### Steps to reproduce

1. Go to [https://tanstack.com/query/latest/docs/framework/react/examples/nextjs-suspense-streaming](https://tanstack.com/query/latest/docs/framework/react/examples/nextjs-suspense-streaming)
2. Wait until it runs
3. There are some errors in console

### Expected behavior

The example should work fine.

### How often does this bug happen?

Every time

### Screenshots or Videos

![Screenshot 2024-02-25 114106](https://github.com/TanStack/query/assets/16635118/d037475f-e189-4ab9-a9fb-176f6f707a2f)

### Platform

StackBlitz

### Tanstack Query adapter

None

### TanStack Query version

v5.24.1

### TypeScript version

v5.2.2

**Comment by TkDodo** [comment]
it works fine in codesandbox:

https://codesandbox.io/p/devbox/github/tanstack/query/tree/main/examples/react/nextjs-suspense-streaming?embed=1&file=%2Fpackage.json&theme=dark
