### ISSUE TITLE
Getting " Cannot convert a Symbol value to a string" error in NextJs

### ISSUE THREAD

**Issue by shreeshauppangala** [TanStack/query#6984]
### Describe the bug

`
const postApi = (url: string, data: any) => axios.post(url, data);

const signIn = (data: LoginFormDataI) => postApi(`${API.signIn}`, data);

const { mutate: mutateSignIn, isPending: isSignInLoading } = useMutation({
    mutationFn: signIn,
    onSuccess: ({ data }) => {
      axios.defaults.headers.common.Authorization = `Bearer ${data.access}`;
      setUser({ ...data.user });
      queryClient.clear();
    },
  });

  const onSignIn = (data: LoginFormDataI) => {
    mutateSignIn(data);
  };`
  
  **throwing the below error while using the above code block**
![image](https://github.com/TanStack/query/assets/75727390/da861c4b-7fcf-4c2f-935d-ab17564bc9c0)

### Your minimal, reproducible example

typescript, @tanstack/react-query, axios

### Steps to reproduce

execute the above code block

### Expected behavior

Should not throw error

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/75727390/a7c37f50-7dc8-4aac-9b63-0892913eeb48)

### Platform

Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

^5.20.1

### TypeScript version

^5

**Comment by TkDodo** [comment]
as always, we need a runnable, standalone, minimal reproduction (codesandbox or stackblitz) to look into issues. This is very likely _not_ related to react-query at all. We'll re-open once there is a reproduction
