### ISSUE TITLE
Parts of queries getting terribly mixed up in some scenarios with invalidation

### ISSUE THREAD

**Issue by TPReal** [TanStack/query#6995]
### Describe the bug

In some scenarios in SolidJS, apparently involving the router and invalidations, parts of queries created from one observer get mixed up completely. In debugging I can see that sometimes two queries have the same key, sometimes the result is assigned as data to the incorrect query, OMG how bad it gets.

The problem appears since 5.0 at least.

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/tanstack-query-invalidate-bug-vhpdmt?file=%2Fsrc%2Findex.tsx%3A91%2C1

### Steps to reproduce

(Also written in the repro project)
1. Load the page on the /x path
2. Click the /y link (result is now y)
3. Click the / link (this invalidates both queries, result is now x)
4. Click the / link again (invalidates again, result still x)
5. Click the /y link

### Expected behavior

Expected: The result is now y, as the URL is /y.
Actual: The result is now x, despite the URL being /y. Consequent clicking on the links looks like the result is somehow delayed by one click.

### How often does this bug happen?

Every time

### Platform

- OS: Windows
- Browser: Chrome 121.0.6167.185 (Oficjalna wersja) (64-bitowa) (cohort: Stable)

### Tanstack Query adapter

solid-query

### TanStack Query version

v5.24.1

### TypeScript version

v5.3.3

### Additional context

I'm using the technique of invalidating all queries when the currently selected item in the menu is clicked again. This seems to be orthogonal to the usage of TanStack Query, but somehow I wasn't able to reproduce the problem when the invalidation came from just a button click. Anyway, what happens in the library is terrible, despite just using the API.

**Comment by TPReal** [comment]
I can see that instead of the / link I can make a button that invalidates all queries and then navigates to /x, and the bug is still there. But I don't see how to get rid of the router part and still show the problem.

**Comment by TkDodo** [comment]
@ardeora can you have a look please ?

**Comment by ardeora** [comment]
https://codesandbox.io/p/devbox/tanstack-query-invalidate-bug-forked-chhvt8?file=%2Fpackage.json%3A13%2C38&workspaceId=0d8b5620-4f50-49f2-a5b1-e4173816b150

This issue has already been fixed in v5.24.3+ The example above shows queries being populated as expected. Please let me know if you still run into any issues! Closing this issue for now
