### ISSUE TITLE
docs: solid-start example new `app.config.ts` file

### ISSUE THREAD

**Issue by talensjr** [TanStack/query#7002]
### Describe the bug

The `solid-start` example now uses a `app.config.ts` file instead of `vite.config.ts` file from `vinxi: 0.3.6` and examples are now using `vinxi: 0.3.8` so the dev server does error out.

### Your minimal, reproducible example

https://stackblitz.com/github/tanstack/query/tree/main/examples/solid/solid-start-streaming?embed=1&theme=dark&preset=node

### Steps to reproduce

1. The server automatically start.
2. It will throw an error related to not finding the new file.

### Expected behavior

Expected dev server to run correctly.

### How often does this bug happen?

Every time

### Platform

Not platform related.

### Tanstack Query adapter

solid-query

### TanStack Query version

v5

**Comment by TkDodo** [comment]
@ardeora FYI
