### ISSUE TITLE
Docs: special behaviour of `initialDataUpdatedAt=0` is not documented

### ISSUE THREAD

**Issue by Jokero** [TanStack/query#7003]
### Describe the bug

It seems `useQuery` works differently from what is written in the [docs](https://tanstack.com/query/latest/docs/framework/react/guides/initial-query-data#:~:text=while%20also%20allowing%20the%20data%20to%20be%20refetched%20on%20mount%20if%20the%20initialData%20is%20older%20than%20the%20staleTime) when `initialDataUpdatedAt=0`:
> This option allows the staleTime to be used for its original purpose, determining how fresh the data needs to be, **while also allowing the data to be refetched on mount if the initialData is older than the staleTime**

So if I have the following config, `useQuery` shouldn't refetch data on mount:
```ts
const { data } = useQuery({
    ...
    initialData: [],
    initialDataUpdatedAt: 0, // it shouldn't refetch data as Date.now() - 0 < Infinity, but it does refetch in reality
    staleTime: Infinity,
    ...
});
```
I guess this is by design as I found few issues/discussions where `initialDataUpdatedAt: 0` was mentioned (for example, [this](https://github.com/TanStack/query/issues/5250#issuecomment-1663291651) and [this](https://github.com/TanStack/query/discussions/6161#discussioncomment-7301217)).

However, there is no information about it on https://tanstack.com/query/v5/docs/framework/react/reference/useQuery and https://tanstack.com/query/v5/docs/framework/react/guides/initial-query-data.

### Your minimal, reproducible example

https://stackblitz.com/edit/github-krgozk

### Steps to reproduce

1. Go to https://stackblitz.com/edit/github-krgozk
2. Open Network tab in Dev Tools
3. Find a request to https://api.github.com/repos/tannerlinsley/react-query (it shouldn't be made according to docs, as `initialData` is not older than `staleTime`)

### Expected behavior

Case with `initialDataUpdatedAt=0` is documented on https://tanstack.com/query/v5/docs/framework/react/reference/useQuery and https://tanstack.com/query/v5/docs/framework/react/guides/initial-query-data.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="1417" alt="image" src="https://github.com/TanStack/query/assets/434135/1e09a6ce-56e3-47af-85d8-0c5e5802b057">

### Platform

Chrome

### Tanstack Query adapter

None

### TanStack Query version

v5

**Comment by TkDodo** [comment]
it seems to be this condition specifically because zero is falsy in js 🙄 

https://github.com/TanStack/query/blob/b32ad24f5d2ac79eb8dee32047195e2bb9267b2b/packages/query-core/src/query.ts#L253

I would consider this a bug rather than a missing documentation. There a couple of those checks that we likely should change towards `> 0` instead.

**Comment by TkDodo** [comment]
okay, it's late. I think we shouldn't check for `dataUpdatedAt` here at all. This check likely means: we're always stale if there is no data yet. `!dataUpatedAt` kind of reflects that, but not really. The check should likely be made against `this.state.data !== undefined` like we do here:

https://github.com/TanStack/query/blob/b32ad24f5d2ac79eb8dee32047195e2bb9267b2b/packages/query-core/src/query.ts#L624

**Comment by Jokero** [comment]
@TkDodo Ok, makes sense, thank you
