### ISSUE TITLE
angular-adapter: does not re-render ui on signal changes

### ISSUE THREAD

**Issue by bjesuiter** [TanStack/query#7023]
### Describe the bug

I'm using a bog-standard setup of @tanstack/angular-query-experimental. 

For some reason, none of the signals render a second time when the source is re-fetched. 

Note: Please run the minimal example locally, since they don't run on either of stackblitz or codesandbox and i don't really know why not. 
Here are the links to these services anyway: 
- https://stackblitz.com/~/github.com/bjesuiter/stackblitz-tanstack-query-angular-rerender-bug
- https://codesandbox.io/p/github/bjesuiter/stackblitz-tanstack-query-angular-rerender-bug/draft/wizardly-ives

### Your minimal, reproducible example

https://github.com/bjesuiter/stackblitz-tanstack-query-angular-rerender-bug

### Steps to reproduce

1. clone the repo 
2. npm i && npm start
3. Open the local url 
4. See the first response from the world time api 
5. in the tanstack devtools, click the refetch or invalidate button to refresh the data 

### Expected behavior

As a developer I expected to see the time on the screen update when I refetch the source from worldTimeApi, but for some reason the ui doesn't update. 

### How often does this bug happen?

Every time

### Platform

- OS: macos

### Tanstack Query adapter

angular-query

### TanStack Query version

5.24.8

### TypeScript version

5.3.3

**Comment by arnoud-dv** [comment]
Thanks for reporting this bug. It's fixed in [v5.26.1](https://github.com/TanStack/query/releases/tag/v5.26.1)
