### ISSUE TITLE
 queryClient.getQueryCache is not a function at ReactQueryDevtoolsPanel2

### ISSUE THREAD

**Issue by mil920** [TanStack/query#7034]
### Describe the bug

I have a console error when i call <ReactQueryDevtools> component in a vitejs app.
`
...other import
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: Infinity,
    },
  },
});
function App() {
  return (
    <ThemeProvider defaultTheme="dark" storageKey="vite-ui-theme">
      <HelmetProvider>
        <QueryClientProvider client={queryClient}>
          <BrowserRouter>
            <Router />
            <ReactQueryDevtools initialIsOpen={false} />
          </BrowserRouter>
        </QueryClientProvider>
      </HelmetProvider>
    </ThemeProvider>
  );
}
`
<img width="1440" alt="Capture d’écran 2024-03-06 à 09 53 02" src="https://github.com/TanStack/query/assets/9515269/d80bc984-2263-41f0-9160-e98aa1bd4dd2">

### Your minimal, reproducible example

#

### Steps to reproduce

Install react app with vite :
yarn create vite my-app --template react
try to add react query and react query devtools

### Expected behavior

I want to react dev tools working

### How often does this bug happen?

None

### Platform

Mac OS

### Tanstack Query adapter

react-query

### TanStack Query version

5.24.8

### TypeScript version

5.2.2

### Additional context

vitejs version : 5.1.4
react-query-devtools : 5.25.0

**Comment by mil920** [comment]
I solved myself :)  dependencies issue 
"@tanstack/react-query": "^5.24.8", **-> need to be 5.25.0**
"@tanstack/react-query-devtools": "^5.25.0",

**Comment by boyhax** [comment]
i still have the issue 

    "@tanstack/react-query": "^5.65.1",
    "@tanstack/react-query-devtools": "^5.65.1",

on react vite

**Comment by andersevenrud** [comment]
I also still have this issue on `^5.66.0` using  vanilla React + Vite project. Tried using different versions, but to no avail.

Did you figure something out @boyhax ?

**Comment by andersevenrud** [comment]
> i fixed it just now by removing node madules and reinstall it ,the problem mostly caused by changing package manager from pnpm to bun .also make sure same versions on both react-query and devtools

Thanks for the quick response and insight @boyhax !

I previously tried removing the `node_modules` from my entire project tree and re-installing, but it had no effect. It broke after upgrading from v4 to v5.

But, after deleting the global pnpm cache, then deleting all`node_modules` + running install again, then adding `--force` to Vite it started working. I'm not sure which of these actions solved my issue, but after spending hours on this I don't really care and just happy my app is starting up again.
