### ISSUE TITLE
`useQueries` + `skipToken` looses `.data` type inference

### ISSUE THREAD

**Issue by vjee** [TanStack/query#7035]
### Describe the bug

When using `useQueries` with `skipToken`, `queryResult.data` is inferred as `unknown` instead of the actual return type of the `queryFn`.

```ts
const [withEnabled] = useQueries({
  queries: [{ queryKey: ["withEnabled"], queryFn: () => 1, enabled: true }],
});

const [withSkipToken] = useQueries({
  queries: [
    { queryKey: ["withSkipToken"], queryFn: true ? () => 1 : skipToken },
  ],
});

withEnabled.data;
//           ^? number | undefined
withSkipToken.data;
//             ^? unknown
```

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/tanstack-react-query-usequeries-skiptoken-issue-wdk8m5

### Steps to reproduce

- Open repro
- Hover over `withEnabled.data` and `withSkipToken.data` to see the types

### Expected behavior

I expected `withSkipToken.data` to be inferred as `number | undefined` instead of `unknown`.

### How often does this bug happen?

None

### Platform

@tanstack/react-query v5.25.0

### Tanstack Query adapter

react-query

### TanStack Query version

v5.25.0

### TypeScript version

v5.3.3

**Comment by TkDodo** [comment]
@Jaaneek can you take a look here? I'm afraid I'm no expert with the `userQueries` typings 😅

**Comment by Jaaneek** [comment]
Looking into it!

**Comment by Jaaneek** [comment]
@vjee quick fix is to add "as const" after queries array.

```tsx
 queries: [
    { queryKey: ["withSkipToken"], queryFn: true ? () => 1 : skipToken },
  ] as const
  ```
  
 For some reason typescript doesnt make the array "readonly" by default when passing skipToken @TkDodo 
 
 I'm looking for a solution

**Comment by vjee** [comment]
Thanks for the quick fix. Great feature btw! Well done 👏

**Comment by Jaaneek** [comment]
I found a fix, pull request incoming

**Comment by Jaaneek** [comment]
Seems like some other tests are failing once thix is fixed.

Can't find a good solution at this moment.

Feel free to contribute anyone!

temporary fix is add `as const`
```
 queries: [
    { queryKey: ["withSkipToken"], queryFn: true ? () => 1 : skipToken },
  ] as const
  ```

**Comment by gwansikk** [comment]
I've worked on the issue in question. Please take a look.
