### ISSUE TITLE
refetch returning stale data

### ISSUE THREAD

**Issue by drewbietron** [TanStack/query#7038]
### Describe the bug

Performing a refetch on a query does not return back fresh data despite the refetch being triggered.    This is happening with a specific query on a React Native application.  The exact same query on web refetches as expected, as does the rest of the refetch calls within the React Native application. While it seems as if its specific to the implementation of the app, I can confirm that the app does refetch with an explicit 

```typescript
await queryClient.clear();
await query.refetch();
```

While just calling `await query.refetch()`, makes the refetch call, but with stale data returned.

The query keys are automatically generated via [Graphql React Query Codegen](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-react-query) and the query has for the query in question is (if this info is helpful for debugging)

```json
["ConversationList.infinite",{"orderConversationsBy":{"updatedAt":"DescNullsLast"},"orderMessagesBy":{"createdAt":"DescNullsLast"}}]
``` 

### Your minimal, reproducible example

n/a

### Steps to reproduce

Perform the initial query, everything here is fine.
```typescript
 const { graphqlClient, queryClient } = useSupabase();
  const { data, refetch, isFetched, isFetching, fetchNextPage } =
    useInfiniteConversationListQuery(
      graphqlClient,
      {
        orderMessagesBy: { createdAt: OrderByDirection.DescNullsLast },
        orderConversationsBy: { updatedAt: OrderByDirection.DescNullsLast },
      },
      {
        initialPageParam: 0,
        getNextPageParam: (lastPage) => {
          if (!lastPage.conversations?.pageInfo.hasNextPage) return;
          return {
            after: lastPage.conversations.pageInfo.endCursor,
          };
        },
      }
    );
```

Invoke `refetch`
```typescript
await refetch()
```

Stale data is returned

Invoke cache clear + refetch
```typescript
await queryClient.clear(); 
await refetch();
```

Im attaching a video to show the reproduction.  I dont know if its a React Native implication, since the exact sale query/useQuery hook is used on web and it works fine.  The refetch is happening, but stale data is returned 😵 

I have also tried many combinations of `invalidateQueries`;

```typescript
await queryClient.invalidateQueries({ queryKey: ["ConversationList.infinite"] });
or 
await queryClient.invalidateQueries({ queryKey: ["ConversationList.infinite",{"orderConversationsBy":{"updatedAt":"DescNullsLast"},"orderMessagesBy":{"createdAt":"DescNullsLast"}}] });
await refetch();
```

### Expected behavior

I expect refetch to refetch the data.  Why it happens successfully but returns stale data has me confused.

### How often does this bug happen?

One this query on this platform, every time

### Screenshots or Videos

https://github.com/TanStack/query/assets/1255104/e174d3c2-bac1-4267-8325-86a024a9d944

### Platform

- React Native `0.73.4`

### Tanstack Query adapter

None

### TanStack Query version

v5.25.0

### TypeScript version

v5.3.3

**Comment by TkDodo** [comment]
what does "stale data" refer to in your case? If the refetch happens with the correct parameters - how can it be "stale" ?

Can you maybe inspect the network trace somehow and see what gets sent / what gets returned from the backend?

I'm afraid I'm not going to look into this too much without a standalone reproduction. It could very well be that the code-gen does something wrong, so please try reproducing without it (or open an issue there)

**Comment by drewbietron** [comment]
Stale data as in not what's returned from the request and rather the data from the initial request.

I'll get a reproduction up and post it.

**Comment by TkDodo** [comment]
I'll reopen once there is a reproduction. Almost certain that it has something to do with the backend returning old data

**Comment by drewbietron** [comment]
> I'll reopen once there is a reproduction. Almost certain that it has something to do with the backend returning old data

I can confirm the backend is not sending old data. I'll get a reproduction up. Clearing the cache + refetching works while just calling refetch does not.

**Comment by kincaidoneil** [comment]
Here's a reproduction: https://stackblitz.com/edit/vitejs-vite-z4sumt?file=src%2FApp.tsx

Essentially:
1. A component calls `refetch`.
2. While refetching, that component unmounts and another refetch gets triggered elsewhere.
3. The `refetch` resolves with stale data.

**Comment by TkDodo** [comment]
unmounting a component doesn't abort the fetch unless you use the provided AbortSignal. Have a look at [Query Cancellation](https://tanstack.com/query/v5/docs/framework/react/guides/query-cancellation) in the docs.

So in your reproduction, what happens is that:

- a fetch is triggered
- the component unmounts (this does nothing)
- another component mounts
  - this would trigger a fetch, but because there is already one in progress, no new fetch is triggered.
- the one fetch resolves (the one triggered by refetch), and everyone gets that data

The only issue I'm seeing is related to the result returned from `refetch`. There, when the promise resolves, the calculated result is still in `fetching` state - that's why `isRefetching` is true. You can file an issue for that if you want, but the data returned is correct.

**Comment by kincaidoneil** [comment]
Thanks for looking. My bad, I thought the repro was returning stale data, but it is correct. (I did _not_ expect/want the queries to be canceled when it was unmounted, but thought they were)
