### ISSUE TITLE
keepPreviousData doesn't work with useQueries

### ISSUE THREAD

**Issue by david-roeger** [TanStack/query#7051]
### Describe the bug

Using `keepPreviousData` in useQueries always returns:

```js
{
  data: undefined,
  status: "pending",
  isPlaceholderData: false
 ...
}
```
while the query-function is running. 
This produces different results for using the same query.

(See the reproduction)

### Your minimal, reproducible example
[Reproduction](
https://codesandbox.io/p/devbox/hungry-benz-sw22n2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clthijacv00072e682sdpvxtd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clthijacv00022e68w6vqtznd%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clthijacv00042e68lhc8vp3d%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clthju47k02s42e68bvgehytv%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clthijacv00062e68oryqmo0x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B58.36679031837016%252C41.63320968162984%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clthijacv00022e68w6vqtznd%2522%253A%257B%2522id%2522%253A%2522clthijacv00022e68w6vqtznd%2522%252C%2522activeTabId%2522%253A%2522clthit0ts010g2e68vcs2ro47%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clthikg0400522e68n1efwdoq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A3%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clthit0ts010g2e68vcs2ro47%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clthijacv00062e68oryqmo0x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clthijacv00052e68n86qkn2i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clthijacv00062e68oryqmo0x%2522%252C%2522activeTabId%2522%253A%2522clthijacv00052e68n86qkn2i%2522%257D%252C%2522clthijacv00042e68lhc8vp3d%2522%253A%257B%2522id%2522%253A%2522clthijacv00042e68lhc8vp3d%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clthijacv00032e689kuq0bv5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clthijacv00032e689kuq0bv5%2522%257D%252C%2522clthju47k02s42e68bvgehytv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clthju42o02rz2e68y0dm6bj4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clthju4au0012digx661r6l6x%2522%257D%255D%252C%2522id%2522%253A%2522clthju47k02s42e68bvgehytv%2522%252C%2522activeTabId%2522%253A%2522clthju42o02rz2e68y0dm6bj4%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. use `useQuery` -> the previousData is kept
2. use `useQueries`  and return the query-> the previousData is discarded

3. See the reproduction and increment the input
4. Both results hold different values

### Expected behavior

I don't know if this is a limitation due to how `useQueries` or `keepPreviousData` works but I would expect the `placeHolderData` to be kept around. If that's not possible maybe this could be documented somewhere.

### How often does this bug happen?

Every time

### Screenshots or Videos

![grafik](https://github.com/TanStack/query/assets/61949735/33dcf4c0-ccda-466d-9835-08566719cc86)

### Platform

```
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 2.28 GB / 4.01 GB
    Container: Yes
    Shell: Unknown
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    @tanstack/eslint-plugin-query: @latest => 5.20.1 
    @tanstack/react-query: @latest => 5.24.8 
    @tanstack/react-query-devtools: @latest => 5.25.0 
    @vitejs/plugin-react: ^2.0.0 => 2.2.0 
    react: ^18.0.0 => 18.2.0 
    react-dom: ^18.0.0 => 18.2.0 
    vite: ^3.0.0 => 3.2.8 
```

### Tanstack Query adapter

react-query

### TanStack Query version

v5.24.8

**Comment by TkDodo** [comment]
That's a known limitation:

https://tanstack.com/query/v5/docs/framework/react/reference/useQueries

> The placeholderData option exists for useQueries as well, but it doesn't get information passed from previously rendered Queries like useQuery does, because the input to useQueries can be a different number of Queries on each render.

It's very hard to know what the "previous" query was in a dynamic list of queries. We tried to be smart and figure out which queries belong together, or only do it if the length didn't change, but even then, you could've swapped things around in the array, and keeping previous data would yield wrong results.

If you think it should be better documented that this doesn't work, please open a PR to the docs.

**Comment by knilink** [comment]
came across with the same issue
could we introduce an item identifier? like the `key` prop when dealing with array of elements in react.
@TkDodo

**Comment by realainov** [comment]
@TkDodo - why not just let the user specify IDs for queries, as is being done now for queryKey?
