### ISSUE TITLE
useMutation - throwOnError triggering on each render

### ISSUE THREAD

**Issue by ugurbayraktarr** [TanStack/query#7058]
### Describe the bug

When i use a mutation in my react component, each render is triggering `throwOnError`.

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-it3a6h?file=src%2FApp.tsx

### Steps to reproduce

1. click on `increase count` - you won't see alert.
2. click on `trigger mutation` - you will see alert.
3. click on `increase count` again, you will see alert again. 

### Expected behavior

As a user, i want to listen `throwOnError`. But it triggers many times after each render. 

### How often does this bug happen?

Every time

### Platform

OS: Windows
Browser: Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

v5.25.0

**Comment by ugurbayraktarr** [comment]
I've tried to write a custom error handler. It tries to handle the error. 
If it can handle the error, it displays a modal with detailed information about the error and returns false on `throwOnError`, otherwise it returns true on `throwOnError`. However, this structure shows the error modal on every render.
How should I handle this case? It seems like `throwOnError` is not the right choice for my case.

**Comment by TkDodo** [comment]
throwOnError is not a function you can use to perform a side effect like rendering a modal. You should render a modal depending on the error field returned from useMutation or the onError callback.
