### ISSUE TITLE
pageParams is inferred as unknown[] in the cache for infinite querys

### ISSUE THREAD

**Issue by lgenzelis** [TanStack/query#7069]
### Describe the bug

When using `infiniteQueryOptions(.....).queryKey` to access the cache, the type of the `pages` is inferred correctly. However, the type of `pageParams` is just `unknown[]`.

### Your minimal, reproducible example
[Ts Playground](https://www.typescriptlang.org/play?ts=5.3.3#code/JYWwDg9gTgLgBAbzsAdgM1cGBTAigV2ygE8B5MGYCFAZwBo4CjiBhAG2GxXgF840oEEHADkAARgBDWlIDGAawD0UbJNkwAtAEdCJEQG4AUIYAm2WW0kq4s6jXg7m7TtwBcjXaw5cYRwzGIwbDgWCAg2AAVJAHNggF5EQzhkuAAPd3soVGijFLhidwAjMLZVFCMeYzMLK2C0fBR1KhQ4EGIASXRMHCYSADEUAAoASndQ8KjYv0NbGTgICmaaOATUDBQsPE9ySjtBhCSUxxIAaWwCuABtERgAC2wNeXORAF06Q+Tj4gH3Ns71za9b4od55brASSRGLYKJQSQgdwABlBKViMAActhUjBJjCrPD3IMAPqWey4qBwOhEyFQ2L0OCknHQ2Hw4YrAB8DMkZOZ+OEAGo4ABGBiKRRwAAGjNxLJAEuQy1sUBU6jYxGQ6CI2BMcG5kpQ+BAhSIEo+cDFeUtVutNttdrtAD0APyHHjDab1Rq7FpoMIjRJ5Wb2Gxqe4mADKMHwaDQKzgX2cPgAdGigQARSRSQYLb00JNfM7Ed1m4CxwYAQlkoe1kejaDZKijUHKxkDdngYGhywSVdkYdrMaTnbp+nN4olw+wNHlwEV0BVMDVGrQRBUOr1EvGtOwlxepryFuSzrNQY7vLhIG7Ib7Najg8nspoo4ttwgAHdsAA3IgMCfn+HTgqkoNPIKDvigu4zjIqg6hAsYSgaRpEJBZqHnAx6VEAA)

### Steps to reproduce

The ts playground has comments explaining what's going on.

### Expected behavior

`pageParams` should be inferred as `number[]`

### Tanstack Query adapter

None

### TanStack Query version

5.25.0

### TypeScript version

5.3.3

**Comment by lgenzelis** [comment]
Now that I think about it, maybe this is more a feature request than a bug? 😅 I mean, `unknown` is not wrong.. It's just odd that type inference works so well for `pages` but not for `pageParams`.

**Comment by TkDodo** [comment]
Duplicate:
- https://github.com/TanStack/query/issues/6628
