### ISSUE TITLE
exhaustive-deps doesn't understand function call for query key

### ISSUE THREAD

**Issue by fdw** [TanStack/query#7077]
### Describe the bug

We want to offer comfort hooks to query and invalidate calls. Of course, they need to use the same query key, so we extracted it like this:
```
export function useSomeData(id: number) = useQuery({
  queryKey: queryKeyFor(id),
  queryFn: ...
})

export function useQueryCache() {
  const queryClient = useQueryClient()
  return {
    invalidate: (id: number) =>
      queryClient.invalidateQueries({ queryKey: queryKeyFor(id) })
  }
}

function queryKeyFor(id: number) {
  return ['api', id]
}
```

In practice, this works perfectly. However, the eslint-plugin `exhaustive-deps` doesn't understand that `id` is contained in the query key.

### Your minimal, reproducible example

n/a

### Steps to reproduce

see above

### Expected behavior

I expect the hook to understand that `id` is used in the query key factory, but it's not.

### How often does this bug happen?

Every time

### Platform

- OS: Linux
- Browser: n/a

### Tanstack Query adapter

react-query

### TanStack Query version

@tanstack/eslint-plugin-query@5.20.1

### TypeScript version

5.3.3

**Comment by TkDodo** [comment]
we have tests for this, so please show a reproduction:

https://github.com/TanStack/query/blob/7b7cc2f6abbe4435da3f421ac64a64a025b25b60/packages/eslint-plugin-query/src/__tests__/exhaustive-deps.test.ts#L142-L156

**Comment by fdw** [comment]
Here's a reproduction: https://stackblitz.com/edit/vitejs-vite-hutlfq?file=src%2Fhooks.ts
The issue seems to be more subtly about `undefined` and coalescing. Maybe you have a better idea how to solve this :)

**Comment by TkDodo** [comment]
thanks for the reproduction. it really seems to be a bug around `??`.

This yields no lint error:

```
queryKey: `blah${id}`,
```

but this does:

```
queryKey: `blah${id ?? -1}`,
```

@Newbie012 could you have a look at this?

**Comment by fdw** [comment]
That was quick! Thank you very much!
