### ISSUE TITLE
Solid Query: Query errors are not caught by ErrorBoundary in the same component

### ISSUE THREAD

**Issue by PeterDraex** [TanStack/query#7083]
### Describe the bug

If the option `throwOnError` is `true`, Solid Query throws errors which can be caught with an ErrorBoundary. The issue is that the error doesn't get caught by the ErrorBoundary in the same component as where the query is defined, only by it's parent. 

This leads to less readable code, because to properly catch errors, you need to .
It's also inconsistent with the behavior of SolidJS's Suspense and `createResource`.

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-query-urg3e7?file=src%2FExample.tsx

### Steps to reproduce

1. Open the link
2. See that it shows "Parent ErrorBoundary was triggered 😢" while the expected result would be "Inner ErrorBoundary was triggered 🎉"

### Expected behavior

If `throwOnError` is `true`, the ErrorBoundary defined within the same component is triggered (more specifically, the ErrorBoundary which is closes to the place where `queryResult.data` is accessed). 

### Tanstack Query adapter

solid-query 5.25.0

**Comment by ardeora** [comment]
Taking a look at this this week!
