### ISSUE TITLE
v3 and v4 docs are unavailable

### ISSUE THREAD

**Issue by pleunv** [TanStack/query#7091]
### Describe the bug

As of very recently (I think max 2-3 days) the docs for v3 and v4 lead to an error page:

- v3: https://tanstack.com/query/v3/docs/framework/react/overview
- v4: https://tanstack.com/query/v4/docs/framework/react/overview

### Your minimal, reproducible example

n/a

### Steps to reproduce

n/a

### Expected behavior

n/a

### How often does this bug happen?

None

### Screenshots or Videos

<img width="785" alt="image" src="https://github.com/TanStack/query/assets/182021/e3308df5-8da9-44ea-9ce3-35acc954a997">

### Platform

n/a

### Tanstack Query adapter

None

### TanStack Query version

n/a

**Comment by TkDodo** [comment]
we're aware. it's related to a recent refactoring of the docs page. @lachlancollins fyi

**Comment by lachlancollins** [comment]
Fixed in #7102 and #7103
