### ISSUE TITLE
Typescript incorrectly narrows `error` based on `isLoading`

### ISSUE THREAD

**Issue by lgenzelis** [TanStack/query#7105]
### Describe the bug

If I do 
```ts
const { error, isLoading } = useQuery(...);
if (isLoading) {
  ....
```
`error` is assumed to be `null` by typescript. That's wrong: if it's the first time the query is used, then yes, that's right. But if:
1. query retries until we have `isLoading === false` and `error !== null`
2. the component using the query is unmounted
3. it gets remounted
4. the query will be automatically retried (resulting in `isLoading === true` again), but `error` will be initialized with the previous `error`, so we have `error !== null` while also `isLoading === true`.
 
So either the types or the implementation are wrong. I'm hoping for the types being wrong, because I like this behavior 😅 

In case it helps: the same implementation behavior is present with `isFetching` (so, you can have  `isFetching === true` while also having `error !== null`), but the type narrowing doesn't kick in that case. 

### Your minimal, reproducible example

[Ts Playground](https://www.typescriptlang.org/play?ts=5.3.3#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ5wC+cAZlBCHAOQACMAhgHaoMDGA1gPRTr2swBaAI458VANwAoSQBN0rADb0epZI37AIjUuhisAFgGUKu-cEYBzABQBKAFxwACuRDAMAHgQAPB42QgAI1xCAD4pSRI1DS04ADEICFtESThUuFYtFkQ4NwAZCHoZcwsAGhzUWN0DYrLccigiOABeFAxsXDwrBBEOgGl0PAcAbSoQPAF2AaoAXTKe-FjGBxIqoxMYM0tCG3C0nJI4KzyCossbZL29uugpS7TOTjgAPQB+FLTCaT3gA6OK1eK5wQ7zu1ygtzucAezzee0+nyAA)

### Steps to reproduce

Since I'm hoping for this to be a bug in the types and not the implementation, I'm providing a Ts Playground as MWE. But if you folks tell me this is an implementation bug, I can create a codesandbox instead.

### Expected behavior

Type narrowing match implementation

### How often does this bug happen?

Every time

### Platform

-

### Tanstack Query adapter

None

### TanStack Query version

5.25.0

### TypeScript version

5.3.3

**Comment by TkDodo** [comment]
> the query will be automatically retried (resulting in isLoading === true again), but error will be initialized with the previous error, so we have error !== null while also isLoading === true.

can you show this in a runtime sandbox, because if `isLoading` is `true`, `data` should be `undefined` and `error` should be `null`. This can be seen in the code here:

https://github.com/TanStack/query/blob/549862e34d0afd74dd3306047fc701dfb0bb24c5/packages/query-core/src/query.ts#L561-L564

if a fetch comes in and we have no data, `error` state will be reset. So I don't see a runtime scenario where `isLoading` (derived from `isPending`) is `true` and `isError` is defined. If so, we have a runtime issue, not a typing issue :)

**Comment by lgenzelis** [comment]
Alright, I created a [sandbox mwe](https://codesandbox.io/p/sandbox/react-query-isloading-and-error-bug-4mxmzr?file=%2Fsrc%2Findex.tsx%3A12%2C26-12%2C27&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltrag2qw00063b6lp6yyoltl%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltrag2qv00023b6lsbc2w09l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltrag2qv00033b6lv6pw3p4r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltrag2qv00053b6lsbfn9t4h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B59.686380443320495%252C40.313619556679505%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltrag2qv00023b6lsbc2w09l%2522%253A%257B%2522id%2522%253A%2522cltrag2qv00023b6lsbc2w09l%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltragt7400023b6gnt2ygvb2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cltraqfxg00023b6lhr8xdgk2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A26%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A27%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltraqfxg00023b6lhr8xdgk2%2522%257D%252C%2522cltrag2qv00053b6lsbfn9t4h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltrag2qv00043b6luvms55u7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltrag2qv00053b6lsbfn9t4h%2522%252C%2522activeTabId%2522%253A%2522cltrag2qv00043b6luvms55u7%2522%257D%252C%2522cltrag2qv00033b6lv6pw3p4r%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltrag2qv00033b6lv6pw3p4r%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

To see it:
- open the browser console and reload the sandbox
- wait for the error. You should see
```
===== rendering ====
>> error oh no
>> isLoading false
```
- click on the Toggle button, which unmounts the component, and then click it again to remount it
- You now will see the bug. The first render will show:
```
===== rendering ====
>> error oh no
>> isLoading true
```
and then it'll be almost instantly followed by a re-render where `error` is correctly set to `null`.

Btw, for context: why is this an issue? Because I'm resorting to `useEffect` to show an error toast if the query fails, and because of this issue the error toast is shown as soon as the component remounts.
