### ISSUE TITLE
Depracted warnings when installing  @tanstack/react-query@latest

### ISSUE THREAD

**Issue by Maltstar** [TanStack/query#7108]
### Describe the bug

When I install  `@tanstack/react-query `with `npm i @tanstack/react-query@latest` 
I got warning about deprecated packages being used.

### Expected Behavior 
The package `@tanstack/react-query `is installed and no warnings are reported.

### Current Behavior
The package `@tanstack/react-query `is installed and the following warnings are reported:
```bash
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: 
This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. 
Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6:
This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. 
Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: 
This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. 
Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: 
This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. 
Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: 
This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. 
Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: 
This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. 
Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: 
This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. 
Please use @babel/plugin-transform-object-rest-spread instead.
npm WARN deprecated @motionone/vue@10.16.4: Motion One for Vue is deprecated. 
Use Oku Motion instead https://oku-ui.com/motion
npm WARN deprecated webextension-polyfill-ts@0.25.0: This project has moved to @types/webextension-polyfill
```

Are there relevant warnings? If so would it be possible to replace the packages as suggested by npm.

### Your minimal, reproducible example

none since it occurs by only installing the package not using it

### Steps to reproduce

1.In a terminal install the package via  `npm i @tanstack/react-query@latest`

### Expected behavior

The package `@tanstack/react-query `is installed and no warnings are reported.

### How often does this bug happen?

Every time

### Screenshots or Videos

![@tanstack_react-query](https://github.com/TanStack/query/assets/101098152/172531fb-4d49-4c3d-8566-5de91dc9befe)

### Platform

- Ubuntu Release 22.04.3 LTS (Jammy Jellyfish) 64-bit
- MATE 1.26.0
- npm ^10.2.5

### Tanstack Query adapter

react-query

### TanStack Query version

v5.28.0

### TypeScript version

v5.4.2

**Comment by TkDodo** [comment]
I just ran this in an empty directory with an empty package.json, here's what I got:

```
npm i @tanstack/react-query@latest

added 5 packages, and audited 6 packages in 561ms

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

When you run `npm i`, it will also install other things that are out-of-date in your package.json. This is not from adding react-query.
