### ISSUE TITLE
Devtools Picture-in-Picture not Working With `shadowDOMTarget`

### ISSUE THREAD

**Issue by joealden** [TanStack/query#7109]
### Describe the bug

Two recently added devtool features don't seem to play nicely together:

- https://github.com/TanStack/query/pull/6931
- https://github.com/TanStack/query/pull/7005

When enabling picture-in-picture mode with `shadowDOMTarget` specified, no styles are applied.

I'm not sure how the picture-in-picture mode is implemented, but maybe it needs to ignore `shadowDOMTarget`?

### Your minimal, reproducible example

None (I don't believe CodeSandbox would be able to show this?)

### Steps to reproduce

1. Render the `ReactQueryDevtools` component.
2. Open the devtools and click the "picture-in-picture" mode button.
3. See that the newly opened devtool window has no styling.

### Expected behavior

Styles should be applied as usual.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/10297243/a81c4f3c-817d-4c18-8c7a-7fca508df16b)

### Platform

- OS: Linux
- Browser: Chrome
- Browser Version: 122.0.6261.111

### Tanstack Query adapter

react-query

### TanStack Query version

5.28.0

### TypeScript version

5.4.2

**Comment by joealden** [comment]
cc @ardeora @michelleoj

**Comment by ardeora** [comment]
Will take a look today and fix it! Thanks for creating an issue ❤️

**Comment by ardeora** [comment]
This should be fixed in the newer versions (v5.28.3+). Here is a working reproduction! https://stackblitz.com/github/ardeora/react-query-shadow-dom-repro?file=README.md

Let me know if you face any issues!

**Comment by joealden** [comment]
Works perfectly - thanks for the quick fix!
