### ISSUE TITLE
useSuspenseQueries inference differ from useQueries inference

### ISSUE THREAD

**Issue by wk-ouisense** [TanStack/query#7118]
### Describe the bug

Link to TypeScript playground - [playground](https://www.typescriptlang.org/fr/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1WO1AGjgEccoBPAeTBmAgDsiUMBlNMdJrc-VOAL5wAZlAgg4AIgACMAIZN5AYwDWAeijo5SmAFoyuCpIBQxpY1TxG6OAF5S5arXpMAFAmNwHhgNLoKAFxwANqS1pIAuoSe3pQAYgxBcqgUDEpwrgCUdgB8iDFemjDIUAxS4XDJcOaKANwxAtECmfVmFvAwAO4QdrFOdBbuMQaUfoEhkl0QkdFeIxQJSSlpGdm2eR5ehejFpVJTkpX8NZb1Xo3Gza0n8MHWmMRTmBG9aDy4fO4jfEHBMdazOBTYwRZpwNRqODABjCXCaAAmcF0R2q7TgjCBAAsbHIoFA5BQ4PCIAQ4AwIPAlJiFABzHEMCgwTHQmmmE4QAA26AAdByIDTXPdufC5PJHt1MMLRXJMmy0XcGOh2MwpsqXvY3srONxsB8CF9eARfv9FYDgaDshCUAwVOTOmVkVUbuiykycXiCUSSfxyZTqQw6ZUGUyWXKmJyeXyBdZlVKxUDurGRfJZcYgA)

In the playground, you can see that `useSuspenseQueries` data are not inferred and becomes `unknown`. `useQueries` is working great

### Your minimal, reproducible example

https://www.typescriptlang.org/fr/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1WO1AGjgEccoBPAeTBmAgDsiUMBlNMdJrc-VOAL5wAZlAgg4AIgACMAIZN5AYwDWAeijo5SmAFoyuCpIBQxpY1TxG6OAF5S5arXpMAFAmNwHhgNLoKAFxwANqS1pIAuoSe3pQAYgxBcqgUDEpwrgCUdgB8iDFemjDIUAxS4XDJcOaKANwxAtECmfVmFvAwAO4QdrFOdBbuMQaUfoEhkl0QkdFeIxQJSSlpGdm2eR5ehejFpVJTkpX8NZb1Xo3Gza0n8MHWmMRTmBG9aDy4fO4jfEHBMdazOBTYwRZpwNRqODABjCXCaAAmcF0R2q7TgjCBAAsbHIoFA5BQ4PCIAQ4AwIPAlJiFABzHEMCgwTHQmmmE4QAA26AAdByIDTXPdufC5PJHt1MMLRXJMmy0XcGOh2MwpsqXvY3srONxsB8CF9eARfv9FYDgaDshCUAwVOTOmVkVUbuiykycXiCUSSfxyZTqQw6ZUGUyWXKmJyeXyBdZlVKxUDurGRfJZcYgA

### Steps to reproduce

```ts
const [oneSus, twoSus] = useSuspenseQueries({queries: [
  one,
  two
]})
```

### Expected behavior

Types being inferred and not marked as `unknown`

### How often does this bug happen?

Every time

### Screenshots or Videos

![CleanShot 2024-03-15 at 16 38 53@2x](https://github.com/TanStack/query/assets/154219517/b859ea0d-236e-4e27-94d6-9bfc94db425b)

### Platform

- macOS
- VSCode/IDEA

### Tanstack Query adapter

react-query

### TanStack Query version

v5.28.4

### TypeScript version

v5.2.2 or v5.4.2

**Comment by TkDodo** [comment]
yeah looks like an issue with the types. Do you want to take a look at where this went wrong?

**Comment by wk-ouisense** [comment]
I looked at the difference between the two and saw no difference that could cause this. I can't go deeper right now, I let anyone that can fix this!
