### ISSUE TITLE
Error is reset to null during invalidation

### ISSUE THREAD

**Issue by izri16** [TanStack/query#7130]
### Describe the bug

When invalidating a query that thrown, its `error` field is reset to `null` during invalidation until it throws again. This is not consistent with the behavior of RQ v3 where the `error` field was retained. As I could not find any information on that in the migration docs or any option to fallback to the old behavior, I consider this behavior a bug.
If you consider this correct, could you provide some links explaining it or provide guidance about how to fallback to the previous behavior?

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/rq-v5-invalidation-issues-forked-3nh2c9?file=%2Fsrc%2FApp.js

### Steps to reproduce

1. Navigate to the sandbox
2. Open console
3. Click on "Invalidate queries" button
4. See that the error text and error from console disappears until its thrown again

### Expected behavior

The error would be retained on invalidation, same as in v3.

### How often does this bug happen?

Every time

### Platform

OS - [macOS]
browser - Chrome
version - 122.0.6261.112

### Tanstack Query adapter

None

### TanStack Query version

5.27.3

**Comment by TkDodo** [comment]
this is on purpose - errors reset when going into loading state. This is the same behaviour as in v3 - here's a fork of your reproduction downgraded to v3 and it behaves exactly the same:

https://codesandbox.io/p/sandbox/rq-v5-error-not-kept-forked-5wz54w?file=%2Fsrc%2FApp.js%3A8%2C1
