### ISSUE TITLE
i have firebase + react query and i want to show data offline 

### ISSUE THREAD

**Issue by miteshdevg** [TanStack/query#7138]
### Describe the bug

which thing do i need to use to show data react-query or firebase (firestore) please give me a suggestion 

### Your minimal, reproducible example

i can't share my code sorry ,

### Steps to reproduce

1, i have tried to implement react-query offline but it's not working properly 
2, I implemented firestore offline it's working fine but I have a question it's right way or not?

### Expected behavior

i want to check it why my cache data is automatically clear and gives me a blank array like [ ] 
it's working fine with firestore offline but I can't confirm with it, whether is it the right way or not.

### How often does this bug happen?

None

### Platform

android ios 

### Tanstack Query adapter

None

### TanStack Query version

^4.33.0

### Additional context

expo ,react-query ,firebase

**Comment by TkDodo** [comment]
Are you being serious? you just field the same "issue" yesterday:

- https://github.com/TanStack/query/issues/7134

**Comment by miteshdevg** [comment]
@TkDodo Yes please give me response ,
it's right or wrong

**Comment by frederikhors** [comment]
This is not a chat and not an academy. Please stop.

**Comment by miteshdevg** [comment]
Okay i'm sorry but i am stug and i can't find any kind of solution please help me for it
