### ISSUE TITLE
When using PersistQueryClient, staleTime on query is not respected

### ISSUE THREAD

**Issue by ARodSunPower** [TanStack/query#7142]
### Describe the bug

I'm using nextjs output build (static front end assets with no server) for my react site.  Multiple pages.  APIGW backend. 

We use session storage as our persister: 

```
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      gcTime: 1000 * 60 * 60 * 24, // 24 hours max age of session cache
    },
  },
});
//set up react query to keep cache in session storage for cross page loads.
const persister = createSyncStoragePersister({
  storage: typeof window !== "undefined" ? window.sessionStorage : undefined,
});

export default function App({ Component, pageProps }: AppProps) {

  return (
      <PersistQueryClientProvider client={queryClient} persistOptions={{ persister }}>
          <Component {...pageProps} />
      </PersistQueryClientProvider>
  );
}

```

We have set stale time to 3 seconds on the useQuery call: 

```
useQuery({
    queryKey: ["getAsset", id],
    queryFn: async () => getAsset(id),
    enabled: !!id,
    staleTime: 3000,
  });
 ```  
 
 These seems to all work ok, except, the staleTime is completely ignored, and the cached values stick around much longer than the 3 seconds of configured staleTime.  I think either records stick around to the gcTime or maybe some other default.    
 
 How can I force the api call to be made if the cache entry is older than a couple seconds?  

### Your minimal, reproducible example

code inline

### Steps to reproduce

1. Set up persister with sessionStorage 
2. load page to call useQuery and load result into cache.  
3.  wait for more than 3 seconds 
4. load page again to call useQuery and inspect network traffic to see no call is made 

### Expected behavior

I expect useQuery to perform api call when record in cache has passed its stale time.  

### How often does this bug happen?

Every time

### Platform

Seems to happen across os and browser combinations. 

### Tanstack Query adapter

react-query

### TanStack Query version

5.17.19

**Comment by ARodSunPower** [comment]
closing as new info from other code has come up

**Comment by 0xd8d** [comment]
> closing as new info from other code has come up

What new info?
