### ISSUE TITLE
Cached data is sometimes lost

### ISSUE THREAD

**Issue by dieterhoeven** [TanStack/query#7148]
### Describe the bug

Hello! 

- we have an app that uses RQ to display data, also when users have no internet/poor internet, to handle optimistic updates etc.
- we set the `gcTime` of the data to a month
- we want to be able to count on the cached data staying in there for the time specified in `gcTime`, unless of course new data is pulled in from the server that overwrites/modifies it in some way.

What we are experiencing is that the cached data sometimes just disappears, resulting in unexpected behavior.

Could it be that it is related to queries that are put in an error state?
If I trigger a 500 error on a query that is tied to query key, it seems like the data vanishes after a certain amount of time, although I can't seem to pinpoint a consistent moment when it happens, but it seems like having a query in an error state overrides the `gcTime` that we have set on the data. I am, however not able to find any concrete documentation on this behavior, nor a way to alter it.

Any light that could be shed on this situation would be very helpful :)

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/throbbing-brook-ss98q9

### Steps to reproduce

- define query with long `gcTime`
- have it successfully execute and have cached data available
- make it fail
- seems like cached data disappears after x minutes

### Expected behavior

- `gcTime` of data should always be respected even if an error occurs, or it should at least be possible to define ourselves what we want to do in this case

### How often does this bug happen?

Every time

### Platform

- OS: OSX
- Env: React Native

### Tanstack Query adapter

None

### TanStack Query version

v.5.28.4

### TypeScript version

v5.3.3

**Comment by TkDodo** [comment]
looking at your reproduction it's just an unstable query client:

https://tkdodo.eu/blog/react-query-fa-qs#2-the-queryclient-is-not-stable

**Comment by dieterhoeven** [comment]
Hello @TkDodo 

appreciate your comment.
Although not reproduced here, our QueryClientProvider is properly created outside of our main App component and should serve as a stable reference.

The codesandbox example here is not really of much use in it's current form, but the question remains.

**Comment by TkDodo** [comment]
> Could it be that it is related to queries that are put in an error state?

Yes. If you use persistence, only queries in the `success` state are persisted per default.
