### ISSUE TITLE
Solid Query hydrates wrong query key

### ISSUE THREAD

**Issue by PeterDraex** [TanStack/query#7149]
### Describe the bug

I use Solid Query to load a list of items. The list is paginated. Page number is part of the queryKey.

If the user clicks on the "Next page" button before hydratation has completed, the user sees the title "Page 2" but is displayed items that belong to page 1. On window refocus, items for page 2 are fetched and displayed correctly.

In Solid Query dev tools, I can see:
queryKey for page 1 has 0 subscribers ✅, state is inactive ✅, data is null ❌
queryKey for page 2 has 1 subscriber ✅, state is stale ✅, it has data that belong to page 1 ❌

This leads me to believe that when Solid Query receives the data from hydration, it incorrectly assumes that they belong to the current queryKey, which is not necessarily the case. 

### Your minimal, reproducible example

I don't have a repro, but perhaps, a report like this will be sufficient in this case.

### Tanstack Query adapter

solid-query 5.28.5

**Comment by TkDodo** [comment]
please show a reproduction, thanks.

**Comment by PeterDraex** [comment]
🥳 thanks
