### ISSUE TITLE
createQueries prevent SolidStart SSR page from loading

### ISSUE THREAD

**Issue by literalpie** [TanStack/query#7167]
### Describe the bug

In Safari the page fails to load, and in Chrome, the query never leaves a loading state when all of the following are true:

- Solid Query version 5.0.0 or later is installed. (I don't see the issue in `5.0.0-beta.15`, which is what makes me think this is a Tanstack issue, not SolidStart)
- SSR is enabled using SolidStart
- Any component in the page uses `createQueries`

### Your minimal, reproducible example

https://github.com/literalpie/ben-solid-router

### Steps to reproduce

Run the app (`pnpm run dev`) and open it in your browser. The main route will fail to load.

Notice that removing `<CreateQueriesComponent />` from the `App` component allows the app to load.

### Expected behavior

The route should load.

### How often does this bug happen?

Every time

### Platform

macOS 14.4
Safari 17.4
@tanstack/solid-query 5.28.6
solid-js 1.8.16
@solidjs/start ^1.0.0-rc.0

### Tanstack Query adapter

None

### TanStack Query version

5.28.6

**Comment by ardeora** [comment]
Yeah unfortunately `createQueries` primitive does not support SSR currently. But unlike `useQueries` you can implement a SSR supported structure by simply doing 

```tsx

const makeMultipleQueries = () => {
  return Array.from({ length: 100}).map((_, idx) => {
     return createQuery(() = ({...}))
  })
}

const queries = makeMultipleQueries()

```

**Comment by literalpie** [comment]
Could this be documented or could we add a warning of some sort?
