### ISSUE TITLE
Combination of skipToken and useSuspenseQuery not working

### ISSUE THREAD

**Issue by BertVereecken** [TanStack/query#7178]
### Describe the bug

# Context

Our whole application is written at this point with `useQuery`. Recently we refactored our queries to use the new `skipToken` functionality instead of the `enabled` prop. 

Now we would like to move to `Suspense` and thus also use the `useSuspenseQuery` hook.

Unfortunately we see that `skipToken` is not supported in combination with `useSuspenseQuery`, which is kind of a bummer. (see attached image below)

We have a couple of question regarding this:

- Why is this combination not supported (yet) ?
- How can we use conditional queries with `Suspense` at this moment ?
---- Do we need to fallback on the enabled prop ? This would be a downgrade for us since it's less typesafe. We would prefer to use the `skipToken`.

I reproduced the error/behaviour in a codeSandbox (below) and also attached a image with the error.

Thanks in advance for looking into this.

Kind regards
Bert

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/suspense-skiptoken-3mz572?file=%2Fsrc%2Findex.tsx%3A6%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu84nki600063b6hn7e2it5u%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu84nki500023b6hyri3fpla%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu84nki500033b6hxu0mc6b1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu84nki600053b6hdnk39o3n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu84nki500023b6hyri3fpla%2522%253A%257B%2522id%2522%253A%2522clu84nki500023b6hyri3fpla%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu84t0nr00023b6h6iviltp3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clu84urfq00023b6hycpewyhb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu84urfq00023b6hycpewyhb%2522%257D%252C%2522clu84nki600053b6hdnk39o3n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu84nki600043b6hn9sq5lyn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu84nki600053b6hdnk39o3n%2522%252C%2522activeTabId%2522%253A%2522clu84nki600043b6hn9sq5lyn%2522%257D%252C%2522clu84nki500033b6hxu0mc6b1%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu84nki500033b6hxu0mc6b1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

1. By default the `useSuspenseTodo` query will run in the codeSanbox and fail
2. When you enable the `useTodo` and comment the other hook out, it will work correctly.

### Expected behavior

As a user I expect to be able to use the combination of `skipToken` and `useSuspenseQuery`

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/query/assets/47784490/304efe6c-8977-441a-bb9e-a24266d17b12

### Platform

MacOS + latest version of Chrome. Doesn't really matter much.

### Tanstack Query adapter

react-query

### TanStack Query version

5.28.8

### TypeScript version

5.3.3

**Comment by TkDodo** [comment]
`skipToken` is not supported because `enabled` is not supported in suspense queries. We'll probably get there when `use` becomes available, but as of now, this is per design.
