### ISSUE TITLE
The documentation for the @tanstack eslint plugin is inconsistent

### ISSUE THREAD

**Issue by jakobarsement** [TanStack/query#7200]
### Describe the bug

In these docs (https://tanstack.com/query/v4/docs/eslint/eslint-plugin-query) should `@tanstack/query` be `@tanstack/eslint-plugin-query`? This was a little confusing for me on first read. 

![image](https://github.com/TanStack/query/assets/43357341/be13b63d-23d3-4b6e-8356-7d1ba08d93fa)

### Your minimal, reproducible example

https://tanstack.com/query/v4/docs/eslint/eslint-plugin-query#usage

### Steps to reproduce

Go to: https://tanstack.com/query/v4/docs/eslint/eslint-plugin-query#usage

### Expected behavior

I expect this plugin in the example code to be either 1) consistent with the wording of the description above it e.g. both are `@tanstack/eslint-plugin-query` or 2) be more accurately described in the description regarding the relationship between `@tanstack/query` and `@tanstack/eslint-plugin-query`

### How often does this bug happen?

None

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/43357341/be13b63d-23d3-4b6e-8356-7d1ba08d93fa)

### Platform

Google Chrome 

Version 122.0.6261.128 (Official Build) (64-bit)

### Tanstack Query adapter

None

### TanStack Query version

v4 documentation

**Comment by TkDodo** [comment]
afaik, this is eslint plugin convention. See:
- https://eslint.org/docs/latest/use/configure/plugins#configure-plugins

> To configure plugins inside of a configuration file, use the plugins key, which contains a list of plugin names. The eslint-plugin- prefix can be omitted from the plugin name.

**Comment by jakobarsement** [comment]
Can we clarify this for users? It's hard to be aware of every subtle nuance like this when it isn't stated at the time of relevance. @TkDodo

**Comment by TkDodo** [comment]
the code in the docs is copy-paste-able as it is, so what do we need to clarify?

**Comment by jakobarsement** [comment]
thank you for your care on this small matter. i see your points, i just found this a bit frustrating when setting up the eslint plugin and assumed others might too

this might look like an error to someone that is not aware of that eslint doc you linked. my specific scenario: when debugging why eslint was not be behaving as expected, it caused me to doubt the docs' accuracy
