### ISSUE TITLE
Infinite query error when getNextPageParam is not after queryFn

### ISSUE THREAD

**Issue by hosmelq** [TanStack/query#7222]
### Describe the bug

`linksQueryOptions` throw a type error when `getNextPageParam` is not after `queryFn`.

### Your minimal, reproducible example

https://www.typescriptlang.org/play?ssl=35&ssc=5&pln=35&pc=12#code/JYWwDg9gTgLgBAQwB7AgZwDRwN4wJ5gCmcAgiugKJRTRb5GnloBKhakAdmoQL5wBmNEHADkyVGhEBYAFCzZoSLByy4cYB34bgMQgEUAroSh4A8mBiouGVXAPcAkpu27DxvDZlr7hALIGYBEsIDk9vbjcTAGEAG2BCDhhPPkEIYREAAUCuQIBjAGsAeihCBFyYAFoARyMTaTkZDV0ofjLiAAUEAHMNIKsAHgAVAD4VLzgAEyCEAC44QYBtAF1bEEJAuexbNVyDagSYAH0wbsI5jgMQACNjbbgYhDQjk66zuAvr2-GeWR+GpuMrVyxAAMhp8qw0BA9sCxmpgBM5k8oBour95DJCEglPB+AYOOUrPdwWhImYLFY0AAKaBdBAcYAALz6IQciLgyNRcAAPu8DDEYgBKOFwEowPYcdTOBmuWrk4JcKlbcZqBIIK4xQjsgCE2tp9KZLI4bLCajgrxgADksTBOq9OlAECA5kqphscGtAjweFhDggBXa2FgHk9Aw6ncKALyjZVms3AfhwKmehAAOl2+0Sx1OcGGkbgKdTIeep2FsbjZrFErsHAmhC0HC1dzUf2bovW1eLYYQjuEAGo4ABGO4+u4uYD+7u9uaD01qGruADShDwcwWIn1DOZCskWE3hoVJtEcQ4+UkSzncAXJgAYhwXdgXoRw864E+sGhgF0OP6eFGY22VZQJK4joKmFr9HavQKv0YKnpC0JQMCwzDFSbZqAABvu26UoUAAk2DYUabI8IUJ5nhhl5xuWFZmicvZoJsT6jiqtEcl+P4xFRZosbRgojqaf7og0WI4gI+KEiEdjcHBZ40lAdJbsR7KchwXQ8nyAplrYQGSj4TgNjo+hylS5GknK5g7vJikHlYbKCvxMg8EAA

### Steps to reproduce

1. Go to playground
2. Move `getNextPageParam` after `queryFn` and the error should gone

### Expected behavior

Do not throw an error.

### How often does this bug happen?

Every time

### Platform

N/A

### Tanstack Query adapter

react-query

### TanStack Query version

5.28.14

### TypeScript version

5.2.2

**Comment by Andarist** [comment]
On the spot, I'm not sure what `getNextPageParam` depends on - but I assume that it might depend on the return type of `queryFn`. In the reported situation the `queryFn` is context-sensitive (it has unannotated parameters). If we introduce that extra change to the simplified repro above we end up with an issue too:
https://www.typescriptlang.org/play?ts=5.4.4#code/C4TwDgpgBAsiDyAjAVhAxsAPAFQHxQF4oBvAWACgoowAnAewBMBXNCALigAoBDDgZ2A0AlgDsA5gEpC+bAG4KVNHRF8mAW3ZcG3YLyjYpBfADc6QhvPIBfSxSUrgUAGZ06hKDgA0uTnRQc4JFQMHFxDfDJKKHsBKFEwJkciP2QAOlpGFghOACIciUsqFNSY9Wz4xIKKGwoKFzpOSKoM5lYOHnCoAEYAJgBmTwVo5VUNdorgTonU4DoAMSEADwgGTglB6yryOtdGodKxrgmpkQTgGfmllbWN5vpWzQ7pbv6Nqy2gA

**Comment by TkDodo** [comment]
ah got it. I remember there was an open TS issue but I couldn't find it. I think we're fine having this as a known limitation.
