### ISSUE TITLE
'React Example: Nextjs Suspense Streaming' doesn't work

### ISSUE THREAD

**Issue by siyeol97** [TanStack/query#7226]
### Describe the bug

The 'React Example: Nextjs Suspense Streaming' doesn't work on the StackBlitz and CodeSandbox.

### Your minimal, reproducible example

https://tanstack.com/query/latest/docs/framework/react/examples/nextjs-suspense-streaming

### Steps to reproduce

1. Go to https://tanstack.com/query/latest/docs/framework/react/examples/nextjs-suspense-streaming
2. Wait until run - There's an error
3. Go to https://codesandbox.io/p/devbox/github/tanstack/query/tree/main/examples/react/nextjs-suspense-streaming?embed=1&theme=light
4. Wait until run - There's an error

### Expected behavior

The example should work fine.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="1469" alt="image" src="https://github.com/TanStack/query/assets/85405709/83a804ba-3f5f-43bc-ae37-101b81027a57">
<img width="808" alt="image" src="https://github.com/TanStack/query/assets/85405709/36c10940-ef88-4140-88be-a72a3618b3bb">

### Platform

StackBlitz and CodeSandbox on https://tanstack.com/query/latest/docs/framework/react/examples/nextjs-suspense-streaming

### Tanstack Query adapter

None

### TanStack Query version

5.28.14

### TypeScript version

5.2.2

**Comment by TkDodo** [comment]
the example works fine when running it locally. if there is an issue, it is with codesandbox
