### ISSUE TITLE
Docs: Broken links in react suspense guide

### ISSUE THREAD

**Issue by manskron** [TanStack/query#7245]
### Describe the bug

Links to dedicated hooks in react suspense guide do not have correct urls.

### Your minimal, reproducible example

https://tanstack.com/query/latest/docs/framework/react/guides/suspense

### Steps to reproduce

1. Go to https://tanstack.com/query/latest/docs/framework/react/guides/suspense
2. Click on any of the three links in the top to the dedicated hooks.
3. Observe 404.

### Expected behavior

Links should work.

### How often does this bug happen?

Every time

### Platform

OS: MacOS
Browser: Brave

### Tanstack Query adapter

None

### TanStack Query version

v5.29.1

**Comment by TkDodo** [comment]
known issue, we're working on it. All links that go between `react` and `core` are broken since we introduced that distinction.

**Comment by TkDodo** [comment]
this has been fixed.
