### ISSUE TITLE
Dependent useQueries creates too many updates (exceeds maximum update depth)

### ISSUE THREAD

**Issue by joelMuehlena** [TanStack/query#7264]
### Describe the bug

When using react-query together with React and the useQueries hook in a dependent manner like described in the docs I get constant rerenders when setting a state with an object inside useEffect with the useQueries result as dependency.

```js
const [onboardingData, setOnboardingData] = useState<Onboarding | null>(null);
const [testState, setTestState] = useState<{ test: string } | null>(null);
const [testState2, setTestState2] = useState(false);

const { data } = useQuery({
  queryKey: ["gitlab", "123456/nonprod-tenant", "data"],
  queryFn: (): Promise<{ files: string[] }> => {
    return new Promise(resolve => {
      resolve({
        files: ["data.pdf"],
      });
    });
  },
});

const uploadedFilesQueries = useQueries({
  queries:
    data?.files.map(file => {
      return {
        queryKey: ["gitlab", "tmp", "files", file],
        queryFn: () => {
          return new Promise(resolve => {
            resolve({ test: true, data: Math.random() });
          });
        },
      };
    }) ?? [],
});

useEffect(() => {
  console.log("SET", uploadedFilesQueries);
  // Creates constantly retrigger of this very hook the the corresponding useEffect to display
  setOnboardingData({} as any);

  // This works
  setTestState(s => {
    return s;
  });

  // This works
  setTestState2(true);
}, [uploadedFilesQueries]);

useEffect(() => {
  console.log("data", onboardingData);
}, [onboardingData]);

useEffect(() => {
  console.log("testState", testState);
}, [testState]);

useEffect(() => {
  console.log("testState2", testState2);
  setTestState({} as any);
}, [testState2]);
```

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/react-query-issue-v7k28v

### Steps to reproduce

Open the console in the code sandbox and watch how the console is spammed & errors pop up

### Expected behavior

I expected not to create so much renaders but to set the state and the only rerender when the useQueries is refetched

### How often does this bug happen?

Every time

### Platform

- Browser: Chrome, Safari
- Platform: MacOS, CodeSandbox

### Tanstack Query adapter

react-query

### TanStack Query version

5.29.0

### TypeScript version

4.9.5

**Comment by TkDodo** [comment]
the result returned from `useQueries` is not referentially stable, but `data` inside it is.

This is documented here: https://tanstack.com/query/v5/docs/framework/react/guides/render-optimizations#referential-identity

you don't need a `useEffect` to set state depending on a result of a query, you can derive that state. You can also use the `combine` function on `useQueries` in v5.

**Comment by joelMuehlena** [comment]
Alright. Thank you didn't found it in the docs. But maybe also was not reading deep enough. Makes sense now.
