### ISSUE TITLE
[vue-query] `useQueries` type inference issues with `select`, `computed` and `Array.map`

### ISSUE THREAD

**Issue by romansp** [TanStack/query#7270]
### Describe the bug

Using `useQueries` with queries constructed with different combinations of `select`, `computed` and `Array.map` may lose type inference and produce type errors.

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRwK4FMoE8DyYbAQB2AzgDRyonoCKGUw6JcAvnAGZQQhwBEAAjACGpYQGMA1gHoAbhgC0aTFl4AoUJFiI4Y7mFQx0AEwpR07Vhy49ec9GtW7RcIqhAAjTMwC8cANoAjBQATBQAzAC6ANyOxCTwrh5eAErmcL5m7AAUgSHhEQCUMU7xKPRYANLoWOlwWUQAXC5unlAF6QB8-kTRsc5K2ABiRLX1TYmt7d5dWVNdAArWwNQAdGYkEAA2Muj1RX2l1JvoYvC+WUZCwuMtmHNwl8IrMBAAyjAMRADmszEH8ANGD5mkkoCQViAhGB6p06ghVHAysoqlgmn4emQEUiho06vdFtxlug1kwtjs9pjEUcTjAmhcrkIbqD7o8hM83h9gN9ZpiWAV9v9sUCAOrAGAACwgBle6GOp1qEy8EKhMOmcKxA0q1SampRFI15WGOsNRH1fIFgsBTFFEroyjwBDiCtuYOV0JGas1DsIpCy8MRuu12K1WH1AZNxuUwzDcGpp15-L+JQB9BFYvFduw3riNsl0tlNOdoPBkPdsK9+B9JD9BuRQcDoaIBUpwaNrdNTYTAuTQqYAGE9AZjLVdOAh0YsrNYf64GYYKgoCNFWDUuwVjIhJsMG7VTMZ+G66jg3rO1iDzjIziY1SC-GsebVHyk3EU5ggQOx4YjLmpTAZXKzh0Qcv0ne4ZznBclxdEhV3XTdt1LXd1URc8Q0vENr3bdDo1PREHyfVRLVTa100zXBKziD99C-EdgOMUDYWXGDzDgrdiUQj0ugrR1fRnBt0JPZtawvdsYzjGAu27F9exIXMyOzUgqPHH98wA2jP3oqc1SY2CNzYndOODBTqz48oUQE6oY01NtrI7ITzSk-pygCWoqFoYiTJky8gVYfYe01YJXOoTMgT9LyZJUv9b3gAj-PKMIgvct8mDCq0SG8kjbXKYzfOKaTNQAFkSkKUqQNKMtk0jsoo0hIv-QtYvy8oAFZio81KPIqpSaMapzlAANja5LPPKmTuuMOrotyojlAAdiGhhSvCtK5OqniSHGoxpri5QAA4FtCsrOoiqr7Rqja6O-dNf3q+UCJm7AP3cLl0F8NySpM4SgQqigsVHZ6iHQJpWWnM9Z3QedFweBkSSMVAxF2LIhDEMQKGAMCwcRZGxBWfQSHFLJgBWEGAH4Sb4Xh9hQlCIKh7GYmplgKD8CI4CEZh4k+L4Wap1hH0c0pNSel7JrUt7gva0zhoq0WaV+xF-pe4GGVB6naZGVlYfhxHsbRjHqaxlHcaoAmidJ8mAAZebViHILZlGGZQpn-FZ9mQVaHnHZYfmYiAA

### Steps to reproduce

1. Open provided TS playground
2. Inspect type-errors

### Expected behavior

I expected for types to infer and flow through Array.map/computed/useQueries calls.

### How often does this bug happen?

Every time

### Platform

N/A

### Tanstack Query adapter

vue-query

### TanStack Query version

v5.29.0

### TypeScript version

v5.4.5

### Additional context

Same code infers types just fine in `@tanstack/react-query` https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRwK4FMoE8DyYbAQB2AzgDRyonoCKGUw6JcAvnAGZQQhwBEAAjACGpYQGMA1gHoo6IWJgBaNJiy8AUOrHES8IqhAAjTMwC8cANoBGCgCYKAZgC6Abi074K7AGl0WOOYAFEQAXHD6RpgAlAEAfJZEru6iKPRYAGJEAXDBYRHGUDGm8YFF8QAKXCDA1AB0siQQADYAbujBUW7aKdRN6ArZgQAmQsJ5BgVlcCPCtTAQAMowDEQA5qVuybqpmIxm4RMmtSBCYMFxOQjqcDs+fmFeWL5YHWTXtxmhH5mv7739MDeLCinU03W2Xj2AHVgDAABZ0VR4Ag6bL5I4nM5ZYofZGEUiBK43R7PB5pZ6-YlpTJk1Q-IhRN43f4KIEgzbgzxpKzZKi0eh7Qm3Pa0hhMVigzkfWy86iIsUkIWQpii6GwhFpPGo4EcjwfADC3EMwCI6Fl-N2TEJ72VJFVTAo720RhN6DCMyEFyJNzgshgqCgWQ99XQQ1QYnagXkYgowCm3p9cGjtTAVDhgWAtQ9cAA-Dm+LxQYmbn6A1lo25EywKBYnEnmLoVqta0XWOodUA

**Comment by TkDodo** [comment]
can confirm that this is `vue` related (which I don't know enough about, so tagging @DamianOsipiuk). I've removed everything `vue` related and what remains works fine in `react-query`:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRwK4FMoE8DyYbAQB2AzgDRyonoCKGUw6JcAvnAGZQQhwBEAAjACGpYQGMA1gHoo6IWJgBaNJiy8AUOrHES8IqhAAjTMwC8cANoBGCgCYKAZgC6Abi074K7AGl0WOOYAFEQAXHD6RpgAlAEAfJZEru6iKPRYAGJEAXDBYRHGUDGm8YFF8QAKXCDA1AB0siQQADYAbujBUW7aKdRN6ArZgQAmQsJ5BgVlcCPCtTAQAMowDEQA5qVuybqpmIxm4RMmtSBCYMFxOQjqcDs+fmEWiWTXtxmhOVOV3DXo9UzNbQ6zxuvX6MDCw1GQnGkUKFxmQjmi2WwDWpWeLCinU03W2Xj2AHVgDAABYQVAwBboPoDcz5I4nM5ZYqXF5eLC+LBhdmcoFstKZbkCoh8zHYnEeW6E4kkuiqPAEHTZelQEjHU7nFnshWEUiBK43Hn3V68ohRYGvQWWkVmi2ghQYrGbXGeejS0ly7A6nRE0nkynUsHKw6q9VMi7a-C6kj6-mqTlC+N+PmG4WJ7CZUVOzRbV2qKzZKi0N1MfVSpjpvasbEu162QvUT17Mv4ivlki+skUqk0+CYrqS9kOBvF3alpCtkiVpidz24KNK-u514AFhHTfH7enHZlc+9pE7-p7QaXy-ZAGFuIZUehzEWNzGDVv2xQXtojDewgiLk+brIYKgUBZAifxDKgYjtIE8hiBQwBTL+NxwNBtRgFQJKBMAtTfgA-NhfC8NiiGIf+gFZNBbhESwFAWE4SHMLoKyrDRhGsOop61heV43oe3aBrSlCNiWj5xgwbaTjxAa9q+NzvteRDoF+UI-i8f7oABQHTFCoHgZB0GwfBKmIchqEkOhmE4XhAAMLFESRGnkYZVGWLRQjMCqzEUaxS5AA

If you change the import back to `vue-query`, you'll see some red squiggles showing up.
