### ISSUE TITLE
Solid Query: <Suspense> gets stuck in a loading state

### ISSUE THREAD

**Issue by PeterDraex** [TanStack/query#7275]
### Describe the bug

Bug first [reported by charlie](https://discord.com/channels/719702312431386674/1217559935986962542/1217559935986962542) on Discord.

When typing into the input slowly everything works correctly, however spamming keys quickly can sometimes cause it to get stuck in a loading state. I believe it might be a race condition somewhere, as my demo doesn't actually reproduce it quite as reliably as the app I extracted it from.

If I switch to using createResource ([stackblitz](https://stackblitz.com/edit/solidjs-templates-n3phg5?file=src%2FApp.tsx)) directly then I can't reproduce the issue.

### Your minimal, reproducible example

https://stackblitz.com/edit/solidjs-templates-al24pp?file=src%2FApp.tsx

### Steps to reproduce

Spam characters quickly enough to the <input> and some times it will get stuck in the loading state

### Expected behavior

Loading state is resolved within 500 ms

### How often does this bug happen?

Often

### Platform

Chrome 123

### Tanstack Query adapter

solid-query

### TanStack Query version

5.30.1

**Comment by ardeora** [comment]
Hello! Yeah I just reworked the internals of createQuery that fixes a lot of these issues. If you update to v5.30.1+ It should fix the issues. Here it is working https://stackblitz.com/edit/solidjs-templates-xcihcy?file=package.json

**Comment by PeterDraex** [comment]
> Hello! Yeah I just reworked the internals of createQuery that fixes a lot of these issues. If you update to v5.30.1+ It should fix the issues. Here it is working https://stackblitz.com/edit/solidjs-templates-xcihcy?file=package.json

I can still repro this if I type `oi` quickly. Here is a screen recording from your StackBlitz:
https://github.com/TanStack/query/assets/18402223/0e6fb515-a829-4800-acbb-d022c2acce18

**Comment by ardeora** [comment]
Oopsie! Thanks taking a look now

**Comment by ardeora** [comment]
> > Hello! Yeah I just reworked the internals of createQuery that fixes a lot of these issues. If you update to v5.30.1+ It should fix the issues. Here it is working https://stackblitz.com/edit/solidjs-templates-xcihcy?file=package.json
> 
> @ardeora I can still repro this if I type `oi` quickly. Here is a screen recording from your StackBlitz: https://github.com/TanStack/query/assets/18402223/0e6fb515-a829-4800-acbb-d022c2acce18

This is a super weird issue which seems like a SolidJS cleanup issue. Could potentially be upstream but if this is a pressing issue, it seems to be solved if the inner component is wrapped in suspense too

https://stackblitz.com/edit/solidjs-templates-xcihcy?file=src%2FApp.tsx Her is the repro

**Comment by ardeora** [comment]
I'm still investigating this actively and will have some updates soon (hopefully)

**Comment by ardeora** [comment]
Another workaround using reconcile to keep the same DOM node intact

https://stackblitz.com/edit/solidjs-templates-ux7dqi?file=src%2FApp.tsx

**Comment by ardeora** [comment]
Okay fully fixed with existing code https://stackblitz.com/edit/solidjs-templates-wvsree?file=src%2FApp.tsx

**Comment by ardeora** [comment]
> @ardeora Working! Thanks for this and for all the other fixes.

Anytime! ❤️ Thanks for taking the time and filing these issues. SolidQuery is in a much better spot because of these bug fixes
