### ISSUE TITLE
Docs: Broken link on "Installation" page

### ISSUE THREAD

**Issue by eecavanna** [TanStack/query#7278]
### Describe the bug

The "Installation" page of the documentation contains a broken link. That is the case on both GitHub-rendered documentation and on the `tanstack.com`-hosted documentation.

Here's the offending code:

https://github.com/TanStack/query/blob/8469951141199a253cc187090ea865ad1241e066/docs/framework/react/installation.md?plain=1#L57

### Your minimal, reproducible example

https://tanstack.com/query/latest/docs/framework/react/installation

### Steps to reproduce

1. Go to https://tanstack.com/query/latest/docs/framework/react/installation
2. Click on the `ESLint Plugin Query` link shown in the screenshots below
3. See the error message

### Expected behavior

I expected to see information about the ESLint Plugin Query.

### How often does this bug happen?

Every time

### Screenshots or Videos

Broken link on GitHub:

![image](https://github.com/TanStack/query/assets/134325062/cdda86cf-13d7-4cf2-bee0-6fa415971247)

![image](https://github.com/TanStack/query/assets/134325062/4ccbeab7-aaab-4183-a06b-1550cbf81761)

Broken link on`tanstack.com`:

<img width="886" alt="image" src="https://github.com/TanStack/query/assets/134325062/4b79d1fb-83b4-445d-acc6-9aae3a3adb65">

<img width="1015" alt="image" src="https://github.com/TanStack/query/assets/134325062/9aeba1af-ae18-4359-8346-5601d64e67aa">

### Platform

- Latest Brave
- Latest Firefox

### Tanstack Query adapter

None

### TanStack Query version

Not applicable

### Additional context

It took me a few minutes to fill out this form. I recommend creating a dedicated template for documentation-related issues.

**Comment by TkDodo** [comment]
it is known

- #7245
