### ISSUE TITLE
Docs : Remove ‘$’ from Installation Commands in Documentation

### ISSUE THREAD

**Issue by Mandeep56Singh** [TanStack/query#7293]
I’ve been using the React Query library and found the documentation to be very helpful. However, I noticed that the installation commands in the documentation include a dollar sign (‘$’) at the beginning. For example:

$ npm install react-query

When copying the command from the documentation and pasting it into the terminal in these IDEs, the dollar sign is also copied. This leads to an invalid command for those users who use IDE like VS code  with bash terminal which already provide you with "$".

I suggest removing the dollar sign from the commands in the documentation 

This small change could greatly improve the user experience for developers who copy paste fast like me.

Thank you for considering this issue.

### Your minimal, reproducible example

https://tanstack.com/query/v3/docs/framework/react/installation

### Steps to reproduce

1.Go to Installation Page  i.e. [https://tanstack.com/query/v3/docs/framework/react/installation]()
2.Copy the Installation command i.e `$ npm i react-query`
3.Open your IDE terminal like  VS Code terminal , Paste it 
4.Run the command and see the issue 

### Expected behavior

Installation Command should not include "$" sign

### Screenshots 

This is the documentation page 

![Screenshot (145)](https://github.com/TanStack/query/assets/139469106/f5b86a51-4317-4b4b-991e-7284e8acf082)

After copy , Your terminal doesn't recognize it as bash command due to additional dollar sign
![Screenshot (146)](https://github.com/TanStack/query/assets/139469106/2b50cce3-5132-4070-9b3e-1da3646ca16e)

### Platform

OS: Windows

### Tanstack Query adapter

None

### TanStack Query version

latest

I can contribute to this if you want . This will be my tribute to TanStack community

**Comment by TkDodo** [comment]
yes please just file a docs PR instead of an issue if you want to contribute, thanks.
