### ISSUE TITLE
Wrong inferring in useInfiniteQuery

### ISSUE THREAD

**Issue by ArianHamdi** [TanStack/query#7301]
### Describe the bug

In `useInfiniteQuery`, the`queryFn` randomly infers `unknown` instead of the actual data type.

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCSA7AZsbYGdARWXSgE84BfOXKCEOAcgAEYBDbVLgYwDWAeijpOfGAFoAjuSosA3AFgAUKtXoAHpFhw+EHvDToAwmhhMAEhAgCAjHAC8cABQBKJwD5EquHFEwyFDYKBg4+ITEZBSULgi+fnCyMQDS6JQAXHAA2ix85kwsALoANAl+BETAnAA2AAqcAOboDVCcIFkADGUqiXDNMAByWjANza3tWS41nLxj6B6O3t3lcEJCBLgUKNgC2BAA7tiryVQAYthTSDSL3vG9ff7ogcE5diVwAEwfAMxFqzQen4bsoVDRQRptNB4PpDKFTAUQNZbJ8nK5bj4HgEgiFjOFKlE5LF7n1TpQ0pkcnlEcUgYkCdV6k0Wpw2h04CsHn4BsNNKNmRN2dNZvzmhjOX11qIQBAAG7oOAAE3QvCgyAkQXQq3Wm222GQIAARhRsv8uUkiRcphiSY9sa9su8vr8zX1AQkQapweoVFodDCDLx4WZeFYbAIfmj3F5MX57biwngCaQiXFtUIZfKLTELnALHmABYKixgdO6qBwfVGk2uxJkq2ua421Zx544t4fb5wP4Aul+MkUrK5fKhkC01YM2rzQVdPv9Z680UstlTGZzZnij1uUHgoA

### Steps to reproduce

Hover over `queryFn` in `useCustomHook1`. The inferred type is `unknown`, but it is inferred correctly in `useCustomHook2` and `useCustomHook3`.

### Expected behavior

It should always infer correctly.

### How often does this bug happen?

Sometimes

### Screenshots or Videos

<img width="846" alt="image" src="https://github.com/TanStack/query/assets/59548833/4fb72107-8546-4008-ae17-e207b115adb4">

### Platform

Doesn't matter

### Tanstack Query adapter

react-query

### TanStack Query version

5.29.2

### TypeScript version

5.4.5

**Comment by TkDodo** [comment]
order matters:
- https://github.com/TanStack/query/issues/7222

**Comment by ArianHamdi** [comment]
> order matters:
> 
> * [Infinite query error when getNextPageParam is not after queryFn #7222](https://github.com/TanStack/query/issues/7222)

Actually destructuring in `queryFn` is breaking inferring which I don't understand why this is happening.

<img width="396" alt="image" src="https://github.com/TanStack/query/assets/59548833/4ad097ed-d57c-4ab2-b5e0-20a861c58784">

**Comment by TkDodo** [comment]
also part of the typescript limitation. it's outlined in the reproduction in the linked issue.
