### ISSUE TITLE
docs: search doesn't work

### ISSUE THREAD

**Issue by tryonelove** [TanStack/query#7306]
### Describe the bug

Hello,

Search on the docs doesn't work at all,
Seems like something wrong with search provider, it doesn't return any results in the response body.

### Your minimal, reproducible example

-

### Steps to reproduce

1. Go to https://tanstack.com/query/latest/docs/framework/react/overview
2. Try to search something

### Expected behavior

Search results show up

### How often does this bug happen?

Every time

### Screenshots or Videos

![chrome_jG4vJigL0j](https://github.com/TanStack/query/assets/20541870/aaa61b7c-839f-40b7-8009-923754bb8fb2)

Search results for `usequery`:
![image](https://github.com/TanStack/query/assets/20541870/3b6a919a-f4a5-444a-a870-71022ed69a59)
![image](https://github.com/TanStack/query/assets/20541870/af944885-76fd-41dd-a8d9-46ab75958842)

### Platform

- OS: Windows 11
- Chrome 123

### Tanstack Query adapter

react-query

### TanStack Query version

v5

**Comment by TkDodo** [comment]
search has been fixed. if this comes up again, please file an issue in the docs repo:
- https://github.com/TanStack/tanstack.com
