### ISSUE TITLE
Docs website doesn't work in Brave

### ISSUE THREAD

**Issue by mmiller42** [TanStack/query#7307]
### Describe the bug

Sorry to be the person who opens this kind of issue, but I wanted to call attention to it, because I just did a whole talk today on Tanstack-Query to a team starting on a greenfield react-native project, and would love to be able to link to the documentation. The documentation website doesn't work in Brave Browser, even with the "shield" disabled.

### Your minimal, reproducible example

https://tanstack.com/query/latest/docs/framework/react/overview

### Steps to reproduce

1. Go to https://tanstack.com/query/

### Expected behavior

Docs website should load

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="100%" src="https://github.com/TanStack/query/assets/11927375/739e6236-9e8e-4597-985d-5a2bb778d1cd" />

<img width="100%" src="https://github.com/TanStack/query/assets/11927375/ab1e701b-c4ef-49e1-bd2a-23377b71bcf9" />

### Platform

- OS: macOS
- Browser: Brave Browser
- Version: 1.65.114 Chromium: 124.0.6367.60 (Official Build) (arm64)

### Tanstack Query adapter

None

### TanStack Query version

n/a

**Comment by ZJTAN97** [comment]
I think its not limited to Brave, I am experiencing it on Chrome and Edge as well.

The other documentation sites from TanStack are also facing the same issue.

https://tanstack.com/form/latest
https://tanstack.com/router/latest

![image](https://github.com/TanStack/query/assets/68308477/8fc82fa6-2e0c-4b54-9bbc-5c6a04530720)

**Comment by TkDodo** [comment]
the error is fixed. if something comes up again, please file in the docs repo:
- https://github.com/TanStack/tanstack.com
