### ISSUE TITLE
Docs website is down

### ISSUE THREAD

**Issue by SofianeDjellouli** [TanStack/query#7314]
### Describe the bug

Console says there is a React error

### Your minimal, reproducible example

none

### Steps to reproduce

go to https://tanstack.com/query/latest 

### Expected behavior

Website works

### How often does this bug happen?

None

### Screenshots or Videos

<img width="1440" alt="image" src="https://github.com/TanStack/query/assets/38258952/2899bc08-c534-44f0-af93-24318dbf4446">

### Platform

Firefox and Chrome

### Tanstack Query adapter

None

### TanStack Query version

not known

**Comment by samuellawrentz** [comment]
Still down

**Comment by samuellawerentz** [comment]
You can use https://web.archive.org/ to view archived pages until the site is up.

**Comment by TkDodo** [comment]
https://github.com/TanStack/query/issues/7307#issuecomment-2067599677
