### ISSUE TITLE
Docs: Error on migration guides

### ISSUE THREAD

**Issue by wanjas** [TanStack/query#7319]
### Describe the bug

Hello,

Migration guides are broken. Looks like they miss some plugin for the code viewer. 

> Language `diff` is not included in this bundle. You may want to load it from external source.

https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v3
https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v4
https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5

### Your minimal, reproducible example

https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5

### Steps to reproduce

Go to any of the following pages

https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v3
https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v4
https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5

### Expected behavior

See docs

### How often does this bug happen?

None

### Platform

Any browser

### Tanstack Query adapter

None

### TanStack Query version

5

**Comment by TkDodo** [comment]
this needs to be fixed in the tanstack.com repo
