### ISSUE TITLE
isLoading does not exist on useMutation @tanstack/vue-query

### ISSUE THREAD

**Issue by benlutz** [TanStack/query#7331]
### Describe the bug

the `isLoading` property is missing on the `useMutation` Result

```
Property 'isLoading' does not exist on type 'UseMutationReturnType<Response, Error, void, unknown, MutationResult<Response, Error, void, unknown>>'.ts(2339)
```

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/silent-dream-wcczzk?file=%2Fsrc%2FApp.vue

### Steps to reproduce

1. Follow the docs, by using this code snipped:
```
const { isLoading, isError, error, isSuccess, mutate } = useMutation({
  mutationFn: (newTodo) => axios.post('/todos', newTodo),
})
```
2. Try to use `isLoading`.

### Expected behavior

I expect `isLoading` to be either `true` or `false`.

### How often does this bug happen?

Every time

### Platform

- OS: Mac OS 14.4.1
- Browser: Chrome 124.0.6367.60

### Tanstack Query adapter

vue-query

### TanStack Query version

5.31.0

### TypeScript version

5.4.5

### Additional context

it seems like also `status` is missing `loading`

**Comment by benlutz** [comment]
It seems like also `status` is missing `loading`

**Comment by issam-seghir** [comment]
I have a similar problem using `status `from `useIfiniteQuery ` doesn't have `"pending"` or `"loading" `




 ![Image](https://github.com/user-attachments/assets/6dcd6440-9ae4-47cc-9619-7ba1c61a2a7e)
