### ISSUE TITLE
Entire website is down

### ISSUE THREAD

**Issue by SwapnilSoni1999** [TanStack/query#7339]
### Describe the bug

I've visited https://tanstack.com/query
and the website loaded just for a second and suddenly white page is showing.

Here's the following error I'm getting currently

![image](https://github.com/TanStack/query/assets/25403317/e95a955e-36d4-450c-95ce-095688fccef9)

### Your minimal, reproducible example

https://tanstack.com/query

### Steps to reproduce

described in description.

### Expected behavior

Should Load the website.

### How often does this bug happen?

None

### Platform

any machine

### Tanstack Query adapter

react-query

### TanStack Query version

latest

**Comment by TkDodo** [comment]
those are most often caused by browser extensions. Everything works on my end.
