### ISSUE TITLE
Allow to pass nonce to ReactQueryStreamedHydration

### ISSUE THREAD

**Issue by hey-kevin** [TanStack/query#7352]
### Describe the bug

Hello, many thanks for your hard work!

We are introducing the app router to some of our pages and we decided to use react-query with `<ReactQueryStreamedHydration />` to do pre-fetch in SSR.

I understand the query result in the server is later hydrated in the client through the inline script tag created by `useServerInsertedHTML` in [UseClientHydrationStreamProvider](https://github.com/tanstack/query/blob/main/packages/react-query-next-experimental/src/HydrationStreamProvider.tsx#L68)

My issue is that my CSP configuration with nonce prevents this inline script from running - hence the same query runs on the client 😭 (our CSP configuration is mostly copied from [here](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy#adding-a-nonce-with-middleware)).

**Here is my ask:**
Can we open a new prop called `nonce` for `<ReactQueryStreamedHydration />` much similar to `<ReactQueryDevtools />`'s `styleNonce` prop to make sure the inline script gets executed properly?

Here is a screenshot of html generated from next.js with csp middleware implementation - as you can see only this inline tag did not get the blessing of nonce injection :(
![image](https://github.com/TanStack/query/assets/141622178/8069ad19-49a0-4ccb-bedf-5e49d9f18489)

### Your minimal, reproducible example

https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy#adding-a-nonce-with-middleware

### Steps to reproduce

1. Add a content security policy header for script-src that expects a nonce like the example above.
2. Include <ReactQueryStreamedHydration />
3. Use useSuspenseQuery in the client component to fetch some data
4. See the console log like this 
![image](https://github.com/TanStack/query/assets/141622178/95d2a5eb-291d-4e79-a60a-6229a7954cc7)

### Expected behavior

The troublesome inline tag generated by `ReactQueryStreamedHydration` gets executed properly.

### How often does this bug happen?

Every time

### Platform

OS: MacOS
Browser: Version 124.0.6367.79 (Official Build) (arm64)

### Tanstack Query adapter

react-query

### TanStack Query version

v5.17.9

### Additional context

FYI my @tanstack/react-query-next-experimental version is 5.20.5, but I don't see any nonce related implementation in the latest version of the source code

**Comment by TkDodo** [comment]
Yes, do you want to PR it?

**Comment by TkDodo** [comment]
@hey-kevin if this is still important to you, please file a PR. Otherwise, I'll close this issue as stale.

**Comment by hey-kevin** [comment]
@TkDodo hey! Sorry I think I missed your comment. Yes I will create a PR soon (probably in a week or two)!

**Comment by hey-kevin** [comment]
@TkDodo just created a PR https://github.com/TanStack/query/pull/7575 for this issue, thx in advance!
