### ISSUE TITLE
queryOptions is not in @tanstack/react-query

### ISSUE THREAD

**Issue by abarbosa-godaddy** [TanStack/query#7374]
### Describe the bug

The doc mentions the following function.

https://tanstack.com/query/latest/docs/framework/react/guides/query-options

I can't import it though. 

I get the following message `'"@tanstack/react-query"' has no exported member named 'queryOptions'. Did you mean 'QueryOptions'?`

### Your minimal, reproducible example

N/A

### Steps to reproduce

on version 4.29.25, try to import `queryOptions` function

### Expected behavior

It should export the function.

### How often does this bug happen?

None

### Platform

MacOS M3

### Tanstack Query adapter

react-query

### TanStack Query version

4.29.25

**Comment by TkDodo** [comment]
This is a v5 feature.
