### ISSUE TITLE
404 page in the documentation

### ISSUE THREAD

**Issue by p-pey** [TanStack/query#7395]
### Describe the bug

at end of the this document [https://tanstack.com/query/v4/docs/reference/QueryCache](page), there is a link to [https://tanstack.com/query/v4/docs/reference/QueryCache/framework/react/community/tkdodos-blog#18-inside-react-query](community) that it is not exist

### Your minimal, reproducible example

https://tanstack.com/query/v4/docs/reference/QueryCache/framework/react/community/tkdodos-blog#18-inside-react-query

### Steps to reproduce

 link that missing: 
https://tanstack.com/query/v4/docs/reference/QueryCache/framework/react/community/tkdodos-blog#18-inside-react-query

### Expected behavior

should open community page

### How often does this bug happen?

Every time

### Platform

Windows 10 - google chrome

### Tanstack Query adapter

None

### TanStack Query version

4

**Comment by p-pey** [comment]
Doc Link: https://tanstack.com/query/v4/docs/reference/QueryCache

**Comment by TkDodo** [comment]
yeah the links are fixed for `v5` and `latest`, but not `v4`. @fulopkovacs is that something we could port back to the `v4` branch ?

**Comment by TkDodo** [comment]
oh, I see we already have a draft PR?

- https://github.com/TanStack/query/pull/7398

**Comment by fulopkovacs** [comment]
> yeah the links are fixed for `v5` and `latest`, but not `v4`. @fulopkovacs is that something we could port back to the `v4` branch ?

> oh, I see we already have a draft PR?
> 
> https://github.com/TanStack/query/pull/7398

Yes, I'm already working on it! ☺️

**Comment by rschubkegel** [comment]
Links still seem to be broken... found on this [this page](https://tanstack.com/query/v4/docs/framework/react/reference/useInfiniteQuery).

The "useQuery hook" link points to `https://tanstack.com/query/v4/framework/react/reference/useQuery` instead of `https://tanstack.com/query/v4/docs/framework/react/reference/useQuery` (missing `docs` directory).

**Comment by TkDodo** [comment]
@rschubkegel we switched frameworks (from remix to tanstack start) a while ago and all links needed to be changed. We did that for the latest version (v5), but I haven’t had the time or energy to do that for v4 and v3, too.

If it’s important to you, please a file a PR to the `v4` branch, but I’m not gonna do it.
