### ISSUE TITLE
[angular] isPending type isn't typed as Signal

### ISSUE THREAD

**Issue by k3nsei** [TanStack/query#7401]
### Describe the bug

When I want to use `isPending` from mutation I'm getting wrong type. It's returning calculated signal but type is wrongly resolved to boolean. It's also happening to some other properties but I'm using only `isPending` in my project also I don't remember what others were that weren't working correctly.

### Your minimal, reproducible example

https://stackblitz.com/edit/stackblitz-starters-1t77xr?file=src%2Fmain.ts

### Steps to reproduce

```typescript
import { Injectable, Signal } from "@angular/core";
import { injectMutation } from "@tanstack/angular-query-experimental";

@Injectable()
export class Service {
  protected readonly mutation = injectMutation(() => ({
    mutationFn: () => Promise.resolve({}),
  }));

  // TypeScript Error: `boolean` is not assignable to type `Signal<boolean>`
  public readonly isProcessing: Signal<boolean> = this.mutation.isPending;
}
```

### Expected behavior

`isPending` should be resolved to type `Signal<boolean>`

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/190422/5654e3a0-b02a-4db1-9ab6-6f871acbcd1b)

### Platform

- OS: Windows
- Browser: not important
- Version: not important

### Tanstack Query adapter

angular-query

### TanStack Query version

v5.35.3

### TypeScript version

v5.4.5

**Comment by TkDodo** [comment]
@arnoud-dv FYI
