### ISSUE TITLE
useQuery get stuck in case of throw error on queryFn

### ISSUE THREAD

**Issue by Devecor** [TanStack/query#7411]
### Describe the bug

useQuery will keep in pending when I mock a http call with nock:
<img width="1904" alt="image" src="https://github.com/TanStack/query/assets/29839447/38fba582-5933-4e6a-8a73-1269717b88b0">

and `return Promise.reject()` will also get it stuck in pending.

### Your minimal, reproducible example

https://github.com/Devecor/test-react-query

### Steps to reproduce

1. please refer this dedicated repo to reproduce: https://github.com/Devecor/test-react-query
2. and the github actions test shows how it failed: https://github.com/Devecor/test-react-query/actions/runs/9034787406/job/24828135597

### Expected behavior

useQuery finished with `error` status

### How often does this bug happen?

None

### Screenshots or Videos

<img width="1904" alt="image" src="https://github.com/TanStack/query/assets/29839447/38fba582-5933-4e6a-8a73-1269717b88b0">

### Platform

- node 20
- "@tanstack/react-query": "^5.35.5"
- "react": "^18.3.1"
- "react-dom": "^18.3.1"

### Tanstack Query adapter

react-query

### TanStack Query version

5.35.5

**Comment by TkDodo** [comment]
Judging from the screenshot, you run into the default retries and they take too long for a test with exponential backoff. Turn off retries in tests: https://tkdodo.eu/blog/testing-react-query#turn-off-retries

**Comment by Devecor** [comment]
Thanks! that works. I'l close this
