### ISSUE TITLE
Unable to pass queryOptions to QueriesObserver (TypeScript error)

### ISSUE THREAD

**Issue by yannickcr** [TanStack/query#7446]
### Describe the bug

When passing options created with the `queryOptions` helper to `QueriesObserver` we got the following TypeScript error as it is unable to assign `UseQueryOptions` to `QueryObserverOptions`:

```ts
Type 'UseQueryOptions<string, Error, string, string[]> & { initialData?: undefined; } & { queryKey: DataTag<string[], string>; }' is not assignable to type 'QueryObserverOptions<unknown, Error, unknown, unknown, QueryKey, never>'.
  Types of property 'refetchInterval' are incompatible.
    Type 'number | false | ((query: Query<string, Error, string, string[]>) => number | false | undefined) | undefined' is not assignable to type 'number | false | ((query: Query<unknown, Error, unknown, QueryKey>) => number | false | undefined) | undefined'.
      Type '(query: Query<string, Error, string, string[]>) => number | false | undefined' is not assignable to type 'number | false | ((query: Query<unknown, Error, unknown, QueryKey>) => number | false | undefined) | undefined'.
        Type '(query: Query<string, Error, string, string[]>) => number | false | undefined' is not assignable to type '(query: Query<unknown, Error, unknown, QueryKey>) => number | false | undefined'.
          Types of parameters 'query' and 'query' are incompatible.
            Type 'Query<unknown, Error, unknown, QueryKey>' is not assignable to type 'Query<string, Error, string, string[]>'.
              Types of property 'queryKey' are incompatible.
                The type 'QueryKey' is 'readonly' and cannot be assigned to the mutable type 'string[]'.
```

### Your minimal, reproducible example

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgRQK4FMoE8DCAbYdAOxgBoUNsB5AIwGdMA3TctTQu2hqZqcgR0pYqYGMAhE6cAL5wAZlAgg4AcgACMAIaStAYwDWAeijpNumAFpBmLCoBQd3RLrxr2fIRJwAvHCLoAdwobD2IYAAoASgBuBycdOBh0FzZsHzg3YVFxSXCEOzgMoQBpdCwALjgAbRUQW3IVfTKVAF1SAqKbADEiSs06LCJdOCifAD5VOrhGTTwMFXbpSLjneDqu4CgXLiZMdP8g1OF6XahwzNCSciSUoRiOwsfCx1W4OoBldHiAEx2ePd8B2CUA4f145yElzI1RuMCOLXuTyRyJRqLR6IxhkMcAAenA6AALCCoPDfPwQeCYRRQFYJOoAFQJm1+J3+UH2gWBoNZ4IuBDC5Cq+UKmVKFWqtXqqiatjaHUyPT6AyGI0i40mWGms3miwR0SAA

### Steps to reproduce

In the playground, see that `QueryObserver` accepts `testQuery` as options and that `myFirstObserver` type is correctly inferred to `QueryObserver<string, Error, string, string, string[]>`.

However `QueriesObserver` errors when passing `testQuery` as options. If we inline the object then we have no errors.

Also `QueryObserverResult` is not properly inferred (`TData` is always `unknown`) even when passing the options as an inline object (I can open another issue for this point if needed).

No issue at runtime, the code is working as expected.

### Expected behavior

We should be able to pass the result of the `queryOptions` helper to `QueriesObserver` and have `QueryObserverResult` properly inferred.

Quoting the documentation on https://tanstack.com/query/latest/docs/reference/QueriesObserver#queriesobserver:

> The options for the `QueriesObserver` are exactly the same as those of [useQueries](https://tanstack.com/query/latest/docs/framework/react/reference/useQueries).

So, from what I understand, the `queryOptions` helper here should work too (and as you can see in the playground above, it actually works with `QueryObserver`, but not `QueriesObserver`).

### How often does this bug happen?

Every time

### Platform

- macOS
- Chrome 124

### Tanstack Query adapter

react-query

### TanStack Query version

v5.36.2

### TypeScript version

v5.4.5

**Comment by yannickcr** [comment]
> usually not necessary because @tanstack/react-query re-exports everything from the query-core.

Noted 👍 

> I don't know rxjs much but are you unsubscribing the observer correctly?

No, but I do not want to unsubscribe (our project is a bit particular on this point, but I think this is not important for our problem here 🙂)

> The type are slightly different for each adapter

That's a good explanation (it raise a lot of other questions, but I'll open a discussion because that's a bit out of scope here 😅).

> A bit of both probably 😂 . If the widening to <any, any, any, any> works, I'd accept a PR for that.

Haha. Ok 😄. The widening to `<any, any, any, any>` works as it solve the TS error, but of course we miss the inference of the results. It's a good quick fix for now I suppose. I can submit a PR for this.

**Comment by TkDodo** [comment]
ah, if we miss inference then it's no good :/

**Comment by yannickcr** [comment]
By missing inference I mean that in the playground above the types of `mySecondObserver` and `myThirdObserver` will be `QueriesObserver<QueryObserverResult[]>`

(instead of `QueriesObserver<[QueryObserverResult<string, Error>]>` that would have been ideal but require more work)

**Comment by TkDodo** [comment]
ah okay, then let's do that to make it at least passable ...
