### ISSUE TITLE
ReactQueryDevtoolsPanel no longer exists in v5

### ISSUE THREAD

**Issue by marcuslindfeldt** [TanStack/query#7462]
### Describe the bug

More of an undocumented regression. In v4 you could import `ReactQueryDevtoolsPanel` like so `import { ReactQueryDevtoolsPanel } from "@tanstack/react-query-devtools";` and use it as a controlled component. This is good for anyone that builds their own devtools and don't want multiple devtools buttons taking up space in the dev environment.

This is no longer possible in v5 and there is no mention of this breaking change.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/musing-roman-s8thth

### Steps to reproduce

1. try and import ReactQueryDevtoolsPanel with `import { ReactQueryDevtoolsPanel } from "@tanstack/react-query-devtools";`
2. Watch it fail

### Expected behavior

1. try and import ReactQueryDevtoolsPanel with `import { ReactQueryDevtoolsPanel } from "@tanstack/react-query-devtools";`
2. Watch it succeed 😉 

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 124.0.6367.62

### Tanstack Query adapter

react-query

### TanStack Query version

5.36.2

### TypeScript version

5.2.2

**Comment by TkDodo** [comment]
we know about this, and @ardeora has it on his list of things to add:

- https://github.com/TanStack/query/discussions/6564#discussioncomment-8593608

**Comment by Ephem** [comment]
This was fixed by a contribution from @toofff in [v5.54.0](https://github.com/TanStack/query/releases/tag/v5.54.0)! 🎉
