### ISSUE TITLE
[react-query][Bug?]When invalidating useSuspenseQuery queries with invalidateQueries, the refetch process does not run.

### ISSUE THREAD

**Issue by yanachuwan9sm** [TanStack/query#7558]
### Describe the bug

When the complete button is pressed, the query is disabled and getTodo is not executed when it should be fetching data again in the background. (Check out codesandbox!)

### Your minimal, reproducible example

[codesandbox](https://codesandbox.io/p/sandbox/usesuspensequery-refetch-example-rst2nj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxclpkta00073b6rjby5ih32%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxclpkt900033b6r6ndc5c8i%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxclpkt900043b6rroqtzza4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxclpkt900063b6rvrkvbu77%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B48.67812596641969%252C51.32187403358031%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxclpkt900033b6r6ndc5c8i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxclpkt900023b6ru4p75mu2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Ftodo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxclqkqm003h3b6r8miplnse%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxclpkt900033b6r6ndc5c8i%2522%252C%2522activeTabId%2522%253A%2522clxclqkqm003h3b6r8miplnse%2522%257D%252C%2522clxclpkt900063b6rvrkvbu77%2522%253A%257B%2522id%2522%253A%2522clxclpkt900063b6rvrkvbu77%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxclpkt900053b6rv1q9u7r4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxclpkt900053b6rv1q9u7r4%2522%257D%252C%2522clxclpkt900043b6rroqtzza4%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxclpkt900043b6rroqtzza4%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1 Click on the complete button
2 Please check the console in DevTools

### Expected behavior

I want the following console log to be displayed when the complete button is pressed.

> If the query is currently being rendered via useQuery or related hooks, it will also be refetched in the background
> https://tanstack.com/query/latest/docs/framework/react/guides/query-invalidation

```bash
### getTodo
------------------------------------------------------------------------
### completeTodo
------------------------------------------------------------------------
### getTodo
------------------------------------------------------------------------
```

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/query/assets/95360878/ab7e6b5b-a08d-4dfc-933a-7fbabe9bc140

### Platform

N/A

### Tanstack Query adapter

react-query

### TanStack Query version

v5.28.6

### TypeScript version

v4.4.4

**Comment by TkDodo** [comment]
you're not importing `getTodoQueryKey` in the file that executes the mutation. The TypeScript error you see is in your sandbox is there for a reason ...

https://codesandbox.io/p/sandbox/usesuspensequery-refetch-example-forked-8fwz68?file=%2Fsrc%2FTodo%2Fuse-complite-todo.ts%3A4%2C26
