### ISSUE TITLE
"React Example: Nextjs Suspense Streaming" doesn't work

### ISSUE THREAD

**Issue by c1tru55** [TanStack/query#7604]
### Describe the bug

example doesn't work:
https://tanstack.com/query/latest/docs/framework/react/examples/nextjs-suspense-streaming

> ative addon because loading addons is disabled: /home/projects/qgniggnjz.github/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node
 ⚠ Attempted to load @next/swc-linux-x64-musl, but an error occurred: Cannot load native addon because loading addons is disabled: /home/projects/qgniggnjz.github/node_modules/@next/swc-linux-x64-musl/next-swc.linux-x64-musl.node
 ⨯ Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc

### Your minimal, reproducible example

https://tanstack.com/query/latest/docs/framework/react/examples/nextjs-suspense-streaming

### Steps to reproduce

.

### Expected behavior

.

### How often does this bug happen?

None

### Platform

.

### Tanstack Query adapter

None

### TanStack Query version

.

**Comment by TkDodo** [comment]
probably an upstream issue with stackblitz. it works fine in codesandbox.

https://codesandbox.io/p/devbox/github/tanstack/query/tree/main/examples/react/nextjs-suspense-streaming?embed=1&theme=dark
