### ISSUE TITLE
invoking `suspense()` with `enabled: false` will wait infinite while ssr

### ISSUE THREAD

**Issue by n0099** [TanStack/query#7609]
### Describe the bug

```js
const enabled = ref(false);
const { data, suspense } = useInfiniteQuery({ enabled })
await suspense()
```

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/eloquent-frog-3w6pk9?file=%2Fapp.vue

### Steps to reproduce

0. By default the preview will never end loading
1. Change the line in `/app.vue`
```diff
-const enabled = ref(false);
+const enabled = ref(true);
```
2. Refresh preview

### Expected behavior

Instantly exit `suspense()` as there's nothing to fetch while ssr.

### How often does this bug happen?

Every time

### Platform

`nuxt^3.5.2`
Windows 11
Chrome 126

### Tanstack Query adapter

vue-query

### TanStack Query version

5.45.0

### Additional context

This only reproducible when using `useInfiniteQuery()`, `useQuery()` is not affected:
```diff
-const { data, suspense } = useInfiniteQuery({
+const { data, suspense } = useQuery({
  queryKey: ['test'],
  queryFn: fetcher,
-  initialPageParam: '',
-  getNextPageParam: () => '',
  enabled
})
```

**Comment by DamianOsipiuk** [comment]
@n0099 This is done on purpose in response to an old ticket, where this particular behavior was requested.

And since it's rather easy to skip `suspense()`  call with condition during SSR, it currently supports both use-cases.

Related tickets:
- https://github.com/TanStack/query/issues/4924
- https://github.com/DamianOsipiuk/vue-query/issues/229

**Comment by n0099** [comment]
https://github.com/TanStack/query/issues/4924#issuecomment-1419577999
```ts
onServerPrefetch(async () => { // https://github.com/TanStack/query/issues/7609
    if (toValue(toValue(options)?.enabled) ?? true)
        await ret.suspense();
});
```

**Comment by n0099** [comment]
How do I make this compatible with https://github.com/TanStack/query/pull/7566 that introduced a param `query` to the callback variant of `enabled?`
