### ISSUE TITLE
Vercel build error when using HydrationBoundary

### ISSUE THREAD

**Issue by chertik77** [TanStack/query#7611]
### Describe the bug

```typescript
const DashboardPage = async () => {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery({
    queryKey: ['profile'],
    queryFn: userService.getProfile
  })

  return (
    <HydrationBoundary state={dehydrate(queryClient)}>
      <Header />
    </HydrationBoundary>
  )
}

export default DashboardPage
``` 

```typescript
'use client'

import { useQuery } from '@tanstack/react-query'

import { userService } from '@/services/user.service'

export const Header = () => {
  const { data } = useQuery({
    queryKey: ['profile'],
    queryFn: userService.getProfile
  })

  return <div>{data?.name}</div>
}
``` 

And when i'm deploying on vercel i'm getting this error: 

```
 ⨯ Static worker exited with code: null and signal: SIGTERM
> Build error occurred
Error: Static page generation for /dashboard is still timing out after 3 attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
```

### Your minimal, reproducible example

.

### Steps to reproduce

See the code above

### Expected behavior

Successful production build

### How often does this bug happen?

Every time

### Platform

macOS, Arc Browser

### Tanstack Query adapter

react-query

### TanStack Query version

5.45.1

### TypeScript version

5

**Comment by TkDodo** [comment]
try:

```diff
- queryFn: userService.getProfile
+ queryFn: () => userService.getProfile()
```

in the server component. If that's not helping, I need to see a minimal reproduction please.

**Comment by chertik77** [comment]
> try:
> 
> ```diff
> - queryFn: userService.getProfile
> + queryFn: () => userService.getProfile()
> ```
> 
> in the server component. If that's not helping, I need to see a minimal reproduction please.

what reproduction? that error appears only when deploying on vercel, on localhost everything is fine

**Comment by TkDodo** [comment]
> what reproduction? that error appears only when deploying on vercel, on localhost everything is fine

then I guess you want to open an issue at vercel 🤷

**Comment by chertik77** [comment]
> > what reproduction? that error appears only when deploying on vercel, on localhost everything is fine
> 
> then I guess you want to open an issue at vercel 🤷

I fixed it, it happens because the promise is not resolving
