### ISSUE TITLE
Enabled exactOptionalPropertyTypes causes error when trying to use the optional selector

### ISSUE THREAD

**Issue by vladcos** [TanStack/query#7641]
### Describe the bug

Per article https://tkdodo.eu/blog/react-query-data-transformations#3-using-the-select-option I'm using the optional `select()` passed from outside. When typing it as described by @TkDodo  here https://stackoverflow.com/a/75788655/255408 an error comes up (see repro)

### Your minimal, reproducible example

https://www.typescriptlang.org/play/?exactOptionalPropertyTypes=true#code/JYWwDg9gTgLgBAbwFBzgVwM4FMCKatQCeANEgL5wBmUEIcA5AAIwCGAdhqwMYDWA9FCwsuMALQBHfEXpIkMQmCxwAogA8CXYNgxwAvIjKysqyLDhcIHeJiwBxLDDUatWDAHkA0nrgAeACoAIiys3k5QmtoAfAAU2AA2WCIA-ABccNEAJsEsaWERrgCUepFwgdlFuiXIqIIwaFBs6Nh4BITR1ahwkq0eWIRpANr0xs7a9AC6pJ1dUoQAYmxp0RUlA5MonQB027FYCSJwSYhw8YnwFGkIZAVTcNcA3OSPRibQ8BZWTXYOeS4YygAlAFuAHefxBEL6X5RXb7GCpdJZVi5dThP4rUoQlgYjq1eqNGwtIjtDaobpEXr9OBDEZosbrabk+aLdIYta3VCnES3B5PIA

### Steps to reproduce

The combinations of the typings and enabled `exactOptionalPropertyTypes`  cause an error because an explicit `undefined`  is not allowed

### Expected behavior

The typings should allow explicit `undefined` 

### How often does this bug happen?

Every time

### Platform

Any

### Tanstack Query adapter

react-query

### TanStack Query version

v5.36.1

### TypeScript version

v5.5.2

**Comment by TkDodo** [comment]
I'd probably just do this:

```
export const useGetExercisesOK2 = <TData = Exercises>(options?: { select?: (data: Exercises) => TData }) => {
  return useQuery({
    queryKey: ['exercises'],
    queryFn: () => [],
    ...options
  });
};
```

[TypeScript playground](https://www.typescriptlang.org/play/?exactOptionalPropertyTypes=true#code/JYWwDg9gTgLgBAbwFBzgVwM4FMCKatQCeANEgL5wBmUEIcA5AAIwCGAdhqwMYDWA9FCwsuMALQBHfEXpIkMQmCxwAogA8CXYNgxwAvIjKysqyLDhcIHeJiwBxLDDUatWDAHkA0nrgAeACoAIiys3k5QmtoAfAAU2AA2WCIA-ABccNEAJsEsaWERrgCUepFwgdlFuiXIqIIwaFBs6Nh4BITR1ahwkq0eWIRpANr0xs7a9AC6pJ1dUoQAYmxp0RUlA5MonQB027FYCSJwSYhw8YnwFGkIZAVTcNcA3OSPSMam8BZWTXYOeS7uHgAmbz+IIhfS-KLRCBgGDASwYVLHU7JJZZVi5dThP4rUqglh3HEdWr1Ro2FpEdobVDdIi9fpwIYjLFjdbTGnzRbpHFrW6obabaGw+EbB5PWQvEzQd7w6zYeyOTH5DDKABKKrcKuBZTBKkVfxiyJgiMy2Qxo0KxVx5UtRIcJK+5LaHWpszpg2GepZvJmrQWS25rM6htuorI9yAA)
