### ISSUE TITLE
`useIsFetching` is reacting only to first static queryKey

### ISSUE THREAD

**Issue by sadeghbarati** [TanStack/query#7680]
### Describe the bug

```ts
export function useCaptchaQuery(queryKey: string) {
	const data = useQuery<{
		userId: string
		id: string
		title: string
		completed: boolean
	}>({
		refetchOnMount: true,
		retry: true,
		retryOnMount: false,
		queryKey: ['auth', 'captcha', queryKey],
		async queryFn() {
			return $fetch('https://jsonplaceholder.typicode.com/todos/1')
		},
	})

	return data
}
```

For example this query contains two static queryKey like `auth` and `captcha` and one dynamic `queryKey`
I want to check if tanstack query is fetching this API with `useIsFetching` hook but

- useIsFetching({ queryKey: ['auth'] }) ✅ 
- useIsFetching({ queryKey: ['captcha'] }) ❌ 
- useIsFetching({ queryKey: ['auth', 'captcha'] }) ❌ 
- useIsFetching({ queryKey: ['auth', 'dynamicQueryKey'] }) ❌ 

`useIsFetching` is only works with first static query key

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-uii3jr

### Steps to reproduce

1. Go to Stackblitz demo check `hooks/useCaptcha.ts`
2. Then go to `Captcha.tsx` component which is using `useCaptchaQuery` query hook
3. In the `App.tsx`, I added three buttons to check `useIsFetching` hooks with different queryKeys but only `auth` queryKey is working and it will disable the last button on the load and refetch event

### Expected behavior

Those three buttons in Stackblitz playground should be disabled on the first load and the refetch event

### How often does this bug happen?

Every time

### Platform

- OS: [Windows 11]
- Browser: [Chrome]
- Version: [126.0.6478.127 64bit]

### Tanstack Query adapter

react-query

### TanStack Query version

v5.50.1

### TypeScript version

v5.5.3

**Comment by 87xie** [comment]
Each element in `queryKey` represents a level. In your case, `['auth', 'captcha', queryKey]`:

- First level: `auth`
- Second level: `captcha`
- Third level: string from the parameter

With the `useIsFetching` examples:

- `useIsFetching({ queryKey: ['auth'] })` will find the first level equal to `auth`
- `useIsFetching({ queryKey: ['captcha'] })` will find the first level equal to `captcha`

You can use a `predicate` option to ignore a specific level, like this:

```ts
useIsFetching({
    predicate: (query) => {
      return query.queryKey.some((key) => {
        return key === 'auth' || key === 'captcha';
      });
    },
  });
```

**Comment by sadeghbarati** [comment]
@87xie Many thanks 🙌  it worked
