### ISSUE TITLE
`vue-query` client `invalidateQueries` doesn't invalidate immediately

### ISSUE THREAD

**Issue by kazcw** [TanStack/query#7694]
### Describe the bug

The Vue implementation of `QueryClient.invalidateQueries` does not invalidate queries "immediately", as described in the documentation.

### Your minimal, reproducible example

[https://codesandbox.io/p/devbox/vue-query-query-invalidation-w2kn9y](https://codesandbox.io/p/devbox/vue-query-query-invalidation-w2kn9y?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clydflqfi00083b6j8cz4qy8q%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clydflqfi00023b6jnujonv5x%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clydflqfi00053b6jc1kxkpil%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clydflqfi00073b6jtwhqs6li%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clydflqfi00023b6jnujonv5x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clydflqfi00013b6jja45n946%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clydflqfi00023b6jnujonv5x%2522%252C%2522activeTabId%2522%253A%2522clydflqfi00013b6jja45n946%2522%257D%252C%2522clydflqfi00073b6jtwhqs6li%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clydflqfi00063b6j4i4pbhcc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clydflqfi00073b6jtwhqs6li%2522%252C%2522activeTabId%2522%253A%2522clydflqfi00063b6j4i4pbhcc%2522%257D%252C%2522clydflqfi00053b6jc1kxkpil%2522%253A%257B%2522id%2522%253A%2522clydflqfi00053b6jc1kxkpil%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clydflqfi00033b6jlo2u5v4d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clydflqfi00033b6jlo2u5v4d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Run the CodeSandbox; the rendered page shows the difference in behavior between the Vue QueryClient and the base implementation (the latter seems more consistent with the documentation).

### Expected behavior

The [documentation for QueryClient.invalidateQueries](https://tanstack.com/query/latest/docs/reference/QueryClient/#queryclientinvalidatequeries) says that "By default, all matching queries are immediately marked as invalid and active queries are refetched in the background." I understand this to mean that, after calling the function, matched queries should be seen to be invalidated, even if the function's returned `Promise` was not awaited. This is the case when using the base `QueryClient` of `@tanstack/query-core`.

### How often does this bug happen?

Every time

### Platform

- OS: Not operating-system specific
- Browser: Not browser-specific
- Browser version: Not browser-version specific

### Tanstack Query adapter

vue-query

### TanStack Query version

v5.51.0

### Additional context

[A workaround I'm using](https://github.com/enso-org/enso/pull/10431/files#diff-d8643cbb344122aa9950c1cdb87a6de5ea090e71fe960cf7c8960387fd33b4b2R6-R34) is to override `invalidateQueries` with an implementation that performs the invalidations immediately, deferring only the query refetches (as required to fix #6414).

**Comment by Mini-ghost** [comment]
Your approach was very effective. I simplified the implementation based on your solution:

```ts
export class QueryClient extends QC
  invalidateQueries(
    filters: MaybeRefDeep<InvalidateQueryFilters> = {},
    options: MaybeRefDeep<InvalidateOptions> = {},
  ): Promise<void> {
    const filtersCloned = cloneDeepUnref(filters)
    const optionsCloned = cloneDeepUnref(options)

    super.invalidateQueries({ ...filtersCloned, refetchType: 'none' }, optionsCloned)
    return nextTick().then(() => {
      return super.refetchQueries(filtersCloned, optionsCloned)
    })
  }
}
```

What do you think?

cc @@DamianOsipiuk

**Comment by kazcw** [comment]
> Your approach was very effective. I simplified the implementation based on your solution:
> 
> ```ts
> export class QueryClient extends QC
>   invalidateQueries(
>     filters: MaybeRefDeep<InvalidateQueryFilters> = {},
>     options: MaybeRefDeep<InvalidateOptions> = {},
>   ): Promise<void> {
>     const filtersCloned = cloneDeepUnref(filters)
>     const optionsCloned = cloneDeepUnref(options)
> 
>     super.invalidateQueries({ ...filtersCloned, refetchType: 'none' }, optionsCloned)
>     return nextTick().then(() => {
>       return super.refetchQueries(filtersCloned, optionsCloned)
>     })
>   }
> }
> ```
> 
> What do you think?
> 
> cc @@DamianOsipiuk

`filtersCloned.refetchType` needs to be propagated to `refetchQueries`.

**Comment by Mini-ghost** [comment]
https://github.com/TanStack/query/blob/14d9c49fba6715a21e62dd473c11c8454cdc51f9/packages/query-core/src/types.ts#L505-L507

https://github.com/TanStack/query/blob/14d9c49fba6715a21e62dd473c11c8454cdc51f9/packages/query-core/src/queryClient.ts#L288-L290

It seems that `refetchType` exists to determine whether `invalidateQueries` needs to perform a `refetch`. This approach only defers `refetchQueries` to the next micro task.

**Comment by TkDodo** [comment]
@Mini-ghost if the goal is to perform the marking as `invalidated` immediately, but do the refetching in the "next tick", then your implementation looks correct. looking at the comment in the code left by @DamianOsipiuk:

https://github.com/TanStack/query/blob/febbde676d0888d8dd4868177868a3316686cb58/packages/vue-query/src/queryClient.ts#L178-L179

I can only assume that what needs to be deferred is the refetch, not the mark as invalidated, because only the refetch itself runs the `queryFn`.

sadly, in the PR that introduced the fix, we didn't add a test case:

- https://github.com/TanStack/query/pull/6561/files

So I'm unsure what still needs to "work" after the fix. But maybe we can add a test case now and look at the original issue posted in:

- https://github.com/TanStack/query/issues/6414

@Mini-ghost would you like to PR that?

**Comment by kazcw** [comment]
The `refetchType` property of `InvalidateQueryFilters` can be used in two ways:
- It can be set to `none` to prevent refetch.
- It can be set to a refetch type, which should be passed to the `refetchQueries` function.

This implementation ignores the `refetchType` entirely; see comments added here:

> ```ts
> export class QueryClient extends QC
>   invalidateQueries(
>     filters: MaybeRefDeep<InvalidateQueryFilters> = {},
>     options: MaybeRefDeep<InvalidateOptions> = {},
>   ): Promise<void> {
>     const filtersCloned = cloneDeepUnref(filters)
>     const optionsCloned = cloneDeepUnref(options)
> 
>     // Here we call `super.invalidateQueries` with `refetchType` overridden, so the `refetchType` is not used.
>     super.invalidateQueries({ ...filtersCloned, refetchType: 'none' }, optionsCloned)
>     return nextTick().then(() => {
>       // Now:
>       // - We are calling `refetchQueries` even if `refetchType` is `none`
>       // - We are passing the filters to `refetchQueries`, but it ignores `refetchType`, because that is a property
>       //  of `InvalidateQueryFilters` that is not present in the `refetchQueries` filters.
>       return super.refetchQueries(filtersCloned, optionsCloned)
>     })
>   }
> }
> ```

---

In order to support those two functionalities offered by the `refetchType` property, we need to replicate the logic that `super.invalidateQueries` would have performed if we didn't override `refetchType`:

- We should skip refetching if the value is `none`:

https://github.com/TanStack/query/blob/14d9c49fba6715a21e62dd473c11c8454cdc51f9/packages/query-core/src/queryClient.ts#L288-L290

- When we don't skip refetching, any `refetchType` value provided should set the `type` field passed to `refetchQueries` (because it reads `type`, not `refetchType`):

https://github.com/TanStack/query/blob/14d9c49fba6715a21e62dd473c11c8454cdc51f9/packages/query-core/src/queryClient.ts#L291-L294

**Comment by Mini-ghost** [comment]
@TkDodo Thank you for your response. I am happy to address this issue and will review various operation combinations to add test cases for these scenarios.

**Comment by Mini-ghost** [comment]
@kazcw After reviewing the core code implementation, I realize you are correct. I will check if `refetchType` is `none` to determine whether to execute `super.refetchQueries`.

**Comment by DamianOsipiuk** [comment]
> sadly, in the PR that introduced the fix, we didn't add a test case:
  https://github.com/TanStack/query/pull/6561/files
  So I'm unsure what still needs to "work" after the fix. But maybe we can add a test case now and look at the original issue 
  posted in:

Issue is that reactive values in vue are queued in the event loop. 

```ts
const foo = ref('foo');
useQuery({
  queryKey: ['foo', foo],
  queryFn: async ({ queryKey }) => {
    console.log(queryKey[1], foo.value);
    return {};
  },
});

const queryClient = useQueryClient();

setTimeout(() => {
  foo.value = 'bar';
  queryClient.invalidateQueries();
}, 2000);
```

In this case `queryKey[1]` which is taken from `queryFn` context has stale value. While `foo.value` is correct.

And yes, the solution to this might be to re-implement invalidate function to defer only `refetch` if necessary.
