### ISSUE TITLE
`AbortSignal` does not fire when query errors out

### ISSUE THREAD

**Issue by steveluscher** [TanStack/query#7724]
### Describe the bug

Consider [this example](https://github.com/TanStack/query/blob/79e52029975d8a889ffafd7e161010d4997af219/docs/framework/angular/guides/query-cancellation.md?plain=1#L37-L53) from the TanStack Query docs. Imagine that when one of the todo details fetches fails, the entire query should error out. The `AbortSignal` supplied to the `fetchFn` by TanStack Query should fire the `abort` event in this case, to cancel pending requests, but it does not.

### Your minimal, reproducible example

[Codesandbox repro](https://codesandbox.io/p/sandbox/tanstack-query-query-not-aborted-on-error-h4nx35?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyhu570o00063b6gb4tmdi8n%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyhu570o00023b6gmnhwdo49%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyhu570o00033b6grj55lm6f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyhu570o00053b6guc9122wz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyhu570o00023b6gmnhwdo49%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyhu570o00013b6g32lov9ke%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clyhu570o00023b6gmnhwdo49%2522%252C%2522activeTabId%2522%253A%2522clyhu570o00013b6g32lov9ke%2522%257D%252C%2522clyhu570o00053b6guc9122wz%2522%253A%257B%2522id%2522%253A%2522clyhu570o00053b6guc9122wz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyhu570o00043b6gl579ncbj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clyhu570o00043b6gl579ncbj%2522%257D%252C%2522clyhu570o00033b6grj55lm6f%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyhu570o00033b6grj55lm6f%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Run the example with the console open.

Observe that, when the request for `/todo/2` rejects, the abort event is _not_ fired on the `AbortSignal` supplied to the `fetchFn` by TanStack Query.

### Expected behavior

The `abort` event should fire so that all of the abortables created inside `fetchFn` abort.

### How often does this bug happen?

Every time

### Platform

All platforms.

### Tanstack Query adapter

react-query

### TanStack Query version

5.51.1

### TypeScript version

4.4.4

**Comment by 87xie** [comment]
You can manually call `queryClient.cancelQueries({ queryKey: ['foo'], exact: true })` to trigger abort callbacks. However, the query will revert to its previous state, which may not be the expected result if you want to display the rejected information.

If you don't need to revert to the previous query state, would creating another `AbortController` within the `queryFn` to control the request flow be more appropriate?

```ts
const { data, error } = useQuery({
  retry: false,
  queryKey: ["foo"],
  async queryFn() {
    const controller = new AbortController();
    const signal = controller.signal;
    
    const [resultA, resultB] = await Promise.all([
      // REQUEST A
      // Always dies in 1000ms.
      new Promise<number>((_, reject) => {
        const timerId = setTimeout(() => {
          reject(new Error("Request A died!"));
          controller.abort();
        }, 1000);

        signal.addEventListener("abort", () => {
          console.log("request A was aborted");
        });
      }),
      // REQUEST B
      // Takes a lot longer than 1000ms; should always be aborted.
      new Promise<number>((resolve) => {
        // ...
        signal.addEventListener("abort", () => {
          console.log("request B was aborted");
        });
      }),
    ]);
    // Imagine it's something like price * units.
    return resultA * resultB;
  },
});
```

**Comment by steveluscher** [comment]
Thanks for your thoughts, @87xie. For the purpose of this issue, let's focus on the bug in TanStack Query rather than talk about workarounds.

For avoidance of doubt, I've changed the repro in the issue to be one that pulls straight from the TanStack Query docs themselves, so that we can all agree that if the use case in the docs is valid, then this bug is valid.

**Comment by 87xie** [comment]
Thanks for your information. I'm not sure if it's a bug. [The example](https://github.com/TanStack/query/blob/79e52029975d8a889ffafd7e161010d4997af219/docs/framework/angular/guides/query-cancellation.md?plain=1#L37-L53) from the TanStack Query docs shows sequential requests. The todoDetails request depends on todos, so I think it only triggers after resolved todos.

`queryFn` rejections are not always due to `AbortError`, so I think triggering an abort on each rejection is inappropriate. For a single request in the `queryFn` case, this seems unnecessary, or maybe it should be opt-in. If I missed something obvious, please let me know.

**Comment by steveluscher** [comment]
> [The example](https://github.com/TanStack/query/blob/79e52029975d8a889ffafd7e161010d4997af219/docs/framework/angular/guides/query-cancellation.md?plain=1#L37-L53) from the TanStack Query docs shows sequential requests

The example shows concurrent requests. See the `Promise.all` at the bottom.

**Comment by 87xie** [comment]
Ahh, thanks for the explanation, `todoDetails` are indeed concurrent requests. It would be great if `Promise.all(todoDetails)` could have a better mechanism for canceling pending requests, but we also need to consider the scenario of `Promise.allSettled(todoDetails)`?

**Comment by steveluscher** [comment]
To your concern, if TanStack Query doesn't abort the signal, you _can't_ implement responsible cancellation at all, however if TanStack Query _does_ abort the signal, the developer _still has control over how to proceed_. The implementor of `queryFn` could decide to cancel all, some, or none of the in-flight requests, and to return complete or partial data.

**Comment by TkDodo** [comment]
I don't think this is really a bug, what you are proposing is a change in behaviour. What we are currently doing is we are aborting the signal only in two cases:

- when `queryClient.cancelQueries` is triggered (imperatively by the user)
- when the query becomes unused - that means, the last observer unsubscribes. This usually happens when the `queryFn` runs and the user navigates away to a different page, which leads to the observer unmounting.

If your `queryFn` makes multiple requests, it's not on us to decide that all requests should be aborted just because one of them fails. That might be your wanted behaviour for your use-case, but there's no guarantee that this is always correct.

The example you linked to shows that you can pass the signal to multiple requests, and if the component unmounts, all of those will be cancelled. Nothing in our docs indicates that rejecting one promise should abort other requests.

As described by others, there are lots of ways to achieve what you want. Additionally, I would probably go for `useQueries` in your example with `combine` and keep it to one request per queryFn.
