### ISSUE TITLE
Query included in derived store dependency array does not get executed

### ISSUE THREAD

**Issue by maalni** [TanStack/query#7778]
### Describe the bug

Query stores consumed by a derived store are not executed and dont change the derived store state.

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-query-khmocq?file=src%2FApp.svelte

### Steps to reproduce

1. create a query and a derived store
2. add query to derived store dependency array without referencing it somewhere else

### Expected behavior

Query stores should be consumable by derived stores and get executed.
Additionally it should update the derived store base.

### How often does this bug happen?

Every time

### Platform

- OS: Windows, Chrome v126

### Tanstack Query adapter

svelte-query

### TanStack Query version

5.51.1

### TypeScript version

5.5.3

**Comment by TkDodo** [comment]
@lachlancollins can you have a look please

**Comment by lachlancollins** [comment]
Hi @maalni , that example like something that would be better suited to a reactive statement `$: {...}` rather than derived. If you have a specific use case that requires derived, please submit a new repro.
