### ISSUE TITLE
DevTools work only when shadowDOM is `open`

### ISSUE THREAD

**Issue by fdw** [TanStack/query#7784]
### Describe the bug

I'm using Tanstack Query in a webcomponent, with ` this.attachShadow({ mode: 'closed' })`. When I then add the dev tools, they do show up and I can see queries, but almost everything is non-interactive. I can only switch between `queries` and `mutations`. The buttons do not work, nor can I open details about a query.

After some testing, it seems to work better with `mode: 'open'`. Almost everything now works, except the settings (?).

### Your minimal, reproducible example

https://stackblitz.com/edit/github-ifjxaf?file=src%2Fmain.tsx

### Steps to reproduce

1. Create a shadow DOM with `mode: closed`
2. Add React dev tools
3. Try to click a button or anything

### Expected behavior

I'd expect the dev tools to react to my input, but they don't

### How often does this bug happen?

Every time

### Platform

- Browser: Firefox

### Tanstack Query adapter

react-query

### TanStack Query version

5.51.11

### TypeScript version

5.5.3

**Comment by TkDodo** [comment]
if you want, please investigate the issue and propose a fix. I don't know enough about shadowDOM 😅

**Comment by fdw** [comment]
I've dug a bit, and it seems you use solid.js for the devtools. Unfortunately, they seem to have a problem with closed shadow DOM and don't intend to fix it: https://github.com/solidjs/solid/issues/1891

**Comment by TkDodo** [comment]
thanks, then I'll close this as an upstream issue.
