### ISSUE TITLE
_reactQuery.QueryClient is not a constructor

### ISSUE THREAD

**Issue by JayYoungman** [TanStack/query#7831]
### Describe the bug

Jest test suite is failing with TypeError: _reactQuery.QueryClient is not a constructor.

following this example of writing tests with react query.

https://github.com/TkDodo/testing-react-query/blob/main/src/tests/App.test.tsx

### Your minimal, reproducible example

Snippet

### Steps to reproduce

//testingLibraryHelpers.tsx

```
const createTestQueryClient = () =>
  new QueryClient({
    defaultOptions: {
      queries: {
        retry: false,
      },
    },
  })
```

```
export function renderWithClient(ui: React.ReactElement) {
  const testQueryClient = createTestQueryClient()
  const { rerender, ...result } = render(<QueryClientProvider client={testQueryClient}>{ui}</QueryClientProvider>)
  return {
    ...result,
    rerender: (rerenderUi: React.ReactElement) =>
      rerender(<QueryClientProvider client={testQueryClient}>{rerenderUi}</QueryClientProvider>),
  }
}
```

```
export function createWrapper() {
  const testQueryClient = createTestQueryClient()
  return ({ children }: { children: React.ReactNode }) => <QueryClientProvider client={testQueryClient}>{children}</QueryClientProvider>
}
```

//test.tsx

```
it.only('should not render the carousel for brands until there is data', () => {
      const { container } = renderWithClient(
        <MemoryRouter initialEntries={['/']}>
          <BrandsCarousel />
        </MemoryRouter>
      )

      const carousel = container.querySelector('.brand-carousel-wrapper')

      expect(carousel).not.toBeInTheDocument()
    })
```

//app.tsx

```
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: Infinity,
    },
  },
})

```

```
const AppWrapper: FC = (props) => {
  const { isRegionSelectorModalVisible } = useRegionSelector()
  const isScrollable = !isRegionSelectorModalVisible

  return (
      <QueryClientProvider client={queryClient}>
        <TamaguiProvider config={config} defaultTheme="light">
          ....
        </TamaguiProvider>
      </QueryClientProvider>
  )
}
```

### Expected behavior

Test suite should not fail

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="750" alt="Screenshot 2024-07-31 at 15 26 01" src="https://github.com/user-attachments/assets/4f3e6849-2596-417a-b494-b779c22ad1b8">

### Platform

Jest/ React testing library

"@testing-library/react": "^16.0.0",
"jest": "^27.4.7",

### Tanstack Query adapter

react-query

### TanStack Query version

5.51.11

### TypeScript version

4.7.4

### Additional context

Would appreciate any support, thank you :)

**Comment by TkDodo** [comment]
Thank you for filing this issue, but we need more information before looking into this.

Specifically, a minimal, standalone, runnable reproduction is needed - preferably with [codesandbox](https://codesandbox.io/new) or [stackblitz](https://stackblitz.com/). If your issue is TypeScript related, prefer a [TypeScript playground](https://www.typescriptlang.org/play).

We'll close this issue for now, but we'll certainly re-open it if there is a proper reproduction.

**Comment by pranshuchittora** [comment]
I am also facing the same issue. 
For some reason importing QueryClient works at runtime, but breaks during jest tests.
The imports are undefined
