### ISSUE TITLE
Codesandbox example linked in issue template is 404

### ISSUE THREAD

**Issue by IanVS** [TanStack/query#7862]
### Describe the bug

I want to open an issue, and was going to try to create a minimal reproduction, but the link in the template seems outdated:

>Feel free to fork any of the official CodeSandbox examples to reproduce your issue: https://tanstack.com/query/v4/docs/examples/react/simple

It points to v4, but the page is also missing and gives a 404 error.

### Your minimal, reproducible example

Try visiting https://tanstack.com/query/v4/docs/examples/react/simple

### Steps to reproduce

Click "new issue" in GitHub, click the link to the official CodeSandbox example, get 404

### Expected behavior

I expected to be taken to a codesandbox page so that I could fork it and reproduce my issue.

### How often does this bug happen?

Every time

### Platform

NA

### Tanstack Query adapter

None

### TanStack Query version

N/A

**Comment by IanVS** [comment]
Further, when I did find the v5 examples and tried to fork in stackblitz, I get an error from stackblitz as well.

https://stackblitz.com/edit/tanstack-query-k3intu?file=src%2Findex.tsx&preset=node

<img width="450" alt="image" src="https://github.com/user-attachments/assets/bf762505-626b-40a6-a143-1bbd2b588a0c">

**Comment by TkDodo** [comment]
The correct link is:

> https://tanstack.com/query/v4/docs/framework/react/examples/simple

please file a PR to update the template, thanks

**Comment by IanVS** [comment]
You still want it to point to the V4 docs?

**Comment by TkDodo** [comment]
No, /latest please
