### ISSUE TITLE
inappropriate installation guide

### ISSUE THREAD

**Issue by Jay-Karia** [TanStack/query#7869]
### Describe the bug

The installation guide at https://tanstack.com/query/latest/docs/framework/react/installation has a section called "NPM" which shows scripts to install the package which also includes pnpm, yarn, and bun.

### Your minimal, reproducible example

https://tanstack.com/query/latest/docs/framework/react/installation

### Steps to reproduce

1. Go to [installation guide](https://tanstack.com/query/latest/docs/framework/react/installation)
2. Visit "NPM" section

### Expected behavior

I expect to have different sections for different package managers.

### How often does this bug happen?

None

### Platform

OS: Win 10
Browser: Chrome

### Tanstack Query adapter

None

### TanStack Query version

v5

### TypeScript version

v4.5

**Comment by TkDodo** [comment]
you still install from npm (the registry) even if you use pnpm or yarn.

**Comment by Jay-Karia** [comment]
The copy button will copy the full text (including yarn and pnpm commands ) with comments.
So dividing them might improve DX

**Comment by TkDodo** [comment]
then please make a PR to split the instructions only; but I think this isn't the only place in the docs where we do this. Search for `yarn add` in the docs directory

**Comment by Jay-Karia** [comment]
@TkDodo, Fixed
