### ISSUE TITLE
useMutation Docs indicate queryClient is an option in 1 place but not another, and not in the typescript

### ISSUE THREAD

**Issue by onionhammer** [TanStack/query#7946]
### Describe the bug

The documents indicate you can pass queryClient in the options passed to useMutation, but using 5.52.1, the typescript does not recognize that option.

https://tanstack.com/query/latest/docs/framework/react/reference/useMutation

In the list, 'queryClient' is not present, but it is the last option listed when you scroll down the page.

> 
> queryClient?: QueryClient,
> Use this to use a custom QueryClient. Otherwise, the one from the nearest context will be used.
> 

### Your minimal, reproducible example

N/A

### Steps to reproduce

N/A

### Expected behavior

queryClient should be passable

### How often does this bug happen?

None

### Platform

N/A

### Tanstack Query adapter

None

### TanStack Query version

5.52.1

### TypeScript version

N/A

### Additional context

N/A

**Comment by TkDodo** [comment]
queryClient is not an option, but can be passed as the second argument. Please make a PR to fix the docs.

**Comment by baeharam** [comment]
@TkDodo I think this could be closed. Thanks for your approval 😄
