### ISSUE TITLE
Docs: Bug in code example

### ISSUE THREAD

**Issue by Jay-Karia** [TanStack/query#7959]
### Describe the bug

The code example [here](https://tanstack.com/query/latest/docs/framework/react/quick-start) has this bug.

![query_bug](https://github.com/user-attachments/assets/3f4ddcc1-abdb-43b1-842f-97b30fdf9897)

The arguments passed to the `mutate` function causes.

### Your minimal, reproducible example

https://tanstack.com/query/latest/docs/framework/react/quick-start

### Steps to reproduce

1. Copy the code given in the link
2. Run it

### Expected behavior

No errors

### How often does this bug happen?

Every time

### Screenshots or Videos

![query_bug](https://github.com/user-attachments/assets/3f4ddcc1-abdb-43b1-842f-97b30fdf9897)

### Platform

Win 10
Chrome

### Tanstack Query adapter

None

### TanStack Query version

5.52.1

### TypeScript version

5

**Comment by mauroaccornero** [comment]
@Jay-Karia I think it depends on how you define the postTodo's function. I was able to resolve the error defining a custom postTodo function like this:
```
const postTodo = async ({id, title}: {id: number, title: string}) => {
    console.log(id,title)
}
```

**Comment by TkDodo** [comment]
the quick start is not a full example that's meant to be copy-pasted. It has an import that doesn't exist:

```
import { getTodos, postTodo } from '../my-api'
```

For runnable examples, please look at the examples:
https://tanstack.com/query/latest/docs/framework/react/examples/simple
