### ISSUE TITLE
Calling `invalidateQueries` twice causes two refetches

### ISSUE THREAD

**Issue by Diggsey** [TanStack/query#7963]
### Describe the bug

As a high level API, I would expect `invalidateQueries` to simply mark queries as invalid, and only refetch invalid queries asynchronously.

ie. Calling `invalidateQueries` twice synchronously, should be the same as calling it once.

At the moment it will cause two refetches, which is surprising, and very hard to workaround even once the issue is known. I next tried `notifyManager.batch` on the invalidations, but that did not help. I also tried separating out the refetch, but there is no way to refetch only *invalid* queries (`{state: true, type: "active"}` refetches queries which are stale but not invalid, which is not what I want.)

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/staging-pine-r9p2kp?workspaceId=1adec8c4-7281-41f6-bdc7-396d56e39954&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0cbnla200082a69nb9kvf5s%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0cbnla200032a69k4cgx0dz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0cbnla200052a69uc552hsc%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0cbnla200072a69zk98spyx%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0cbnla200032a69k4cgx0dz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0cbnla200022a69a1t504jl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0cbnla200032a69k4cgx0dz%2522%252C%2522activeTabId%2522%253A%2522cm0cbnla200022a69a1t504jl%2522%257D%252C%2522cm0cbnla200072a69zk98spyx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0cbnla200062a69z260qpa7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%255D%252C%2522id%2522%253A%2522cm0cbnla200072a69zk98spyx%2522%252C%2522activeTabId%2522%253A%2522cm0cbnla200062a69z260qpa7%2522%257D%252C%2522cm0cbnla200052a69uc552hsc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0cbnla200042a69ltph8wuk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cm0cbnla200052a69uc552hsc%2522%252C%2522activeTabId%2522%253A%2522cm0cbnla200042a69ltph8wuk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

Call `invalidateQueries` twice synchronously.

### Expected behavior

Query is refetched once.

### How often does this bug happen?

Every time

### Platform

- OS: Windows
- Browser: Firefox

### Tanstack Query adapter

react-query

### TanStack Query version

v5.52.2, v5.28.8

**Comment by TkDodo** [comment]
> Calling invalidateQueries twice synchronously, should be the same as calling it once.

This is on purpose, because it's an imperative API. If you call `invalidateQueries` for an active query, we want it to actually cancel any ongoing fetch and trigger a new one. The reason is simply that if we don't do that, and you invoke an `increase` mutation multiple times:

```
const { mutate } = useMutation({
   mutationFn: increaseCounter,
   onSuccess: () => queryClient.invalidateQueries({ queryKey: ['counter'] })
})
```

The first mutation can trigger a refetch, but the second one might not, e.g if the first invalidation request is still in-flight. That means at the end of calling mutate() here multiple times, you might not see the latest data. It's not "eventually consistent".

We've made this change in v4: https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-react-query-4#consistent-behavior-for-cancelrefetch

You can however opt out of this behaviour by calling:

```
queryClient.invalidateQueries({ queryKey }, { cancelRefetch: false })
```

That way, multiple consecutive calls to `invalidateQueries` will not cancel each other out, but  deduplicate.

**Comment by Diggsey** [comment]
@TkDodo you seem to have misunderstood the issue.

The issue is not that the first query is being cancelled, the issue is that the refetch is being triggered synchronously with the call to invalidate.

I expect the refetch to trigger on the next micro-task, so that successive calls to `invalidateQuery` within the same microtask do not cause duplicate fetches.

**Comment by TkDodo** [comment]
This yields 2 fetches:

```
function invalidate() {
  queryClient.invalidateQueries({ queryKey: ["repoData"] });
  queryClient.invalidateQueries({ queryKey: ["repoData"] });
}
```

this yields 1 fetch:

```
function invalidate() {
  queryClient.invalidateQueries({ queryKey: ["repoData"] });
  queryClient.invalidateQueries({ queryKey: ["repoData"] }, { cancelRefetch: false });
}
```

what am I misunderstanding ?

**Comment by Diggsey** [comment]
```
async function shouldCancel() {
  queryClient.invalidateQueries({ queryKey: ["repoData"] });
  triggerUpdateThatMayTakeAWhile();
  queryClient.invalidateQueries({ queryKey: ["repoData"] }, { cancelRefetch: false });
  // Uh oh, we don't see the effects of the update because the first refetch wasn't cancelled
}

async function shouldNotCancel() {
  triggerUpdateThatMayTakeAWhile();
  queryClient.invalidateQueries({ queryKey: ["repoData"] });
  queryClient.invalidateQueries({ queryKey: ["repoData"] });
  // Second invalidation should be merged with the first, since they are both triggered within the same micro-task
}
```

The point is that I *do* want query cancellation, I just don't want the refetch to *start* until I've had a chance to trigger several invalidations.

**Comment by TkDodo** [comment]
Sorry, I still don't understand what you are trying to do / expecting to happen.

In the first function (`shouldCancel`), if you want the second invalidation to cancel the first one, pass `cancelRefetch: true` (or don't pass anything, as that is the default)

In the second function (`shouldNotCancel`), pass `cancelRefetch: false` to merge the two.

Since this is imperative code (= functions that you are actively calling), you can decide to pass the flag or not, depending on what you want to achieve.

Yes, if you write code like in the two cases shown, it will not work as you'd expect, because you need to write it differently.

**Comment by Diggsey** [comment]
I never want to cancel a refetch. I want to be able to trigger multiple invalidations before any refetching happens.

**Comment by Diggsey** [comment]
Let me put it a different way: I have a list of query filters which I want to invalidate in the query cache. Entries in this list may overlap (ie. there may exist queries which match more than one filter in the list). I want to invaldiate all the queries matching any of these filters.
How would you do this?

**Comment by TkDodo** [comment]
> I want to be able to trigger multiple invalidations before any refetching happens.

`invalidate` is an overloaded term here. What it does is:

- mark all matching queries as `"invalid"`
- then refetch all matching, active queries.

If you want to invalidate, but not refetch, pass `refetchType: 'none'` to `invalidateQueries`. Then, you can call `queryClient.refetchQueries` afterwards.

**Comment by Diggsey** [comment]
@TkDodo This just moves the problem to `refetchQueries` - there's no way to know what queries to refetch, since there's no way to refetch only invalidated queries, and passing the full list will result in duplicate refetches.

There should be a way to mark an arbitrary number of queries as invalid, and then re-fetch invalid queries, without over-fetching.

**Comment by TkDodo** [comment]
> there's no way to refetch only invalidated queries

sure there is:

```
queryClient.refetchQueries({
  stale: true
})
```

`invalidate` marks queries as `stale`.

**Comment by TkDodo** [comment]
and if you only want to target those that have manually been invalidated:

```
queryClient.refetchQueries({
  predicate: (query) => query.state.isInvalidated
})
```

**Comment by Diggsey** [comment]
>   predicate: (query) => query.state.isInvalidated

Ok, that is the missing piece. It is completely undocumented though.

Don't you think it would make more sense if `invalidateQueries` was equivalent to:
```
markQueriesInvalid(filters);
setTimeout(() => {
    refetchQueries({
      filters,
      predicate: (query) => query.state.isInvalidated
    })
}, 0);
```

That way one could simply call `invalidateQueries` freely without having to worry about over-fetching.

**Comment by TkDodo** [comment]
> It is completely undocumented though.

The [invalidation guide](https://tanstack.com/query/v4/docs/framework/react/guides/query-invalidation#query-matching-with-invalidatequeries) links to the [query filters API docs](https://tanstack.com/query/v4/docs/framework/react/guides/query-invalidation#query-matching-with-invalidatequeries).

Is it easily findable? Probably not on first glance.
Is it something that 99% of our users will ever need? Also, no.

> Don't you think it would make more sense

No because we can _return_ the Promise from `refetchQueries` directly from `invalidateQueries`.

I mean I guess we could, I think I still haven't understood the actual use-case you're trying to solve with this:

> There should be a way to mark an arbitrary number of queries as invalid, and then re-fetch invalid queries, without over-fetching.

I'm just using `invalidateQueries()` and that's it 🤷‍♂️ ....

**Comment by Diggsey** [comment]
> The [invalidation guide](https://tanstack.com/query/v4/docs/framework/react/guides/query-invalidation#query-matching-with-invalidatequeries) links to the [query filters API docs](https://tanstack.com/query/v4/docs/framework/react/guides/query-invalidation#query-matching-with-invalidatequeries).

But it's not *in* the query filters API docs!

(Specifically, the `Query` type is not documented anywhere, so `query.state.isInvalidated` is not discoverable)

> No because we can return the Promise from refetchQueries directly from invalidateQueries.

That's still possible.

> I mean I guess we could, I think I still haven't understood the actual use-case you're trying to solve with this:

We have a set of API functions, where each function does two things:
1. Make the API call
2. Call `invalidateQueries` on any state that might have been invalidated by the API call.

The important thing is that specific state invalidated depends on the API call.

The problem is that sometimes we need to make multiple update API calls in response to a single action. In this case, we get back a list of query filters to invalidate, but there might be some overlap between the invalidations. Naively calling `invalidateQueries` triggers multiple refetches of the same data which (when the data is large) causes the action to be unnecessarily slow.

**Comment by TkDodo** [comment]
you can call `invalidateQueries({ queryKey }, { cancelRefetch: false })`

**Comment by TkDodo** [comment]
I don’t know how long your “next tick” is or what that will do to fix your issue, but it won’t harm react-query. You can call imperative functions whenever you want.
