### ISSUE TITLE
useInfiniteQuery getNextPageParam and getPreviousPageParam are called even when isEnabled is false

### ISSUE THREAD

**Issue by rockus123** [TanStack/query#7996]
### Describe the bug

 useInfiniteQuery queryFn is not called but getNextPageParam and getPreviousPageParam are called even when isEnabled is false

### Your minimal, reproducible example

No sandbox

### Steps to reproduce

 useInfiniteQuery getNextPageParam and getPreviousPageParam are called even when isEnabled is true

### Expected behavior

 useInfiniteQuery getNextPageParam and getPreviousPageParam should not be called even when isEnabled is false

### How often does this bug happen?

None

### Platform

All

### Tanstack Query adapter

None

### TanStack Query version

v5

**Comment by TkDodo** [comment]
we call those functions to determine `hasNextPage` and `hasPreviousPage` if data exists, so this is very much expected.
