### ISSUE TITLE
v5.56.1 breaks trpc

### ISSUE THREAD

**Issue by KATT** [TanStack/query#8050]
### Describe the bug

We send `null` as `initialPageParam`. Infinite queries are not triggered

Just creating this to track the issue. You already know about this

### Your minimal, reproducible example

n/a (sorry)

### Steps to reproduce

You already know

### Expected behavior

That it works

### How often does this bug happen?

None

### Platform

all

### Tanstack Query adapter

None

### TanStack Query version

5.56.1

### Additional context

https://x.com/alexdotjs/status/1834252248701861906

**Comment by TkDodo** [comment]
Do you also use trpc? The issue is related to using `null` as `initialPageParam`, which I generally wouldn't recommend for raw react-query

**Comment by ddolcimascolo** [comment]
Nope, just a plain `useSuspenseInfiniteQuery`. I'm open to change my code anyway, but what would be a good `initialPageParam` then, considering that compatible APIs usually don't expect this param for the first request?

**Comment by TkDodo** [comment]
well the option is required, so I guess you're not using TypeScript ? We also infer the types from there so if you use null, you'll get bad inference. Anyways, fix is on the way.

**Comment by ddolcimascolo** [comment]
> well the option is required, so I guess you're not using TypeScript ? We also infer the types from there so if you use null, you'll get bad inference. Anyways, fix is on the way.

Right, this is pure Javascript code

**Comment by ddolcimascolo** [comment]
Thx for the quick fix!
