### ISSUE TITLE
Links in the docs point to 404 pages

### ISSUE THREAD

**Issue by brebiv** [TanStack/query#8069]
### Describe the bug

This two links:
https://tanstack.com/query/v3/docs/framework/react/guides/community/tkdodos-blog#1-practical-react-query
https://tanstack.com/query/v3/docs/framework/react/guides/community/tkdodos-blog#10-react-query-as-a-state-manager

in the bottom section of this page:
https://tanstack.com/query/v3/docs/framework/react/guides/important-defaults#further-reading
![Image](https://github.com/user-attachments/assets/58c2cffc-da64-456f-b94c-c4400bdb8ef4)

point to 404 pages

### Your minimal, reproducible example

https://tanstack.com/query/v3/docs/framework/react/guides/important-defaults#further-reading

### Steps to reproduce

1. Go to 'https://tanstack.com/query/v3/docs/framework/react/guides/important-defaults#further-reading'
2. Click on links in further reading section

### Expected behavior

Pages should not be 404

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Browser: Chrome

### Tanstack Query adapter

None

### TanStack Query version

v3

**Comment by TkDodo** [comment]
we changed routing (from remix to TanStack router) and that needed most of the links to change. We've fixed it for v4 and v5, but not v3, and I also don't intend to do this. If you want to contribute fixing the links, the branch to work against is `v3`
