### ISSUE TITLE
Mutation cache .find method finds old data even though it saves new submit data to client with the same mutationKey

### ISSUE THREAD

**Issue by fake364** [TanStack/query#8073]
### Describe the bug

Issue: React query client creates additional mutation instances with  the same key if component that held this hook was unmounted.
What I expected: I wanted to use information about last submitted time on screen but is doesn't change because it refers to old mutation instance so "Last submitted time" is not changed even though  I submit and use that mutation multiple times later

### Your minimal, reproducible example

https://github.com/fake364/tanstack-use-mutation-bug-repro

### Steps to reproduce

1. Go to 'https://github.com/fake364/tanstack-use-mutation-bug-repro'
2. npm intall
3. npm start
4. click on "resend code" button
5. Last submitted time appeared so keep in mind that value
6. click on Logout button
7. we got back to unauthenticated screen and time is the same - thats expected
8. click on "resend code"

### Expected behavior

**Expected:** time is updated since I've used mutation again
**Actual**: even though through logs I see that client saves new mutation with the same key, it finds old data and displays it

### How often does this bug happen?

Every time

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/5b68a591-0bab-49c3-996a-13c6920ac5b9)
https://github.com/user-attachments/assets/b5a8c6b3-c67b-4a4f-80ca-7f302c6ab508

### Platform

- OS: Windows
- Chrome
- 128.0.6613.120 (Official Build) (64-bit)

### Tanstack Query adapter

react-query

### TanStack Query version

5.56.2

### Additional context

I tried to find any information about this but couldn't

**Comment by TkDodo** [comment]
This is expected. You can see in the query devtools (mutation tab) that two mutations are created. Every time `mutate` is called, a new mutation entry is created. There is no deduplication as there is for queries. With `client.getMutationCache().find(['test-mutation'])` you just find the first match, even though there are multiple ones. You can use `findAll` to get all matches, then choose the one with the latest timestamp. If you need a reactive version, you want `useMutationState`.
