### ISSUE TITLE
ESLint error onSuccess callback: Promise-returning function provided to property where a void return was expected

### ISSUE THREAD

**Issue by tgdn** [TanStack/query#8087]
### Describe the bug

Following [this article](https://tkdodo.eu/blog/mastering-mutations-in-react-query#awaited-promises), I'm returning a promise in the `onSuccess` callback. Since the callback signature should return `void`, it cannot return a promise and causes the following ESLint error.

`Promise-returning function provided to property where a void return was expected`

![Image](https://github.com/user-attachments/assets/87a128a4-5419-4edf-9188-6e848bf01459)

![Image](https://github.com/user-attachments/assets/91af70dd-cbec-4706-90a3-9b7c10dc4d77)

### Steps to reproduce

Return a promise from a within the `onSuccess` callback.

### Expected behavior

I should be able to return a promise from within the `onSuccess` callback.

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

v5.35.5

### TypeScript version

v5.4.5

**Comment by TkDodo** [comment]
only `onSuccess` on `useMutation` can return a Promise. The callbacks on `mutate` can’t return anything
