### ISSUE TITLE
ESLint rule `@tanstack/query/exhaustive-deps` reports missing dependencies when using optional changing

### ISSUE THREAD

**Issue by nickrttn** [TanStack/query#8112]
### Describe the bug

The ESLint rule `@tanstack/query/exhaustive-deps` reports false positive missing dependencies when using optional chaining in the `queryKey`.

### Your minimal, reproducible example

https://stackblitz.com/edit/stackblitz-starters-rqku3u?file=app%2Fuse-users.ts

### Steps to reproduce

1. Go to https://stackblitz.com/edit/stackblitz-starters-rqku3u?file=app%2Fuse-users.ts
2. Run `npx eslint .` in the terminal

### Expected behavior

I would not expect an error to be shown when linting. I would expect the optional chaining to be valid.

### How often does this bug happen?

Every time

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/576951be-b9f7-4b2b-bd41-90dcf20be4ce)

### Platform

- macOS Sequoia 15.0

### Tanstack Query adapter

react-query

### TanStack Query version

5.45.1

### TypeScript version

5.6.2

**Comment by TkDodo** [comment]
do you want to work on this @nickrttn ?

**Comment by nickrttn** [comment]
Sure! I can take a look

**Comment by TkDodo** [comment]
This got fixed with:
- https://github.com/TanStack/query/pull/8146
