### ISSUE TITLE
Inactive query is not garbage collected when a useSuspenseQuery is made inactive while in fetching state

### ISSUE THREAD

**Issue by cirex-web** [TanStack/query#8159]
### Describe the bug

I set `gcTime` to 1000, so we should expect inactive queries to disappear from the cache pretty quickly. This does not happen when we inactivate the query while it is still being fetched.
<video src="https://github.com/user-attachments/assets/4ae0633e-4fac-40ce-a900-eaa6659e5cbe"/>

useQuery doesn't have this bug, however.

### Your minimal, reproducible example

https://github.com/cirex-web/tanstack-gc-bug

### Steps to reproduce

See video above

### Expected behavior

I expected the query cached value to be deleted within 1s of being inactive.

### How often does this bug happen?

Every time

### Platform

OS - macOS
Browser - Chrome
Browser Version - 129.0.6668.71 

### Tanstack Query adapter

react-query

### TanStack Query version

v5.59.8

### TypeScript version

v5.6.3

**Comment by TkDodo** [comment]
here’s the same thing with `useQuery` and it garbage collects just fine:

https://stackblitz.com/edit/github-eryyap?file=src%2Fapp%2Fsubpage%2Fpage.tsx

**Comment by cirex-web** [comment]
It would also be great if the minimum gcTime was smaller (like 100ms). What I want to do is pretty much guarantee that the cache isn't being used after leaving and then re-opening the subpage. (I'm aware that we can also just clear the cache manually, but if there's like 10 useQuery calls happening in the subpage, that might be a bit of a hassle...)

**Comment by cirex-web** [comment]
It's also interesting that garbage collection only fails when it the observer gets removed during the _first_ fetch

**Comment by cirex-web** [comment]
Thanks for resolving!
