### ISSUE TITLE
Pagination buttons not working first time only 2nd time click

### ISSUE THREAD

**Issue by MariuzM** [TanStack/query#8179]
### Describe the bug

Apologies if this has been posted but i can't find this issue :(

API returns list of `items` and also `pages` . `pages` will show in frontend how many page buttons it will have.

Problem when i receive data i can't use `Pagination` component properly, when i first time click it nothing happens i mean the number does not change in the `Pagination` component but API request is being made. But if click 2nd time then it works and you see animation moving from one number to another. 

```tsx
import { useState } from 'react'
import { NextUIProvider, Pagination } from '@nextui-org/react'
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query'
import { createFileRoute } from '@tanstack/react-router'

export const queryClient = new QueryClient()

export const Route = createFileRoute('/test8/tsq')({
	component: () => (
		<QueryClientProvider client={queryClient}>
			<NextUIProvider>
				<Tsq />
			</NextUIProvider>
		</QueryClientProvider>
	),
})

const fetchData = async (page: number) => {
	const r = await fetch(`https://jsonplaceholder.typicode.com/posts?_page=${page}&_limit=2`)
	if (!r.ok) throw new Error('Network response was not ok')
	return { pages: 4, items: await r.json() }
}

const Tsq = () => {
	const [page, setPage] = useState(1)
	const { data } = useQuery({ queryKey: ['posts', page], queryFn: () => fetchData(page) })
	console.log('🚀 ~ data:', data?.pages)

	return (
		<div>
			<p>TSQ page</p>
			{data?.pages && <Pagination total={data.pages} initialPage={1} onChange={setPage} />}
			<pre>{JSON.stringify(data, null, 2)}</pre>
		</div>
	)
}
```

Also made video https://github.com/user-attachments/assets/cd1a04f8-bfe5-46ea-8572-12fccf412bf4

### Your minimal, reproducible example

https://github.com/MariuzM/web-frameworks/blob/main/react-tsr/src/routes/test8/tsq.tsx

### Steps to reproduce

1. Click any number, first time click it wont select that number, but second time clicking it will

### Expected behavior

When clicking first time the number should change of the Pagination component. 

### How often does this bug happen?

Every time

### Platform

macOS

### Tanstack Query adapter

react-query

### TanStack Query version

5.59.13

### TypeScript version

5

**Comment by TkDodo** [comment]
yes, it’s documented here: https://tanstack.com/query/latest/docs/framework/vue/guides/paginated-queries#better-paginated-queries-with-placeholderdata
