### ISSUE TITLE
Conflict Between initialData and placeholderData – Either undefined or UI Flicker​

### ISSUE THREAD

**Issue by lucaspelloni2** [TanStack/query#8183]
### Describe the bug

Hi everyone,

I’m new to TanStack Query and encountered an issue that I’m not sure is by design. I would appreciate your insights.

I’m using React Query’s useQuery hook and would like to share the previous data across requests to avoid undesirable UI flickering. Here’s the query I set up:

```
const {
  data: listingPins,
  isLoading,
  error,
} = useQuery({
  queryKey: ['listingPins', currentCoordinates],
  queryFn: () => getListingPins(currentCoordinates),
  placeholderData: keepPreviousData,
});
```

This works well, and placeholderData effectively prevents flickering by keeping the previous data. However, `listingPins` is now initially `undefined`. So, I added `initialData: []` to the query.

After doing this, the flickering issue reappeared, and it seems like placeholderData no longer has any effect.

Is this behavior expected? Shouldn’t placeholderData still work alongside initialData, or am I missing something? Any guidance on how to keep the UI smooth while initializing the data with an empty array would be greatly appreciated.

Thanks in advance for your help!

### Your minimal, reproducible example

see above

### Steps to reproduce

1. npm install @tanstack/react-query

2.	Create a basic query function to simulate data fetching. For example:
```const getListingPins = async (coordinates) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([{ id: 1, name: 'Pin 1' }]); // Simulate API response
    }, 2000); // Simulate network delay
  });
};
```

3.	Implement the useQuery hook in your component using placeholderData to keep previous data:
```
const {
  data: listingPins,
  isLoading,
  error,
} = useQuery({
  queryKey: ['listingPins', currentCoordinates],
  queryFn: () => getListingPins(currentCoordinates),
  placeholderData: keepPreviousData,  // Keeps the previous result
});
```

4. Observe the behavior: On request refresh, listingPins retains the previous data (no flicker) while loading new data.

5. Now, add initialData: [] to the useQuery hook to initialize listingPins with an empty array:
```
const {
  data: listingPins,
  isLoading,
  error,
} = useQuery({
  queryKey: ['listingPins', currentCoordinates],
  queryFn: () => getListingPins(currentCoordinates),
  placeholderData: keepPreviousData,
  initialData: [],  // Initialize with an empty array
});
```

6.	Observe the new behavior: After adding initialData, the flickering returns, and it seems that placeholderData is no longer effective in preventing the flicker.

### Expected behavior

Being able to use both values

### How often does this bug happen?

None

### Platform

- React Native 0.75

### Tanstack Query adapter

None

### TanStack Query version

5.59.1

### TypeScript version

5.3.3

**Comment by TkDodo** [comment]
`initialData: []` initializes every cache entry with an empty array. So when you change the key, you get a new cache entry, and that will will have `[]` in the cache. If a cache entry has cached data, no matter where it came from, `placeholderData` is “not necessary”.

> However, listingPins is now initially undefined

Just do this:

```
placeholderData: (previousData) => previousData ?? []
```

**Comment by lucaspelloni2** [comment]
@TkDodo thank you for the quick answer! 

I still have the UI flickering problem with you approach tho.. 

```
  const {
    data,
    isLoading: isLoadingListingPins,
    isFetching: isFetchingListingPins,
    error,
  } = useQuery({
    initialData: [],
    queryKey: ['listingPins', currentCoordinates],
    queryFn: () => getListingPins(currentCoordinates),
    placeholderData: previousData => previousData ?? [],
  });

```

-> data is resetted across requests -> UI flickering


When I remove initialData, then it works as expected BUT I get the typescript `undefined` which is not optimal. 

Any other hints?

**Comment by lucaspelloni2** [comment]
![Image](https://github.com/user-attachments/assets/166965c1-2869-437c-88a8-eb1cfb253f3a)

**Comment by TkDodo** [comment]
> When I remove initialData, then it works as expected BUT I get the typescript undefined which is not optimal.

that’s what you need to do. `placeholderData` doesn’t fill the cache so if the request fails, data is undefined. See: https://tkdodo.eu/blog/placeholder-and-initial-data-in-react-query

you can of course use `initialData` function and compute a matching `initialData` by reading from the cache, but you need to keep track of the “previousCoordinates” then yourself. This isn’t worth it. Just add `?.map` or whatever you do with that data :) empty array or undefined don’t matter much.

**Comment by KishorJena** [comment]
placeholderData: (previousData) => previousData ?? []

placeholderData is always undefined
