### ISSUE TITLE
`infiniteQueryOptions` can't be used with both `useInfiniteQuery` and `useSuspenseInfiniteQuery`

### ISSUE THREAD

**Issue by alisamonstr** [TanStack/query#8184]
### Describe the bug

When upgrading from `5.59.9` to `5.59.14` the types from basic `infiniteQueryOptions` changed so they don't work with both  `useInfiniteQuery` and `useSuspenseInfiniteQuery` when you set 
```
 "compilerOptions": {
    "strict": true,
    "exactOptionalPropertyTypes": true
  }
```

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-xfkpkc?file=src%2FApp.tsx

### Steps to reproduce

1. Go to `App.tsx`
2. Observe Type error on line 41 (infiniteQueryResult)
3. Downgrade to `"@tanstack/react-query": "5.59.9"`
4. Go back to `App.tsx` and observe that the Type error is gone

### Expected behavior

Not having a Type error

### How often does this bug happen?

Every time

### Platform

- Typescript "5.6.2"

### Tanstack Query adapter

react-query

### TanStack Query version

5.59.14

### TypeScript version

5.6.2

**Comment by TkDodo** [comment]
Do you think adding `| undefined` here would fix it?

https://github.com/TanStack/query/blob/a085c92a5324b049ac4fc43d58c075815a6380e4/packages/react-query/src/infiniteQueryOptions.ts#L50-L62

**Comment by alvarlagerlof** [comment]
> Do you think adding `| undefined` here would fix it?

(same team) It doesn't fix it because infiniteQueryOptions still matches `UnusedSkipTokenInfiniteOptions`, which isn't supported by any of the [useInifiniteQuery overloads](https://github.com/TanStack/query/blob/a085c92a5324b049ac4fc43d58c075815a6380e4/packages/react-query/src/useInfiniteQuery.ts#L21-L71). Previously, our `infiniteQueryOptions` used the `UndefinedInitialDataInfiniteOptions` type.

**Comment by gwansikk** [comment]
I have reviewed the example project you provided, but I couldn’t reproduce the bug you mentioned. Could you please provide more detailed information about the issue?

**Comment by alvarlagerlof** [comment]
> I have reviewed the example project you provided, but I couldn’t reproduce the bug you mentioned. Could you please provide more detailed information about the issue?

Try adding `"exactOptionalPropertyTypes": true` to the `tsconfig.app.json` file. It seems like it it wasn't always enough to just have it in the `tsconfig.json`.

You should see an error like this:

![Image](https://github.com/user-attachments/assets/ee1f90c2-23db-4ec9-a832-5714f9e242b5)
