### ISSUE TITLE
`useInfiniteQuery` doesn't respect changed `initialPageParam`

### ISSUE THREAD

**Issue by bvanderdrift** [TanStack/query#8185]
### Describe the bug

Using cursor-based infinite queries might have ever changing `initialPageParam`. But, this package will ignore any changes to `initialPageParam` once first cache is stored.

What I'm expecting is that as long a cache is not stale; it checks whether `pageParams` are equal per page. If not, it refetches. This would happen in sequence; so if the second page param then doesn't change; that won't be refetched.

I realise I could put the initial page param in the `queryKey` but that would break the power of caching. I also understood from @TkDodo `initialPageParam` should be changeable [as seen in the example here](https://github.com/TanStack/query/discussions/6170#discussioncomment-7312883).

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/adoring-rosalind-6mhqlz

### Steps to reproduce

1. Click "Change page param"
2. **Expected**: "First page cursor" value updates to match `initialPageParam`.
3. **Actual**: "First page cursor" value keeps to cached value.

### Expected behavior

"First page cursor" value updates to match `initialPageParam`.

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/user-attachments/assets/6b9fa9ce-a110-4f4e-a917-ffba35b52245

### Platform

- OS: Mac OS
- Browser: Brave

### Tanstack Query adapter

react-query

### TanStack Query version

v5.59.14

**Comment by TkDodo** [comment]
`initialPageParam` is the page param for the first page. It will be stored when the cache entry is created, and you can’t change it after that. I’m not really sure what the demo is trying to achieve? Re-mounting the `Repro` component with a new key doesn’t change that the query with the `queryKey: ["some-key"]` (which is static!) has been created on the first render ...

**Comment by bvanderdrift** [comment]
Given cursor-based pagination is possible using `useInfiniteQuery`, and it detects changed cursors on pages at index 1+, I expected the first page to also have this change detection.

I guess the best workaround would be to have no cursor on the first page? (So `initialPageParam: null` or alike) and only start having cursors on the following pages?

But then, [in the example given here](https://github.com/TanStack/query/discussions/6170#discussioncomment-7312883), once user has opened that page with `?page=3`, it won't open page 4 if it receives `?page=4` right?

**Comment by TkDodo** [comment]
> But then, https://github.com/TanStack/query/discussions/6170#discussioncomment-7312883, once user has opened that page with ?page=3, it won't open page 4 if it receives ?page=4 right?

if you go to the page with `?page=3` and show a query for that, the `initialPageParam` - the one for the  first page - is 3. We store that value as part of the data for that page. If you later change it to 4 and expect it to be reflected, you would need to create a new query (by adding that param to the queryKey). Then, you’ll get a brand new query that starts at 4

**Comment by bvanderdrift** [comment]
Allright, I'll close this since sounds like this is done by design.
