### ISSUE TITLE
Type Error updating TanStack Query version

### ISSUE THREAD

**Issue by AngyDev** [TanStack/query#8230]
### Describe the bug

I'm trying to update the TanStack Query version to 5.59.15 but I'm having the following error:

```
Type 'UseQueryOptions<T, Error, T, QueryKey> & { queryKey: DataTag<QueryKey, T>; }' is not assignable to type 'UseSuspenseQueryOptions<T, Error, T, QueryKey>'.
  Types of property 'queryFn' are incompatible.
    Type 'unique symbol | QueryFunction<T, QueryKey, never> | undefined' is not assignable to type 'QueryFunction<T, QueryKey, never> | undefined'.
      Type 'typeof skipToken' is not assignable to type 'QueryFunction<T, QueryKey, never>'
```
I tried other versions and it seems that the [5.59.11](https://github.com/TanStack/query/releases/tag/v5.59.11) version changed something related to the error.

Do you know what is causing the error?
Thanks

### Your minimal, reproducible example

I don't have any

### Steps to reproduce

You can reproduce the error following the snippet below

```  
const [{ data: objects }, { data: containers }] = useSuspenseQueries({
    queries: [
      getAllObjects.getOptions({
        projectId,
      }),
      getAllContainers.getOptions({
        projectId,
      }),
    ],
  });

---

const getAllObjects = createSuspenseQuery<T, { projectId: string }>({
  queryKey: ["objects"],
  fetcher: async (variables): Promise<]T> => {...}
})

```

### Expected behavior

Typecheck doesn't fail

### How often does this bug happen?

None

### Platform

- OS: any
- Browser: Chrome
- react-query-kit Version: 3.3.0

### Tanstack Query adapter

None

### TanStack Query version

 5.59.11

### TypeScript version

5.6.3

### Additional context

We have also tried updating the TanStack query version with the previous version of react-query-kit (2.0.10), but we have the same error.

**Comment by l-Leniac-l** [comment]
how did you fix this? I'm having the same issue

**Comment by javadbat** [comment]
why did you close this? how do you solve it?

**Comment by geoff-harper-qii** [comment]
I'm also having the same problem

**Comment by AngyDev** [comment]
@javadbat, @geoff-harper-qii I solved it by installing the new version of react-query-kit v3.3.1. 
Check the issue https://github.com/HuolalaTech/react-query-kit/issues/66

**Comment by rtabulov** [comment]
for anyone in 2025: my problem was that i confused UseSuspenseQueryOptions and UseQueryOptions 🥲
