### ISSUE TITLE
[lint]: `no-rest-destructuring` does not report on `useSuspsenseQuery`

### ISSUE THREAD

**Issue by SimenB** [TanStack/query#8231]
### Describe the bug

Presumably just because it's missing from https://github.com/TanStack/query/blob/c61ff1e2f8036afa3f60ed434866e95175a3421c/packages/eslint-plugin-query/src/rules/no-rest-destructuring/no-rest-destructuring.rule.ts#L10

### Your minimal, reproducible example

I don't think this is needed - obviously just missing the function from the code? If I'm wrong, happy to put together a repro

### Steps to reproduce

```ts
function Component() {
  const {data, ...rest} = useSuspenseQuery(getOptions());
}
```

### Expected behavior

The ESLint rule should trigger

### How often does this bug happen?

Every time

### Platform

N/A

### Tanstack Query adapter

react-query

### TanStack Query version

5.59.16

### TypeScript version

5.6.3

**Comment by saul-atomrigs** [comment]
I'm also wondering why only those three hooks 🤔

**Comment by TkDodo** [comment]
yeah we’d need to add the others too. Would you like to contribute this?

**Comment by TkDodo** [comment]
the full list should be:

```
const queryHooks = ['useQuery', 'useQueries', 'useInfiniteQuery', 'useSuspenseQuery', 'useSuspenseQueries', 'useSuspenseInfiniteQuery']
```

**Comment by Gyumong** [comment]
Can I work on this?

**Comment by TkDodo** [comment]
Yes please
