### ISSUE TITLE
Framework-specific searches mostly redirect to React results without any indication

### ISSUE THREAD

**Issue by zkriszti** [TanStack/query#8245]
### Describe the bug

When initiating a search from a framework specific subsite of the docs (ie. vue-query), search results will mostly be related to react-query, but it is not indicated. After clicking upon any of these hits, my sidebar also changes to react-related items (which I understand might be a desired behaviour for direct links, but it is a sub-optimal experience for searches initiated from the docs). 

### Your minimal, reproducible example

https://tanstack.com/query/v5/docs/framework/vue/overview

### Steps to reproduce

- Go to a framework-specific subsite of the docs, ie. [https://tanstack.com/query/v5/docs/framework/vue/overview](https://tanstack.com/query/v5/docs/framework/vue/overview)
- Click on the search field in the left sidebar
- Type a search term into the search window (ie. refetch)
- Choose a search result
- You'll (most probably, depending on the content) be redirected to the react-query subpages AND the sidebar content items' badge will also change to "react" (again, obviously depending on the content)

### Expected behavior

As a developer reading the tanstack query docs, I'd expect to get framework-specific results if I initiate my search from a framework specific subsite. 

If there are no hits regarding my relevant framework,
- either don't even include those hits OR
- add a small badge near the result (like in the sidebar), indicating the framework the given hit is relevant to

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/user-attachments/assets/280edd03-5617-4144-83f6-7d47c3004bfa

### Platform

OS: Windows11
Browser: Firefox Developer Edition 132.0b9 (64-bit)
_but the issue is reproducible on any browser._ 

### Tanstack Query adapter

None

### TanStack Query version

v5

### Additional context

The issue is very similar when searching across product versions (v3-v4-v5). For example, I choose React as a framework and set v3 in the sidebar. Initiate a search. When clicking a search result (probably depending which result it is), I'm taken back to "latest", without any way of knowing whether the article applies to all versions (or only to latest, even though I specifically searched for v3 or v4).

**Comment by TkDodo** [comment]
Please file this issue in the tanstack . com repo - there isn't anything we can do here about this: https://github.com/TanStack/tanstack.com
