### ISSUE TITLE
`UseQueryOptions` type declaration regression, does not work for `useSuspenseQuery`

### ISSUE THREAD

**Issue by jaens** [TanStack/query#8258]
### Describe the bug

In previous versions, `useSuspenseQuery` can take a `UseQueryOptions<>` type as a parameter.

After an upgrade, this no longer works, and instead throws a type error.

```
Argument of type 'UseQueryOptions<TData, TError, TVariables, TQueryKey>' is not assignable to parameter of type 'UseSuspenseQueryOptions<TData, TError, TVariables, TQueryKey>'.
  Types of property 'queryFn' are incompatible.
    Type 'unique symbol | QueryFunction<TData, TQueryKey, never> | undefined' is not assignable to type 'QueryFunction<TData, TQueryKey, never> | undefined'.
      Type 'typeof skipToken' is not assignable to type 'QueryFunction<TData, TQueryKey, never>'.ts(2345)
```

How is one supposed to declare the types of functions that return the return value of `queryOptions`?

I looked into the current type declarations, and due to the heavy overloading now going on there, this actually seems impossible to do cleanly?

### Your minimal, reproducible example

not sure how this is supposed to work, the issue template does not show how to import Tanstack Query into the TypeScript playground

### Steps to reproduce

```typescript
export function useStandardSuspenseQuery<
    TArgs extends unknown[],
    TData,
    TError,
    TVariables,
    TQueryKey extends QueryKey,
>(fn: (api: ApiClient, ...args: TArgs) => UseQueryOptions<TData, TError, TVariables, TQueryKey>, ...args: TArgs) {
    const apiClient = useApiClient();
    return useSuspenseQuery(fn(apiClient, ...args));
}

useStandardSuspenseQuery(c => queryOptions({
    queryKey: ["test"],
    queryFn: async () => {
        return "test";
    },
}))
```

### Expected behavior

No type error.

### How often does this bug happen?

None

### Platform

TypeScript compiler

### Tanstack Query adapter

React

### TanStack Query version

5.59.20

### TypeScript version

5.6.3

**Comment by jaens** [comment]
Actually, I guess I found a workaround: Changing all `UseQueryOptions<>` to `UseSuspenseQueryOptions<>` seems to make it work.

...since `useQuery` can also take `UseSuspenseQueryOptions<>`  -- is that guaranteed?

**Comment by DogPawHat** [comment]
Yeah, I think it was changed in this pr https://github.com/TanStack/query/pull/8082

Basically, suspense can't take a `skipToken`  but regular query can so they now have different options. `UseSuspenseQueryOptions` is therefore narrower and can fit in `useQuery` just fine.

**Comment by TkDodo** [comment]
yeah so [passing queryOptions to useSuspenseQuery](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwLACg5wI4FcCmUCeA8mDMBAHYDOANKulpTgMoNg5U4CKuBqAvnABmUCCDgAiAAIwAhlVkBjANYB6KDhkKYAWmx584gNypUCipXgQSZKnAC8mHkWvmAFMjTpH+gNI58AFxwANriMDgW4gC6tJ7oegQAYuRBMpT45ApwrgCU9gB8iHReJeowWFDkEuGRxnFwfLF8OSYoDMys7Izc+q5WpOY5QA) still works, but it [fails if the queryFn is a skipToken](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwLACg5wI4FcCmUCeA8mDMBAHYDOANKulpTgMoNg5U4CKuBtaclANbAwAFQiD2fAL5wAZlAgg4AIgACMAIZUtAY0EB6KDk26YAWmx58KgNypUuipXgQSZKnAC8mHkXfOABTI-OhWBADSOPgAXHAA2iowOC4qALp86GF+AGLkcUIi4pLkqNIAlA4oDMys7Izc1oFupM7lQA).

If you build abstractions, you have to re-do what we do in our types; you can indeed just return `SuspenseQueryOptions` and pass those [to either `useQuery` or `useSuspsenseQuery`](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwLACg5wI4FcCmUCeA8mDMBAHYDOANKulpTgMoNg5U4CKuBtacDLj3x903PPgDSOEXTgBVRi0psO4gsVIVKqAL5wAZlAgg4AIgACMAIZUbAYwDWAeig5r9mAFpsEswG5UVBh8NjgAQTBgAGEAG2B2eABeREMICAAuOAAjdNj3cjhdIJR7bXhBSJj4xLgUgAoASjqAPjh6hDTMuBgoXCLGkpwAD0hYQyxyTzJCwSYbcgATayhF5VVGdXwAHjl0ABVwqABzSjgRmHZFs8nHcggAd3IAbQBdUXQ4fYARaxsPg4AUSgxigAK+ADUVsBrNl8jQ9l8ttJ8OdhpclmdkTI+C16gZyFl6tYolkqnEEuQYNQ4AA6ekrU5ZQ4nSjNJJtRTMVjsTbCTQzSjbH5-aw0-bA0HiqFQGFwnA0JHCFEtGn02mMyjMo6nZrIfjoMp2OAk6qU5ICRjkmpUpqBA1wNwwLBQWZ8iT48jEqIUxJqhmsxqNe2fODOZyOnDO12W7kqXlCD0E71mv10gO64N6EpzBbLVbrBNber2VqYfkkQUdRG+AgorLPMyXSgwMzvGvCABihJNlHwU3a7La+tDoadLsKTYVrZDn10fF0QaAA)
