### ISSUE TITLE
CreateMutationOptions is not exported correctly

### ISSUE THREAD

**Issue by kevinmeyvaert** [TanStack/query#8318]
### Describe the bug

`CreateMutationOptions` is not exposed correctly in @tanstack/angular-query-experimental `5.61.0`. As such you get errors using `mutationOptions`.

```
Public property x' of exported class has or is using name 'CreateMutationOptions' from external module "path/node_modules/@tanstack/angular-query-experimental/build/index" but cannot be named.

### Your minimal, reproducible example

/

### Steps to reproduce

use the newly introduced `mutationOptions` function.

```
 test = () => {
    return mutationOptions({
      mutationFn: () => Promise.resolve(),
    });
  };

![Image](https://github.com/user-attachments/assets/0643c62c-2404-493c-aa5c-530403af215a)

### Expected behavior

No ts error.

### How often does this bug happen?

Every time

### Platform

- Mac OSX
- Typescript 5.5.4

### Tanstack Query adapter

angular-query

### TanStack Query version

5.61.0

### TypeScript version

5.5.4

**Comment by arnoud-dv** [comment]
I cannot reproduce this in a newly generated Angular application even when I set `skipLibCheck` to false and use TypeScript 5.5.4. But it makes sense to export this type. Can you check using v5.61.1 if it works now?

**Comment by kevinmeyvaert** [comment]
Goodmorning Arnoud, I just checked the `5.61.1` release and the error is not longer present. Thanks for sorting this out so swiftly! Have a nice day. 😀
