### ISSUE TITLE
eslint: exhaustive-deps false positive for optional chain

### ISSUE THREAD

**Issue by Jack-Works** [TanStack/query#8357]
### Describe the bug

```ts
declare function sendQuery(address: string): Promise<any>
function useTest(data?: any) {
    return useQuery({
        // The following dependencies are missing in your queryKey: data
        queryKey: ['query-name', data?.address],
        queryFn: async () => sendQuery(data!.address),
        enabled: !!data?.address,
    })
}
```

```ts
declare function sendQuery(address: string): Promise<any>
function useTest(data?: any) {
    return useQuery({
        // The following dependencies are missing in your queryKey: data.address
        queryKey: ['query-name', data?.address],
        queryFn: async () => sendQuery(data.address),
        enabled: !!data?.address,
    })
}

```

### Your minimal, reproducible example

...

### Steps to reproduce

1. enable rule @tanstack/query/exhaustive-deps

### Expected behavior

No error

### How often does this bug happen?

Every time

### Platform

- "@tanstack/eslint-plugin-query": "^5.61.4"

### Tanstack Query adapter

None

### TanStack Query version

not applicable

### TypeScript version

5.7.2

**Comment by TkDodo** [comment]
@Newbie012 can you take a look please? I added this test case and indeed, it fails:

```
{
  name: 'should pass with optional chaining',
  code: `
  function useTest(data?: any) {
    return useQuery({
      queryKey: ['query-name', data?.address],
      queryFn: async () => sendQuery(data.address),
      enabled: !!data?.address,
    })
  }
  `,
},
```

**Comment by Newbie012** [comment]
Fixed in https://github.com/TanStack/query/issues/8357

As a side note, I think you may want to use [`skipToken`](https://tanstack.com/query/latest/docs/framework/react/guides/disabling-queries#typesafe-disabling-of-queries-using-skiptoken).
