### ISSUE TITLE
useSuspenseQueries does not accept array of UseSuspenseQueryOptions

### ISSUE THREAD

**Issue by Arnagos** [TanStack/query#8390]
### Describe the bug

It's not possible to call useSuspenseQueries with an array of UseSuspenseQueryOptions / SuspenseQueryOptions:
![Image](https://github.com/user-attachments/assets/29654c3b-cdd2-465b-868c-935d5eea866b)

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/rough-brook-drv2hx

### Steps to reproduce

```typescript
const [{ error, data }] = useSuspenseQueries({
  queries: [getSuspenseQueryOptions()],
});

function getSuspenseQueryOptions(): UseSuspenseQueryOptions<ValueType,  ErrorType> {
  return {};
}

type ValueType = { some: string; value: string };
type ErrorType = { error: unknown };
```

### Expected behavior

`UseSuspenseQueryOptions` can be used in useSuspenseQueries

### How often does this bug happen?

Every time

### Platform

Windows 11
Any browser

### Tanstack Query adapter

react-query

### TanStack Query version

5.62.2

### TypeScript version

5.7.2

**Comment by TkDodo** [comment]
can you please narrow down in which version this broke? We did a lot of type changes lately. What works is using `queryOptions`, which is the recommended way:

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwFB1XArgZwKYGUtjYB2OAiutlMNpgDQpoCOFUAngPJgzAQn0C+cAGZQIIOAHIAAjACGJOQGMA1gHoo2WYpgBaZpVYSA3EiSLemeAG0EcSqKi04AE1ly4-ALpwAvBhz4mIQk2OSU1JgAFMhocPpUNABccFYgrGFsnNwWkQCUngK5JkhC6ETaPERwaRkcXJVRuYgMqBow6FBV8XXZJNEtTCysANLYrMlWEkIQEBIFA6jdAGJEyXm+AHxwAAqiIMA4AHQamBAANgBu2JEArLkD-Pf8QA

**Comment by Arnagos** [comment]
@TkDodo This error already appears in the first version of 5. The types seem to have been generally incompatible since their inception. I can't use `queryOptions` because a large part of our endpoints get generated via Orval. I'll have to create an issue there as well.

**Comment by TkDodo** [comment]
gonna close this since the recommended solution is to use `queryOptions`. As for orval, I would suggest that they should start to have an option to emit `queryOptions` instead of `useQuery` hooks. This is the syntax other tools like `trpc` are also going towards
