### ISSUE TITLE
Quote in docs for fetchQuery is confusing

### ISSUE THREAD

**Issue by Josh68** [TanStack/query#8396]
[This quote](https://github.com/TanStack/query/blob/7cd2d192e6da3df0b08e334ea1cf04cd70478827/docs/react/reference/QueryClient.md?plain=1#L76) confuses me. Is it a run-on sentence and, if so, where and how should it be broken into more than one sentence. If it's not, what am I missing?

I wonder whether it should read as follows, but this is just a guess:

> The difference between using `fetchQuery` and `setQueryData` is that `fetchQuery` is async and will ensure that duplicate requests for this query are not created. With `useQuery`, instances for the same query are rendered while the data is fetching.

I feel like the explanation could be fleshed out a little more, particularly the distinction between this method and the `useQuery` hook

**Comment by TkDodo** [comment]
yeah the sentence makes no sense whatsoever. I don’t even think we need to highlight the difference between `fetchQuery` and `setQueryData` - they are two different things, and they both describe well what they do (one is a synchronous update, and one runs the queryFn ...)

I’ve removed the sentence.

**Comment by Josh68** [comment]
Thanks, @TkDodo. If possible, at some point, I'd love some post or docs on dealing with legacy code, where simply swapping in `useQuery` for sometimes very complex `useEffect`s might be difficult. I thought pulling in `useQueryClient` and then calling `queryClient.fetchQuery` inside an existing effect might be a substitute, but I've seen you post on SO that it's really not. Calling this out (and why) in the docs would be nice, IMO.
