### ISSUE TITLE
infinite isFetching

### ISSUE THREAD

**Issue by master8848** [TanStack/query#8430]
### Describe the bug

In condition when queryClient.clear() is run while some request  are in progress even after request is complete tanstack query doesn't resolve . 

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-query-zyumu7lg?file=src%2Findex.tsx&preset=node

### Steps to reproduce

Go to provided link click on press me 

### Expected behavior

Item should refetch or get resolved

### How often does this bug happen?

Every time

### Platform

All System

### Tanstack Query adapter

None

### TanStack Query version

v5.53.3

**Comment by TkDodo** [comment]
You’re removing the value (query) we’re trying to set the state to, so we can’t set the state to `success` afterwards.

Generally, calling an unconditional `clear()` while you are having queries mounted isn’t a good idea. You can use `queryClient.removeQueries(filters)` with filters to remove what you want more granuarly.
