### ISSUE TITLE
Bug in documentation website: "Redirect to latest version" doesn't work

### ISSUE THREAD

**Issue by NoamAnisfeld** [TanStack/query#8440]
### Describe the bug

When you're visiting the Tanstack Query documentation website (https://tanstack.com/query) and reaches a part that relates to a version older than the latest (a common case when you're coming from Google search or links from other websites), you see a banner prompting you to go the the docs of the latest version. However, recently the target of the links included in the banner isn't actually the docs of the latest version but the main page of the same version.

### Your minimal, reproducible example

https://tanstack.com/query/v3/docs

### Steps to reproduce

1. Go to https://tanstack.com/query/v3/docs
2. A banner appears prompting you to go to the docs of the latest version
3. Click either of the "latest" links
4. You'll be redirected to https://tanstack.com/query/v3

### Expected behavior

Redirect to the latest version documentation (currently https://tanstack.com/query/v5), preferably to the corresponding page.

### How often does this bug happen?

Every time

### Platform

Chrome for Windows

### Tanstack Query adapter

None

### TanStack Query version

v5

**Comment by TkDodo** [comment]
please open website related issues in the website repository:

https://github.com/tanstack/tanstack.com

we can’t fix these things from here.
