### ISSUE TITLE
declares 'QueryClient' locally, but it is not exported

### ISSUE THREAD

**Issue by sysmat** [TanStack/query#8475]
### Describe the bug

Module '"@tanstack/angular-query-experimental"' declares 'QueryClient' locally, but it is not exported.ts(2459)
index.d.ts(1, 447): 'QueryClient' is declared here.

### Your minimal, reproducible example

https://tanstack.com/query/latest/docs/framework/angular/quick-start

### Steps to reproduce

https://tanstack.com/query/latest/docs/framework/angular/quick-start

### Expected behavior

import must work and ts must be happy

### How often does this bug happen?

Every time

### Platform

- win 11

### Tanstack Query adapter

angular-query

### TanStack Query version

"@tanstack/angular-query-experimental": "^5.62.9",

### TypeScript version

5.6.3

**Comment by arnoud-dv** [comment]
I need a reproduction to be able to look into this. If you provide one and it's not the issue described below I'll reopen it.

I have seen this error only on Stackblitz when it's not run as webcontainers. To confirm it uses webcontainers, click the gear icon to open settings. It should show webcontainers as in the screenshot, NOT Angular as that is an obsolete template that actually does not work great with recent versions of Angular.

<img width="311" alt="Image" src="https://github.com/user-attachments/assets/57c0d3df-6106-4edb-9486-2b5ca24a6c67" />

**Comment by sysmat** [comment]
it seams my ts config was problem

**Comment by arnoud-dv** [comment]
> it seams my ts config was problem

Thank you for the update and good to know it works for you now. What setting did you change? Maybe it's worth adding it to the docs.

**Comment by sysmat** [comment]
- old conf:
```
"baseUrl": "./",
"forceConsistentCasingInFileNames": true,
"moduleResolution": "node",
"useDefineForClassFields": false,
"moduleResolution": "node",
```

- for new conf I copy what `ng create` do it ("skipLibCheck": true,  "isolatedModules": true, "moduleResolution": "bundler",)
- I didn't play with which conf prop broke
